<?php

use Zend\View\Renderer\PhpRenderer;
use Application\Entity\Db\MailConfirmation;

/**
 * @var PhpRenderer            $this
 * @var string $destinataire
 * @var string $titre
 * @var string $corps
 */

$this->redirect()->toRoute('these');

?>

<h1> Envoie du mail de confirmation </h1>

<?php


echo "<dl>";
echo "<dt>";
echo "Destinataire";
echo "</dt>";
echo "<dd>";
echo $destinataire;
echo "</dd>";
echo "<dt>";
echo "Titre";
echo "</dt>";
echo "<dd>";
echo $titre;
echo "</dd>";
echo "<dt>";
echo "Corps";
echo "</dt>";
echo "<dd>";
echo $corps;
echo "</dd>";
echo "</dl>";


