<?php

use Zend\View\Renderer\PhpRenderer;
use Application\Entity\Db\MailConfirmation;

/**
 * @var PhpRenderer            $this
 * @var MailConfirmation       $mailConfirmation
 */

?>

<h1> Envoie du mail de confirmation </h1>

<?php

$confirm = $this->url('mail-confirmation-reception', ['id' => $mailConfirmation->getId(), 'code' => $mailConfirmation->getCode()], [] , true);
$destinataire = $mailConfirmation->getIndividu()->getPrenom1() ." ". $mailConfirmation->getIndividu()->getNomUsuel() . " " . "&lt;<tt>".$mailConfirmation->getEmail()."</tt>&gt;";
$titre = "[SyGAL] Confirmation de votre email";
$corps = "<br/>"
        ."&nbsp;&nbsp;&nbsp;&nbsp;Bonjour,<br/><br/>"
        ."Pour finaliser l'enregistrement de votre email professionelle veuillez confirmer celui-ci en cliquant sur le liens suivant :<br/>"
        ."<a href='".$confirm."'>".$confirm."</a><br/><br/>"
        ."Une fois confirmé, cet email sera utilisé pour recevoir les notifications de SyGAL et vous permettera de vous connecter à SyGAL.";

echo "<dl>";
echo "<dt>";
echo "Destinataire";
echo "</dt>";
echo "<dd>";
echo $destinataire;
echo "</dd>";
echo "<dt>";
echo "Titre";
echo "</dt>";
echo "<dd>";
echo $titre;
echo "</dd>";
echo "<dt>";
echo "Corps";
echo "</dt>";
echo "<dd>";
echo $corps;
echo "</dd>";
echo "</dl>";


