<?php

use Zend\View\Renderer\PhpRenderer;
use Application\Entity\Db\MailConfirmation;

/**
 * @var PhpRenderer      $this
 * @var MailConfirmation $mailConfirmation
 */
?>

<h1 class="page-header"> Adresse électronique de contact</h1>

<?php if ($mailConfirmation->isConfirmer()): ?>
    <p>
        <?php
        $message = sprintf("Votre adresse électronique <strong>%s</strong> est maintenant confirmée, merci.", $mailConfirmation->getEmail());
        echo $this->messenger()->setMessage($message, \UnicaenApp\View\Helper\Messenger::SUCCESS);
        ?>
    </p>
    <p>
        <a href="<?php echo $this->url('home', [], [], true) ?>">
            <input type='button' class='btn btn-info' value="Retour à l'acceuil de SyGAL">
        </a>
    </p>
<?php else: ?>
    <p>
        Votre adresse électronique n'a pas pu être confirmée, êtes-vous sûr d'avoir cliqué sur le bon lien ?
    </p>
<?php endif ?>

