<?php

use Zend\View\Renderer\PhpRenderer;
use Application\Entity\Db\MailConfirmation;

/**
 * @var PhpRenderer      $this
 * @var MailConfirmation $mailConfirmation
 */
?>

<h1 class="page-header"> Confirmation de l'email professionnelle </h1>


<?php if ($mailConfirmation->isConfirmer()): ?>
    <p>
        Votre adresse <strong><?php echo $mailConfirmation->getEmail() ?></strong> est maintenant confirmée, merci.
    </p>
    <p>
        <a href="<?php echo $this->url('home', [], [], true) ?>">
            <input type='button' class='btn btn-info' value="Retour à l'acceuil de SyGAL">
        </a>
    </p>
<?php else: ?>
    <p>
        Votre adresse mail n'a pas pu être confirmé, êtes-vous sûr d'avoir cliqué sur le bon lien ?
    </p>
<?php endif ?>

