<?php

use Application\View\Renderer\PhpRenderer;
use Substitution\Controller\SubstitutionController;
use UnicaenPrivilege\Guard\PrivilegeController;

/**
 * @var PhpRenderer $this
 * @var string $type
 * @var \Doctrine\DBAL\Result $result
 * @var int $count
 * @var int $count
 * @var string[] $npdAttributes [name => label]
 *
 * @see \Substitution\Controller\SubstitutionController::listerAction()
 */

$canEdit = $this->isAllowed(PrivilegeController::getResourceId(SubstitutionController::class, 'modifier'));
?>

<?php $this->headTitle($this->translate("Substitutions existantes : $type")) ?>

<h1 class="page-header">
    <span class="fas fa-object-group"></span>
    <?php echo $this->translate("Substitutions existantes") ?> <span class="badge bg-primary text-uppercase p-1"><?php echo $type ?></span>
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace(); ?>

<?php if ($resultCount = $result->rowCount()): ?>
    <p>
        <?php echo $count ?> substituants trouvés.
        <?php if ($count > $resultCount): ?>
            <strong>Liste tronquée à <?php echo $resultCount ?>.</strong>
        <?php endif; ?>
    </p>

    <table class="table table-bordered table-extra-condensed">
        <tr>
            <th rowspan="2">NPD</th>
            <th colspan="2">Substituant</th>
            <th rowspan="2">Substitués</th>
            <th rowspan="2"></th>
        </tr>
        <tr>
            <th>Id</th>
            <th><?php echo implode(', ', $npdAttributes) ?></th>
        </tr>
        <?php while ($row = $result->fetchAssociative()): ?>
            <?php
            $fromIds = array_map('trim', explode('|', $row['from_ids']));
            $fromSources = array_combine($fromIds, array_map('trim', explode('|', $row['from_sources'])));
            $npdForces = array_combine($fromIds, array_map('trim', explode('|', $row['from_npd_forces'])));
            $npdCalcules = array_combine($fromIds, array_map('trim', explode('|', $row['from_npd_calcs'])));
            $datesCreations = array_combine($fromIds, array_map('trim', explode('|', $row['from_dates_creations'])));
            ?>
            <tr>
                <td>
                    <a href="<?php echo $this->url('substitution/substitution/voir', ['type' => $type, 'id' => $row['to_id']]) ?>"
                       title="Accéder aux détails de cette substitution">
                        <?php echo $row['npd'] ?></a>
                </td>
                <td>
                    <?php echo $row['to_id'] ?>
                    <?php if ($row['est_substituant_modifiable'] === false): ?>
                        <span class="badge bg-secondary substitue"
                              title="La mise à jour automatique des attributs de ce substituant à partir de ceux des substitués est désactivée">
                            <i class="fas fa-lock"></i>
                        </span>
                    <?php endif; ?>
                </td>
                <td>
                    <?php echo implode(', ', array_map(fn($name) => $row[$name], array_keys($npdAttributes))) ?>
                </td>
                <td class="d-flex flex-row">
                    <?php foreach ($fromIds as $id): ?>
                        <div class="substitue px-1">
                            <?php echo $id ?>
                            <?php if ($npdForces[$id]): ?>
                                <?php echo $this->partial('substitution/substitution/_partial/badge-substitue-force', ['npdForce' => $npdForces[$id]]); ?>
                            <?php endif; ?>
                            <p class="complement-substitue">
                                <span title="Source <?php echo $s = $fromSources[$id] ?>"><?php echo $s ?></span><br>
                                <span title="Ajouté le <?php echo $d = $datesCreations[$id] ?>"><?php echo $d ?></span>
                            </p>
                        </div>
                    <?php endforeach; ?>

                    <?php if ($canEdit): ?>
                        <a href="<?php echo $this->url('substitution/substitution/voir/modifier', ['type' => $type, 'id' => $row['to_id']]) ?>"
                           title="Modifier cette substitution"
                           class="ms-auto align-self-center"><span class="icon icon-modifier"></span></a>
                    <?php endif; ?>
                </td>
                <td>
                </td>
            </tr>
        <?php endwhile ?>
    </table>
<?php else: ?>
    <p>Aucune.</p>
<?php endif ?>
