
<?php
/**
 * @var \Application\View\Renderer\PhpRenderer $this
 * @var string $type
 * @var array $substitution
 * @var \Substitution\Entity\Db\SubstitutionAwareEntityInterface $substituant
 * @var ?\Substitution\Entity\Db\SubstitutionAwareEntityInterface[] $substitues
 * @var string[] $npdAttributes [name => label]
 *
 * @var string $informationPartial
 * @var bool $includeGotoDetailsLink
 *
 * @see \Substitution\Controller\SubstitutionController::modifierAction()
 */

use Ramsey\Uuid\Uuid;
use UnicaenApp\Form\Element\SearchAndSelect;

$fromDatesCreations = array_combine(array_keys($substitues), explode('|', $substitution['from_dates_creations']));
$fromNpdCalcules = array_combine(array_keys($substitues), explode('|', $substitution['from_npd_calcs']));
$fromNpdForces = array_combine(array_keys($substitues), explode('|', $substitution['from_npd_forces']));
$fromSources = array_combine(array_keys($substitues), explode('|', $substitution['from_sources']));

$autocompleteUrl = $this->url('substitution/substitution/voir/rechercher-substituable',
    ['type' => $type, 'id' => $substituant->getId()], [], true);

$modifierSubstituantUrl = $this->url('substitution/substitution/voir/modifier-substituant',
    ['type' => $type, 'id' => $substituant->getId(), 'substituantId' => $substituant->getId()], [], true);

$uidSubstitue = Uuid::uuid1();
$voirSubstitueUrl = $this->url('substitution/substitution/voir-substituable',
    ['type' => $type, 'substituableId' => $uidSubstitue/*temporaire*/], [], true);
?>

<?php echo $this->messenger()->setMessagesFromFlashMessengerWithNoNamespace() ?>

<h1 class="page-header">
    Modification de la substitution
    <span class="badge bg-primary text-uppercase p-1"><?php echo $type ?></span>
    <code><abbr title="NPD"><?php echo $substitution['npd'] ?></abbr></code>
</h1>

<?php if (count($substitues) === 1): ?>
    <p class="alert alert-danger">
        <span class="icon icon-attention"></span> <strong>Votre attention, svp !</strong>
        <?php echo \Substitution\Constants::ALERTE_1_SEUL_SUBSTITUE ?>
    </p>
<?php endif; ?>

<p class="lead">

</p>

<div class="row align-items-start">
    <div class="col col-md-9">
        <h2>
            Substitution actuelle
        </h2>
        <div class="filler">
            <p>
                <?php echo count($substitues) ?> enregistrements substitués.
            </p>
        </div>
        <div class="row align-items-start">
            <div class="col">
                <?php echo $this->partial('substitution/substitution/_partial/substituant', [
                    'type' => $type,
                    'substituant' => $substituant,
                    'npdAttributes' => $npdAttributes,
                    'canEdit' => true,
                    'informationPartial' => $informationPartial,
                    'includeGotoDetailsLink' => true,
                ]) ?>
            </div>
            <?php foreach ($substitues as $id => $substitue): ?>
                <div class="col px-1">
                    <?php
                    echo $this->partial('substitution/substitution/_partial/substitue', [
                        'substitue' => $substitue,
                        'npdAttributes' => $npdAttributes,
                        'id' => $id,
                        'fromSource' => $fromSources[$id],
                        'fromDateCreation' => $fromDatesCreations[$id],
                        'fromNpdCalcule' => $fromNpdCalcules[$id],
                        'fromNpdForce' => $fromNpdForces[$id],
                        'informationPartial' => $informationPartial,
                        'includeGotoDetailsLink' => true,
                    ]);
                    $estSubstitueManuellement = !empty($fromNpdForces[$id]) && $fromNpdForces[$id] === $substitution['npd'];
                    ?>
                    <form method="post" action="<?php echo $this->url('substitution/substitution/voir/retirer-substitue', ['type' => $type, 'id' => $substituant->getId()]) ?>">
                        <input type="hidden" value="<?php echo $substitue->getId() ?>" name="substitue"/>
                        <?php if (count($substitues) > 1): ?>
                            <?php if ($estSubstitueManuellement): ?>
                                <input type="submit" value="Retirer"
                                       title="Retirer de la substitution cet enregistrement ajouté manuellement"
                                       class="btn btn-warning float-end"
                                       onclick="return confirm('Êtes-vous certain·e de vouloir retirer cet enregistrement ?')"/>
                            <?php else: ?>
                                <input type="submit" value="Retirer ce faux doublon"
                                       title="Retirer de la substitution cet enregistrement car vous estimez que c'est un faux doublon"
                                       class="btn btn-danger float-end"
                                       onclick="return confirm('Êtes-vous certain·e de vouloir retirer ce faux doublon ?')"/>
                            <?php endif ?>
                        <?php else: ?>
                            <input type="submit" value="Impossible de retirer l'unique enregistrement substitué"
                                   class="btn btn-danger float-end disabled"
                                   onclick="return false"/>
                        <?php endif ?>
                    </form>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="col col-md-3">
        <h2>
            Enregistrement à ajouter
        </h2>
        <form method="post" class="substituable"
              action="<?php echo $this->url('substitution/substitution/voir/ajouter-substitue', ['type' => $type, 'id' => $substitution['to_id']]) ?>">
            <div class="filler">
                <?php
                $sas = new SearchAndSelect('substituable');
                $sas->setAttributes(['id' => 'sas', 'placeholder' => "Entrez au moins 2 caractères", 'tabindex' => 1])
                    ->setAutocompleteSource($autocompleteUrl);
                echo $this->formControlGroup($sas);
                ?>
            </div>
            <div class="selection" data-url="(générée en fonction de la sélection)">
                <!-- contenu dynamique -->
            </div>
            <div class="controls" style="display: none;">
                <input type="submit" value="Ajouter" class="btn btn-success"
                       title="Ajouter cet enregistrement à la substitution"
                       onclick="return confirm('Êtes-vous certain·e de vouloir ajouter manuellement cet enregistrement à cette substitution ?')"><br>
                <input type="reset" value="Annuler"
                       title="Abandonner l'ajout de cet enregistrement"
                       class="btn btn-outline-secondary float-end">
            </div>
        </form>
    </div>
</div>


<script>
    $(function () {
        /**
         * Gestion du formulaire de recherche/ajout d'un substitué.
         */
        let $sas = $("#sas-autocomplete");
        $sas.on("autocompleteselect", function (source, selected) {
            $("body").addClass("loading");
            let url = "<?php echo $voirSubstitueUrl ?>".replace('<?php echo $uidSubstitue ?>', selected.item.id);
            $("form .selection").data('url', url).refresh(null, function() {
                $("form .selection, form .controls").show('slide', { direction: "up" });
                $("body").removeClass("loading");
            });
        }).on("autocompletesearch", function (source) {
            $("form .selection, form .controls").hide();
        });
        $("form.substituable").on('reset', function() {
            $sas.focus();
            $("form .selection, form .controls").hide('slide', { direction: "up" });
        });

        /**
         * Gestion du formulaire de modification du substituant.
         */
        $("[name=majAutomatiqueSubstituant]").on('change', function(event) {
            $("form.substituant").submit();
        });

        /**
         * Pour tous les formulaires.
         */
        $("form").on('submit', function() {
            $("body").addClass("loading");
        });
    });
</script>

<style>
    div.filler {
        min-height: 40px;
    }
</style>
