<?php

use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var \Doctrine\DBAL\Result $result
 * @var string $type
 */
?>

<?php $this->headTitle($this->translate("Clés étrangères : $type")) ?>

<h1 class="page-header">
    <span class="fas fa-key"></span>
    <?php echo $this->translate("Clés étrangères") ?> <span class="badge bg-primary text-uppercase p-1"><?php echo $type ?></span>
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace(); ?>

<p class="lead">
    Voici la liste des clés étrangères prises en charge par le mécanisme de substitution automatique.
    Lorsqu'une substitution est créée, ces clés étrangères sont mises à jour automatiquement :
    tous les id des substitués sont remplacés par l'id du substituant.
</p>

<?php if ($count = $result->rowCount()): ?>
    <p><?php echo $count ?> clés étrangères trouvées.</p>

    <table class="table table-bordered table-extra-condensed">
        <tr>
            <th>Table</th>
            <th>Colonne</th>
        </tr>
        <?php while ($row = $result->fetchAssociative()): ?>
            <tr>
                <td><?php echo $row['source_table'] ?></td>
                <td><?php echo $row['fk_column'] ?></td>
            </tr>
        <?php endwhile ?>
    </table>
<?php else: ?>
    <p>Aucune.</p>
<?php endif ?>
