<?php
/**
 * @var \Application\Entity\Db\Rapport $rapport
 * @var \Application\Form\Rapport\RapportAvisForm $form
 */

$form->prepare();
?>

<?php $this->headTitle($this->translate($title = "Rapports d'activité"))
    ->prepend("Nouvel avis")
    ->prepend($rapport->getThese()->getDoctorant()->getIndividu()->getNomUsuel()) ?>

<h1 class="page-header">Nouvel avis à propos d'un rapport</h1>

<dl>
    <dt>Rapport :</dt>
    <dd><?php echo $rapport ?></dd>
</dl>

<?php echo $this->form()->openTag($form) ?>
<div class="row">
    <div class="col-md-4">
        <?php echo $this->formControlGroup($form->get('avis')) ?>
    </div>
</div>
<div class="row">
    <div class="col-md-7">
        <?php
        echo $this->formControlGroup($form->get('commentaires'));
        echo $this->formControlGroup($form->get('security'));
        echo $this->formControlGroup($form->get('submit'));
        ?>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>