<?php

use Application\Entity\Db\FichierThese;
use Application\Entity\Db\NatureFichier;
use Application\Entity\Db\These;
use Application\Entity\Db\VersionFichier;
use Application\Provider\Privilege\FichierPrivileges;
use Application\Provider\Privilege\ThesePrivileges;
use Application\View\Renderer\PhpRenderer;
use Zend\Form\Element\Hidden;

/**
 * @var PhpRenderer    $this
 * @var These          $these
 * @var string         $uploadUrl
 * @var string         $annexesListUrl
 * @var NatureFichier  $nature
 * @var VersionFichier $versionFichier
 */

$canEdit = $this->isAllowed($these, FichierPrivileges::privilegeTeleverserFor($nature, $versionFichier));

$uploader = $this->uploader()->setUrl($uploadUrl);

$maxFileCountAutres = 50;

//$hasFichierThese = $these->getFichiersBy(false, false, false)->count() > 0;
//$hasFichiersAnnexesThese = $these->getFichiersBy(true, false, false)->count() > 0;
?>

<h3 class=""><?php echo $titre ?></h3>

<p class="help-block">
    Vérifiez la liste des formats  acceptés sur le site <a href="https://facile.cines.fr">https://facile.cines.fr</a>.
</p>

<?php if ($hasFichierThese || $hasFichiersAnnexesThese): ?>

    <div class="_row autres widget-uploader" id="uploader-div-autres">
        <div class="_col-md-7 pre-scrollable">
            <!-- Liste des fichiers déposés -->
            <?php echo $uploader->renderUploadedFiles($annexesListUrl, "Fichiers téléversés :") ?>
        </div>
        <div class="_col-md-5 upload-form">
            <!-- formulaire de dépôt -->
            <?php if ($canEdit): ?>
                <?php
                $form = $uploader->getForm(); // NB: même instance de formulaire qu'au-dessus
                $form->get('files')->setLabel("")->setAttribute('multiple', true)->setAttribute('accept', null);
                $form->addElement((new Hidden('annexe'))->setValue(1));
                echo $uploader->renderForm();
                ?>
                <div class="clearfix"></div>
                <div class="text-sm text-info" style="margin-top: 8px; max-width: 250px">
                    <strong>NB: </strong> <?php echo FichierThese::MESSAGE_DEPOT_DUREE ?>
                </div>
            <?php endif ?>
        </div>
    </div>

<?php else: ?>

    Vous devez d'abord téléverser la thèse au format PDF.

<?php endif ?>



<script>

    $(function () {
        var maxFileCountAutres = <?php echo $maxFileCountAutres ?>;
        var eventNames = "upload-event-files-listed upload-event-file-deleted upload-event-file-uploaded";

        // Un fichier vient d'être déposé ou supprimé, ou la liste des fichiers a été actualisée.
        $("body").on(eventNames, ".autres.widget-uploader", function(event, data) {
            var uploadContainer = $(data[0]);
            updateUploadForm(uploadContainer);
        });

        /**
         * Compte le nombre de fichiers déjà déposés et masque le formulaire de dépôt si le maximum est atteint.
         *
         * @param uploadContainer
         */
        function updateUploadForm(uploadContainer) {
            var fichiersCount = uploadContainer.find(".uploaded-files-div ul li").length;
            var div = uploadContainer.find("div.upload-form");

            if (fichiersCount >= maxFileCountAutres) {
                div.hide('fade');
            }
            else {
                div.show('fade');
            }
        }
    });
</script>