<?php

use Application\Assertion\BaseAssertion;
use Application\Entity\Db\Etablissement;
use Application\Entity\Db\NatureFichier;
use Application\Entity\Db\These;
use Application\Entity\Db\VersionFichier;
use Application\Provider\Privilege\ThesePrivileges;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer    $this
 * @var These          $these
 * @var string         $info
 * @var string         $uploadUrl
 * @var string         $theseListUrl
 * @var NatureFichier  $nature
 * @var VersionFichier $versionFichier
 * @var Etablissement  $etabComue
 */

$maintenant = new DateTime();
$soutenance = $these->getDateSoutenance();

$privilege = ThesePrivileges::privilegeDeposerFor($nature, $versionFichier);
$canEdit = $this->isAllowed($these, $privilege);

$uploader = $this->uploader()->setUrl($uploadUrl);

$maxFileCountThese = 1;
?>

<h3 class=""><?php echo $titre ?></h3>

<?php if (isset($info)): ?>
<div class="alert alert-md alert-danger">
    <span class="glyphicon glyphicon-exclamation-sign"></span> <?php echo $info ?>
</div>
<?php endif ?>


<?php echo $this->partial('application/these/depot/partial/fichier', [
    'canUpload'               => $canEdit,
    'class'                   => 'these',
    'uploadUrl'               => $uploadUrl,
    'uploadedFilesListUrl'    => $theseListUrl,
    'maxUploadableFilesCount' => $maxFileCountThese,
]);
?>

<div class="alert alert-sm alert-warning">
    <p>
        <span class="glyphicon glyphicon-warning-sign"></span> Les modèles de page de couverture des thèses de
        <?php echo $etabComue ?> doivent être rigoureusement respectés.
    </p>
    <p>
        Ils sont obligatoires pour le dépôt numérique de la thèse dans <?php echo $this->appInfos()->nom ?> pour archivage et diffusion.
        Sur la page de 4e de couverture, les informations obligatoires sont : titre, mots clés et résumé en français et en anglais.
    </p>
    <p>
        Téléchargez les modèles de page de couverture
        <a href="http://recherche.unicaen.fr/etudes-doctorales/soutenir-sa-these/modeles-de-page-de-couverture-de-these-normandie-universite-844344.kjsp?RH=1275467239552"
           target="_blank">sur cette page</a>.
    </p>
</div>


<?php
$msgCollector = $this->messageCollector(BaseAssertion::class);
$msgCollector->getMessengerHelper()->setContainerClassesToAdd('alert-sm');
echo $msgCollector->render();
?>
