<?php

use Application\Assertion\BaseAssertion;
use Application\Entity\Db\Etablissement;
use Application\Entity\Db\NatureFichier;
use Application\Entity\Db\These;
use Application\Entity\Db\VersionFichier;
use Application\Provider\Privilege\FichierPrivileges;
use Application\Provider\Privilege\ThesePrivileges;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer    $this
 * @var These          $these
 * @var string         $info
 * @var string         $uploadUrl
 * @var string         $theseListUrl
 * @var NatureFichier  $nature
 * @var VersionFichier $versionFichier
 */

$maintenant = new DateTime();
$soutenance = $these->getDateSoutenance();

$privilege = FichierPrivileges::privilegeTeleverserFor($nature, $versionFichier);
$canEdit = $this->isAllowed($these, $privilege);

$uploader = $this->uploader()->setUrl($uploadUrl);

$maxFileCountThese = 1;
?>

<h3 class=""><?php echo $titre ?></h3>

<?php if (isset($info)): ?>
<div class="alert alert-md alert-danger">
    <span class="glyphicon glyphicon-exclamation-sign"></span> <?php echo $info ?>
</div>
<?php endif ?>


<?php echo $this->partial('application/these/depot/partial/fichier', [
    'canUpload'               => $canEdit,
    'class'                   => 'these',
    'uploadUrl'               => $uploadUrl,
    'uploadedFilesListUrl'    => $theseListUrl,
    'maxUploadableFilesCount' => $maxFileCountThese,
]);
?>

<div class="alert alert-sm alert-warning">
    <p>
        <span class="glyphicon glyphicon-warning-sign"></span> Le manuscrit que vous devez déposer ne doit pas contenir de page de couverture.
        La page de couverture est générée automatiquement et sera ajoutée automatiquement à votre manuscrit de thèse.
    </p>
    <p>
        La page de 4e de couverture doit contenir les informations suivantes : titre, mots clefs et résumé en français et en anglais.
        Ces informations sont obligatoires pour le dépôt numérique de la thèse dans <?php echo $this->appInfos()->nom ?> pour archivage et diffusion.
    </p>
</div>


<?php
$msgCollector = $this->messageCollector(BaseAssertion::class);
$msgCollector->getMessengerHelper()->setContainerClassesToAdd('alert-sm');
echo $msgCollector->render();
?>
