<?php

use Application\Provider\Privilege\SubstitutionPrivileges;

$canSubstitutionAutomatique = $this->isAllowed(SubstitutionPrivileges::getResourceId(SubstitutionPrivileges::SUBSTITUION_AUTOMATIQUE));
?>

<?php $this->headTitle($this->translate("Substitution de structures")) ?>

<h1 class="page-header first">
    <?php echo $this->translate("Substitution  de structures"); ?>
</h1>

<?php
$messenger = $this->messenger();
echo $messenger->addMessagesFromFlashMessenger();
?>

<?php if($canSubstitutionAutomatique): ?>
    <p>
        <a href="<?php echo $this->url('substitution-automatique', [], [], true);?>" title="Recherche automatique de substitution">
            <button class="btn btn-primary"><span class="glyphicon glyphicon-cog"></span> Recherche automatique de substitutions </button>
        </a>
    </p>
<?php endif; ?>

<div id="ecole-doctorale"> </div>
<div id="etablissement"> </div>
<div id="unite-recherche"> </div>



<script>
    $(document).ready(function() {
        loadSubstitution("ecole-doctorale");
        loadSubstitution("etablissement");
        loadSubstitution("unite-recherche");



        $("body").on("edition-substitution", function(event, data) {
            console.log("With args : ", data);
            event.div.modal('hide'); // ferme la fenêtre modale
            var type = data[0].value;
            loadSubstitution(type);

        })
        .on("click", "span#detruire", function() {
            var id = $(this).attr("ref");
            var type = $(this).attr("type");
            var url = "detruire/" + id;
            $.ajax({
                url : url,
                beforeSend:
                    function () {
                        $("#" + type).html('<span class="waiting">Chargement des substitutions ...</span>');
                    },
                success:
                    function(retour) {
                        loadSubstitution(type);
                    }
            });

        });
    });

    function loadSubstitution(type) {
        var url = "index-structure/" + type;
        $.ajax({
            url : url,
            beforeSend:
                function () {
                    $("#" + type).html('<span class="waiting">Chargement des substitutions ...</span>');
                },
            success:
                function(retour){
                    $("#" + type).html(retour);
                }
        });
    }
</script>