<?php

use Application\Entity\Db\Etablissement;

/**
 * Variables remontant du controleur
 * @var Etablissement   $nouvelEtablissement ==> l'etablissement qui va regrouper les établissements
 * @var Etablissement[] $selectedEtablissements ==> la liste des établissements sélectionnés
 * @var Etablissement[] $etablissements ==> la liste des établissements triés
 */
?>

<?php $this->headTitle($this->translate("Substitution d'établissements")) ?>

<h1 class="page-header first">
    <?php echo $this->translate("Substitution d'établissements"); ?>
    <span class="badge"><?php echo $nouvelEtablissement->getSigle(); ?></span>
</h1>

<div class="pull-left">
<?php
    foreach($selectedEtablissements as $selectedEtablissement) {
        echo generateDivEtablissement($selectedEtablissement);
    }
?>
</div>

<div class="pull-right">
    <?php
    echo generateDivSubstitution($nouvelEtablissement);
    ?>
</div>

<?php
function generateDivEtablissement(Etablissement $etablissement) {
    $texte =    "";
    $texte .=   "<div class='etablissement bg-warning'>";

    $texte .= "<div id='logo-div' class='pull-right'>";
    if ($etablissement->getCheminLogo() !== null) {
        $texte .= "<input id='Logo_" . $etablissement->getSigle() . "' type='radio' name='logo' /> &nbsp; ";
    }
    $texte .= "<img style='max-width: 125px; max-height: 125px; border: 1px solid black; background-color: white;' src='data:image/png;base64," . base64_encode($etablissement->getLogoContent()) ."'/>";
    $texte .= "</div>";

    $texte .= $etablissement->getSource() ."/". $etablissement->getId() . " " . $etablissement->getCode() ;
    $texte .=   "<br/>";

    $texte .= "<span>";
    $texte .= "<input id='Sigle_".$etablissement->getSigle()."' type='radio' name='sigle'/> &nbsp; ";
    $texte .= "<span class='texte'>" . $etablissement->getSigle() ."</span>";
    $texte .= "</span>";

    $texte .=   "<br/>";

    $texte .= "<span>";
    $texte .= "<input id='Libelle_".$etablissement->getSigle()."' type='radio' name='libelle'/> &nbsp; ";
    $texte .= "<span class='texte'>" . $etablissement->getLibelle() . "</span>";
    $texte .= "</span>";

    $texte .=   "</div>";
    return $texte;
}

function generateDivSubstitution($etablissement) {
    $texte =    "";
    $texte .=   "<div class='etablissement bg-info'>";

    $texte .= "<div id='logo-div' class='pull-right'>";
    $texte .= "<img style='max-width: 125px; max-height: 125px; border: 1px solid black; background-color: white;' src='data:image/png;base64," . base64_encode($etablissement->getLogoContent()) ."'/>";
    $texte .= "</div>";

    $texte .= $etablissement->getSource() ."/". $etablissement->getId() . " " . $etablissement->getCode() ;
    $texte .=   "<br/>";

    $texte .= "<input type='text' id='Sigle'/>";
    $texte .=   "<br/>";

    $texte .= "<input type='text' id='Libelle'/>";

    $texte .=   "</div>";
    return $texte;
}
?>

<style>
    div.etablissement {
        margin: 5px;
        padding: 5px;
        border: 2px gray solid;
        border-radius: 5px;
        width: 400px;
        height: 150px;
    }
</style>


<script>
    $(document).ready(function(){

        $("input[type='radio']").click(function() {
            var id = $(this).attr('id');
            var type= id.split("_")[0];

            //remplacement in the target
            var texte =  ($(this).parent().find(".texte").text());
             $('input[id='+type+']').val( texte );

        });

    });
</script>