<?php

/**
 * Array(identifiant => EcoleDoctorale[]) $substitutionsEcolesDoctorales
 * Array(identifiant => Etablissement[]) $substitutionsEtablissements
 * Array(identifiant => UniteRecherche[]) $substitutionsUnitesRecherches
 */

use Application\Entity\Db\TypeStructure;

?>

<?php $this->headTitle($this->translate("Substitutions automatiques")) ?>


<h1 class="page-header first">
    Substitutions automatiques
</h1>

<h2>
    Substitutions d'écoles doctorales
    <span class="badge"><?php echo count($substitutionsEcolesDoctorales); ?></span>
</h2>

<?php foreach ($substitutionsEcolesDoctorales as $identifier => $substitution) : ?>
    <div id="<?php echo TypeStructure::CODE_ECOLE_DOCTORALE; ?>_<?php echo $identifier; ?>">
    </div>
<?php endforeach; ?>


<h2>
    Substitutions d'établissements
    <span class="badge"><?php echo count($substitutionsEtablissements); ?></span>
</h2>

<?php foreach ($substitutionsEtablissements as $identifier => $substitution) : ?>
    <div id="<?php echo TypeStructure::CODE_ETABLISSEMENT; ?>_<?php echo $identifier; ?>">
    </div>
<?php endforeach; ?>


<h2>
    Substitutions d'unités de recherche
    <span class="badge"><?php echo count($substitutionsUnitesRecherches); ?></span>
</h2>

<?php foreach ($substitutionsUnitesRecherches as $identifier => $substitution) : ?>
    <div id="<?php echo TypeStructure::CODE_UNITE_RECHERCHE; ?>_<?php echo $identifier; ?>">
    </div>
<?php endforeach; ?>


<script>
    $(document).ready(function() {
        <?php foreach ($substitutionsEcolesDoctorales as $identifier => $substitution) : ?>
            loadSubstitutionByIdentifiant("ecole-doctorale", "<?php echo $identifier; ?>");
        <?php endforeach; ?>
        <?php foreach ($substitutionsEtablissements as $identifier => $substitution) : ?>
            loadSubstitutionByIdentifiant("etablissement", "<?php echo $identifier; ?>");
        <?php endforeach; ?>
        <?php foreach ($substitutionsUnitesRecherches as $identifier => $substitution) : ?>
            //loadSubstitutionByIdentifiant("unite-recherche", "<?php //echo $identifier; ?>//");
        <?php endforeach; ?>

        $("body")
            .on("click","button.btn-danger", function() {
                var id = $(this).attr("id").split("_");
                var type = id[1];
                var identifiant = id[2];
                $("div[id='div_"+type+ "_" + identifiant +"']").hide();
        });

        $("body")
            .on("click","button.btn-success", function() {
                var id = $(this).attr("id").split("_");
                var type = id[1];
                var identifiant = id[2];

                var url = "automatique/enregistrer/" + type + "/" + identifiant;
                $.ajax({
                    type: "POST",
                    url : url,
                    success:
                        function(retour){
                            $("div[id='div_"+type+ "_" + identifiant +"']").hide();
                        }
                });
            });

        $("body").on("edition-substitution", function(event, data) {
                // console.log("Event received : ", event);
                console.log("With args : ", data);
                event.div.modal('hide'); // ferme la fenêtre modale

                var type = data[0].value;
                var identifiant = data[1].value;
                console.log("FAIRE UN REFRESH " + type + " " + identifiant);
                loadSubstitutionByIdentifiant(type,identifiant);
            });
    });

    function loadSubstitutionByIdentifiant(type, identifiant) {
        var url = "automatique/afficher/" + type + "/" + identifiant;
        // console.log(url);
        $.ajax({
            type: "POST",
            url : url,
            success:
                function(retour){
                    $("div[id='"+type+ "_" +identifiant+"']").html(retour);
                }
        });

    }
</script>