<?php

/**
 * Array(identifiant => EcoleDoctorale[]) $substitutionsEcolesDoctorales
 * Array(identifiant => Etablissement[]) $substitutionsEtablissements
 * Array(identifiant => UniteRecherche[]) $substitutionsUnitesRecherches
 */

use Application\Entity\Db\TypeStructure;

?>

<?php $this->headTitle($this->translate("Substitutions automatiques")) ?>


<h1 class="page-header first">
    Substitutions automatiques
</h1>

<h2>
    Substitutions d'écoles doctorales
    <span class="badge"><?php echo count($substitutionsEcolesDoctorales); ?></span>
</h2>

<?php foreach ($substitutionsEcolesDoctorales as $identifier => $substitution) : ?>

    <div id="div_ed_<?php echo $identifier; ?>" class="panel panel-info">
        <div class="panel-heading">
            Substitution basé sur l'identitfiant <?php echo $identifier; ?>
        </div>
        <div class="panel-body">

            <div class="col-md-5">
                Substituées :
                <ol>
                    <?php foreach($substitution[0] as $structure): ?>
                        <li>
                            <?php echo $structure->getSourceCode(); ?>
                            -
                            <?php echo $structure->getLibelle(); ?>
                        </li>
                    <?php endforeach; ?>
                </ol>
            </div>
            <div class="col-md-5">
                Substituante :
                <?php if ($substitution[1] !== null): ?>
                <ul>
                    <li>
                        <?php echo $substitution[1]->getSourceCode(); ?>
                        -
                        <?php echo $substitution[1]->getLibelle(); ?>
                    </li>
                </ul>
                <?php endif ?>
            </div>
            <div class="col-md-2">
                <a href="<?php echo $this->url('substitution-automatique/modifier', ['type' => TypeStructure::CODE_ECOLE_DOCTORALE, 'identifiant' => $identifier], [], true); ?>">
                <button id="editer_ed_<?php echo $identifier; ?>" class="btn btn-info" style="width:95%;margin:2px;">
                    <span class="glyphicon glyphicon-pencil"></span>
                    Personnaliser
                </button>
                </a>
                <br/>
                <button id="valider_ed_<?php echo $identifier; ?>" class="btn btn-success" style="width:95%;margin:2px;">
                    <span class="glyphicon glyphicon-ok"></span>
                    Enregistrer
                </button>
                <br/>
                <button id="annuler_ed_<?php echo $identifier; ?>" class="btn btn-danger" style="width:95%;margin:2px;">
                    <span class="glyphicon glyphicon-remove"></span>
                    Masquer
                </button> <br/>
            </div>
        </div>
    </div>

<?php endforeach; ?>

<h2>
    Substitutions d'établissements
    <span class="badge"><?php echo count($substitutionsEtablissements); ?></span>
</h2>

<?php foreach ($substitutionsEtablissements as $identifier => $substitution) : ?>

    <div id="div_et_<?php echo $identifier; ?>" class="panel panel-info">
        <div class="panel-heading">
            Substitution basé sur l'identitfiant <?php echo $identifier; ?>
        </div>
        <div class="panel-body">

            <div class="col-md-5">
                Substituées :
                <ol>
                    <?php foreach($substitution[0] as $structure): ?>
                        <li>
                            <?php echo $structure->getSourceCode(); ?>
                            -
                            <?php echo $structure->getLibelle(); ?>
                        </li>
                    <?php endforeach; ?>
                </ol>
            </div>
            <div class="col-md-5">
                Substituante :
                <?php if ($substitution[1] !== null): ?>
                    <ul>
                        <li>
                            <?php echo $substitution[1]->getSourceCode(); ?>
                            -
                            <?php echo $substitution[1]->getLibelle(); ?>
                        </li>
                    </ul>
                <?php endif ?>
            </div>
            <div class="col-md-2">
                <a
                   data-event="edition-substitution"
                   href="<?php echo $this->url('substitution-automatique/modifier', ['type' => TypeStructure::CODE_ETABLISSEMENT, 'identifiant' => $identifier], [], true); ?>"
                   class="ajax-modal"
                >
                    <button id="editer_et_<?php echo $identifier; ?>" class="btn btn-info" style="width:95%;margin:2px;">
                        <span class="glyphicon glyphicon-pencil"></span>
                        Personnaliser
                    </button>
                </a>
                <br/>
                <button id="valider_et_<?php echo $identifier; ?>" class="btn btn-success" style="width:95%;margin:2px;">
                    <span class="glyphicon glyphicon-ok"></span>
                    Enregistrer
                </button>
                <br/>
                <button id="annuler_et_<?php echo $identifier; ?>" class="btn btn-danger" style="width:95%;margin:2px;">
                    <span class="glyphicon glyphicon-remove"></span>
                    Masquer
                </button> <br/>
            </div>
        </div>
    </div>

<?php endforeach; ?>


<h2>
    Substitutions d'unités de recherche
    <span class="badge"><?php echo count($substitutionsUnitesRecherches); ?></span>
</h2>

<?php foreach ($substitutionsUnitesRecherches as $identifier => $substitution) : ?>

    <div id="div_ur_<?php echo $identifier; ?>" class="panel panel-info">
        <div class="panel-heading">
            Substitution basé sur l'identitfiant <?php echo $identifier; ?>
        </div>
        <div class="panel-body">

            <div class="col-md-5">
                Substituées :
                <ol>
                    <?php foreach($substitution[0] as $structure): ?>
                        <li>
                            <?php echo $structure->getSourceCode(); ?>
                            -
                            <?php echo $structure->getLibelle(); ?>
                        </li>
                    <?php endforeach; ?>
                </ol>
            </div>
            <div class="col-md-5">
                Substituante :
                <?php if ($substitution[1] !== null): ?>
                    <ul>
                        <li>
                            <?php echo $substitution[1]->getSourceCode(); ?>
                            -
                            <?php echo $substitution[1]->getLibelle(); ?>
                        </li>
                    </ul>
                <?php endif ?>
            </div>
            <div class="col-md-2">
                <a href="<?php echo $this->url('substitution-automatique/modifier', ['type' => TypeStructure::CODE_UNITE_RECHERCHE, 'identifiant' => $identifier], [], true); ?>">
                    <button id="editer_ur_<?php echo $identifier; ?>" class="btn btn-info" style="width:95%;margin:2px;">
                        <span class="glyphicon glyphicon-pencil"></span>
                        Personnaliser
                    </button>
                </a>
                <br/>
                <button id="valider_ur_<?php echo $identifier; ?>" class="btn btn-success" style="width:95%;margin:2px;">
                    <span class="glyphicon glyphicon-ok"></span>
                    Enregistrer
                </button>
                <br/>
                <button id="annuler_ur_<?php echo $identifier; ?>" class="btn btn-danger" style="width:95%;margin:2px;">
                    <span class="glyphicon glyphicon-remove"></span>
                    Masquer
                </button> <br/>
            </div>
        </div>
    </div>

<?php endforeach; ?>
<script>
    $(document).ready(function() {


       $("button.btn-danger").click(function() {
           var id = $(this).attr("id");
           var splits = id.split("_");
           var type = splits[1];
           var number = splits[2];
          //alert("Click sur le bouton annuler ["+id+"]");
          $("div[id='div_"+type+ "_" +number+"']").hide();
       });


        $("button.btn-success").click(function() {
            var id = $(this).attr("id");
            var splits = id.split("_");
            var type = splits[1];
            var number = splits[2];
            // alert("Click sur le bouton valider ["+id+"]");

            if (type === "ed") type_c = "ecole-doctorale";
            if (type === "et") type_c = "etablissement";
            if (type === "ur") type_c = "unite-recherche";

            var url = "automatique/enregistrer/" + type_c + "/" + number;

            $.ajax({
                type: "POST",
                url : url,
                success:
                    function(retour){
                        $("div[id='div_"+type+ "_" +number+"']").hide();
                    }
            });

        });
        $("button.btn-info").click(function() {
            //var id = $(this).attr("id");
            // alert("Click sur le bouton editer ["+id+"]");
        });

        $("body").on("edition-substitution", function(event, data) {
            /**
             * event          : événement jQuery (cf. http://api.jquery.com/category/events/event-object/)
             *   event.type   : nom de l'événement ("save-message" dans cet exemple)
             *   event.div    : DIV correspondant à la fenêtre modale (objet jQuery)
             *   event.a      : lien hypertexte cliqué
             * data           : formulaire sérialisé en tableau à l'aide de jQuery.serializeArray()
             */
            console.log("Event received : ", event);
            console.log("With args : ", data);
            // ...
            event.div.modal('hide'); // ferme la fenêtre modale
        });
    });
</script>