<?php

namespace Substitution;

use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var \Doctrine\DBAL\Result $result
 *
 * @see \Substitution\Controller\IndexController::unite-rechAction()
 */
?>

<?php $this->headTitle($this->translate("Clés étrangères vers des unités de recherche")) ?>

<h1 class="page-header">
    <span class="fas fa-key"></span>
    <?php echo $this->translate("Clés étrangères vers des unités de recherche"); ?>
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace(); ?>

<?php echo $this->partial('substitution/foreign-key/_partial/liste', [
    'result' => $result,
]); ?>

