<?php
/**
 * @var AdmissionValidation $admissionValidation
 * @var array $messages
 *
 * @see \Admission\Notification\AdmissionValidationSupprimeeNotification
 */

use Admission\Entity\Db\AdmissionValidation;
use Application\Constants;

$admission = $admissionValidation->getAdmission();

$precisionDestructeur = '';
if (($admissionValidation->getHistoModificateur() ?: $admissionValidation->getHistoCreateur()) ===
    ($d = $admissionValidation->getHistoDestructeur())) {
    $precisionDestructeur = " par $d";
}
?>
    <p>
        Bonjour,
    </p>
    <p>
        Ceci est un mail envoyé automatiquement par l'application <?php echo $this->appInfos()->nom ?>.
    </p>
    <p>
        La <strong><?php echo lcfirst($admissionValidation->getTypeValidation()) ?></strong>
        du <strong><?php echo lcfirst($admission) ?></strong>
        de <strong><?php echo $admission->getIndividu() ?></strong>
        datant du
        <?php echo ($admissionValidation->getHistoModification() ?: $admissionValidation->getHistoCreation())->format(Constants::DATETIME_FORMAT) ?>
        a été <strong>annulée</strong><?php echo $precisionDestructeur ?>.
    </p>

<?php if ($messages): ?>
    Compléments :
    <ul>
        <?php foreach ((array)$messages as $severity => $message): ?>
            <li><?php echo implode ('<br>', (array)$message) ?></li>
        <?php endforeach; ?>
    </ul>
<?php endif ?>