<?php
/**
 * @var AdmissionValidation $admissionValidation
 *
 * @see \Admission\Notification\AdmissionValidationAjouteeNotification
 */

use Admission\Entity\Db\AdmissionValidation;
use Application\Constants;

$admission = $admissionValidation->getAdmission();
?>
<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application <?php echo $this->appInfos()->nom ?>.
</p>
<p>
    Le <strong><?php echo lcfirst($admission) ?></strong>
    de <strong><?php echo $admission->getIndividu() ?></strong>
    complété à la date du
    <?php echo ($admission->getHistoModification() ?: $admission->getHistoCreation())->format(Constants::DATETIME_FORMAT) ?>
    a été <strong>validé</strong> par
    <?php echo $admissionValidation->getHistoModificateur() ?: $admissionValidation->getHistoCreateur() ?>,
    le <?php echo ($admissionValidation->getHistoModification() ?: $admissionValidation->getHistoCreation())->format(Constants::DATETIME_FORMAT) ?>.
</p>
