<?php

use Individu\Entity\Db\Individu;
use Formation\Entity\Db\Session;
use UnicaenApp\Form\Element\SearchAndSelect;

/**
 * @see \Formation\Controller\InscriptionController::ajouterAction()
 * @var Session $session
 */

?>

<form method="post" action="<?php echo $this->url('formation/inscription/ajouter', ['session' => $session->getId()], [], true); ?>">
    <?php
    $sas = new SearchAndSelect('individu');
    $sas->setLabel($this->translate("Recherche d'un·e doctorant·e"));
    $sas->setAttribute('class', 'individu-finder');
    /** @see IndividuController::rechercherAction() */
    $sas->setAutocompleteSource($this->url('individu/rechercher', [], ['query' => ['type' => Individu::TYPE_DOCTORANT]], true));
    echo $this->formControlGroup($sas, 'formSearchAndSelect');
    ?>

    <button type="submit" value="Ajouter le doctorant" class="btn btn-primary">
        <span class="icon icon-ajouter"></span>
        Ajouter le doctorant
    </button>
</form>
