<?php

/**
 * @see \Formation\Controller\InscriptionController::indexAction()
 * @var Inscription[] $inscriptions
 */

use Formation\Entity\Db\Inscription;
use Formation\Provider\Privilege\InscriptionPrivileges;
use Formation\Provider\Privilege\SessionPrivileges;


$canVoirSession     = $this->isAllowed(SessionPrivileges::getResourceId(SessionPrivileges::SESSION_AFFICHER));

$canHistoriserInscription      = $this->isAllowed(InscriptionPrivileges::getResourceId(InscriptionPrivileges::INSCRIPTION_HISTORISER));
$canSupprimerInscription       = $this->isAllowed(InscriptionPrivileges::getResourceId(InscriptionPrivileges::INSCRIPTION_SUPPRIMER));
?>

<h1> Index des inscriptions </h1>

<table class="table table-condensed">
    <thead>
        <tr>
            <th>Identifiant</th>
            <th>Session</th>
            <th>Individu</th>
            <th>Liste</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($inscriptions as $inscription) : ?>
        <tr>
            <td> <?php echo $inscription->getId(); ?> </td>
            <td>
                <?php echo $inscription->getSession()->getId(); ?>
                <?php echo $inscription->getSession()->getModule()->getLibelle(); ?>
            </td>
            <td> <?php echo $inscription->getDoctorant()->getIndividu()->getNomComplet(); ?> </td>
            <td>
                <?php if ($inscription->isListePrincipale()) : ?>
                    <span class="liste-principale">
                        Principale
                    </span>
                <?php endif; ?>
                <?php if ($inscription->isListeComplementaire()) : ?>
                    <span class="liste-complementaire">
                        Complémentaire
                    </span>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($canVoirSession AND $inscription->getSession() !== null) : ?>
                    <?php /** @see \Formation\Controller\SessionController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('formation/session/afficher', ['session' => $inscription->getSession()->getId()], [], true); ?>"
                       title="Accéder à la session associée" data-toggle="tooltip" data-html="true"
                    >
                        <span class="glyphicon glyphicon-list-alt"></span>
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <?php if ($inscription->estNonHistorise()) : ?>
                        <?php /** @see \Formation\Controller\InscriptionController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('formation/inscription/historiser', ['inscription' => $inscription->getId()], [], true); ?>"
                           title="Historiser l'inscription" data-toggle="tooltip" data-html="true"
                        >
                            <span class="glyphicon glyphicon-trash"></span>
                        </a>
                    <?php else : ?>
                        <?php /** @see \Formation\Controller\InscriptionController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url('formation/inscription/restaurer', ['inscription' => $inscription->getId()], [], true); ?>"
                           title="Restaurer l'inscription" data-toggle="tooltip" data-html="true"
                        >
                            <span class="glyphicon glyphicon-leaf"></span>
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canSupprimer) : ?>
                    <?php /** @see \Formation\Controller\InscriptionController::supprimerAction() */?>
                    <a href="<?php echo $this->url('formation/inscription/supprimer',['inscription' => $inscription->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification"
                       title="Suppression de l'inscription de <?php echo $inscription->getDoctorant()->getIndividu()->getNomComplet(); ?>" data-toggle="tooltip" data-html="true">
                        <span class="glyphicon glyphicon-remove"></span>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>