<?php
    /**
     * @var \Laminas\Form\Form $form
     * @var bool $validationsDejaEffectuees
     */

    if(isset($validationsDejaEffectuees) && $validationsDejaEffectuees): ?>
        <div class="alert alert-warning">
            <span class="icon icon-attention"></span>
            En cas de modification de la proposition, toutes les validations seront annulées et la proposition devra être à nouveau
            validée.
        </div>
    <?php endif;
    echo $this->form($form);
?>

<script>
    $(document).ready(function() {
        $('select').selectpicker();
    });
    $(function () {
        $('[data-bs-toggle="tooltip"]').tooltip({});
    });
</script>