-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sygaldb.unicaen.fr;sid=SYGLPROD;port=1523

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW src_individu (id, source_code, source_id, type, supann_id, civilite, nom_usuel, nom_patronymique, prenom1, prenom2, prenom3, email, date_naissance, nationalite) AS SELECT 
  NULL                                     AS id,
  tmp.SOURCE_CODE,
  src.id                                   AS SOURCE_ID,
  TYPE,
  SUPANN_ID,
  civ                                      AS CIVILITE,
  lib_nom_usu_ind                          AS NOM_USUEL,
  lib_nom_pat_ind                          AS NOM_PATRONYMIQUE,
  lib_pr1_ind                              AS PRENOM1,
  lib_pr2_ind                              AS PRENOM2,
  lib_pr3_ind                              AS PRENOM3,
  EMAIL,
  dat_nai_per                              AS DATE_NAISSANCE,
  lib_nat                                  AS NATIONALITE
 FROM TMP_INDIVIDU tmp
       JOIN SOURCE src ON src.CODE = tmp.SOURCE_ID;

