-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sygaldb.unicaen.fr;sid=SYGLPROD;port=1523

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW v_diff_origine_financement (source_code, source_id, operation, u_code, u_libelle_court, u_libelle_long, s_code, s_libelle_court, s_libelle_long, d_code, d_libelle_court, d_libelle_long) AS with diff as (
        SELECT 
            coalesce(s.SOURCE_CODE, d.SOURCE_CODE) SOURCE_CODE,
            coalesce(s.source_id, d.source_id) source_id,

            case 
            when (s.SOURCE_CODE IS NOT NULL AND d.SOURCE_CODE IS NULL) then 'insert'
            when (s.SOURCE_CODE IS NOT NULL AND d.SOURCE_CODE IS NOT NULL and (d.HISTO_DESTRUCTION IS NULL or d.HISTO_DESTRUCTION > SYSDATE)) then 'update'
            when (s.SOURCE_CODE IS NOT NULL AND d.SOURCE_CODE IS NOT NULL and (d.HISTO_DESTRUCTION IS NOT NULL and d.HISTO_DESTRUCTION <= SYSDATE)) then 'undelete'
            when (s.SOURCE_CODE IS NULL AND d.SOURCE_CODE IS NOT NULL and (d.HISTO_DESTRUCTION IS NULL or d.HISTO_DESTRUCTION > SYSDATE)) then 'delete' end as operation,

            CASE WHEN d.CODE <> s.CODE OR (d.CODE IS NULL AND s.CODE IS NOT NULL) OR (d.CODE IS NOT NULL AND s.CODE IS NULL) THEN 1 ELSE 0 END as U_CODE,
    CASE WHEN d.LIBELLE_COURT <> s.LIBELLE_COURT OR (d.LIBELLE_COURT IS NULL AND s.LIBELLE_COURT IS NOT NULL) OR (d.LIBELLE_COURT IS NOT NULL AND s.LIBELLE_COURT IS NULL) THEN 1 ELSE 0 END as U_LIBELLE_COURT,
    CASE WHEN d.LIBELLE_LONG <> s.LIBELLE_LONG OR (d.LIBELLE_LONG IS NULL AND s.LIBELLE_LONG IS NOT NULL) OR (d.LIBELLE_LONG IS NOT NULL AND s.LIBELLE_LONG IS NULL) THEN 1 ELSE 0 END as U_LIBELLE_LONG,

            s.CODE AS S_CODE,
    s.LIBELLE_COURT AS S_LIBELLE_COURT,
    s.LIBELLE_LONG AS S_LIBELLE_LONG,

            d.CODE AS D_CODE,
    d.LIBELLE_COURT AS D_LIBELLE_COURT,
    d.LIBELLE_LONG AS D_LIBELLE_LONG

         FROM ORIGINE_FINANCEMENT d
        JOIN source src ON src.id = d.source_id AND src.importable = 1
        FULL OUTER JOIN SRC_ORIGINE_FINANCEMENT s ON s.source_id = d.source_id AND s.SOURCE_CODE = d.SOURCE_CODE
    )
    select "SOURCE_CODE","SOURCE_ID","OPERATION","U_CODE","U_LIBELLE_COURT","U_LIBELLE_LONG","S_CODE","S_LIBELLE_COURT","S_LIBELLE_LONG","D_CODE","D_LIBELLE_COURT","D_LIBELLE_LONG" from diff
    where operation is not null
    and (operation = 'undelete' or 0 < U_CODE+U_LIBELLE_COURT+U_LIBELLE_LONG);

