-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sygaldb.unicaen.fr;sid=SYGLPROD;port=1523

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW v_individu_role (utilisateur_id, nom_usuel, prenom1, email, source_code, role_id, id) AS SELECT 
    i.id utilisateur_id, i.NOM_USUEL, i.PRENOM1, i.EMAIL, i.SOURCE_CODE,
    r.ROLE_ID, r.id
   FROM INDIVIDU_ROLE ir
    join INDIVIDU i on i.id = ir.INDIVIDU_ID
    join role r on r.id = ir.ROLE_ID
  order by NOM_USUEL, PRENOM1, r.ROLE_ID;

