-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sygaldb.unicaen.fr;sid=SYGLPROD;port=1523

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW v_these_annee_univ_first (id, source_code, source_id, these_id, annee_univ, histo_createur_id, histo_creation, histo_modificateur_id, histo_modification, histo_destructeur_id, histo_destruction) AS with firsts(SOURCE_CODE) as (
    SELECT  distinct first_value(SOURCE_CODE) OVER (PARTITION BY THESE_ID ORDER BY ANNEE_UNIV)
     FROM THESE_ANNEE_UNIV
    )
    select au.ID,au.SOURCE_CODE,au.SOURCE_ID,au.THESE_ID,au.ANNEE_UNIV,au.HISTO_CREATEUR_ID,au.HISTO_CREATION,au.HISTO_MODIFICATEUR_ID,au.HISTO_MODIFICATION,au.HISTO_DESTRUCTEUR_ID,au.HISTO_DESTRUCTION
    from THESE_ANNEE_UNIV au
           join firsts fi on au.SOURCE_CODE = fi.SOURCE_CODE;

