-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sygaldb.unicaen.fr;sid=SYGLPROD;port=1523

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW v_wf_etape_pertin (these_id, etape_id, code, ordre, id) AS SELECT 
    to_number(these_id) these_id,
    to_number(etape_id) etape_id,
    code,
    ordre,
    row_number() over (order by 1,2,3,4) as id
 FROM (
         --
         -- validation_page_de_couverture
         --
         select
             t.id as these_id,
             e.id as etape_id,
             e.code,
             e.ordre
         from these t
                  join wf_etape e on e.code = 'VALIDATION_PAGE_DE_COUVERTURE'
         where t.ETAT_THESE in ('E', 'S') -- thèses en cours ou soutenues
         union all

         --
         -- depot_version_originale
         --
         select
             t.id as these_id,
             e.id as etape_id,
             e.code,
             e.ordre
         from these t
                  join wf_etape e on e.code = 'DEPOT_VERSION_ORIGINALE'
         where t.ETAT_THESE in ('E', 'S') -- thèses en cours ou soutenues
         union all

         --
         -- autorisation_diffusion_these
         --
         select
             t.id as these_id,
             e.id as etape_id,
             e.code,
             e.ordre
         from these t
                  join wf_etape e on e.code = 'AUTORISATION_DIFFUSION_THESE'
         where t.ETAT_THESE in ('E', 'S') -- thèses en cours ou soutenues
         union all

         --
         -- attestations
         --
         select
             t.id as these_id,
             e.id as etape_id,
             e.code,
             e.ordre
         from these t
                  join wf_etape e on e.code = 'ATTESTATIONS'
         where t.ETAT_THESE in ('E', 'S') -- thèses en cours ou soutenues
         union all

         --
         -- signalement_these
         --
         select
             t.id as these_id,
             e.id as etape_id,
             e.code,
             e.ordre
         from these t
                  join wf_etape e on e.code = 'SIGNALEMENT_THESE'
         where t.ETAT_THESE in ('E', 'S') -- thèses en cours ou soutenues
         union all

         --
         -- archivabilite_version_originale
         --
         select
             t.id as these_id,
             e.id as etape_id,
             e.code,
             e.ordre
         from these t
                  join wf_etape e on e.code = 'ARCHIVABILITE_VERSION_ORIGINALE'
         where t.ETAT_THESE in ('E', 'S') -- thèses en cours ou soutenues
         union all

         --
         -- depot_version_archivage
         --
         select
             t.id as these_id,
             e.id as etape_id,
             e.code,
             e.ordre
         from these t
                  join wf_etape e on e.code = 'DEPOT_VERSION_ARCHIVAGE'
                  join v_situ_archivab_vo situ on situ.these_id = t.id and situ.est_valide = 0 -- VO non archivable
         where t.ETAT_THESE in ('E', 'S') -- thèses en cours ou soutenues
         union all

         --
         -- archivabilite_version_archivage
         --
         select
             t.id as these_id,
             e.id as etape_id,
             e.code,
             e.ordre
         from these t
                  join wf_etape e on e.code = 'ARCHIVABILITE_VERSION_ARCHIVAGE'
                  join v_situ_archivab_vo situ on situ.these_id = t.id and situ.est_valide = 0 -- VO non archivable
         where t.ETAT_THESE in ('E', 'S') -- thèses en cours ou soutenues
         union all

         --
         -- verification_version_archivage
         --
         select
             t.id as these_id,
             e.id as etape_id,
             e.code,
             e.ordre
         from these t
                  join wf_etape e on e.code = 'VERIFICATION_VERSION_ARCHIVAGE'
                  join v_situ_archivab_va situ on situ.these_id = t.id and situ.est_valide = 1 -- VA archivable
         where t.ETAT_THESE in ('E', 'S') -- thèses en cours ou soutenues
         union all

         --
         -- rdv_bu_saisie_doctorant
         --
         select
             t.id as these_id,
             e.id as etape_id,
             e.code,
             e.ordre
         from these t
                  join wf_etape e on e.code = 'RDV_BU_SAISIE_DOCTORANT'
         where t.ETAT_THESE in ('E', 'S') -- thèses en cours ou soutenues
         union all

         --
         -- rdv_bu_saisie_bu
         --
         select
             t.id as these_id,
             e.id as etape_id,
             e.code,
             e.ordre
         from these t
                  join wf_etape e on e.code = 'RDV_BU_SAISIE_BU'
         where t.ETAT_THESE in ('E', 'S') -- thèses en cours ou soutenues
         union all

         --
         -- rdv_bu_validation_bu
         --
         select
             t.id as these_id,
             e.id as etape_id,
             e.code,
             e.ordre
         from these t
                  join wf_etape e on e.code = 'RDV_BU_VALIDATION_BU'
         where t.ETAT_THESE in ('E', 'S') -- thèses en cours ou soutenues
         union all



         --
         -- depot_version_originale_corrigee
         --
         select
             t.id as these_id,
             e.id as etape_id,
             e.code,
             e.ordre
         from these t
                  join wf_etape e on e.code = 'DEPOT_VERSION_ORIGINALE_CORRIGEE'
         where (t.correc_autorisee is not null or t.CORREC_AUTORISEE_FORCEE is not null or t.CORREC_EFFECTUEE = 'O') -- correction attendue
           and t.ETAT_THESE in ('E', 'S') -- thèses en cours ou soutenues
         union all

         --
         -- autorisation_diffusion_these_version_corrigee
         --
         select
             t.id as these_id,
             e.id as etape_id,
             e.code,
             e.ordre
         from these t
                  join wf_etape e on e.code = 'AUTORISATION_DIFFUSION_THESE_VERSION_CORRIGEE'
         where (t.correc_autorisee is not null or t.CORREC_AUTORISEE_FORCEE is not null or t.CORREC_EFFECTUEE = 'O') -- correction attendue ou effectuée
           and t.ETAT_THESE in ('E', 'S') -- thèses en cours ou soutenues
         union all

         --
         -- attestations_version_corrigee
         --
         select
             t.id as these_id,
             e.id as etape_id,
             e.code,
             e.ordre
         from these t
                  join wf_etape e on e.code = 'ATTESTATIONS_VERSION_CORRIGEE'
         where (t.correc_autorisee is not null or t.CORREC_AUTORISEE_FORCEE is not null or t.CORREC_EFFECTUEE = 'O') -- correction attendue ou effectuée
           and t.ETAT_THESE in ('E', 'S') -- thèses en cours ou soutenues
         union all

         --
         -- archivabilite_version_originale_corrigee
         --
         select
             t.id as these_id,
             e.id as etape_id,
             e.code,
             e.ordre
         from these t
                  join wf_etape e on e.code = 'ARCHIVABILITE_VERSION_ORIGINALE_CORRIGEE'
         where (t.correc_autorisee is not null or t.CORREC_AUTORISEE_FORCEE is not null or t.CORREC_EFFECTUEE = 'O') -- correction attendue ou effectuée
           and t.ETAT_THESE in ('E', 'S') -- thèses en cours ou soutenues
         union all

         --
         -- depot_version_archivage_corrigee
         --
         select
             t.id as these_id,
             e.id as etape_id,
             e.code,
             e.ordre
         from these t
                  join wf_etape e on e.code = 'DEPOT_VERSION_ARCHIVAGE_CORRIGEE'
                  join v_situ_archivab_voc situ on situ.these_id = t.id and situ.est_valide = 0 -- VOC non archivable
         where (t.correc_autorisee is not null or t.CORREC_AUTORISEE_FORCEE is not null or t.CORREC_EFFECTUEE = 'O') -- correction attendue ou effectuée
           and t.ETAT_THESE in ('E', 'S') -- thèses en cours ou soutenues
         union all

         --
         -- archivabilite_version_archivage_corrigee
         --
         select
             t.id as these_id,
             e.id as etape_id,
             e.code,
             e.ordre
         from these t
                  join wf_etape e on e.code = 'ARCHIVABILITE_VERSION_ARCHIVAGE_CORRIGEE'
                  join v_situ_archivab_voc situ on situ.these_id = t.id and situ.est_valide = 0 -- VOC non archivable
         where (t.correc_autorisee is not null or t.CORREC_AUTORISEE_FORCEE is not null or t.CORREC_EFFECTUEE = 'O') -- correction attendue ou effectuée
           and t.ETAT_THESE in ('E', 'S') -- thèses en cours ou soutenues
         union all

         --
         -- verification_version_archivage_corrigee
         --
         select
             t.id as these_id,
             e.id as etape_id,
             e.code,
             e.ordre
         from these t
                  join wf_etape e on e.code = 'VERIFICATION_VERSION_ARCHIVAGE_CORRIGEE'
                  join v_situ_archivab_vac situ on situ.these_id = t.id and situ.est_valide = 1 -- VAC archivable
         where (t.correc_autorisee is not null or t.CORREC_AUTORISEE_FORCEE is not null or t.CORREC_EFFECTUEE = 'O') -- correction attendue ou effectuée
           and t.ETAT_THESE in ('E', 'S') -- thèses en cours ou soutenues
         union all

         --
         -- depot_version_corrigee_validation_doctorant
         --
         select
             t.id as these_id,
             e.id as etape_id,
             e.code,
             e.ordre
         from these t
                  join wf_etape e on e.code = 'DEPOT_VERSION_CORRIGEE_VALIDATION_DOCTORANT'
         where (t.correc_autorisee is not null or t.CORREC_AUTORISEE_FORCEE is not null or t.CORREC_EFFECTUEE = 'O') -- correction attendue ou effectuée
           and t.ETAT_THESE in ('E', 'S') -- thèses en cours ou soutenues
         union all

         --
         -- depot_version_corrigee_validation_directeur
         --
         select
             t.id as these_id,
             e.id as etape_id,
             e.code,
             e.ordre
         from these t
                  join wf_etape e on e.code = 'DEPOT_VERSION_CORRIGEE_VALIDATION_DIRECTEUR'
         where (t.correc_autorisee is not null or t.CORREC_AUTORISEE_FORCEE is not null or t.CORREC_EFFECTUEE = 'O') -- correction attendue ou effectuée
           and t.ETAT_THESE in ('E', 'S') -- thèses en cours ou soutenues
         union all

         --
         -- REMISE_EXEMPLAIRE_PAPIER_THESE_CORRIGEE
         --
         select
             t.id as these_id,
             e.id as etape_id,
             e.code,
             e.ordre
         from these t
                  join wf_etape e on e.code = 'REMISE_EXEMPLAIRE_PAPIER_THESE_CORRIGEE'
         where (t.correc_autorisee is not null or t.CORREC_AUTORISEE_FORCEE is not null or t.CORREC_EFFECTUEE = 'O') -- correction attendue ou effectuée
           and t.ETAT_THESE in ('E', 'S') -- thèses en cours ou soutenues
           and exists (
                 select * from DIFFUSION d
                 where d.THESE_ID = t.id and d.VERSION_CORRIGEE = 1 and d.AUTORIS_MEL in (0/*Non*/
, 1/*Oui+embargo*/
) -- exemplaire papier requis
             )

     );

