<?php

/**
 * @see \These\Controller\TheseSaisieController::ajouterAction()
 *
 * @var \Laminas\Form\Form $form
 */

$title = "Saisie d'une nouvelle thèse";
$this->headTitle($title);

$form->prepare();
?>

<h1 class="page-header">
    <?php echo $title ?>
</h1>

<?php echo $this->form()->openTag($form); ?>
<?php echo $this->partial('these/these-saisie/partial/generalites'); ?>
<?php echo $this->formHidden($form->get('security')); ?>
<?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-primary')); ?>

<?php echo $this->form()->closeTag(); ?>
