<?php

/**
 * @see \These\Controller\TheseSaisieController::modifier()
 *
 * @var \These\Entity\Db\These $these
 * @var \Laminas\Form\Form $form
 * @var string $formPartial
 * @var ?array $errorMessages
 */

$this->headTitle($these->getDoctorant()->getNomUsuel());
$this->headTitle($this->translate("Modification"));

$form->prepare();
?>

<h1 class="page-header">
    <?php echo $this->translate("Modification de la thèse de") . " {$these->getDoctorant()}" ?>
</h1>

<?php if(isset($errorMessages) && is_array($errorMessages)){ ?>
    <div class="alert alert-danger">
        Certains champ(s) du formulaire n'ont pas pu être validé : <br><br>
        <ul>
            <?php
            foreach ($errorMessages as $key => $messageGroup) { ?>
                <li>
                    <ul>
                        Onglet <?php echo $key; ?> :
                        <?php foreach ($messageGroup as $name => $errors) { ?>

                            <?php if (is_array($errors)) {
                                foreach ($errors as $errorKey => $errorMessage) {
                                    echo "<li><b>'$name'</b> : $errorMessage<br></li>";
                                }
                            } ?>
                        <?php } ?>
                    </ul>
                </li>
                <br>
            <?php } ?>
        </ul>
    </div>
<?php } ?>

<?php
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>

<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="informations-tab" data-bs-toggle="tab" data-bs-target="#informations" type="button" role="tab" aria-controls="informations" aria-selected="true"><?php echo $form->get("generalites")->getLabel();?></button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="structures-tab" data-bs-toggle="tab" data-bs-target="#structures" type="button" role="tab" aria-controls="structures" aria-selected="false"><?php echo $form->get("structures")->getLabel();?></button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="specifites-tab" data-bs-toggle="tab" data-bs-target="#specifites" type="button" role="tab" aria-controls="specifites" aria-selected="false">Spécifités envisagées</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="direction-tab" data-bs-toggle="tab" data-bs-target="#direction" type="button" role="tab" aria-controls="direction" aria-selected="false"><?php echo $form->get("direction")->getLabel();?></button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="encadrements-tab" data-bs-toggle="tab" data-bs-target="#encadrements" type="button" role="tab" aria-controls="encadrements" aria-selected="false"><?php echo $form->get("encadrements")->getLabel();?></button>
    </li>
    <!--    <li class="nav-item" role="presentation">-->
    <!--        <button class="nav-link" id="confidentialite-tab" data-bs-toggle="tab" data-bs-target="#confidentialite" type="button" role="tab" aria-controls="confidentialite" aria-selected="false">Spécifités envisagées</button>-->
    <!--    </li>-->
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="financement-tab" data-bs-toggle="tab" data-bs-target="#financement" type="button" role="tab" aria-controls="financement" aria-selected="false"><?php echo $form->get("financements")->getLabel();?></button>
    </li>
</ul>

<?php echo $this->form()->openTag($form); ?>

<div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="informations" role="tabpanel" aria-labelledby="informations-tab">
        <?php echo $this->partial('these/these-saisie/partial/generalites'); ?>
    </div>
    <div class="tab-pane fade" id="structures" role="tabpanel" aria-labelledby="structures-tab">
        <?php echo $this->partial('these/these-saisie/partial/structures'); ?>
        <br/><br/>
        <span class="alert alert-warning">Quid des co-tutelle ?</span>
    </div>
    <div class="tab-pane fade" id="specifites" role="tabpanel" aria-labelledby="specifites-tab">
        <?php echo $this->partial('these/these-saisie/partial/specifites'); ?>
    </div>
    <div class="tab-pane fade" id="encadrements" role="tabpanel" aria-labelledby="encadrements-tab">
        <?php echo $this->partial('these/these-saisie/partial/encadrement'); ?>
    </div>
    <div class="tab-pane fade" id="direction" role="tabpanel" aria-labelledby="direction-tab">
        <?php echo $this->partial('these/these-saisie/partial/direction'); ?>
    </div>
    <div class="tab-pane fade" id="confidentialite" role="tabpanel" aria-labelledby="confidentialite-tab">
        <!--        --><?php //echo $this->partial('these/these-saisie/partial/confidentialite'); ?>
    </div>
    <div class="tab-pane fade" id="financement" role="tabpanel" aria-labelledby="financement-tab">
        <?php echo $this->partial('these/these-saisie/partial/financement'); ?>
    </div>
</div>

<?php echo $this->formHidden($form->get('security')); ?>
<?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-primary')); ?>
<?php echo $this->form()->closeTag(); ?>

<style>
    span.erase-acteur {
        cursor: pointer;
    }
</style>


