<?php

/**
 * @see \These\Controller\TheseSaisieController::modifier()
 *
 * @var \These\Entity\Db\These $these
 * @var \Laminas\Form\Form $form
 * @var string $formPartial
 * @var ?array $errorMessages
 */

$this->headTitle($these->getDoctorant()->getNomUsuel());
$this->headTitle($this->translate("Modification"));

$form->prepare();
?>

<h1 class="page-header">
    <?php echo $this->translate("Modification de la thèse de") . " {$these->getDoctorant()}" ?>
</h1>

<?php if(isset($errorMessages) && is_array($errorMessages)){ ?>
    <div class="alert alert-danger">
        Certains champ(s) du formulaire n'ont pas pu être validé : <br><br>
        <ul>
            <?php
            foreach ($errorMessages as $key => $messageGroup) { ?>
                <li>
                    <ul>
                        Onglet <?php echo $key; ?> :
                        <?php foreach ($messageGroup as $name => $errors) { ?>

                            <?php if (is_array($errors)) {
                                foreach ($errors as $errorKey => $errorMessage) {
                                    echo "<li><b>'$name'</b> : $errorMessage<br></li>";
                                }
                            } ?>
                        <?php } ?>
                    </ul>
                </li>
                <br>
            <?php } ?>
        </ul>
    </div>
<?php } ?>

<?php echo $this->form()->openTag($form); ?>
<div role="tabpanel">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation">
            <a class="nav-link" href="#informations" aria-controls="informations" role="tab" data-toggle="tabz"><?php echo $form->get("generalites")->getLabel();?></a>
        </li>
        <li role="presentation">
            <a class="nav-link" href="#structures" aria-controls="structures" role="tab" data-toggle="tabz"><?php echo $form->get("structures")->getLabel();?></a>
        </li>
        <li role="presentation">
            <a class="nav-link" href="#specifites" aria-controls="specifites" role="tab" data-toggle="tabz">Spécifités envisagées</a>
        </li>
        <li role="presentation">
            <a class="nav-link" href="#direction" aria-controls="confidentialite" role="tab" data-toggle="tabz"><?php echo $form->get("direction")->getLabel();?></a>
        </li>
        <li role="presentation">
            <a class="nav-link" href="#encadrements" aria-controls="encadrements" role="tab" data-toggle="tabz"><?php echo $form->get("encadrements")->getLabel();?></a>
        </li>
<!--        <li role="presentation">-->
<!--            <a class="nav-link" href="#confidentialite" aria-controls="confidentialite" role="tab" data-toggle="tabz">             Confidentialité</a>-->
<!--        </li>-->
        <li role="presentation">
            <a class="nav-link" href="#financement" aria-controls="financement" role="tab" data-toggle="tabz"><?php echo $form->get("financements")->getLabel();?></a>
        </li>
<!--        <li role="presentation">-->
<!--            <a class="nav-link" href="#missions-enseignement" aria-controls="missions-enseignement" role="tab" data-toggle="tabz">--><?php //echo $form->get("missionsEnseignement")->getLabel();?><!--</a>-->
<!--        </li>-->
    </ul>
</div>

<?php echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>
<div class="tab-content">
    <div id="informations" class="tab-pane " role="tabpanel">
        <?php echo $this->partial('these/these-saisie/partial/generalites'); ?>
    </div>
    <div id="structures" class="tab-pane " role="tabpanel">
        <?php echo $this->partial('these/these-saisie/partial/structures'); ?>
        <br/><br/>
    </div>
    <div id="specifites" class="tab-pane " role="tabpanel">
        <?php echo $this->partial('these/these-saisie/partial/specifites'); ?>
        <br/><br/>
    </div>
    <div id="direction" class="tab-pane " role="tabpanel">
        <?php echo $this->partial('these/these-saisie/partial/direction'); ?>
        <br/><br/>
    </div>
    <div id="encadrements" class="tab-pane " role="tabpanel">
        <?php echo $this->partial('these/these-saisie/partial/encadrement'); ?>
        <br/><br/>
    </div>
<!--    <div id="confidentialite" class="tab-pane " role="tabpanel">-->
<!--        --><?php ////echo $this->partial('these/these-saisie/partial/'); ?>
<!--    </div>-->
    <div id="financement" class="tab-pane " role="tabpanel">
        <?php echo $this->partial('these/these-saisie/partial/financement'); ?>
    </div>
<!--    <div id="missions-enseignement" class="tab-pane " role="tabpanel">-->
<!--        --><?php //echo $this->partial('these/these-saisie/partial/missions-enseignement'); ?>
<!--    </div>-->
</div>
<?php echo $this->formHidden($form->get('security')); ?>
<?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-primary')); ?>
<?php echo $this->form()->closeTag(); ?>


<script>
    $(function() {
        let hash = $(location).attr('hash');
        let name = hash.substring(1);
        if (name === undefined || name === "") name = "informations";

        $('a[aria-controls=' + name + ']').tab('show');

        $('.nav-tabs a').click(function () {
            $(this).tab('show');
        });
    });

    $('span.erase-acteur').click(function() {
        let id = $(this).attr('id');
        $('select[name=' + id + '-qualite]').val("");
        $('select[name=' + id + '-etablissement]').val("");
        $('input[name="' + id + '-individu[id]').val("");
        $('input[name="' + id + '-individu[label]').val("");
    });

    // $('select').selectpicker();
</script>

<style>
    span.erase-acteur {
        cursor: pointer;
    }
</style>


