<?php

/**
 * @see \These\Controller\TheseSaisieController::saisieAction()
 * @var TheseSaisieForm $form
 */

use These\Form\TheseSaisie\TheseSaisieForm;

$this->headTitle("Saisie d'une thèse");

?>

<h1 class="page-header">
    Saisie d'une thèse
</h1>

<?php //echo $this->form($form); ?>

<?php echo $this->form()->openTag($form); ?>
    <div role="tabpanel">
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation">
                <a class="nav-link" href="#informations" aria-controls="informations" role="tab" data-toggle="tabz">                   Informations générales</a>
            </li>
            <li role="presentation">
                <a class="nav-link" href="#structures" aria-controls="structures" role="tab" data-toggle="tabz">                       Structures encadrantes</a>
            </li>
            <li role="presentation">
                <a class="nav-link" href="#encadrements" aria-controls="encadrements" role="tab" data-toggle="tabz">                   Direction de thèse</a>
            </li>
            <li role="presentation">
                <a class="nav-link" href="#confidentialite" aria-controls="confidentialite" role="tab" data-toggle="tabz">             Confidentialité</a>
            </li>
        </ul>
    </div>

<div class="tab-content">
    <div id="informations" class="tab-pane " role="tabpanel">
        <?php echo $this->formControlGroup($form->get('titre')); ?>
        <?php echo $this->formControlGroup($form->get('doctorant')); ?>
        <?php echo $this->formControlGroup($form->get('discipline')); ?>

        <?php echo $this->formControlGroup($form->get('bouton')); ?>
    </div>
    <div id="structures" class="tab-pane " role="tabpanel">

        <?php echo $this->formControlGroup($form->get('unite-recherche')); ?>
        <?php echo $this->formControlGroup($form->get('ecole-doctorale')); ?>
        <?php echo $this->formControlGroup($form->get('etablissement')); ?>
        <?php echo $this->formControlGroup($form->get('bouton')); ?>

        <br/><br/>
        <span class="alert alert-warning">Quid des co-tutelle ?</span>
    </div>
    <div id="encadrements" class="tab-pane " role="tabpanel">
        <h3> Directeur·trice de thèse <span class="icon icon-information" title="Un·e seul·e directeur·trice de thèse"></span></h3>
        <div class="row">
            <div class="col-md-4"> <?php echo $this->formControlGroup($form->get('directeur-individu')); ?> </div>
            <div class="col-md-4"> <?php echo $this->formControlGroup($form->get('directeur-etablissement')); ?> </div>
            <div class="col-md-3"> <?php echo $this->formControlGroup($form->get('directeur-qualite')); ?> </div>
            <div class="col-md-1 pull-right"><br/><span id="directeur" class="erase-acteur icon icon-historiser" title="Remise à zéro"></span></div>
        </div>
        <h3> Co-directeur·trice de thèse</h3>
        <?php for($i = 1 ; $i <= TheseSaisieForm::NBCODIR ; $i++)  : ?>
        <div class="row">
            <div class="col-md-4"> <?php echo $this->formControlGroup($form->get('codirecteur'.$i.'-individu')); ?> </div>
            <div class="col-md-4"> <?php echo $this->formControlGroup($form->get('codirecteur'.$i.'-etablissement')); ?> </div>
            <div class="col-md-3"> <?php echo $this->formControlGroup($form->get('codirecteur'.$i.'-qualite')); ?> </div>
            <div class="col-md-1 pull-right"><br/><span id="codirecteur<?php echo $i; ?>" class="erase-acteur icon icon-historiser" title="Remise à zéro"></span></div>
        </div>
        <?php endfor; ?>
        <?php echo $this->formControlGroup($form->get('bouton')); ?>

        <br/><br/>
        <span class="alert alert-warning">Quid des co-encadrements ici ?</span>
    </div>
    <div id="confidentialite" class="tab-pane " role="tabpanel">
        <?php echo $this->formControlGroup($form->get('confidentialite')); ?>
        <?php echo $this->formControlGroup($form->get('fin-confidentialite')); ?>
        <?php echo $this->formControlGroup($form->get('bouton')); ?>
    </div>
</div>
<?php //echo $this->formControlGroup($form->get('titre')); ?>
<?php echo $this->form()->closeTag(); ?>


<script>
    $(function() {
        let hash = $(location).attr('hash');
        let name = hash.substring(1);
        if (name === undefined || name === "") name = "informations";

        $('a[aria-controls=' + name + ']').tab('show');

        $('.nav-tabs a').click(function () {
            $(this).tab('show');
        });
    });

    $('span.erase-acteur').click(function() {
        let id = $(this).attr('id');
        $('select[name=' + id + '-qualite]').val("");
        $('select[name=' + id + '-etablissement]').val("");
        $('input[name="' + id + '-individu[id]').val("");
        $('input[name="' + id + '-individu[label]').val("");
    });

    // $('select').selectpicker();
</script>

<style>
    span.erase-acteur {
        cursor: pointer;
    }
</style>