<?php

use Application\Entity\Db\Doctorant;
use Application\Entity\Db\These;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var These $these
 * @var string $contact
 * @var Doctorant $doctorant
 * @var bool  $emailDoctorantAbsent
 */
?>

<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application <?php echo $this->appInfos()->nom ?>.
</p>
<?php if ($emailDoctorantAbsent): ?>
<p>
    <em>Ce mail aurait dû être envoyé à <?php echo $doctorant ?> (<?php echo $doctorant->getSourceCodeSansPrefix() ?>)
    mail aucune adresse mail n'a été trouvée pour ce doctorant.</em>
</p>
<?php endif ?>
<p>
    Votre dossier est complet.
</p>
<p>
    Vous pouvez récupérer votre attestation de réussite au diplôme de doctorat
    au Bureau des doctorats ou la demander par courriel à
    <a href="mailto:<?php echo $contact ?>>"><?php echo $contact ?></a>.
</p>

