<?php

namespace Application;

use Application\Entity\Db\Rapport;
use Application\Entity\Db\These;
use Application\Entity\Db\TypeValidation;
use Application\Form\RapportActiviteForm;
use Application\Provider\Privilege\RapportPrivileges;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var These $these
 * @var Rapport[] $rapports
 * @var RapportActiviteForm $form
 * @var bool $tousLesRapportsTeleverses
 * @var TypeValidation $typeValidation
 *
 * @see \Application\Controller\Rapport\RapportActiviteController::consulterAction()
 */

$routeName = 'rapport-activite';
$privilege_TELEVERSER_TOUT = RapportPrivileges::RAPPORT_ACTIVITE_TELEVERSER_TOUT;
$privilege_TELEVERSER_SIEN = RapportPrivileges::RAPPORT_ACTIVITE_TELEVERSER_SIEN;
$privilege_SUPPRIMER_TOUT = RapportPrivileges::RAPPORT_ACTIVITE_SUPPRIMER_TOUT;
$privilege_SUPPRIMER_SIEN = RapportPrivileges::RAPPORT_ACTIVITE_SUPPRIMER_SIEN;
$privilege_TELECHARGER_TOUT = RapportPrivileges::RAPPORT_ACTIVITE_TELECHARGER_TOUT;
$privilege_TELECHARGER_SIEN = RapportPrivileges::RAPPORT_ACTIVITE_TELECHARGER_SIEN;
$privilege_VALIDER_TOUT = RapportPrivileges::RAPPORT_ACTIVITE_VALIDER_TOUT;
$privilege_VALIDER_SIEN = RapportPrivileges::RAPPORT_ACTIVITE_VALIDER_SIEN;
$privilege_DEVALIDER_TOUT = RapportPrivileges::RAPPORT_ACTIVITE_DEVALIDER_TOUT;
$privilege_DEVALIDER_SIEN = RapportPrivileges::RAPPORT_ACTIVITE_DEVALIDER_SIEN;

$form->prepare();
$rapportProto = (new Rapport())->setThese($these);
$canAdd = $this->isAllowed($rapportProto, $privilege_TELEVERSER_TOUT) || $this->isAllowed($rapportProto, $privilege_TELEVERSER_SIEN);
if ($tousLesRapportsTeleverses) {
    $canAdd = false;
}
?>

<?php $this->headTitle($this->translate($title = "Rapports d'activité"))
    ->prepend($these->getDoctorant()->getIndividu()->getNomUsuel()) ?>

<h1 class="page-header">
    <?php echo $this->translate($title); ?>
    <small><?php echo $this->partial('application/these/partial/titre') ?></small>
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace(); ?>

<p class="lead">Selon l'état d'avancement de votre thèse :</p>
<ul class="lead">
    <li>
        <strong>Si votre soutenance n'est pas prévue avant le 31 décembre</strong> de l'année en cours,
        <strong>vous devez rédiger un rapport d'activité annuel</strong> qui doit <strong>être déposé ci-dessous avant le 31 juillet</strong>.
        Son dépôt conditionne l'autorisation de réinscription en thèse.
        <a href="<?php echo $this->url('fichier/telecharger-permanent', ['idPermanent' => 'RAPPORT_ACTIVITE_MODELE']) ?>">Cliquez ici pour télécharger le modèle de rapport annuel.</a>
    </li>
    <li>
        <strong>Si votre soutenance est programmée avant le 31 décembre</strong> de l'année en cours,
        <strong>vous devez rédiger un rapport d'activité de fin de thèse</strong> qui doit <strong>être déposé ci-dessous avant le 31 juillet</strong>.
        Dans ce cas, les données indiquées doivent couvrir l'ensemble de la thèse.
        <a href="<?php echo $this->url('fichier/telecharger-permanent', ['idPermanent' => 'RAPPORT_ACTIVITE_MODELE']) ?>">Cliquez ici pour télécharger le modèle de rapport de fin de thèse.</a>
    </li>
</ul>
<p class="lead">
    Les rapports d'activité doivent être concis (suivez les indications de taille maximum pour chaque item).
</p>
<ul class="lead">
    <li>Complétez le document téléchargé, faites le signer par vos directions de thèse et de laboratoire</li>
    <li>Scannez le document signé et téléversez le en version PDF</li>
</ul>

<div class="row">
    <div class="col-md-11">

        <h2>Rapports téléversés</h2>

        <?php if (count($rapports) > 0): ?>

            <?php echo $this->partial('application/rapport/partial/rapports-table', [
                'rapports' => $rapports,
                'routeName' => $routeName,
                'typeValidation' => $typeValidation,
                'privilege_TELEVERSER_TOUT' => $privilege_TELEVERSER_TOUT,
                'privilege_TELEVERSER_SIEN' => $privilege_TELEVERSER_SIEN,
                'privilege_SUPPRIMER_TOUT' => $privilege_SUPPRIMER_TOUT,
                'privilege_SUPPRIMER_SIEN' => $privilege_SUPPRIMER_SIEN,
                'privilege_TELECHARGER_TOUT' => $privilege_TELECHARGER_TOUT,
                'privilege_TELECHARGER_SIEN' => $privilege_TELECHARGER_SIEN,
                'privilege_VALIDER_TOUT' => $privilege_VALIDER_TOUT,
                'privilege_VALIDER_SIEN' => $privilege_VALIDER_SIEN,
                'privilege_DEVALIDER_TOUT' => $privilege_DEVALIDER_TOUT,
                'privilege_DEVALIDER_SIEN' => $privilege_DEVALIDER_SIEN,
                'displayEtablissement' => false,
                'displayType' => true,
                'displayDoctorant' => false,
                'displayDirecteurThese' => false,
                'displayEcoleDoctorale' => false,
                'displayUniteRecherche' => false,
                'displayValidation' => true,
            ]) ?>

        <?php else: ?>

            Aucun.

        <?php endif; ?>

    </div>
</div>

<div class="row">
    <div class="col-md-offset-1 col-md-8">

        <?php if ($tousLesRapportsTeleverses): ?>
            <div class="row">
                <div class="col-md-6 text-success">
                    <p>
                        <span class="glyphicon glyphicon-info-sign"></span>
                        Toutes les années universitaires d'inscription du doctorant ont fait l'objet d'un téléversement de rapport.
                    </p>
                </div>
            </div>
        <?php endif ?>

        <?php $ajouterFormVisible = !empty($form->getMessages()); ?>
        <div id="ajouterDiv">
            <div class="row">
                <div class="col-md-4">
                    <a href="#" id="ajouterBtn" class="btn btn-primary <?php echo $canAdd ? '' : 'disabled' ?>"
                       style="display: <?php echo !$ajouterFormVisible ? 'inherit' : 'none' ?>">
                        <span class="glyphicon glyphicon-plus"></span> Téléverser un rapport</a>
                </div>
            </div>

            <div id="ajouterForm" style="display: <?php echo $ajouterFormVisible ? 'inherit' : 'none' ?>">
                <h3>Formulaire de téléversement</h3>

                <?php echo $this->form()->openTag($form) ?>
                <div class="row">
                    <div class="col-md-6">
                        <?php echo $this->formControlGroup($form->get('estFinal')); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <?php echo $this->formControlGroup($form->get('anneeUniv')) ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-7">
                        <?php
                        echo $this->formControlGroup($form->get('files'));
                        echo $this->formControlGroup($form->get('security'));
                        echo $this->formSubmit($form->get('submit')->setAttributes(['class' => 'btn btn-primary']));
                        ?>
                    </div>
                </div>
                <?php echo $this->form()->closeTag() ?>
                <div class="row">
                    <div class="col-md-3">
                        <a href="#" id="annulerBtn" class="btn btn-danger">Annuler</a>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>


<script>
    $(function() {
        var $ajouterBtn = $("#ajouterBtn");
        var $annulerBtn = $("#annulerBtn");
        var $ajouterForm = $("#ajouterForm");

        $ajouterBtn.on('click', function() {
            $ajouterForm.show();
            $ajouterBtn.hide();
            return false;
        });
        $annulerBtn.on('click', function() {
            $ajouterForm.hide();
            $ajouterBtn.show();
            return false;
        });
        $('[data-toggle=confirmation]').confirmation({
            rootSelector: '[data-toggle=confirmation]',
            container: 'body',
            title: "Êtes-vous sûr(e) ?",
            btnOkLabel: "Oui",
            btnCancelLabel: "Non",
        });
    });
</script>
