<?php

/**
 * @var \Application\Entity\Db\Profil[] $profils
 * @var \Application\Entity\Db\Privilege[] $privileges
 */
$this->headTitle("Profils");

$canEdit = true;
$canDelete = true;
$canManage = true;
$canChangePrivilege = true;
?>

<h1 class="page-header">
    Profils
    <span class="badge bg-secondary">
        <?php echo count($profils); ?>
    </span>
</h1>

<h2> Liste des profils </h2>

<a href="<?php echo $this->url('profil/editer', [], [], true); ?>" class="btn btn-primary ajax-modal" data-event="modification">
    <span class="icon icon-plus"></span> Ajouter un nouveau profil
</a>

<table class="table table-sm">
    <thead>
    <tr>
        <th> Code </th>
        <th> Libellé </th>
        <th> Structure dépendant </th>
        <th> Nombre de rôle ayant le profil </th>
        <th> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($profils as $profil) : ?>
        <tr>
            <td> <?php echo $profil->getRoleCode(); ?> </td>
            <td> <?php echo $profil->getLibelle(); ?></td>
            <td> <?php echo $profil->getStructureType(); ?></td>
            <td> <?php echo count($profil->getRoles()); ?></td>
            <td>
                <?php if ($canEdit) : ?>
                    <a href="<?php echo $this->url('profil/editer', ['profil' => $profil->getId()], [], true);?>" class="ajax-modal" data-event="modification">
                        <span class="icon icon-edit" title="Éditer les informations du profil"></span>
                    </a>
                <?php endif; ?>
                <?php if ($canEdit) : ?>
                    <a class="ajax-modal" data-event="modification" href="<?php echo $this->url('profil/dupliquer', ['profil' => $profil->getId()], [], true);?>">
                        <span class="fas fa-paste" title="Recopier privilèges d'une autre profil"></span>
                    </a>
                <?php endif; ?>
                <?php if ($canDelete) : ?>
                    <a href="<?php echo $this->url('profil/supprimer', ['profil' => $profil->getId()], [], true);?>">
                        <span class="icon icon-delete iconly" title="Supprimer le profil"></span>
                    </a>
                <?php endif; ?>
                <?php if ($canManage) : ?>
                    <a href="<?php echo $this->url('profil/gerer-roles', ['profil' => $profil->getId()], [], true);?>">
                        <span class="fas fa-link" title="Gérer les rôles associés au profil" ></span>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<h2> Gestion des privilèges accordés aux profils </h2>

<table class="table table--condensed">
    <thead>
    <tr>
        <th> Privilège </th>
        <?php foreach ($profils as $profil) : ?>
            <th> <?php echo $profil; ?> </th>
        <?php endforeach; ?>
    </tr>
    </thead>
    <tbody>
    <?php $previous = "" ?>
    <?php foreach ($privileges as $privilege) : ?>
        <?php if ($previous != $privilege->getCategorie()): ?>
            <tr>
                <?php $previous = $privilege->getCategorie(); ?>
                <td class="categorie" colspan="<?php echo (1 + count($profils)); ?>"><span title="<?php echo $previous->getCode() ?>"><?php echo $previous ?></span></td>
            </tr>
        <?php endif; ?>
        <tr data-legend="<?php echo $privilege->getLibelle() ?>">
            <th><span title="<?php echo $privilege->getCode() ?>"><?php echo $privilege ?></span></th>
            <?php foreach ($profils as $profil) : ?>
                <td class="<?php echo ($profil->getStructureType())?$profil->getStructureType()->getCode():"aucun"; ?>" id="<?php echo $privilege->getId(); ?>_<?php echo $profil->getId();?>"
                    data-legend="<?php echo $profil->getLibelle() ?>">
                    <?php if ($profil->hasPrivilege($privilege)) : ?>
                        <span class="fa fa-check faa-spin faa-fast text-success checkable" title="Cliquer pour retirer le privilège"></span>
                    <?php else: ?>
                        <span class="fa fa-ban faa-spin faa-fast text-danger checkable" title="Cliquer pour ajouter le privilège"></span>
                    <?php endif; ?>
                </td>
            <?php endforeach; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


<style>
    td.categorie {
        font-size:  small;
        background-color: lightblue;
    }

    td.aucun {
        background-color: lightgoldenrodyellow;
    }

    td.ecole-doctorale {
        background-color: #F1CEFF;
    }
    td.unite-recherche {
        background-color: #c8e7ff;
    }
    td.etablissement {
        background-color: #dcffe9;
    }

    span.checkable {
        cursor: pointer;
    }

</style>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
        $(".checkable").each(function() {
            installTooltipOnCheckable($(this));
        });
    });

    function installTooltipOnCheckable($checkable) {
        var profil = $checkable.parent("td").data("legend");
        var privilege = $checkable.parent("td").parent("tr").data("legend");
        var title = $checkable.attr("title") + " <strong>" + privilege + "</strong><br>au profil<br><strong>" + profil + "</strong>";
        $checkable.attr("title", title).tooltip({trigger: "hover", html: true, placement: "bottom", container: "body"});
    }

    $(document).ready(function() {
        $("td").on("click", function() {

            var canModifier =  Boolean(<?php echo $canChangePrivilege; ?>);
            if (!canModifier) {
                alert("Vous n'êtes pas autorisé à modifier les privilèges associés à un rôle.");
                return;
            }

            var $td = $(this);
            var $checkable = $(this).find(".checkable");
            var id = $td.attr("id");
            var splits = id.split("_");
            var role = splits[1];
            var privilege = splits[0];
            var url = "modifier-profil-privilege/" + role + "/" + privilege;

            $.ajax({
                type: "POST",
                url : url,
                beforeSend:
                    function () {
                        $checkable.tooltip("dispose");
                        $checkable.addClass("animated");
                    },
                success:
                    function(retour){
                        if (retour["value"] == 1) texte = "<span class='fa fa-check faa-spin faa-fast text-success checkable' title='Cliquer pour retirer le privilège'></span>";
                        else var texte = "<span class='fa fa-ban faa-spin faa-fast text-danger checkable' title='Cliquer pour ajouter le privilège'></span>";
                        $td.html(texte);
                        installTooltipOnCheckable($td.find(".checkable"))
                    },
                error:
                    function() {
                        $checkable.removeClass("animated");
                    }
            });
        });
    });
</script>