<?php

/**
 * @see \Application\Controller\IndividuComplController::detruireAction()
 * @var string $title
 * @var string $text
 * @var string $action
 */

?>

<p class="lead">
<?php echo $text; ?>
</p>

<table>
    <tr><td>
<form method="post" action="<?php echo $action; ?>">
    <input type="hidden" name="reponse" value="oui">
    <input type="submit" name="reponse" class="btn btn-success action" value="Oui, je suis sûr&middot;e">
</form>
        </td><td>
<form method="post" action="<?php echo $action; ?>">
    <input type="hidden" name="reponse" value="non">
    <input type="submit" id="non" name="reponse" class="btn btn-danger action"  value="Non, je ne veux pas">
</form>
        </td></tr>
</table>

<script>
    $(function() {
        $("input#non").click(function(e){
            $('div.modal').modal('hide');
            e.preventDefault(e);
        });
    });
</script>

