--
-- Requêtes des indicateurs converties en pgsql en vue de la migration.
--

-- alter table INDICATEUR modify REQUETE VARCHAR2(2048);

update INDICATEUR set REQUETE = 'SELECT THESE.ID ID,THESE.ETABLISSEMENT_ID ETABLISSEMENT_ID,THESE.DOCTORANT_ID DOCTORANT_ID,THESE.ECOLE_DOCT_ID ECOLE_DOCT_ID,
       THESE.UNITE_RECH_ID UNITE_RECH_ID,THESE.BESOIN_EXPURGE BESOIN_EXPURGE,THESE.COD_UNIT_RECH COD_UNIT_RECH,
       THESE.CORREC_AUTORISEE CORREC_AUTORISEE,THESE.DATE_AUTORIS_SOUTENANCE DATE_AUTORIS_SOUTENANCE,
       THESE.DATE_FIN_CONFID DATE_FIN_CONFID,THESE.DATE_PREM_INSC DATE_PREM_INSC,THESE.DATE_PREV_SOUTENANCE DATE_PREV_SOUTENANCE,
       THESE.DATE_SOUTENANCE DATE_SOUTENANCE,THESE.ETAT_THESE ETAT_THESE,THESE.LIB_DISC LIB_DISC,THESE.LIB_ETAB_COTUT LIB_ETAB_COTUT,
       THESE.LIB_PAYS_COTUT LIB_PAYS_COTUT,THESE.LIB_UNIT_RECH LIB_UNIT_RECH,THESE.RESULTAT RESULTAT,
       THESE.SOUTENANCE_AUTORIS SOUTENANCE_AUTORIS,THESE.TEM_AVENANT_COTUT TEM_AVENANT_COTUT,
       THESE.TITRE TITRE,THESE.SOURCE_CODE SOURCE_CODE,THESE.SOURCE_ID SOURCE_ID,
       THESE.HISTO_CREATEUR_ID HISTO_CREATEUR_ID,THESE.HISTO_CREATION HISTO_CREATION,
       THESE.HISTO_MODIFICATEUR_ID HISTO_MODIFICATEUR_ID,THESE.HISTO_MODIFICATION HISTO_MODIFICATION,
       THESE.HISTO_DESTRUCTEUR_ID HISTO_DESTRUCTEUR_ID,THESE.HISTO_DESTRUCTION HISTO_DESTRUCTION
FROM THESE THESE;'
where id = 1;

update INDICATEUR set REQUETE = 'SELECT t.*
FROM THESE T
         LEFT JOIN VALIDATION V ON T.ID = V.THESE_ID
         LEFT JOIN TYPE_VALIDATION N on V.TYPE_VALIDATION_ID = N.ID
WHERE T.DATE_SOUTENANCE > LOCALTIMESTAMP - interval ''2 month''
  AND T.ETAT_THESE = ''E''
  AND N.CODE = ''PAGE_DE_COUVERTURE''
  AND V.ID IS NULL;'
where id = 2;

update INDICATEUR set REQUETE = 'SELECT t.*
FROM THESE T
         LEFT JOIN fichier_these F on T.ID = F.THESE_ID
         LEFT JOIN fichier Fi on Fi.ID = F.fichier_id
         LEFT JOIN NATURE_FICHIER N on Fi.NATURE_ID = N.ID
WHERE T.DATE_SOUTENANCE > LOCALTIMESTAMP - interval ''1 month''
  AND T.ETAT_THESE = ''E''
  AND N.CODE = ''THESE_PDF''
  AND F.ID IS NULL;'
where id = 3;

update INDICATEUR set REQUETE = 'SELECT *
FROM THESE t
WHERE t.ETAT_THESE = ''E''
  AND t.DATE_SOUTENANCE < LOCALTIMESTAMP;'
where id = 4;


update INDICATEUR set REQUETE = 'SELECT *
FROM THESE t
WHERE t.ETAT_THESE = ''E''
  AND t.DATE_SOUTENANCE > LOCALTIMESTAMP;'
where id = 5;


update INDICATEUR set REQUETE = 'SELECT *
FROM THESE t
WHERE t.ETAT_THESE = ''E''
  AND t.DATE_PREM_INSC < LOCALTIMESTAMP - interval ''72 month'';'
where id = 6;


update INDICATEUR set REQUETE = 'SELECT i.*
FROM THESE t
         JOIN DOCTORANT d ON d.ID = t.DOCTORANT_ID
         JOIN INDIVIDU I on d.INDIVIDU_ID = I.ID
WHERE i.TYPE=''doctorant''
  AND t.ETAT_THESE = ''E''
  AND i.EMAIL is NULL;'
where id = 7;


update INDICATEUR set REQUETE = 'SELECT * FROM THESE WHERE ECOLE_DOCT_ID=(SELECT ID FROM ECOLE_DOCT WHERE SOURCE_CODE=''UCN::497'') AND ETAT_THESE=''E'';'
where id = 21;


update INDICATEUR set REQUETE = 'SELECT *
FROM STRUCTURE
WHERE ID IN (
    SELECT UNITE_RECH.STRUCTURE_ID
    FROM THESE
             LEFT JOIN UNITE_RECH ON THESE.UNITE_RECH_ID = UNITE_RECH.ID
    WHERE THESE.ETAT_THESE=''E''
      AND UNITE_RECH.STRUCTURE_ID IS NOT NULL
    GROUP BY UNITE_RECH.STRUCTURE_ID)
  AND CHEMIN_LOGO IS NULL;'
where id = 61;

update INDICATEUR set REQUETE = 'SELECT *
FROM STRUCTURE
WHERE ID IN (
    SELECT ECOLE_DOCT.STRUCTURE_ID
    FROM THESE
             LEFT JOIN ECOLE_DOCT ON THESE.ECOLE_DOCT_ID = ECOLE_DOCT.ID
    WHERE THESE.ETAT_THESE=''E''
      AND ECOLE_DOCT.STRUCTURE_ID IS NOT NULL
    GROUP BY ECOLE_DOCT.STRUCTURE_ID)
  AND CHEMIN_LOGO IS NULL;'
where id = 62;


update INDICATEUR set REQUETE = 'SELECT *
FROM THESE t
WHERE t.DATE_PREM_INSC <= LOCALTIMESTAMP - interval ''60 month''
  AND t.ETAT_THESE = ''E''
  AND ID IN (
    SELECT THESE_ID
    FROM THESE_ANNEE_UNIV
             JOIN THESE T on THESE_ANNEE_UNIV.THESE_ID = t.ID
    WHERE t.ETAT_THESE = ''E''
    GROUP BY(THESE_ID)
    HAVING MAX(ANNEE_UNIV) <= extract(YEAR from (LOCALTIMESTAMP - interval ''12 month''))
);'
where id = 81;


update INDICATEUR set REQUETE = 'select i.*
FROM DOCTORANT d
         join INDIVIDU i ON d.INDIVIDU_ID = i.ID
         left join THESE t ON d.ID = t.DOCTORANT_ID
where t.ETAT_THESE = ''E''
  and t.DATE_PREM_INSC < LOCALTIMESTAMP + interval ''60 month''
  and t.ID IN (
    SELECT THESE_ID
    FROM THESE_ANNEE_UNIV
             JOIN THESE T on THESE_ANNEE_UNIV.THESE_ID = T.ID
    WHERE T.ETAT_THESE = ''E''
    GROUP BY(THESE_ID)
    HAVING MAX(ANNEE_UNIV) < extract(YEAR from (LOCALTIMESTAMP - interval ''12 month''))
);'
where id = 101;


update INDICATEUR set REQUETE = 'select * FROM individu
where SOURCE_CODE in (
    SELECT SOURCE_CODE
    FROM V_DIFF_INDIVIDU
    WHERE operation = ''insert''
);'
where id = 121;


