<?php

use Structure\Entity\Db\EcoleDoctorale;
use Structure\Provider\Privilege\StructurePrivileges;

/**
 * @var EcoleDoctorale[] $ecoles
 *
 * @see \Structure\Controller\EcoleDoctoraleController::indexAction()
 */

$canModifier = $this->isAllowed(StructurePrivileges::getResourceId(StructurePrivileges::STRUCTURE_MODIFICATION_TOUTES_STRUCTURES));
$canAjouter = $this->isAllowed(StructurePrivileges::getResourceId(StructurePrivileges::STRUCTURE_MODIFICATION_TOUTES_STRUCTURES));
?>


<?php $this->headTitle($this->translate("Écoles doctorales")) ?>

<h1 class="page-header first">
    <?php echo $this->translate("Écoles doctorales") ?>
    <span class="badge bg-secondary"><?php echo count($ecoles); ?></span>
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace() ?>

<p>
    <?php if ($canAjouter): ?>
        <a href="<?php echo $this->url('ecole-doctorale/ajouter', [], [], true) ?>"
           class="btn btn-primary"
           title="<?php echo $this->translate("Créer une nouvelle école doctorale"); ?>">
            <span class="icon icon-plus"></span>
            <?php echo $this->translate("Ajouter une nouvelle école doctorale"); ?>
        </a>
    <?php endif ?>
</p>

<div>
    <table class="table table-sm">
        <thead>
        <tr>
            <th> Libellé</th>
            <th> </th>
            <th> Source</th>
            <th> Code</th>
            <th> Sigle</th>
            <th> Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($ecoles as $ecole): ?>

            <?php
            $historisee = (!$ecole->estNonHistorise());
            $canModifierCetteEcole = $this->isAllowed($ecole->getStructure(),StructurePrivileges::STRUCTURE_MODIFICATION_SES_STRUCTURES);
            ?>

            <tr>
                <td>
                    <a href="<?php echo $this->url('ecole-doctorale/voir', ['ecole-doctorale' => $ecole->getId()], [], true); ?>">
                        <?php echo $ecole->getStructure()->getLibelle(); ?>
                    </a>
                </td>
                <td>
                    <?php if ($ecole->getStructure()->estFermee()) : ?>
                        &nbsp;<span class="badge bg-danger" title="Structure fermée">Fermée</span>
                    <?php endif; ?>
                </td>
                <td>
                    <?php echo $ecole->getSource(); ?>
                    <?php if ($ecole->estSubstituant()) : ?>
                        <a href="<?php echo $this->url('substitution/substitution/voir', ['type' => \Substitution\Constants::TYPE_ecole_doct, 'id' => $ecole->getId()]) ?>"
                           title="Accéder aux détails de cette substitution">
                            <span class="badge bg-light text-info" title="Cet enregistrement substitue d'autres enregistrements, cliquez pour en savoir plus...">Substitution</span></a>
                    <?php endif; ?>
                </td>
                <td>
                    <?php echo $ecole->getStructure()->getCode(); ?>
                </td>
                <td> <?php echo $ecole->getStructure()->getSigle(); ?> </td>
                <td>
                    <?php if (($canModifier OR $canModifierCetteEcole) && !$historisee) : ?>
                        <a href="<?php echo $this->url('ecole-doctorale/supprimer', ["ecole-doctorale" => $ecole->getId()], [], true); ?>"
                           title="Historiser l'établissement">
                            <span class="icon icon-delete iconly"></span>
                        </a>
                    <?php endif; ?>

                    <?php if (($canModifier OR $canModifierCetteEcole) && $historisee) : ?>
                        <a href="<?php echo $this->url('ecole-doctorale/restaurer', ["ecole-doctorale" => $ecole->getId()], [], true); ?>"
                           title="Restaurer l'établissement">
                            Restaurer
                        </a>
                    <?php endif; ?>
                </td>
            </tr>

        <?php endforeach; ?>

        </tbody>
    </table>
</div>