<?php

/**
 * @see \Structure\Controller\EcoleDoctoraleController::informationAction()
 * @var EcoleDoctorale $ecole
 * @var array          $roleListing     (string => int)
 * @var IndividuRole[] $individuRoles
 * @var string         $logoContent
 * @var Acteur[]       $coencadrants
 * @var string[]       $contenus
 */

use These\Entity\Db\Acteur;
use Individu\Entity\Db\IndividuRole;
use These\Provider\Privilege\CoEncadrantPrivileges;
use Structure\Controller\StructureController;
use Structure\Entity\Db\EcoleDoctorale;
use Structure\Entity\Db\TypeStructure;
use Structure\Provider\Privilege\StructurePrivileges;

$this->headTitle("École Doctorale '{$ecole->getStructure()->getCode()}'");

$canEdit = ($this->isAllowed(StructurePrivileges::getResourceId(StructurePrivileges::STRUCTURE_MODIFICATION_TOUTES_STRUCTURES))) ||
    ($this->isAllowed($ecole->getStructure(), StructurePrivileges::STRUCTURE_MODIFICATION_SES_STRUCTURES));
$canAddRole = $canEdit;

$canCoencadrantAfficher = $this->isAllowed(CoEncadrantPrivileges::getResourceId(CoEncadrantPrivileges::COENCADRANT_AFFICHER));
$canCoencadrantExport = $this->isAllowed(CoEncadrantPrivileges::getResourceId(CoEncadrantPrivileges::COENCADRANT_AFFICHER));

$tab = $this->queryParams()['tab'] ?? StructureController::TAB_infos;

$structure = $ecole->getStructure();
?>

<h1 class="page-header">
    École doctorale &laquo; <?php echo $ecole->getStructure()->getLibelle(); ?> &raquo;
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace() ?>

<ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="nav-item">
        <a class="nav-link <?php echo $tab === StructureController::TAB_infos ? 'active' : '' ?>"
           href="<?php echo $this->url('ecole-doctorale/voir', ['ecole-doctorale' => $ecole->getId()], ['query' => ['tab' => StructureController::TAB_infos]], true) ?>"
           role="tab"
        >
            Informations générales
        </a>
    </li>
    <li role="presentation" class="nav-item">
        <a class="nav-link <?php echo $tab === StructureController::TAB_membres ? 'active' : '' ?>"
           href="<?php echo $this->url('ecole-doctorale/voir', ['ecole-doctorale' => $ecole->getId()], ['query' => ['tab' => StructureController::TAB_membres]], true) ?>"
           role="tab"
        >
            Rôles et membres
        </a>
    </li>
    <li role="presentation" class="nav-item">
        <a class="nav-link <?php echo $tab === StructureController::TAB_coenc ? 'active' : '' ?>"
           href="<?php echo $this->url('ecole-doctorale/voir', ['ecole-doctorale' => $ecole->getId()], ['query' => ['tab' => StructureController::TAB_coenc]], true) ?>"
           role="tab"
        >
            Co-encadrants
        </a>
    </li>
    <li role="presentation" class="nav-item">
        <a class="nav-link <?php echo $tab === StructureController::TAB_docs ? 'active' : '' ?>"
           href="<?php echo $this->url('ecole-doctorale/voir', ['ecole-doctorale' => $ecole->getId()], ['query' => ['tab' => StructureController::TAB_docs]], true) ?>"
           role="tab"
        >
            Documents
        </a>
    </li>
</ul>

<div class="<?php echo $tab === StructureController::TAB_infos ? '' : 'd-none' ?>" id="informations">
    <div class="row">
        <div class="col-md-6">
            <?php echo $this->partial('structure/ecole-doctorale/partial/information', ['entity' => $ecole]) ?>
        </div>
        <div class="col-md-4">
            <dl>
                <dt>Logo :</dt>
                <dd>
                    <img id="logo" style="max-width: 200px; max-height: 200px; background-color: white;"
                         src="data:image/*;base64,<?php echo base64_encode($logoContent); ?>"/>
                </dd>
            </dl>
        </div>
    </div>

    <?php if ($canEdit): ?>
        <a href="<?php echo $this->url('ecole-doctorale/modifier', ['ecole-doctorale' => $ecole->getId()], [], true); ?>"
           class="btn btn-primary action"><span class="icon icon-edit"></span> Modifier l'école doctorale
        </a>
    <?php endif; ?>
</div>

<div class="<?php echo $tab === StructureController::TAB_membres ? '' : 'd-none' ?>" id="membres">
    <h2>
        Rôles et membres
    </h2>

    <table class="table table-sm">
        <thead>
        <tr>
            <th> Libellé du rôle</th>
            <th> Effectif</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($roleListing as $libelle => $count): ?>
            <tr>
                <td> <?php echo $libelle; ?> </td>
                <td> <?php echo $count; ?> </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <table class="table table-sm">
        <thead>
        <tr>
            <th> Dénomination</th>
            <th> Adresse électronique</th>
            <th> Établissement d'inscription</th>
            <th> Rôle</th>
            <th> &nbsp; </th>
        </tr>
        </thead>
        <tbody>
        <?php /** @var IndividuRole $individuRole */ ?>
        <?php foreach ($individuRoles as $individuRole): ?>
            <?php
                $individu = $individuRole->getIndividu();
                $role = $individuRole->getRole();
            ?>
            <tr>
                <td> <?php echo $individu->getNomComplet(); ?> </td>
                <td> <?php echo $individu->getEmailPro(); ?> </td>
                <td> <?php echo $individu->getEtablissement(); ?> </td>
                <td> <?php echo $role->getLibelle(); ?> </td>
                <td>
                    <?php if ($canEdit) : ?>
                        <a href="<?php echo $this->url("individu-compl/gerer", ['individu' => $individu->getId()], [], true); ?>" class="ajax-modal" data-event="modification">
                            <span class="icon icon-editer" title="Ajouter/Modifier un complément"></span></a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <?php if ($canAddRole && empty($roleListing)): ?>
        <a href="<?php echo $this->url('structure/generer-roles-defauts', [
            'id' => $ecole->getStructure()->getId(),
            'type' => TypeStructure::CODE_ECOLE_DOCTORALE], [], true); ?>"
           class="btn btn-warning"><span class="fas fa-cog"></span> Générer rôles par défaut</a>
    <?php endif; ?>
</div>

<div class="<?php echo $tab === StructureController::TAB_coenc ? '' : 'd-none' ?>" id="coencadrants">

    <h2>
        Co-encadrants
        <span class="badge bg-secondary"> <?php echo count($coencadrants); ?> </span>
    </h2>

    <?php if($canCoencadrantExport) : ?>
        <?php /** @see \These\Controller\CoEncadrantController::genererExportCsvAction() */ ?>
        <a href="<?php echo $this->url('co-encadrant/generer-export-csv', ['structure-type' => 'ecole-doctorale', 'structure-id' => $ecole->getId()], [], true); ?>"
           class="btn btn-primary"
        >
            <span class="icon icon-export"></span>
            Générer l'export CSV des co-encadrants
        </a>
    <?php endif; ?>

    <br/>
    <br/>

    <ul>
    <?php foreach ($coencadrants as $coencadrant) : ?>
        <?php
            $acteur = $coencadrant['co-encadrant'];
            $count = count($coencadrant['theses']);
        ?>
        <li>
            <?php echo $acteur->getIndividu()->getPrenom1(); ?>
            <?php echo $acteur->getIndividu()->getNomUsuel(); ?>
            (<?php echo $count; ?> co-encadrement<?php if ($count > 1) echo "s"; ?>.)
            <?php if ($canCoencadrantAfficher) : ?>
                <a href="<?php echo $this->url('co-encadrant/historique', ['co-encadrant' => $acteur->getId()],[], true); ?>">
                    <span class="icon icon-voir" title="Accéder à l'historique de co-encadrement"></span></a>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
    </ul>
</div>

<div class="<?php echo $tab === StructureController::TAB_docs ? '' : 'd-none' ?>" id="documents">

    <?php echo $this->partial('structure/structure/partial/documents', ['structure' => $structure, 'contenus' => $contenus]); ?>

</div>


<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
