<?php

/**
 * @see \Structure\Controller\EcoleDoctoraleController::informationAction()
 *
 * @var \Application\View\Renderer\PhpRenderer $this
 * @var EcoleDoctorale $ecole
 * @var array          $roleListing     (string => int)
 * @var IndividuRole[] $individuRoles
 * @var string         $logoContent
 * @var Acteur[]       $coencadrants
 * @var string[]       $contenus
 */

use Individu\Entity\Db\IndividuRoleEtablissement;
use These\Entity\Db\Acteur;
use Individu\Entity\Db\IndividuRole;
use These\Provider\Privilege\CoEncadrantPrivileges;
use Structure\Controller\StructureController;
use Structure\Entity\Db\EcoleDoctorale;
use Structure\Entity\Db\TypeStructure;
use Structure\Provider\Privilege\StructurePrivileges;

$this->headTitle("École Doctorale '{$ecole->getStructure()->getCode()}'");

$canEdit = ($this->isAllowed(StructurePrivileges::getResourceId(StructurePrivileges::STRUCTURE_MODIFICATION_TOUTES_STRUCTURES))) ||
    ($this->isAllowed($ecole->getStructure(), StructurePrivileges::STRUCTURE_MODIFICATION_SES_STRUCTURES));
$canAddRole = $canEdit;

$canCoencadrantAfficher = $this->isAllowed(CoEncadrantPrivileges::getResourceId(CoEncadrantPrivileges::COENCADRANT_AFFICHER));
$canCoencadrantExport = $this->isAllowed(CoEncadrantPrivileges::getResourceId(CoEncadrantPrivileges::COENCADRANT_AFFICHER));

$tab = $this->queryParams()['tab'] ?? StructureController::TAB_infos;

$structure = $ecole->getStructure();
?>

<h1 class="page-header">
    École doctorale &laquo; <?php echo $ecole->getStructure()->getLibelle(); ?> &raquo; - <?php echo $ecole->getStructure()->getSigle() ?>
</h1>

<?php echo $this->alertes()->addAlertesFromFlashMessenger()->renderAsBootstrapToasts() ?>

<ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="nav-item">
        <a class="nav-link <?php echo $tab === StructureController::TAB_infos ? 'active' : '' ?>"
           href="<?php echo $this->url('ecole-doctorale/voir', ['ecole-doctorale' => $ecole->getId()], ['query' => ['tab' => StructureController::TAB_infos]], true) ?>"
           role="tab"
        >
            Informations générales
        </a>
    </li>
    <li role="presentation" class="nav-item">
        <a class="nav-link <?php echo $tab === StructureController::TAB_membres ? 'active' : '' ?>"
           href="<?php echo $this->url('ecole-doctorale/voir', ['ecole-doctorale' => $ecole->getId()], ['query' => ['tab' => StructureController::TAB_membres]], true) ?>"
           role="tab"
        >
            Rôles et membres
        </a>
    </li>
    <li role="presentation" class="nav-item">
        <a class="nav-link <?php echo $tab === StructureController::TAB_coenc ? 'active' : '' ?>"
           href="<?php echo $this->url('ecole-doctorale/voir', ['ecole-doctorale' => $ecole->getId()], ['query' => ['tab' => StructureController::TAB_coenc]], true) ?>"
           role="tab"
        >
            Co-encadrants
        </a>
    </li>
    <li role="presentation" class="nav-item">
        <a class="nav-link <?php echo $tab === StructureController::TAB_docs ? 'active' : '' ?>"
           href="<?php echo $this->url('ecole-doctorale/voir', ['ecole-doctorale' => $ecole->getId()], ['query' => ['tab' => StructureController::TAB_docs]], true) ?>"
           role="tab"
        >
            Documents
        </a>
    </li>
</ul>

<div class="<?php echo $tab === StructureController::TAB_infos ? '' : 'd-none' ?>" id="informations">
    <div class="row">
        <div class="col-md-6">
            <?php echo $this->partial('structure/ecole-doctorale/partial/information', ['entity' => $ecole]) ?>
        </div>
        <div class="col-md-4">
            <dl>
                <dt>Logo :</dt>
                <dd>
                    <img id="logo" style="max-width: 200px; max-height: 200px; background-color: white;"
                         src="data:image/*;base64,<?php echo base64_encode($logoContent); ?>"/>
                </dd>
            </dl>
        </div>
    </div>

    <?php if ($canEdit): ?>
        <a href="<?php echo $this->url('ecole-doctorale/modifier', ['ecole-doctorale' => $ecole->getId()], [], true); ?>"
           class="btn btn-primary action"><span class="icon icon-edit"></span> Modifier l'école doctorale
        </a>
    <?php endif; ?>
</div>

<div class="<?php echo $tab === StructureController::TAB_membres ? '' : 'd-none' ?>" id="membres">
    <h2>
        Rôles et membres
    </h2>

    <div class="row">
        <div class="col-md-7">
            <table class="table table-sm">
                <thead>
                <tr>
                    <th>Rôle</th>
                    <th>Nombre d'individus ayant ce rôle</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($roleListing as $libelle => $count): ?>
                    <tr>
                        <td> <?php echo $libelle; ?> </td>
                        <td> <?php echo $count; ?> </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

    <table class="table table-sm">
        <thead>
        <tr>
            <th>Rôle</th>
            <th>Périmètre</th>
            <th>Individu</th>
        </tr>
        </thead>
        <tbody>
        <?php /** @var IndividuRole $individuRole */ ?>
        <?php foreach ($individuRoles as $individuRole): ?>
            <?php
                $individu = $individuRole->getIndividu();
                $role = $individuRole->getRole();
            ?>
            <tr>
                <td><?php echo $role->getLibelle(); ?></td>
                <td>
                    <?php $perimetres = $individuRole->getIndividuRoleEtablissementToString('<br>', fn(IndividuRoleEtablissement $irp) =>
                        '<span class="text-structure etablissement">' . $irp->getEtablissement() . '</span>'); ?>
                    <?php if ($perimetres) : ?>
                        <?php echo $perimetres ?>
                    <?php else: ?>
                        <abbr title="Pas de restriction selon l'établissement d'inscription">Aucun</abbr>
                    <?php endif; ?>

                    <?php if ($canEdit) : ?>
                        <a href="<?php echo $this->url("individu-role/modifier", ['individu' => $individu->getId(), 'role' => $role->getId()], [], true); ?>"
                           class="ajax-modal" data-event="modification"
                           title="Modifier cette attribution de rôle">
                            <span class="icon icon-editer"></span></a>
                    <?php endif; ?>
                </td>
                <td>
                    <?php echo $individu->getNomComplet(); ?> &ndash;
                    <?php if ($email = $individu->getEmailProComplement()) : ?>
                        <em title="Valeur forcée issue du complément d'individu"><a href="mailto:<?php echo $email ?>"><?php echo $email ?></a></em>
                    <?php elseif ($email = $individu->getEmailPro()): ?>
                        <a href="mailto:<?php echo $email ?>"><?php echo $email ?></a>
                    <?php else: ?>
                        Adresse électronique inconnue
                    <?php endif; ?>

                    <?php if ($canEdit) : ?>
                        <?php if ($compl = $individu->getComplement()): ?>
                            <a href="<?php echo $this->url("individu-compl/modifier", ['individu-compl' => $compl->getId()], [], true); ?>"
                               class="ajax-modal" data-event="modification" title="Modifier ou supprimer un complément d'individu">
                                <span class="icon icon-edit"></span>
                            </a>
                        <?php else: ?>
                            <a href="<?php echo $this->url("individu-compl/ajouter", ['individu' => $individu->getId()], [], true); ?>"
                               class="ajax-modal" data-event="modification" title="Créer un complément d'individu">
                                <span class="icon icon-plus"></span>
                            </a>
                        <?php endif; ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <?php if ($canAddRole && empty($roleListing)): ?>
        <a href="<?php echo $this->url('structure/generer-roles-defauts', [
            'id' => $ecole->getStructure()->getId(),
            'type' => TypeStructure::CODE_ECOLE_DOCTORALE], [], true); ?>"
           class="btn btn-warning"><span class="fas fa-cog"></span> Générer rôles par défaut</a>
    <?php endif; ?>
</div>

<div class="<?php echo $tab === StructureController::TAB_coenc ? '' : 'd-none' ?>" id="coencadrants">

    <h2>
        Co-encadrants
        <span class="badge bg-secondary"> <?php echo count($coencadrants); ?> </span>
    </h2>

    <?php if($canCoencadrantExport) : ?>
        <?php /** @see \These\Controller\CoEncadrantController::genererExportCsvAction() */ ?>
        <a href="<?php echo $this->url('co-encadrant/generer-export-csv', ['structure-type' => 'ecole-doctorale', 'structure-id' => $ecole->getId()], [], true); ?>"
           class="btn btn-primary"
        >
            <span class="icon icon-export"></span>
            Générer l'export CSV des co-encadrants
        </a>
    <?php endif; ?>

    <br/>
    <br/>

    <ul>
    <?php foreach ($coencadrants as $coencadrant) : ?>
        <?php
            $acteur = $coencadrant['co-encadrant'];
            $count = count($coencadrant['theses']);
        ?>
        <li>
            <?php echo $acteur->getIndividu()->getPrenom1(); ?>
            <?php echo $acteur->getIndividu()->getNomUsuel(); ?>
            (<?php echo $count; ?> co-encadrement<?php if ($count > 1) echo "s"; ?>.)
            <?php if ($canCoencadrantAfficher) : ?>
                <a href="<?php echo $this->url('co-encadrant/historique', ['co-encadrant' => $acteur->getId()],[], true); ?>">
                    <span class="icon icon-voir" title="Accéder à l'historique de co-encadrement"></span></a>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
    </ul>
</div>

<div class="<?php echo $tab === StructureController::TAB_docs ? '' : 'd-none' ?>" id="documents">

    <?php echo $this->partial('structure/structure/partial/documents', ['structure' => $structure, 'contenus' => $contenus]); ?>

</div>


<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
