<?php

use Structure\Controller\EcoleDoctoraleController;
use Structure\Entity\Db\EcoleDoctorale;
use Structure\Form\EcoleDoctoraleForm;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer        $this
 * @var string             $title
 * @var EcoleDoctoraleForm $form
 * @var string             $logoContent
 *
 * @method string formControlGroup()
 *
 * @see EcoleDoctoraleController::modifierAction()
*/

/** @var EcoleDoctorale $ecole */
$ecole = $form->getObject();
$isNew = $ecole->getId() === null;
$estSubstituee = $ecole->getStructure()->estSubstituee();
$estModifiable = !($ecole->getSource()->getImportable());
$fcg = $this->formControlGroup();
$this->headTitle("Modification de l'école doctorale ".$ecole->getStructure()->getCode());

$editable = $isNew || (!$estSubstituee AND $estModifiable);
$form->get('libelle')->setAttribute('readonly', !$editable);
$form->get('sigle')->setAttribute('readonly', !$editable);
$form->get('code')->setAttribute('readonly', !$editable);
?>

<h1 class="page-header">
    <?php if ($isNew): ?>
        Création d'une nouvelle école doctorale
    <?php else: ?>
        Modification de l'école doctorale &laquo; <?php echo $ecole->getStructure()->getLibelle(); ?> &raquo;
    <?php endif ?>
</h1>

<?php if (!$editable) : ?>
<div class="alert alert-warning">
        <p>
        <?php if (!$estModifiable) : ?>
            <span class="icon icon-attention"></span>
            <strong>La source (<?php echo $ecole->getSource()->getLibelle(); ?>) ne permet pas de modification.</strong>
            <br/>
        <?php endif; ?>
        <?php if ($estSubstituee) : ?>
            <span class="icon icon-attention"></span>
            <strong>La structure est substituée et ne doit pas être modifiée.</strong>
            <br/>
        <?php endif; ?>
        </p>

    <p>
        Par conséquent, vous ne pouvez pas modifier les champs : libellé, sigle et code.
    </p>
</div>
<?php endif; ?>

<?php echo $this->form()->openTag($form->prepare()->setAttribute('class', 'ecole-doctorale')) ?>
<div class="row">

    <div class="col-md-6">
        <?php echo $fcg($form->get('libelle')) ?>
        <?php echo $fcg($form->get('sigle')) ?>
        <?php echo $fcg($form->get('code')) ?>
        <?php echo $fcg($form->get('id_ref')) ?>
        <?php echo $fcg($form->get('id_hal')) ?>
        <?php echo $fcg($form->get('theme')) ?>
        <?php echo $fcg($form->get('offre-these')) ?>
        <?php echo $fcg($form->get('estFerme')) ?>
    </div>

    <div id="logo-div" class="col-md-6">

        <?php
        /** @var \Laminas\Form\Element\File $logoFile */
        $logoFile = $form->get('cheminLogo');
        echo $this->formLabel($logoFile);
        ?>

        <?php
        $content = $logoContent;
        if ($content === null) {
            $ecole->getStructure()->setCheminLogo(null);
        }
        ?>


        <table>
            <tr>
                <td>
                    <img
                            id="logo"
                            style="max-width: 200px; max-height: 200px; border: 1px solid black; background-color: white;"
                            src="data:image/*;base64,<?php echo base64_encode($logoContent); ?>"
                    />
                </td>
                <td style="padding:20px;">
                    <?php
                    echo $this->formFile($logoFile);
                    echo $this->formElementErrors($logoFile);
                    ?>
                    <br/>
                    <?php if($ecole->getId()): ?>
                        <a id="supprimer-logo" class="btn btn-danger" href="<?php echo $this->url('ecole-doctorale/supprimer-logo', ["structure" => $ecole->getStructure()->getId()]); ?>">
                            <span class="icon icon-delete"></span>
                            Supprimer le logo
                        </a>
                    <?php endif; ?>
                </td>
            </tr>
        </table>

        <div class="alert alert-warning">
            <small>
                <span class="icon icon-warning"></span>
                Le logo de la structure doit être donné dans un des formats suivant&nbsp;:
                <ul>
                    <li>.bmp</li>
                    <li>.jpg, .jpeg</li>
                    <li>.png</li>
                </ul>
            </small>
        </div>
    </div>

</div>

<?php echo $this->formElement($form->get('submit')) ?>
<?php echo $this->form()->closeTag() ?>

<!-- pour traduction -->
<?php
    $this->translate("Libellé :");
    $this->translate("Sigle :");
    $this->translate("Code :");
    $this->translate("Enregistrer");
    $this->translate("Supprimer le logo");
    $this->translate("Logo de l'école doctorale :");
?>


<script>
    $(document).ready(function() {

        //remplacement dans la structure cible
        $("input[name='cheminLogo']").on("change", function () {

            var myFile = $("input[name='cheminLogo']").prop('files');
            console.log(myFile[0]);
            fr = new FileReader();
            fr.onload = function () {
                var content = fr.result;
                console.log(content);
                $('#logo').attr("src", content);
            };
            fr.readAsDataURL( myFile[0] );
        });
    });
</script>
