<?php
/**
 * @var \Application\View\Renderer\PhpRenderer $this
 * @var \RapportActivite\Entity\RapportActiviteOperationInterface $operationAttendue
 * @var string[] $anomalies
 *
 * @see \RapportActivite\Notification\RapportActiviteOperationAttenduNotification
 */

use Application\Constants;

$rapport = $operationAttendue->getRapportActivite();
$these = $rapport->getThese();
$etab = $these->getEtablissement();
$ur = $these->getUniteRecherche();
$unite = $ur?->getStructure()->getSigle();
$etablissement = $etab?->getStructure()->getSigle();
?>
<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application <?php echo $this->appInfos()->nom ?>.
</p>
<?php if ($anomalies): ?>
    <p>
        <em><?php echo implode('<br>', $anomalies) ?></em>
    </p>
<?php endif ?>
<p>
    Le <strong><?php echo lcfirst($rapport) ?></strong>
    de <strong><?php echo $rapport->getThese()->getDoctorant() ?></strong> (<?php if($unite) echo $unite; ?>, <?php if($etablissement) echo $etablissement; ?>)
    complété à la date du
    <?php echo ($rapport->getHistoModification() ?: $rapport->getHistoCreation())->format(Constants::DATETIME_FORMAT) ?>
    est en attente de l'opération suivante de votre part :
    <strong><?php echo $operationAttendue->getTypeToString() ?></strong>.
</p>
<p>
    Merci de vous connecter sur la plateforme <?php echo $this->appInfos()->nom ?> via le lien suivant :
    <a href="<?php echo $this->url('rapport-activite/consulter', [
        'these' => $rapport->getThese()->getId(),
        'rapport' => $rapport->getId(),
    ], ['force_canonical' => true]) ?>">lien</a>.
</p>
<p>
    <strong>Note importante : une fois connecté, pensez à vérifier le rôle que vous endossez (en cliquant sur votre nom en haut à droite
    des pages de l'application) et le cas échéant à sélectionner celui permettant de réaliser l'opération attendue.</strong>
</p>
