<?php
/**
 * @var \RapportActivite\Entity\Db\RapportActivite $rapportActivite
 *
 * @see \RapportActivite\Notification\RapportActiviteSupprimeNotification
 */

$these = $rapportActivite->getThese();
$etab = $these?->getEtablissement();
$ur = $these?->getUniteRecherche();
$unite = $ur?->getStructure()->getSigle();
$etablissement = $etab?->getStructure()->getSigle();
?>
<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application <?php echo $this->appInfos()->nom ?> à propos
    du rapport d'activité &laquo; <?php echo $rapportActivite->getAnneeUniv()->toString() ?> -
    <?php echo $rapportActivite->getEstFinContratToString() ?> &raquo; de
    <?php echo $rapportActivite->getThese()->getDoctorant() ?> (<?php if($unite) echo $unite; ?>, <?php if($etablissement) echo $etablissement; ?>).
</p>
<p>
    Ce rapport d'activité a été supprimé par <?php echo $rapportActivite->getHistoDestructeur() ?>,
    le <?php echo $rapportActivite->getHistoDestruction()->format('d/m/Y à H:i') ?>.
</p>
