<?php
/**
 * @var \RapportActivite\Entity\Db\RapportActiviteValidation $rapportActiviteValidation
 *
 * @see \RapportActivite\Notification\RapportActiviteValidationAjouteeNotification
 */

use Application\Constants;

$rapport = $rapportActiviteValidation->getRapportActivite();
$these = $rapport->getThese();
$etab = $these?->getEtablissement();
$ur = $these?->getUniteRecherche();
$unite = $ur?->getStructure()->getSigle();
$etablissement = $etab?->getStructure()->getSigle();
?>
<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application <?php echo $this->appInfos()->nom ?>.
</p>
<p>
    Le <strong><?php echo lcfirst($rapport) ?></strong>
    de <strong><?php echo $rapport->getThese()->getDoctorant() ?></strong> (<?php if($unite) echo $unite; ?>, <?php if($etablissement) echo $etablissement; ?>)
    complété à la date du
    <?php echo ($rapport->getHistoModification() ?: $rapport->getHistoCreation())->format(Constants::DATETIME_FORMAT) ?>
    a été <strong>validé</strong> par
    <?php echo $rapportActiviteValidation->getHistoModificateur() ?: $rapportActiviteValidation->getHistoCreateur() ?>,
    le <?php echo ($rapportActiviteValidation->getHistoModification() ?: $rapportActiviteValidation->getHistoCreation())->format(Constants::DATETIME_FORMAT) ?>.
</p>
