<?php

use Application\Entity\Db\These;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var These       $these
 * @var bool        $estPremiereNotif
 * @var string      $url
 */
?>

<?php $url = $this->url('these/depot', ['these' => $these->getId()], ['force_canonical' => true]) ?>

<p>Bonjour,</p>
<p>Ceci est un mail envoyé automatiquement par l'application <?php echo $this->appInfos()->nom ?>.</p>

<?php if ($these->getCorrectionAutoriseeEstMineure()): ?>

    <p>
        A l’issue de la soutenance, le jury vous a demandé d’apporter des corrections mineures (corrections de forme) à votre thèse. Ces corrections sont facultatives.
        <br>
        Vous disposez d'un mois après la soutenance pour déposer votre thèse corrigée dans <?php echo $this->appInfos()->nom ?>. Une fois les modifications certifiées conformes aux préconisations du jury par votre(vos) directeurs(s) de thèse dans SoDoct, elle sera la version de référence de votre thèse, ce second dépôt se substituant au premier.
    </p>
    <p>
        Passé le délai d’un mois, vous n’aurez plus la possibilité d'effectuer un second dépôt.
        <br>
        En ce cas la version déposée avant la soutenance restera la version de référence de votre thèse.
    </p>

<?php elseif ($these->getCorrectionAutoriseeEstMajeure()): ?>

    <?php if ($estPremiereNotif): ?>

        <p>
            A l’issue de la soutenance, le jury vous a demandé d’apporter des corrections majeures (corrections de fond) à votre thèse. Ces corrections sont obligatoires et la version déposée avant la soutenance, invalidée par le jury, a été détruite dès réception du PV de soutenance.
            <br>
            Vous disposez de 3 mois après la soutenance pour déposer votre thèse corrigée dans <?php echo $this->appInfos()->nom ?>. Une fois les modifications certifiées conformes aux préconisations du jury dans SoDoct par votre(vos) directeurs(s) de thèse, elle sera la version de référence de votre thèse, ce second dépôt se substituant au premier.
        </p>
        <p>
            Passé le délai de 3 mois, vous n’aurez plus la possibilité d'effectuer un second dépôt.
            <br>
            En ce cas ni l'attestation de soutenance, ni le diplôme ne pourront vous être délivrés.
        </p>

    <?php else: ?>

        <p>
            A l’issue de la soutenance, le jury vous a demandé d’apporter des corrections majeures (corrections de fond) à votre thèse et la version déposée avant la soutenance a, en conséquence, été invalidée et détruite.
        </p>
        <p>
            Vous n'avez pas, à ce jour, procédé au dépôt obligatoire de la version corrigée dans <?php echo $this->appInfos()->nom ?>.
            <br>
            Vous ne disposez plus que d'un mois pour ce faire conformément à l’article 24 de l’Arrêté du 25 mai 2016.
            <br>
            Passé ce délai, vous n'aurez plus la possibilité d'effectuer de dépôt et ni l'attestation de réussite au diplôme, ni le diplôme de doctorat ne pourront vous être délivrés.
        </p>

    <?php endif ?>

<?php endif ?>

Cliquez <a href="<?php echo $url ?>">ici</a> pour accéder à l'application.

