<?php

use Application\Entity\Db\These;
use Application\Entity\Db\WfEtape;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var These $these
 * @var bool  $updating
 * @var array $diff
 */
?>

<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application <?php echo $this->appInfos()->nom ?>.
</p>
<p>
    Vous êtes informé-e que les coordonnées et disponibilités
    de <?php echo $these->getDoctorant() ?> en vue de son rendez-vous avec la BU
    viennent d'être <?php echo $updating ? "modifiées" : "saisies" ?>.
</p>
<p>
    Cliquez sur ce lien pour accéder à la page correspondante de l'application : <br>
    <?php echo $this->wf($these)->one(WfEtape::CODE_RDV_BU_SAISIE_DOCTORANT); ?>
</p>
