<?php

use Application\Entity\Db\These;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var These $these
 * @var bool  $updating
 * @var string $contact
 */
?>

<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application SoDoct.
</p>
<p>
    Votre dossier est complet.
</p>
<p>
    Vous pouvez récupérer votre attestation de réussite au diplôme de doctorat
    au Bureau des doctorats ou la demander par courriel à
    <a href="mailto:<?php echo $contact ?>>"><?php echo $contact ?></a>.
</p>

