<?php

use Application\Entity\Db\FichierThese;
use Application\Entity\Db\ValiditeFichier;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var FichierThese $fichierRetraite
 * @var ValiditeFichier $validite
 * @var string $url
 */
?>

<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application <?php echo $this->appInfos()->nom ?>.
</p>
<p>
    Le retraitement de votre fichier de thèse est terminé.
</p>
<p>
    <?php $url = $this->urlThese()->setForceCanonical()->archivageThese($fichierRetraite->getThese(), $fichierRetraite->getFichier()->getVersion()) ?>
    Cliquez <a href="<?php echo $url ?>">ici</a> pour accéder à la page correspondante de l'application.
</p>