<?php

use Application\Entity\Db\These;
use Fichier\Entity\Db\VersionFichier;
use Application\Filter\IdifyFilter;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var These $these
 * @var VersionFichier $version
 */
?>

<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application <?php echo $this->appInfos()->nom ?>.
</p>
<p>
    Vous êtes informé-e que <em><?php echo $version->toString() ?></em> de la thèse de <?php echo $these->getDoctorant() ?> vient d'être déposée.
</p>
<p>
    Cliquez sur <a href="<?php echo $this->url('these/depot', ['these' => IdifyFilter::id($these)],
        ['force_canonical' => true]) ?>">ce lien</a> pour accéder à la page correspondante de l'application.
</p>
