<?php

use Application\Entity\Db\Fichier;
use Application\Entity\Db\ValiditeFichier;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var Fichier $fichierRetraite
 * @var string $outputFilePath
 * @var string $url
 */
?>

<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application <?php echo $this->appInfos()->nom ?>.
</p>
<p>
    L'ajout de la page de couverture est maintenant terminé.
</p>
<p>
    <?php $url = $this->urlThese()->setForceCanonical()->telechargerFusion($outputFilePath) ?>
    Cliquez <a href="<?php echo $url ?>">ici</a> pour accéder à la page correspondante au téléchargement de votre manuscrit.
</p>