<?php

/**
 * @var NatureFichier[] $natures;
 * @var Etablissement[] $etablissements;
 * @var string $action
 */

use Application\Entity\Db\Etablissement;
use Application\Entity\Db\NatureFichier;

?>

<form method="post" action="<?php echo $action; ?>">
    <div class="form-group">
        <label for="nature">Nature du fichier : </label>
        <select class="form-control" id="nature" name="nature">
            <?php foreach ($natures as $nature) : ?>
                <option value="<?php echo $nature->getId(); ?>"> <?php echo $nature->getLibelle(); ?> </option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="form-group">
        <label for="etablissement">Établissement lié : </label>
        <select class="form-control" id="etablissement" name="etablissement">
            <option> Aucun </option>
            <?php foreach ($etablissements as $etablissement) : ?>
                <option value="<?php echo $etablissement->getId(); ?>"> <?php echo $etablissement->getLibelle(); ?> </option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="form-group">
    <input type="file" id="fichier" name="fichier"/>
    </div>

    <div class="form-group">
    <input type="submit" class="btn btn-primary action" value="Téléverser">
    </div>
</form>


<style>
    input[type='submit'].action {
        width: 25rem;
        font-weight: bold;
    }
</style>