<?php

namespace Substitution;

use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var \Doctrine\DBAL\Result $result
 * @var \Doctrine\DBAL\Result $operations
 *
 * @see \Substitution\Controller\IndexController::individuAction()
 */
?>

<?php $this->headTitle($this->translate("Logs concernant les individus")) ?>

<h1 class="page-header">
    <span class="fas fa-key"></span>
    <?php echo $this->translate("Logs concernant les individus"); ?>
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace(); ?>

<?php echo $this->partial('substitution/log/_partial/liste', [
    'result' => $result,
    'operations' => $operations,
    'logRoute' => 'substitution/log/individu',
]); ?>
