<?php
/**
 * @var \StepStar\Entity\Db\Log[] $logs
 */
?>

<p>
    Les envois vers STEP/STAR des thèses suivantes ont échoué :
</p>
<ul>
<?php foreach ($logs as $log): ?>

    <li>
        Thèse de <?php echo $log->getThese()->getDoctorant()->getIndividu()->getNomComplet() ?>
        (<?php echo $log->getThese()->getId() ?>), le <?php echo $log->getStartedOnToString() ?> :
        <a href="<?php echo $this->url('step-star/log/consulter', ['log' => $log->getId()]) ?>">log</a>
    </li>

<?php endforeach ?>
</ul>
