<?php
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var string      $text
 */

$queryParams = $this->queryParams();
$urlRechercher = $this->url('fichier/deposes', [], ['query' => $queryParams], true);
$inputTitle = <<<EOS
<div class="these-search-input-help">
    Recherche possible sur 
    <ul>
        <li>le titre de la thèse</li>
        <li>le nom de l'auteur</li>
        <li>le prénom de l'auteur</li>
        <li>le nom du fichier</li>
    </ul>
</div>
EOS;

?>

<form method="post" action="<?php echo $urlRechercher ?>" class="search-form these form-inline">
    <div class="form-group">
        <label class="form-label visually-hidden" for="search-input">Recherche d'une thèse (code, titre de la thèse ; code, nom, prénom de l'auteur) :</label>
        <div class="input-group">
            <div class="input-text"><span class="icon icon-search"></span></div>
            <input type="search"
                   value="<?php echo $text; ?>"
                   name="text"
                   class="form-control"
                   id="search-input"
                   placeholder="<?php echo $this->translate("Entrez 2 caractères au moins...");?>"
                   data-bs-content="<?php echo htmlspecialchars(
                           "<div class=\"these-search-input-help\">".
                           $inputTitle .
                           "</div>"
                   );
                   ?>">
        </div>
    </div>
    <button type="button"
            class="btn btn-secondary"
            onclick="$('form.these input').val('')"
            title="<?php echo $this->translate("Vider");?>" >
        <span class="icon icon-delete iconly"></span>
    </button>
    <button type="submit" class="btn btn-primary">
        <?php echo $this->translate("Rechercher"); ?>
    </button>
<!--    <p class="form-text">Recherche sur le titre, le code national de l'école doctorale, l'unité de recherche de la thèse, le numéro étudiant, le nom, le prénom de l'auteur.</p>-->
</form>

<script>
    $(function() {
        $("#search-input").popover({html: true, trigger: "hover", placement: "bottom"});
    });
</script>