<?php
/**
 * Elément visuel indiquant la validité d'un fichier.
 *
 * Paramètres attendus en entrée :
 * $fichier
 *
 * @var PhpRenderer $this
 * @var FichierThese $fichier
 */

use Application\Entity\Db\FichierThese;
use Application\View\Renderer\PhpRenderer;

$validiteFichier = $fichier->getFichier()->getValidite();
?>

<?php if ($validiteFichier): ?>
    <?php
    $valide = $validiteFichier->getEstValide();
    $label = [null => "Une erreur est survenue lors du test d'archivabilité", true => 'Archivable', false => 'Non archivable'];
    $labelClass = [null => 'warning', true => 'success', false => 'danger'];
    $iconClass = [null => 'warning-sign', true => 'thumbs-up', false => 'thumbs-down'];
    $message = str_replace('|', PHP_EOL, $validiteFichier->getMessage());
    ?>
    <span class="label-validite label label-<?php echo $labelClass[$valide] ?>"
          title="Compte-rendu du test: <?php echo htmlspecialchars($message) ?>"><span
            class="glyphicon glyphicon-<?php echo $iconClass[$valide] ?>"></span> <?php echo $label[$valide] ?></span>
    <?php if ($validiteFichier->getEstValide() === null): ?>
        <div class="alert alert-danger alert-sm">
            Le test d'archivabilité du fichier a rencontré un problème indépendant de notre volonté. <br>
            Veuillez supprimer le fichier puis réessayer ultérieurement ou signaler le problème à
            l'adresse figurant sur la page
            <a title="Cliquez pour accéder à la page" href="<?php echo $this->url('contact') ?>">Contact</a>.
        </div>
    <?php endif ?>
<?php endif ?>