<?php
/**
 * Eléments concernant la validité (archivabilité) d'un fichier.
 *
 * Paramètres attendus en entrée :
 * $fichier
 *
 * @var PhpRenderer $this
 * @var FichierThese $fichier
 */

use Application\Entity\Db\FichierThese;
use Application\View\Renderer\PhpRenderer;

$canConform = true;//$this->isAllowed(Privileges::getResourceId(Privileges::PIECE_JUSTIFICATIVE_TELECHARGEMENT));

$validiteFichier = $fichier->getFichier()->getValidite();
?>

<!-- Validité du fichier -->
<?php if ($validiteFichier): ?>
    <?php echo $this->partial('application/fichier-these/partial/label-validite', ['fichier' => $fichier]) ?>
<?php endif ?>