<?php

namespace Substitution;

use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var \Doctrine\DBAL\Result $result
 *
 * @see \Substitution\Controller\IndexController::unite-rechAction()
 */
?>

<?php echo $this->partial('substitution/doublon/_partial/liste', [
    'type' => 'unite-rech',
    'result' => $result,
    'attributes' => ['code' => 'Code'],
    'routeName' => 'unite-recherche/voir',
    'routeParamName' => 'unite-recherche',
]); ?>

