<?php

use Structure\Entity\Db\Etablissement;
use These\Entity\Db\These;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var string      $text
 */

/**
 * @param string $paramName
 * @param string $paramValue
 * @param array $queryParams
 * @return string
 */
$urlFiltrer = function ($paramName, $paramValue, $queryParams) {
    $queryParams[$paramName] = $paramValue;
    return $this->url('tableau-de-bord/anomalie', [], ['query' => $queryParams], true);
};

//preparation des etablissements
$paramEtablissements = [];
$paramEtablissements[] = ['value' => '',                             'label' => $this->translate("Tous") ];
/** @var Etablissement[] $etablissements */
foreach ($etablissements as $etablissement) {
    $paramEtablissements[] = ['value' => $v = $etablissement->getStructure()->getCode(), 'label' => $etablissement->getStructure()->getSigle() ];
}

echo $this->filterPanel([

    $this->translate("Établissement") => [
        'paramName' => 'etablissement',
        'paramConfig' => $paramEtablissements,
        'filterUrl' => $urlFiltrer,
    ],
]) ?>


