<?php

namespace Admission\Provider\Template;

class MailTemplates {

    const OPERATION_ATTENDUE = 'ADMISSION_OPERATION_ATTENDUE';
    const VALIDATION_AJOUTEE = 'ADMISSION_VALIDATION_AJOUTEE';
    const DERNIERE_VALIDATION_AJOUTEE = 'ADMISSION_DERNIERE_VALIDATION_AJOUTEE';
    const VALIDATION_SUPPRIMEE = 'ADMISSION_VALIDATION_SUPPRIMEE';
    const AVIS_AJOUTE = 'ADMISSION_AVIS_AJOUTE';
    const AVIS_MODIFIE = 'ADMISSION_AVIS_MODIFIE';
    const AVIS_SUPPRIME = 'ADMISSION_AVIS_SUPPRIME';
    const COMMENTAIRES_AJOUTES = 'ADMISSION_COMMENTAIRES_AJOUTES';
    const NOTIFICATION_GESTIONNAIRE = 'ADMISSION_NOTIFICATION_GESTIONNAIRE';
    const NOTIFICATION_DOSSIER_COMPLET = 'ADMISSION_NOTIFICATION_DOSSIER_COMPLET';
    const NOTIFICATION_DOSSIER_INCOMPLET = 'ADMISSION_NOTIFICATION_DOSSIER_INCOMPLET';
}