<?php

namespace Admission\Provider\Template;

class MailTemplates {

    const OPERATION_ATTENDUE = 'ADMISSION_OPERATION_ATTENDUE';
    const VALIDATION_AJOUTEE = 'ADMISSION_VALIDATION_AJOUTEE';
    const VALIDATION_SUPPRIMEE = 'ADMISSION_VALIDATION_SUPPRIMEE';
    const COMMENTAIRES_AJOUTES = 'ADMISSION_COMMENTAIRES_AJOUTES';
    const NOTIFICATION_GESTIONNAIRE = 'ADMISSION_NOTIFICATION_GESTIONNAIRE';
}