<?php

namespace Admission\Provider\Template;

class TexteTemplates {

    const ADMISSION_INFO_HANDICAP = 'ADMISSION_INFO_HANDICAP';
    const ADMISSION_INFO_VAE = 'ADMISSION_INFO_VAE';
    const ADMISSION_INFO_COTUTELLE = 'ADMISSION_INFO_COTUTELLE';
    const ADMISSION_INFO_COENCADREMENT = 'ADMISSION_INFO_COENCADREMENT';

    const CODES = [
        self::ADMISSION_INFO_HANDICAP,
        self::ADMISSION_INFO_VAE,
        self::ADMISSION_INFO_COTUTELLE,
        self::ADMISSION_INFO_COENCADREMENT
    ];
}