<?php
/**
 * @var \These\Entity\Db\These $these
 */

use Application\Entity\Db\Role;
use Individu\View\Helper\IndividuUsurpationHelper;
use These\Entity\Db\Acteur;
use These\Filter\ActeursFormatter;

$acteursFormatter = new ActeursFormatter();
$acteursFormatter->paramFilter(["role" => [
    Role::CODE_DIRECTEUR_THESE,
    Role::CODE_CODIRECTEUR_THESE,
    Role::CODE_MEMBRE_JURY,
    Role::CODE_PRESIDENT_JURY,
    Role::CODE_RAPPORTEUR_JURY,
    Role::CODE_RAPPORTEUR_ABSENT,
]]);
$acteursFormatter->paramDisplay(["role" => true, "complement" => true, "qualite" => true, "etablissement" => true]);
$acteursFormatter->asArray();
$acteurs = $these->getActeursSorted();
$results = $acteursFormatter->doFormat($acteurs->toArray());
?>

<dl class="row">

    <?php if ($results): ?>
        <?php
        // Affichage des acteurs de la these
        $previous = "";
        foreach ($results as $result) {
            $aucunSupannIdDansIndividu = isset($result['alerte-supann-id']);
            /** @var Acteur $acteur */
            $acteur = $result["acteur"];
            if ($previous != $result["role"]) {
                echo "</dd>";
                echo '<dt class="col-md-3">' . $result["role"] . "</dt>";
                echo '<dd class="col-md-9">';
                $previous = $result["role"];
            }
            $ligne = [];
            if (isset($result["nom"])) {
                $ligne[] = $result["nom"];
            }
            if (isset($result["complement"])) {
                $ligne[] = "<strong>" . $result["complement"] . "</strong>";
            }
            if (isset($result["qualite"]) && trim($result["qualite"]) != "") {
                $ligne[] = $result["qualite"];
            }
            if (isset($result["etablissement"]) && trim($result["etablissement"]) != "") {
                $ligne[] = $result["etablissement"];
            }
            if ($acteur->estDirecteur() && $aucunSupannIdDansIndividu) {
                if (empty($utilisateurs[$acteur->getId()])) {
                    $ligne[] = sprintf('<span class="fas fa-exclamation-triangle text-danger" title="%s"></span>',
                        $result['alerte-supann-id']);
                } else {
                    $ligne[] = sprintf('<span class="fas fa-info-circle text-warning" title="Compte local"></span>');
                }
//                    if ($canCreate) {
//                        $ligne[] = sprintf('<a href="%s" class="btn btn-sm btn-warning">Gérer l\'utilisateur</a>',
//                            $this->url('utilisateur/gerer-utilisateur', ['individu' => $acteur->getIndividu()->getId()], [], true));
//                    }
            }

            $ligne = implode(" &ndash; ", $ligne);
            echo $ligne;

            if (($acteur->estDirecteur() || $acteur->estCodirecteur() || $acteur->estRapporteur() || $acteur->estRapporteurAbsent()) && !isset($result['alerte-supann-id'])) {
                // bouton d'usurpation d'identité
                $individuUsurpationHelper = $this->plugin('individuUsurpation');
                /* @var $individuUsurpationHelper IndividuUsurpationHelper */
                $individuUsurpationHelper->setIndividu($acteur->getIndividu());
                echo $individuUsurpationHelper();
            }

            echo "<br/>";
        }
        ?>
    <?php else : ?>
        <dt class="col-md-3">Direction</dt>
        <dd class="col-md-9">
        <span class='text-danger'>
            <span class='fas fa-exclamation-triangle'></span>
            <?php echo $this->translate("Aucune direction renseignée") ?>
        </span>
        </dd>
    <?php endif ?>

</dl>
