<?php
/**
 * @var \These\Entity\Db\These $these
 *
 */

use Individu\View\Helper\IndividuUsurpationHelper;
use These\Entity\Db\Acteur;
use These\Filter\ActeursFormatter;
use These\Provider\Privilege\CoEncadrantPrivileges;

$canCoEncadrantAfficher = $this->isAllowed(CoEncadrantPrivileges::getResourceId(CoEncadrantPrivileges::COENCADRANT_AFFICHER));
$canCoEncadrantGerer = false && $this->isAllowed(CoEncadrantPrivileges::getResourceId(CoEncadrantPrivileges::COENCADRANT_GERER));

$acteursFormatter = new ActeursFormatter();
$acteursFormatter->paramDisplay(["role" => true, "complement" => true, "qualite" => true, "etablissement" => true]);
$acteursFormatter->asArray();
$acteurs = $these->getActeursSorted();
$results = $acteursFormatter->doFormat($acteurs->toArray());
?>

<dl class="row">

    <?php if ($results): ?>
        <?php
        // Affichage des acteurs de la these
        $previous = "";
        foreach ($results as $result) {
            $aucunSupannIdDansIndividu = isset($result['alerte-supann-id']);
            /** @var Acteur $acteur */
            $acteur = $result["acteur"];
            if ($previous != $result["role"]) {
                echo "</dd>";
                echo '<dt class="col-md-4">' . $result["role"] . "</dt>";
                echo '<dd class="col-md-8">';
                $previous = $result["role"];
            }
            $ligne = [];
            if (isset($result["nom"])) {
                $ligne[] = $result["nom"];
            }
            if (isset($result["complement"])) {
                $ligne[] = "<strong>" . $result["complement"] . "</strong>";
            }
            if (isset($result["qualite"]) && trim($result["qualite"]) != "") {
                $ligne[] = $result["qualite"];
            }
            if (isset($result["etablissement"]) && trim($result["etablissement"]) != "") {
                $ligne[] = $result["etablissement"];
            }
            if ($acteur->estDirecteur() && $aucunSupannIdDansIndividu) {
                if (empty($utilisateurs[$acteur->getId()])) {
                    $ligne[] = sprintf('<span class="fas fa-exclamation-triangle text-danger" title="%s"></span>',
                        $result['alerte-supann-id']);
                } else {
                    $ligne[] = sprintf('<span class="fas fa-info-circle text-warning" title="Compte local"></span>');
                }
//                    if ($canCreate) {
//                        $ligne[] = sprintf('<a href="%s" class="btn btn-sm btn-warning">Gérer l\'utilisateur</a>',
//                            $this->url('utilisateur/gerer-utilisateur', ['individu' => $acteur->getIndividu()->getId()], [], true));
//                    }
            }

            $ligne = implode(" &ndash; ", $ligne);
            echo $ligne;

            if (($acteur->estDirecteur() || $acteur->estCodirecteur() || $acteur->estRapporteur() || $acteur->estRapporteurAbsent()) && !isset($result['alerte-supann-id'])) {
                // bouton d'usurpation d'identité
                $individuUsurpationHelper = $this->plugin('individuUsurpation');
                /* @var $individuUsurpationHelper IndividuUsurpationHelper */
                $individuUsurpationHelper->setIndividu($acteur->getIndividu());
                echo $individuUsurpationHelper();
            }

            echo " &nbsp;";

            if ($canCoEncadrantAfficher and $acteur->estCoEncadrant()) {
                echo " <a href='" . $this->url('co-encadrant/historique', ['co-encadrant' => $acteur->getId()], [], true) . "'>";
                echo "<span class='icon icon-voir' title='Voir historique de co-encadrement'></span></a>";
            }
            if ($canCoEncadrantGerer and $acteur->estCoEncadrant()) {
                echo " <a href='" . $this->url('co-encadrant/retirer-co-encadrant', ['these' => $these->getId(), 'co-encadrant' => $acteur->getId()], [], true) . "'>";
                echo "<span class='icon icon-delete iconly' title='Retirer le co-encadrant'></span></a>";
            }

            echo "<br/>";
        }
        ?>
    <?php else : ?>
        <dt class="col-md-4">Encadrement</dt>
        <dd class="col-md-8">
        <span class='text-danger'>
            <span class='fas fa-exclamation-triangle'></span>
            <?php echo $this->translate("Aucun encadrement renseigné") ?>
        </span>
        </dd>
    <?php endif ?>

    <?php if ($results && $canCoEncadrantGerer) : ?>
        <dt class="col-md-4"></dt>
        <dd class="col-md-8">
            <a <?php /**  @see CoEncadrantController::ajouterCoEncadrantAction() */ ?>
                    class="btn btn-primary ajax-modal" data-event="modification"
                    href="<?php echo $this->url('co-encadrant/ajouter-co-encadrant', ['these' => $these->getId()], [], true); ?>"
            >
                <span class="icon icon-plus"></span>
                Ajouter un co-encadrant
            </a>
        </dd>
    <?php endif; ?>

</dl>
