<?php
/**
 * @var These $these
 * @var bool $estDoctorant
 * @var string $mailContact
 * @var string $etatMailContact
 * @var string $modifierEmailContactConsentUrl
 * @var string $modifierEmailContactUrl
 * @var string $modifierPersopassUrl
 *
 */

use Application\Entity\Db\DomaineHal;
use Doctorant\Provider\Privilege\DoctorantPrivileges;
use Doctrine\ORM\PersistentCollection;
use Individu\Provider\Privilege\IndividuPrivileges;
use Individu\View\Helper\IndividuUsurpationHelper;
use These\Entity\Db\These;
use These\Provider\Privilege\ThesePrivileges;
use UnicaenAuth\Provider\Privilege\Privileges;

$canVoirEmailContact = $this->isAllowed($these, DoctorantPrivileges::DOCTORANT_AFFICHER_EMAIL_CONTACT);
$canEditEmailContact = $this->isAllowed($these, DoctorantPrivileges::DOCTORANT_MODIFIER_EMAIL_CONTACT);
$canEditEmailContactConsent = $this->isAllowed($these, DoctorantPrivileges::DOCTORANT_MODIFIER_EMAIL_CONTACT);
$emailContactModifiedEvent = 'email-contact-modified-event';
$emailContactConsentModifiedEvent = 'email-contact-consent-modified-event';
$canDomaineHalModifier = $this->isAllowed($these, ThesePrivileges::THESE_MODIFICATION_DOMAINES_HAL_THESE);
?>

<dl class="row generalites">
    <dt class="col-md-3">
        <?php echo $this->translate("Établissement d'inscription"); ?>
    </dt>
    <dd class="col-md-9">
        <?php if ($these->getEtablissement()): ?>
            <span class="text-structure etablissement"><?php echo $these->getEtablissement()->getStructure()->getLibelle() ?></span>
        <?php else: ?>
            <div class='alert alert-sm alert-warning'>
                <span class='fas fa-exclamation-triangle'></span> Aucun établissement n'est renseignée.
            </div>
        <?php endif; ?>
    </dd>

    <dt class="col-md-3">
        <?php echo $this->translate("Doctorant"); ?>
    </dt>
    <dd class="col-md-8">
        <?php
            $nomComplet = $these->getDoctorant()->getIndividu()->getNomComplet(true, true, true);
            $dateNaissance = $these->getDoctorant()->getIndividu()->getDateNaissanceToString();
            echo !empty($dateNaissance) ? sprintf("%s (%s)", $nomComplet, $dateNaissance) : $nomComplet;
        ?>
        <?php
        $canVisualiserIndividu = $this->isAllowed($these->getDoctorant()->getIndividu(), IndividuPrivileges::INDIVIDU_CONSULTER);
        $canVisualiserIndividu = $this->isAllowed(Privileges::getResourceId(IndividuPrivileges::INDIVIDU_CONSULTER));
        if ($canVisualiserIndividu) {
            echo " <a href='".$this->url('individu/voir', ['individu' => $these->getDoctorant()->getIndividu()->getId()], [], true) ."'>";
            echo "<span class='icon icon-voir' title='Accéder à la fiche détaillée de cet individu'></span></a>";
        }
        ?>
        <?php
        // bouton d'usurpation d'identité
        $individuUsurpationHelper = $this->plugin('individuUsurpation'); /* @var $individuUsurpationHelper IndividuUsurpationHelper */
        $individuUsurpationHelper->setIndividu($these->getDoctorant()->getIndividu());
        echo $individuUsurpationHelper();
        ?>
        <br>

        <strong>
            <?php echo $this->translate("Nationalité :"); ?>
        </strong>
        <?php echo $these->getDoctorant()->getIndividu() && $these->getDoctorant()->getIndividu()->getPaysNationalite() ?
            $these->getDoctorant()->getIndividu()->getPaysNationalite()->getLibelleNationalite() :
            null;?>
        <br>

        <strong>
            <?php echo $this->translate("N° étudiant :"); ?>
        </strong>
        <?php echo $these->getDoctorant()->getNumeroEtudiant() ?> <br>

        <strong>
            <?php echo $this->translate("Adresse électronique institutionnelle :"); ?>
        </strong>
        <?php if ($email = $these->getDoctorant()->getIndividu()->getEmailPro()): ?>
            <a href="mailto: <?php echo $email ?>"><?php echo $email ?></a>
        <?php else: ?>
            <?php echo $this->translate("(Inconnu)"); ?>
        <?php endif ?>

        <?php if ($canVoirEmailContact) : ?>
            <br>
            <strong>
                <?php echo $this->translate("Adresse de contact :"); ?>
            </strong>
            <?php if ($mailContact = $these->getDoctorant()->getIndividu()->getEmailContact()): ?>
                <a href="mailto: <?php echo $mailContact = $these->getDoctorant()->getIndividu()->getEmailContact() ?>"><?php echo $mailContact ?></a>
            <?php else: ?>
                (Non renseignée)
            <?php endif; ?>
            <?php if ($canEditEmailContact): ?>
                <a href="<?php echo $modifierEmailContactUrl ?>"
                   title="Modifer l'adresse de contact"
                   data-event="<?php echo $emailContactModifiedEvent ?>"
                   class="btn btn-secondary btn-sm ajax-modal">
                    <?php echo $this->translate(($mailContact ? "Modifier" : "Renseigner") .  " l'adresse de contact"); ?>
                </a>
            <?php endif ?>
            <?php if ($canEditEmailContactConsent): ?>
                <a href="<?php echo $modifierEmailContactConsentUrl ?>"
                   title="Votre consentement à utiliser l'adresse de contact"
                   data-event="<?php echo $emailContactConsentModifiedEvent ?>"
                   class="btn btn-secondary btn-sm ajax-modal">
                    <?php echo $this->translate("Consentement"); ?>
                </a>
            <?php endif ?>
        <?php endif; ?>
    </dd>

    <dt class="col-md-3">
        <?php echo $this->translate("Discipline SISE"); ?>
    </dt>
    <dd class="col-md-8"><?php echo $these->getDiscipline() ?></dd>

    <dt class="col-md-3">Domaine(s) HAL</dt>
    <dd class="col-md-9">
        <?php
        if ($these->getDomainesHal() instanceof PersistentCollection && $these->getDomainesHal()->isEmpty()){ ?>
            <em> Aucun domaine HAL de renseigné </em>
        <?php }else{ ?>
            <ul>
                <?php foreach($these->getDomainesHal() as $domaine){ ?>
                    <li>
                        <?php
                        /** @var DomaineHal $domaine */
                        echo $domaine->getFrDomainS();
                        ?>
                    </li>
                <?php } ?>
            </ul>
        <?php }
        if($canDomaineHalModifier){?>
            <td>
                <div class="float-end">
                    <a  <?php /**  @see \These\Controller\DomaineHalSaisieController::saisieDomaineHalAction() */ ?>
                            class="ajax-modal" data-event="modification"
                            href="<?php echo $this->url('these/saisie-domaine-hal', ['these' => $these->getId()], [], true); ?>"
                    >
                        <?php if ($these->getDomainesHal() instanceof PersistentCollection && $these->getDomainesHal()->isEmpty()){ ?>
                            <span class="icon icon-plus"></span>
                        <?php }else{ ?>
                        <span class="icon icon-edit"></span>
                        <?php } ?>
                    </a>
                </div>
            </td>
        <?php } ?>
    </dd>
</dl>
