<?php
/**
 * @var These $these
 * @var bool $useTitreThese
 * @var int $length
 * @var boolean $description
 */

if (! isset($length)) $length = 40;

use These\Entity\Db\These;
use UnicaenApp\Util;

$class = $these->estConfidentielle() ? 'text-danger' : '';
?>

<?php if (isset($useTitreThese) && $useTitreThese): ?>
    <span class="<?php echo $class ?>"
          title="<?php echo $titre = $these->getTitre() ?>"><?php echo trim($titre) ? Util::truncatedString($titre, $length) : "(Aucun titre)" ?></span>
<?php else: ?>
    <span class="<?php echo $class ?>"><?php echo $these->getDoctorant()->getIndividu()->getNomComplet() ?></span>
<?php endif ?>

<?php if ($these->estConfidentielle()): ?>
    <?php $content = sprintf('<span class="text-danger">Confidentielle jusqu\'au %s</span>', $these->getDateFinConfidentialiteToString()) ?>
    <span class="text-danger"
       data-bs-toggle="popover"
       data-bs-content="<?php echo htmlspecialchars($content) ?>"
       data-bs-trigger="hover"
       data-bs-html="true"
       data-bs-placement="bottom"><span class="badge bg-danger">CONFIDENTIELLE</span></span>
<?php endif ?>

<?php if (isset($description) && $description !== false) : ?>
    <a title="Thèse"
       data-bs-toggle="popover"
       data-bs-content="<?php echo htmlspecialchars($this->partial('these/these/partial/fiche')) ?>"
       data-bs-trigger="click"
       data-bs-placement="bottom"
       data-bs-html="true"
       role="button"><span class="fas fa-list-alt"></span>
    </a>
<?php endif; ?>