<?php

namespace UnicaenAvis\Hydrator;

use Doctrine\Laminas\Hydrator\DoctrineObject;
use UnicaenAvis\Service\AvisServiceAwareTrait;

class AvisTypeHydrator extends DoctrineObject
{
    use AvisServiceAwareTrait;

    public function extract(object $object): array
    {
        return parent::extract($object); // TODO: Change the autogenerated stub
    }

    public function hydrate(array $data, object $object)
    {
        return parent::hydrate($data, $object); // TODO: Change the autogenerated stub
    }
}