<?php

/**
 * @see \These\Controller\CoEncadrantController::historiqueAction()
 * @var Acteur $coencadrant
 * @var These[] $encours
 * @var These[] $closes
 */

use These\Entity\Db\Acteur;
use These\Entity\Db\These;

$denomination = $coencadrant->getIndividu()->getPrenom1() . " " . $coencadrant->getIndividu()->getNomUsuel();

$this->headTitle('Historique de co-encadrement de ' . $denomination);
?>

<h1 class="page-header">
    Historique de co-encadrement de <?php echo $denomination; ?>
</h1>

<div class="main">

    <a href="<?php echo $this->url('co-encadrant/generer-justificatif-coencadrements', ['co-encadrant' => $coencadrant->getId()], [], true); ?>" class="btn btn-primary">
        Générer justificatif
    </a>

    <h2> Thèses en cours
        <span class="badge bg-secondary"> <?php echo count($encours); ?></span>
    </h2>

    <?php echo $this->partial('partial/table-these', ['theses' => $encours]); ?>

    <h2>
        Thèses closes
        <span class="badge bg-secondary"> <?php echo count($closes); ?></span>
    </h2>

    <?php echo $this->partial('partial/table-these', ['theses' => $closes]); ?>

</div>
