-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sygaldb.unicaen.fr;sid=SYGLPROD;port=1523

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS individu_rech_update ON individu CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_individu_rech_update() RETURNS trigger AS $BODY$
DECLARE
    v_haystack text := individu_haystack(NEW.NOM_USUEL, NEW.NOM_PATRONYMIQUE, NEW.PRENOM1, NEW.EMAIL, NEW.SOURCE_CODE);
  BEGIN
    IF TG_OP = 'INSERT' THEN
      insert into INDIVIDU_RECH(ID, HAYSTACK) values (NEW.ID, v_haystack);
    END IF;
    IF TG_OP = 'UPDATE' THEN
      UPDATE INDIVIDU_RECH SET HAYSTACK = v_haystack where ID = NEW.ID;
    END IF;
    IF TG_OP = 'DELETE' THEN
      delete from INDIVIDU_RECH where id = OLD.ID;
    END IF;
  IF TG_OP = 'DELETE' THEN
	RETURN OLD;
ELSE
	RETURN NEW;
END IF;

END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_individu_rech_update() FROM PUBLIC;

CREATE TRIGGER individu_rech_update
	AFTER INSERT OR UPDATE OR DELETE ON individu FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_individu_rech_update();

