<?php

namespace RapportActivite;

use Application\Constants;
use Application\Entity\Db\Role;
use Application\Filter\FinancementFormatter;
use Application\Filter\IdifyFilter;
use Application\View\Renderer\PhpRenderer;
use RapportActivite\Entity\Db\RapportActivite;
use RapportActivite\Provider\Privilege\RapportActivitePrivileges;
use These\Filter\ActeursFormatter;

/**
 * @var PhpRenderer $this
 * @var RapportActivite $rapport
 * @var \RapportActivite\Entity\RapportActiviteOperationInterface[] $operations
 * @var \Application\Entity\AnneeUniv $anneeUnivCourante
 *
 * @see \RapportActivite\Controller\RapportActiviteController::consulterAction()
 */

$acteursFormatterDirecteurs = new ActeursFormatter();
$acteursFormatterDirecteurs->asSeparated()
    ->paramDisplay(['role' => false, "qualite" => true, "etablissement" => true,])
    ->paramFilter((['role' => Role::CODE_DIRECTEUR_THESE]));
$acteursFormatterCodirecteurs = new ActeursFormatter();
$acteursFormatterCodirecteurs->asSeparated()
    ->paramDisplay(['role' => false, "qualite" => true, "etablissement" => true,])
    ->paramFilter((['role' => Role::CODE_CODIRECTEUR_THESE]));
$acteursFormatterCoencadrants = new ActeursFormatter();
$acteursFormatterCoencadrants->asSeparated()
    ->paramDisplay(['role' => false, "qualite" => true, "etablissement" => true,])
    ->paramFilter((['role' => Role::CODE_CO_ENCADRANT]));

$financementFormatter = $this->financementFormatter();
$financementFormatter->setSortBy(FinancementFormatter::SORT_BY_DATE);
$financementFormatter->setDisplayAs(FinancementFormatter::DISPLAY_AS_HTML_LINES);

$ajaxModalEvent = 'EVENT_AVIS_SAISI';

$these = $rapport->getThese();
$canEdit =
    $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_MODIFIER_TOUT) ||
    $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_MODIFIER_SIEN);
$canDel =
    $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_SUPPRIMER_TOUT) ||
    $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_SUPPRIMER_SIEN);
$canDl =
    $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_TELECHARGER_TOUT) ||
    $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_TELECHARGER_SIEN);
$canGen =
    $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_GENERER_TOUT) ||
    $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_GENERER_SIEN);
?>

<?php $this->headTitle($this->translate($title = (string)$rapport))
    ->prepend($rapport->getThese()->getDoctorant()->getIndividu()->getNomUsuel()) ?>

<h1 class="page-header">
    <?php echo $this->translate($title); ?>
    <small><?php echo $this->partial('these/these/partial/titre', ['these' => $rapport->getThese()]) ?></small>
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace(); ?>

<div class="row informations-compl-div" style="margin-left: 2px;">
    <div class="col-md-6 informations-compl-card information-etat-card -etat-card"
         data-bs-toggle="tooltip" data-bs-original-title="Création du rapport d'activité">
        <span class="fas fa-clock"></span>
        <h2>
            par <?php echo $rapport->getHistoCreateur() ?> le
            <?php echo $rapport->getHistoCreation()->format('d/m/Y à H:i') ?>
        </h2>
    </div>
    <div class="col-md-6">
        <?php if ($canEdit): ?>
            <a class="btn btn-primary" href="<?php echo $this->url('rapport-activite/modifier', ['rapport' => $rapport->getId()]) ?>">
                <span class="icon icon-modifier"></span> Modifier ce rapport d'activité
            </a>
        <?php endif; ?>

        <?php if ($canDel): ?>
            <a class="btn btn-danger"
               href="<?php echo $this->url('rapport-activite/supprimer', ['rapport' => $rapport->getId()]) ?>"
               data-toggle="confirmationx"
               data-bs-toggle="tooltip"
               data-bs-html="true"
               title="Une confirmation avant la suppression vous sera demandée">
                <span class="icon icon-supprimer"></span>
                Supprimer ce rapport d'activité
            </a>
        <?php endif; ?>

        <?php if ($canDl): ?>
            <a class="btn btn-info"
               href="<?php echo $this->url('rapport-activite/telecharger', ['rapport' => $rapport->getId()]) ?>">
                <span class="icon icon-telecharger"></span>
                Télécharger ce rapport d'activité
            </a>
        <?php endif; ?>

        <?php if ($canGen): ?>
            <a class="btn btn-primary"
               href="<?php echo $this->url('rapport-activite/generer', ['rapport' => $rapport->getId()]) ?>">
                <span class="icon icon-pdf"></span>
                Générer et télécharger ce rapport au format PDF
            </a>
        <?php endif; ?>
    </div>
</div>

<div class="rapport-activite-container">

    <?php if ($rapport->getParDirecteurTheseMotif()): ?>
        <div class="alert alert-warning">
            <span class="icon icon-info"></span>
            <b>Motif de la non saisie du rapport par le doctorant (en cas d’incapacité du doctorant) : </b>
            <?php echo $rapport->getParDirecteurTheseMotif() ?>
        </div>
    <?php endif; ?>

    <?php if ($fichier = $rapport->getFichier()): ?>
        Fichier téléversé :
        <?php if ($canDl): ?>
            <?php $returnUrl = $this->url('rapport-activite/consulter', ['these' => $these->getId(), 'rapport' => IdifyFilter::id($rapport)]) ?>
            <a href="<?php echo $this->url('rapport-activite/telecharger', ['rapport' => IdifyFilter::id($rapport)], ['query' => ['redirect' => $returnUrl]]) ?>"
               title="Cliquez pour télécharger">
                <?php echo $fichier->getNom() ?>
            </a>
        <?php else: ?>
            <?php echo $fichier->getNom() ?>
        <?php endif; ?>
        <span class="icon icon-info text-info"
              title="Il s'agit d'un rapport non dématérialisé téléversé dans l'ancienne version du module Rapport d'activité"></span>
    <?php endif; ?>

    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" id="informations-tab" data-bs-toggle="tab" data-bs-target="#informations"
                    type="button" role="tab" aria-controls="informations" aria-selected="true">Informations générales
                (General information)
            </button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="formations-tab" data-bs-toggle="tab" data-bs-target="#formations" type="button" role="tab" aria-controls="formations" aria-selected="false">Formations/Activités (Training/Activities)</button>
        </li>
        <?php if ($rapport->getCalendrierPrevionnelFinalisationEnabled($anneeUnivCourante) && $rapport->getCalendrierPrevionnelFinalisation() !== null): ?>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="calendrier-tab" data-bs-toggle="tab" data-bs-target="#calendrier" type="button" role="tab" aria-controls="calendrier" aria-selected="false">Calendrier prévisionnel de fin de thèse (Provisional timetable for completion of thesis)</button>
            </li>
        <?php endif; ?>
        <?php if ($rapport->getPreparationApresTheseEnabled() || $rapport->getPerspectivesApresTheseEnabled()): ?>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="apres-tab" data-bs-toggle="tab" data-bs-target="#apres" type="button" role="tab" aria-controls="apres" aria-selected="false">L'après-thèse (After the thesis)</button>
            </li>
        <?php endif; ?>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="commentaires-tab" data-bs-toggle="tab" data-bs-target="#commentaires" type="button" role="tab" aria-controls="commentaires" aria-selected="false">Commentaires (Additional Comments)</button>
        </li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane fade show active" id="informations" role="tabpanel" aria-labelledby="informations-tab">
            <div class="row">
                <h3 class="mt-4 mb-4">Volet administratif / <span class="en">General information</span></h3>

                <div class="col-md-6">
                    <dl>
                        <dt>
                            École doctorale /
                            <span class="en">Doctoral School</span>
                        </dt>
                        <dd>
                            <span class="text-structure ed"><?php echo $these->getEcoleDoctorale() ?></span>
                        </dd>

                        <dt>
                            Établissement d’inscription /
                            <span class="en">Enrollment institution</span>
                        </dt>
                        <dd>
                            <span class="text-structure etablissement"><?php echo $these->getEtablissement() ?></span>
                        </dd>

                        <dt>
                            Unité de recherche /
                            <span class="en">Research unit</span>
                        </dt>
                        <dd>
                            <span class="text-structure ur"><?php echo $these->getUniteRecherche() ?></span>
                        </dd>

                        <dt>
                            Année de 1re inscription en thèse /
                            <span class="en">Starting year of your PhD program</span>
                        </dt>
                        <dd>
                            <?php echo $these->getDatePremiereInscriptionToString() ?>
                        </dd>

                    </dl>
                </div>
                <div class="col-md-6">
                    <dl>
                        <dt>
                            Direction de thèse /
                            <span class="en">Thesis advisor</span>
                        </dt>
                        <dd class="acteurs">
                            <?php
                            $directeurs = $acteursFormatterDirecteurs->filter($these->getActeurs());
                            foreach ($directeurs as $directeur) {
                                echo $acteursFormatterDirecteurs->htmlifyActeur($directeur) . "<br/>";
                            }
                            ?>
                        </dd>

                        <dt>
                            Codirection de thèse /
                            <span class="en">Co-advisor</span>
                        </dt>
                        <dd class="acteurs">
                            <?php $codirecteurs = $acteursFormatterCodirecteurs->filter($these->getActeurs()) ?>
                            <?php if ($codirecteurs): ?>
                                <?php foreach ($codirecteurs as $codirecteur): ?>
                                    <?php echo $acteursFormatterCodirecteurs->htmlifyActeur($codirecteur) . "<br/>" ?>
                                <?php endforeach ?>
                            <?php else: ?>
                                Aucune
                            <?php endif ?>
                        </dd>

                        <dt>
                            Co-encadrement /
                            <span class="en">Additional supervisor</span>
                        </dt>
                        <dd class="acteurs">
                            <?php $coencadrants = $acteursFormatterCoencadrants->filter($these->getActeursByRoleCode(Role::CODE_CO_ENCADRANT)) ?>
                            <?php if ($coencadrants): ?>
                                <?php foreach ($coencadrants as $coencadrant): ?>
                                    <?php echo $acteursFormatterCoencadrants->htmlifyActeur($coencadrant) . "<br/>" ?>
                                <?php endforeach ?>
                            <?php else: ?>
                                Aucune
                            <?php endif ?>
                        </dd>

                        <dt>
                            Cotutelle /
                            <span class="en">Joint supervision</span>
                        </dt>
                        <dd>
                            <?php if ($these->getLibelleEtabCotutelle()): ?>
                                Avec <?php echo $these->getLibelleEtabCotutelle() ?>,
                                <?php echo $these->getLibellePaysCotutelle() ?>
                            <?php else: ?>
                                Aucune
                            <?php endif ?>
                        </dd>

                        <dt>
                            Thèse confidentielle /
                            <span class="en">Confidential research</span>
                        </dt>
                        <dd>
                            <?php echo $these->estConfidentielle() ? "Oui" : "Non" ?>
                        </dd>
                    </dl>
                </div>
            </div>

            <h3 class="mt-4 mb-4">Nature du financement doctoral / <span class="en">Funding information</span></h3>

            <div class="row">
                <div class="col-md-6">
                    <?php if ($these->getFinancements()->isEmpty()): ?>
                        Pas de financement dédié à la thèse.
                    <?php else: ?>
                        <?php echo $financementFormatter->format($these->getFinancements()->toArray()); ?>
                    <?php endif ?>
                </div>
            </div>


            <h3 class="mt-5 mb-4">Activités scientifiques / <span class="en">Scientific activities</span></h3>

            <div class="row">
                <div class="col-md-10">
                    <dl>
                        <dt>Description du projet de recherche</dt>
                        <dd>
                            <?php echo $rapport->getDescriptionProjetRecherche() ?>
                        </dd>
                        <dt>Principaux résultats obtenus</dt>
                        <dd>
                            <?php echo $rapport->getPrincipauxResultatsObtenus() ?>
                        </dd>
                        <dt>Productions scientifiques</dt>
                        <dd>
                            <?php echo $rapport->getProductionsScientifiques() ?>
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="formations" role="tabpanel" aria-labelledby="formations-tab">
            <p class="lead mt-2">Les formations/activités présentées ci-dessous, sont celles suivies/effectuées depuis la première année d'inscription en thèse</p>
            <h3 class="mt-4 mb-4">Formations doctorales thématiques et transversales / <span class="en">Doctoral training</span>
                <span class="badge bg-secondary">
                    <?php echo $rapport->getFormationsSpecifiquesTempsTotal() + $rapport->getFormationsTransversalesTempsTotal() + $rapport->getActionsDiffusionCultureScientifiqueTempsTotal()?> h
                </span>
            </h3>

            <div class="row">
                <div class="col-md-6 liste-formations">
                    <dl>
                        <?php $formationsArray = $rapport->getFormationsSpecifiques() ?>
                        <dt>Formations spécifiques/thématiques / <span class="en">Specific training</span>
                            <span class="badge bg-secondary"><?php echo count($formationsArray) ?> formation(s) / <?php echo $rapport->getFormationsSpecifiquesTempsTotal() ?> h</span>
                        </dt>
                            <?php if ($formationsArray): ?>
                                <ul>
                                    <?php foreach ($formationsArray as $action): ?>
                                        <li>
                                            <div class="card formation-card shadow-sm p-2">
                                                <div class="d-flex align-items-center">
                                                    <div class="formation-icon text-primary me-2">
                                                        <i class="fas fa-book fa-2x"></i>
                                                    </div>
                                                    <div class="formation-details flex-grow-1">
                                                        <h6 class="mb-0"> <?php echo $action->getIntitule() ?></h6>
                                                        <small class="text-muted">
                                                            Volume horaire : <?php echo $action->getTemps() ?> h</small>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                    <?php endforeach ?>
                                </ul>
                            <?php else: ?>
                                <div class="card formation-card aucune shadow-sm p-2">
                                    <div class="d-flex align-items-center">
                                        <div class="formation-icon text-primary me-2">
                                            <i class="fas fa-book fa-2x"></i>
                                        </div>
                                        <div class="formation-details flex-grow-1">
                                            <h6 class="mb-0">Aucune</h6>
                                        </div>
                                    </div>
                                </div>
                            <?php endif ?>

                        <?php $formationsArray = $rapport->getFormationsTransversales() ?>
                        <dt class="mt-4">Formations transversales/professionnalisantes / <span class="en">Transversal training</span>
                            <span class="badge bg-secondary"><?php echo count($formationsArray) ?> formation(s) / <?php echo $rapport->getFormationsTransversalesTempsTotal() ?> h</span></dt>
                            <?php if ($formationsArray): ?>
                                <ul>
                                    <?php foreach ($formationsArray as $action): ?>
                                        <li>
                                            <div class="card formation-card shadow-sm p-2">
                                                <div class="d-flex align-items-center">
                                                    <div class="formation-icon text-primary me-2">
                                                        <i class="fas fa-book fa-2x"></i>
                                                    </div>
                                                    <div class="formation-details flex-grow-1">
                                                        <h6 class="mb-0"> <?php echo $action->getIntitule() ?></h6>
                                                        <small class="text-muted">
                                                            Volume horaire : <?php echo $action->getTemps() ?> h</small>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                    <?php endforeach ?>
                                </ul>
                            <?php else: ?>
                                <div class="card formation-card aucune shadow-sm p-2">
                                    <div class="d-flex align-items-center">
                                        <div class="formation-icon text-primary me-2">
                                            <i class="fas fa-book fa-2x"></i>
                                        </div>
                                        <div class="formation-details flex-grow-1">
                                            <h6 class="mb-0">Aucune</h6>
                                        </div>
                                    </div>
                                </div>
                            <?php endif ?>

                        <?php $actionsArray = $rapport->getActionsDiffusionCultureScientifique() ?>
                        <dt class="mt-4">Actions de diffusion de la culture scientifique, technique et industrielle
                            (CSTI) / <span class="en">Actions undertaken within the framework of the promotion of scientific, technical and industrial knowledge</span>
                            <span class="badge bg-secondary"><?php echo count($actionsArray) ?> action(s) / <?php echo $rapport->getActionsDiffusionCultureScientifiqueTempsTotal() ?> h</span></dt>
                        <?php if ($actionsArray): ?>
                            <ul>
                                <?php foreach ($actionsArray as $action): ?>
                                    <li>
                                        <div class="card formation-card shadow-sm p-2">
                                            <div class="d-flex align-items-center">
                                                <div class="formation-icon text-primary me-2">
                                                    <i class="fas fa-book fa-2x"></i>
                                                </div>
                                                <div class="formation-details flex-grow-1">
                                                    <h6 class="mb-0"><?php echo $action->getNature() ?></h6>
                                                    <small class="text-muted">
                                                        Public : <?php echo $action->getPublic() ?>
                                                    </small>
                                                    <br>
                                                    <small class="text-muted">
                                                        Temps consacré: <?php echo $action->getTemps() ?> h
                                                    </small>
                                                    <br>
                                                    <small class="text-muted">
                                                        Date
                                                        : <?php echo $action->getDate()->format(Constants::DATE_FORMAT) ?>
                                                    </small>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                <?php endforeach ?>
                            </ul>
                        <?php else: ?>
                            <div class="card formation-card aucune shadow-sm p-2">
                                <div class="d-flex align-items-center">
                                    <div class="formation-icon text-primary me-2">
                                        <i class="fas fa-book fa-2x"></i>
                                    </div>
                                    <div class="formation-details flex-grow-1">
                                        <h6 class="mb-0">Aucune</h6>
                                    </div>
                                </div>
                            </div>
                        <?php endif ?>
                    </dl>
                </div>
            </div>


            <h3 class="mt-4 mb-4">Autres activités / <span class="en">Other activities</span>
                <span class="badge bg-secondary">
                    <?php echo $rapport->getAutresActivitesTempsTotal()?> h
                </span>
            </h3>

            <div class="row">
                <div class="col-md-6 liste-formations">
                    <dl>
                        <?php $autresActivitesArray = $rapport->getAutresActivites() ?>
                        <dt>Autres activités / <span class="en">Other activities</span>
                            <span class="badge bg-secondary"><?php echo count($autresActivitesArray) ?> activité(s) / <?php echo $rapport->getAutresActivitesTempsTotal() ?> h</span></dt>
                        <?php if ($autresActivitesArray): ?>
                            <ul>
                                <?php foreach ($autresActivitesArray as $autreActivite): ?>
                                    <li>
                                        <div class="card formation-card shadow-sm p-2">
                                            <div class="d-flex align-items-center">
                                                <div class="formation-icon text-primary me-2">
                                                    <i class="fas fa-book fa-2x"></i>
                                                </div>
                                                <div class="formation-details flex-grow-1">
                                                    <h6 class="mb-0"><?php echo $autreActivite->getNature() ?></h6>
                                                    <small class="text-muted">
                                                        Public : <?php echo $autreActivite->getPublic() ?>
                                                    </small>
                                                    <br>
                                                    <small class="text-muted">
                                                        Temps consacré : <?php echo $autreActivite->getTemps() ?> h
                                                    </small>
                                                    <br>
                                                    <small class="text-muted">
                                                        Date
                                                        : <?php echo $autreActivite->getDate()->format(Constants::DATE_FORMAT) ?>
                                                    </small>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                <?php endforeach ?>
                            </ul>
                        <?php else: ?>
                            <div class="card formation-card aucune shadow-sm p-2">
                                <div class="d-flex align-items-center">
                                    <div class="formation-icon text-primary me-2">
                                        <i class="fas fa-book fa-2x"></i>
                                    </div>
                                    <div class="formation-details flex-grow-1">
                                        <h6 class="mb-0">Aucune</h6>
                                    </div>
                                </div>
                            </div>
                        <?php endif ?>
                    </dl>
                </div>
            </div>
        </div>
        <?php if ($rapport->getCalendrierPrevionnelFinalisationEnabled($anneeUnivCourante) && $rapport->getCalendrierPrevionnelFinalisation() !== null): ?>
            <div class="tab-pane fade" id="calendrier" role="tabpanel" aria-labelledby="calendrier-tab">
                <div class="row">
                    <div class="col-md-10">
                        <dl>
                            <dt>
                                Calendrier prévisionnel / <span class="en">Provisional timetable (up to 4-5 lines)</span>
                            </dt>
                            <dd>
                                <?php echo $rapport->getCalendrierPrevionnelFinalisation() ?>
                            </dd>
                        </dl>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <?php if ($rapport->getPreparationApresTheseEnabled() || $rapport->getPerspectivesApresTheseEnabled()): ?>
            <div class="tab-pane fade" id="apres" role="tabpanel" aria-labelledby="apres-tab">
                <?php if ($rapport->getPreparationApresTheseEnabled()): ?>
                    <h3 class="mt-4 mb-4">Perspectives de carrière et démarches entreprises / <span class="en">Careers paths and actions undertaken</span></h3>

                    <div class="row">
                        <div class="col-md-10">
                            <?php echo $rapport->getPreparationApresThese() ?>
                        </div>
                    </div>
                <?php endif ?>

                <?php if ($rapport->getPerspectivesApresTheseEnabled()): ?>
                    <h3 class="mt-4 mb-4">Perspectives de carrière et démarches entreprises / <span class="en">Plans after the thesis</span></h3>

                    <div class="row">
                        <div class="col-md-10">
                            <?php echo $rapport->getPerspectivesApresThese() ?>
                        </div>
                    </div>

                <?php endif ?>
            </div>
        <?php endif; ?>
        <div class="tab-pane fade" id="commentaires" role="tabpanel" aria-labelledby="commentaires-tab">
            <h3 class="mt-4 mb-4">Commentaires libres / <span class="en">Additional comments</span></h3>

            <div class="row">
                <div class="col-md-10">
                    <?php if ($commentaires = $rapport->getCommentaires()): ?>
                        <?php echo $commentaires ?>
                    <?php else: ?>
                        Aucun
                    <?php endif ?>
                </div>
            </div>
        </div>
    </div>

    <br>
    <div class="separator"></div>
    <br>


    <h2>Validations et avis</h2>

    <div class="row">
        <div class="col-md-4">
            <?php if ($operations): ?>
                <?php foreach ($operations as $i => $operation): ?>
                    <?php
                    echo $this->partial('rapport-activite/partial/operation-card', [
                        'operation' => $operation,
                        'ajaxModalEvent' => $ajaxModalEvent,
                    ]);
                    ?>
                <?php endforeach ?>
            <?php else: ?>
                Aucune validation ni aucun avis attendus.
            <?php endif ?>
        </div>
    </div>
</div>


<div class="modal fade" id="avisComplemsModal" tabindex="-1" aria-labelledby="avisComplemsModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="avisComplemsModalLabel">Détails de l'avis</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button>
            </div>
            <div class="modal-body">
                <!-- rempli dynamiquement -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
            </div>
        </div>
    </div>
</div>



<script>
    $(function () {
        const avisComplemsModal = document.getElementById('avisComplemsModal')
        avisComplemsModal.addEventListener('show.bs.modal', function (event) {
            // Button that triggered the modal
            const button = event.relatedTarget;
            const logFullContent = $(button).parent().siblings(".log-full-content").html();
            // Update the modal's content.
            const modalBody = avisComplemsModal.querySelector('.modal-body');
            $(modalBody).html(logFullContent);
        });

        // Gestion de la fermeture de la modale de saisie d'un avis
        let ajaxModalEvent = '<?php echo $ajaxModalEvent ?>';
        $("body").on(ajaxModalEvent, function (event) {
            $("body").addClass("loading");
            event.div.modal('hide'); // ferme la fenêtre modale
            window.location.reload();
        });
    })
</script>

