<?php

namespace RapportActivite;

use Application\Constants;
use Application\Entity\Db\Role;
use Application\Filter\FinancementFormatter;
use Application\Filter\IdifyFilter;
use Application\View\Renderer\PhpRenderer;
use RapportActivite\Entity\Db\RapportActivite;
use RapportActivite\Provider\Privilege\RapportActivitePrivileges;
use These\Filter\ActeursFormatter;

/**
 * @var PhpRenderer $this
 * @var RapportActivite $rapport
 * @var \RapportActivite\Entity\RapportActiviteOperationInterface[] $operations
 *
 * @see \RapportActivite\Controller\RapportActiviteController::consulterAction()
 */

$acteursFormatterDirecteurs = new ActeursFormatter();
$acteursFormatterDirecteurs->asSeparated()
    ->paramDisplay(['role' => false, 'complement' => true, "qualite" => true, "etablissement" => true,])
    ->paramFilter((['role' => Role::CODE_DIRECTEUR_THESE]));
$acteursFormatterCodirecteurs = new ActeursFormatter();
$acteursFormatterCodirecteurs->asSeparated()
    ->paramDisplay(['role' => false, 'complement' => true, "qualite" => true, "etablissement" => true,])
    ->paramFilter((['role' => Role::CODE_CODIRECTEUR_THESE]));
$acteursFormatterCoencadrants = new ActeursFormatter();
$acteursFormatterCoencadrants->asSeparated()
    ->paramDisplay(['role' => false, 'complement' => true, "qualite" => true, "etablissement" => true,])
    ->paramFilter((['role' => Role::CODE_CO_ENCADRANT]));

$financementFormatter = $this->financementFormatter();
$financementFormatter->setSortBy(FinancementFormatter::SORT_BY_DATE);
$financementFormatter->setDisplayAs(FinancementFormatter::DISPLAY_AS_HTML_LINES);

$ajaxModalEvent = 'EVENT_AVIS_SAISI';

$these = $rapport->getThese();
$canEdit =
    $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_MODIFIER_TOUT) ||
    $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_MODIFIER_SIEN);
$canDel =
    $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_SUPPRIMER_TOUT) ||
    $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_SUPPRIMER_SIEN);
$canDl =
    $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_TELECHARGER_TOUT) ||
    $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_TELECHARGER_SIEN);
$canGen =
    $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_GENERER_TOUT) ||
    $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_GENERER_SIEN);
?>

<?php $this->headTitle($this->translate($title = (string)$rapport))
    ->prepend($rapport->getThese()->getDoctorant()->getIndividu()->getNomUsuel()) ?>

<h1 class="page-header">
    <?php echo $this->translate($title); ?>
    <small><?php echo $this->partial('these/these/partial/titre', ['these' => $rapport->getThese()]) ?></small>
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace(); ?>

<div class="rapport-activite-container">

    <dl>
        <dt>
            Création du rapport
        </dt>
        <dd>
            <?php echo $rapport->getHistoCreateur() ?> le
            <?php echo $rapport->getHistoCreation()->format('d/m/Y à H:i') ?>
        </dd>

        <?php if ($rapport->getParDirecteurTheseMotif()): ?>
            <dt>
                Motif de la non saisie du rapport par le doctorant (en cas d’incapacité du doctorant)
            </dt>
            <dd>
                <?php echo $rapport->getParDirecteurTheseMotif() ?>
            </dd>
        <?php endif; ?>

        <?php if ($fichier = $rapport->getFichier()): ?>
            <dt>
                Fichier téléversé
            </dt>
            <dd>
                <?php if ($canDl): ?>
                    <?php $returnUrl = $this->url('rapport-activite/consulter', ['these' => $these->getId(), 'rapport' => IdifyFilter::id($rapport)]) ?>
                    <a href="<?php echo $this->url('rapport-activite/telecharger', ['rapport' => IdifyFilter::id($rapport)], ['query' => ['redirect' => $returnUrl]]) ?>"
                       title="Cliquez pour télécharger">
                        <?php echo $fichier->getNom() ?>
                    </a>
                <?php else: ?>
                    <?php echo $fichier->getNom() ?>
                <?php endif; ?>
                <span class="icon icon-info text-info"
                      title="Il s'agit d'un rapport non dématérialisé téléversé dans l'ancienne version du module Rapport d'activité"></span>
            </dd>
        <?php endif; ?>
    </dl>


    <h2>Volet administratif / General information</h2>

    <div class="row">
        <div class="col-md-6">
            <dl>
                <dt>
                    École doctorale / Doctoral School
                </dt>
                <dd>
                    <?php if ($ed = $these->getEcoleDoctorale()): ?>
                        <abbr title="<?php echo $ed->getStructure()->getLibelle() ?>">
                            <?php echo $ed->getStructure()->getCode(); ?>
                        </abbr>
                    <?php endif ?>
                </dd>

                <dt>
                    Établissement d’inscription / Enrollment institution
                </dt>
                <dd>
                    <abbr title="<?php echo $these->getEtablissement()->getStructure()->getLibelle() ?>">
                        <?php echo $these->getEtablissement()->getStructure()->getCode() ?>
                    </abbr>
                </dd>

                <dt>
                    Unité de recherche / Research unit
                </dt>
                <dd>
                    <?php if ($ur = $these->getUniteRecherche()): ?>
                        <abbr title="<?php echo $ur->getStructure()->getLibelle() ?>">
                            <?php echo $ur->getStructure()->getCode(); ?>
                        </abbr>
                    <?php endif ?>
                </dd>

                <dt>
                    Année de 1re inscription en these / Starting year of your PhD program
                </dt>
                <dd>
                    <?php echo $these->getDatePremiereInscriptionToString() ?>
                </dd>

            </dl>
        </div>
        <div class="col-md-6">
            <dl>
                <dt>
                    Direction de thèse / Thesis advisor
                </dt>
                <dd class="acteurs">
                    <?php
                    $directeurs = $acteursFormatterDirecteurs->filter($these->getActeurs());
                    foreach ($directeurs as $directeur) {
                        echo $acteursFormatterDirecteurs->htmlifyActeur($directeur) . "<br/>";
                    }
                    ?>
                </dd>

                <dt>
                    Codirection de thèse / Co-advisor
                </dt>
                <dd class="acteurs">
                    <?php $codirecteurs = $acteursFormatterCodirecteurs->filter($these->getActeurs()) ?>
                    <?php if ($codirecteurs): ?>
                        <?php foreach ($codirecteurs as $codirecteur): ?>
                            <?php echo $acteursFormatterCodirecteurs->htmlifyActeur($codirecteur) . "<br/>" ?>
                        <?php endforeach ?>
                    <?php else: ?>
                        Aucune
                    <?php endif ?>
                </dd>

                <dt>
                    Co-encadrement / Additional supervisor
                </dt>
                <dd class="acteurs">
                    <?php $coencadrants = $acteursFormatterCoencadrants->filter($these->getActeursByRoleCode(Role::CODE_CO_ENCADRANT)) ?>
                    <?php if ($coencadrants): ?>
                        <?php foreach ($coencadrants as $coencadrant): ?>
                            <?php echo $acteursFormatterCoencadrants->htmlifyActeur($coencadrant) . "<br/>" ?>
                        <?php endforeach ?>
                    <?php else: ?>
                        Aucune
                    <?php endif ?>
                </dd>

                <dt>
                    Cotutelle / Joint supervision
                </dt>
                <dd>
                    <?php if ($these->getLibelleEtabCotutelle()): ?>
                        Avec <?php echo $these->getLibelleEtabCotutelle() ?>,
                        <?php echo $these->getLibellePaysCotutelle() ?>
                    <?php else: ?>
                        Aucune
                    <?php endif ?>
                </dd>

                <dt>
                    Thèse confidentielle / Confidential research
                </dt>
                <dd>
                    <?php echo $these->estConfidentielle() ? "Oui" : "Non" ?>
                </dd>
            </dl>
        </div>
    </div>


    <h2>Nature du financement doctoral / Funding information</h2>

    <div class="row">
        <div class="col-md-6">
            <?php if ($these->getFinancements()->isEmpty()): ?>
                (Non renseigné)
            <?php else: ?>
                <?php echo $financementFormatter->format($these->getFinancements()->toArray()); ?>
            <?php endif ?>
        </div>
    </div>


    <h2>Activités scientifiques / Scientific activities</h2>

    <div class="row">
        <div class="col-md-10">
            <dl>
                <dt>Description du projet de recherche</dt>
                <dd>
                    <?php echo $rapport->getDescriptionProjetRecherche() ?>
                </dd>
                <dt>Principaux résultats obtenus</dt>
                <dd>
                    <?php echo $rapport->getPrincipauxResultatsObtenus() ?>
                </dd>
                <dt>Productions scientifiques</dt>
                <dd>
                    <?php echo $rapport->getProductionsScientifiques() ?>
                </dd>
            </dl>
        </div>
    </div>


    <h2>Formations doctorales thématiques et transversales / Doctoral training</h2>

    <div class="row">
        <div class="col-md-8">
            <dl>
                <?php $formationsArray = $rapport->getFormationsSpecifiquesToArray() ?>
                <dt>Formations spécifiques/thématiques / Specific training
                    <span class="badge bg-secondary"><?php echo count($formationsArray) ?></span></dt>
                <dd class="collection">
                    <?php if ($formationsArray): ?>
                        <ul>
                            <?php foreach ($formationsArray as $action): ?>
                                <li>
                                    <dl class="row">
                                        <dt class="col-md-2">Intitulé</dt>
                                        <dd class="col-md-9"><?php echo $action->getIntitule() ?></dd>
                                        <dt class="col-md-2">Volume horaire</dt>
                                        <dd class="col-md-9"><?php echo $action->getTemps() ?> h</dd>
                                    </dl>
                                </li>
                            <?php endforeach ?>
                        </ul>
                        <span class="total">Volume horaire total : <?php echo $rapport->getFormationsSpecifiquesTempsTotal() ?> h</span>
                    <?php else: ?>
                        Aucune
                    <?php endif ?>
                </dd>

                <?php $formationsArray = $rapport->getFormationsTransversalesToArray() ?>
                <dt>Formations transversales/professionnalisantes / Transversal training
                    <span class="badge bg-secondary"><?php echo count($formationsArray) ?></span></dt>
                <dd class="collection">
                    <?php if ($formationsArray): ?>
                        <ul>
                            <?php foreach ($formationsArray as $action): ?>
                                <li>
                                    <dl class="row">
                                        <dt class="col-md-2">Intitulé</dt>
                                        <dd class="col-md-9"><?php echo $action->getIntitule() ?></dd>
                                        <dt class="col-md-2">Volume horaire</dt>
                                        <dd class="col-md-9"><?php echo $action->getTemps() ?> h</dd>
                                    </dl>
                                </li>
                            <?php endforeach ?>
                        </ul>
                        <span class="total">Volume horaire total : <?php echo $rapport->getFormationsTransversalesTempsTotal() ?> h</span>
                    <?php else: ?>
                        Aucune
                    <?php endif ?>
                </dd>

                <?php $actionsArray = $rapport->getActionsDiffusionCultureScientifiqueToArray() ?>
                <dt>Actions de diffusion de la culture scientifique, technique et industrielle (CSTI) / Actions undertaken within the framework of the promotion of scientific, technical and industrial knowledge
                    <span class="badge bg-secondary"><?php echo count($actionsArray) ?></span></dt>
                <dd class="collection">
                    <?php if ($actionsArray): ?>
                        <ul>
                            <?php foreach ($actionsArray as $action): ?>
                                <li>
                                    <dl class="row">
                                        <dt class="col-md-2">Nature</dt>
                                        <dd class="col-md-9"><?php echo $action->getNature() ?></dd>
                                        <dt class="col-md-2">Public</dt>
                                        <dd class="col-md-9"><?php echo $action->getPublic() ?></dd>
                                        <dt class="col-md-2">Temps consacré</dt>
                                        <dd class="col-md-9"><?php echo $action->getTemps() ?> h</dd>
                                        <dt class="col-md-2">Date</dt>
                                        <dd class="col-md-9"><?php echo $action->getDate()->format(Constants::DATE_FORMAT) ?></dd>
                                    </dl>
                                </li>
                            <?php endforeach ?>
                        </ul>
                        <span class="total">Volume horaire total : <?php echo $rapport->getActionsDiffusionCultureScientifiqueTempsTotal() ?> h</span>
                    <?php else: ?>
                        Aucune
                    <?php endif ?>
                </dd>
            </dl>
        </div>
    </div>


    <h2>Autres activités / Other activities</h2>

    <div class="row">
        <div class="col-md-8">
            <dl>
                <?php $autresActivitesArray = $rapport->getAutresActivitesToArray() ?>
                <dt>Autres activités / Other activities
                    <span class="badge bg-secondary"><?php echo count($autresActivitesArray) ?></span></dt>
                <dd class="collection">
                    <?php if ($autresActivitesArray): ?>
                        <ul>
                            <?php foreach ($autresActivitesArray as $autreActivite): ?>
                                <li>
                                    <dl class="row">
                                        <dt class="col-md-2">Nature</dt>
                                        <dd class="col-md-9"><?php echo $autreActivite->getNature() ?></dd>
                                        <dt class="col-md-2">Lieu</dt>
                                        <dd class="col-md-9"><?php echo $autreActivite->getLieu() ?></dd>
                                        <dt class="col-md-2">Public</dt>
                                        <dd class="col-md-9"><?php echo $autreActivite->getPublic() ?></dd>
                                        <dt class="col-md-2">Temps consacré</dt>
                                        <dd class="col-md-9"><?php echo $autreActivite->getTemps() ?> h</dd>
                                        <dt class="col-md-2">Date</dt>
                                        <dd class="col-md-9"><?php echo $autreActivite->getDate()->format(Constants::DATE_FORMAT) ?></dd>
                                    </dl>
                                </li>
                            <?php endforeach ?>
                        </ul>
                        <span class="total">Volume horaire total : <?php echo $rapport->getAutresActivitesTempsTotal() ?> h</span>
                    <?php else: ?>
                        Aucune
                    <?php endif ?>
                </dd>
            </dl>
        </div>
    </div>


    <?php if ($rapport->getCalendrierPrevionnelFinalisationEnabled()): ?>

        <h2>Calendrier prévisionnel de finalisation de la thèse / Provisional timetable to finalize the thesis</h2>

        <div class="row">
            <div class="col-md-10">
                <dl>
                    <dt>
                        Calendrier prévisionnel / Provisional timetable (up to 4-5 lines)
                    </dt>
                    <dd>
                        <?php echo $rapport->getCalendrierPrevionnelFinalisation() ?>
                    </dd>
                </dl>
            </div>
        </div>

    <?php endif ?>


    <?php if ($rapport->getPreparationApresTheseEnabled()): ?>

        <h2>Préparation de l’après-thèse / Preparing for after the thesis</h2>

        <div class="row">
            <div class="col-md-10">
                <dl>
                    <dt>
                        Perspectives de carrière et démarches entreprises / Careers paths and actions undertaken
                    </dt>
                    <dd>
                        <?php echo $rapport->getPreparationApresThese() ?>
                    </dd>
                </dl>
            </div>
        </div>

    <?php endif ?>


    <?php if ($rapport->getPerspectivesApresTheseEnabled()): ?>

        <h2>Perspectives de carrière et démarches entreprises / Plans after the thesis</h2>

        <div class="row">
            <div class="col-md-10">
                <dl>
                    <dt>
                        Perspectives de carrière et démarches entreprises / Careers paths and actions undertaken
                    </dt>
                    <dd>
                        <?php echo $rapport->getPerspectivesApresThese() ?>
                    </dd>
                </dl>
            </div>
        </div>

    <?php endif ?>


    <h2>Commentaires / Additional comments</h2>

    <div class="row">
        <div class="col-md-10">
            <dl>
                <dt>
                    Commentaire libres / Additional comments
                </dt>
                <dd>
                    <?php if ($commentaires = $rapport->getCommentaires()): ?>
                        <?php echo $commentaires ?>
                    <?php else: ?>
                        Aucun
                    <?php endif ?>
                </dd>
            </dl>
        </div>
    </div>


    <h2>Validations et avis</h2>

    <div class="row">
        <div class="col-md-4">
            <?php if ($operations): ?>
                <?php foreach ($operations as $i => $operation): ?>
                    <?php
                    echo $this->partial('rapport-activite/partial/operation-card', [
                        'operation' => $operation,
                        'ajaxModalEvent' => $ajaxModalEvent,
                    ]);
                    ?>
                <?php endforeach ?>
            <?php else: ?>
                Aucune validation ni aucun avis attendus.
            <?php endif ?>
        </div>
    </div>


    <hr>


    <?php if ($canEdit): ?>
        <a class="btn btn-primary" href="<?php echo $this->url('rapport-activite/modifier', ['rapport' => $rapport->getId()]) ?>">
            <span class="icon icon-modifier"></span> Modifier ce rapport d'activité
        </a>
    <?php endif; ?>

    <?php if ($canDel): ?>
        <a class="btn btn-danger float-end"
           href="<?php echo $this->url('rapport-activite/supprimer', ['rapport' => $rapport->getId()]) ?>">
            <span class="icon icon-supprimer"></span> Supprimer ce rapport d'activité</a>
    <?php endif; ?>

    <?php if ($canDl): ?>
        <a class="btn btn-info"
           href="<?php echo $this->url('rapport-activite/telecharger', ['rapport' => $rapport->getId()]) ?>">
            <span class="icon icon-telecharger"></span> Télécharger ce rapport d'activité</a>
    <?php endif; ?>

    <?php if ($canGen): ?>
        <a class="btn btn-info"
           href="<?php echo $this->url('rapport-activite/generer', ['rapport' => $rapport->getId()]) ?>">
            <span class="icon icon-telecharger"></span> Générer et télécharger ce rapport au format PDF</a>
    <?php endif; ?>

</div>


<div class="modal fade" id="avisComplemsModal" tabindex="-1" aria-labelledby="avisComplemsModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="avisComplemsModalLabel">Détails de l'avis</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button>
            </div>
            <div class="modal-body">
                <!-- rempli dynamiquement -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
            </div>
        </div>
    </div>
</div>



<script>
    $(function () {
        const avisComplemsModal = document.getElementById('avisComplemsModal')
        avisComplemsModal.addEventListener('show.bs.modal', function (event) {
            // Button that triggered the modal
            const button = event.relatedTarget;
            const logFullContent = $(button).parent().siblings(".log-full-content").html();
            // Update the modal's content.
            const modalBody = avisComplemsModal.querySelector('.modal-body');
            $(modalBody).html(logFullContent);
        });

        // Gestion de la fermeture de la modale de saisie d'un avis
        let ajaxModalEvent = '<?php echo $ajaxModalEvent ?>';
        $("body").on(ajaxModalEvent, function (event) {
            $("body").addClass("loading");
            event.div.modal('hide'); // ferme la fenêtre modale
            window.location.reload();
        });
    })
</script>

