<?php

namespace RapportActivite;

use Application\Filter\FinancementFormatter;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var \RapportActivite\Entity\Db\RapportActivite $rapport
 * @var \RapportActivite\Form\RapportActiviteAnnuelForm|\RapportActivite\Form\RapportActiviteFinContratForm $form
 *
 * @see \RapportActivite\Controller\RapportActiviteController::consulterAction()
 */

$title = $rapport->getId() ?
    "Modification du " . lcfirst($rapport) :
    "Nouveau " . lcfirst($rapport->getTypeRapportLibelle());

$financementFormatter = $this->financementFormatter();
$financementFormatter->setSortBy(FinancementFormatter::SORT_BY_DATE);
$financementFormatter->setDisplayAs(FinancementFormatter::DISPLAY_AS_HTML_LINES);

$form->prepare();
?>

<?php $this->headTitle($this->translate($title))
    ->prepend($rapport->getThese()->getDoctorant()->getIndividu()->getNomUsuel()) ?>

<h1 class="page-header">
    <?php echo $this->translate($title); ?>
    <small><?php echo $this->partial('these/these/partial/titre', ['these' => $rapport->getThese()]) ?></small>
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace(); ?>

<div class="alert alert-warning">
    <span class="icon icon-info"></span>
    La sauvegarde régulière de vos données est cruciale en cas de dysfonctionnement réseau ou machine par exemple.<br>
    Cela vous évitera la perte totale des données saisies et n’empêche aucunement leurs modifications.<br>
    Nous vous invitons donc à procéder à la sauvegarde régulière des données saisies dans ce formulaire.<br><br>

    <b>Puisque les champs de ce dernier sont obligatoires, vous avez la possibilité de saisir des informations inexactes pour pouvoir le soumettre.
        Après l'enregistrement, vous pourrez revenir ultérieurement tant de fois que vous le voulez, afin de corriger les données saisies.</b>
</div>
<div class="rapport-activite-container">

    <?php echo $this->form()->openTag($form) ?>

    <div class="row">
        <div class="col-md-2">
            <?php echo $this->formControlGroup($form->get('anneeUniv')) ?>
        </div>
    </div>

    <?php if ($form->has('parDirecteurTheseMotif')): ?>
        <div class="row">
            <div class="col-md-7">
                <?php echo $this->formControlGroup($form->get('parDirecteurTheseMotif')); ?>
            </div>
        </div>
    <?php endif ?>


    <h2>Financement de la thèse / <span class="en">Thesis funding</span></h2>

    <div class="row">
        <div class="col-md-7">
            <?php if ($rapport->getThese()->getFinancements()->isEmpty()): ?>
                Pas de financement dédié à la thèse.
            <?php else: ?>
                <?php echo $financementFormatter->format($rapport->getThese()->getFinancements()->toArray()); ?>
            <?php endif ?>
        </div>
    </div>


    <h2>Activités scientifiques / <span class="en">Scientific activities</span></h2>

    <div class="row">
        <div class="col-md-7">
            <?php echo $this->formControlGroup()->setHelpContent("")->render($form->get('descriptionProjetRecherche')); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-7">
            <?php echo $this->formControlGroup($form->get('principauxResultatsObtenus')); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-7">
            <?php echo $this->formControlGroup($form->get('productionsScientifiques')); ?>
            <p class="form-text text-info">En cas de non production scientifique, merci d’écrire une justification / <span class="en">In case of no scientific production, please write a justification</span>.</p>
        </div>
    </div>


    <h2>Formations doctorales thématiques et transversales / <span class="en">Doctoral training</span></h2>

    <p class="help">
        Formations spécifiques/thématiques proposées par votre ED (ou une autre structure) : précisez le volume horaire
        pour chaque formation suivie au cours de l'année universitaire en question. Inclure les éventuelles autres
        activités comptabilisées par l’ED au titre de la formation. <br>
        <u>Dans le cas où vous n'auriez suivi aucune formation, merci de le justifier dans la partie Commentaires
        (située en fin de formulaire).</u>
    </p>
    <p class="help en">
        Specific training, relevant to your field, offered by your doctoral school or another institution. Specify
        the number of hours for each training taken during the academic year in question. Include any other activities
        likely to be recognized as part of your training. <br>
        <u>If you have not followed any training, please justify it in the Comments section (located at the end of this form).</u>
    </p>
    <div class="row">
        <div class="col-md-7">
            <?php echo $this->formElementCollection($form->get('formationsSpecifiques')); ?>
        </div>
    </div>

    <p class="help">
        Formations transversales/professionnalisantes proposées par le Collège doctoral (ou une autre structure) :
        précisez le volume horaire pour chaque formation suivie au cours de l'année universitaire en question. <br>
        <u>Dans le cas où vous n'auriez suivi aucune formation, merci de le justifier dans la partie Commentaires
        (située en fin de formulaire).</u>
    </p>
    <p class="help en">
        Transversal training (or training not specific to your field and which is relevant to the employment
        market), offered by the Doctoral College or another institution. Specify the number of hours for each training
        taken during the academic year in question. <br>
        <u>If you have not followed any training, please justify it in the Comments section (located at the end of this form).</u>
    </p>

    <div class="row">
        <div class="col-md-7">
            <?php echo $this->formElementCollection($form->get('formationsTransversales')); ?>
        </div>
    </div>

    <p class="help">
        Actions de diffusion de la culture scientifique, technique et industrielle (CSTI) :
        Listez les actions auxquelles vous avez participé en précisant leur nature, le public concerné, le temps
        consacré et la date. Exemples : MT 180s, Fête de la science, Journées Portes Ouvertes, forums,
        communications auprès du grand public, des lycéens, des collégiens etc. (cette rubrique n’inclut pas les
        présentations en colloques). <br>
        <u>Dans le cas où vous n'auriez effectué aucune action de diffusion CSTI, merci de le justifier dans la partie
        Commentaires (située en fin de formulaire).</u>
    </p>
    <p class="help en">
        Actions undertaken within the framework of the promotion of scientific, technical and industrial
        knowledge : list and describe all relevant activities (excluding presentations in symposia or conferences),
        e.g. “3-minute thesis”, communications to high school or middle grade students, forums, open house days,
        etc. <br>
        <u>Please justify in the Comments section (located at the end of the report) if you have not carried out any CSTI
        dissemination action.</u>
    </p>
    <div class="row">
        <div class="col-md-7">
            <?php echo $this->formElementCollection($form->get('actionsDiffusionCultureScientifique')); ?>
        </div>
    </div>


    <h2>Autres activités / <span class="en">Other activities</span></h2>

    <p class="help">
        Listez les activités menées en marge de votre projet de recherche mais inscrites dans votre formation doctorale
        (mission d’enseignement, mission d’expertise en entreprise, mission de valorisation, etc.).
    </p>
    <p class="help en">
        List and describe all activities undertaken as part of your doctoral training but not related to your research
        project (teaching, expertise, etc.).
    </p>
    <div class="row">
        <div class="col-md-7">
            <?php echo $this->formElementCollection($form->get('autresActivites')); ?>
        </div>
    </div>


    <?php if ($form->has('calendrierPrevionnelFinalisation')): ?>
        <h2>Calendrier prévisionnel de finalisation de la thèse /
            <span class="en">Provisional timetable to finalize the thesis</span></h2>

        <p class="help">
            Lister les activités programmées pour finaliser la thèse (à renseigner uniquement pour les doctorants en 3ème année et plus).
        </p>
        <p class="help en">
            List your plans to achieve this (only applicable to 3rd year doctoral students).
        </p>
        <div class="row">
            <div class="col-md-7">
                <?php echo $this->formControlGroup($form->get('calendrierPrevionnelFinalisation')); ?>
            </div>
        </div>
    <?php endif ?>


    <?php if ($form->has('preparationApresThese')): ?>
        <h2>Préparation de l’après-thèse / <span class="en">Preparing for after the thesis</span></h2>

        <p class="help">
            Quelles sont les perspectives de carrière vers lesquelles vous souhaitez (à ce stade) vous engager et les
            démarches entreprises ?
        </p>
        <p class="help en">
            What career paths are you envisioning at this stage in your education? What actions have you undertaken to
            further that professional aim?
        </p>
        <div class="row">
            <div class="col-md-7">
                <?php echo $this->formControlGroup($form->get('preparationApresThese')); ?>
            </div>
        </div>
    <?php endif ?>

    <?php if ($form->has('perspectivesApresThese')): ?>
        <h2>Perspectives de l’après-thèse / <span class="en">Plans after the thesis</span></h2>

        <p class="help">
            Quelles sont les perspectives de carrière vers lesquelles vous souhaitez vous engager et les démarches
            entreprises ?
        </p>
        <p class="help en">
            What career paths do you wish to pursue and what actions have you undertaken to further that goal ?
        </p>
        <div class="row">
            <div class="col-md-7">
                <?php echo $this->formControlGroup($form->get('perspectivesApresThese')); ?>
            </div>
        </div>
    <?php endif ?>


    <h2>Commentaires libres / <span class="en">Additional comments</span></h2>

    <p class="help">
        Indiquer toute situation particulière professionnelle ou personnelle (congé maladie, congé
        maternité, etc. Si pas de commentaire, indiquer dans le champs ci-dessous "Pas de commentaire".
    </p>
    <p class="help en">
        Any personal or professional situation that has had an impact on your research work (sick leave, maternity leave, etc.)
        If no comment, indicate in the field below "No comment".
    </p>
    <div class="row">
        <div class="col-md-7">
            <?php echo $this->formControlGroup($form->get('commentaires')); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-7">
            <?php
            echo $this->formControlGroup($form->get('security'));
            echo $this->formControlGroup($form->get('submit'));
            ?>
        </div>
    </div>
    <?php echo $this->form()->closeTag() ?>

</div>