<?php
/**
 * @var \Doctorant\Entity\Db\Doctorant $entity
 * @var bool $includeGotoDetailsLink
 * @var bool $horizontal
 */

$horizontal = $horizontal ?? false;

$dlClass = $horizontal ? 'row' : '';
$dtClass = $horizontal ? 'col-md-5' : '';
$ddClass = $horizontal ? 'col-md-7' : '';
?>

<h3>
    Informations générales
</h3>
<dl class="<?php echo $dlClass ?>">
    <dt class="<?php echo $dtClass ?>">INE</dt>
    <dd class="<?php echo $ddClass ?>"><?php echo $entity->getIne() ?></dd>

    <dt class="<?php echo $dtClass ?>">Code apprenant</dt>
    <dd class="<?php echo $ddClass ?>">
        <?php if ($entity->getCodeApprenantInSource()) : ?>
            <?php echo $entity->getCodeApprenantInSource() ?>
        <?php else : ?>
            (Non renseigné)
        <?php endif; ?>
    </dd>

    <dt class="<?php echo $dtClass ?>">Dernière modification</dt>
    <dd class="<?php echo $ddClass ?>">
        <?php echo ($entity->getHistoModification() ?: $entity->getHistoCreation())->format('d/m/Y H:i:s') ?>
    </dd>

    <?php if ($entity->estHistorise()): ?>
        <dt class="<?php echo $dtClass ?> text-danger">Supprimé le</dt>
        <dd class="<?php echo $ddClass ?> text-danger"><?php echo $entity->getHistoDestruction()->format('d/m/Y H:i:s') ?></dd>
    <?php endif ?>
</dl>

<h3>
    Informations techniques
</h3>
<dl class="<?php echo $dlClass ?>">
    <dt class="<?php echo $dtClass ?>">Id</dt>
    <dd class="<?php echo $ddClass ?>"><?php echo $entity->getId() ?></dd>

    <dt class="<?php echo $dtClass ?>">Source</dt>
    <dd class="<?php echo $ddClass ?>"><?php echo $entity->getSource() ?></dd>

    <dt class="<?php echo $dtClass ?>">Source code</dt>
    <dd class="<?php echo $ddClass ?>"><code><?php echo $entity->getSourceCode() ?></code></dd>

    <dt> IdRef :</dt>
    <dd>
        <?php if ($idref = $entity->getIndividu()->getIdRef()) : ?>
            <?php echo $idref ?>
        <?php else : ?>
            (Non renseigné)
        <?php endif; ?>
    </dd>
</dl>

<?php if ($entity->estHistorise()): ?>
    <h3 class="text-danger">
        Historisé
    </h3>
    <dl class="<?php echo $dlClass ?> text-danger">
        <dt>Date :</dt>
        <dd><?php echo $entity->getHistoDestruction()->format('d/m/Y à H:i:s') ?></dd>
    </dl>
<?php endif ?>

<?php if ($includeGotoDetailsLink ?? false): ?>
    <a href="<?php echo $this->url('doctorant/voir', ['doctorant' => $entity->getId()], [], true); ?>"
       class="action btn btn-outline-secondary"><span class="icon icon-voir"></span> Voir la fiche détaillée de ce·tte doctorant·e
    </a>
<?php endif ?>