<?php
/**
 * @var \Doctorant\Entity\Db\Doctorant $entity
 * @var bool $includeGotoDetailsLink
 */
?>

<h3>
    Informations générales
</h3>
<dl class="row">
    <dt class="col-md-5">INE</dt>
    <dd class="col-md-5"><?php echo $entity->getIne() ?></dd>

    <dt class="col-md-5">Code apprenant</dt>
    <dd class="col-md-5">
        <?php if ($entity->getCodeApprenantInSource()) : ?>
            <?php echo $entity->getCodeApprenantInSource() ?>
        <?php else : ?>
            (Non renseigné)
        <?php endif; ?>
    </dd>

    <dt class="col-md-5">Dernière modification</dt>
    <dd class="col-md-5">
        <?php echo ($entity->getHistoModification() ?: $entity->getHistoCreation())->format('d/m/Y H:i:s') ?>
    </dd>

    <?php if ($entity->estHistorise()): ?>
        <dt class="col-md-5 text-danger">Supprimé le</dt>
        <dd class="col-md-5 text-danger"><?php echo $entity->getHistoDestruction()->format('d/m/Y H:i:s') ?></dd>
    <?php endif ?>
</dl>

<h3>
    Informations techniques
</h3>
<dl>
    <dt class="col-md-5">Id</dt>
    <dd class="col-md-5"><?php echo $entity->getId() ?></dd>

    <dt class="col-md-5">Source</dt>
    <dd class="col-md-5"><?php echo $entity->getSource() ?></dd>

    <dt class="col-md-5">Source code</dt>
    <dd class="col-md-5"><code><?php echo $entity->getSourceCode() ?></code></dd>

    <dt> IdRef :</dt>
    <dd>
        <?php if ($idref = $entity->getIndividu()->getIdRef()) : ?>
            <?php echo $idref ?>
        <?php else : ?>
            (Non renseigné)
        <?php endif; ?>
    </dd>
</dl>

<?php if ($entity->estHistorise()): ?>
    <h3 class="text-danger">
        Historisé
    </h3>
    <dl class="text-danger">
        <dt>Date :</dt>
        <dd><?php echo $entity->getHistoDestruction()->format('d/m/Y à H:i:s') ?></dd>
    </dl>
<?php endif ?>

<?php if ($includeGotoDetailsLink ?? false): ?>
    <a href="<?php echo $this->url('doctorant/voir', ['doctorant' => $entity->getId()], [], true); ?>"
       class="action btn btn-outline-secondary"><span class="icon icon-voir"></span> Voir la fiche détaillée de ce·tte doctorant·e
    </a>
<?php endif ?>