<?php

use Application\Constants;
use These\Entity\Db\Acteur;
use These\Entity\Db\These;
use Soutenance\Entity\Avis;
use Soutenance\Entity\Membre;
use Soutenance\Provider\Privilege\AvisSoutenancePrivileges;

/**
 * @see \Soutenance\Controller\AvisController::afficherAction()
 *
 * @var These $these
 * @var Acteur $rapporteur
 * @var Membre $membre
 * @var Avis $avis
 * @var string $url
 */

$this->headTitle("Avis de soutenance (".$avis->getId().")");

$canAnnuler = $this->isAllowed(AvisSoutenancePrivileges::getResourceId(AvisSoutenancePrivileges::AVIS_ANNULER));
?>

<h1 class="page-header">
    Avis de soutenance
</h1>

<div class="row">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header bg-dark text-white">
                Informations de la thèse
            </div>

            <div class="card-body">
                <dl>
                    <dt> Thèse </dt>
                    <dd> <?php echo $these->getTitre(); ?> </dd>
                    <dt> Doctorant </dt>
                    <dd> <?php echo $these->getDoctorant()->getIndividu(); ?> </dd>
                </dl>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <?php
            $vclass="bg-info";
            switch ($avis->getAvis()) {
                case "Favorable" :
                    $vclass = "bg-success";
                    break;
                case "Défavorable" :
                    $vclass = "bg-danger";
                    break;
            }
        ?>

        <div class="card">
            <div class="card-header <?php echo $vclass; ?>">
                Avis de soutenance
            </div>
            <div class="card-body">
                <dl>
                    <dt> Rapporteur </dt>
                    <dd> <?php echo $rapporteur->getIndividu(); ?> </dd>
                    <dt> Avis </dt>
                    <dd> <?php echo $avis->getAvis(); ?></dd>
                    <?php if ($avis->getMotif()) : ?>
                        <dt> Motif </dt>
                        <dd> <?php echo $avis->getMotif(); ?></dd>
                    <?php endif; ?>
                    <dt> Rapport de présoutenance</dt>
                    <dd>
                        <a href="<?php echo $url; ?>">
                            <?php echo $avis->getFichier()->getNom(); ?>
                        </a>
                    </dd>
                    <dt> Date de création </dt>
                    <dd>
                        <?php echo $avis->getValidation()->getHistoModification()->format(Constants::DATETIME_FORMAT); ?>
                    </dd>

                </dl>
            </div>
        </div>
    </div>

</div>

<?php if ($avis !== null AND $avis->estNonHistorise()): ?>
    <div class="box card" style="margin: 1rem 0;">
        <div class="card-header bg-success">
            <h2 class="first"> Et ensuite ? </h2>
        </div>
        <div class="card-body">

            Vous avez maintenant terminé la procédure de pré-soutenance.

        </div>
    </div>
<?php endif; ?>

<div>
<?php if ($canAnnuler) : ?>
    <div class="float-end">
        <a href="<?php echo $this->url('soutenance/index-rapporteur', ['these' => $these->getId()], [], true); ?>"
           class="btn btn-primary float-end" style="margin-left: 1rem;">
            <span class="icon icon-retour"></span>
                Retour à l'index rapporteur
        </a>
    </div>
    <a
        <?php /** @see \Soutenance\Controller\AvisController::annulerAction() */ ?>
            href="<?php echo $this->url('soutenance/avis-soutenance/annuler', ['these' => $these->getId(), 'rapporteur' => $membre->getId()], [] , true); ?>"
            class="btn btn-danger float-end">
        <span class="icon icon-delete"></span>
        Annuler l'avis de soutance
    </a> &nbsp;&nbsp;
<?php endif; ?>

</div>
