<?php

use Application\Entity\Db\Acteur;
use Application\Entity\Db\These;

/**
 * @var These $these
 * @var Acteur $rapporteur
 */

//$denominationDoctorant = $these->getDoctorant()->getIndividu()->__toString();
//$denominationRapporteur = $rapporteur->getIndividu()->__toString();
//$titrePage = "Avis sur la soutenance de la thèse de ".$denominationDoctorant;
//$this->headTitle($titrePage);
//
//$canEdit = true;
?>



<h1 class="page-header">
<!--    --><?php //echo $titrePage; ?>
</h1>

<p class="lead">
    En cas d’avis favorable, si vous souhaitez néanmoins que des modifications soient apportées à la thèse, elles seront
    transmises au jury qui peut demander à l’issu de la soutenance l'introduction de corrections dans la thèse.
</p>

<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>


<div class="panel panel-info">
    <div class="panel-heading">
        <h2> Dépot du prérapport de soutenance et de l'avis de soutenance </h2>
    </div>
    <div class="panel-body">

<?php echo $this->form($form); ?>



<!--        --><?php //echo $this->form()->openTag($form); ?>
<!---->
<!--        <div class="row">-->
<!--            <div class="col-md-4">-->
<!--                --><?php //echo $this->formControlGroup($form->get('rapport')); ?>
<!--            </div>-->
<!--            <div class="col-md-4">-->
<!--                --><?php
//                    echo $this->formControlGroup($form->get('avis'));
//                ?>
<!--            </div>-->
<!--            <div class="col-md-4">-->
<!--                --><?php //echo $denominationRapporteur; ?><!-- <br/>-->
<!--                --><?php //echo $this->formControlGroup($form->get('enregistrer')); ?>
<!--            </div>-->
<!--        </div>-->
<!--        <div class="col-md-12" id="justification">-->
<!--            --><?php //echo $this->formControlGroup($form->get('motif')); ?>
<!--        </div>-->
<!---->
<!--        --><?php //echo $this->form()->closeTag(); ?>

    </div>
</div>

<style>
    .form-control {
        height: auto;
    }
</style>

<script>
    // $(document).ready(function() {
    //     alert('test');
    //     if ($("input[name='avis']").attr('value') === 'Favorable') {
    //         $("div#justification").hide();
    //     }
    // });

    // $("input[name='avis']").change(function() {
    //     if ($(this).attr('value') === 'Favorable') {
    //         $("div#justification").hide();
    //     } else {
    //         $("div#justification").show();
    //     }
    // })
</script>