<?php

use Application\Entity\Db\Acteur;
use Application\Entity\Db\These;
use Soutenance\Form\Avis\AvisForm;
use Soutenance\Provider\Privilege\AvisSoutenancePrivileges;

/**
 * @see \Soutenance\Controller\AvisController::indexAction()
 * @var AvisForm $form
 * @var These $these
 * @var Acteur $rapporteur
 */

$denominationDoctorant = $these->getDoctorant()->getIndividu()->__toString();
$denominationRapporteur = $rapporteur->__toString();
$titrePage = "Avis sur la soutenance de la thèse de ".$denominationDoctorant . " / Notification on the PhD defense ";
$this->headTitle($titrePage);

$canEdit = $this->isAllowed($rapporteur, AvisSoutenancePrivileges::AVIS_MODIFIER);
?>



<h1 class="page-header">
    <?php echo $titrePage; ?>
</h1>

<!--<p class="lead">-->
<!--    En cas d’avis favorable, si vous souhaitez néanmoins que des modifications soient apportées à la thèse, elles seront-->
<!--    transmises au jury qui peut demander à l’issu de la soutenance l'introduction de corrections dans la thèse.-->
<!--</p>-->

<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>

<?php if ($canEdit) : ?>
    <div class="card">
        <div class="card-header bg-info">
            <h2> Avis sur la soutenance et dépôt du pré-rapport de soutenance /
                Notification on the PhD defense and uploading of the PhD report </h2>
        </div>
        <div class="card-body">

    <?php echo $this->form($form); ?>
        </div>
    </div>
<?php else : ?>
    <div class="card">
        <div class="card-header bg-danger">
            <h2> Vous ne pouvez pas modifier cette avis de soutenance </h2>
        </div>
        <div class="card-body">
            Les raisons de cette impossiblité peuvent être :
            <ul>
                <li> vous n'êtes pas connecté&middot;e avec le rôle de 'Rapporteur' ;</li>
                <li> le dépassement de la date de rendu des rapports.</li>
            </ul>
        </div>
    </div>
<?php endif; ?>

<div class="float-end">
    <a href="<?php echo $this->url('soutenance/index-rapporteur', ['these' => $these->getId()], [], true); ?>"
       class="btn btn-primary">
        Retour à l'index rapporteur
    </a>
</div>

<style>
    .form-control {
        height: auto;
    }
</style>

<script>
    $("textarea#motif").parent().hide();

    $("input[name='avis']").on("change", function() {
        if ($(this).attr('value') === 'Favorable') {
            $("textarea#motif").parent().hide();
        } else {
            $("textarea#motif").parent().show();
        }
    })
</script>