<?php

use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var string $type
 * @var \Doctrine\DBAL\Result $result
 *
 * @see \Substitution\Controller\ForeignKeyController::listerAction()
 */
?>

<?php $this->headTitle($this->translate("Triggers : $type")) ?>

<h1 class="page-header">
    <span class="fas fa-gun"></span>
    <?php echo $this->translate("Triggers") ?> <span class="badge bg-primary text-uppercase p-1"><?php echo $type ?></span>
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace(); ?>

<p class="lead">
    Voici la liste des triggers en base de données sur lequel s'appuie le moteur de substitutions.
</p>

<?php if ($count = $result->rowCount()): ?>
    <p><?php echo $count ?> triggers trouvés.</p>

    <table class="table table-bordered table-extra-condensed">
        <tr>
            <th>Nom</th>
            <th>Table</th>
            <th>Événements déclencheurs</th>
            <th>Mode de déclenchement</th>
            <th>Activé ?</th>
        </tr>
        <?php while ($row = $result->fetchAssociative()): ?>
            <tr>
                <td><?php echo $row['trigger_name'] ?></td>
                <td><?php echo $row['table_name'] ?></td>
                <td><?php echo $row['event'] ?></td>
                <td><?php echo $row['activation'] ?></td>
                <td><?php echo $row['enabled'] ? 'Oui' : 'Non' ?></td>
            </tr>
        <?php endwhile ?>
    </table>
<?php else: ?>
    <p>Aucun.</p>
<?php endif ?>
