<?php

namespace Application;

use Application\Entity\Db\RapportAnnuel;
use Application\Entity\Db\Role;
use Application\Filter\ActeursFormatter;
use Application\Filter\IdifyFilter;
use Application\Provider\Privilege\RapportAnnuelPrivileges;
use Application\Search\Filter\Provider\SearchFilterProviderService;
use UnicaenAuth\Provider\Privilege\Privileges;
use Zend\Paginator\Paginator as ZendPaginator;

/**
 * @var ZendPaginator $paginator
 */

$canDlZip = $this->isAllowed(Privileges::getResourceId(RapportAnnuelPrivileges::RAPPORT_ANNUEL_TELECHARGER_ZIP));
$queryParams = $this->queryParams();

$acteursFormatterDirecteurs = new ActeursFormatter();
$acteursFormatterDirecteurs->asSeparated()
    ->paramDisplay(['role' => false, 'complement' => false, "qualite" => false, "etablissement" => false,])
    ->paramFilter((['role' => Role::CODE_DIRECTEUR_THESE]));
$acteursFormatterCodirecteurs = new ActeursFormatter();
$acteursFormatterCodirecteurs->asSeparated()
    ->paramDisplay(['role' => false, 'complement' => false, "qualite" => false, "etablissement" => false,])
    ->paramFilter((['role' => Role::CODE_CODIRECTEUR_THESE]));
?>

<h1 class="page-header">Rapports annuels</h1>

<!-- Formulaire de filtrage -->
<div class="pull-left">
    <?php $loadFiltersUrl = $this->url('rapport-annuel/recherche/filters', [], ['query' => $this->queryParams()], true); ?>
    <div id="filters" data-url="<?php echo $loadFiltersUrl ?>" style="min-height: 130px">
        <!-- Contenu chargé en AJAX -->
    </div>
</div>
<div class="clearfix"></div>


<?php if (count($paginator) > 0): ?>

    <p>
        <?php
        echo $paginator->getTotalItemCount();
        echo " ";
        echo $this->translate("rapport(s) trouvé(s).");
        ?>
    </p>

    <table class="table table-condensed">
        <thead>
        <tr>
            <?php if ($displayEtablissement = true): ?>
                <th>
                    <a href="<?php echo $s = $this->sortable(SearchFilterProviderService::NAME_etab_inscription) ?>"
                       title="<?php echo $this->translate("Établissement") ?> ">
                        <?php echo $this->translate("Étab.") ?>
                    </a> <?php echo $s->icon() ?>
                </th>
            <?php endif ?>
            <th>
                <a href="<?php echo $s = $this->sortable(SearchFilterProviderService::NAME_nom_doctorant) ?>"
                   title="<?php echo $this->translate("Identité du doctorant") ?>">
                    <?php echo $this->translate("Doctorant") ?>
                </a> <?php echo $s->icon() ?>
            </th>
            <th>
                <?php echo $this->translate("Directeur(s) de thèse"); ?>
            </th>
            <th>
                <a href="<?php echo $s = $this->sortable(SearchFilterProviderService::NAME_ecole_doctorale); ?>"
                   title="<?php echo $this->translate("École doctorale"); ?>">
                    <?php echo $this->translate("École<br>doct."); ?>
                </a> <?php echo $s->icon() ?>
            </th>
            <th>
                <a href="<?php echo $s = $this->sortable(SearchFilterProviderService::NAME_unite_recherche); ?>"
                   title="<?php echo $this->translate("Unité de recherche"); ?>">
                    <?php echo $this->translate("Unité<br>rech."); ?>
                </a> <?php echo $s->icon() ?>
            </th>
            <th>
                <a href="<?php echo $s = $this->sortable(SearchFilterProviderService::NAME_annee_rapport_annuel); ?>"
                   title="<?php echo $this->translate("Année universitaire concernée par le rapport"); ?>">
                    <?php echo $this->translate("Année du<br>rapport"); ?>
                </a> <?php echo $s->icon() ?>
            </th>
            <th>
                Document
            </th>
        </tr>
        </thead>

        <tbody>
        <?php /** @var RapportAnnuel $rapportAnnuel */
        foreach ($paginator as $rapportAnnuel): ?>
            <?php
            $these = $rapportAnnuel->getThese();
            $canDl = $this->isAllowed($rapportAnnuel, RapportAnnuelPrivileges::RAPPORT_ANNUEL_TELECHARGER);
            ?>
            <tr>
                <?php
                if ($displayEtablissement) {
                    echo "<td>";
                    echo "<abbr title='";
                    echo $these->getEtablissement()->getLibelle();
                    echo "'>";
                    echo $these->getEtablissement()->getCode();
                    echo "</abbr>";
                    echo "</td>";
                }
                ?>
                <td>
                    <a href="<?php echo $this->url('these/identite', ['these' => $these->getId()], [], true) ?>"
                       title="<?php echo $these->getTitre() ?>">
                        <?php echo $these->getDoctorant()->getIndividu()->getNomComplet() ?>
                    </a>
                </td>
                <td class="acteurs">
                    <?php
                    $directeurs = $acteursFormatterDirecteurs->filter($these->getActeurs());
                    foreach ($directeurs as $directeur) {
                        echo $acteursFormatterDirecteurs->htmlifyActeur($directeur)."<br/>";
                    }
                    $codirecteurs = $acteursFormatterCodirecteurs->filter($these->getActeurs());
                    foreach ($codirecteurs as $codirecteur) {
                        echo $acteursFormatterCodirecteurs->htmlifyActeur($codirecteur)."<br/>";
                    }
                    ?>
                </td>
                <td>
                    <?php if ($ed = $these->getEcoleDoctorale()): ?>
                        <abbr title="<?php echo $ed->getLibelle() ?>">
                            <?php echo $ed->getStructure()->getCode(); ?>
                        </abbr>
                    <?php endif ?>
                </td>
                <td>
                    <?php if ($ur = $these->getUniteRecherche()): ?>
                        <abbr title="<?php echo $ur->getLibelle() ?>">
                            <?php echo $ur->getStructure()->getCode(); ?>
                        </abbr>
                    <?php endif ?>
                </td>
                <td>
                    <?php echo $rapportAnnuel->getAnneeUnivToString() ?>
                    <?php if ($rapportAnnuel->getEstFinal()): ?>
                        <br>
                        <span class="label label-info">Rapport final</span>
                    <?php endif ?>
                </td>
                <td>
                    <?php $title = "Téléversé le " . $rapportAnnuel->getHistoCreation()->format('d/m/Y à H:i:s') . " par " . (string) $rapportAnnuel->getHistoCreateur() ?>
                    <?php if ($canDl): ?>
                        <a href="<?php echo $this->url('rapport-annuel/telecharger', ['rapportAnnuel' => IdifyFilter::id($rapportAnnuel)]) ?>"
                        title="<?php echo $title ?>">
                            <?php echo $rapportAnnuel->getFichier()->getNom() ?>
                        </a>
                    <?php else: ?>
                        <span title="<?php echo $title ?>"><?php echo $rapportAnnuel->getFichier()->getNom() ?>
                        </span>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>

    <?php echo $paginationControl = $this->paginationControl($paginator, 'sliding', 'partial/paginator.phtml', ['route' => 'these']) ?>

    <?php if ($canDlZip): ?>
        <a class="btn btn-default" href="<?php echo $this->url('rapport-annuel/recherche/telecharger-zip', [], ['query' => $queryParams]) ?>"
           title="Télécharger tous ces rapports sous la forme d'une archive compressée (.zip)">
            <span class="glyphicon glyphicon-export"></span>
            <?php echo $this->translate("Télécharger les rapports"); ?>
        </a>
    <?php endif ?>

<?php else: ?>

    <p>Aucun rapport trouvé.</p>

<?php endif ?>


<script>
    $(function() {
        $("#filters").refresh();
    });
</script>