<?php

/**
 * @var ComiteSuivi[] $comites
 * @var string $anneeScolaire
 */

use Application\Entity\Db\These;
use ComiteSuivi\Entity\Db\ComiteSuivi;
use ComiteSuivi\Entity\Db\Membre;
use ComiteSuivi\Provider\Privilege\ComiteSuiviPrivileges;

$this->headTitle('Index des comités de suivi de thèse');

$canAfficherComite = $this->isAllowed(ComiteSuiviPrivileges::getResourceId(ComiteSuiviPrivileges::COMITESUIVI_AFFICHER));
$canModifierComite = $this->isAllowed(ComiteSuiviPrivileges::getResourceId(ComiteSuiviPrivileges::COMITESUIVI_MODIFIER));
?>

<h1 class="page-header">
    Index des comités de suivi de thèse
</h1>

<div class="main">
    <?php /** @var ComiteSuivi[] $comiteArray */ ?>
    <?php foreach ($comites as $theseId => $comiteArray) : ?>
        <?php $comite_ = current($comiteArray); ?>
        <?php /** @var These $these */ $these = $comite_->getThese(); ?>

        <h2>
            <?php echo $these->getTitre(); ?>
        </h2>
        <h3>
            <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?>
        </h3>

        <table class="table table-condensed">
            <thead>
            <tr>
                <th> Année de thèse </th>
                <th> Année scolaire </th>
                <th> Examinateurs </th>
                <th> Action </th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($comiteArray as $comite) : ?>
                <tr>
                    <td> <?php echo $this->anneeThese($comite->getAnneeThese()); ?> </td>
                    <td> <?php echo $comite->getAnneeScolaire(); ?> </td>
                    <td>
                        <ul>
                            <?php $membres = $comite->getMembres(); ?>
                            <?php if(!empty($membres)) : ?>
                                <?php foreach ($membres as $membre) : ?>
                                    <?php if ($membre->getRole()->getCode() === Membre::ROLE_EXAMINATEUR_CODE) : ?>
                                        <li> <?php echo $membre->getDenomination(); ?> </li>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            <?php else :?>
                                Aucun
                            <?php endif; ?>
                        </ul>
                    </td>
                    <td>
                        <?php if($canModifierComite): ?>
                            <a  <?php /** @see \ComiteSuivi\Controller\ComiteSuiviController::modifierAction() */ ?>
                                    href="<?php echo $this->url('comite-suivi/afficher', ['these' => $comite->getThese()->getId(), 'comite-suivi' => $comite->getId()], [], true); ?>"
                                    class="ajax-modal"
                                    title="Afficher le comité de suivi"
                            >
                                <span class="glyphicon glyphicon-eye-open"></span></a>
                        <?php endif; ?>
                        <?php if($canModifierComite AND $comite->getAnneeScolaire() === $anneeScolaire): ?>
                            <a  <?php /** @see \ComiteSuivi\Controller\ComiteSuiviController::modifierAction() */ ?>
                                    href="<?php echo $this->url('comite-suivi/modifier', ['these' => $comite->getThese()->getId(), 'comite-suivi' => $comite->getId()], [], true); ?>"
                                    title="Modifier le comite de suivi"
                            >
                                <span class="glyphicon glyphicon-pencil"></span></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>

    <?php endforeach; ?>
</div>



