<?php

use Application\Entity\Db\These;
use ComiteSuivi\Entity\Db\ComiteSuivi;
use ComiteSuivi\Entity\Db\CompteRendu;

/**
 * @see \ComiteSuivi\Controller\CompteRenduController::afficherAction()
 * @var These $these
 * @var ComiteSuivi $comite
 * @var CompteRendu $compterendu
 */

?>

<h1 class="page-header">
    Compte-rendu du comite de suivi de thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?> <br/>
    Année : <?php echo $this->anneeThese($comite->getAnneeThese()); ?> <br/>
    Examinateur : <?php echo $compterendu->getMembre()->getDenomination(); ?> <br/>
</h1>

<div class="main">
    <p>
        Modifier le <em><?php echo $compterendu->getHistoModification()->format('d/m/Y à H:i'); ?></em>
        par <em><?php echo $compterendu->getHistoModificateur()->getDisplayName(); ?></em>.
    </p>

    <h2>
        Compte-rendu
    </h2>

    <?php echo $compterendu->getReponse(); ?>
</div>
