<?php

/**
 * @see \ComiteSuivi\Controller\CompteRenduController::modifierAction()
 *
 * @var ComiteSuivi $comite
 * @var CompteRendu $compterendu
 * @var CompteRenduForm $form
 */

use ComiteSuivi\Entity\Db\ComiteSuivi;
use ComiteSuivi\Entity\Db\CompteRendu;
use ComiteSuivi\Form\CompteRendu\CompteRenduForm;

?>

<div class="row">
    <a      <?php /** @see \ComiteSuivi\Controller\CompteRenduController::modifierAction() */ ?>
            href="<?php echo $this->url('comite-suivi/modifier', ['these' => $comite->getThese()->getId(), 'comite-suivi' => $comite->getId()], [], true); ?>" class="btn btn-info action">
        <span class="glyphicon glyphicon-chevron-left"></span>
        Retour vers le comité
    </a>
</div>

<?php echo $this->form($form); ?>

<script>
    $(document).ready(function() {
        tinymce.remove();
        tinymce.init({
            selector: '#reponse',
            toolbar: 'newdocument undo redo | formatselect bold italic | bullist numlist',
            block_formats: 'Normal=p;Titre 1=h1;Titre 2=h2;Titre 3=h3',
            resize: true,
            language: 'fr_FR',
            plugins: 'lists',
            statusbar: true,
            browser_spellcheck: true,
            branding: false,
            menu: {},
            body_id: 'motif',
            setup: function (editor) {
                editor.on("focusout", function () {
                    $('textarea#reponse').val(tinymce.get('reponse').getContent());
                });
            }
        });
    });
</script>
