version: '2.2'

services:
  sygal:
    container_name: sygal-container
#    depends_on:
#      - sygal-import-ws
    build:
      args:
        PHP_VERSION: 7.3
      context: .
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
    ports:
     - "8003:443"
    volumes:
     - .:/app
     - /tmp:/tmp
     - $HOME/.ssh:/root/.ssh
    working_dir: /app
    network_mode: bridge
#    networks:
#      - sygalnet

  sygal-import-ws:
    container_name: sygal-import-ws-container
    build:
      context: ../sygal-import-ws
      args:
        PHP_VERSION: 7.0
    ports:
     - "8080:80"
     - "8443:443"
    volumes:
     - ../sygal-import-ws:/app
    working_dir: /app
    network_mode: bridge
#    networks:
#      - sygalnet

#networks:
#  sygalnet:
#    driver: bridge