###########################################################################################
#
#                               Image pour le dev.
#
#         Montage des sources attendu dans le volume "/webapp" du container.
#
###########################################################################################

FROM php:7-apache

LABEL maintainer="Bertrand GAUTHIER <bertrand.gauthier at unicaen.fr>"

ARG http_proxy
ARG https_proxy
ARG no_proxy

# Mise à niveau de la distrib.
RUN apt-get update && apt-get install -y \
        git \
        libaio1 \
        libcurl4-openssl-dev \
        libfreetype6-dev \
        libicu-dev \
        libjpeg62-turbo-dev \
        libldap2-dev \
        libmcrypt-dev \
        libssl-dev \
        libxml2-dev \
        make \
        netcat-openbsd \
        subversion \
        unzip \
        vim \
        wget \
    && docker-php-ext-install -j$(nproc) iconv gettext gd soap curl intl \
    && docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu && docker-php-ext-install ldap \
    && rm -rf /var/lib/apt/lists/*

# Installation d'extensions PECL
RUN pear config-set http_proxy "$http_proxy"
RUN pecl install xdebug && docker-php-ext-enable xdebug

# Package PHP Oracle OCI8
ADD docker/instantclient-basiclite-linux.x64-12.2.0.1.0.zip /tmp/
ADD docker/instantclient-sdk-linux.x64-12.2.0.1.0.zip /tmp/
ADD docker/instantclient-sqlplus-linux.x64-12.2.0.1.0.zip /tmp/
RUN unzip /tmp/instantclient-basiclite-linux.x64-12.2.0.1.0.zip -d /usr/local/ && \
    unzip /tmp/instantclient-sdk-linux.x64-12.2.0.1.0.zip -d /usr/local/ && \
    unzip /tmp/instantclient-sqlplus-linux.x64-12.2.0.1.0.zip -d /usr/local/ && \
    ln -s /usr/local/instantclient_12_2 /usr/local/instantclient && \
    ln -s /usr/local/instantclient/libclntsh.so.12.1 /usr/local/instantclient/libclntsh.so && \
    ln -s /usr/local/instantclient/sqlplus /usr/bin/sqlplus && \
    echo 'export LD_LIBRARY_PATH="/usr/local/instantclient"' >> /etc/apache2/envvars && \
    echo 'export LD_LIBRARY_PATH="/usr/local/instantclient"' >> /root/.bashrc && \
    echo 'umask 002' >> /root/.bashrc && \
    echo 'instantclient,/usr/local/instantclient' | pecl install oci8 && \
    echo "extension=oci8.so" > /usr/local/etc/php/conf.d/php-oci8.ini

# Ajustement des config PHP.
#RUN printf "log_errors = On \nerror_log = /dev/stderr\n" > /usr/local/etc/php/conf.d/php-logs.ini
RUN echo "date.timezone = Europe/Paris"       >> /usr/local/etc/php/conf.d/01-timezone.ini && \
    echo "upload_max_filesize = 51M"          >> /usr/local/etc/php/conf.d/02-uploads.ini && \
    echo "post_max_size = 60M"                >> /usr/local/etc/php/conf.d/02-uploads.ini && \
    echo "error_reporting = E_ALL"            >> /usr/local/etc/php/conf.d/01-errors.ini && \
    echo "display_startup_errors = 1"         >> /usr/local/etc/php/conf.d/01-errors.ini && \
    echo "display_errors = 1"                 >> /usr/local/etc/php/conf.d/01-errors.ini && \
    echo "xdebug.remote_enable = 1"           >> /usr/local/etc/php/conf.d/20-xdebug.ini && \
    echo "xdebug.remote_connect_back = 1"     >> /usr/local/etc/php/conf.d/20-xdebug.ini && \
    echo "xdebug.profiler_enable_trigger = 1" >> /usr/local/etc/php/conf.d/20-xdebug.ini && \
    echo "xdebug.max_nesting_level = 250"     >> /usr/local/etc/php/conf.d/20-xdebug.ini

# Point de montage pour les sources de l'appli
VOLUME /webapp

EXPOSE 8000

# Configuration et activation du site Apache
RUN a2enmod rewrite
RUN echo "<VirtualHost *:80>"                >> /etc/apache2/sites-available/webapp.conf && \
    echo "     ServerName localhost"         >> /etc/apache2/sites-available/webapp.conf && \
    echo "     DocumentRoot /webapp/public"  >> /etc/apache2/sites-available/webapp.conf && \
    echo "     RewriteEngine On"             >> /etc/apache2/sites-available/webapp.conf && \
    echo "     <Directory /webapp/public>"   >> /etc/apache2/sites-available/webapp.conf && \
    echo "         DirectoryIndex index.php" >> /etc/apache2/sites-available/webapp.conf && \
    echo "         AllowOverride All"        >> /etc/apache2/sites-available/webapp.conf && \
    echo "         Require all granted"      >> /etc/apache2/sites-available/webapp.conf && \
    echo "     </Directory>"                 >> /etc/apache2/sites-available/webapp.conf && \
    echo "</VirtualHost>"                    >> /etc/apache2/sites-available/webapp.conf && \
    a2ensite webapp

