version: '2.2'

services:
  sygal:
    image: registre.unicaen.fr:5000/sygal-image-php7.3
    container_name: sygal-container-php7.3
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY
    ports:
      - "8003:443"
    volumes:
     - .:/app
     - /tmp:/tmp
     - $HOME/.ssh:/root/.ssh
    working_dir: /app
    networks:
      - sygalnet
    depends_on:
      - sygal-db

  sygal-db:
    image: registre.unicaen.fr:5000/sygal-db-image
    container_name: sygal-db-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      # Base de dev
      - ./docker/db/dev/sql/:/sql              # Scripts de création/init
      - ./data/db/dev:/var/lib/postgresql/data # Données persistées.
    networks:
      - sygalnet

  sygal-import-ws:
    image: registre.unicaen.fr:5000/sygal-import-ws-image-php7.0
    container_name: sygal-import-ws-container-php7.0
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY
    ports:
     - "8443:443"
    volumes:
     - ../sygal-import-ws:/app
     - /tmp:/tmp
    working_dir: /app
    networks:
      - sygalnet

networks:
  sygalnet:
    driver: bridge