version: '2.2'

services:
  sygal:
    image: sygal-image-php7.3
    container_name: sygal-container-php7.3
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
    ports:
      - "8003:443"
    volumes:
     - .:/app
     - /tmp:/tmp
     - $HOME/.ssh:/root/.ssh
    working_dir: /app
    networks:
      - sygalnet

  sygal-import-ws:
    image: sygal-import-ws-image-php7.0
    container_name: sygal-import-ws-container-php7.0
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
    ports:
     - "8443:443"
    volumes:
     - ../sygal-import-ws:/app
     - /tmp:/tmp
    working_dir: /app
    networks:
      - sygalnet

networks:
  sygalnet:
    driver: bridge