version: '3.7'

networks:
  sygalnet:
    name: sygalnet
    driver: bridge

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: minio/minio
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
    # environment:
    # MINIO_ROOT_USER: minioadmin
    # MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3
  networks:
    - sygalnet


services:
  sygal:
#    image: registre.unicaen.fr:5000/sygal-image-php8.0
    build:
      context: .
      args:
        - PHP_VERSION=8.0
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY
    ports:
      - "8003:443"
    volumes:
     - .:/app
     - /tmp:/tmp
     - /tmp/upload:/tmp/upload
     - $HOME/.ssh:/root/.ssh
     - $HOME/.cache/composer:/root/.cache/composer
     - ../sygal-pegase-connect/vendor/unicaen/sygal-api:/sygal-api
     - ./docker/configs/apache/conf-available/api.conf:/etc/apache2/conf-available/api.conf
     - ./docker/configs/apache/conf-available/livelog.conf:/etc/apache2/conf-available/livelog.conf
     - ./docker/configs/apache/conf-available/security.conf:/etc/apache2/conf-available/security.conf
     - ./docker/entrypoint.d/001_memcached:/entrypoint.d/001_memcached
     - ./docker/entrypoint.d/008_api:/entrypoint.d/008_api
     - ./docker/entrypoint.d/009_livelog:/entrypoint.d/009_livelog
    working_dir: /app
    networks:
      - sygalnet
    extra_hosts:
      - "host.docker.internal:host-gateway"

  sygal-db-demo:
    image: registre.unicaen.fr:5000/sygal-db-image
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      SYGAL_DB: sygal
      SYGAL_USER: ad_sygal
      SYGAL_PASSWORD: azerty
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/sql/demo:/sql                       # Scripts de création/init
      - ./docker/db/data/demo:/var/lib/postgresql/data  # Données persistées.
    networks:
      - sygalnet

  sygal-import-ws:
    image: registre.unicaen.fr:5000/sygal-import-ws-image-php7.4
    container_name: sygal-import-ws-container-php7.4
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY
    ports:
     - "8443:443"
    volumes:
     - ../sygal-import-ws:/app
     - /tmp:/tmp
    working_dir: /app
    networks:
      - sygalnet

  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ../minio/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
    networks:
      - sygalnet

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
