version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: minio/minio
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
    # environment:
    # MINIO_ROOT_USER: minioadmin
    # MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3
  networks:
    - sygalnet


services:
  sygal:
#    image: registre.unicaen.fr:5000/sygal-image-php7.4
    build:
      context: .
      args:
        - PHP_VERSION=7.4
    container_name: sygal-container-php7.4
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY
    ports:
      - "8003:443"
    volumes:
     - .:/app
     - /tmp:/tmp
     - $HOME/.ssh:/root/.ssh
     - ./docker/apache/livelog.conf:/etc/apache2/conf-available/livelog.conf
     - ./docker/entrypoint.d/009_livelog:/entrypoint.d/009_livelog
    working_dir: /app
    networks:
      - sygalnet
    depends_on:
      - sygal-db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  sygal-db:
    image: registre.unicaen.fr:5000/sygal-db-image
    container_name: sygal-db-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      SYGAL_DB: sygal
      SYGAL_USER: ad_sygal
      SYGAL_PASSWORD: azerty
    ports:
      - 5432:5432
    volumes:
      # Base de dev
      - ./tmp/docker/db/dev/sql/:/sql          # Scripts de création/init
      - ./data/db/dev:/var/lib/postgresql/data # Données persistées.
    networks:
      - sygalnet

  sygal-import-ws:
    image: registre.unicaen.fr:5000/sygal-import-ws-image-php7.4
    container_name: sygal-import-ws-container-php7.4
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY
    ports:
     - "8443:443"
    volumes:
     - ../sygal-import-ws:/app
     - /tmp:/tmp
    working_dir: /app
    networks:
      - sygalnet

  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ../minio/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
    networks:
      - sygalnet

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:

networks:
  sygalnet:
    driver: bridge