########################################################################################################################
#                           Image pour les tests unitaires/fonctionnels
#                            NE partant PAS de l'image Unicaen de base.
########################################################################################################################

FROM adrianharabula/php7-with-oci8

LABEL maintainer="Bertrand GAUTHIER <bertrand.gauthier at unicaen.fr>"

# Mise à niveau de la distrib.
RUN apt-get update && \
    apt-get install -y \
        git \
        libldap2-dev \
        libxml2-dev \
        libssl-dev \
        libcurl4-openssl-dev \
        libicu-dev \
        make \
        netcat-openbsd \
        phpunit \
        subversion \
        vim \
        wget && \
    rm -rf /var/lib/apt/lists/*

# Installation d'extensions PHP
RUN docker-php-ext-install -j$(nproc) gd soap curl gd intl
RUN docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu && docker-php-ext-install ldap

# Installation d'extensions PECL
RUN pear config-set http_proxy "$HTTP_PROXY"
RUN pecl install xdebug && docker-php-ext-enable xdebug

# Ajustement des config PHP.
RUN echo "date.timezone = Europe/Paris"       >> /usr/local/etc/php/conf.d/01-timezone.ini && \
    echo "upload_max_filesize = 51M"          >> /usr/local/etc/php/conf.d/02-uploads.ini && \
    echo "post_max_size = 60M"                >> /usr/local/etc/php/conf.d/02-uploads.ini && \
    echo "error_reporting = E_ALL"            >> /usr/local/etc/php/conf.d/01-errors.ini && \
    echo "display_startup_errors = 1"         >> /usr/local/etc/php/conf.d/01-errors.ini && \
    echo "display_errors = 1"                 >> /usr/local/etc/php/conf.d/01-errors.ini && \
#    echo "error_reporting = E_ALL"            >> /etc/php/7.0/cli/conf.d/01-errors.ini && \
#    echo "display_startup_errors = 1"         >> /etc/php/7.0/cli/conf.d/01-errors.ini && \
#    echo "display_errors = 1"                 >> /etc/php/7.0/cli/conf.d/01-errors.ini && \
    echo "xdebug.remote_enable = 1"           >> /usr/local/etc/php/conf.d/20-xdebug.ini && \
    echo "xdebug.remote_connect_back = 1"     >> /usr/local/etc/php/conf.d/20-xdebug.ini && \
    echo "xdebug.profiler_enable_trigger = 1" >> /usr/local/etc/php/conf.d/20-xdebug.ini && \
    echo "xdebug.max_nesting_level = 250"     >> /usr/local/etc/php/conf.d/20-xdebug.ini

# Point de montage pour les sources de l'appli
VOLUME /webapp

# Configuration et activation du site Apache
RUN echo "<VirtualHost *:80>"                >> /etc/apache2/sites-available/webapp.conf && \
    echo "     ServerName localhost"         >> /etc/apache2/sites-available/webapp.conf && \
    echo "     DocumentRoot /webapp/public"  >> /etc/apache2/sites-available/webapp.conf && \
    echo "     RewriteEngine On"             >> /etc/apache2/sites-available/webapp.conf && \
    echo "     <Directory /webapp/public>"   >> /etc/apache2/sites-available/webapp.conf && \
    echo "         DirectoryIndex index.php" >> /etc/apache2/sites-available/webapp.conf && \
    echo "         AllowOverride All"        >> /etc/apache2/sites-available/webapp.conf && \
    echo "         Require all granted"      >> /etc/apache2/sites-available/webapp.conf && \
    echo "     </Directory>"                 >> /etc/apache2/sites-available/webapp.conf && \
    echo "</VirtualHost>"                    >> /etc/apache2/sites-available/webapp.conf && \
    a2ensite webapp
