version: '2.2'

services:
  sygal:
    container_name: sygal-container
    build:
      args:
        PHP_VERSION: 7.0
      context: .
    ports:
     - "8000:80"
     - "443:443"
    volumes:
     - .:/app
     - /tmp:/tmp
     - $HOME/.ssh:/root/.ssh
    working_dir: /app
    network_mode: bridge

  sygal-import-ws:
    container_name: sygal-import-ws-container
    build:
      context: ../sygal-import-ws
      args:
        PHP_VERSION: 7.0
    ports:
     - "8080:80"
     - "8443:443"
    volumes:
     - ../sygal-import-ws:/app
    working_dir: /app
    network_mode: bridge
