<?php
/**
 * @var \RapportActivite\Entity\Db\RapportActivite $rapportActivite
 * @var \UnicaenAvis\Form\AvisForm $form
 * @var string $title
 */

$form->prepare();
?>

<?php $this->headTitle($this->translate($title))
    ->prepend("Nouvel avis")
    ->prepend($rapportActivite->getThese()->getDoctorant()->getIndividu()->getNomUsuel()) ?>

<h1 class="page-header"><?php echo $title ?></h1>

<dl>
    <dt>Rapport :</dt>
    <dd><?php echo $rapportActivite ?></dd>
    <dt>Type de rapport :</dt>
    <dd><?php echo $rapportActivite->getTypeRapportToString() ?></dd>
</dl>

<div class="row">
    <div class="col-md-7">
        <?php echo $this->partial('unicaen-avis/partial/avis-form', ['form' => $form]) ?>
    </div>
</div>