<?php
/**
 * @var \Doctorant\Entity\Db\Doctorant $doctorant
 * @var \Application\Entity\Db\MailConfirmation $mailConfirmation
 */

use UnicaenApp\View\Helper\Messenger;

?>

<h1 class="page-header">Votre adresse électronique de contact</h1>

<?php if ($mailConfirmation === null): ?>

    <?php
    echo $this->messenger()->setMessage(
        ":-( L'application ne dispose d'aucune adresse électronique vous concernant.",
        Messenger::ERROR
    ); ?>

<?php else: ?>

    <p class="lead">
        L'adresse électronique de contact que vous avez fournie est :
        <strong><?php echo $mailConfirmation->getEmail() ?></strong>
    </p>

<?php endif ?>

<p>
    Pour modifier votre adresse électronique de contact, veuillez cliquer sur le bouton ci-dessous.
</p>

<a href="<?php echo $this->url('doctorant/modifier-email-contact',['doctorant' => $doctorant->getId()], ['query' => ['force' => 1]], true) ?>"
   class="btn btn-info">Modifier mon adresse électronique de contact</a>
