<?php

namespace RapportActivite;

use Application\Entity\Db\Role;
use Application\Entity\Db\TypeValidation;
use Application\Filter\IdifyFilter;
use Application\Service\Rapport\RapportSearchService;
use Application\View\Renderer\PhpRenderer;
use RapportActivite\Entity\Db\RapportActivite;
use RapportActivite\Provider\Privilege\RapportActivitePrivileges;
use Structure\Search\EcoleDoctorale\EcoleDoctoraleSearchFilter;
use Structure\Search\Etablissement\EtablissementSearchFilter;
use Structure\Search\UniteRecherche\UniteRechercheSearchFilter;
use These\Filter\ActeursFormatter;

/**
 * @var PhpRenderer $this
 * @var RapportActivite[] $rapports
 * @var array[] $operationss
 *
 * @var TypeValidation $typeValidation
 *
 * @var bool $displayEtablissement
 * @var bool $displayType
 * @var bool $displayDoctorant
 * @var bool $displayDirecteurThese
 * @var bool $displayEcoleDoctorale
 * @var bool $displayUniteRecherche
 * @var bool $displayValidation
 * @var bool $displayAvis
 *
 * @var string $returnUrl
 *
 * @see \RapportActivite\Controller\RapportActiviteController::consulterAction()
 */

$acteursFormatterDirecteurs = new ActeursFormatter();
$acteursFormatterDirecteurs->asSeparated()
    ->paramDisplay(['role' => false, 'complement' => false, "qualite" => false, "etablissement" => false,])
    ->paramFilter((['role' => Role::CODE_DIRECTEUR_THESE]));
$acteursFormatterCodirecteurs = new ActeursFormatter();
$acteursFormatterCodirecteurs->asSeparated()
    ->paramDisplay(['role' => false, 'complement' => false, "qualite" => false, "etablissement" => false,])
    ->paramFilter((['role' => Role::CODE_CODIRECTEUR_THESE]));

$ajaxModalEvent = 'EVENT_AVIS_SAISI';
?>

<table class="table table-bordered table-hover rapport-activite">
    <thead>
    <tr>
        <?php if ($displayEtablissement): ?>
        <th>
            <a href="<?php echo $s = $this->sortable(EtablissementSearchFilter::NAME) ?>"
               title="<?php echo $this->translate("Établissement") ?> ">
                <?php echo $this->translate("Étab.") ?>
            </a> <?php echo $s->icon() ?>
        </th>
        <?php endif ?>

        <?php if ($displayType): ?>
        <th>
            <a href="<?php echo $s = $this->sortable(RapportSearchService::NAME_type); ?>"
               title="<?php echo $this->translate("Type"); ?>">
                <?php echo $this->translate("Type"); ?>
            </a> <?php echo $s->icon() ?>
        </th>
        <?php endif ?>

        <th>
            <a href="<?php echo $s = $this->sortable('anneeRapport'); ?>"
               title="<?php echo $this->translate("Année universitaire du rapport"); ?>">
                <?php echo $this->translate("Année"); ?>
            </a> <?php echo $s->icon() ?>
        </th>

        <?php if ($displayDoctorant): ?>
        <th>
            <a href="<?php echo $s = $this->sortable(RapportSearchService::NAME_nom_doctorant) ?>"
               title="<?php echo $this->translate("Identité du doctorant") ?>">
                <?php echo $this->translate("Doctorant") ?>
            </a> <?php echo $s->icon() ?>
        </th>
        <?php endif ?>

        <?php if ($displayDirecteurThese): ?>
        <th>
            <?php echo $this->translate("Directeur(s) de thèse"); ?>
        </th>
        <?php endif ?>

        <?php if ($displayEcoleDoctorale): ?>
        <th>
            <a href="<?php echo $s = $this->sortable(EcoleDoctoraleSearchFilter::NAME); ?>"
               title="<?php echo $this->translate("École doctorale"); ?>">
                <?php echo $this->translate("École<br>doct."); ?>
            </a> <?php echo $s->icon() ?>
        </th>
        <?php endif ?>

        <?php if ($displayUniteRecherche): ?>
        <th>
            <a href="<?php echo $s = $this->sortable(UniteRechercheSearchFilter::NAME); ?>"
               title="<?php echo $this->translate("Unité de recherche"); ?>">
                <?php echo $this->translate("Unité<br>rech."); ?>
            </a> <?php echo $s->icon() ?>
        </th>
        <?php endif ?>

        <th>
            Création
        </th>

        <th>
            Fichier
        </th>

        <?php if ($displayAvis || $displayValidation): ?>
            <th>
                Validations
            </th>
        <?php endif ?>

        <th class="action">
            Action
        </th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($rapports as $rapport): ?>
        <tr>
            <?php
            $these = $rapport->getThese();
            $rapportAviss = $rapport->getRapportAvis();
            $canList =
                $this->isAllowed(RapportActivitePrivileges::getResourceId(RapportActivitePrivileges::RAPPORT_ACTIVITE_LISTER_TOUT)) ||
                $this->isAllowed(RapportActivitePrivileges::getResourceId(RapportActivitePrivileges::RAPPORT_ACTIVITE_SUPPRIMER_SIEN));
            $canView =
                $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_CONSULTER_TOUT) ||
                $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_CONSULTER_SIEN);
            $canEdit =
                $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_MODIFIER_TOUT) ||
                $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_MODIFIER_SIEN);
            $canDel =
                $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_SUPPRIMER_TOUT) ||
                $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_SUPPRIMER_SIEN);
            $canDl =
                $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_TELECHARGER_TOUT) ||
                $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_TELECHARGER_SIEN);
            $canGen =
                $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_GENERER_TOUT) ||
                $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_GENERER_SIEN);
            ?>

            <?php if ($displayEtablissement): ?>
            <td>
                <abbr title="<?php echo $these->getEtablissement()->getStructure()->getLibelle() ?>">
                    <?php echo $these->getEtablissement()->getStructure()->getCode() ?>
                </abbr>
            </td>
            <?php endif ?>

            <?php if ($displayType): ?>
            <td>
                <?php echo $rapport->getTypeRapportLibelle() ?>
            </td>
            <?php endif ?>

            <td>
                <?php echo $rapport->getAnneeUniv() ?>
            </td>

            <?php if ($displayDoctorant): ?>
            <td>
                <?php echo $these->getDoctorant()->getIndividu()->getNomComplet() ?>
                <?php if ($canList): ?>
                    <p>
                        <a href="<?php echo $this->url('rapport-activite/lister', ['these' => $these->getId()], [], true) ?>"
                           class="small"
                           title="Aller à la page des rapports d'activité de <?php echo $these->getDoctorant() ?>">Rapports</a>
                    </p>
                <?php endif ?>
            </td>
            <?php endif ?>

            <?php if ($displayDirecteurThese): ?>
            <td class="acteurs text-sm">
                <?php
                $directeurs = $acteursFormatterDirecteurs->filter($these->getActeurs());
                foreach ($directeurs as $directeur) {
                    echo $acteursFormatterDirecteurs->htmlifyActeur($directeur)."<br/>";
                }
                $codirecteurs = $acteursFormatterCodirecteurs->filter($these->getActeurs());
                foreach ($codirecteurs as $codirecteur) {
                    echo $acteursFormatterCodirecteurs->htmlifyActeur($codirecteur)."<br/>";
                }
                ?>
            </td>
            <?php endif ?>

            <?php if ($displayEcoleDoctorale): ?>
            <td>
                <?php if ($ed = $these->getEcoleDoctorale()): ?>
                    <abbr title="<?php echo $ed->getStructure()->getLibelle() ?>">
                        <?php echo $ed->getStructure()->getCode(); ?>
                    </abbr>
                <?php endif ?>
            </td>
            <?php endif ?>

            <?php if ($displayUniteRecherche): ?>
            <td>
                <?php if ($ur = $these->getUniteRecherche()): ?>
                    <abbr title="<?php echo $ur->getStructure()->getLibelle() ?>">
                        <?php echo $ur->getStructure()->getCode(); ?>
                    </abbr>
                <?php endif ?>
            </td>
            <?php endif ?>

            <td>
                <?php echo $rapport->getHistoCreateur() ?><br>
                <?php echo $rapport->getHistoCreation()->format('d/m/Y H:i') ?>
            </td>

            <td>
                <?php if ($fichier = $rapport->getFichier()): ?>
                    <?php if ($canDl): ?>
                        <a href="<?php echo $this->url('rapport-activite/telecharger', ['rapport' => IdifyFilter::id($rapport)], ['query' => ['redirect' => $returnUrl]]) ?>"
                           title="Cliquez pour télécharger">
                            <?php echo $fichier->getNom() ?>
                        </a>
                    <?php else: ?>
                        <?php echo $fichier->getNom() ?>
                    <?php endif; ?>
                    <span class="icon icon-info text-info"
                          title="Il s'agit d'un rapport non dématérialisé téléversé dans l'ancienne version du module Rapport d'activité"></span>
                <?php else: ?>
                    Aucun
                    <span class="icon icon-info text-info"
                          title="Aucun fichier téléversé car il s'agit d'un rapport dématérialisé créé avec le nouveau module Rapport d'activité"></span>
                <?php endif; ?>
            </td>

            <?php if ($displayAvis || $displayValidation): ?>
            <td>
                <?php foreach ($operationss[$rapport->getId()] as $i => $operation): ?>
                    <?php
                    echo $this->partial('rapport-activite/partial/operation-card', [
                        'operation' => $operation,
                        'ajaxModalEvent' => $ajaxModalEvent,
                    ]);
                    ?>
                <?php endforeach ?>
            </td>
            <?php endif; ?>

            <td class="action">
                <?php if ($canView): ?>
                    <a href="<?php echo $this->url('rapport-activite/consulter', ['these' => $rapport->getThese()->getId(), 'rapport' => $rapport->getId()], ['query' => ['redirect' => $returnUrl]]) ?>"
                       title="Consulter ce rapport"><span class="icon icon-voir iconly"></span></a>
                <?php endif; ?>
                <?php if ($canEdit): ?>
                    <a href="<?php echo $this->url('rapport-activite/modifier', ['rapport' => $rapport->getId()], ['query' => ['redirect' => $returnUrl]]) ?>"
                       title="Modifier ce rapport"><span class="icon icon-modifier iconly"></span></a>
                    </a>
                <?php endif; ?>
                <?php if ($canDel): ?>
                    <a href="<?php echo $this->url('rapport-activite/supprimer', ['rapport' => $rapport->getId()], ['query' => ['redirect' => $returnUrl]]) ?>"
                       title="Supprimer ce rapport"
                       data-toggle="confirmationx"
                       data-message="Êtes-vous sûr de vouloir supprimer ce rapport ?"><span class="icon icon-delete iconly"></span></a>
                <?php endif; ?>
                <?php if ($canGen): ?>
                    <a href="<?php echo $this->url('rapport-activite/generer', ['rapport' => $rapport->getId()]) ?>"
                       title="Cliquez pour générer et télécharger le rapport au format PDF"><span class="icon icon-telecharger iconly"></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


<div class="modal fade" id="avisComplemsModal" tabindex="-1" aria-labelledby="avisComplemsModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="avisComplemsModalLabel">Détails de l'avis</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button>
            </div>
            <div class="modal-body">
                <!-- rempli dynamiquement -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(function() {
        const avisComplemsModal = document.getElementById('avisComplemsModal')
        avisComplemsModal.addEventListener('show.bs.modal', function (event) {
            // Button that triggered the modal
            const button = event.relatedTarget;
            const logFullContent = $(button).parent().siblings(".log-full-content").html();
            // Update the modal's content.
            const modalBody = avisComplemsModal.querySelector('.modal-body');
            $(modalBody).html(logFullContent);
        });

        // Gestion de la fermeture de la modale
        let ajaxModalEvent = '<?php echo $ajaxModalEvent ?>';
        $("body").on(ajaxModalEvent, function(event) {
            $("body").addClass("loading");
            event.div.modal('hide'); // ferme la fenêtre modale
            window.location.reload();
        });
    })
</script>