<?php

namespace RapportActivite;

use Application\Entity\Db\Role;
use Application\Entity\Db\TypeValidation;
use Application\Filter\ActeursFormatter;
use Application\Filter\IdifyFilter;
use Structure\Search\EcoleDoctorale\EcoleDoctoraleSearchFilter;
use Structure\Search\Etablissement\EtablissementSearchFilter;
use Structure\Search\UniteRecherche\UniteRechercheSearchFilter;
use Application\Service\Rapport\RapportSearchService;
use Application\View\Renderer\PhpRenderer;
use RapportActivite\Entity\Db\RapportActivite;
use RapportActivite\Provider\Privilege\RapportActivitePrivileges;

/**
 * @var PhpRenderer $this
 * @var RapportActivite[] $rapports
 *
 * @var TypeValidation $typeValidation
 *
 * @var bool $displayEtablissement
 * @var bool $displayType
 * @var bool $displayDoctorant
 * @var bool $displayDirecteurThese
 * @var bool $displayEcoleDoctorale
 * @var bool $displayUniteRecherche
 * @var bool $displayValidation
 * @var bool $displayAvis
 *
 * @var string $returnUrl
 *
 * @see \RapportActivite\Controller\RapportActiviteController::consulterAction()
 */

$acteursFormatterDirecteurs = new ActeursFormatter();
$acteursFormatterDirecteurs->asSeparated()
    ->paramDisplay(['role' => false, 'complement' => false, "qualite" => false, "etablissement" => false,])
    ->paramFilter((['role' => Role::CODE_DIRECTEUR_THESE]));
$acteursFormatterCodirecteurs = new ActeursFormatter();
$acteursFormatterCodirecteurs->asSeparated()
    ->paramDisplay(['role' => false, 'complement' => false, "qualite" => false, "etablissement" => false,])
    ->paramFilter((['role' => Role::CODE_CODIRECTEUR_THESE]));

$ajaxModalEvent = 'EVENT_AVIS_SAISI';
?>

<table class="table table-bordered table-hover">
    <thead>
    <tr>
        <?php if ($displayEtablissement): ?>
        <th>
            <a href="<?php echo $s = $this->sortable(EtablissementSearchFilter::NAME) ?>"
               title="<?php echo $this->translate("Établissement") ?> ">
                <?php echo $this->translate("Étab.") ?>
            </a> <?php echo $s->icon() ?>
        </th>
        <?php endif ?>

        <?php if ($displayType): ?>
        <th>
            <a href="<?php echo $s = $this->sortable(RapportSearchService::NAME_type); ?>"
               title="<?php echo $this->translate("Type"); ?>">
                <?php echo $this->translate("Type"); ?>
            </a> <?php echo $s->icon() ?>
        </th>
        <?php endif ?>

        <th>
            <a href="<?php echo $s = $this->sortable('anneeRapport'); ?>"
               title="<?php echo $this->translate("Année universitaire du rapport"); ?>">
                <?php echo $this->translate("Année"); ?>
            </a> <?php echo $s->icon() ?>
        </th>

        <?php if ($displayDoctorant): ?>
        <th>
            <a href="<?php echo $s = $this->sortable(RapportSearchService::NAME_nom_doctorant) ?>"
               title="<?php echo $this->translate("Identité du doctorant") ?>">
                <?php echo $this->translate("Doctorant") ?>
            </a> <?php echo $s->icon() ?>
        </th>
        <?php endif ?>

        <?php if ($displayDirecteurThese): ?>
        <th>
            <?php echo $this->translate("Directeur(s) de thèse"); ?>
        </th>
        <?php endif ?>

        <?php if ($displayEcoleDoctorale): ?>
        <th>
            <a href="<?php echo $s = $this->sortable(EcoleDoctoraleSearchFilter::NAME); ?>"
               title="<?php echo $this->translate("École doctorale"); ?>">
                <?php echo $this->translate("École<br>doct."); ?>
            </a> <?php echo $s->icon() ?>
        </th>
        <?php endif ?>

        <?php if ($displayUniteRecherche): ?>
        <th>
            <a href="<?php echo $s = $this->sortable(UniteRechercheSearchFilter::NAME); ?>"
               title="<?php echo $this->translate("Unité de recherche"); ?>">
                <?php echo $this->translate("Unité<br>rech."); ?>
            </a> <?php echo $s->icon() ?>
        </th>
        <?php endif ?>

        <th>
            Document téléversé
        </th>

        <?php if ($displayAvis): ?>
            <th>
                Statut
            </th>
        <?php endif ?>

        <?php if ($displayValidation): ?>
            <th>
                Validation
            </th>
        <?php endif ?>

        <th class="action">
            Action
        </th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($rapports as $rapport): ?>
        <tr>
            <?php
            $these = $rapport->getThese();
            $rapportValidation = $rapport->getRapportValidation();
            $rapportAviss = $rapport->getRapportAvis();
            $canList =
                $this->isAllowed(RapportActivitePrivileges::getResourceId(RapportActivitePrivileges::RAPPORT_ACTIVITE_LISTER_TOUT)) ||
                $this->isAllowed(RapportActivitePrivileges::getResourceId(RapportActivitePrivileges::RAPPORT_ACTIVITE_SUPPRIMER_SIEN));
            $canDel =
                $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_SUPPRIMER_TOUT) ||
                $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_SUPPRIMER_SIEN);
            $canDl =
                $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_TELECHARGER_TOUT) ||
                $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_TELECHARGER_SIEN);
            ?>

            <?php if ($displayEtablissement): ?>
            <td>
                <abbr title="<?php echo $these->getEtablissement()->getLibelle() ?>">
                    <?php echo $these->getEtablissement()->getCode() ?>
                </abbr>
            </td>
            <?php endif ?>

            <?php if ($displayType): ?>
            <td>
                <?php echo $rapport->getTypeRapportToString() ?>
            </td>
            <?php endif ?>

            <td>
                <?php echo $rapport->getAnneeUniv() ?>
            </td>

            <?php if ($displayDoctorant): ?>
            <td>
                <?php echo $these->getDoctorant()->getIndividu()->getNomComplet() ?>
                <?php if ($canList): ?>
                    <p>
                        <a href="<?php echo $this->url('rapport-activite/consulter', ['these' => $these->getId()], [], true) ?>"
                           class="small"
                           title="Aller à la page des rapports d'activité de <?php echo $these->getDoctorant() ?>">Rapports</a>
                    </p>
                <?php endif ?>
            </td>
            <?php endif ?>

            <?php if ($displayDirecteurThese): ?>
            <td class="acteurs text-sm">
                <?php
                $directeurs = $acteursFormatterDirecteurs->filter($these->getActeurs());
                foreach ($directeurs as $directeur) {
                    echo $acteursFormatterDirecteurs->htmlifyActeur($directeur)."<br/>";
                }
                $codirecteurs = $acteursFormatterCodirecteurs->filter($these->getActeurs());
                foreach ($codirecteurs as $codirecteur) {
                    echo $acteursFormatterCodirecteurs->htmlifyActeur($codirecteur)."<br/>";
                }
                ?>
            </td>
            <?php endif ?>

            <?php if ($displayEcoleDoctorale): ?>
            <td>
                <?php if ($ed = $these->getEcoleDoctorale()): ?>
                    <abbr title="<?php echo $ed->getLibelle() ?>">
                        <?php echo $ed->getStructure()->getCode(); ?>
                    </abbr>
                <?php endif ?>
            </td>
            <?php endif ?>

            <?php if ($displayUniteRecherche): ?>
            <td>
                <?php if ($ur = $these->getUniteRecherche()): ?>
                    <abbr title="<?php echo $ur->getLibelle() ?>">
                        <?php echo $ur->getStructure()->getCode(); ?>
                    </abbr>
                <?php endif ?>
            </td>
            <?php endif ?>

            <td>
                <?php if ($canDl): ?>
                    <a href="<?php echo $this->url('rapport-activite/telecharger', ['rapport' => IdifyFilter::id($rapport)]) ?>"
                       title="Cliquez pour télécharger">
                        <?php echo $rapport->getFichier()->getNom() ?>
                    </a>
                <?php else: ?>
                    <?php echo $rapport->getFichier()->getNom() ?>
                <?php endif; ?>
                <div class="text-sm">
                    <?php echo $rapport->getHistoCreateur() ?><br>
                    <?php echo $rapport->getHistoCreation()->format('d/m/Y H:i') ?>
                </div>
            </td>

            <?php if ($displayAvis): ?>
                <td>
                <?php
                $rapportAvisPossible = $rapport->getRapportAvisPossible();
                $canAjouterAvis = $rapportAvisPossible && (
                        $this->isAllowed($rapportAvisPossible, RapportActivitePrivileges::RAPPORT_ACTIVITE_AJOUTER_AVIS_TOUT) ||
                        $this->isAllowed($rapportAvisPossible, RapportActivitePrivileges::RAPPORT_ACTIVITE_AJOUTER_AVIS_SIEN)
                    );
                ?>
                    <?php foreach ($rapportAviss as $i => $rapportAvis): ?>
                    <?php
                    $canModifierAvis =
                        $this->isAllowed($rapportAvis, RapportActivitePrivileges::RAPPORT_ACTIVITE_MODIFIER_AVIS_TOUT) ||
                        $this->isAllowed($rapportAvis, RapportActivitePrivileges::RAPPORT_ACTIVITE_MODIFIER_AVIS_SIEN);
                    $canSupprimerAvis =
                        $this->isAllowed($rapportAvis, RapportActivitePrivileges::RAPPORT_ACTIVITE_SUPPRIMER_AVIS_TOUT) ||
                        $this->isAllowed($rapportAvis, RapportActivitePrivileges::RAPPORT_ACTIVITE_SUPPRIMER_AVIS_SIEN);
                    $avis = $rapportAvis->getAvis();
                    $statusClass = $avis->getAvisValeur()->getValeurBool() ? 'success' : 'danger';
                    ?>
                    <div class="card text-center validation-rapport-activite">
                        <div class="card-header">
                            <!--<span class="badge rounded-pill bg-secondary"><?php /*echo $i+1 */?></span>-->
                            <?php echo $avis->getAvisType()->getLibelle() ?>
                        </div>
                        <div class="card-body">
                            <div class="card-subtitle mb-2 text-sm text-muted">
                                <?php echo $rapportAvis->getHistoModificateur() ?: $rapportAvis->getHistoCreateur() ?>,
                                le <?php echo ($rapportAvis->getHistoModification() ?: $rapportAvis->getHistoCreation())->format('d/m/Y H:i') ?>
                            </div>
                            <p class="card-text text-<?php echo $statusClass ?>">
                                <span class="icon <?php echo $avis->getAvisValeur()->getTags() ?>"></span>
                                <strong><?php echo $avis->getAvisValeur()->getValeur() ?></strong>

                                <?php if ($avisComplemsToHtml = $avis->getAvisComplemsToHtml()): ?>
                                    <br>
                                    <a type="button" class="card-link text-sm" data-bs-toggle="modal" data-bs-target="#avisComplemsModal">
                                        <span class="fas fa-glasses" title="Voir les détails de la validation"></span> Détails
                                    </a>
                                <?php endif ?>
                            </p>
                            <div class="log-full-content d-none">
                                <p>Voici les compléments :</p>
                                <?php echo $avisComplemsToHtml ?>
                            </div>
                            <?php if ($canModifierAvis): ?>
                                <a href="<?php echo $this->url('rapport-activite/avis/modifier', ['rapportAvis' => $rapportAvis->getId()]) ?>"
                                   class="card-link btn btn-secondary btn-sm action ajax-modal"
                                   data-event="<?php echo $ajaxModalEvent ?>"
                                   title="Modifier cet avis ?">Modifier l'avis</span></a>
                            <?php endif ?>
                            <?php if ($canSupprimerAvis): ?>
                                <a href="<?php echo $this->url('rapport-activite/avis/supprimer', ['rapportAvis' => $rapportAvis->getId()], ['query' => ['redirect' => $returnUrl]]) ?>"
                                   class="card-link btn btn-warning btn-sm"
                                   title="Supprimer cet avis ?"
                                   data-toggle="confirmationx">Supprimer l'avis</span></a>
                            <?php endif ?>
                        </div>
                    </div>
                <?php endforeach ?>
                <?php if ($rapportAvisPossible !== null): ?>
                    <div class="card text-center validation-rapport-activite">
                        <div class="card-header">
                            <!--<span class="badge rounded-pill bg-secondary"><?php /*echo count($rapportAviss)+1 */?></span>-->
                            <?php echo $rapportAvisPossible->getAvis()->getAvisType()->getLibelle() ?>
                        </div>
                        <div class="card-body">
                            <p class="card-text">
                                En attente
                            </p>
                            <?php if ($canAjouterAvis): ?>
                                <a href="<?php echo $this->url('rapport-activite/avis/ajouter', ['rapport' => $rapport->getId()]) ?>"
                                   class="card-link btn btn-primary btn-sm action ajax-modal"
                                   data-event="<?php echo $ajaxModalEvent ?>">Saisir l'avis</span></a>
                            <?php endif ?>
                        </div>
                    </div>
                <?php endif ?>
                </td>
            <?php endif; ?>

            <?php if ($displayValidation): ?>
            <td>
                <?php $returnUrl = $returnUrl ?: $this->url('rapport-activite/consulter', ['these' => $these->getId()]) ?>
                <?php if ($rapportValidation !== null): ?>
                    <p>
                        <strong>Validé</strong> <br>
                        <span class="text-sm text-muted"><?php echo $rapportValidation->getHistoCreateur() ?><br>
                            <?php echo $rapportValidation->getHistoCreation()->format('d/m/Y H:i') ?></span>
                    </p>
                    <?php $canDevalider = $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_DEVALIDER_TOUT) || $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_DEVALIDER_SIEN) ?>
                    <?php if ($canDevalider): ?>
                        <a href="<?php echo $this->url('rapport-activite/devalider', ['rapportValidation' => $rapportValidation->getId()], ['query' => ['redirect' => $returnUrl]]) ?>"
                           class="btn btn-danger collapsable-action"
                           title="Dévalider ce rapport ?"
                           data-toggle="confirmationx"
                           data-message="Êtes-vous sûr·e de vouloir dévalider ?">Dévalider</span></a>
                    <?php endif ?>
                <?php else: ?>
                    <p>En attente d'avis.</p>
                    <?php $canValider = $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_VALIDER_TOUT) || $this->isAllowed($rapport, RapportActivitePrivileges::RAPPORT_ACTIVITE_VALIDER_SIEN) ?>
                    <?php if ($canValider): ?>
                        <a href="<?php echo $this->url('rapport-activite/valider', ['rapport' => $rapport->getId(), 'typeValidation' => $typeValidation->getId()], ['query' => ['redirect' => $returnUrl]]) ?>"
                           class="btn btn-success"
                           title="Valider ce rapport ?"
                           data-toggle="confirmationx"
                           data-message="Êtes-vous sûr·e de vouloir valider ce rapport ?">Valider</span></a>
                    <?php endif ?>
                <?php endif ?>
            </td>
            <?php endif; ?>

            <td class="action">
                <?php if ($canDel): ?>
                    <a href="<?php echo $this->url('rapport-activite/supprimer', ['rapport' => $rapport->getId()], ['query' => ['redirect' => $returnUrl]]) ?>"
                       title="Supprimer ce rapport"
                       data-toggle="confirmationx"
                       data-message="Êtes-vous sûr de vouloir supprimer ce rapport ?"><span class="icon icon-delete iconly"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


<div class="modal fade" id="avisComplemsModal" tabindex="-1" aria-labelledby="avisComplemsModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="avisComplemsModalLabel">Détails de l'avis</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button>
            </div>
            <div class="modal-body">
                <!-- rempli dynamiquement -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(function() {
        const avisComplemsModal = document.getElementById('avisComplemsModal')
        avisComplemsModal.addEventListener('show.bs.modal', function (event) {
            // Button that triggered the modal
            const button = event.relatedTarget;
            const logFullContent = $(button).parent().siblings(".log-full-content").html();
            // Update the modal's content.
            const modalBody = avisComplemsModal.querySelector('.modal-body');
            $(modalBody).html(logFullContent);
        });

        // Gestion de la fermeture de la modale
        let ajaxModalEvent = '<?php echo $ajaxModalEvent ?>';
        $("body").on(ajaxModalEvent, function(event) {
            $("body").addClass("loading");
            event.div.modal('hide'); // ferme la fenêtre modale
            window.location.reload();
        });
    })
</script>