<?php

namespace Substitution;

use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var \Doctrine\DBAL\Result $result
 *
 * @see \Substitution\Controller\IndexController::doctorantAction()
 */

?>

<?php $this->headTitle($this->translate("Substitutions de doctorants")) ?>

<h1 class="page-header">
    <span class="fas fa-object-group"></span>
    <?php echo $this->translate("Substitutions de doctorants"); ?>
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace(); ?>

<?php echo $this->partial('substitution/substitution/_partial/liste', [
    'result' => $result,
    'attributes' => ['to_ine' => 'INE'],
    'routeName' => 'doctorant/voir',
    'routeParamName' => 'doctorant',
]); ?>
