<?php

namespace Substitution;

use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var string $type
 * @var \Doctrine\DBAL\Result $result
 * @var int $count
 *
 * @see \Substitution\Controller\IndexController::doctorantAction()
 */

?>

<?php echo $this->partial('substitution/substitution/_partial/liste', [
    'type' => $type,
    'result' => $result,
    'count' => $count,
    'count' => $count,
    'attributes' => ['to_ine' => 'INE'],
]); ?>
