<h1> Aide sur les routes associés a la récupération de données</h1>

<p>Il existe deux route dans le module de récupération de données :
    <ol>
        <li> La route d'accés à l'aide : <b> fetch/help</b></li>
        <li> La route de récupération : <b> fetch/:SERVICE/:ETABLISSEMENT[/:SOURCE_ID]</b></li>
    </ol>
</p>

<p>
<table class="table-bordered">
    <tr><th>Variable</th><th>Valeur</th></tr>
    <tr><td>SERVICE</td>        <td> le service appelé (all, these, ...) </td></tr>
    <tr><td>ETABLISSEMENT</td>  <td> l'établissement dans lequel récupéré les données (UCN, fOO, ...) </td></tr>
    <tr><td>SOURCE_CODE</td>    <td> le code associé à un objet à récupérer (12047, 99003667, ...) </td></tr>
</table>
</p>

