<?php
/**
 * @var array $logs
 */
?>

<h1 class="page-header">
    Récupération paramétrée
</h1>

<h2>
    Paramètres
</h2>

<?php $parameterList = [ "service","etablissement", "source_code" ]; ?>

<table class="table table-bordered">
    <thead>
    <tr>
        <th> name </th>
        <th> value </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($parameterList as $parameter) : ?>
        <tr>
            <td> <?php echo $parameter; ?> </td>
            <td> <?php echo $$parameter; ?> </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<h2>Logs</h2>

<table class="table table-bordered">
    <thead>
    <tr>
        <th>date</th>
        <th>message</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($logs as $log) : ?>
        <tr>
            <td> <?php echo $log['date']->format('Y/m/d H:i:s '); ?> </td>
            <td> <?php echo $log['message']; ?> </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
