<?php
/**
 * @var string[] $codesEtablissements
 * @see ImportController::indexAction()
 */

?>

<h1 class="page-header">Import</h1>

<?php foreach ($codesEtablissements as $code): ?>

<h2><?php echo $code; ?></h2>

<div class="api-info" data-url="<?php echo $this->url('ws-import/api-info', ['etablissement' => $code]) ?>">
    <!-- chargée en AJAX -->
</div>

<?php endforeach; ?>


<script>
    $(function() {
        $(".api-info").each(function(index, element) {
            $(element).addClass("loading").refresh([], function () {
                $(element).removeClass("loading").fadeIn();
            });
        });
    })
</script>
