<?php


 /**
  * @var string $query
  * @var string $last_time
  * @var string $message
  */

 $date = new DateTime($last_time);

 ?>

<table class="table">
    <tbody>
    <tr>
        <td> <?php echo $query ; ?></td>
        <td> <?php echo $date->format("d/m/Y"); ?></td>
        <td> <?php echo $date->format("H:i:s"); ?></td>
        <td> <?php echo $message; ?></td>
    </tr>
    </tbody>

</table>