<?php

use Application\Entity\Db\Anomalie;

/**
 * @var array(string => Anomalie[]) $anomaliesTables
 */

$all = 0;
foreach ($anomaliesTables as $anomaliesTable) $all += count($anomaliesTable);

?>



<?php $this->headTitle($this->translate("Anomalies des données")); ?>


<h1 class="page-header first">
    <?php echo $this->translate("Anomalies des données"); ?>
    <span class="badge bg-secondary"><?php echo $all; ?></span>
</h1>

<!-- Formulaire de filtrage -->
<div class="float-start">
    <?php echo $this->partial('partial/form-filtrage', ['etablissements' => $etablissements]) ?>
</div>



<div class="float-end">
<?php
    $nombreAnomalies = count($anomaliesTables);
    switch($nombreAnomalies) {
        case 0 : echo "Aucune anomelie détectée.";
        break;
        case 1 : echo "Anomalie détectée dans la table :";
        break;
        default : echo "Anomalies détectées dans les ".$nombreAnomalies." tables :";
        break;
    }
?>

<ul>
    <?php
        foreach ($anomaliesTables as $tableName => $anomalies) {
            echo '<li><a href="#'.$tableName.'"> '.$tableName.'</a> <span class="badge bg-secondary">'.count($anomalies).'</span></li>';
        }
    ?>
</ul>
</div>

<div style="clear: both;"></div>

<div>
<?php


    foreach ($anomaliesTables as  $tableName => $anomalies) {
        echo '<a name="'.$tableName.'"></a>';
        echo '<h2> Anomalies associées à la table ['.$tableName.'] <span class="badge bg-secondary">'.count($anomalies).'</span></h2>';

        $anomalieType = [];
        /** @var Anomalie $anomalie */
        foreach ($anomalies as $anomalie) {
            $anomalieType[$anomalie->getTableColumn()]++;
        }

        echo '<ul>';
        foreach ($anomalieType as $colonne => $nombre) echo '<li>'.$colonne. ' <span class="badge bg-secondary">'.$nombre.'</span></li>';
        echo '</ul>';
        
        echo '<table class="table table-extra-condensed">';
        echo '<thead>';
        echo '    <tr>';
        echo '        <th>Source Code</th>';
        echo '        <th>Anomalie</th>';
        echo '        <th>Valeur</th>';
        echo '    </tr>';
        echo '</thead>';

        echo '<tbody>';
        /** @var Anomalie $anomalie */
        $previous = "";
        foreach($anomalies as $anomalie) {
            if ($previous === $anomalie->getSourceCode()) {
                echo '<tr>';
                echo '    <td style="border:white;"></td>';
            } else {
                $previous = $anomalie->getSourceCode();
                echo '<tr>';
                echo '    <td>' . $anomalie->getSourceCode() . '</td>';
            }
            echo '    <td>' . $anomalie->getDescription() . '</td>';
            echo '    <td>' . $anomalie->getTableColumn() . ' = ' . $anomalie->getColumnValue() . '</td>';
            echo '</tr>';

        }
        echo '</tbody>';
        echo '</table>';
    }
?>
</div>