<?php

namespace Substitution;

use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var \Doctrine\DBAL\Result $result
 * @var \Doctrine\DBAL\Result $operations
 *
 * @see \Substitution\Controller\IndexController::doctorantAction()
 */

?>

<?php echo $this->partial('substitution/log/_partial/liste', [
    'type' => 'doctorant',
    'result' => $result,
    'operations' => $operations,
    'logRoute' => 'substitution/log/doctorant',
]); ?>
