version: '2.2'

services:
  sygal-utln:
    image: registre.unicaen.fr:5000/sygal-image-php7.3
    container_name: sygal-utln-container-php7.3
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY
    ports:
      - "8003:443"
    volumes:
     - ../../:/app
     - /tmp:/tmp
    working_dir: /app
    networks:
      - sygalnet
    depends_on:
      - sygal-db-utln

  sygal-db-utln:
#    image: registre.unicaen.fr:5000/sygal-db-image
    image: sygal-db-image
    container_name: sygal-db-utln-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      SYGAL_DB: sygal_dev
      SYGAL_USER: ad_sygal_dev
      SYGAL_PASSWORD: azerty
    ports:
      - 5442:5432
    volumes:
      - ../../etabs/utln/tmp/build/sql/:/sql/              # Répertoire des scripts de création de la bdd
      - ../../etabs/utln/data/db:/var/lib/postgresql/data  # Répertoire pour persister la bdd
    networks:
      - sygalnet

networks:
  sygalnet:
    driver: bridge