<?php
/**
 * @see \Soutenance\Controller\PropositionController::confidentialiteAction()
 * @var ConfidentialiteForm $form
 * @var These|HDR $object
 * @var bool $validationsDejaEffectuees
 */

use HDR\Entity\Db\HDR;
use These\Entity\Db\These;
use Soutenance\Form\Confidentialite\ConfidentialiteForm;

?>

<?php
    if(isset($validationsDejaEffectuees) && $validationsDejaEffectuees): ?>
        <div class="alert alert-warning">
            <span class="icon icon-attention"></span>
            En cas de modification de la proposition, toutes les validations seront annulées et la proposition devra être à nouveau
            validée.
        </div>
    <?php endif;
    echo $this->form()->openTag($form);
    if ($object->getDateFinConfidentialite() === null) {
        echo $this->formControlGroup()->render($form->get('date'));
    }
    echo $this->formControlGroup()->render($form->get('huitClos'));
    echo $this->formControlGroup()->render($form->get('submit'));
    echo $this->form()->closeTag();
?>

