<?php

/**
 * @see \Soutenance\Controller\PropositionController::declarationNonPlagiatAction()
 * @var These $these
 * @var Validation $validation
 * @var string $urlValider
 * @var string $urlRefuser
 */

use Application\Entity\Db\Acteur;
use Application\Entity\Db\These;
use Application\Entity\Db\Validation;
use Soutenance\Provider\Privilege\PropositionPrivileges;
use Soutenance\Provider\Validation\TypeValidation;

$this->headTitle("Déclaration sur l'honneur de non plagiat");

$denomination =  $these->getDoctorant()->getIndividu()->getNomComplet(true, false, false, true);

$direction = "direction de thèse non déclarée";
/** @var Acteur $acteur */
$acteurs = [];
foreach ($these->getActeurs() as $acteur) {
    if ($acteur->estNonHistorise() and ($acteur->estDirecteur() or $acteur->estCodirecteur())) {
        $acteurs[] = $acteur;
    }
}
if (!empty($acteurs)) {
    usort($acteurs, function (Acteur $a, Acteur $b) {
        return $a->getIndividu()->getNomComplet() > $b->getIndividu()->getNomComplet();
    });
    $acteurs = array_map(function (Acteur $a) {
        return $a->getIndividu()->getNomComplet(true, false, false, true);
    }, $acteurs);
    $direction = implode(", ", $acteurs);
}

$unite = "unité de recherche non renseignée";
$ur = $these->getUniteRecherche();
if ($ur !== null) {
    $unite = $ur->getLibelle() . " (" . $ur->getSigle() . ")";
}

$canValider = $this->isAllowed($these, PropositionPrivileges::PROPOSITION_DECLARATION_HONNEUR_VALIDER);

?>

<div class="row">
    <div class="col-md-8">
        <h1 class="page-header">
            «&nbsp;Lutte anti-plagiat : Déclaration sur l’honneur&nbsp;»
        </h1>
    </div>
</div>

<p>
    Je soussigné(e), <?php echo $denomination; ?> , déclare par la présente que le manuscrit de thèse est le fruit de mon
    propre travail, réalisé sous la direction scientifique de <?php echo $direction; ?> au sein de l’Unité de Recherche
    <?php echo $unite; ?>, dans le respect des principes d’honnêteté, d’intégrité et de responsabilité inhérents à la
    mission de recherche.
</p>
<p>
    Je suis informé(e) de ce que l’absence de citation claire et transparente d’une source empruntée à un tiers (texte,
    raisonnement ou autre création) constitue une forme de plagiat. Je suis également conscient(e) que le plagiat, la
    falsification et/ou la fabrication de données sont des fautes graves susceptibles de conduire à des sanctions
    disciplinaires, allant jusqu’au renvoi de mon établissement d’inscription en thèse et à l’annulation du diplôme,
    et passibles de poursuites devant les tribunaux de la République Française.
</p>
<p>
    Au vu de ce qui précède, j’atteste sur l’honneur que mon manuscrit de thèse constitue une œuvre originale et que je
    n’ai pas eu recours au plagiat ou à toute autre forme de manquement à l'intégrité scientifique, tant dans la préparation
    de ma thèse que dans la rédaction du document final.
</p>

<div class="row">
    <div class="col-md-4">
        <?php if ($canValider): ?>
            <p>
        <span style="text-align: center">
        <a      href="<?php echo $urlValider;  ?>"
                class="btn btn-success" style="width:80%;">
            <span class="glyphicon glyphicon-thumbs-up"></span>
            Je signe
        </a>

            <br/>
            <br/>

        <a
                href="<?php echo $urlRefuser;  ?>"
                class="btn btn-danger" style="width:80%;"  data-event="modification">
            <span class="glyphicon glyphicon-thumbs-down"></span>
            Je ne signe pas </a>
        </span>

            </p>
        <?php else: ?>
            <div class="panel panel-danger">
                <div class="panel-heading">
                    Vous n'êtes pas habilité à signer cette déclaration sur l'honneur.
                </div>
            </div>
        <?php endif; ?>
    </div>
    <div class="col-md-8">
        <!-- affichage -->
        <?php if ($validation): ?>
            <div class="panel
            <?php  if ($validation && $validation->getTypeValidation()->getCode() === TypeValidation::CODE_VALIDATION_DECLARATION_HONNEUR): ?>
                panel-success
            <?php else : ?>
                panel-danger
            <?php endif; ?>
        ">
                <div class="panel-heading">
                    <?php echo $this->validation($validation) ?>
                </div>
            </div>
        <?php else: ?>
            <div class="panel panel-warning">
                <div class="panel-heading">
                    Aucune signature.
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
