<?php

use Soutenance\Entity\Proposition;
use Soutenance\Entity\PropositionThese;

/**
 * @see \Soutenance\Controller\PropositionController::generateViewInformationsAction()
 *
 * @var Proposition $proposition
 * @var boolean $canModifier
 * @var string $FORMULAIRE_DEMANDE_LABEL
 * @var string $FORMULAIRE_DEMANDE_ANGLAIS
 * @var string $FORMULAIRE_DEMANDE_CONFIDENTIALITE
 * @var string $typeProposition
 */

?>

<?php
if($proposition instanceof PropositionThese){
    echo $this->partial('soutenance/proposition-these/partial/informations-complementaires', [
        'proposition' => $proposition,
        'canModifier' => $canModifier,
        'FORMULAIRE_DEMANDE_LABEL' => $FORMULAIRE_DEMANDE_LABEL,
        'FORMULAIRE_DEMANDE_ANGLAIS' => $FORMULAIRE_DEMANDE_ANGLAIS,
        'FORMULAIRE_DEMANDE_CONFIDENTIALITE' => $FORMULAIRE_DEMANDE_CONFIDENTIALITE,
        'typeProposition' => $typeProposition
    ]);
}else{
    echo $this->partial('soutenance/proposition-hdr/partial/informations-complementaires', [
        'proposition' => $proposition,
        'canModifier' => $canModifier,
        'FORMULAIRE_DEMANDE_ANGLAIS' => $FORMULAIRE_DEMANDE_ANGLAIS,
        'FORMULAIRE_DEMANDE_CONFIDENTIALITE' => $FORMULAIRE_DEMANDE_CONFIDENTIALITE,
        'typeProposition' => $typeProposition
    ]);
}
?>