<?php

use Soutenance\Entity\Proposition;

/**
 * @see \Soutenance\Controller\PropositionController::generateViewJuryAction()
 *
 * @var Proposition $proposition
 * @var boolean $canModifier
 * @var array $indicateurs
 * @var string $FORMULAIRE_DELEGUATION
 * @var string $typeProposition
 */

?>

<?php
echo $this->partial('partial/composition-jury', [
    'proposition' => $proposition,
    'indicateurs' => $indicateurs,
    'canModifier' => $canModifier,
    'FORMULAIRE_DELEGUATION' => $FORMULAIRE_DELEGUATION,
    'typeProposition' => $typeProposition,]);
?>
