<?php

use Laminas\Form\Element;
use Soutenance\Entity\Proposition;
use Soutenance\Form\Membre\MembreForm;
use These\Entity\Db\These;

/**
 * @see \Soutenance\Controller\PropositionController::modifierMembreAction()
 * @var MembreForm $form
 * @var Proposition $proposition
 * @var bool $validationsDejaEffectuees
 */

$object = $proposition->getObject();
?>


<?php
if(isset($validationsDejaEffectuees) && $validationsDejaEffectuees): ?>
    <div class="alert alert-warning">
        <span class="icon icon-attention"></span>
        En cas de modification de la proposition, toutes les validations seront annulées et la proposition devra être à nouveau
        validée.
    </div>
<?php endif;
echo $this->form()->openTag($form);
echo $this->formControlGroup($form->get('sexe'));
echo $this->formControlGroup($form->get('prenom'));
echo $this->formControlGroup($form->get('nom'));
echo $this->formControlGroup($form->get('email'));
echo $this->formControlGroup($form->get('qualite'));
echo $this->formControlGroup($form->get('etablissement'));
echo $this->formControlGroup($form->get('adresse'));

/** @var Element $element */
$element = $form->get('exterieur');
if ($object->getEtablissement()->estComue()) {
    $element->setLabel('Le membre est extérieur (n\'appartient pas à l\'établissement qui délivre le dîplome)');
}else{
    if ($object instanceof These) {
        $element->setLabel("Le membre est extérieur (non membre d'un établissement de la COMUE et non membre de l'unité de recherche de la thèse) <span class='icon icon-obligatoire' style='color: darkred;font-size: 0.8em;' data-bs-toggle='tooltip' title='Obligatoire'></span> :");
    }else{
        $element->setLabel("Le membre est extérieur (n'appartient pas à l'établissement d'inscription du candidat HDR) <span class='icon icon-obligatoire' style='color: darkred;font-size: 0.8em;' data-bs-toggle='tooltip' title='Obligatoire'></span> :");
    }
}

echo $this->formControlGroup($form->get('exterieur'));
echo $this->formControlGroup($form->get('visio'));
echo $this->formControlGroup($form->get('role'));

echo $this->formControlGroup($form->get('submit'));
echo $this->form()->closeTag();
?>


<?php
//echo $this->form($form);
?>

<script>
    $('select').selectpicker();
    $(function () {
        $('[data-bs-toggle="tooltip"]').tooltip({});
    });
</script>
