<?php

use Application\Constants;
use Application\Entity\Db\Role;
use Application\Entity\Db\Validation;
use Depot\Controller\Plugin\UrlFichierThese;
use Doctorant\Entity\Db\Doctorant;
use Individu\Entity\Db\IndividuRole;
use Soutenance\Entity\Avis;
use Soutenance\Entity\Etat;
use Soutenance\Entity\Justificatif;
use Soutenance\Entity\Proposition;
use Soutenance\Provider\Privilege\JustificatifPrivileges;
use Soutenance\Provider\Privilege\PropositionPrivileges;
use Soutenance\Provider\Validation\TypeValidation;
use These\Entity\Db\Acteur;
use These\Entity\Db\These;

/**
 * @see \Soutenance\Controller\PropositionController::propositionAction()
 *
 * @var \Application\View\Renderer\PhpRenderer $this
 *
 * @var These $these
 * @var Proposition $proposition
 * @var Validation[] $validations
 * @var Doctorant $doctorant
 * @var Acteur[] $directeurs
 * @var Avis[] $avis
 * @var array $indicateurs
 * @var boolean $isOk
 * @var boolean $juryOk
 * @var UrlFichierThese $urlFichierThese ,
 * @var array $justificatifs ,
 * @var boolean $justificatifsOk ,
 * @var boolean $validationActeur
 *
 * @var Justificatif[] $attestationsIntegriteScientifique
 *
 * @var IndividuRole[] $ecoleResponsables
 * @var IndividuRole[] $uniteResponsables
 * @var IndividuRole[] $etablissementResponsables
 * @var bool $informationsOk
 *
 * @var $FORMULAIRE_DELOCALISATION
 * @var $FORMULAIRE_DELEGUATION
 * @var $FORMULAIRE_DEMANDE_LABEL
 * @var $FORMULAIRE_DEMANDE_ANGLAIS
 * @var $FORMULAIRE_DEMANDE_CONFIDENTIALITE
 */

$canModifier = ($this->isAllowed($these, PropositionPrivileges::PROPOSITION_MODIFIER) or $this->isAllowed($these, PropositionPrivileges::PROPOSITION_MODIFIER_GESTION));
$canModifierJustificatif = ($this->isAllowed($these, JustificatifPrivileges::JUSTIFICATIF_AJOUTER));

$this->headTitle("Proposition de soutenance");
?>

<?php echo $this->alertes()
    ->withCode(Constants::ALERTE_FERMETURE_ESTIVALE)
    ->withMatchingPlanning()
    ->renderAsBootstrapToasts() ?>

<h1 class="page-header">
    Proposition de soutenance
    <small><?php echo $this->partial('these/these/partial/titre') ?></small>
</h1>

<p class="lead">
    Afin d'être validée et traitée par l'école doctorale, la proposition de soutenance doit être validée par tous les
    intervenants immédiats de la thèse (c'est-à-dire doctorant, directeur et co-directeur).
    Les règles de composition du jury sont rappelées dans la page d'accueil <q>Guide de la thèse</q>.
</p>
<div class="alert alert-warning">
    <span class="icon icon-attention"></span>
    En cas de modifications de la proposition, toutes validations seront annulées et la proposition devra être à nouveau
    être validée.
</div>

<br/><br/>

<div class="INFORMATIONS"></div>
<?php
echo $this->partial('partial/informations', [
    'proposition' => $proposition,

    'informationsOk' => $informationsOk,
    'directeurs' => $directeurs,
    'uniteResponsables' => $uniteResponsables,
    'ecoleResponsables' => $ecoleResponsables,
    'etablissementResponsables' => $etablissementResponsables,

    'canModifier' => $canModifier]);
?>

<div id="DATE_ET_LIEU"></div>
<?php
echo $this->partial('partial/date-et-lieu', [
    'proposition' => $proposition,
    'canModifier' => $canModifier,
    'FORMULAIRE_DELOCALISATION' => $FORMULAIRE_DELOCALISATION]);
?>

<div id="COMPOSITION_JURY"></div>
<?php
echo $this->partial('partial/composition-jury', [
    'proposition' => $proposition,
    'indicateurs' => $indicateurs,
    'canModifier' => $canModifier,
    'FORMULAIRE_DELEGUATION' => $FORMULAIRE_DELEGUATION]);
?>


<div id="INFORMATION"></div>
<?php
echo $this->partial('partial/informations-complementaires', [
    'proposition' => $proposition,
    'canModifier' => $canModifier,
    'FORMULAIRE_DEMANDE_LABEL' => $FORMULAIRE_DEMANDE_LABEL,
    'FORMULAIRE_DEMANDE_ANGLAIS' => $FORMULAIRE_DEMANDE_ANGLAIS,
    'FORMULAIRE_DEMANDE_CONFIDENTIALITE' => $FORMULAIRE_DEMANDE_CONFIDENTIALITE]);
?>

<div id="JUSTIFICATIF"></div>
<?php echo $this->partial('partial/fichiers', [
    'proposition' => $proposition,
    'canModifier' => $canModifierJustificatif,
    'justificatifs' => $justificatifs,
    'justificatifsOk' => $justificatifsOk,
    'urlFichierThese' => $urlFichierThese,
]); ?>

<div id="DECLARATION"></div>
<?php echo $this->partial('partial/declaration-non-plagiat', [
    'these' => $these,
    'proposition' => $proposition,
    'validation' => $validations[TypeValidation::CODE_VALIDATION_DECLARATION_HONNEUR],
    'refus' => $validations[TypeValidation::CODE_REFUS_DECLARATION_HONNEUR],

    'canModifier' => $canModifierJustificatif,
    'urlFichierThese' => $urlFichierThese,
    'attestationsIntegriteScientifique' => $attestationsIntegriteScientifique,
]); ?>

<br/><br/>

<div id="VALIDATION"></div>
<?php
$canValiderActeur = $isOk && ($justificatifsOk !== false) && ($informationsOk !== false) && $this->isAllowed($these, PropositionPrivileges::PROPOSITION_VALIDER_ACTEUR);
$canSursis = $this->isAllowed(PropositionPrivileges::getResourceId(PropositionPrivileges::PROPOSITION_SURSIS));

echo $this->partial('partial/validations-acteurs', [
    'proposition' => $proposition,
    'validations' => $validations,
    'canValiderActeur' => $canValiderActeur,
    'canSursis' => $canSursis,

    'isOk' => $isOk,
    'doctorant' => $doctorant,
    'directeurs' => $directeurs,
    'validationActeur' => $validationActeur,

    'informationsOk' => $informationsOk,

]); ?>

<?php
$canStructureValider = $isOk && $this->isAllowed($these, PropositionPrivileges::PROPOSITION_VALIDER_UR) ||
    $this->isAllowed($these, PropositionPrivileges::PROPOSITION_VALIDER_ED) ||
    $this->isAllowed($these, PropositionPrivileges::PROPOSITION_VALIDER_BDD);
$canPresidence = $this->isAllowed($these, PropositionPrivileges::PROPOSITION_PRESIDENCE);

echo $this->partial('partial/validations-structures', [
    'proposition' => $proposition,
    'validations' => $validations,
    'canStructureValider' => $canStructureValider,
    'canPresidence' => $canPresidence,
]); ?>

<?php
echo $this->partial('partial/pre-rapports', [
    'these' => $these,
    'avis' => $avis,
]);
?>

<?php
$validationMDD = null;
if ($validations[Role::CODE_BDD]) {
    $validationMDD = current($validations[Role::CODE_BDD]);
}

if ($validationMDD and $proposition->getEtat()->getCode() === Etat::EN_COURS and $canPresidence): ?>
    <div class="box card">
        <div class="card-header bg-success">
            <h2 class="first"> Et ensuite ? </h2>
        </div>
        <div class="card-body">

            Vous pouvez maintenant procéder aux saisies des informations de préparation de la soutenance.
            <nav aria-label="Etape suivante">
                <ul class="roadmap pagination">
                    <li>
                        <a
                            <?php /** @see \Soutenance\Controller\AvisController::indexAction() */ ?>
                                class="roadmap-step-link"
                                href="<?php echo $this->url('soutenance/presoutenance', ['these' => $these->getId()], [], true); ?>">
                            <span class="fas fa-arrow-alt-circle-right"></span>
                            Préparation de la soutenance
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
<?php endif; ?>

<script>
    let navbar = 50 + 5;

    $(function () {
        $("body").on({
            "edition-datelieu": function (event) {
                event.div.modal('hide');
                $.ajax({
                    type: "POST",
                    url: "<?php echo $this->url('soutenance/proposition/generate-view-date-lieu', ["these" => $these->getId()], [], true); ?>",
                    beforeSend:
                        function () {
                            $("div#BOXDIV_DATE_LIEU").html("<div class='alert alert-warning'> <span class='fas fa-exclamation-triangle'></span> Rechargement de la vue associée à la date et lieu de soutenance.</div><br/>");
                        },
                    success:
                        function (retour) {
                            $("div#BOXDIV_DATE_LIEU").html(retour);
                        }
                });

                // window.location.reload();
                // let top = $('div#DATE_ET_LIEU').offset().top - navbar;
                // window.scrollTo(0,top);
            },
            "edition-membre": function (event) {
                event.div.modal('hide');
                //$.ajax({
                //    type: "POST",
                //    url : "<?php //echo $this->url('soutenance/proposition/generate-view-jury', ["these" => $these->getId()], [], true); ?>//",
                //    beforeSend:
                //        function () {
                //            $("div#BOXDIV_JURY").html("<div class='alert alert-warning'> <span class='icon icon-warning'></span> Rechargement de la vue associée au jury.</div><br/>");
                //        },
                //    success:
                //        function(retour){
                //            let texte = "ok";
                //            $("div#BOXDIV_JURY").html(retour);
                //        }
                //});

                window.location.reload();
                let top = $('div#COMPOSITION_JURY').offset().top - navbar;
                window.scrollTo(0, top);
            },
            "edition-informations": function (event) {
                event.div.modal('hide');
                //$.ajax({
                //    type: "POST",
                //    url : "<?php //echo $this->url('soutenance/proposition/generate-view-informations', ["these" => $these->getId()], [], true); ?>//",
                //    beforeSend:
                //        function () {
                //            $("div#BOXDIV_INFORMATIONS").html("<div class='alert alert-warning'> <span class='icon icon-warning'></span> Rechargement de la vue associée aux inforamtions.</div><br/>");
                //        },
                //    success:
                //        function(retour){
                //            let texte = "ok";
                //            $("div#BOXDIV_INFORMATIONS").html(retour);
                //        }
                //});

                window.location.reload();
                let top = $('div#BOXDIV_INFORMATIONS').offset().top - navbar;
                window.scrollTo(0, top);
            },
            "edition-confidentialite": function (event) {
                event.div.modal('hide');
                window.location.reload();
            },
            "refus-proposition": function (event) {
                event.div.modal('hide');
                window.location.reload();
            },
        });
    });

    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });

</script>