<?php

use UnicaenAuth\Provider\Privilege\Privileges;

$canViewRoles      = $this->isAllowed(Privileges::getResourceId(Privileges::DROIT_ROLE_VISUALISATION));
$canViewPrivileges = $this->isAllowed(Privileges::getResourceId(Privileges::DROIT_PRIVILEGE_VISUALISATION));
$canViewProfils = $this->isAllowed(Privileges::getResourceId(Privileges::DROIT_PRIVILEGE_VISUALISATION));

?>
<h1 class="page-header">Gestion des droits d'accès</h1>

<dl>
    <?php if ($canViewRoles): ?>
        <dt><a href="<?php echo $this->url('droits/roles') ?>">Rôles</a></dt>
        <dd>
            Page consacrée aux différents <em>rôles</em> existants.
        </dd>
    <?php endif; ?>

    <?php if ($canViewProfils): ?>
        <dt><a href="<?php echo $this->url('profil') ?>">Profils et privilèges</a></dt>
        <dd>
            Page consacrée aux <em>profils</em> et à leur attribution de privilèges.
        </dd>
    <?php endif; ?>

    <?php if ($canViewPrivileges): ?>
        <dt><a href="<?php echo $this->url('gestion-privilege') ?>">Rôles et privilèges</a></dt>
        <dd>
            Page consacrées à l'attribution directe de privilèges aux rôles n'étant liés à aucun profil.
        </dd>
    <?php endif; ?>
</dl>
<style>

    dt {
        padding-top: 2em;
    }

</style>