<h1 class="page-header">Gestion des rôles</h1>
<?php

use Application\Entity\Db\Role;
use UnicaenAuth\Provider\Privilege\Privileges;

/* @var $roles Role[] */

$canEdit = $this->isAllowed('privilege/'.Privileges::DROIT_ROLE_EDITION);
$ajoutUrl = $this->url( 'droits/roles/edition' );

?>
<table class="table table-condensed table-bordered">
    <tr>
        <th>Role (ROLE_ID)</th>
        <th>Code</th>
        <th>Source code</th>
        <th>Type structure</th>
        <?php if ($canEdit): ?><th>Action</th><?php endif; ?>
    </tr>
<?php foreach( $roles as $role ):
    $editionUrl     = $this->url( 'droits/roles/edition',     ['role' => $role->getId()] );
    $suppressionUrl = $this->url( 'droits/roles/suppression', ['role' => $role->getId()] );

    $importe = $role->getSource() && $role->getSource()->getImportable();
    $historise = $role->getHistoDestruction() !== null;
    $canEditThisRole = $canEdit && !$importe;

    $class = implode(' ', array_filter([
        $importe ? 'imported-role-name' : null,
        $historise ? 'historise-role-name' : null,
    ]))
?>
    <tr>
        <td><span class="<?php echo $class ?>"><?php echo $role->getRoleId(); ?></span></td>
        <td><?php echo $role->getCode(); ?></td>
        <td><?php echo $role->getSourceCode(); ?></td>
        <td><?php echo $role->getTypeStructureDependant(); ?></td>
        <td style="width:1%;white-space: nowrap;text-align: center">
            <?php if ($canEditThisRole): ?>
            <a href="<?php echo $editionUrl; ?>" class="ajax-modal" data-event="role-edition"><span class="glyphicon glyphicon-edit"></span></a>
            <a href="<?php echo $suppressionUrl; ?>" class="ajax-modal" data-event="role-suppression"><span class="glyphicon glyphicon-remove"></span></a>
            <?php endif; ?>
        </td>
    </tr>
<?php endforeach; ?>
</table>
<?php if ($canEdit): // droits ?>
<a href="<?php echo $ajoutUrl ?>" class="btn btn-primary ajax-modal" data-event="role-edition">Création d'un nouveau rôle</a>
<?php endif; ?>
<?php echo $this->modalAjaxDialog('roles-edition-suppression'); ?>
<script type="text/javascript">
    $(function() {
        $("body").on("role-edition", function(event, data) {
            window.location.reload();
        }).on("role-suppression", function(event, data) {
            window.location.reload();
        });
    });
</script>