<?php

use Formation\Entity\Db\Session;
use UnicaenApp\Form\Element\SearchAndSelect;

/**
 * @see \Formation\Controller\FormateurController::ajouterAction()
 * @var Session $session
 */

?>

<form method="post" action="<?php echo $this->url('formation/formateur/ajouter', ['session' => $session->getId()], [], true); ?>">
    <?php
    $sas = new SearchAndSelect('individu');
    $sas->setLabel($this->translate("Recherche d'un·e formateur·trice"));
    $sas->setAttribute('class', 'individu-finder');
    /** @see Uti::rechercherAction() */
    $sas->setAutocompleteSource($this->url('individu/rechercher', [], [], true));
    echo $this->formControlGroup($sas, 'formSearchAndSelect');
    ?>

    <input type="Submit" value="Ajouter le·a formateur·trice" class="btn btn-primary" />
</form>
