<?php
/**
 * @var \StepStar\Form\Envoi\EnvoiFichiersForm $form
 *
 * @see \StepStar\Controller\Envoi\EnvoiController::envoyerFichiersAction()
 */

$form->prepare();
?>

<h1 class="page-header">Envoi de fichiers</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace() ?>

<div class="row">
    <div class="col-md-5">
        <?php echo $this->form()->openTag($form); ?>
        <?php echo $this->formControlGroup()->render($form->get('path')); ?>
        <?php echo $this->formControlGroup()->render($form->get('submit')); ?>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>



