<?php

/**
 * @see \Soutenance\Controller\IndexController::indexStructureAction()
 * @var Proposition[] $propositions
 * @var Role $role
 * @var Etablissement[] $etablissements
 * @var EcoleDoctorale[] $ecoles
 * @var UniteRecherche[] $unites
 * @var Etat[] $etats
 * @var integer $etablissementId
 * @var integer $ecoleDoctoraleId
 * @var integer $uniteRechercheId
 * @var integer $etatId
 */

use Structure\Entity\Db\EcoleDoctorale;
use Structure\Entity\Db\Etablissement;
use Application\Entity\Db\Role;
use These\Entity\Db\These;
use Structure\Entity\Db\UniteRecherche;
use These\Provider\Privilege\ThesePrivileges;
use Soutenance\Entity\Etat;
use Soutenance\Entity\Proposition;

$canVoirThese = $this->isAllowed(ThesePrivileges::getResourceId(ThesePrivileges::THESE_CONSULTATION_FICHE));
$canSuppression = ($role->getCode() === Role::CODE_ADMIN_TECH);
?>

<h1 class="page-header">
    Index des propositions en cours
    <span class="badge bg-secondary">
        <?php echo count($propositions); ?>
    </span>
</h1>

<?php echo $this->partial('partial/filtre-proposition',
    ['etablissements' => $etablissements, 'ecoles' => $ecoles, 'unites' => $unites, 'etats' => $etats,
     'etablissementId' => $etablissementId, 'ecoleDoctoraleId' => $ecoleDoctoraleId, 'uniteRechercheId' => $uniteRechercheId, 'etatId' => $etatId ]); ?>

<table class="table table-sm">
    <thead>
        <tr>
            <th class="title-column">
                These
            </th>
            <th>
                Doctorant
            </th>
            <th>
                Direction
            </th>
            <th>
                Structures
            </th>
            <th>
                État
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($propositions as $proposition) : ?>
                <?php
                    /** @var These $these **/
                    $these = $proposition->getThese();
                    $unite = $these->getUniteRecherche();
                ?>
                <tr>
                    <td>
                        <?php if ($canVoirThese) : ?>
                            <a  <?php /** @see \These\Controller\TheseController::detailIdentiteAction() */ ?>
                                href="<?php echo $this->url('these/identite', ['these' => $proposition->getThese()->getId()], [] ,true); ?>">
                        <?php endif; ?>
                            <?php echo $proposition->getThese()->getTitre(); ?>
                        <?php if ($canVoirThese) : ?>
                            </a>
                            <?php if ($proposition->getDate()) : ?>
                                <br>
                                Date de soutenance prévue : <?php echo $proposition->getDate()->format('d/m/Y à H:i'); ?>
                            <?php endif; ?>
                        <?php endif; ?>
                    </td>
                    <td> <?php echo $proposition->getThese()->getDoctorant()->getIndividu(); ?> </td>
                    <td>
                        <?php foreach ($proposition->getThese()->getEncadrements() as $encadrement) : ?>
                            <?php if ($encadrement->getRole()->getCode() !== Role::CODE_DIRECTEUR_THESE) echo "<i>"; ?>
                            <?php echo $encadrement->getIndividu() ; ?>
                            <?php if ($encadrement->getRole()->getCode() !== Role::CODE_DIRECTEUR_THESE) echo "</i>"; ?>
                            <br/>
                        <?php endforeach; ?>
                    </td>
                    <td>
                        <?php if ($these->getEtablissement()) : ?>
                            <span class="structure etablissement"
                                  title="Établissement : <?php echo $these->getEtablissement()->getStructure()->getLibelle(); ?> (<?php echo $these->getEtablissement()->getStructure()->getSourceCode(); ?>)"
                            >
                                <?php echo $these->getEtablissement()->getStructure()->getLibelle(); ?>
                            </span>
                        <?php else : ?>
                            <strong style="color:darkred;">
                                Établissement  : Aucun
                            </strong>
                        <?php endif; ?>
                        <br/>

                        <?php if ($these->getEcoleDoctorale()) : ?>
                            <span class="structure ecole-doctorale"
                                  title="École doctorale : <?php echo $these->getEcoleDoctorale()->getStructure()->getLibelle(); ?> <?php echo "(".$these->getEcoleDoctorale()->getStructure()->getSigle() .")"; ?>"
                            >
                                <?php echo $these->getEcoleDoctorale()->getStructure()->getLibelle(); ?>
                            </span>
                        <?php else : ?>
                            <strong style="color:darkred;">
                                École doctorale  : Aucune
                            </strong>
                        <?php endif; ?>
                        <br/>

                        <?php if ($these->getUniteRecherche()) : ?>
                            <span class="structure unite-recherche"
                                  title="Unité de recherche : <?php echo $these->getUniteRecherche()->getStructure()->getLibelle(); ?> <?php echo "(".$these->getUniteRecherche()->getStructure()->getSigle() .")"; ?>"
                            >
                                <?php echo $these->getUniteRecherche()->getStructure()->getLibelle(); ?>
                            </span>
                        <?php else : ?>
                            <!-- Gestion des unités de recherche -->
                            <strong style="color:darkred;">
                                Unité de recherche :
                                <?php if ($these->getLibelleUniteRecherche() === null) : ?>
                                    Aucune
                                <?php else : ?>
                                    <?php echo $these->getLibelleUniteRecherche(); ?>
                                <?php endif; ?>
                            </strong>
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php echo $this->etatSoutenance()->render($proposition->getEtat()); ?>
                    </td>
                    <td>
                        <a
                            <?php /** @see \Soutenance\Controller\PropositionController::propositionAction() */ ?>
                            href="<?php echo $this->url('soutenance/proposition', ['these' => $proposition->getThese()->getId()], [], true); ?>"
                           title="Visualiser la proposition de soutenance"
                        >
                            Proposition
                        </a>
                        <br/>
                        <a
                            <?php /** @see \Soutenance\Controller\PresoutenanceController::presoutenanceAction() */ ?>
                            href="<?php echo $this->url('soutenance/presoutenance', ['these' => $proposition->getThese()->getId()], [], true); ?>"
                           title="Visualiser la préparation de la soutenance"
                        >
                            Présoutenance
                        </a>
                        <br/>
                        <?php if ($canSuppression) : ?>
                        <a
                            <?php /** @see \Soutenance\Controller\PropositionController::suppressionAction() */ ?>
                            href="<?php echo $this->url('soutenance/proposition/suppression', ['these' => $proposition->getThese()->getId()], [], true); ?>"
                           title="">
                            Suppression
                        </a>
                        <?php endif; ?>
                    </td>
                </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<style>
    th.title-column {
        width:70rem;
    }

    span.structure {
        display: inline-block;
        margin-bottom: 0.5rem;
        /*font-weight: 500;*/
    }
    span.etablissement {
        /*color:darkred;*/
    }

    span.ecole-doctorale {
        /*color:darkblue;*/
    }

    span.unite-recherche {
        /*color:darkgreen;*/
    }
</style>