<?php

/**
 * @see \Soutenance\Controller\IndexController::indexActeurAction()
 *
 * @var These[] $theses
 */

use Application\Entity\Db\These;
use Soutenance\Provider\Privilege\PropositionPrivileges;
use Soutenance\Provider\Privilege\EngagementImpartialitePrivileges;

$this->headTitle("Gestion de la préparation de la soutenance");

$canProposer   = $this->isAllowed(EngagementImpartialitePrivileges::getResourceId(PropositionPrivileges::PROPOSITION_MODIFIER));
$canVisualiser = $this->isAllowed(EngagementImpartialitePrivileges::getResourceId(PropositionPrivileges::PROPOSITION_VISUALISER));
?>

<h1 class="page-header">
    Gestion de la préparation de la soutenance
</h1>

<p class="lead">
    Ce module permet de préparer votre soutenance de thèse, de la <strong>proposition du jury jusqu'à la réception des rapports de pré-soutenance</strong>.
</p>

<h2> Constituer votre jury de thèse </h2>

<p>
    <?php echo $this->appInfos()->nom ?> permet la constitution de votre jury de thèse de façon dématérialisée et ceci en deux étapes :
</p>
<ol>
    <li> <strong>proposition</strong> de jury par le doctorant et le directeur de thèse (et le cas échéant le co-directeur de thèse) ;</li>
    <li> <strong>validation de cette proposition</strong> successivement par le directeur de l'unité de recherche, l'école doctorale et la maison du doctorat.</li>
</ol>

<strong>Attention, votre jury doit respecter les règles suivantes :</strong>
    <ul>
        <li> le jury doit inclure deux rapporteurs, extérieurs aux établissements membres de la ComUE Normandie Université, et soit de rang A (Professeur des universités, Directeur de recherche, ...), soit d’un niveau équivalent (Professeur ou personnalité exerçant à l’étranger qui peuvent justifier d’un statut équivalent), soit de rang B détenteur d’une HDR (Maître de Conférence-HDR, Chargé de Recherche-HDR) ;</li>
        <li> au moins la moitié des membres doivent être de rang A (Professeur des universités, Directeur de recherche, ...) ou équivalents (Professeur ou personnalité à l’étranger qui peuvent justifier d’un statut équivalent) ; </li>
        <li> au moins la moitié des membres doivent être extérieurs aux établissements membres de la ComUE Normandie Université. </li>
    </ul>

    <u>N.B. :</u> En fonction des disciplines, le jury doit respecter un équilibre entre hommes et femmes..


<p>
    Lors de cette étape, il pourra vous être demandé de télécharger des documents et justificatifs (délégation de signature, attestation d’HDR ...)
</p>

    <?php if ($canProposer && $theses !== []) : ?>
        <div class="btn-group pull-right action">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-pencil"></span>
                Consulter les propositions <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <?php foreach($theses as $theseLink) : ?>
                    <li class="complete">
                        <a
                            <?php /** @see \Soutenance\Controller\PropositionController::propositionAction() */ ?>
                            href="<?php echo $this->url('soutenance/proposition', ['these' => $theseLink->getId()], [], true); ?>">
                            <span class="badge"><?php echo $theseLink->getDoctorant(); ?></span>
                            <?php
                                 echo $this->partial('application/these/partial/titre', ['these' => $theseLink, 'useTitreThese' => true, 'length' => 120, 'description' => false])
                            ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>

<h2> Voir l'avancement des validations de votre soutenance </h2>

<p>
    Avant de pouvoir soutenir, <strong>votre proposition de jury doit être validée</strong> par les directeur et co-directeur de thèse, directeur de l’unité de recherche, l’école doctorale et l’établissement d’inscription puis <strong>votre thèse doit recevoir un avis positif des 2 rapporteurs</strong> de votre thèse.
    Afin de suivre ces validations, <?php echo $this->appInfos()->nom ?> fournit une interface permettant de suivre l'évolution de la procédure.
    Cette interface permet de connaître la liste de validations reçues et celles en attente.
</p>

    <?php if ($canVisualiser && $theses !== []) : ?>
        <div class="btn-group pull-right action">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-eye-open"></span>
                Voir les validations <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
<!--                --><?php //foreach($theses as $theseLink) : ?>
<!--                    <li class="complete">-->
<!--                        <a  --><?php ///** @see \Soutenance\Controller\PropositionController::avancementAction() */ ?>
<!--                            href="--><?php //echo $this->url('soutenance/avancement', ['these' => $theseLink->getId()], [], true); ?><!--">-->
<!--                            <span class="badge">--><?php //echo $theseLink->getDoctorant(); ?><!--</span>-->
<!--                            --><?php
//                            echo $this->partial('application/these/partial/titre', ['these' => $theseLink, 'useTitreThese' => true, 'length' => 120, 'description' => false])
//                            ?>
<!--                        </a>-->
<!--                    </li>-->
<!--                --><?php //endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>

<style>
    .action {
        width: 20em;
    }
</style>
