<?php

/**
 * @see \Soutenance\Controller\IndexController::indexRapporteurAction()
 *
 * @var Proposition $proposition
 * @var These[] $theses
 * @var Membre $membre
 * @var boolean $depot
 * @var These $these
 * @var Validation $engagement
 * @var Avis $avis
 * @var string $telecharger

 */

use Application\Constants;
use Application\Entity\Db\Role;
use These\Entity\Db\These;
use Application\Entity\Db\Validation;
use Soutenance\Entity\Avis;
use Soutenance\Entity\Membre;
use Soutenance\Entity\Proposition;
use Soutenance\Provider\Privilege\AvisSoutenancePrivileges;

$canEngagement = true;
$canTelecharger = true;
$canAvis = true;
$canAnnuler = ($membre)?$this->isAllowed($membre->getActeur(), AvisSoutenancePrivileges::AVIS_ANNULER):false;
?>

<?php /** Plusieurs thèses ont été trouvées, le rapporteurs doit alors sélectionner celle sur laquelle il veut travailler */ ?>
<?php if (isset($theses)) : ?>
    <h1 class="page-header">
        Index des soutenances / Index of the PhD defense
    </h1>

    <p class="lead">
        Vous êtes actuellement rapporteur de plusieurs thèses en cours.
        Veuillez sélectionner la thèse sur laquelle vous souhaitez intervenir.
    </p>

    <table class="table table-sm">
        <thead>
            <tr>
                <th class="these-titre">    Titre </th>
                <th class="">               Doctorant </th>
                <th class="">               Encadrement </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($theses as $these) : ?>
                <tr>
                    <td>
                        <a  <?php /** @see \Soutenance\Controller\IndexController::indexRapporteurAction()*/ ?>
                            href="<?php echo $this->url('soutenance/index-rapporteur', ['these' => $these->getId()], [], true); ?>">
                            <?php echo $these->getTitre(); ?>
                        </a>
                    </td>
                    <td> <?php echo $these->getDoctorant()->getIndividu(); ?> </td>
                    <td>
                        <?php foreach ($these->getEncadrements() as $encadrement) : ?>
                            <?php if ($encadrement->getRole()->getCode() !== Role::CODE_DIRECTEUR_THESE) echo "<i>"; ?>
                            <?php echo $encadrement->getIndividu() ; ?>
                            <?php if ($encadrement->getRole()->getCode() !== Role::CODE_DIRECTEUR_THESE) echo "</i>"; ?>
                            <br/>
                        <?php endforeach; ?>
                    </td>

                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

<?php else : ?>


<h1 class="page-header">
    Index de la soutenance / Index of the PhD defense
    <small><?php echo $this->partial('these/these/partial/titre') ?></small>
</h1>

<div class="box card">
    <div class="card-header bg-dark text-white">
        <h2> Proposition de jury / Jury Proposal </h2>
    </div>
    <div class="card-body">
        <?php if ($proposition !== null) : ?>
            <h3> Date et lieu </h3>
            <p>La soutenance est prévue pour le <strong><?php echo $proposition->getDate()?->format(Constants::DATETIME_FORMAT); ?></strong>
                dans <strong><?php echo $proposition->getLieu(); ?></strong>.</p>

            <h3> Jury </h3>
            <table class="table table-sm">
                <thead>
                    <tr>
                        <th> Dénomination </th>
                        <th> Qualité </th>
                        <th> Établissement </th>
                        <th> Rôle </th>
                    </tr>
                </thead>
                <tbody>
                    <?php /** @var Membre $jury  */ ?>
                    <?php foreach ($proposition->getMembres() as $jury) : ?>
                        <tr>
                            <td> <?php echo $jury->getDenomination(); ?> </td>
                            <td> <?php echo ($jury->getQualite())?$jury->getQualite()->getLibelle():"Non définie"; ?> </td>
                            <td> <?php echo $jury->getEtablissement(); ?> </td>
                            <td> <?php echo $jury->getRole(); ?> </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php else : ?>
            Aucune proposition de soutenance de trouvée.
        <?php endif; ?>
    </div>
</div>

<div class="box card">
    <div class="card-header <?php echo ($engagement !== null)?"bg-dark":"bg-warning"; ?> text-white">
        <h2> Engagement d'impartialité / Impartiality Commitement </h2>
    </div>
    <div class="card-body">
        <?php if ($engagement !== null) : ?>
            Vous avez signé l'engagement pour la thèse de <?php echo $these->getDoctorant(); ?>.
            <div class="card float-end">
                <div class="card-header bg-dark text-white">
                    Signature de l'engagment d'impartialité
                </div>
                <div class="card-body">
                    <ul>
                        <li><?php echo $engagement->getIndividu(); ?></li>
                        <li><?php echo $engagement->getHistoCreation()->format(Constants::DATETIME_FORMAT); ?></li>
                    </ul>
                </div>
            </div>
        <?php else : ?>
            <span class="fas fa-exclamation-triangle"></span>
            Pour être enregistré comme rapporteur de thèse, vous devez signer l'engagement d'impartialité. <br/>
            To be registered as external referee you must sign the impartiality commitment

            <?php if ($membre) : ?>
            <a
                    <?php /** @see \Soutenance\Controller\EngagementImpartialiteController::engagementImpartialiteAction() */?>
                    href="<?php echo $this->url('soutenance/engagement-impartialite', ['these' => $these->getId(), 'membre' => $membre->getId()], [], true); ?>"
               class="btn btn-primary float-end"
            >
                <span class="icon icon-edit"></span>
<!--                Signer / Sign-->
                Accès à l'engagement d'impartialité / Access to the impartiality commitment
            </a>
            <?php endif; ?>

        <?php endif; ?>
    </div>
</div>

<div class="box card">
    <div class="card-header <?php echo ($depot !== null)?"bg-dark":"bg-warning"; ?>">
        <h2> Téléchargement de la thèse / Downloading the manuscrit </h2>
    </div>
    <div class="card-body">
        <?php if ($engagement === null) : ?>
            <span class="fas fa-exclamation-triangle"></span> Vous ne pourrez télécharger la version électronique de la thèse qu'après avoir signé l'engagement d'impartialité.
        <?php else : ?>
            <?php if ($depot !== null) : ?>
                Vous pouvez télécharger la version électronique de la thèse via <?php echo $this->appInfos()->nom; ?>.

                <a
                    <?php /** @see \These\Controller\TheseController::fusionAction() */ ?>
                    href="<?php echo $this->url("these/fusion", ["these" => $these->getId()], [], true); ?>"
                   class="btn btn-primary float-end"
                >
                    <span class="icon icon-download"></span>
                    Télécharger la thèse / Downloading manuscrit
                </a>
            <?php else : ?>
                <span class="fas fa-exclamation-triangle"></span>
                La thèse de <?php echo $these->getDoctorant()->getIndividu(); ?> n'a pas encore été déposée dans <?php echo $this->appInfos()->nom; ?>.
                Une fois le dépôt réalisé vous pourrez télécharger celle-ci via cette page.
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>

<div class="box card">
    <div class="card-header <?php echo ($engagement !== null)?"bg-dark":"bg-warning"; ?>">
        <h2> Avis de soutenance / Notification on the PhD defense </h2>
    </div>
    <div class="card-body">
    <?php if ($engagement !== null) : ?>
            <?php if ($avis !== null) : ?>
                Vous avez rendu votre avis de soutenance pour la thèse de <?php echo $these->getDoctorant()->getIndividu(); ?>.

            <div>
                <div class="col-md-5 float-end">
                    <div class="card">
                        <div class="card-header <?php echo ($avis->getAvis() === 'Favorable')?"bg-success":"bg-danger"; ?>">
                            Avis de soutenance : <strong><?php echo $avis->getAvis(); ?></strong>
                        </div>
                        <div class="card-body">
                            <ul>
                                <li>Rendu le <?php echo $avis->getValidation()->getHistoModification()->format(Constants::DATETIME_FORMAT); ?> par <?php echo $avis->getValidation()->getIndividu(); ?></li>
                            </ul>

                            <dl>
                                <?php if ($avis->getAvis() !== 'Favorable') : ?>
                                    <dt> Motif de refus </dt>
                                    <dd> <?php echo $avis->getMotif(); ?> </dd>
                                <?php endif; ?>
                            </dl>

<!--                            <a href=" --><?php //echo $this->urlFichierThese->telechargerFichierThese($these, $avis->getFichier()); ?><!--" >-->
                            <a
                                <?php /** @see TELECHARGEMENT FICHIER */ ?>
                                href=" <?php echo $telecharger; ?>" >
                                Prérapport de soutenance
                            </a>
                        </div>
                    </div>

                    <a
                        <?php /** @see \Soutenance\Controller\AvisController::annulerAction() */ ?>
                        href="<?php echo $this->url('soutenance/avis-soutenance/annuler', ['these' => $these->getId(), 'rapporteur' => $membre->getId()], [] , true); ?>"
                        class="btn btn-danger" style="margin-top: 1rem;">
                        <span class="icon icon-delete"></span>
                        Annuler l'avis de soutance
                    </a>
                    </div>
                </div>
            </div>
            <?php else : ?>
                <p>
                    Afin de valider la soutenance de thèse de <?php echo $these->getDoctorant()->getIndividu(); ?>, vous devez rendre votre
                    avis de soutenance et votre prérapport de soutenance.
                </p>
                <p>
                    <span <?php if ((new DateTime()) > $proposition->getRenduRapport()) echo 'style="color:darkred;"'; ?> >
                        <span class="icon icon-attention"></span>
                        Attention, la date limite de rendu des pré-rapports est le <strong><?php echo $proposition->getRenduRapport()->format('d/m/Y'); ?></strong>.
                    </span>
                </p>
            <?php if ($canAnnuler) : ?>
            <div>
                <a
                    <?php /** @see \Soutenance\Controller\AvisController::indexAction() */ ?>
                    href="<?php echo $this->url('soutenance/avis-soutenance', ['these' => $these->getId(), 'rapporteur' => $membre->getId()], [], true); ?>"
                   class="btn btn-primary float-end"
                >
                    <span class="icon icon-edit"></span>
                    Rendre l'avis de soutenance / Give our report
                </a>
            </div>
            <?php endif; ?>

            <?php endif; ?>
        <?php else : ?>
        <span class="fas fa-exclamation-triangle"></span> Pour pouvoir rendre votre avis de soutenance vous devez avoir signez l'engagement d'impartialité.
        <?php endif; ?>
    </div>
</div>

<?php endif; ?>