<h1 class="page-header">
    Index du module de soutenance
</h1>

<p class="lead">
    Le rôle que vous avez sélectionné ne peut pas intervenir dans le module de soutenance.
</p>

<p>
    Les rôles pouvant intervenir sont :
</p>
<ul>
    <li> <strong>les acteurs directs de la thèses</strong> : doctorant, directeur et co-directeurs ; </li>
    <li> <strong>les intervenant des structures associées</strong> : écoles doctorales, maison du doctorat et unités de recherche ; </li>
    <li> <strong>les rapporteurs de la thèses </strong>.</li>
</ul>