<?php

/**
 * @see \Soutenance\Controller\IndexController::indexAction()
 */


?>

<h1 class="page-header">
    Index du module de soutenance
</h1>

<p class="lead">
    Le rôle que vous avez sélectionné ne peut pas intervenir dans le module de soutenance.
</p>

<p>
    Les rôles pouvant intervenir sont :
</p>
<ul>
    <li> <strong>les acteurs directs de la thèse</strong> : doctorant, directeur et co-directeurs ; </li>
    <li> <strong>les intervenants des structures associées</strong> : écoles doctorales, maison du doctorat et unités de recherche ; </li>
    <li> <strong>les rapporteurs de la thèse </strong>.</li>
</ul>