<?php
/**
 * @var \Soutenance\Entity\Proposition $proposition
 * @var \Application\Entity\Db\These $these
 */
?>

<div class="panel <?php echo ($proposition->hasDateEtLieu())?'panel-success':'panel-danger'; ?>">

    <div class="panel-heading">
        <h4>
            Date/Heure et lieu de la soutenance
        </h4>
    </div>

    <div class="panel-body">

        <div class="row">
            <div class="col-md-8">
                <dl>
                    <dt> Date de la soutenance </dt>
                    <dd> <?php echo ($proposition->getDate())?$proposition->getDate()->format("d/m/Y"):'<strong>non communiquée</strong>'; ?> </dd>
                    <dt> Heure de la soutenance </dt>
                    <dd> <?php echo ($proposition->getDate())?$proposition->getDate()->format("H:i"):'<strong>non communiquée</strong>'; ?> </dd>
                    <dt> Lieu de la Soutenance </dt>
                    <dd>
                        <?php echo ($proposition->getLieu())?$proposition->getLieu():'<strong>non communiqué</strong>'; ?>
                        <?php echo ($proposition->isExterieur())?" (extérieur)":""; ?>
                    </dd>
                </dl>
            </div>

            <div class="col-md-4">
                <div class="pull-right">
                    <?php if ($canModifier) : ?>
                    <a
                        href="<?php echo $this->url('soutenance/proposition/modifier-date-lieu', ['these' => $these->getId()], [], true); ?>"
                        class="btn btn-primary action ajax-modal"
                        data-event="edition-datelieu"
                    >
                        <span class="glyphicon glyphicon-pencil"></span> Éditer lieu et date de la soutenance
                    </a>


                <?php endif; ?>

                </div>

                <br/>
                <br/>
                <br/>

                <?php if ($proposition->isExterieur()) : ?>
                    <div class="alert alert-sm alert-warning">
                        <span class="glyphicon glyphicon-warning-sign"> </span>
                        Si la soutenance ne se déroule pas dans les locaux de l'établissement d'inscription il est nécessaire de signer une demande de délocalisation :
                        <a href="https://localhost/informations/fichiers/telecharger/283">formulaire de demande de délocalisation</a>.
                    </div>
                <?php endif; ?>
            </div>

        </div>
    </div>

</div>
