<?php

namespace Formation\Provider\Template;

class MailTemplates {

    const INSCRIPTION_ENREGISTREE = "FORMATION_INSCRIPTION_ENREGISTREE";
    const INSCRIPTION_LISTE_PRINCIPALE = "FORMATION_INSCRIPTION_LISTE_PRINCIPALE";

}