<?php

namespace Formation\Provider\Template;

class MailTemplates
{

    const INSCRIPTION_ENREGISTREE = "FORMATION_INSCRIPTION_ENREGISTREE";
    const INSCRIPTION_LISTE_PRINCIPALE = "FORMATION_INSCRIPTION_LISTE_PRINCIPALE";
    const INSCRIPTION_LISTE_COMPLEMENTAIRE = "FORMATION_INSCRIPTION_LISTE_COMPLEMENTAIRE";
    const INSCRIPTION_CLOSE = "FORMATION_INSCRIPTION_CLOSE";
    const INSCRIPTION_ECHEC = "FORMATION_INSCRIPTION_ECHEC";

    const SESSION_IMMINENTE = "FORMATION_SESSION_IMMINENTE";
    const SESSION_IMMINENTE_FORMATEUR = "FORMATION_SESSION_IMMINENTE_FORMATEUR";
    const SESSION_TERMINEE = "FORMATION_SESSION_TERMINEE";
    const SESSION_ANNULEE = "FORMATION_SESSION_ANNULEE";

    const FORMATION_SPECIFIQUE_AJOUTEE = "FORMATION_FORMATION_SPECIFIQUE_OUVERTE";

}