<?php
/**
 * @var PropositionThese $proposition
 * @var string $FORMULAIRE_DEMANDE_LABEL
 * @var string $FORMULAIRE_DEMANDE_ANGLAIS
 * @var string $FORMULAIRE_DEMANDE_CONFIDENTIALITE
 * @var bool $canModifier
 * @var string $typeProposition
 */

use Soutenance\Entity\PropositionThese;
use Soutenance\Service\Horodatage\HorodatageService;


$these = $proposition->getThese();
?>

<div id="BOXDIV_INFORMATIONS_THESE">
    <div class="box card">
        <div class="card-header bg-dark text-white">
            <h2>
                Informations sur la thèse et la soutenance
            </h2>
        </div>
        <div class="row card-body">
            <div class="col-md-8">
                <dl>
                    <!-- COTUTELLE -->
                    <?php if ($these->getLibelleEtabCotutelle() || $these->getLibellePaysCotutelle()) : ?>

                        <dt> Établissement de co-tutelle</dt>
                        <dd> <?php echo ($these->getLibelleEtabCotutelle()) ? $these->getLibelleEtabCotutelle() : "non renseigné"; ?></dd>
                        <dt> Pays de co-tutelle</dt>
                        <dd> <?php echo ($these->getLibellePaysCotutelle()) ? $these->getLibellePaysCotutelle() : "non renseigné"; ?></dd>
                    <?php else : ?>
                        <dt> Cotutelle</dt>
                        <dd> Pas de cotutuelle.</dd>
                    <?php endif; ?>
                </dl>
            </div>

            <div class="col-md-8">
                <dl>
                    <!-- LABEL -->
                    <dt>Label européen</dt>
                    <dd>
                        <?php echo ($proposition->isLabelEuropeen()) ? "Oui" : "Non"; ?>
                    </dd>

                </dl>
            </div>

            <div class="col-md-4">
                <?php if ($canModifier) : ?>
                    <a <?php /** @see PropositionTheseController::labelEuropeenAction(); */ ?>
                            href="<?php echo $this->url("soutenance_{$typeProposition}/proposition/label-europeen", ['id' => $these->getId()], [], true); ?>"
                            class="btn btn-primary action ajax-modal"
                            data-event="edition-informations-these"
                    >
                        <?php if($proposition->isLabelEuropeen()): ?>
                            <span class="icon icon-minus"></span>
                            Retirer le label européen
                        <?php else: ?>
                            <span class="icon icon-plus"></span>
                            Renseigner un label européen
                        <?php endif; ?>
                    </a>
                <?php endif; ?>

                <?php if ($proposition->isLabelEuropeen()): ?>
                    <div class="alert alert-warning">
                        <span class="fas fa-exclamation-triangle"> </span>
                        Afin de réaliser une demande de label européen, vous devez remplir le formulaire de demande suivant :
                        <a href="<?php echo $FORMULAIRE_DEMANDE_LABEL; ?>">formulaire de demande de label européen</a>.
                    </div>
                <?php endif; ?>
            </div>

            <!-- THESE EN ANGLAIS ----------------------------------------------------------------------------------------->
            <div class="col-md-8">
                <dl>
                    <dt>Thèse en anglais</dt>

                    <?php if (/*$proposition->isManuscritAnglais() ||*/
                    $proposition->isSoutenanceAnglais()) : ?>
                        <!--                    --><?php //if ($proposition->isManuscritAnglais()) : ?>
                        <!--                        <dd>-->
                        <!--                            Manuscrit en anglais-->
                        <!--                        </dd>-->
                        <!--                    --><?php //endif; ?>
                        <?php if ($proposition->isSoutenanceAnglais()) : ?>
                            <dd>
                                Soutenance en anglais
                            </dd>
                        <?php endif; ?>
                    <?php else : ?>
                        <dd> Non</dd>
                    <?php endif; ?>

                </dl>
            </div>

            <div class="col-md-4">
                <?php if ($canModifier) : ?>
                    <a  <?php /** @see PropositionController::anglaisAction() */ ?>
                            href="<?php echo $this->url("soutenance_{$typeProposition}/proposition/anglais", ['id' => $these->getId()], [], true); ?>"
                            class="btn btn-primary action ajax-modal"
                            data-event="edition-informations-these"
                    >
                        <?php if ($proposition->isSoutenanceAnglais()) : ?>
                            <span class="icon icon-minus"></span>
                        <?php else: ?>
                            <span class="icon icon-plus"></span>
                        <?php endif; ?>
                        Renseigner thèse en anglais
                    </a>
                <?php endif; ?>

                <!--            --><?php //if($proposition->isManuscritAnglais() || $proposition->isSoutenanceAnglais()): ?>
                <!--                <div class="alert alert-warning">-->
                <!--                    <span class="icon icon-warning"> </span>-->
                <!--                    Afin de réaliser la demande de rédaction ou de soutenance en anglais vous devez motiver votre demande via la demande suivante :-->
                <!--                    <a href="-->
                <?php //echo $FORMULAIRE_DEMANDE_ANGLAIS; ?><!--">demande de redaction ou de soutenance en anglais</a>.-->
                <!--                </div>-->
                <!--            --><?php //endif; ?>
            </div>

            <div class="col-md-8">
                <dl>
                    <dt> Confidentialité de la thèse</dt>
                    <?php if ($these->getDateFinConfidentialite() !== null): ?>
                        Thèse confidentielle jusqu'au <?php echo $these->getDateFinConfidentialite()->format('d/m/Y'); ?>
                        <?php if ($proposition->isHuitClos()): ?>
                            <dd> Soutenance en huis clos</dd>
                        <?php endif; ?>
                    <?php else: ?>
                        <?php if ($proposition->getConfidentialite()): ?>
                            <dd> Date de fin de confidentialité
                                : <?php echo $proposition->getConfidentialite()->format("d/m/Y"); ?> </dd>
                            <?php if ($proposition->isHuitClos()): ?>
                                <dd> Soutenance en huis clos</dd>
                            <?php endif; ?>
                        <?php else : ?>
                            <dd> Thèse non confidentielle</dd>
                        <?php endif; ?>
                    <?php endif; ?>
                </dl>
            </div>

            <div class="col-md-4">
                <?php if ($canModifier) : ?>
                    <a <?php /** @see PropositionController::confidentialiteAction(); */ ?>
                            href="<?php echo $this->url("soutenance_{$typeProposition}/proposition/confidentialite", ['id' => $these->getId()], [], true); ?>"
                            class="btn btn-primary action ajax-modal"
                            data-event="edition-informations-these"
                    >
                        <span class="icon icon-plus"></span>
                        Renseigner un huis clos et/ou une confidentialité
                    </a>
                <?php endif; ?>

                <?php if ($proposition->getConfidentialite()): ?>
                    <div class="alert alert-warning">
                        <span class="fas fa-exclamation-triangle"> </span>
                        Afin de réaliser une demande de confidentialité, un accord doit au préalable être rempli :
                        <a href="<?php echo $FORMULAIRE_DEMANDE_CONFIDENTIALITE; ?>">demande d'accord de confidentialité</a>.
                    </div>
                <?php endif; ?>
            </div>

            <div class="col-md-8">
                <dl>
                    <dt> Titre de la thèse</dt>
                    <dd> <?php echo ($proposition->getNouveauTitre()) ?: $these->getTitre(); ?> </dd>
                </dl>
            </div>

            <div class="col-md-4">
                <?php if ($canModifier) : ?>
                    <a <?php /** @see PropositionTheseController::changementTitreAction(); */ ?>
                            href="<?php echo $this->url("soutenance_{$typeProposition}/proposition/changement-titre", ['id' => $these->getId()], [], true); ?>"
                            class="btn btn-primary action ajax-modal"
                            data-event="edition-informations-these"
                    >
                        <span class="icon icon-modifier"></span>
                        Modifier le titre de la thèse
                    </a>
                <?php endif; ?>
            </div>
        </div>
        <?php echo $this->horodatagesParType($proposition, HorodatageService::TYPE_MODIFICATION, "Informations complémentaires"); ?>
    </div>
</div>