<?php
/**
 * @var \Structure\Entity\Db\EcoleDoctorale $entity
 * @var bool $includeGotoDetailsLink
 */
?>

<h3>
    Informations générales
</h3>
<dl>
    <dt> Libelle :</dt>
    <dd>    <?php echo $entity->getStructure()->getLibelle(); ?>     </dd>
    <dt> Code :</dt>
    <dd>    <?php echo $entity->getStructure()->getCode(); ?>        </dd>
    <dt> Sigle :</dt>
    <dd>    <?php echo $entity->getStructure()->getSigle(); ?>       </dd>
    <dt> Thème :</dt>
    <dd> <?php echo ($entity->getTheme()) ?: "(Non renseigné)"; ?></dd>
    <dt> Lien vers l'offre des thèses :</dt>
    <dd>
        <?php if ($entity->getOffreThese()) : ?>
            <a href="<?php echo $entity->getOffreThese(); ?>"><?php echo $entity->getOffreThese(); ?></a>
        <?php else: ?>
            (Non renseigné)
        <?php endif; ?>
    </dd>
    <dt> Statut :</dt>
    <dd>
        <?php if ($entity->getStructure()->estFermee()) : ?>
            <span class="badge bg-danger">Structure fermée</span>
        <?php else : ?>
            <span class="badge bg-success">Structure ouverte</span>
        <?php endif; ?>
    </dd>
</dl>

<h3>
    Informations techniques
</h3>
<dl>
    <dt>Id interne :</dt>
    <dd><?php echo $entity->getId(); ?></dd>
    <dt>IdRef :</dt>
    <dd>
        <?php if ($entity->getStructure()->getIdRef() !== null and trim($entity->getStructure()->getIdRef()) !== "") : ?>
            <?php echo $this->idrefLink($entity->getStructure()->getIdRef()); ?>
        <?php else : ?>
            (Non renseigné)
        <?php endif; ?>
    </dd>
    <dt> Id HAL :</dt>
    <dd>
        <?php if ($entity->getStructure()->getIdHal() !== null and trim($entity->getStructure()->getIdHal()) !== "") : ?>
            <?php echo $entity->getStructure()->getIdHal(); ?>
        <?php else : ?>
            (Non renseigné)
        <?php endif; ?>
    </dd>
</dl>

<?php if ($entity->estHistorise()): ?>
    <h3 class="text-danger">
        Historisé
    </h3>
    <dl class="text-danger">
        <dt>Date :</dt>
        <dd><?php echo $entity->getHistoDestruction()->format('d/m/Y à H:i:s') ?></dd>
    </dl>
<?php endif ?>

<?php if ($includeGotoDetailsLink ?? false): ?>
    <a href="<?php echo $this->url('ecole-doctorale/voir', ['ecole-doctorale' => $entity->getId()], [], true); ?>"
       class="action btn btn-outline-secondary"><span class="icon icon-voir"></span> Voir la fiche détaillée de cette école doctorale
    </a>
<?php endif ?>