<?php

use Soutenance\Entity\Etat;

/**
 * @see \Soutenance\View\Helper\EtatViewHelper
 * @var Etat|null $etat
 * @var array $options
 */

switch ($etat->getCode()){
    case Etat::EN_COURS_EXAMEN :
    case Etat::EN_COURS_SAISIE :
    case Etat::COMPLET :
        $iconEtat = "hourglass";
        break;
    case Etat::REJETEE :
        $iconEtat = "ko";
        break;
    case Etat::VALIDEE :
        $iconEtat = "ok";
        break;
    case Etat::ETABLISSEMENT :
        $iconEtat = "checked";
        break;
    default:
        $iconEtat = "";
}
?>

<?php if ($etat === null) : ?>

        Pas d'état

<?php else : ?>
        <div class="row informations-compl-these-div">
            <div class="col-md-6 informations-compl-these-card information-etat-these-card <?=$etat->getCode()?>-etat-these-card"
                 data-bs-toggle="tooltip" data-bs-original-title="État de la proposition">
                <span class="icon icon-<?=$iconEtat?>"></span>
                <h2><?= $etat->getLibelle(); ?></h2>
            </div>
        </div>
<?php endif; ?>


<style>
    div.information-etat-these-card.<?php echo Etat::VALIDEE; ?>-etat-these-card {
        color: darkgreen;
        border-left: 5px solid darkgreen;
        min-width: 09%;
    }
    div.information-etat-these-card.<?php echo Etat::REJETEE; ?>-etat-these-card {
        color: darkred;
        border-left: 5px solid darkred;
        min-width: 09%;
    }
    div.information-etat-these-card.<?php echo Etat::EN_COURS_EXAMEN; ?>-etat-these-card,
    div.information-etat-these-card.<?php echo Etat::EN_COURS_SAISIE; ?>-etat-these-card{
        color: darkorange;
        border-left: 5px solid darkorange;
        min-width: 09%;
    }
    div.information-etat-these-card.<?php echo Etat::ETABLISSEMENT; ?>-etat-these-card {
        color: teal;
        border-left: 5px solid teal;
        min-width: 09%;
    }
    div.information-etat-these-card.<?php echo Etat::COMPLET; ?>-etat-these-card {
        color: dodgerblue;
        border-left: 5px solid dodgerblue;
        min-width: 09%;
    }
</style>

