<?php

/**
 * @see \Soutenance\View\Helper\JustificatifViewHelper
 * @var Justificatif $justificatif
 * @var UrlFichierThese $urlFichierThese
 * @var array $options
 */

use Depot\Controller\Plugin\UrlFichierThese;
use Fichier\Entity\Db\NatureFichier;
use Soutenance\Entity\Justificatif;

$these = $justificatif->getProposition()->getThese();
$fichierThese = $justificatif->getFichier();
$fichier = $justificatif->getFichier()->getFichier();
$membre = $justificatif->getMembre();

?>

<?php
    $label = "";
    if (isset($options['court']) && $options['court'] === true) {
        $label = "Justificatif ";
    } else {
        $label = $fichier->getNature()->getLibelle();
    }
    if($membre !== null) {
        $label .= " pour ";
        $label .= "<strong>";
        $label .= "<span class='icon icon-user'></span>";
        $label .= $membre->getDenomination();
        $label .= "</strong>";
    }
    if ($justificatif->getFichier()->getFichier()->getNature()->getCode() === NatureFichier::CODE_AUTRES_JUSTIFICATIFS) {
        $label .= "'".$justificatif->getFichier()->getFichier()->getNomOriginal()."'";
    }
?>

<a href="<?php echo $urlFichierThese->telechargerFichierThese($these, $fichierThese); ?>">
    <?php echo $label; ?>
</a>
    (<?php echo $fichier->getHistoCreateur()->getDisplayName(); ?> - <?php echo $fichier->getHistoCreation()->format("d/m/Y à H:i"); ?>)

