<?php

namespace Admission\Hydrator;

use Admission\Entity\Db\Etudiant;
use Admission\Entity\Db\Individu;
use Application\Entity\Db\Pays;
use Doctrine\Laminas\Hydrator\DoctrineObject;

/**
 * @author Unicaen
 */
class EtudiantHydrator extends DoctrineObject
{
    public function extract(object $object): array
    {
        /** @var Etudiant $object */
        $data = parent::extract($object);

        if (array_key_exists($key = 'paysNaissance', $data) && $data[$key] instanceof Pays) {
            $data[$key] = array("id" => $object->getPaysNaissance()->getId(), "label" => $object->getPaysNaissance()->getLibelle());
        }else{
            $data['paysNaissance'] = array("id" => null, "label" => null);
        }

        if (array_key_exists($key = 'nationalite', $data) && $data[$key] instanceof Pays) {
            $data[$key] = array("id" => $object->getNationalite()->getId(), "label" => $object->getNationalite()->getLibelle());
        }else{
            $data['nationalite'] = array("id" => null, "label" => null);
        }

        $data['verificationEtudiant'] = $object->getVerificationEtudiant()->first() ?: null;

        return $data;
    }

    public function hydrate(array $data, object $object): object
    {
//        var_dump($data);
        $data["paysNaissance"] = empty($data["paysNaissance"]["id"]) ? null : $data["paysNaissance"]["id"];
        $data["nationalite"] = empty($data["nationalite"]["id"]) ? null : $data["nationalite"]["id"];
        $data["adresseCodePostal"] = empty($data["adresseCodePostal"]) ? null : $data["adresseCodePostal"];

        //Si la case niveauEtude n'est pas le diplôme national, on met à null les valeurs des champs reliés
        if(isset($data["niveauEtude"]) && $data["niveauEtude"] != 1){
            $data["intituleDuDiplomeNational"] = null;
            $data["anneeDobtentionDiplomeNational"] = null;
            $data["etablissementDobtentionDiplomeNational"] = null;
        }

        //Si la case niveauEtude n'est pas la case Autre, on met à null les valeurs des champs reliés
        if(isset($data["niveauEtude"]) && $data["niveauEtude"] != 2){
            $data["typeDiplomeAutre"] = null;
            $data["intituleDuDiplomeAutre"] = null;
            $data["anneeDobtentionDiplomeAutre"] = null;
            $data["etablissementDobtentionDiplomeAutre"] = null;
        }

        if (isset($data['verificationEtudiant']) && !is_array($data['verificationEtudiant'])) {
            $data['verificationEtudiant'] = [$data['verificationEtudiant']];
        }


//        var_dump($data);

        return parent::hydrate($data, $object); // TODO: Change the autogenerated stub
    }

}