<?php

namespace Admission\Hydrator;

use Application\Entity\Db\Pays;
use Doctrine\Laminas\Hydrator\DoctrineObject;

/**
 * @author Unicaen
 */
class IndividuHydrator extends DoctrineObject
{
    public function extract(object $object): array
    {
        $data = parent::extract($object);

        if (array_key_exists($key = 'paysNaissance', $data) && $data[$key] instanceof Pays) {
            $data[$key] = $data[$key]->getId();
        }

        return $data;
    }

    public function hydrate(array $data, object $object): object
    {
        $data["paysNaissance"] = empty($data["paysNaissance"]["id"]) ? null : $data["paysNaissance"]["id"];
        $data["nationalite"] = empty($data["nationalite"]["id"]) ? null : $data["nationalite"]["id"];
        $data["adresseCodePostal"] = empty($data["adresseCodePostal"]) ? null : $data["adresseCodePostal"];

        return parent::hydrate($data, $object); // TODO: Change the autogenerated stub
    }

}