<?php

namespace Admission\Hydrator;

use Doctrine\Laminas\Hydrator\DoctrineObject;
use Structure\Entity\Db\EcoleDoctorale;
use Structure\Entity\Db\Structure;
use Structure\Entity\Db\UniteRecherche;

/**
 * @author Unicaen
 */
class InscriptionHydrator extends DoctrineObject
{
    public function extract(object $object): array
    {
        return parent::extract($object); // TODO: Change the autogenerated stub
    }

    public function hydrate(array $data, object $object): object
    {
        $data["composanteDoctorat"] = empty($data["composanteDoctorat"]["id"]) ? null : $data["composanteDoctorat"]["id"];
        $data["nomCodirecteurThese"] = empty($data["nomCodirecteurThese"]["id"]) ? null : $data["nomCodirecteurThese"]["id"];
        $data["nomDirecteurThese"] = empty($data["nomDirecteurThese"]["id"]) ? null : $data["nomDirecteurThese"]["id"];
        $data["paysCoTutelle"] = empty($data["paysCoTutelle"]["id"]) ? null : $data["paysCoTutelle"]["id"];

        return parent::hydrate($data, $object);
    }

}