<?php
/**
 * @var array $operations
 * @var Individu $individu
 * @var string $returnUrl
 */

use Admission\Entity\Db\TypeValidation;
use Individu\Entity\Db\Individu;

?>
<div class="row">
    <div class="col-lg-7 col-sm-12">
        <?php
        $count = 1;
        $dossier_complet = false;
        $conditionPassed = false;
        $validation_en_attente = null;
        foreach ($operations as $i => $operation):
            $dossier_complet = ($i == TypeValidation::CODE_VALIDATION_GESTIONNAIRE && $operation->getId()) ? true : $dossier_complet;
            if ($operation->getId() == null && !$conditionPassed) {
                $validation_en_attente = ($i !== TypeValidation::CODE_ATTESTATION_HONNEUR) ? $operation->getTypeToString() : null;
                $conditionPassed = true;
            }
            echo $this->partial('admission/admission/partial/validation/operation-card', [
                'operation' => $operation,
                'count' => $count,
                'individu' => $individu,
                'validation_en_attente' => $validation_en_attente,
                'returnUrl' => $returnUrl
            ]);
            $count += 1;
        endforeach;
        ?>
    </div>
    <div class="col-lg-5 col-sm-12 cardsValidation">
        <?php if ($dossier_complet) { ?>
            <div class="card border-success mb-3 dossier_complet">
                <div class="card-body text-success">
                    <i class="icon icon-information"></i>
                    <p class="card-title">Votre dossier est complet</p>
                </div>
            </div>
        <?php }
        if ($validation_en_attente) { ?>
            <div class="card mb-3 dossier_incomplet">
                <div class="card-body text-warning">
                    <i class="icon icon-information"></i>
                    <p class="card-title">En attente de la <?= strtolower($validation_en_attente); ?></p>
                </div>
            </div>
        <?php } ?>
    </div>
</div>