<?php

use Admission\Entity\Db\AdmissionOperationInterface;
use Admission\Entity\Db\AdmissionValidation;
use Admission\Entity\Db\TypeValidation;
use Admission\Provider\Privilege\AdmissionPrivileges;

/**
 * @var int $count
 * @var AdmissionValidation $operation
 * @var AdmissionOperationInterface $operationEnAttente
 * @var string $returnUrl
 * @var string $libelleOperation
 * @var bool $showRangOperation
 * @var boolean $showActionButtons
 * @var boolean $isOperationAllowedByRole
 */

$canValiderOperation =
    $this->isAllowed($operation, AdmissionPrivileges::ADMISSION_VALIDER_SIEN) ||
    $this->isAllowed($operation, AdmissionPrivileges::ADMISSION_VALIDER_TOUT);

$admission = $operation->getAdmission();
$canAjouterDonneesExport = $this->isAllowed($admission, AdmissionPrivileges::ADMISSION_AJOUTER_DONNEES_EXPORT);
?>
<div class="row subfield">
    <div class="col etape-signature-infos-container">
        <?php
        if ($showRangOperation):
            if ($operationEnAttente && $operationEnAttente->getTypeToString() === $operation->getTypeToString()): ?>
                <div class="col-lg-2 circle-etape etape-signature-infos-container">
                    <span class="icon icon-hourglass operation-waiting"></span>
                </div>
            <?php else: ?>
                <div class="rang-operation-container"><p><?= $count ?></p></div>
            <?php endif;
        endif; ?>

        <div class="col-lg-6 libelle-etape-container etape-signature-infos-container">
            <label><?php echo $libelleOperation ?: $operation->getTypeValidation()->getLibelle(); ?></label>
            <?php
            if($isOperationAllowedByRole):
                //Si l'attestation sur l'honneur ne peut-être effectuée, on affiche ce message
                if (!$canValiderOperation && $operation->getTypeValidation()->getCode() === TypeValidation::CODE_ATTESTATION_HONNEUR):
                    echo '<span class="icon icon-warning dossier-incomplet-validation-impossible" data-toggle="tooltip">
                            <span class="tooltip-text">La charte doctorale (présente dans les pièces justificatives) doit avoir été lue pour pouvoir attester sur l\'honneur</span>
                         </span>';
                    //Si l'attestation sur l'honneur peut-être effectuée mais qu'elle n'a pas été faîte, on affiche ce message
                elseif($canValiderOperation && $operation->getId() === null && $operation->getTypeValidation()->getCode() === TypeValidation::CODE_ATTESTATION_HONNEUR):
                    echo '<span class="icon icon-information dossier-incomplet-validation-impossible" data-toggle="tooltip">
                            <span class="tooltip-text">Suite à cette validation, le gestionnaire de ce dossier recevra un mail et vérifiera l\'exactitude des informations renseignées.<br> Ensuite, il validera ou non la conformité des données</span>
                         </span>';
                endif;
                //Si la validation par les gestionnaires ne peut-être effectuée, on affiche ce message
                if((!$canValiderOperation && $operationEnAttente instanceof AdmissionValidation && $operationEnAttente->getTypeValidation()->getCode() === TypeValidation::CODE_VALIDATION_GESTIONNAIRE)):
                    //Si le dossier n'est pas complet, on affiche ce message
                    $message = !$admission->isDossierComplet() ? "Chaque partie de ce dossier doit-être notée comme complète<br>afin d'effectuer cette validation<br><br>" : null;

                    $directeur = $admission->getInscription()->first()->getDirecteur();
                    $coDirecteur = !$admission->getInscription()->first()->getCoDirection() || $admission->getInscription()->first()->getCoDirecteur();
                    //Si le directeur/co-directeur de thèse ne sont pas renseigné, on affiche ce message
                    $message .= !$directeur || !$coDirecteur ? "Le directeur de thèse ainsi que le co-directeur (le cas échéant) doivent-être enregistrés en base de données" : null;

                    if($message): ?>
                        <span class='icon icon-warning dossier-incomplet-validation-impossible' data-toggle='tooltip'>
                            <span class='tooltip-text'><?= $message ?></span>
                        </span>
                    <?php endif;
                endif;
            endif; ?>
        </div>

        <?php if ($canValiderOperation && ((isset($showActionButtons) && $showActionButtons))): ?>
           <a class="btn btn-success access_validation_operation" data-operation="ValidationOperation">Valider</a>
            <div class="modal fade" id="modalShowConfirmationValidationOperation" tabindex="-1" role="dialog">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Confirmation de l'opération</h4>
                        </div>
                        <div class="modal-body">
                            <p>Êtes-vous sûr·e de vouloir valider cette opération ?</p>
                            <p>Are you sure to confirm this operation?</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Annuler</button>
                            <a href="
                            <?php echo $this->url('admission/valider', ['admission' => $operation->getAdmission()->getId(),'typeValidation' => $operation->getTypeValidation()->getId()],
                                ['query' => ['redirect' => $returnUrl]]) ?>"
                               class="btn btn-success collapsable-action validation-operation-btn"
                               title="Valider cette étape du dossier d'admission ?">
                                Valider
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <?php if($operation->getTypeValidation()->getCode() === TypeValidation::CODE_VALIDATION_GESTIONNAIRE && $canAjouterDonneesExport): ?>
                <a class="btn btn-primary action ajax-modal" role="button"
                   href="<?php echo $this->url(
                       'admission/ajouter-transmission',
                       ['admission' => $admission->getId()],
                       [])?>" data-event="ajout-export-donnees-pegase"
                   data-bs-toggle="tooltip" data-bs-html="true"
                   title="Dans le cas où vous utilisez Pégase, ces données seront nécessaires pour l'export vers celui-ci">
                    Déclarer le code vœu/période
                </a>
            <?php endif;
        endif; ?>
    </div>
</div>