<?php

use Admission\Entity\Db\AdmissionValidation;
use Admission\Provider\Privilege\AdmissionPrivileges;

/**
 * @var AdmissionValidation $operation
 * @var bool $ajaxModalEvent
 * @var string $returnUrl
 * @var string $libelleOperation
 */

$canSupprimerOperation =
    $this->isAllowed($operation, AdmissionPrivileges::ADMISSION_DEVALIDER_SIEN) ||
    $this->isAllowed($operation, AdmissionPrivileges::ADMISSION_DEVALIDER_TOUT);
?>
<div class="row subfield">
    <div class="col-lg-2 circle_etape etape_signature">
        <span class="icon icon-checked circle_icon-ok"></span>
    </div>
    <div class="col-lg-6 libelle_etape etape_signature">
        <label><?php echo $libelleOperation ?: $operation->getTypeValidation()->getLibelle(); ?></label>
    </div>
    <div class="col-lg-2 text-sm text-muted info_validation etape_signature">
        <p>
            Par <?php echo $operation->getHistoModificateur() ?: $operation->getHistoCreateur() ?>,
            le <?php echo ($operation->getHistoModification() ?: $operation->getHistoCreation())->format(\Application\Constants::DATETIME_FORMAT) ?>
        </p>
    </div>
    <?php
    if ($canSupprimerOperation && ((isset($showActionButtons) && $showActionButtons))) { ?>
        <div class="col-lg-2 bouton_etape_validation">
            <a href="<?php echo $this->url('admission/devalider', [
                'admissionValidation' => $operation->getId(),
                'typeValidation' => $operation->getTypeValidation()->getId(),
            ], [
                'query' => ['redirect' => $returnUrl],
            ]) ?>"
               class="btn btn-danger collapsable-action"
               title="Dévalider cette étape du dossier d'admission ?"
               data-toggle="confirmationx"
               data-message="Êtes-vous sûr·e de vouloir dévalider ?">Dévalider</span></a>
        </div>
    <?php } ?>
</div>