<?php

namespace Application;

use Laminas\Paginator\Paginator as LaminasPaginator;
use StepStar\Provider\StepStarPrivileges;

/**
 * @var string $title
 * @var LaminasPaginator $paginator
 * @var string $routeName
 *
 * @var string $returnUrl
 *
 * @see \StepStar\Controller\Log\LogRechercheController::indexAction()
 */

$this->headTitle("Logs");
?>

<h1 class="page-header">Module STEP-STAR</h1>

<h2>Logs</h2>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace(); ?>

<!-- Formulaire de filtrage -->
<div class="float-start">
    <?php $loadFiltersUrl = $this->url('step-star/log/filters', [], ['query' => $this->queryParams()], true); ?>
    <div id="filters" data-url="<?php echo $loadFiltersUrl ?>" style="min-height: 160px">
        <!-- Contenu chargé en AJAX -->
    </div>
</div>
<div class="clearfix"></div>


<?php if (count($paginator) > 0): ?>

    <p>
        <?php
        echo $paginator->getTotalItemCount();
        echo " ";
        echo $this->translate("log(s) trouvé(s).");
        ?>
    </p>

    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Début
            </th>
            <th>
                Durée
            </th>
            <th>
                Succès?
            </th>
            <th>
                Opération
            </th>
            <th>
                Thèse
            </th>
            <th>
                Log
            </th>
            <th class="action">
                Action
            </th>
        </tr>
        </thead>

        <tbody>
        <?php /** @var \StepStar\Entity\Db\Log $log */
        foreach ($paginator as $log): ?>
                    <tr>
                        <?php
                        $these = $log->getThese();
        //                $canList =
        //                    $this->isAllowed(RapportActivitePrivileges::getResourceId(RapportActivitePrivileges::RAPPORT_ACTIVITE_LISTER_TOUT)) ||
        //                    $this->isAllowed(RapportActivitePrivileges::getResourceId(RapportActivitePrivileges::RAPPORT_ACTIVITE_SUPPRIMER_SIEN));
                        ?>

                        <td>
                            <?php if ($this->isAllowed(StepStarPrivileges::getResourceId(StepStarPrivileges::LOG_CONSULTER))): ?>
                                <a href="<?php echo $this->url('step-star/log/consulter', ['log' => $log->getId()]) ?>"
                                   title="Voir les détails de ce log"><?php echo $log->getId() ?></a>
                            <?php else: ?>
                                <?php echo $log->getId() ?>
                            <?php endif ?>
                        </td>

                        <td>
                            <?php echo $log->getStartedOnToString() ?>
                        </td>

                        <td>
                            <?php echo $log->getDurationToString() ?>
                        </td>

                        <td>
                            <?php if ($log->isSuccess()): ?>
                                <span class="icon iconly icon-success text-success"></span>
                            <?php else: ?>
                                <span class="icon iconly icon-failure text-danger"></span>
                            <?php endif ?>
                        </td>

                        <td>
                            <?php echo $log->getOperation() ?>
                        </td>

                        <td>
                            <?php if ($theseId = $log->getTheseId()): ?>
                                <a href="<?php echo $this->url('these/identite', ['these' => $theseId]) ?>"
                                   title="Aller à cette thèse">
                                    <?php echo $theseId ?>
                                </a>
                            <?php endif ?>
                        </td>

                        <td class="<?php echo $log->isSuccess() ? '' : 'text-danger' ?>">
                            <?php echo $log->getTruncatedLog() ?>
                        </td>

                        <td class="action">

                        </td>
                    </tr>
                <?php endforeach; ?>
        </tbody>
    </table>


    <?php echo $this->paginationControl($paginator, 'sliding', 'application/paginator.phtml', ['route' => 'step-star/log']) ?>

<?php else: ?>

    <p>Aucun log trouvé.</p>

<?php endif ?>


<script>
    $(function() {
        $("#filters").addClass("loading").refresh(null, function() { $(this).removeClass("loading"); });
    });
</script>