<?php

/** @see \Soutenance\Controller\SimulationController::indexAction()
 *
 * @var These $these
 * @var Acteur[] $acteurs
 **/

use Application\Entity\Db\Acteur;
use Application\Entity\Db\These;

$this->headTitle('Index des acteurs simulés');

?>

<h1 class="page-header">
    Index des acteurs simulés
</h1>

<div class="main">
    <?php if ($these !== null) : ?>
    <div class="panel panel-info">
        <div class="panel-heading">
            Information sur la thèse #<?php echo $these->getId(); ?>
        </div>
        <div class="panel-body">
            <dl class="dl-horizontal">
                <dt> Doctorant </dt>
                <dd> <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?> </dd>
                <dt> Titre </dt>
                <dd> <?php echo $these->getTitre(); ?> </dd>
                <dt> Unité de recherche </dt>
                <dd> <?php echo $these->getUniteRecherche()->getLibelle(); ?></dd>
                <dt> École doctorale </dt>
                <dd> <?php echo $these->getEcoleDoctorale()->getLibelle(); ?></dd>
                <dt> Établissement </dt>
                <dd> <?php echo $these->getEtablissement()->getLibelle(); ?> </dd>

            </dl>
        </div>
    </div>
    <?php endif; ?>

    <div class="row">
        <div class="col-md-8">
            <h2>
                Acteurs enregistrés dans la simulation de S.I.
                <span class="badge">
                    <?php echo count($acteurs) ;?>
                </span>
            </h2>
        </div>
        <div class="pull-right">
            <br/>
            <?php /**  @see \Soutenance\Controller\SimulationController::ajouterActeurSimuleAction(); */ ?>
            <a href="<?php echo $this->url('simulation/ajouter-acteur-simule', ['these' => $these->getId()], [], true); ?>"
               class="btn btn-primary action ajax-modal"
               data-event="modification"
            >
                <span class="glyphicon glyphicon-plus"></span>
                Ajouter un acteur simulé
            </a>
        </div>
    </div>
    <br/>
    <table class="table table-condensed">
        <thead>
            <tr>
                <th> ActeurId </th>
                <th> IndividuId </th>
                <th> TheseId </th>
                <th> Prénom </th>
                <th> Nom </th>
                <th> Mail </th>
                <th> Role </th>
                <th> Qualité </th>
                <th> Établissement </th>
                <th> Action </th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($acteurs as $acteur) : ?>
            <tr>
                <td> <?php echo $acteur->getId(); ?> </td>
                <td> <?php echo $acteur->getIndividu()->getId(); ?> </td>
                <td> <?php echo $acteur->getThese()->getId(); ?> </td>
                <td> <?php echo $acteur->getIndividu()->getPrenom(); ?> </td>
                <td> <?php echo $acteur->getIndividu()->getNomUsuel(); ?> </td>
                <td> <?php echo $acteur->getIndividu()->getEmail(); ?> </td>
                <td> <?php echo $acteur->getRole()->getRoleId(); ?> </td>
                <td> <?php echo ($acteur->getQualite() ? $acteur->getQualite : "Non renseigné"); ?> </td>
                <td> <?php echo ($acteur->getEtablissement() ? $acteur->getEtablissement()->getLibelle() : "Non renseigné"); ?> </td>
                <td>
                    <?php /** @see \Soutenance\Controller\SimulationController::modifierActeurSimuleAction() */ ?>
                    <a href="<?php echo $this->url('simulation/modifier-acteur-simule', ['these' => $these->getId(), 'acteur' => $acteur->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification">
                        <span class="glyphicon glyphicon-pencil" title="Modifier l'acteur"></span></a>
                    <?php /** @see \Soutenance\Controller\SimulationController::supprimerActeurSimuleAction() */ ?>
                    <a href="<?php echo $this->url('simulation/supprimer-acteur-simule', ['these' => $these->getId(), 'acteur' => $acteur->getId()], [], true); ?>">
                        <span class="glyphicon glyphicon-remove" title="Supprimer l'acteur"></span></a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<script>
    $(document).ready(function() {
        //$('select').selectpicker();

        $(function() {
            $("body").on("modification", function (event) {
                event.div.modal('hide');
                window.location.reload();
            });
        });
    });
</script>