<?php

namespace Substitution;

use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var \Doctrine\DBAL\Result $result
 * @var int $count
 *
 * @see \Substitution\Controller\IndexController::individuAction()
 */
?>

<?php echo $this->partial('substitution/doublon/_partial/liste', [
    'type' => 'individu',
    'result' => $result,
    'count' => $count,
    'attributes' => ['nom_patronymique' => 'Nom patronymique', 'prenom1' => 'Prénom 1', 'date_naissance' => 'Date de naissance'],
    'routeName' => 'individu/voir',
    'routeParamName' => 'individu',
]); ?>
