<?php

use Application\Constants;
use These\Entity\Db\These;
use Application\View\Renderer\PhpRenderer;
use Soutenance\Entity\Avis;
use Soutenance\Entity\Proposition;

/**
 * @see \Soutenance\Service\Notification\SoutenanceNotificationFactory::createNotificationAvisDefavorable()
 *
 * @var PhpRenderer $this
 * @var These $these
 * @var Proposition $proposition
 * @var Avis $avis
 * @var string $url
 */

$justification = true;
?>

<p>
    Bonjour,
</p>
<p>
    Le rapporteur <strong><?php echo $avis->getRapporteur()->getIndividu()->getNomComplet(); ?></strong> vient de rendre
    un avis défavorable pour la these de <strong> <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?> </strong>
    intitulée <strong><?php echo $these->getTitre(); ?></strong>.
</p>
<p> Voici le motif donné par le rapporteur : <?php echo $avis->getMotif(); ?></p>
<p>
    Vous pouvez consulter le rapport de présoutenance en utilisant le lien suivant :
</p>
<ul>
    <li>
        <?php echo  $avis->getRapporteur(); ?>
        :

        <?php $url_ = $this->url('fichier/these/telecharger', [
            'these'      => $these->getId(),
            'fichier'    => $avis->getFichier()->getUuid(),
            'fichierNom' => $avis->getFichier()->getNom(),
        ], [
            'force_canonical'=>true
        ],true);
        ?>

        <a href="<?php echo $url_; ?>">
            rapport de pré-soutenance
        </a>
    </li>
</ul>

<?php if ($justification) : ?>
    <p>
        Vous avez reçu ce mail car :
        <ol>
            <li> un avis défavorable a été rendu par un rapporteur ; </li>
            <li> vous êtes soit :
                <ul>
                    <li> un gestionnaire de la maison du doctorat de l'établissement d'inscription du doctorant ; </li>
                    <li> un&middot;e responsable de l'école doctorale gérant la thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?> ; </li>
                    <li> un&middot;e responsable de l'unité de recherche accueillant la thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?> ; </li>
                    <li> le directeur de thèse ou un des codirecteur de la thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?>. </li>
                </ul>
            </li>
        </ol>
    </p>
<?php endif; ?>



