<?php

use Application\Entity\Db\These;
use Application\View\Renderer\PhpRenderer;use Soutenance\Entity\Proposition;

/**
 * @see \Soutenance\Service\Notifier\NotifierSoutenanceService::triggerConnexionRapporteur()
 *
 * @var PhpRenderer $this
 * @var Proposition $proposition
 * @var These $these
 * @var string $username
 * @var string $url
 */

$doctorant = $these->getDoctorant()->getIndividu()->getNomComplet(false, false, false, true, false, true);
$titre = $these->getTitre();

$justification = true;
?>

<p><em>-- Version française----------------------------------------------------</em></p>
<p>
    Bonjour,
</p>
<p>
    Vous venez d'être désigné comme rapporteur pour la thèse de <strong><?php echo $doctorant; ?></strong> intitulée
    <strong><?php echo $titre; ?></strong>. Afin de pouvoir vous connecter à l'application <strong> <?php echo $this->appInfos()->nom; ?> </strong>
    et ainsi pouvoir rendre votre avis de pré-soutenance, vous pouvez utiliser l'adresse suivante : <a href="<?php echo $url; ?>"><?php echo $url;?> </a>.
</p>
<p>
    Vous avez jusqu'au <?php $proposition->getRenduRapport()->format('d/m/Y'); ?> pour effectuer ce dépôt.
</p>
<p>
    Cordialement,
</p>

<p><em>-- English version -----------------------------------------------------</em></p>
<p>
    Dear Mrs/Mr,
</p>
<p>
    You have been appointed as an external referee for the PhD thesis presented by <strong><?php echo $doctorant; ?></strong> entitled
    <strong><?php echo $titre; ?></strong>. In order to have access to the <strong> <?php echo $this->appInfos()->nom; ?> </strong>
    web-based application for submitting your report, you can use the following link : <a href="<?php echo $url; ?>"><?php echo $url;?> </a>.
</p>
<p>
    You have until the <?php $proposition->getRenduRapport()->format('d/m/Y'); ?> to upload your report.
</p>
<p>
    Best regards,
</p>


<?php if ($justification) : ?>
    <p>
        Vous recevez ce mail, car votre rôle dans la soutenance de thèse de <?php echo $doctorant; ?> nécessite un compte <?php echo $this->appInfos()->nom ?>.
    </p>
<?php endif; ?>


