    <?php

use Doctorant\Entity\Db\Doctorant;
use Application\Entity\Db\These;
use Soutenance\Entity\Avis;
use Soutenance\Entity\Proposition;

/**
 * @see \Soutenance\Service\Notifier\NotifierSoutenanceService::triggerEnvoiConvocationDoctorant()
 * @var These $these
 * @var Proposition $proposition
 * @var Doctorant $doctorant
 * @var DateTime $date
 * @var string $url
 * @var array $avisArray $avisArray[Denomination] = lien_de_telechargement
 */

$justification = true;
?>

<p>
Bonjour,
</p>

<p>
Par décision en date du
<?php if ($date): ?>
    <?php echo $date->format('d/m/Y'); ?>,
<?php else: ?>
    <span style='background-color:red;'>
                Date manquante
        </span>
<?php endif; ?>
vous avez été autorisé<?php if($doctorant->getIndividu()->estUneFemme()==="Madame") echo "e"; ?> à présenter en soutenance
vos travaux en vue de l'obtention du diplôme : <br/>
Doctorat en <?php echo $these->getLibelleDiscipline(); ?>.
</p>

<p>
    La soutenance aura lieu le
    <?php if ($proposition->getDate() !== null): ?>
        <?php echo $proposition->getDate()->format('d/m/Y à H:i'); ?>
    <?php else : ?>
        <span style='background-color:red;'>
                Date manquante,
        </span>
    <?php endif; ?> à l'adresse suivante : <br/>
    <?php if ($proposition->getAdresse() !== null): ?>
        <?php echo $proposition->getAdresse(); ?>
    <?php else : ?>
        <span style='background-color:red;'>
                    Adresse manquante
            </span>
        <br/>
    <?php endif; ?>
</p>

<p>
    La soutenance <?php if ($proposition && $proposition->isHuitClos() !== null): ?>
        <?php if ($proposition->isHuitClos()) : ?>
            se déroulera en huis clos.
        <?php else : ?>
            sera publique.
        <?php endif ; ?>
    <?php else: ?>
        <span style='background-color:red;'> information sur l'aspect public manquante </span>
    <?php endif; ?>
</p>

<p>
    Vous pouvez accéder aux rapports de présoutenance grâce aux liens suivants :
<ul>
    <?php /** @var Avis $avis */?>
    <?php foreach ($avisArray as $denomination => $lien) : ?>
        <li>
            Avis de soutenance de <?php echo $denomination; ?> :
            <a href="<?php echo $lien; ?>"> Télécharger le pré-rapport de soutenance</a>
        </li>
    <?php endforeach; ?>
</ul>
</p>

<p>
    Nous vous prions d'agréer, <?php echo ($doctorant->getIndividu()->getCivilite() === 'M.')?"Monsieur":"Madame"; ?>, l'expression de nos salutations distinguées.
</p>

<p> P.S.: Vous pouvez obtenir une version imprimable de cette convocation à l'adresse suivante : <a href="<?php echo $url; ?>">convocation au format PDF</a> </p>

<?php if ($justification) : ?>
    <p>
        Vous avez reçu ce mail car :
        <ol>
            <li> votre proposition de soutenance a été validé par la maison du doctorat;  </li>
            <li> vous êtes le doctorant associé à la proposition de soutenance.  </li>
        </ol>
    </p>
<?php endif; ?>
