<?php

use Application\Entity\Db\These;
use Application\Service\FichierThese\PdcData;
use Soutenance\Entity\Membre;
use Soutenance\Entity\Proposition;

/**
 * @see \Soutenance\Service\Notifier\NotifierSoutenanceService::triggerEnvoiConvocationMembre()
 * @var These $these
 * @var Proposition $proposition
 * @var Membre $membre
 * @var DateTime $date
 * @var PdcData $informations
 * @var string $url
 */
$civilite = ($membre->getGenre() !== "H")?"Madame":"Monsieur";
if ($membre->getIndividu()) $civilite = ($membre->getIndividu()->estUneFemme())?"Madame":"Monsieur";

$justification = true;
?>
<p>
    <?php echo $civilite ?>, <br/>
</p>

<p>
Par décision en date du
<?php if ($date): ?>
    <?php echo $date->format('d/m/Y'); ?>,
<?php else: ?>
    <span style='background-color:red;'>
                Date manquante,
        </span>
<?php endif; ?>
le chef de l'établissement <?php echo  $these->getEtablissement()->getLibelle(); ?> vous a désigné<?php if($civilite==="Madame") echo "e"; ?>
pour participer au jury devant examiner les travaux de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(true); ?>
en vue de l'obtention du diplôme : <br/>
Doctorat en <?php echo $these->getLibelleDiscipline(); ?>.
</p>

<p>
    Le titre des travaux est : <?php echo $these->getTitre(); ?>
</p>

<?php
$encadrement = array_merge($informations->getDirecteurs(), $informations->getCodirecteurs());
$texte_directeur = implode(" et ", $encadrement);
?>

<p>
    Les travaux sont dirigées par <?php echo $texte_directeur; ?>.
</p>

<p>
    La soutenance aura lieu le
    <?php if ($informations->getDate() !== null): ?>
        <?php echo $informations->getDate(); ?>
    <?php else : ?>
        <span style='background-color:red;'>
                Date manquante
        </span>
    <?php endif; ?> à l'adresse suivante : <br/>
    <?php if ($proposition->getAdresse() !== null): ?>
        <?php echo $proposition->getAdresse(); ?>
    <?php else : ?>
        <span style='background-color:red;'>
                    Adresse manquante
            </span>
        <br/>
    <?php endif; ?>
</p>

<p>
    La soutenance <?php if ($proposition && $proposition->isHuitClos() !== null): ?>
        <?php if ($proposition->isHuitClos()) : ?>
            se déroulera en huis clos.
        <?php else : ?>
            sera publique.
        <?php endif ; ?>
    <?php else: ?>
        <span style='background-color:red;'> information sur l'aspect public manquante </span>
    <?php endif; ?>
</p>

<p>
    Je vous prie d'agréer, <?php echo $civilite; ?>, l'expression de mes salutations distinguées.
</p>

<p> P.S.: Vous pouvez obtenir une version imprimable de cette convocation à l'adresse suivante : <a href="<?php echo $url; ?>">convocation au format PDF</a> </p>

<?php if ($justification) : ?>
    Vous avez reçu ce mail car :
    <ol>
        <li> la proposition de soutenance de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?> a été validé;  </li>
        <li> vous avez été désigné comme membre du jury pour la thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?>. </li>
    </ol>
<?php endif; ?>
