<?php

use These\Entity\Db\These;
use Soutenance\Entity\Membre;
use Soutenance\Entity\Proposition;

/**
 * @see \Soutenance\Service\Notifier\NotifierSoutenanceService::triggerDemandeAvisSoutenance()
 * @var These $these
 * @var Proposition $proposition
 * @var Membre $membre
 * @var string $url
 */

//$url = $this->url('soutenance/avis-soutenance', ['these' => $these->getId(), 'rapporteur' => $membre->getId()], ['force_canonical'=>true], true);

$justification = true;
?>

<p><em>-- Version française----------------------------------------------------</em></p>

<p>
    Bonjour,
</p>
<p>
    Vous pouvez commencer à examiner les travaux thèse de <strong><?php echo $these->getDoctorant()->getNomComplet(); ?></strong>,
    ayant pour titre <strong><?php echo $these->getTitre(); ?></strong>.
    Par la suite, vous devez établir un rapport incluant votre avis sur la soutenance et votre signature au moins 14 jours
    avant la date de soutenance, puis le déposer sur la plateforme <?php echo $this->appInfos()->nom ?> à l’adresse
    suivante : <strong><a href="<?php echo $url; ?>">Accéder à votre tableau de bord SyGAL</a></strong>.
</p>
<p>
    Si votre avis est négatif, pourriez-vous indiquer brièvement les raisons de ce choix puis déposer votre rapport.
</p>
<?php if($proposition->getRenduRapport()) : ?>
    <p>
        <u>Rappel : </u>
        Le rapport est attendu pour le <?php echo $proposition->getRenduRapport()->format('d/m/Y'); ?>.
        Au delà de cette date, vous ne pourrez plus rendre votre rapport.
    </p>
<?php endif;?>
<p>
    Cordialement,
</p>

<p><em>-- English version -----------------------------------------------------</em></p>

<p>
    Dear Mrs/Mr,
</p>
<p>
    Since you have signed the "impartiality commitment", you can start the evaluation of the PhD thesis presented by
    <strong><?php echo $these->getDoctorant()->getNomComplet(); ?></strong>, entitled <strong><?php echo $these->getTitre(); ?></strong>.
    Then, you must give your opinion about the PhD thesis and upload your signed PhD report at least 14 days before the
    date of the PhD defense at : <strong><a href="<?php echo $url; ?>">Access your SyGAL dashboard</a></strong>.
</p>
<p>
    In case of a negative opinion, please indicate briefly the main reasons for the rejection and upload your signed PhD report.
</p>
<?php if($proposition->getRenduRapport()) : ?>
    <p>
        Keep in mind that your report must be uploaded before <?php echo $proposition->getRenduRapport()->format('d/m/Y'); ?>.
        After the deadline, you won't be able to upload your report.
    </p>
<?php endif;?>
est regards,
</p>

<?php if ($justification) : ?>
    <p>
        Vous avez reçu ce mail car :
    <ol>
        <li> vous avez déjà signé l'engagement d'impartialité pour la thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?>;  </li>
        <li> vous avez été désigné comme rapporteur de la thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?>. </li>
    </ol>
    </p>
<?php endif; ?>
