<?php

use These\Entity\Db\These;
use Application\Entity\Db\Validation;
use Application\View\Renderer\PhpRenderer;

/**
 * @see \Soutenance\Service\Notification\SoutenanceNotificationFactory::createNotificationDevalidationProposition()
 * @var PhpRenderer $this
 * @var Validation $validation
 * @var These $these
 */

$justification = true;
?>

<?php
$urlRetour = $this->url('soutenance/proposition', ['these' => $these->getId()], ['force_canonical'=>true], true);
?>

<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application <?php echo $this->appInfos()->nom ?>.
</p>

<p>
    Suite à la modification de la proposition de soutenance, votre validation (faite le
    <?php echo $validation->getHistoCreation()->format("d/m/Y") ?> à
    <?php echo $validation->getHistoCreation()->format("H:i") ?>) a été annulée.
    Si la nouvelle proposition vous convient, veuillez valider la proposition de soutenance à nouveau.
</p>

<p>
    Pour consulter, les modifications faites connectez-vous à <?php echo $this->appInfos()->nom ?> et visualisez la proposition de soutenance en
    utilisant le lien suivant : <a href="<?php echo $urlRetour; ?>">proposition de soutenance</a>.
</p>

<p>
    NB : La proposition de soutenance sera envoyée automatiquement à votre unité de recherche puis à votre école doctorale,
    une fois que tous les intervenants directs auront validé celle-ci (c.-à-d. doctorant, directeur et co-directeur(s)).
</p>

<?php if ($justification) : ?>
    <p>
        Vous avez reçu ce mail car :
    <ol>
        <li> vous avez validé la proposition de soutenance de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?>;  </li>
        <li> une modification de la proposition a été faite ou demandée. </li>
    </ol>
    </p>
<?php endif; ?>
