<?php

use These\Entity\Db\These;
use Soutenance\Entity\Membre;
use Soutenance\Entity\Proposition;

/**
 * @see \Soutenance\Service\Notifier\NotifierService::triggerAnnulationEngagementImpartialite()
 * @var These $these
 * @var Proposition $proposition
 * @var Membre $membre
 */

$justification = true;

?>

<p>
    Bonjour,
</p>
<p>
    Votre signature de l'engagement d'impartialité de la thèse de
    <strong><?php echo $these->getDoctorant()->getNomComplet(); ?></strong> intitulée
    <strong><?php echo $these->getTitre(); ?></strong> vient d'être annulée.
</p>

<?php if ($justification) : ?>
<p>
    Vous avez reçu ce mail car :
    <ol>
        <li> vous avez signé l'engagement d'impartialité pour la thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?>;  </li>
        <li> la signature a été annulée. </li>
    </ol>
</p>
<?php endif; ?>