<?php

use Application\Entity\Db\These;
use Soutenance\Entity\Membre;
use Soutenance\Entity\Proposition;

/**
 * @var These $these
 * @var Proposition $proposition
 * @var Membre $membre
 */

$urlRetour = $this->url('soutenance/presoutenance/engagement-impartialite', ['these' => $these->getId(), 'membre' => $membre->getId()], ['force_canonical'=>true], true);
?>


<p>
    Bonjour,
</p>
<p>
    Afin de pouvoir devenir rapporteur de la thèse de <strong><?php echo $these->getDoctorant()->getIndividu(); ?></strong> intitulée
    <strong><?php echo $these->getTitre(); ?></strong>, il est nécessaire de signer électroniquement l'engagement d'impartialité dans
    l'application SyGAL : <a href="<?php echo $urlRetour; ?>">engagement d'impartialité</a>.
</p>
<p>
    Pour vous connecter à l'application, utilisez la connection via la fédération d'identité et les identifiants communiqués dans un courrier précédent.
</p>
<p>
    <u><strong>Important</strong></u> :
    Seul les rapporteurs peuvent signer cet engagment, pensez à vous connecter en tant que rapporteur. <br/>
    <em>Pour changer de rôle, vous devez cliquer sur votre nom en haut à droite de l'application et sélectionner le rôle désiré.</em>
</p>


