<?php

use These\Entity\Db\These;
use Soutenance\Entity\Membre;
use Soutenance\Entity\Proposition;

/**
 * @see \Soutenance\Service\Notifier\NotifierService::triggerRefusEngagementImpartialite()
 * @var These $these
 * @var Proposition $proposition
 * @var Membre $membre
 */

$justification = true;
?>

<p>
    Bonjour,
</p>
<p>
    <strong><?php echo $membre->getIndividu(); ?></strong> vient de refuser de signer l'engagement d'impartialité de la thèse de
    <strong><?php echo $these->getDoctorant()->getNomComplet(); ?></strong> intitulée
    <strong><?php echo $these->getTitre(); ?></strong>.
</p>

<?php
    //$emails  = $this->fetchEmailActeursDirects($these);
    //$emails[] = $this->fetchEmailBdd($these);
?>
?>
<?php if ($justification) : ?>
    <p>
        Vous avez reçu ce mail car :
    <ol>
        <li> le rapporteur <?php echo $membre->getIndividu()->getNomComplet() ?> vient de refuser de signer l'engagement d'impartialité;  </li>
        <li> vous êtes soit :
            <ul>
                <li> un des acteurs directs de la thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?> ; </li>
                <li> un gestionnaire de la maison du doctorat de l'établissement d'inscription du doctorant . </li>
            </ul>
        </li>
    </ol>
    </p>
<?php endif; ?>

