<?php

use These\Entity\Db\These;
use Soutenance\Entity\Membre;
use Soutenance\Entity\Proposition;

/**
 * @see \Soutenance\Service\Notifier\NotifierSoutenanceService::triggerDemandeSignatureEngagementImpartialite()
 * @var These $these
 * @var Proposition $proposition
 * @var Membre $membre
 * @var string $url
 */

//$urlRetour = $this->url('soutenance/engagement-impartialite', ['these' => $these->getId(), 'membre' => $membre->getId()], ['force_canonical'=>true], true);

$justification = true;
?>

<p><em>-- Version française----------------------------------------------------</em></p>
<p>
    Bonjour,
</p>
<p>
    Afin de pouvoir devenir rapporteur de la thèse de <strong><?php echo $these->getDoctorant()->getIndividu(); ?></strong> intitulée
    <strong><?php echo $these->getTitre(); ?></strong>, il est nécessaire de signer électroniquement l'engagement d'impartialité dans
    l'application <?php echo $this->appInfos()->nom ?> : <strong><a href="<?php echo $url; ?>">Accéder à votre table de bord SyGAL</a></strong>.
</p>
<p>
    Vous accéderez ainsi à une page "index de la soutenance" listant les membres du jury.
    Cliquez ensuite sur "accès à l’engagement d’impartialité".
    Puis après avoir pris connaissance des conditions relatives à cet engagement, vous pourrez signer ou non cet engagement d’impartialité.
    Si vous signez, vous pourrez alors télécharger le PDF du manuscrit de thèse.
</p>
<p>
    Cordialement,
</p>

<p><em>-- English version -----------------------------------------------------</em></p>
<p>
    Dear Mrs/Mr,
</p>
<p>
    Before being officially registered as an external referee for the PhD thesis presented by <strong><?php echo $these->getDoctorant()->getIndividu(); ?></strong> entitled
    <strong><?php echo $these->getTitre(); ?></strong>, you have to sign the "impartiality commitment" available in your dashborad : <strong><a href="<?php echo $url; ?>">Access your SyGAL dashboard</a></strong>.
</p>
<p>
    You will then be connected to a web page entitled "index of the PhD defense" listing the PhD jury members.
    Click then on "access to the impartiality commitment".
    Then, after reading the requirements regarding the impartiality commitment of an external referee, you sign it or not.
    If you sign it, you will be able to download the PDF version of the PhD manuscript.
</p>
<p>
    Best regards,
</p>

<?php if ($justification) : ?>
    <p>
        Vous avez reçu ce mail car :
    <ol>
        <li> vous avez été désigné rapporteur pour la thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?>;  </li>
        <li> la signature a été annulée. </li>
    </ol>
    </p>
<?php endif; ?>
