<?php

use Application\Constants;
use These\Entity\Db\These;
use Application\View\Renderer\PhpRenderer;
use Soutenance\Entity\Avis;
use Soutenance\Entity\Proposition;

/**
 * @see \Soutenance\Service\Notifier\NotifierService::triggerFeuVertSoutenance()
 *
 * @var PhpRenderer $this
 * @var These $these
 * @var Proposition $proposition
 * @var Avis[] $avis
 */

$justification = true;
?>

<p>
    Bonjour,
</p>
<p>
    La soutenance de <?php echo $these->getDoctorant()->getIndividu(); ?> a été acceptée par votre établissement.
    Conformément aux informations que vous avez fournies celle-ci se tiendra le
    <em> <?php echo $proposition->getDate()->format(Constants::DATETIME_FORMAT); ?> </em>
    dans <em> <?php echo $proposition->getLieu() ?> </em>.
</p>
<p>
    Vous pouvez consulter les rapports de pré-soutenance en utilisant les liens suivant :
</p>
<ul>
    <?php foreach ($avis as $avi) : ?>
        <?php $url = $this->url('fichier/these/telecharger', [
            'these'      => $these->getId(),
            'fichier'    => $avi->getFichier()->getUuid(),
            'fichierNom' => $avi->getFichier()->getNom(),
        ], [
            'force_canonical'=>true
        ],true);
        ?>
    <li>
        <?php echo  $avi->getRapporteur(); ?>
        :

        <a href="<?php echo $url; ?>">
            rapport de pré-soutenance
        </a>
    </li>
    <?php endforeach; ?>
</ul>


<?php
//    $emailsActeurs      = $this->fetchEmailActeursDirects($these);
//    $emailsED           = $this->fetchEmailEcoleDoctorale($these);
//    $emailsUR           = $this->fetchEmailUniteRecherche($these);
?>

<?php if ($justification) : ?>
    <p>
        Vous avez reçu ce mail car :
    <ol>
        <li> la maison du doctorat vient de donner son feu vert pour la soutenance </li>
        <li> vous êtes soit :
            <ul>
                <li> un acteur direct de la thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?>, </li>
                <li> un&middot;e responsable de l'école de doctorale gérant la thèse, </li>
                <li> un&middot;e responsable de l'unité de recherche encadrant la thèse. </li>
            </ul>
        </li>
    </ol>
    </p>
<?php endif; ?>


