<?php

use Application\Entity\Db\These;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var These $these
 */

$urlRetour = $this->url('soutenance/presoutenance', ['these' => $these->getId()], ['force_canonical'=>true], true);
?>

<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application SyGAL.
</p>

<p>
    La présoutenance de la thèse suivante a été totalement validée :
</p>

<table>
    <tr>
        <th>Titre :</th>
        <td> <?php echo $these->getTitre(); ?> </td>
    </tr>
    <tr>
        <th>Doctorant :</th>
        <td> <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(false,false,false, true); ?> </td>
    </tr>
</table>

<p> Vous pouvez maintenance procéder à la saisie des informations liées à la présoutenance :
    <a href="<?php echo $urlRetour;?>"> présoutenance</a>. </p>
