<?php

use These\Entity\Db\These;
use Application\View\Renderer\PhpRenderer;

/**
 * @see \Soutenance\Service\Notifier\NotifierService::triggerNotificationPresoutenance()
 * @var PhpRenderer $this
 * @var These $these
 */

$urlRetour = $this->url('soutenance/presoutenance', ['these' => $these->getId()], ['force_canonical'=>true], true);

$justification = true;
?>

<p>
    Bonjour,
</p>
<p>
    La proposition de soutenance de la thèse suivante a été totalement validée :
</p>

<table>
    <tr>
        <th>Titre :</th>
        <td> <?php echo $these->getTitre(); ?> </td>
    </tr>
    <tr>
        <th>Doctorant :</th>
        <td> <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(false,false,false, true); ?> </td>
    </tr>
</table>

<p> Vous pouvez maintenance procéder à la saisie des informations liées à la soutenance :
    <a href="<?php echo $urlRetour;?>"> soutenance de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(false,false,false, true); ?></a>. </p>

<?php
    // $email = $this->fetchEmailBdd($these);
?>
<?php if ($justification) : ?>
    <p>
        Vous avez reçu ce mail car :
    <ol>
        <li> la proposition de soutenance de thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?> a été complètement validée ;</li>
        <li> vous êtes gestionnaire de la maison du doctorat de l'établissement d'inscription du doctorant. </li>
    </ol>
    </p>
<?php endif; ?>

