<?php

use Individu\Entity\Db\Individu;
use Application\Entity\Db\Role;
use These\Entity\Db\These;
use Application\View\Renderer\PhpRenderer;
use UnicaenAuth\Entity\Db\RoleInterface;

/**
 * @see \Soutenance\Service\Notifier\NotifierSoutenanceService::triggerRefusPropositionSoutenance()
 * @var PhpRenderer $this
 * @var These $these
 * @var Individu $acteur
 * @var RoleInterface $crole
 * @var Role $role
 * @var string $motif
 * @var bool $justification
 */
?>

<p>
    Bonjour,
</p>
<p>
    <?php echo $acteur->getNomComplet(false, false, false, true); ?>
    (<?php echo $role->getLibelle(); ?> <i><?php echo $role->getStructure()->getLibelle(); ?></i>)
    a refus votre proposition de soutenance.
    Le motif du refus est le suivant :
</p>

<table style="border:gray solid 2px; width:50em; background-color: whitesmoke;">
    <tr><td>
            <?php echo $motif; ?>
        </td></tr>
</table>

<p>
    Suite à ce refus toutes les validations associées à cette proposition ont été annulées.
</p>

<?php
    //$emails = $this->fetchEmailActeursDirects($these);
?>
<?php if ($justification) : ?>
    <p>
        Vous avez reçu ce mail car :
    <ol>
        <li> la proposition de soutenance de thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?> a été refusée ;</li>
        <li> vous êtes un des acteurs directs de la thèse.</li>
    </ol>
    </p>
<?php endif; ?>
