<?php

use Application\Constants;
use These\Entity\Db\These;
use Application\View\Renderer\PhpRenderer;
use Soutenance\Entity\Avis;
use Soutenance\Entity\Proposition;

/**
 * @see \Soutenance\Service\Notifier\NotifierSoutenanceService::triggerStopperDemarcheSoutenance()
 *
 * @var PhpRenderer $this
 * @var These $these
 * @var Proposition $proposition
 * @var Avis[] $avis
 * @var bool $justification
 */

?>

<p>
    Bonjour,
</p>
<p>
    Les démarches associées à la soutenance de <?php echo $these->getDoctorant()->getIndividu(); ?> ont été stoppé par la maison du doctorats de votre établissement.
    Veuillez consulter celle-ci pour obtenir plus d'information.
</p>
<p>
    Vous pouvez consulter les rapports de présoutenance en utilisant les liens suivant :
</p>
<ul>
    <?php foreach ($avis as $avi) : ?>
        <?php $url = $this->url('fichier/these/telecharger', [
            'these'      => $these->getId(),
            'fichier'    => $avi->getFichier()->getUuid(),
            'fichierNom' => $avi->getFichier()->getNom(),
        ], [
            'force_canonical'=>true
        ],true);
        ?>
    <li>
        <?php echo  $avi->getRapporteur(); ?>
        :

        <a href="<?php echo $url; ?>">
            rapport de pré-soutenance
        </a>
    </li>
    <?php endforeach; ?>
</ul>

<?php
//    $emailsActeurs      = $this->fetchEmailActeursDirects($these);
//    $emailsED           = $this->fetchEmailEcoleDoctorale($these);
//    $emailsUR           = $this->fetchEmailUniteRecherche($these);
?>
<?php if ($justification) : ?>
    <p>
        Vous avez reçu ce mail car :
    <ol>
        <li> la soutenance de thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?> ne peut pas avoit lieu dans l'état actuel ;</li>
        <li> vous êtes :
            <ul>
                <li> un des acteurs directs de la thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?>, </li>
                <li> un&middot;e responsable de l'école de doctorale gérant la thèse, </li>
                <li> un&middot;e responsable de l'unité de recherche encadrant la thèse. </li>
            </ul>
        </li>
    </ol>
    </p>
<?php endif; ?>
