<?php

use These\Entity\Db\These;

/**
 * @see \Soutenance\Service\Notification\SoutenanceNotificationFactory::createNotificationAvisRendusDirection()
 *
 * @var These $these
 */

$url = $this->url('soutenance/proposition', ['these' => $these->getId()], ['force_canonical'=>true], true);

$justification = true;
?>

<p>
    Bonjour,
</p>
<p>
    Les rapporteurs de la thèse de <?php echo $these->getDoctorant()->getIndividu(); ?> ont rendu leur rapport de pré-soutenance.
</p>
<p>
    Vous pouvez les consulter ceux-ci sur la page de la proposition de soutenance :
    <a href="<?php echo $url; ?>">page de gestion de la soutenance</a>.
</p>

<?php if ($justification) : ?>
    <p>
        Vous avez reçu ce mail car :
    <ol>
        <li> tous les avis de soutenance de la thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?> ont été rendus ;</li>
        <li> vous êtes membre de la direction de la thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?>. </li>
    </ol>
    </p>
<?php endif; ?>
