<?php

use These\Entity\Db\These;

/**
 * @see \Soutenance\Service\Notifier\NotifierSoutenanceService::triggerAvisRendus()
 *
 * @var These $these
 */

$url = $this->url('soutenance/presoutenance', ['these' => $these->getId()], ['force_canonical'=>true], true);

$justification = true;
?>

<p>
    Bonjour,
</p>
<p>
    Les rapporteurs de la thèse de <?php echo $these->getDoctorant()->getIndividu(); ?> ont rendu leur rapport de pré-soutenance.
</p>
<p>
    Vous pouvez les consulter sur la page de gestion de la pré-soutenance de cette thèse :
    <a href="<?php echo $url; ?>">page de gestion de la soutenance</a>.
</p>

<?php
//    $email = $this->fetchEmailBdd($these);
?>
<?php if ($justification) : ?>
    <p>
        Vous avez reçu ce mail car :
    <ol>
        <li> tous les avis de soutenance de la thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?> ont été rendus ;</li>
        <li> vous êtes gestionnaire de la maison du doctorat de l'établissement d'inscription du doctorant. </li>
    </ol>
    </p>
<?php endif; ?>
