<?php

use Application\Entity\Db\These;

/**
 * @var These $these
 */

$url = $this->url('soutenance/presoutenance', ['these' => $these->getId()], ['force_canonical'=>true], true);
?>

<p>
    Bonjour,
</p>
<p>
    Tous les rapporteurs de la thèse de <?php echo $these->getDoctorant()->getIndividu(); ?> ont été rendu leur avis de soutenance.
    Vous pouvez consuslter ces avis et les rapports de présoutenances sur la page de gestion de la présoutenance de cette thèse :
    <a href="<?php echo $url; ?>">page de gestion de la présoutenance</a>.
</p>
