<?php

use Application\Entity\Db\These;

/**
 * @see \Soutenance\Service\Notifier\NotifierSoutenanceService::triggerAvisRendus()
 *
 * @var These $these
 */

$url = $this->url('soutenance/presoutenance', ['these' => $these->getId()], ['force_canonical'=>true], true);
?>

<p>
    Bonjour,
</p>
<p>
    es rapporteurs de la thèse de <?php echo $these->getDoctorant()->getIndividu(); ?> ont rendu leur rapport de pré-soutenance.
</p>
<p>
    Vous pouvez les consulter sur la page de gestion de la pré-soutenance de cette thèse :
    <a href="<?php echo $url; ?>">page de gestion de la soutenance</a>.
</p>
