<?php

use Application\Entity\Db\These;
use Application\View\Renderer\PhpRenderer;

/**
 * @see \Soutenance\Service\Notifier\NotifierSoutenanceService::triggerNotificationPropositionValidee()
 * @var PhpRenderer $this
 * @var These $these
 */

$urlRetour = $this->url('soutenance/proposition', ['these' => $these->getId()], ['force_canonical'=>true], true);

$justification = true;
?>

<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application <?php echo $this->appInfos()->nom ?>.
</p>

<p>
    La proposition de soutenance de thèse suivante a été validée par tous les acteurs et structures associées :
</p>

<table>
    <tr>
        <th>Titre :</th>
        <td> <?php echo $these->getTitre(); ?> </td>
    </tr>
    <tr>
        <th>Doctorant :</th>
        <td> <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(false,false,false, true); ?> </td>
    </tr>
</table>

<p> Pour examiner cette proposition merci de vous rendre dans l'application <?php echo $this->appInfos()->nom ?> :
    <a href="<?php echo $urlRetour;?>"> proposition de soutenance.</a> </p>

<?php
//$emails = $this->fetchEmailActeursDirects($these);
?>
<?php if ($justification) : ?>
    <p>
        Vous avez reçu ce mail car :
    <ol>
        <li> un des acteurs directs de la thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?> vient de valider la proposition de soutenance  ;</li>
        <li> vous êtes un des acteurs directs de la thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?>.</li>
    </ol>
    </p>
<?php endif; ?>

<?php
    // $emailsBDD      = [ $this->fetchEmailBdd($these) ];
    // $emailsED       = $this->fetchEmailEcoleDoctorale($these);
    // $emailsUR       = $this->fetchEmailUniteRecherche($these);
    // $emailsActeurs  = $this->fetchEmailActeursDirects($these);
?>
<?php if ($justification) : ?>
    <p>
        Vous avez reçu ce mail car :
    <ol>
        <li> la proposition de soutenance vient d'être validée par tous les acteurs directs et toutes les structures concernées ; </li>
        <li> vous êtes soit :
            <ul>
                <li> un des acteurs directs de la thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?>,</li>
                <li> un&middot;e responsable de l'école de doctorale gérant la thèse, </li>
                <li> un&middot;e responsable de l'unité de recherche encadrant la thèse, </li>
                <li> un&middot;e gestionnaire du bureau des doctorat de l'établissement d'inscription du doctorant. </li>
            </ul>
        </li>
    </ol>
    </p>
<?php endif ; ?>
