<?php

use Application\Entity\Db\Validation;
use Application\View\Renderer\PhpRenderer;

/**
 * @see \Soutenance\Service\Notifier\NotifierSoutenanceService::triggerValidationProposition()
 * @var PhpRenderer $this
 * @var Validation $validation
 */
?>

<?php
$urlRetour = $this->url('soutenance/proposition', ['these' => $validation->getThese()->getId()], ['force_canonical'=>true], true);
?>

<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application SyGAL.
</p>

<p>
    <?php echo $validation->getIndividu(); ?> vient de valider la proposition de soutenance de thèse.
</p>

<p>
    Pour consulter cette proposition, connectez-vous à SyGAL et visualisez la proposition de soutenance en utilisant le lien suivant : <a href="<?php echo $urlRetour; ?>">proposition de soutenance</a>.
</p>

<p>
    NB : La proposition de soutenance sera envoyée automatiquement à votre unité de recherche puis à votre école doctorale,
    une fois que tous les intervenants directs auront validé celle-ci (c.-à-d. doctorant, directeur et co-directeur(s)).
</p>
