<?php

use Application\Entity\Db\These;
use Application\View\Renderer\PhpRenderer;

/**
 * @see \Soutenance\Service\Notifier\NotifierSoutenanceService::triggerNotificationUniteRechercheProposition()
 * @see \Soutenance\Service\Notifier\NotifierSoutenanceService::triggerNotificationEcoleDoctoraleProposition()
 * @see \Soutenance\Service\Notifier\NotifierSoutenanceService::triggerNotificationBureauDesDoctoratsProposition()
 * @var PhpRenderer $this
 * @var These $these
 * @var string $type
 */

$urlRetour = $this->url('soutenance/proposition', ['these' => $these->getId()], ['force_canonical'=>true], true);

$justification = true;
?>

<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application SyGAL.
</p>

<p>
    Une proposition de soutenance vient d'être faite pour la thèse suivante :
</p>

<table>
    <tr>
        <th>Titre :</th>
        <td> <?php echo $these->getTitre(); ?> </td>
    </tr>
    <tr>
        <th>Doctorant :</th>
        <td> <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(false,false,false, true); ?> </td>
    </tr>
</table>

<p> Pour examiner cette proposition et statuer sur celle-ci merci de vous rendre dans l'application SyGAL :
    <a href="<?php echo $urlRetour;?>"> proposition de soutenance.</a> </p>

<?php if ($justification) : ?>
<p>
    Vous avez reçu ce mail car :
<ol>
    <?php if ($type === 'unité de recherche') : ?>
        <li> tous les acteurs directs de la thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?> ont validé la proposition de soutenance ; </li>
        <li> vuos êtes un gestionnaire de l'unité de recherche encadrant la thèse. </li>
    <?php endif; ?>
    <?php if ($type === 'école doctorale') : ?>
        <li> l'unité de recherche encadrant la thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?> a validé la proposition de soutenance ; </li>
        <li> vous êtes un gestionnaire de l'école de doctorale gérant la thèse. </li></li>
    <?php endif; ?>
    <?php if ($type === 'maison du doctorat') : ?>
        <li> l'école doctorale gérant la thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?> a validé la proposition de soutenance ; </li>
        <li> vous êtes un gestionnaire du bureau des doctorat de l'établissement d'inscription du doctorant.</li>
    <?php endif; ?>
</ol>
</p>
<?php endif; ?>
