<?php
/**
 * @var AdmissionAvis $operation
 * @var bool $ajaxModalEvent
 * @var AdmissionOperationInterface $operationEnAttente
 * @var int $count
 * @var string $libelleOperation
 * @var bool $showRangOperation
 * @var boolean $showActionButtons
 */

use Admission\Entity\Db\AdmissionAvis;
use Admission\Entity\Db\AdmissionOperationInterface;
use Admission\Provider\Privilege\AdmissionPrivileges;

$avis = $operation->getAvis();

$canAjouterOperation =
    $this->isAllowed($operation, AdmissionPrivileges::ADMISSION_AJOUTER_AVIS_TOUT) ||
    $this->isAllowed($operation, AdmissionPrivileges::ADMISSION_AJOUTER_AVIS_SIEN);
?>
<div class="row subfield">
    <div class="col etape_signature">
        <?php if ($showRangOperation) {
            if ($operationEnAttente && $operationEnAttente->getTypeToString() == $operation->getTypeToString()) { ?>
                <div class="col-lg-2 circle_etape etape_signature">
                    <span class="icon icon-hourglass circle_waiting"></span>
                </div>
            <?php } else { ?>
                <div class="circle"><p><?= $count ?></p></div>
            <?php }
        } ?>
        <div class="col-lg-6 libelle_etape etape_signature">
            <label><?php echo $libelleOperation ?: $operation->getAvis()->getAvisType()->getLibelle(); ?></label>
        </div>
        <?php if ($canAjouterOperation && ((isset($showActionButtons) && $showActionButtons))): ?>
            <a href="<?php echo $this->url('admission/aviser', [
                'admission' => $operation->getAdmission()->getId(),
                'typeAvis' => $operation->getAvis()->getAvisType()->getId(),
            ]) ?>"
               class="card-link btn btn-primary btn-sm action ajax-modal"
               data-event="<?php echo $ajaxModalEvent ?>">Saisir l'avis</span></a>
        <?php endif ?>
    </div>
</div>