<h1 class="page-header">Le doctorat en Normandie</h1>

<h2>Inscription en doctorat</h2>

<p>
    Si vous souhaitez vous inscrire en doctorat en Normandie, suivre les liens suivants en fonction de l’
    <a href="/documents/autres/Etablissements.docx">établissement d’inscription</a> :
</p>
<ul>
    <li><a href="https://www.insa-rouen.fr">INSA Rouen Normandie</a></li>
    <li><a href="https://www.unicaen.fr">Université de Caen Normandie</a></li>
    <li><a href="http://www.univ-rouen.fr">Université de Rouen Normandie</a></li>
    <li><a href="https://www.univ-lehavre.fr">Université Le Havre Normandie</a></li>
</ul>

<h2>Le doctorat </h2>

<p>
    Le doctorat est le plus élevé des grades universitaires. Il correspond au grade de docteur et est attesté par un diplôme national.
    Le grade de doctorat donne droit à l'usage du titre de docteur (ou Dr). Le doctorat est conféré généralement après trois années de
    recherche postérieures à l'obtention du grade de master ou équivalent et à la suite de la soutenance d'une thèse portant sur la
    réalisation de travaux scientifiques originaux. Le doctorat sanctionne « une formation par la recherche, à la recherche et à l'innovation »
    et « une expérience professionnelle de recherche ». </p>

<h2>La direction de thèse</h2>

<p>
    La direction de la thèse est assurée par une ou deux personnes habilitées à diriger des recherches (HDR) rattachées à une
    <a href="/documents/autres/Unités de Recherche.xlsx">Unité de Recherche de Normandie</a>. Exceptionnellement, une seconde
    co-direction de thèse peut être assurée par une personne du monde socio-économique non universitaire.
</p>

<h2>Co-encadrement de thèse</h2>

<p>
    Le doctorant peut être co-encadré par une personne non habilitée à diriger des recherches. La demande de co-encadrement
    est validée par la commission recherche de chacune des universités après avis de l’école doctorale de rattachement.
</p>

<h2>Obligations légales</h2>

<p>
    L’<a href="">arrêté ministériel du 25 mai 2016</a> fixe le cadre national de la formation et les modalités conduisant à la délivrance du diplôme national de doctorat.
</p>

<p>Parmi les obligations légales, rappelons :</p>
<ul>
    <li>la signature, à l’inscription en thèse, de la charte du doctorat, de la convention de formation doctorale et du règlement intérieur de l’Ecole Doctorale de rattachement et le respect des clauses rapportées dans ces textes ;</li>
    <li>la mise en place et la tenue d’un comité de suivi de thèse individuel (CSTI) ;</li>
    <li>l’application du règlement intérieur et/ou des pratiques (sécurité, confidentialité …) de l’<a href="/documents/autres/Unités de Recherche.xlsx">Unité de Recherche d’accueil</a> ;</li>
    <li>la rédaction d’un rapport annuel.</li>
</ul>

<h2>Le doctorat en Normandie</h2>

<p>
    En 2018, près de 1800 doctorants étaient inscrits en thèse en Normandie et 343 ont soutenu leur thèse selon la répartition
    disciplinaire suivante :
</p>

<table class="table table-extra-condensed">
    <thead>
    <tr>
        <th>ED</th>
        <th>Biologie Santé</th>
        <th>Economie Gestion</th>
        <th>Droit</th>
        <th>Histoire Mémoire Patrimoine Langage</th>
        <th>Homme Sociétés Risques Territoire</th>
        <th>Chimie</th>
        <th>Physique, matériaux énergie</th>
        <th>Mathématiques informatique</th>
        <th>Total</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>Inscrits</td>
        <td>275</td>
        <td>82</td>
        <td>142</td>
        <td>332</td>
        <td>253</td>
        <td>133</td>
        <td>329</td>
        <td>217</td>
        <td>1763</td>
    </tr>
    <tr>
        <td>Soutenances</td>
        <td>70</td>
        <td>10</td>
        <td>14</td>
        <td>46</td>
        <td>42</td>
        <td>37</td>
        <td>85</td>
        <td>39</td>
        <td>343</td>
    </tr>
    </tbody>
</table>

<p>
    Les doctorants sont inscrits dans <a href="/documents/autres/Etablissements.docx">un des quatre établissements normands</a>
    habilités à inscrire en thèse. Quel que soit l’établissement d’inscription, les doctorants reçoivent après leur soutenance
    le diplôme de docteur de <a href="/documents/autres/Normandie Université.docx">Normandie Université</a>.
</p>

<h2>Financement des thèses en Normandie</h2>
<p>Le financement des doctorants en Normandie s’établit comme suit (données 2017) :</p>

<table class="table table-extra-condensed">
    <thead>
    <tr>
        <th>Financement</th>
        <th>%</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>Allocation doctorale d’établissement / grands organismes</td>
        <td>24</td>
    </tr>
    <tr>
        <td>Allocation doctorale régionale à 100%</td>
        <td>18.6</td>
    </tr>
    <tr>
        <td>Allocation doctorale régionale co-financée</td>
        <td>4.8</td>
    </tr>
    <tr>
        <td>Contrat avec une entreprise ou un organisme public</td>
        <td>5.6</td>
    </tr>
    <tr>
        <td>CIFRE</td>
        <td>4.8</td>
    </tr>
    <tr>
        <td>Salarié(e)</td>
        <td>23</td>
    </tr>
    <tr>
        <td>Financement pour doctorant en situation de handicap</td>
        <td>1</td>
    </tr>
    <tr>
        <td>Financement pour doctorants étrangers</td>
        <td>8.4</td>
    </tr>
    <tr>
        <td>Doctorants sans financement dédié</td>
        <td>9.7</td>
    </tr>
    </tbody>
</table>

<h2>Les maisons du doctorat</h2>
<p>
    Chaque doctorant est rattaché à une école doctorale et inscrit dans un <a href="/documents/autres/Etablissements.docx">établissement normand</a>
    habilité à inscrire en thèse. Les services supports et conseil du doctorat (Ecoles Doctorales et gestion administrative
    de l’établissement d’inscription) sont regroupés au sein des maisons du doctorat. Des lieux de rencontre entre doctorants
    et des salles dédiées à la formation doctorale sont mis à disposition dans les locaux des maisons du doctorat ou à proximité.
</p>

<p>Ces maisons du doctorat sont localisées sur les principaux sites universitaires normands :</p>
<ul>
    <li>Site de Mont-Saint-Aignan, Université de Rouen Normandie : <a href="/documents/MaisonDoctorat/Plan maison doctorat MSA.pptx">1er étage, bâtiment Monod</a> ;</li>
    <li>Site du Madrillet, Université de Rouen Normandie : <a href="/documents/MaisonDoctorat/Plan maison Madrillet.pptx">hall, faculté des Sciences et Techniques</a> ;</li>
    <li>Campus 1, Université de Caen Normandie : <a href="/documents/MaisonDoctorat/Plan maison doctorat campus 1 UCN.pptx">MRSH</a> ;</li>
    <li>Campus 2, Université de Caen Normandie : <a href="/documents/MaisonDoctorat/Plan maison doctorat campus 2 UCN.pptx">Bâtiment Sciences 3</a> ;</li>
    <li>Université Le Havre Normandie : <a href="/documents/MaisonDoctorat/Plan maison doctorant ULHN.pptx">DirVED</a>.</li>
</ul>

<h2>Le devenir des docteurs</h2>

<p>
    Un suivi sur le devenir des docteurs normands est assuré par les observatoires des établissements qui interrogent .
    régulièrement les docteurs sur leurs situations professionnelles 3 et 5 ans après la soutenance de thèse.
</p>
<p>
    Les résultats de ces enquêtes disponibles sur le <a href="http://www.normandie-univ.fr/insertion-des-docteurs-normands-18585">site de Normandie Université</a>.
</p>