<h1 class="page-header">Les écoles doctorales normandes</h1>

<p>
    Les écoles doctorales ont été créées au début des années 90 avec pour mission l’accompagnement des doctorants vers
    leur insertion professionnelle à l'issue de leur formation doctorale. Les écoles doctorales regroupent des doctorants
    d’un même domaine scientifique pouvant être issus de plusieurs établissements.
</p>

<p>Les missions des écoles doctorales sont :</p>
<ul>
    <li>mettre en œuvre une politique d'admission des nouveaux doctorants, fondée sur des critères explicites et publics.
        Elles informent les étudiants sur les conditions d'accès, les compétences requises, les financements susceptibles
        d'être obtenus, la nature, la qualité et les taux d'activité professionnelle après l'obtention du doctorat ;</li>
    <li>organiser les échanges scientifiques entre doctorants et leur communauté scientifique ;</li>
    <li>proposer aux doctorants des activités de formation disciplinaire ;</li>
    <li>assurer une démarche qualité de suivi de la formation en mettant notamment en place des comités de suivi de thèse
        individuel du doctorant ;</li>
    <li>contribuer à une ouverture internationale.</li>
</ul>

<h2>Les écoles doctorales de Normandie Université</h2>

<p>
    La formation doctorale en Normandie s’articule autour de 8 Écoles Doctorales (ED) disciplinaires qui regroupent des
    unités de recherche rattachées aux Universités de Caen Normandie, Le Havre Normandie et de Rouen Normandie, des deux
    écoles d’ingénieurs l'ENSICAEN et l'INSA Rouen Normandie, ainsi que des établissements associés ou partenaires accueillant
    des doctorants : ESIGELEC, UniLaSalle, CESI, ESITC, GANIL et ENVA. Ces ED sont :</p>

<ul>
    <li><a href="/documents/ED/DN.docx">ED 98 Droit Normandie (DN)</a></li>
    <li><a href="/documents/ED/EGN.docx">ED 242 Économie-Gestion Normandie (EGN)</a></li>
    <li><a href="/documents/ED/NBISE.docx">ED 497 Normande de Biologie Intégrative, Santé, Environnement (NBISE)</a></li>
    <li><a href="/documents/ED/NC.docx">ED 508 Normande de Chimie (NC)</a></li>
    <li><a href="/documents/ED/HSRT.docx">ED 556 Homme, Sociétés, Risques, Territoire (HSRT)</a></li>
    <li><a href="/documents/ED/HMPL.docx">ED 558 Histoire, Mémoire, Patrimoine, Langage (HMPL)</a></li>
    <li><a href="/documents/ED/MIIS.docx">ED 590 Mathématiques, Information, Ingénierie des Systèmes (MIIS)</a></li>
    <li><a href="/documents/ED/PSIME.docx">ED 591 Physique, Sciences de l’Ingénieur, Matériaux, Énergie (PSIME)</a></li>
</ul>

<p>
    Chaque école doctorale est gérée par un directeur et des directeurs-adjoints de site, assistés de gestionnaires et
    d’un conseil dans lequel siègent aussi des représentants des doctorants. Ce conseil définit les actions à mener et
    bénéficie d’un budget propre. Le fonctionnement de chaque Ecole Doctorale est régi par un règlement intérieur.
</p>

<h2>Le Collège des Écoles Doctorales (CED)</h2>

<p>
    La politique doctorale est une compétence propre de <a href="/documents/autres/Normandie Université.docx">Normandie Université</a>.
    En conséquence, elle assure la coordination des Ecoles Doctorales via une composante interne en charge de la formation
    doctorale en Normandie : le Collège des Écoles Doctorales (CED). Ce collège est un lieu de concertation qui rassemble
    les directions Recherche des établissements, les directions des 8 Ecoles Doctorales et des représentants des doctorants.
</p>

<p>Les missions du Collège des Ecoles Doctorales sont :</p>

<ul>
    <li>harmoniser les politiques doctorales des établissements normands ;</li>
    <li>communiquer la politique doctorale de Normandie Université vers les étudiants et le monde socio-économique ;</li>
    <li>consolider les liens entre les ED et le tissu économique ;</li>
    <li>proposer aux doctorants une formation transversale favorisant l'interdisciplinarité et l'acquisition d'une culture
        scientifique élargie en veillant à ce que chaque doctorant reçoive une formation à l'éthique de la recherche, à
        l'intégrité scientifique et aux enjeux de la diffusion de la culture scientifique, technique et industrielle ;</li>
    <li>organiser des événements transversaux de grande ampleur : cérémonie publique de remise du diplôme de docteur, Ma
        Thèse en 180 secondes, les Doctoriales …</li>
    <li>enquêter sur le devenir des docteurs après leur soutenance de thèse.</li>
</ul>
