<?php

namespace Admission\Hydrator\Verification;

use Admission\Entity\Db\Verification;
use Doctrine\Laminas\Hydrator\DoctrineObject;

/**
 * @author Unicaen
 */
class VerificationHydrator extends DoctrineObject
{
    /**
     * @param Verification $object
     * @return array
     */
    public function extract($object): array
    {
        return parent::extract($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $data
     * @param object $object
     * @return Verification
     */
    public function hydrate(array $data, object $object): object
    {
        $data['estComplet'] = $data['estComplet'] ?? null;
        if((isset($data['commentaire']) && trim($data['commentaire']) !== '') && ($data['estComplet'] !== null && !$data['estComplet'])){
            $data['commentaire'] = trim($data['commentaire']);
        }else{
            $data['commentaire'] = null;
        }

        return parent::hydrate($data, $object);
    }
}