<?php

namespace Application;

use Application\Entity\Db\Rapport;
use ComiteSuiviIndividuel\Entity\Db\Membre;
use These\Entity\Db\These;
use Application\Entity\Db\TypeValidation;
use Application\Form\RapportCsiForm;
use Application\Provider\Privilege\RapportPrivileges;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var These $these
 * @var Rapport[] $rapports
 * @var RapportCsiForm $form
 * @var bool $isTeleversementPossible
 * @var TypeValidation $typeValidation
 * @var Membre[] $membres
 *
 * @see \Application\Controller\Rapport\RapportCsiController::consulterAction()
 */

$routeName = 'rapport-csi';
$privilege_TELEVERSER_TOUT = RapportPrivileges::RAPPORT_CSI_TELEVERSER_TOUT;
$privilege_TELEVERSER_SIEN = RapportPrivileges::RAPPORT_CSI_TELEVERSER_SIEN;
$privilege_SUPPRIMER_TOUT = RapportPrivileges::RAPPORT_CSI_SUPPRIMER_TOUT;
$privilege_SUPPRIMER_SIEN = RapportPrivileges::RAPPORT_CSI_SUPPRIMER_SIEN;
$privilege_TELECHARGER_TOUT = RapportPrivileges::RAPPORT_CSI_TELECHARGER_TOUT;
$privilege_TELECHARGER_SIEN = RapportPrivileges::RAPPORT_CSI_TELECHARGER_SIEN;

$form->prepare();
$rapportProto = (new Rapport())->setThese($these);
$canAdd = $this->isAllowed($rapportProto, $privilege_TELEVERSER_TOUT) || $this->isAllowed($rapportProto, $privilege_TELEVERSER_SIEN);
if (!$isTeleversementPossible) {
    $canAdd = false;
}

$canModifier = ($privilege_TELEVERSER_SIEN OR $privilege_TELEVERSER_TOUT);
?>

<?php $this->headTitle($this->translate($title = "Rapports CSI"))
    ->prepend($these->getDoctorant()->getIndividu()->getNomUsuel()) ?>

<h1 class="page-header">
    <?php echo $this->translate($title); ?>
    <small><?php echo $this->partial('these/these/partial/titre') ?></small>
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace(); ?>

<p class="lead">
    Cette page est consacrée au téléversement des rapports CSI.
</p>

<?php if (false) : //todo à retirer lors de la création du vrai module CSI ?>
<div class="row">
    <div class="col-md-11">

        <h2>Membres du comité</h2>

        <?php if ($membres AND !empty($membres)) : ?>
            <table class="table table-condensed table-hover">
                <thead>
                    <tr>
                        <th> Civilité </th>
                        <th> Prénom </th>
                        <th> Nom </th>
                        <th> Adresse électronique </th>
                        <th> Qualité </th>
                        <th> Rang </th>
                        <th> Extérieur </th>
                        <th> Établissement </th>
                        <th> Rôle </th>
                        <th> En visio </th>
                        <?php if ($canModifier) : ?>
                            <th> Action</th>
                        <?php endif; ?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($membres as $membre) : ?>
                    <tr>
                        <td> <?php echo ($membre->getGenre()==='F')?"Madame":"Monsieur"; ?> </td>
                        <td> <?php echo $membre->getPrenom(); ?> </td>
                        <td> <?php echo $membre->getNom(); ?> </td>
                        <td> <?php echo ($membre->getEmail() !== null)?$membre->getEmail():"<strong><span class='text-danger'><span class='fas fa-exclamation-triangle'></span> AUCUN MAIL</span></strong>"; ?> </td>
                        <td> <?php echo ($membre->getQualite())?$membre->getQualite()->getLibelle():"Non définie"; ?> </td>
                        <td> <?php echo $membre->getRang(); ?> </td>
                        <td>
                            <?php if ($membre->isExterieur()): ?>
                                <span class="icon icon-oui iconly text-success"></span>
                            <?php else: ?>
                                <span class="icon icon-non iconly text-danger"></span>
                            <?php endif; ?>
                        </td>
                        <td>
                            <?php echo $membre->getEtablissement(); ?> <br/>
                        </td>
                        <td> <?php echo $membre->getRole(); ?> </td>
                        <td>
                            <?php if ($membre->isVisio()): ?>
                                <span class="icon icon-oui iconly text-success"></span>
                                <?php $hasVisio = true; ?>
                            <?php else: ?>
                                <span class="icon icon-non iconly text-danger"></span>
                            <?php endif; ?>
                        </td>
                        <?php if ($canModifier) : ?>
                            <td>
                                <a  <?php /** @see \ComiteSuiviIndividuel\Controller\MembreController::modifierAction(); */ ?>
                                        href="<?php echo $this->url('comite-suivi-individuel/membre/modifier', ['membre' => $membre->getId()], [] ,true); ?>"
                                        class="ajax-modal"
                                        data-event="modification">
                                    <span class="icon icon-edit iconly"></span>
                                </a>
                                <a  <?php /** @see \ComiteSuiviIndividuel\Controller\MembreController::supprimerAction(); */ ?>
                                        href="<?php echo $this->url('comite-suivi-individuel/membre/supprimer', ['membre' => $membre->getId()], [] ,true); ?>"
                                        class="ajax-modal"
                                        data-event="modification">
                                    <span class="icon icon-delete iconly"></span>
                                </a>
                            </td>
                        <?php endif; ?>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php else : ?>
            <p>
            Aucun membre de désigné
            </p>
        <?php endif; ?>

        <?php if ($canModifier) : ?>
            <a  <?php /** @see \ComiteSuiviIndividuel\Controller\MembreController::ajouterAction(); */ ?>
                href="<?php echo $this->url('comite-suivi-individuel/membre/ajouter', ['these' => $these->getId()]); ?>"
                class="btn btn-primary ajax-modal" data-event="modification"
            >
                <span class="icon icon-user-add"></span>
                Ajouter une membre du comité
            </a>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>

<div class="row">
    <div class="col-md-11">

        <h2>Rapports téléversés</h2>

        <?php if (count($rapports) > 0): ?>

            <?php echo $this->partial('application/rapport/partial/rapports-table', [
                'rapports' => $rapports,
                'routeName' => $routeName,
                'typeValidation' => $typeValidation,
                'privilege_TELEVERSER_TOUT' => $privilege_TELEVERSER_TOUT,
                'privilege_TELEVERSER_SIEN' => $privilege_TELEVERSER_SIEN,
                'privilege_SUPPRIMER_TOUT' => $privilege_SUPPRIMER_TOUT,
                'privilege_SUPPRIMER_SIEN' => $privilege_SUPPRIMER_SIEN,
                'privilege_TELECHARGER_TOUT' => $privilege_TELECHARGER_TOUT,
                'privilege_TELECHARGER_SIEN' => $privilege_TELECHARGER_SIEN,
//                'privilege_VALIDER_TOUT' => $privilege_VALIDER_TOUT,
//                'privilege_VALIDER_SIEN' => $privilege_VALIDER_SIEN,
//                'privilege_DEVALIDER_TOUT' => $privilege_DEVALIDER_TOUT,
//                'privilege_DEVALIDER_SIEN' => $privilege_DEVALIDER_SIEN,
                'displayEtablissement' => false,
                'displayType' => false,
                'displayDoctorant' => false,
                'displayDirecteurThese' => false,
                'displayEcoleDoctorale' => false,
                'displayUniteRecherche' => false,
                'displayValidation' => false,
            ]) ?>

        <?php else: ?>

            <p>Aucun.</p>

        <?php endif; ?>

    </div>
</div>

<div class="row">
    <div class="col-md-offset-1 col-md-8">

<!--        --><?php //if ($tousLesRapportsTeleverses): ?>
<!--            <div class="row">-->
<!--                <div class="col-md-6 text-success">-->
<!--                    <p>-->
<!--                        <span class="icon icon-info"></span>-->
<!--                        Toutes les années universitaires d'inscription du doctorant ont fait l'objet d'un téléversement de rapport.-->
<!--                    </p>-->
<!--                </div>-->
<!--            </div>-->
<!--        --><?php //endif ?>

        <?php $ajouterFormVisible = !empty($form->getMessages()); ?>
        <div id="ajouterDiv">
            <div class="row">
                <div class="col-md-4">
                    <a href="#" id="ajouterBtn" class="btn btn-primary <?php echo $canAdd ? '' : 'disabled' ?>"
                       style="display: <?php echo !$ajouterFormVisible ? 'flex' : 'none' ?>">
                        <span class="icon icon-televerser"></span> Téléverser un rapport</a>
                </div>
            </div>

            <div id="ajouterForm" style="display: <?php echo $ajouterFormVisible ? 'inherit' : 'none' ?>">
                <h3>Formulaire de téléversement</h3>

                <?php echo $this->form()->openTag($form) ?>
                <div class="row">
                    <div class="col-md-4">
                        <?php echo $this->formControlGroup($form->get('anneeUniv')) ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-7">
                        <?php
                        echo $this->formControlGroup($form->get('files'));
                        echo $this->formControlGroup($form->get('security'));
                        echo $this->formSubmit($form->get('submit')->setAttributes(['class' => 'btn btn-primary']));
                        ?>
                    </div>
                </div>
                <?php echo $this->form()->closeTag() ?>
                <div class="row">
                    <div class="col-md-3">
                        <a href="#" id="annulerBtn" class="btn btn-danger">Annuler</a>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>


<script>
    $(function() {
        let $ajouterBtn = $("#ajouterBtn");
        let $annulerBtn = $("#annulerBtn");
        let $ajouterForm = $("#ajouterForm");

        $ajouterBtn.on('click', function() {
            $ajouterForm.show();
            $ajouterBtn.hide();
            return false;
        });
        $annulerBtn.on('click', function() {
            $ajouterForm.hide();
            $ajouterBtn.show();
            return false;
        });

        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });

</script>
