<?php

use Formation\Entity\Db\Formation;
use Formation\Entity\Db\Module;
use Formation\Entity\Db\Session;
use Formation\Provider\Privilege\FormationPrivileges;
use Formation\Provider\Privilege\ModulePrivileges;

/**
 * @see \Formation\Controller\ModuleController::afficherAction()
 * @var Module $module
 */

$pageTitle = 'Affichage du module : ' . $module->getLibelle();
$this->headTitle($pageTitle);

$canModifierModule      = $this->isAllowed(ModulePrivileges::getResourceId(ModulePrivileges::MODULE_MODIFIER));

$canAfficherFormation     = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::FORMATION_AFFICHER));

/** @var Formation[] $formations */
$formations = $module->getFormations()->toArray();
usort($formations, function(Formation $a, Formation $b) { return $a->getLibelle() > $b->getLibelle();});
?>

<h1 class="page-header">
    <?php echo $pageTitle; ?>
</h1>

<div class="row">
    <div class="col-md-8">

        <h2> Informations sur le module </h2>

        <dl class="dl-horizontal">
            <dt> Libellé </dt>
            <dd>
                <?php echo $module->getLibelle(); ?>
            </dd>
            <?php if ($module->getDescription()) : ?>
                <dt> Description du module </dt>
                <dd> <?php echo $module->getDescription(); ?> </dd>
            <?php endif ?>
            <dt> Nombre de formations associées</dt>
            <dd>
                <?php echo count($formations); ?>
            </dd>
        </dl>
    </div>
    <div class="pull-right">
        <?php if ($canModifierModule) : ?>
            <?php /** @see \Formation\Controller\FormationController::modifierAction() */?>
            <a class="btn btn-primary ajax-modal" data-event="modification"
               href="<?php echo $this->url('formation/module/modifier', ['module' => $module->getId()], [], true); ?>"
            >
                <span class="glyphicon glyphicon-pencil"></span>
                Modifier les informations
            </a>
        <?php endif; ?>
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        <h2> Liste des formations </h2>
    </div>
    <div class="pull-right">
    </div>
</div>

<table class="table table-condensed">
    <thead>
    <tr>
        <th>Libelle</th>
        <th>Sessions</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($formations as $formation) : ?>
        <tr>
            <td> <?php echo $formation->getLibelle(); ?> </td>
            <td>
                <ul>
                <?php /** @var Session $session */ ?>
                <?php foreach ($formation->getSessions() as $session) : ?>
                    <li>
                        <?php echo ($session->getDateDebut())?$session->getDateDebut()->format('d/m/Y'):"---"; ?> &Rightarrow;
                        <?php echo ($session->getDateFin())?$session->getDateFin()->format('d/m/Y'):"---"; ?>
                    </li>
                <?php endforeach; ?>
                </ul>
            </td>
            <td>
                <?php if ($canAfficherFormation) : ?>
                    <?php /** @see \Formation\Controller\FormateurController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('formation/formation/afficher', ['formation' => $formation->getId()], [], true); ?>">
                        <span class="glyphicon glyphicon-eye-open"></span>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>


