<?php

use Formation\Entity\Db\Formation;
use Formation\Entity\Db\Module;
use Formation\Entity\Db\Session;
use Formation\Provider\Privilege\FormationPrivileges;
use Formation\Provider\Privilege\ModulePrivileges;

/**
 * @see \Formation\Controller\ModuleController::afficherAction()
 * @var Module $module
 */

$pageTitle = 'Affichage du module : ' . $module->getLibelle();
$this->headTitle($pageTitle);

$canIndexModule      = false && $this->isAllowed(ModulePrivileges::getResourceId(ModulePrivileges::MODULE_INDEX));
$canModifierModule      = $this->isAllowed(ModulePrivileges::getResourceId(ModulePrivileges::MODULE_MODIFIER));

$canAfficherFormation     = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::FORMATION_AFFICHER));

/** @var Formation[] $formations */
$formations = $module->getFormations()->toArray();
usort($formations, function(Formation $a, Formation $b) { return $a->getLibelle() > $b->getLibelle();});
?>

<h1 class="page-header">
    <?php echo $pageTitle; ?>
</h1>

<h2> Informations sur le module </h2>
<dl>
    <dt> Libellé </dt>
    <dd>
        <?php echo $module->getLibelle(); ?>
    </dd>
    <?php if ($module->getDescription()) : ?>
        <dt> Description du module </dt>
        <dd> <?php echo $module->getDescription(); ?> </dd>
    <?php endif ?>
    <?php if ($module->getLien()) : ?>
        <dt> Lien vers la fiche </dt>
        <dd> <a href="<?php echo $module->getLien(); ?>" target="_blank"><?php echo $module->getLien(); ?></a> </dd>
    <?php endif ?>
</dl>

<div>
    <?php if ($canIndexModule) : ?>
        <?php /** @see \Formation\Controller\FormationController::indexAction() */?>
        <a class="action"
           href="<?php echo $this->url('formation/module', [], [], true); ?>"
        >
            <span class="icon icon-retour"></span>
            Retour à la liste des modules
        </a>
    <?php endif; ?>
    <?php if ($canModifierModule) : ?>
        <?php /** @see \Formation\Controller\FormationController::modifierAction() */?>
        <a class="btn btn-primary ajax-modal" data-event="modification"
           href="<?php echo $this->url('formation/module/modifier', ['module' => $module->getId()], [], true); ?>"
        >
            <span class="icon icon-editer"></span>
            Modifier les informations
        </a>
    <?php endif; ?>
</div>

<h2>
    Liste des formations associées au module
    <span class="badge bg-info"><?php echo count($formations); ?></span>
</h2>

<div>
    <a
        <?php /** @see \Formation\Controller\FormationController::ajouterAction() */ ?>
            href="<?php echo $this->url('formation/formation/ajouter', ['module' => $module->getId()], [], true); ?>"
            class="btn btn-primary ajax-modal" data-event="modification">
        <span class="icon icon-ajouter"></span>
        Ajouter une formation
    </a>
</div>

<table class="table table-condensed table-hover">
    <thead>
    <tr>
        <th>Libelle</th>
        <th>Sessions</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($formations as $formation) : ?>
        <tr>
            <td> <?php echo $formation->getLibelle(); ?> </td>
            <td>
                <ul>
                <?php /** @var Session $session */ ?>
                <?php foreach ($formation->getSessions() as $session) : ?>
                    <li>
                        <?php echo ($session->getDateDebut())?$session->getDateDebut()->format('d/m/Y'):"---"; ?> &Rightarrow;
                        <?php echo ($session->getDateFin())?$session->getDateFin()->format('d/m/Y'):"---"; ?>
                    </li>
                <?php endforeach; ?>
                </ul>
            </td>
            <td>
                <?php if ($canAfficherFormation) : ?>
                    <?php /** @see \Formation\Controller\FormateurController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('formation/formation/afficher', ['formation' => $formation->getId()], [], true); ?>">
                        <span class="icon icon-voir"></span>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>


