<?php

/**
 * @see \Formation\Controller\ModuleController::catalogueAction()
 * @var array $catalogue
 */

use Formation\Entity\Db\Formation;
use Formation\Entity\Db\Session;
use Formation\Provider\Privilege\FormationPrivileges;


$canFormationAfficher = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::FORMATION_AFFICHER));
?>

<h1 class="page-header">
    Catalogue des formations
</h1>

<?php foreach ($catalogue as $key => $element) : ?>
        <table class="table table-sm">
        <thead>
            <tr>
                <th class="formation-module" colspan="4">
                    <?php if ($element["module"] !== null) : ?>
                        <?php echo $element["module"]->getLibelle(); ?>
                    <?php else : ?>
                        Formations non liées à un module
                    <?php endif ; ?>
                </th>
            </tr>
        </thead>
        <tbody>
    <?php if (empty($element['formations'])) : ?>
        <tr class="formation-vide"><td colspan="4">Aucune formation</td></tr>
    <?php else : ?>
        <?php /** @var Formation $formation */ ?>
        <?php foreach ($element['formations'] as $formation) : ?>
        <tr>
            <td class="formation-libelle">
                <?php if ($canFormationAfficher) : ?>
                <a
                        href="<?php echo $this->url('formation/formation/afficher', ['formation' => $formation->getId()], [], true); ?>"
                        title="Accéder à la formation [<strong><?php echo $formation->getLibelle(); ?></strong>]" data-bs-toggle="tooltip" data-bs-html="true"
                >
                    <?php echo $formation->getLibelle(); ?>
                </a>
                <?php else : ?>
                    <?php echo $formation->getLibelle(); ?>
                <?php endif; ?>
            </td>
            <td class="formation-site">
                    <?php echo $this->site($formation); ?>
            </td>
            <td class="formation-responsable">
                <?php if ($formation->getResponsable() !== null) : ?>
                    <?php echo $formation->getResponsable()->getNomComplet(); ?>
                <?php else : ?>
                    N.C.
                <?php endif; ?>
            </td>
            <td class="formation-infos">
                <ul>
                <?php /** @var Session $session */ ?>
                <?php foreach ($formation->getSessions() as $session) : ?>
                    <li>
                        <?php if ($session->getDateDebut() AND $session->getDateFin()) : ?>
                            <?php echo $session->getDateDebut()->format('d/m/Y à H:i'); ?> &rightarrow; <?php echo $session->getDateFin()->format('d/m/Y à H:i'); ?>
                        <?php else : ?>
                            À déterminer
                        <?php endif; ?>
                        <br/>
                        <strong>Modalité :</strong> <?php echo $this->modalite($session); ?>
                        <?php if ($session->getDateDebut() AND $session->getDateFin()) : ?>
                            <br/>
                            <strong>Durée :</strong> <?php echo $session->getDuree(); ?> h.
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
                </ul>
            </td>
        </tr>
        <?php endforeach; ?>
    <?php endif; ?>
        </tbody>
        </table>
<?php endforeach; ?>
