<?php

use Formation\Entity\Db\Module;
use Formation\Provider\Privilege\ModulePrivileges;

/**
 * @see \Formation\Controller\ModuleController::indexAction()
 * @var Module[] $modules
 * @var array $filtres
 * @var array $listings
 */

$this->headTitle('Liste des modules de formation');


$canAfficherModule      = $this->isAllowed(ModulePrivileges::getResourceId(ModulePrivileges::MODULE_AFFICHER));
$canAjouterModule       = $this->isAllowed(ModulePrivileges::getResourceId(ModulePrivileges::MODULE_AJOUTER));
$canHistoriserModule    = $this->isAllowed(ModulePrivileges::getResourceId(ModulePrivileges::MODULE_HISTORISER));
$canSupprimerModule     = $this->isAllowed(ModulePrivileges::getResourceId(ModulePrivileges::MODULE_SUPPRIMER));


?>

<h1 class="page-header">
    Liste des modules de formation
</h1>


<?php echo $this->partial('partial/filtre', [ 'filtres' => $filtres, 'listings' => $listings ]); ?>


<?php if ($canAjouterModule) : ?>
    <a
        <?php /** @see \Formation\Controller\ModuleController::ajouterAction() */ ?>
        href="<?php echo $this->url('formation/module/ajouter', [], [], true); ?>"
        class="btn btn-primary action ajax-modal" data-event="modification">
        <span class="icon icon-ajouter"></span>
        Ajouter un module
    </a>
<?php endif; ?>

<table class="table table-sm table-hover">
    <thead>
        <tr>
            <th> Libellé </th>
            <th> #Formation </th>
            <th> Action </th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($modules as $module): ?>
        <tr>
            <td <?php if ($module->estHistorise()) echo " class='historise' "; ?>>
                <?php echo $module->getLibelle(); ?>
                <?php if ($module->getDescription() !== null AND trim($module->getDescription()) !== null) : ?>
                    <span class="icon icon-info"
                          title="<?php echo $module->getDescription(); ?>" data-bs-toggle="tooltip" data-bs-html="true"

                    ></span>
                <?php endif; ?>

            </td>
            <td> <?php echo count($module->getFormations()); ?> </td>
            <td>
                <?php if ($canAfficherModule) : ?>
                    <?php /** @see \Formation\Controller\ModuleController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('formation/module/afficher', ['module' => $module->getId()], [], true); ?>"
                       title="afficher le module de formation #<?php echo $module->getId(); ?>"
                       data-bs-toggle="tooltip" data-bs-html="true">
                        <span class="icon icon-voir"></span>
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriserModule) : ?>
                    <?php if ($module->estNonHistorise()) : ?>
                        <?php /** @see \Formation\Controller\ModuleController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('formation/module/historiser', ['module' => $module->getId()], [], true); ?>"
                           title="Historiser le module de  formation #<?php echo $module->getId(); ?>"
                           data-bs-toggle="tooltip" data-bs-html="true">
                            <span class="icon icon-historiser"></span>
                        </a>
                    <?php else : ?>
                        <?php /** @see \Formation\Controller\ModuleController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url('formation/module/restaurer', ['module' => $module->getId()], [], true); ?>"
                           title="Restaurer le module de  formation #<?php echo $module->getId(); ?>"
                           data-bs-toggle="tooltip" data-bs-html="true">
                            <span class="icon icon-restaurer"></span>
                        </a>
                    <?php endif; ?>
                <?php endif; ?>

                <?php if ($canSupprimerModule) : ?>
                    <?php /** @see \Formation\Controller\ModuleController::supprimerAction() */?>
                    <a href="<?php echo $this->url('formation/module/supprimer',['module' => $module->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification"
                       title="Suppression du module de formation #<?php echo $module->getId(); ?>" data-bs-toggle="tooltip" data-bs-html="true">
                        <span class="icon icon-detruire"></span>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>



<script>
    $(function () {
        $('[data-bs-toggle="tooltip"]').tooltip({});
    });
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });

    });
</script>
