<?php

/**
 * @var string[] $filtres
 * @var array $listings
 */

?>

<div class="card bg-default">
    <div class="card-header">
        <span class="icon icon-filter"></span>
        Filtre des formations
    </div>
    <div class="card-body">
        <form id="filter" method="get" action="">

            <div class="row">
                <!-- Site ------------------------------------------------------------------------------------------------->
                <div class="col-md-4">
                    <label class="form-label" for="site">Site :</label>
                    <select name="site" id="site" class="form-control selectpicker" data-live-search="true">
                        <option value=""> Tous les sites </option>
                        <?php foreach ($listings['sites'] as $site_) : ?>
                            <option value="<?php echo $site_->getCode(); ?>"
                                    <?php if ($site_->getCode() === $filtres['site']) echo " selected "; ?>
                            >
                                <?php echo $site_->getLibelle(); ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="col-md-4">
                    <label class="form-label" for="structure">Structures :</label>
                    <select name="structure" id="structure" class="form-control selectpicker" data-live-search="true">
                        <option value=""> Tous les structures </option>
                        <?php foreach ($listings['structures'] as $structure_) : ?>
                            <option value="<?php echo $structure_->getId(); ?>"
                                <?php if ($structure_->getId() == $filtres['structure']) echo " selected "; ?>
                            >
                                <?php echo $structure_->getLibelle(); ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="col-md-4">
                    <label class="form-label" for="libelle">Libellé : </label>
                    <input class="form-control" type="text" name="libelle" id="libelle" <?php if ($filtres['libelle'] !== null AND $filtres['libelle'] !== '') echo " value='".$filtres['libelle']."' "; ?>/>
                </div>
                <div class="col-md-4">
                    <label class="form-label" for="responsable">Responsable :</label>
                    <select name="responsable" id="responsable" class="form-control selectpicker" data-live-search="true">
                        <option value=""> Tous les responsables </option>
                        <?php foreach ($listings['responsables'] as $responsable_) : ?>
                            <option value="<?php echo $responsable_->getId(); ?>"
                                <?php if ($responsable_->getId() == $filtres['responsable']) echo " selected "; ?>
                            >
                                <?php echo $responsable_->getNomComplet(); ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="col-md-4">
                    <label class="form-label" for="modalite">Modalité :</label>
                    <select name="modalite" id="modalite" class="form-control selectpicker" data-live-search="true">
                        <option value=""> Tous les modalités </option>
                        <option value="P" <?php if ("P" == $filtres['modalite']) echo " selected "; ?>> Présentielle </option>
                        <option value="D" <?php if ("D" == $filtres['modalite']) echo " selected "; ?>> Distancielle </option>
                    </select>
                </div>

                <div>
                    <button type="button" id="filter" class="btn btn-primary filter-action">
                        <span class="icon icon-filter" aria-hidden="true"></span> Filtrer
                    </button>
                    <button type="button" id="reset" class="btn btn-primary filter-action">
                        <span class="icon icon-delete" aria-hidden="true"></span> R.A.Z.
                    </button>
                </div>

            </div>
        </form>

    </div>
</div>

<script>
    $('button#reset').click(function (e) {
        e.preventDefault();
        window.location = '?';
    });
    $('button#filter').click(function () {
        $('form#filter').submit();
    });
</script>