<?php

/**
 * @var string[] $filtres
 * @var array $listings
 */

?>

<div class="panel panel-default">
    <div class="panel-heading">
        <span class="glyphicon glyphicon-filter"></span>
        Filtre des formations
    </div>
    <div class="panel-body">
        <form id="filter" method="get" action="">

            <div class="row">
                <!-- Site ------------------------------------------------------------------------------------------------->
                <div class="col-md-4">
                    <label for="site">Site :</label>
                    <select name="site" id="site" class="selectpicker" data-live-search="true">
                        <option value=""> Tous les sites </option>
                        <?php foreach ($listings['sites'] as $site_) : ?>
                            <option value="<?php echo $site_->getCode(); ?>"
                                    <?php if ($site_->getCode() === $filtres['site']) echo " selected "; ?>
                            >
                                <?php echo $site_->getLibelle(); ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>

                <!-- structure -------------------------------------------------------------------------------------------->
                <div class="col-md-4">
                    <label for="structure">Structures :</label>
                    <select name="structure" id="structure" class="selectpicker" data-live-search="true">
                        <option value=""> Tous les structures </option>
                        <?php foreach ($listings['structures'] as $structure_) : ?>
                            <option value="<?php echo $structure_->getId(); ?>"
                                <?php if ($structure_->getId() == $filtres['structure']) echo " selected "; ?>
                            >
                                <?php echo $structure_->getLibelle(); ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>

            <br/>

            <div class="row">

                <!-- libelle du module ------------------------------------------------------------------------------------>
                <div class="col-md-4">
                    <label for="libelle">Libellé : </label>
                    <input type="text" name="libelle" id="libelle" <?php if ($filtres['libelle'] !== null AND $filtres['libelle'] !== '') echo " value='".$filtres['libelle']."' "; ?>/>
                </div>

                <!-- Responsable ------------------------------------------------------------------------------------------>
                <div class="col-md-4">
                    <label for="responsable">Responsable :</label>
                    <select name="responsable" id="responsable" class="selectpicker" data-live-search="true">
                        <option value=""> Tous les responsables </option>
                        <?php foreach ($listings['responsables'] as $responsable_) : ?>
                            <option value="<?php echo $responsable_->getId(); ?>"
                                <?php if ($responsable_->getId() == $filtres['responsable']) echo " selected "; ?>
                            >
                                <?php echo $responsable_->getNomComplet(); ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>

                <!-- modalité --------------------------------------------------------------------------------------------->
                <div class="col-md-4">
                    <label for="modalite">Modalité :</label>
                    <select name="modalite" id="modalite" class="selectpicker" data-live-search="true">
                        <option value=""> Tous les modalités </option>
                        <option value="P" <?php if ("P" == $filtres['modalite']) echo " selected "; ?>> Présentielle </option>
                        <option value="D" <?php if ("D" == $filtres['modalite']) echo " selected "; ?>> Distancielle </option>
                    </select>
                </div>
            </div>

            <br/>

            <div class="row">
                <div class="pull-right">
                    <button type="button" id="filter" class="btn btn-primary filter-action">
                        <span class="glyphicon glyphicon-filter" aria-hidden="true"></span> Filtrer
                    </button>
                    <button type="button" id="reset" class="btn btn-primary filter-action">
                        <span class="glyphicon glyphicon-erase" aria-hidden="true"></span> R.A.Z.
                    </button>
                </div>
            </div>

        </form>

    </div>
</div>


<style>
    .filter-action {
        width: 20rem;
        margin: 0 1rem;
    }

    form#filter label {
        width: 10rem;
    }
</style>

<script>
    $('button#reset').click(function (e) {
        e.preventDefault();
        window.location = '?';
    });
    $('button#filter').click(function () {
        $('form#filter').submit();
    });
</script>