<?php

namespace Substitution;

use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var \Doctrine\DBAL\Result $result
 * @var int $count
 *
 * @see \Substitution\Controller\IndexController::structureAction()
 */
?>

<?php echo $this->partial('substitution/doublon/_partial/liste', [
    'type' => 'structure',
    'result' => $result,
    'count' => $count,
    'attributes' => ['code' => 'Code'],
    'routeName' => null,
    'routeParamName' => null,
]); ?>
