<?php

namespace Admission\Hydrator\Financement;

use Doctrine\Laminas\Hydrator\DoctrineObject;

/**
 * @author Unicaen
 */
class FinancementHydrator extends DoctrineObject
{
    public function extract(object $object): array
    {
        return parent::extract($object); // TODO: Change the autogenerated stub
    }

    public function hydrate(array $data, object $object): object
    {
        //Si la case contratDoctoral est décochée, on met à null les valeurs des champs reliés
        if (isset($data["contratDoctoral"]) && !$data["contratDoctoral"]) {
            $data["employeurContrat"] = null;
        }

        return parent::hydrate($data, $object); // TODO: Change the autogenerated stub
    }

}