<?php

use Application\Entity\Db\Role;
use Application\Entity\Db\These;

/**
 * @var These  $these
 * @var Role $role
 * @var string $url
 */
?>

<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application <?php echo $this->appInfos()->nom ?>.
</p>
<p>
    Vous êtes informé-e que toutes les personnes ayant le rôle &laquo; <?php echo $role->getLibelle() ?> &raquo; sur la thèse de
    <?php echo $these->getDoctorant() ?> ont validé les corrections de la thèse.
</p>
<p>
    Cliquez <a href="<?php echo $this->url('these/validation-these-corrigee', ['these' => $these->getId()], ['force_canonical' => true]) ?>">ici</a>
    pour accéder à l'application <?php echo $this->appInfos()->nom ?>.
</p>