<?php

use Application\Entity\Db\These;

/**
 * @see \Application\Service\Notification\NotifierService::triggerValidationDepotTheseCorrigee()
 * @var These  $these
 * @var string $message
 * @var string $url
 */
?>

<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application <?php echo $this->appInfos()->nom ?>.
</p>
<p>
    Vous êtes informé-e que <?php echo $these->getDoctorant() ?> a déposé une version corrigée de sa thèse
    et que votre validation est attendue.
</p>
<p>
    Cliquez <a href="<?php echo $url ?>">ici</a>
    pour accéder à l'application <?php echo $this->appInfos()->nom ?>.
</p>

<?php if (isset($message)): ?>
    <p><?php echo $message ?></p>
<?php endif ?>

