<?php

use Application\Entity\Db\Utilisateur;
use Application\Entity\Db\UtilisateurToken;

/**
 * @var Utilisateur $utilisateur
 * @var UtilisateurToken $token
 * @var string $lien
 */

?>
<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application <?php echo $this->appInfos()->nom ?>.
</p>
<p>
    Un jeton d'authentification vient d'être créé.
    Celui-ci vous permettra de vous authentifier à <?php echo $this->appInfos()->nom ?> par un clic sur le lien fourni ci-dessous.
</p>
<a href="<?php echo $lien; ?>" title="Connexion à SyGAL grâce au token #<?php echo $token->getId(); ?>">
    Connexion à SyGAL grâce au token #<?php echo $token->getId(); ?>
</a>.

<p>
    Ce token expirera le <?php echo $token->getExpiredOnToString(); ?>.
</p>
