<?php

use Application\Entity\Db\These;
use Application\Notification\ValidationPageDeCouvertureNotification;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var These       $these
 * @var bool        $isValidation
 *
 * @see ValidationPageDeCouvertureNotification
 */

$appli = $this->appInfos()->nom;
?>

<p>
    <?php echo $these->getDoctorant() ?>,
</p>
<p>
    <em>Ceci est un mail envoyé automatiquement par l'application <?php echo $appli ?>.</em>
</p>

<?php if ($isValidation): ?>
<p>
    Vous êtes informé-e que l'application <?php echo $appli ?> est à présent en mesure de produire la page
    de couverture de votre thèse automatiquement à partir des informations liées à votre dossier de soutenance
    validé par le Président de l'Université.
</p>
<p>
    Par conséquent, en tant que doctorant, vous pouvez désormais procéder au dépôt de votre thèse dans l'application.
    <strong><u> Ce dépôt numérique 1 mois avant la date de soutenance, est un préalable obligatoire </u> à l'autorisation
    de soutenance qui sera accordée par le Président de l'Université au vu des rapports de pré soutenance. </strong>
</p>
<p>
    La page de couverture (page recto) étant produite automatiquement par l'application <?php echo $appli ?>, vous
    n'aurez pas à concevoir et inclure cette page de couverture dans le fichier de thèse que vous déposerez dans l'application.
</p>
<p>
    IMPORTANT :
    Vous pouvez envoyer votre manuscrit de thèse à vos rapporteurs et membres de votre jury de soutenance. Votre directeur
    doit contacter les rapporteurs pour leur indiquer la date de retour de leur rapport, au plus tard 3 semaines avant
    la date de soutenance, accompagné de leur engagement d'impartialité signé.(téléchargeable sur le portail de la recherche -
    <a href="http://recherche.unicaen.fr/etudes-doctorales/soutenir-sa-these/">http://recherche.unicaen.fr/etudes-doctorales/soutenir-sa-these/</a>).
</p>
<?php else: ?>
<p>
    Vous êtes informé-e que l'application <?php echo $appli ?> n'est plus en mesure de produire la page
    de couverture de votre thèse automatiquement à partir des informations de scolarité.
</p>
<p>
    Par conséquent, le processus de dépôt de votre thèse dans l'application est temporairement bloqué. <br>
    Vous recevrez un mail lorsque <?php echo $appli ?> sera de nouveau en mesure de produire la page de couverture
    de manière satisfaisante.
</p>
<?php endif ?>

<p>
    Votre directeur de thèse est en copie de ce mail.
</p>
<p>
    <a href="<?php echo $this->url('home', [], ['force_canonical' => true]) ?>"
    >Accéder à l'application <?php echo $appli ?></a>.
</p>
