<?php

use These\Entity\Db\These;

/**
 * @see \Depot\Service\Notification\DepotNotificationFactory::createNotificationValidationDepotTheseCorrigee()
 * @var These  $these
 * @var string $url
 */
?>

<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application <?php echo $this->appInfos()->nom ?>.
</p>
<p>
    Vous êtes informé-e que <?php echo $these->getDoctorant() ?> a déposé une version corrigée de sa thèse
    et en tant que Président du jury de cette thèse votre validation est attendue.
</p>
<p>
    Cliquez <a href="<?php echo $url ?>">ici</a> pour accéder à l'application <?php echo $this->appInfos()->nom ?> et
    valider le second dépôt du manuscrit (téléchargeable sur cette même page).
</p>

<p>
    Si vous n'avez pas de compte dans l'application <?php echo $this->appInfos()->nom ?>,
    un second mail vient de vous être envoyé afin d'initialiser celui-ci. <br/>
    Si c'est le cas, veuillez initialiser celui-ci et revenir sur le lien ci-dessus.
</p>

<?php if (isset($message)): ?>
    <p><?php echo $message ?></p>
<?php endif ?>

