<?php

use Application\Entity\Db\Acteur;
use Application\Entity\Db\These;

/**
 * @see Application\Notification\PasDeMailPresidentJury
 * @var These $these
 * @var Acteur $president
 */

?>
<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application <?php echo $this->appInfos()->nom ?>.
</p>
<p>
    Le président du jury, <?php echo ($president)?$president->getIndividu()->getNomComplet():"PRESIDENT MANQUANT"; ?>, n'a pas d'email de renseigner dans <?php echo $this->appInfos()->nom ?>.
    <?php echo $this->appInfos()->nom ?> n'a pas pu créer de compte pour celui-ci et par conséquent il ne pourra pas valider les corrections.
    Il présidait le jury de la la thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(); ?> intitulée <?php echo $these->getTitre(); ?>
</p>

<p>
    Vous pouvez renseigner celle-ci dans l'interface de gestion des présidents du jury (Administration > Présidents du jury).
</p>
