<?php

/**
 * @see \HDR\Controller\HDRSaisieController::modifierAction()
 *
 * @var HDR $hdr
 * @var Form $form
 * @var string $formPartial
 * @var ?array $errorMessages
 */

use HDR\Entity\Db\HDR;
use Laminas\Form\Form;

$this->headTitle($this->translate($hdr->getCandidat()->getIndividu()->getNomUsuel()." Modification"));

$form->prepare();
?>

<h1 class="page-header">
    <?php echo $this->translate("Modification de la HDR de") . " {$hdr->getCandidat()}" ?>
</h1>

<a type="button" class="btn btn-primary mb-4"
   href="<?php echo $this->url('hdr/identite', ['hdr' => $hdr->getId()], [], true) ?>"
>
    <span class="icon icon-retour"></span>
    <?php echo $this->translate("Retourner à la HDR"); ?>
</a>

<?php if(isset($errorMessages) && is_array($errorMessages)){ ?>
    <div class="alert alert-danger">
        Certains champ(s) du formulaire n'ont pas pu être validé : <br><br>
        <ul>
            <?php
            foreach ($errorMessages as $key => $messageGroup) { ?>
                <li>
                    <ul>
                        Onglet <?php echo $key; ?> :
                        <?php foreach ($messageGroup as $name => $errors) { ?>

                            <?php if (is_array($errors)) {
                                foreach ($errors as $errorKey => $errorMessage) {
                                    echo "<li><b>'$name'</b> : $errorMessage<br></li>";
                                }
                            } ?>
                        <?php } ?>
                    </ul>
                </li>
                <br>
            <?php } ?>
        </ul>
    </div>
<?php } ?>

<ul class="nav nav-tabs" role="tablist">
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="informations-tab" data-bs-toggle="tab" data-bs-target="#informations" type="button" role="tab" aria-controls="informations" aria-selected="true"><?php echo $form->get("generalites")->getLabel();?></button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="structures-tab" data-bs-toggle="tab" data-bs-target="#structures" type="button" role="tab" aria-controls="structures" aria-selected="false"><?php echo $form->get("structures")->getLabel();?></button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="direction-tab" data-bs-toggle="tab" data-bs-target="#direction" type="button" role="tab" aria-controls="direction" aria-selected="false"><?php echo $form->get("direction")->getLabel();?></button>
    </li>
<!--    <li class="nav-item" role="presentation">-->
<!--        <button class="nav-link" id="encadrements-tab" data-bs-toggle="tab" data-bs-target="#encadrements" type="button" role="tab" aria-controls="encadrements" aria-selected="false">--><?php //echo $form->get("encadrements")->getLabel();?><!--</button>-->
<!--    </li>-->
</ul>

<?php
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>

<div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="informations" role="tabpanel" aria-labelledby="informations-tab">
        <?php echo $this->partial('hdr/hdr-saisie/partial/generalites'); ?>
    </div>
    <div class="tab-pane fade" id="direction" role="tabpanel" aria-labelledby="direction-tab">
        <?php echo $this->partial('hdr/hdr-saisie/partial/direction'); ?>
    </div>
    <div class="tab-pane fade" id="structures" role="tabpanel" aria-labelledby="structures-tab">
        <?php echo $this->partial('hdr/hdr-saisie/partial/structures'); ?>
    </div>
<!--    <div class="tab-pane fade" id="encadrements" role="tabpanel" aria-labelledby="encadrements-tab">-->
<!--        --><?php //echo $this->partial('hdr/hdr-saisie/partial/encadrement'); ?>
<!--    </div>-->
</div>

<?php echo $this->formHidden($form->get('security')); ?>
<?php echo $this->formControlGroup($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>

<style>
    span.erase-acteur {
        cursor: pointer;
    }
</style>