<?php

/**
 * @see \Application\Controller\EcoleDoctoraleController::informationAction()
 * @var EcoleDoctorale $ecole
 * @var array $roleListing (string => int)
 * @var array(string => string[]) $individuListing
 */

use Application\Entity\Db\EcoleDoctorale;
use Application\Entity\Db\TypeStructure;

$this->headTitle('Details de l\'école doctorale ['.$ecole->getLibelle().']');

$canEdit = true;
$canAddRole = true;
?>

<h1 class="page-header">
    Details de l'école doctorale [  <?php echo $ecole->getLibelle(); ?> ]
</h1>

<a href="<?php echo $this->url('ecole-doctorale', [], [], true); ?>"
   class="btn btn-primary action"
   >
    <span class="glyphicon glyphicon-th-list"></span> Index des écoles doctorales
</a>

<?php if($canEdit): ?>
    <a href="<?php echo $this->url('ecole-doctorale/modifier', ['ecoleDoctorale'=> $ecole->getStructure()->getId()], [], true); ?>"
       class="btn btn-primary action"
    >
        <span class="glyphicon glyphicon-pencil"></span> Modifier l'école doctorale
    </a>
<?php endif; ?>

<?php if ($canAddRole && empty($roleListing)): ?>
    <a
            href="<?php echo $this->url('structure/generer-roles-defauts',
                ['id' => $ecole->getStructure()->getId(), 'type' => TypeStructure::CODE_ECOLE_DOCTORALE], [], true);?>"
            class="btn btn-warning"
    >
        <span class="glyphicon glyphicon-refresh"></span>
        Générer rôles par défaut
    </a>
<?php endif; ?>



<div>
    <h2>
        Informations générales
    </h2>
    <div class="row">
        <div class="col-md-4">
            <img
                    id="logo"
                    style="max-width: 200px; max-height: 200px; border: 1px solid black; background-color: white;"
                    src="data:image/png;base64,<?php echo base64_encode($ecole->getLogoContent()); ?>"
            />
        </div>
        <div class="col-md-6">
            <dl>
                <dt> Libelle : </dt>    <dd>    <?php echo $ecole->getLibelle(); ?>     </dd>
                <dt> Sigle : </dt>      <dd>    <?php echo $ecole->getSigle(); ?>       </dd>
                <dt> Code : </dt>       <dd>    <?php echo $ecole->getCode(); ?>        </dd>
            </dl>
        </div>
</div>


<div>
    <h2>
        Rôles et membres
    </h2>
        <div class="row">
            <div class="col-md-6">
                <table class="table table-condensed">
                    <thead>
                    <tr>
                        <th> Libellé du rôles </th> <th> Effectifs </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($roleListing as $libelle => $count): ?>
                        <tr>
                            <td> <?php echo $libelle; ?> </td>
                            <td> <?php echo $count; ?> </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>

                </table>
            </div>


            <div class="col-md-6">
                <table class="table table-condensed">
                    <thead>
                    <tr>
                        <th> Dénomination </th> <th> Rôle </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($individuListing as $denomination => $roles): ?>
                        <?php foreach($roles as $role): ?>
                            <tr>
                                <td> <?php echo $denomination; ?> </td>
                                <td> <?php echo $role; ?> </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
</div>

<style>
    .action {
        width: 20em;
    }
</style>