<?php

/**
 * @see \Application\Controller\EcoleDoctoraleController::informationAction()
 * @var EcoleDoctorale $ecole
 * @var array          $roleListing     (string => int)
 * @var array          $individuListing (string => string[])
 * @var string         $logoContent
 */

use Application\Entity\Db\EcoleDoctorale;
use Application\Entity\Db\TypeStructure;
use Application\Provider\Privilege\StructurePrivileges;

$this->headTitle("École Doctorale '{$ecole->getStructure()->getCode()}'");

$canEdit = ($this->isAllowed(StructurePrivileges::getResourceId(StructurePrivileges::STRUCTURE_MODIFICATION_TOUTES_STRUCTURES))) ||
    ($this->isAllowed($ecole->getStructure(), StructurePrivileges::STRUCTURE_MODIFICATION_SES_STRUCTURES));
$canAddRole = $canEdit;
?>

<h1 class="page-header">
    École doctorale &laquo; <?php echo $ecole->getLibelle(); ?> &raquo;
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace() ?>

<div>
    <h2>
        Informations générales
    </h2>
    <div class="row">
        <div class="col-md-6">
            <dl>
                <dt> Libelle :</dt>
                <dd>    <?php echo $ecole->getLibelle(); ?>     </dd>
                <dt> Sigle :</dt>
                <dd>    <?php echo $ecole->getSigle(); ?>       </dd>
                <dt> Code :</dt>
                <dd>    <?php echo $ecole->getStructure()->getCode(); ?>        </dd>
            </dl>
        </div>
        <div class="col-md-4">
            <dl>
                <dt>Logo :</dt>
                <dd>
                    <img id="logo" style="max-width: 200px; max-height: 200px; background-color: white;"
                         src="data:image/png;base64,<?php echo base64_encode($logoContent); ?>"/>
                </dd>
            </dl>
        </div>
    </div>
    <div>
        <h2>
            Rôles et membres
        </h2>
        <div class="row">
            <div class="col-md-6">
                <table class="table table-condensed">
                    <thead>
                    <tr>
                        <th> Libellé du rôle</th>
                        <th> Effectif</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($roleListing as $libelle => $count): ?>
                        <tr>
                            <td> <?php echo $libelle; ?> </td>
                            <td> <?php echo $count; ?> </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>

                </table>
            </div>


            <div class="col-md-6">
                <table class="table table-condensed">
                    <thead>
                    <tr>
                        <th> Dénomination</th>
                        <th> Rôle</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($individuListing as $denomination => $roles): ?>
                        <?php foreach ($roles as $role): ?>
                            <tr>
                                <td> <?php echo $denomination; ?> </td>
                                <td> <?php echo $role; ?> </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<hr>

<?php if ($canAddRole && empty($roleListing)): ?>
    <a href="<?php echo $this->url('structure/generer-roles-defauts', [
        'id' => $ecole->getStructure()->getId(),
        'type' => TypeStructure::CODE_ECOLE_DOCTORALE], [], true); ?>"
       class="btn btn-warning"><span class="glyphicon glyphicon-cog"></span> Générer rôles par défaut</a>
<?php endif; ?>

<?php if ($canEdit): ?>
    <a href="<?php echo $this->url('ecole-doctorale/modifier', ['structure' => $ecole->getStructure()->getId()], [], true); ?>"
       class="btn btn-primary action"><span class="glyphicon glyphicon-pencil"></span> Modifier l'école doctorale
    </a>
<?php endif; ?>