<?php

use Application\Form\EcoleDoctoraleForm;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer        $this
 * @var string             $title
 * @var EcoleDoctoraleForm $form
 *
* @method string formControlGroup()
*/

$fcg = $this->formControlGroup();
?>

<?php echo $this->form()->openTag($form->prepare()->setAttribute('class', 'ecole-doctorale')) ?>
<?php echo $this->formHidden($form->get('id')) ?>
<?php echo $fcg($form->get('libelle')) ?>
<?php echo $fcg($form->get('sigle')) ?>
<div id="logo-div">
    <img
            style="max-width: 200px; max-height: 200px; border: 1px solid black; background-color: white;"
            src="data:image/png;base64,<?php echo base64_encode($form->getObject()->getLogoContent()); ?>"

    />
</div>

<?php echo $this->formElement($form->get('submit')) ?>
<?php echo $this->form()->closeTag() ?>

<!-- pour traduction -->
<?php
    $this->translate("Libellé :");
    $this->translate("Sigle :");
    $this->translate("Code :");
    $this->translate("Enregistrer");
?>