<?php

use Application\Form\EcoleDoctoraleForm;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer        $this
 * @var string             $title
 * @var EcoleDoctoraleForm $form
 *
* @method string formControlGroup()
*/

$fcg = $this->formControlGroup();
?>

<?php echo $this->form()->openTag($form->prepare()->setAttribute('class', 'ecole-doctorale')) ?>
<?php echo $this->formHidden($form->get('id')) ?>
<?php echo $fcg($form->get('libelle')) ?>
<?php echo $fcg($form->get('sigle')) ?>
<?php echo $fcg($form->get('sourceCode')) ?>

<div id="logo-div">
 <?php
    /** @var \Zend\Form\Element\File $logoFile */
    $logoFile = $form->get('cheminLogo');
    echo $this->formLabel($logoFile);
?>

    <?php
    $content = $form->getObject()->getLogoContent();
    if ($content === null) {
        $form->getObject()->setCheminLogo(null);
    }
    ?>
<table>
    <tr>
        <td>
            <img
                id="logo"
                style="max-width: 200px; max-height: 200px; border: 1px solid black; background-color: white;"
                src="data:image/png;base64,<?php echo base64_encode($form->getObject()->getLogoContent()); ?>"
            />
        </td>
        <td style="padding:20px;">
               <?php
                echo $this->formFile($logoFile);
                echo $this->formElementErrors($logoFile);
                ?>
            <br/>
            <a id="supprimer-logo" class="btn btn-danger" href="<?php echo $this->url('ecole-doctorale/supprimer-logo', ["ecoleDoctorale" => $form->getObject()->getStructure()->getId()]); ?>">
                <span class="glyphicon glyphicon-trash"></span>
                Supprimer le logo
            </a>
        </td>
    </tr>
</table>
</div>
<?php echo $this->formElement($form->get('submit')) ?>
<?php echo $this->form()->closeTag() ?>

<!-- pour traduction -->
<?php
    $this->translate("Libellé :");
    $this->translate("Sigle :");
    $this->translate("Code :");
    $this->translate("Enregistrer");
    $this->translate("Supprimer le logo");
    $this->translate("Logo de l'école doctorale :");
?>


<script>
    $(document).ready(function() {

        //remplacement dans la structure cible
        $("input[name='cheminLogo']").on("change", function () {

            var myFile = $("input[name='cheminLogo']").prop('files');
            console.log(myFile[0]);
            fr = new FileReader();
            fr.onload = function () {
                var content = fr.result;
                console.log(content);
                $('#logo').attr("src", content);
            };
            fr.readAsDataURL( myFile[0] );
        });
    });
</script>
