-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sygaldb.unicaen.fr;sid=SYGLPROD;port=1523

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON



CREATE OR REPLACE FUNCTION individu_haystack ( NOM_USUEL text, NOM_PATRONYMIQUE text, PRENOM1 text, EMAIL text, SOURCE_CODE text) RETURNS varchar AS $body$
BEGIN
    return trim(both str_reduce(
                NOM_USUEL || ' ' || PRENOM1 || ' ' || NOM_PATRONYMIQUE || ' ' || PRENOM1 || ' ' ||
                PRENOM1 || ' ' || NOM_USUEL || ' ' || PRENOM1 || ' ' || NOM_PATRONYMIQUE || ' ' ||
                EMAIL || ' ' ||
                SOURCE_CODE
        ));
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION individu_haystack ( NOM_USUEL text, NOM_PATRONYMIQUE text, PRENOM1 text, EMAIL text, SOURCE_CODE text) FROM PUBLIC;

