<?php

/**
 * @var \Application\View\Renderer\PhpRenderer $this
 * @var \Application\Entity\Db\Rapport $rapport
 * @var \RapportActivite\Service\Fichier\Exporter\PageValidationExportData $data
 *
 * @see \RapportActivite\Controller\RapportActiviteController::telechargerAction()
 */
?>

<!-- SECTION DU LOGO DE LA COMUE -------------------------------------------------------------------------------------->
<div style="text-align: center; margin-bottom: 30px;">
    <div class='logo-comue'>
        <?php if ($data->logoCOMUE !== null): ?>
            <img src="<?php echo $data->logoCOMUE ?>"/>
        <?php else: ?>
            <span style='background-color:red;'> COMUE ou logo de la COMUE non renseigné. </span>
        <?php endif; ?>
    </div>
</div>
<!-- --------------------------------------------------------------------------------------------------------------- -->

<div class='bandeau-these'>
    <?php echo mb_strtoupper($rapport->getTypeRapportLibelle()) ?>
</div>

<div class='bandeau-titre'>
    <?php echo $rapport->getFichier()->getNom() ?>
</div>

<div class='infos-doctorant'>
    <?php $validation = $rapport->getRapportValidationOfType() ?>
    Déposé le <?php echo ($rapport->getHistoModification() ?: $rapport->getHistoCreation())->format('d/m/Y H:i') ?>
    <br>
    <br>
    Validé par <?php echo $validation->getHistoCreateur() ?> le <?php echo $validation->getHistoCreation()->format('d/m/Y H:i') ?>
</div>

<br>
<br>
<br>

<div class='bandeau-these'>
    Thèse
</div>

<div class='infos-diplome'>
    <span class='larger-infos'>Pour obtenir le diplôme de doctorat </span>
    <br/>

    Spécialité
    <?php if ($data->specialite !== null): ?>
        <?php echo $data->specialite; ?>
    <?php else: ?>
        <span style='background-color:red;'> non renseignée </span>
    <?php endif; ?>
    <br/>

    Préparée au sein de
    <?php if ($data->etablissement !== null): ?>
        l'<?php echo $data->etablissement; ?>
    <?php else: ?>
        <span style='background-color:red;'> non renseigné </span>
    <?php endif; ?>
</div>


<div class='bandeau-titre'>
    <?php if ($data->titre !== null): ?>
        <?php echo $data->titre; ?>
    <?php else: ?>
        <span style='background-color:red;'> Aucun titre </span>
    <?php endif; ?>
    <br/>
</div>

<div class='infos-doctorant' style=''>
    <!--Présentée et soutenue par <br/>-->
    <?php if ($data->doctorant !== null): ?>
        <?php echo $data->doctorant; ?>
    <?php else: ?>
        <span style='background-color:red;'> Aucun doctorant </span>
    <?php endif; ?>
</div>


<!-- SECTION DES LOGOS EN BAS DE PAGE --------------------------------------------------------------------------------->
<div class="logos">
    <table style="border:none;" class="logos">
        <tr>
            <td>
                <?php if ($data->logoEtablissement): ?>
                    <img class="logo_small" src="<?php echo $data->logoEtablissement ?>"/>
                <?php else: ?>
                    <span style='background-color:red;'> Établissement d'inscription ou logo d'établissement non renseigné. </span>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($data->logoEcoleDoctorale): ?>
                    <img class="logo_small" src="<?php echo $data->logoEcoleDoctorale ?>"/>
                <?php else: ?>
                    <span style='background-color:red;'> École doctorale ou logo d'école doctorale non renseigné </span>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($data->logoUniteRecherche): ?>
                    <img class="logo_small" src="<?php echo $data->logoUniteRecherche ?>"/>
                <?php else: ?>
                    <span style='background-color:red;'> Unité de recherche ou logo d'unité de recherche non renseigné </span>
                <?php endif; ?>
            </td>
        </tr>
    </table>
</div>
<!-- --------------------------------------------------------------------------------------------------------------- -->