<?php
/** @var bool $canVerifierAdmission
 * @var FormControlGroup $fcg
 */

use Admission\Entity\Db\Verification;
use UnicaenApp\Form\View\Helper\FormControlGroup;

?>
<div class="row_sous_partie">
    <div class="title_sous_partie">
        <h2 class="titre_sous_partie">Commentaires</h2>
    </div>
    <?php if ($canVerifierAdmission) { ?>
        <div class="row observations_gestionnaire">
            <div class="col">
                <?php echo $fcg($fieldset->get('estComplet')) ?>
            </div>
            <div class="commentaires_gestionnaire">
                <?php echo $fcg($fieldset->get('commentaire')) ?>
            </div>
        </div>
    <?php }else{ ?>
        <div class="commentaires_gestionnaire">
            <div class="partie_etudiant">
                <?php
                /** @var Verification $verification */
                $verification = !empty($element) ? $elementVerification->first() : null;
                $nom = !empty($verification) ? $verification->getIndividu()->getNomUsuel() : null;
                $prenom = !empty($verification) ? $verification->getIndividu()->getPrenom() : null;
                $commentaire = !empty($verification) ? $verification->getCommentaire() : null ;
                $date_verification = !empty($verification) ? $verification->getHistoModification()->format('d/m/Y H:i') : null;
//                echo !empty($commentaire) ? "<p class='gestionnaire'>Par ".$nom." ".$prenom.", le ".$date_verification." </p><p> :  ".$commentaire." </p>" : "<p class='pas_de_commentaire'>Pas de commentaire renseigné par vos gestionnaires</p>";
                echo !empty($commentaire) ? "<p class='gestionnaire'>".$commentaire."<p class='text-muted text-sm info-commentaire'>(Par ".$nom." ".$prenom.", le ".$date_verification.")</p>" : "<p class='pas_de_commentaire'>Pas de commentaire renseigné par vos gestionnaires</p>";

                ?>
            </div>
        </div>
    <?php  } ?>
</div>