<?php
/** @var bool $canVerifierAdmission
 * @var Admission $admission
 * @var \Laminas\Form\Fieldset $fieldset
 * @var FormControlGroup $fcg
 */

use Admission\Entity\Db\Admission;
use Admission\Entity\Db\Verification;
use Admission\Provider\Privilege\AdmissionPrivileges;
use UnicaenApp\Form\View\Helper\FormControlGroup;

$canVerifierAdmission  = $this->isAllowed($admission, AdmissionPrivileges::ADMISSION_VERIFIER);
?>
<div class="admission-section-form">
    <div class="admission-section-title-container">
        <h2 class="admission-section-title">Commentaires<label class="admission-section-title-en">&nbsp; /  Comments</label></h2>
    </div>
    <?php if ($canVerifierAdmission) { ?>
        <div class="row observations-gestionnaire">
            <div class="col">
                <?php echo $fcg($fieldset->get('estComplet')) ?>
            </div>
            <div class="commentaires-gestionnaire">
                <div class="precisions-action-container">
                    <i class="fas fa-exclamation-circle"></i>
                    <p>
                        <?php echo $this->formlabel($fieldset->get('commentaire')) ?>
                    </p>
                </div>
                <?php echo $this->formtextarea($fieldset->get('commentaire')) ?>
            </div>
        </div>
    <?php }else{ ?>
        <div class="commentaires-gestionnaire">
            <div class="partie-etudiant">
                <?php
                /** @var Verification $verification */
                $verification = !empty($elementVerification) ? $elementVerification->first() : null;
                $nom = !empty($verification) ? $verification->getIndividu()->getNomUsuel() : null;
                $prenom = !empty($verification) ? $verification->getIndividu()->getPrenom() : null;
                $commentaire = !empty($verification) ? $verification->getCommentaire() : null ;
                $date_verification = !empty($verification) ? $verification->getHistoModification()->format('d/m/Y H:i') : null;
                $isComplet = !empty($verification) ? $verification->getEstComplet() : null ;
                if(!empty($commentaire)){
                    echo "<div class='col-lg-6 col-sm-12 verification-gestionnaire commentaire-gestionnaire'>".$commentaire."</div>";
                    echo "<div class='col-lg-6 col-sm-12 text-muted text-sm info-commentaire'>(Par ".$nom." ".$prenom.", le ".$date_verification.")</div>";
                }else{
                    if($isComplet === null){
                        echo "<p class='verification-gestionnaire aucune-action-effectuee-commentaire'>Aucune action n'a encore été effectuée sur cette étape par la/le gestionnaire de ce dossier d'admission</p>";
                    }elseif(!$isComplet && empty($commentaire)){
                        echo "<p class='verification-gestionnaire pas-de-commentaire-ajoute'>Cette étape est incomplète mais aucun commentaire n'a encore été ajouté par la/le gestionnaire de ce dossier d'admission</p>";
                    }else{
                        echo "<p class='verification-gestionnaire partie-complete'>Cette étape est notée comme complète par la/le gestionnaire de ce dossier d'admission</p>";
                    }
                }
                ?>
            </div>
        </div>
    <?php  } ?>
</div>
