<?php

use Application\Entity\Db\FichierThese;
use Application\Entity\Db\These;
use Application\Provider\Privilege\ThesePrivileges;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var These       $these
 * @var FichierThese $fichierTheseRetraite
 * @var string      $validerFichierRetraiteUrl
 * @var string      $contact
 */

const CERTIF_CONFORME_MODIFIED_EVENT = "CERTIF_CONFORME_MODIFIED_EVENT";
?>

<?php if ($fichierTheseRetraite && ($v = $fichierTheseRetraite->getFichier()->getValidite()) && $v->getEstValide() === true): ?>

    <div class="card box">

        <div class="card-header bg-info">
            <?php
            $version = $fichierTheseRetraite->getFichier()->getVersion();
            $estVersionCorrigee = $version->estVersionCorrigee();
            $heading = $estVersionCorrigee ? "Vérification de la thèse corrigée retraitée" : "Vérification de la thèse retraitée";

            $privilege = ThesePrivileges::THESE_SAISIE_CONFORMITE_VERSION_ARCHIVAGE_($version);
            $canEdit = $this->isAllowed($these, $privilege);
            ?>
            <h2 class="first"><?php echo $heading ?></h2>
        </div>

        <div class="card-body">

            <?php
            $certificationSaisie = $fichierTheseRetraite && $fichierTheseRetraite->getEstConforme() !== null;
            $certifieConforme = $certificationSaisie && $fichierTheseRetraite->getEstConforme();
            ?>

            <?php if ($certificationSaisie): ?>

                <?php
                $text = $certifieConforme ?
                    "Vous avez déclaré que la version retraitée est <strong>conforme</strong> et qu'elle peut être archivée en l'état." :
                    "Vous avez déclaré que la version retraitée n'est <strong>pas conforme</strong> et qu'elle ne peut pas être archivée en l'état.";
                $textClass = $certifieConforme ? 'text-success' : 'text-danger';
                ?>
                <p class="<?php echo $textClass ?> lead">
                    <span class="icon icon-ok"></span> <?php echo $text ?>
                </p>

            <?php elseif ($canEdit): ?>

                <p>
                    <strong>NB:</strong> Le retraitement du fichier peut avoir altéré votre thèse (police de
                    caractère,
                    url...). <br>
                    Après vérification, indiquez si vous le validez pour archivage.
                </p>

            <?php else: ?>

                <?php
                $msgCollector = $this->messageCollector(\Application\Assertion\BaseAssertion::class);
                $msgCollector->getMessengerHelper()->setContainerClassesToAdd('alert-danger');
                echo $msgCollector->render();
                ?>

            <?php endif ?>

            <?php if ($canEdit): ?>
                <p>
                    <a href="<?php echo $validerFichierRetraiteUrl ?>"
                       data-event="<?php echo CERTIF_CONFORME_MODIFIED_EVENT ?>"
                       class="btn <?php echo $certificationSaisie ? "btn-secondary" : "btn-primary" ?> ajax-modal"
                    ><span class="icon icon-edit"></span>
                        <?php echo $certificationSaisie ? "Modifier" : "Répondre" ?></a>
                </p>
            <?php endif ?>

            <?php if ($certificationSaisie): ?>
                <?php if (!$certifieConforme): ?>
                    <p>
                        Vous pouvez contacter <a href="mailto:<?php echo $contact ?>"><?php echo $contact ?></a>
                        pour obtenir de l'aide.
                    </p>
                <?php endif ?>
            <?php endif ?>


        </div>

    </div>

<?php endif ?>


<?php //echo $this->partial('next-step-box', ['these' => $these, 'etape' => WfEtape::CODE_VERIFICATION_VERSION_ARCHIVAGE]) ?>