<?php

use Application\Service\These\Filter\TheseTextFilter;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var TheseTextFilter $filter
 * @var array $queryParams
 */

$paramAttributes = $filter->getAttributes();
$paramName = $filter->getName();

$width = isset($paramAttributes['width']) ? $paramAttributes['width'] : 'fit';
$liveSearch = isset($paramAttributes['liveSearch']) ? (bool)$paramAttributes['liveSearch'] : false;

$value = $filter->getValue();
$text = $value['text'];
$criteria = $value['criteria'];

$title = htmlspecialchars(
    "<div class=\"these-search-input-help\">" .
    $this->translate("La recherche de texte porte sur les critères sélectionnés dans la liste déroulante ci-contre...") .
    "</div>"
);
?>

<div class="form-group">
    <label class="sr-only" for="search-input">Recherche d'une thèse (code, titre de la thèse ; code, nom, prénom de l'auteur) :</label>
    <div class="input-group">
        <div class="input-group-addon"><span class="glyphicon glyphicon-search"></span></div>
        <input type="search"
               value="<?php echo $text; ?>"
               name="text"
               class="form-control filter"
               id="search-input"
               placeholder="<?php echo $this->translate("Entrez 2 caractères au moins...");?>"
               data-content="<?php echo $title ?>">
        <div class="input-group-addon filter">
            <select multiple name="textCriteria[]" id="" class="selectpicker show-menu-arrow"
                    title="Sélectionnez un critère..."
                    data-selected-text-format="count"
                    data-count-selected-text="{0} critères sélectionnés"
                    data-actions-box="true"
                    data-header="Critères sur lesquels portera la recherche textuelle">
                <?php foreach (TheseTextFilter::CRITERIA as $value => $label): ?>
                <?php $isActive = in_array($value, $criteria); ?>
                    <option value="<?php echo $value ?>" <?php echo $isActive ? 'selected' : '' ?>><?php echo $label ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </div>
</div>

<script>
    $(function() {
        $("#search-input").popover({html: true, trigger: "hover", placement: "bottom"});
    });
</script>