<?php

use Application\Search\Filter\SearchFilter;
use Application\Search\Filter\SelectSearchFilter;
use Application\Service\These\Filter\TheseSelectFilter;
use Application\Service\These\Filter\TheseTextFilter;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer                                         $this
 * @var \Application\Service\These\Filter\TheseSelectFilter $filter
 * @var array                                               $queryParams
 */

?>

<?php if ($filter instanceof SelectSearchFilter OR $filter instanceof TheseSelectFilter): ?>
    <?php echo $this->partial('filter-form-item-select') ?>
<?php elseif ($filter instanceof SearchFilter): ?>
    <?php echo $this->partial('filter-form-item-text') ?>
<?php elseif ($filter instanceof TheseTextFilter): ?>
    <?php echo $this->partial('filter-form-item-text-criteria') ?>
<?php else: ?>
    Filtre rencontré inattendu!
<?php endif ?>