<?php

use Application\Service\These\Filter\TheseSelectFilter;
use Application\View\Helper\SelectsFilterPanel\SelectsFilterPanelHelper;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer                                         $this
 * @var \Application\Service\These\Filter\TheseSelectFilter $filter
 * @var array                                               $queryParams
 */

$paramAttributes = $filter->getAttributes();
$paramName = $filter->getName();

$width = isset($paramAttributes['width']) ? $paramAttributes['width'] : 'fit';
$liveSearch = isset($paramAttributes['liveSearch']) ? (bool)$paramAttributes['liveSearch'] : false;


$text = $filter->getValue();

$inputTitle = <<<EOS
<div class="these-search-input-help">
    Recherche possible sur
    <ul>
        <li>le titre de la thèse</li>
        <li>le numéro étudiant de l'auteur</li>
        <li>le nom de l'auteur</li>
        <li>le prénom de l'auteur</li>
        <li>le nom du directeur ou co-directeur de thèse</li>
        <li>le code national de l'école doctorale concernée (ex: 181)</li>
        <li>l'unité de recherche concernée (ex: umr6211)</li>
    </ul>
</div>
EOS;

?>

<div class="form-group">
    <label class="sr-only" for="search-input">Recherche d'une thèse (code, titre de la thèse ; code, nom, prénom de l'auteur) :</label>
    <div class="input-group">
        <div class="input-group-addon"><span class="glyphicon glyphicon-search"></span></div>
        <input type="search"
               value="<?php echo $text; ?>"
               name="text"
               class="form-control filter"
               id="search-input"
               placeholder="<?php echo $this->translate("Entrez 2 caractères au moins...");?>"
               data-content="<?php echo htmlspecialchars(
                   "<div class=\"these-search-input-help\">".
                   $this->translate("Recherche possible sur<ul><li>le titre de la thèse</li><li>le numéro étudiant de l'auteur</li><li>le nom de l'auteur</li><li>le nom du directeur ou co-directeur de thèse</li><li>le code national de l'école doctorale concernée (ex: 181)</li><li>l'unité de recherche concernée (ex: umr6211)</li></ul>") .
                   "</div>"
               );
               ?>">
    </div>
</div>

<script>
    $(function() {
        $("#search-input").popover({html: true, trigger: "hover", placement: "bottom"});
    });
</script>