<?php

use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var string      $formAction
 * @var array       $config
 * Exemple :
 [
    "État" => [
        'paramName' => 'etatThese',
        'paramConfig' => [
            ['value' => '', 'label' => "Tous"],
            ['value' => $v = These::ETAT_EN_COURS, 'label' => These::$etatsLibelles[$v]],
            ['value' => $v = These::ETAT_ABANDONNEE, 'label' => These::$etatsLibelles[$v]],
            ['value' => $v = These::ETAT_SOUTENUE, 'label' => These::$etatsLibelles[$v]],
        ],
        'filterUrl' => function ($param, $value, $queryParams) {
            $queryParams[$param] = $value;
            return $this->url('these/rechercher', [], ['query' => $queryParams], true);
        },
    ],
 ]
 *
 */

$queryParams = $this->queryParams();
?>

<div class="panel panel-default filters">
    <div class="panel-heading">
        <span class="glyphicon glyphicon-filter"></span> Filtres
    </div>
    <form class="panel-body form-inline" method="GET" action="<?php echo $formAction ?>">
        <?php foreach ($config as $label => $data): ?>
        <div class="form-group">
            <label for="<?php echo $data['paramName'] ?>">
                <?php echo $label ?>
            </label>
            <div class="input-group">
                <?php $data['queryParams'] = $queryParams; ?>
                <?php echo $this->partial('filter-form-item', $data) ?>
            </div>
        </div>
        <?php endforeach ?>
        <div class="form-group">
            <div class="input-group">
                <input type="submit" class="btn btn-info btn-sm" value="Appliquer"/>
            </div>
        </div>
    </form>
</div>



<script>
    $(".selectpicker").selectpicker({
        size: 15
    });
    $(".filters form").submit(function() {
        $("body").addClass('wait');
    })
</script>