<?php

use Application\Entity\Db\Individu;
use Application\Entity\Db\Role;
use Application\Entity\Db\These;
use Application\Entity\Db\Validation;
use Application\View\Renderer\PhpRenderer;
use Soutenance\Entity\Membre;
use Soutenance\Entity\Proposition;

/**
 * @var PhpRenderer $this
 * @var These $these
 * @var Proposition $proposition
 * @var Membre $membre
 */
?>

<p>
    Bonjour,
</p>
<p>
    Afin de pouvoir devenir rapport de la thèse de <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(false,false,false, true); ?>
    intitulée <?php echo $these->getTitre(); ?> il est nécessaire de signer électroniquement la <i>demande d'expertise</i> dans l'application SyGAL :
    <a href="<?php echo $this->url('soutenance/presoutenance/demande-expertise', ['these' => $these->getId(), 'proposition' => $proposition->getId(), 'membre' => $membre->getId()], ['force_canonical'=>true], true);?>">
        demande d'expertise
    </a>.
</p>

<p>
    Pour vous connecter à l'application utiliser la connection via la fédération d'identité et les identifiants communiquées dans un courrier précédent.
</p>

<p>
    Suite à ce refus toutes les validations associées à cette proposition ont été annulées.
</p>

