<?php

use Application\Entity\Db\Individu;
use Application\Entity\Db\Role;
use Application\Entity\Db\Validation;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var Validation $validation
 */
?>

    <p>
        Bonjour,
    </p>
    <p>
        Ceci est un mail envoyé automatiquement par l'application SyGAL.
    </p>

    <p>
        Suite à la modification de la proposition de soutenance, votre validation (faite le
        <?php echo $validation->getHistoCreation()->format("d/m/Y") ?> à
        <?php echo $validation->getHistoCreation()->format("H:i") ?>) a été annulée.
        Si la nouvelle proposition vous convient, veuillez valider la proposition de soutenance à nouveau.
    </p>

    <p>
        NB : La proposition de soutenance sera envoyée automatiquement à votre unité de recherche puis à votre école doctorale,
        une fois que tous les intervenants directs auront validé celle-ci (c.-à-d. doctorant, directeur et co-directeur(s)).
    </p>