<?php

use Application\Entity\Db\These;
use Soutenance\Entity\Membre;
use Soutenance\Entity\Proposition;

/**
 * @var These $these
 * @var Proposition $proposition
 * @var Membre $membre
 */
?>

<p>
    Bonjour,
</p>
<p>
    Afin de pouvoir devenir rapporteur de la thèse de <strong><?php echo $these->getDoctorant()->getIndividu()->getNomComplet(false,false,false, true); ?></strong>
    intitulée <strong><?php echo $these->getTitre(); ?></strong> il est nécessaire de signer électroniquement l'<i>engagement d'impartialité</i> dans l'application SyGAL :
    <a href="<?php echo $this->url('soutenance/presoutenance/engagement-impartialite', ['these' => $these->getId(), 'proposition' => $proposition->getId(), 'membre' => $membre->getId()], ['force_canonical'=>true], true);?>">
        engagement d'impartialité
    </a>
</p>

<p>
    Pour vous connecter à l'application, utilisez la connection via la fédération d'identité et les identifiants communiqués dans un courrier précédent.
</p>

