<?php

/**
 * @var PhpRenderer $this
 * @var string      $apercuUrl
 *
 * @see FichierTheseController::apercevoirPageDeCouvertureAction()
 */

use Application\Controller\FichierTheseController;
use Application\View\Renderer\PhpRenderer;

?>

<div class="container">
    <div class="col-md-3">
        <p>Voici un aperçu de la page de couverture générée par l'application :</p>
    </div>
    <div class="col-md-9">
        <!-- L'image PNG est chargée via une requête AJAX (cf. widget dans app.js) -->
        <div class="apercu-fichier widget-image-loader">
            <div class="image-placeholder loading" data-src="<?php echo $apercuUrl ?>" style="width: 450px"></div>
<!--            <a href="#" class="apercu-fichier-recharger" style="display: none"><span class="glyphicon glyphicon-refresh"></span> Recharger</a>-->
        </div>
    </div>
</div>


<!--<script>-->
<!--    $(function() {-->
<!--        $("body").on('image-loaded-event', function() {-->
<!--            $(".apercu-fichier-recharger").show();-->
<!--        });-->
<!--    });-->
<!--</script>-->