<?php
/**
 * Liste de tous les fichiers uploadés.
 *
 * @var PhpRenderer $this
 * @var Fichier     $fichier
 * @var string      $apercuUrl
 */

use Application\Entity\Db\Fichier;
use Application\View\Renderer\PhpRenderer;
?>

<p>Voici un aperçu de la première page du fichier <?php echo $fichier->getNom() ?> :</p>

<!-- L'image PNG est chargée via une requête AJAX (cf. widget dans app.js) -->
<div class="apercu-fichier widget-image-loader">
    <div class="image-placeholder loading" data-src="<?php echo $apercuUrl ?>" style="width: 500px"></div>
</div>
