<?php
/**
 * Affichage d'une liste de fichiers déposés quelconques.
 *
 * Paramètres attendus en entrée :
 * $items : ['file' => UploadedFileInterface, 'downloadUrl' => URL, 'deleteUrl' => URL]
 *
 * @var PhpRenderer $this
 * @var array       $items
 */

use Application\Entity\Db\FichierThese;
use Application\Provider\Privilege\FichierPrivileges;
use Application\View\Renderer\PhpRenderer;

$canCorrect = true;

if (!empty($items)): ?>

    <ul>
        <?php foreach ($items as $item): ?>
            <li class="uploaded-file">
                <!-- lien de téléchargement du fichier -->
                <?php
                /** @var FichierThese $fichierThese */
                $fichierThese = $item['file'];
                $fichier = $fichierThese->getFichier();
                $canDownload = $this->isAllowed($fichierThese->getThese(), FichierPrivileges::privilegeTelechargerFor($fichier->getNature(), $fichier->getVersion()));
                $canEdit = $this->isAllowed($fichierThese->getThese(), FichierPrivileges::privilegeTeleverserFor($fichier->getNature(), $fichier->getVersion()));
                if ($canDownload) {
                    $urlTelecharger = isset($item['downloadUrl']) ? $item['downloadUrl'] : null;
                } else {
                    $urlTelecharger = null;
                }
                echo sprintf('<span class="%s">%s</span>',
                    $fichier->getVersion()->getCode(),
                    $this->uploader()->renderUploadedFile($fichier, $urlTelecharger));
                ?>
                <?php if ($fichier->getNomOriginal() !== $fichier->getNom()): ?>
                <br>
                <!-- Nom original du fichier -->
                <small><abbr title="Nom original du fichier déposé"><?php echo $fichier->getNomOriginal() ?></abbr></small>
                <?php endif ?>

                <!-- lien de suppression du fichier -->
                <?php
                $urlSupprimer = isset($item['deleteUrl']) ? $item['deleteUrl'] : null;
                if ($canEdit && $urlSupprimer) {
                    echo $this->uploader()->renderDeleteFile($fichier, $urlSupprimer);
                }
                ?>

                <?php if (!empty($inclureValidite)): ?>
                    <div class="fichier-validite">
                    <?php echo $this->partial('application/fichier-these/partial/validite', ['fichier' => $fichierThese]) ?>
                    </div>
                <?php endif ?>
                <?php if (!empty($inclureRetraitement)): ?>
                    <div class="fichier-retraitement">
                        <?php echo $this->partial('application/fichier-these/partial/retraitement', ['fichier' => $fichierThese]) ?>
                    </div>
                <?php endif ?>

            </li>
        <?php endforeach ?>
    </ul>

<?php else: ?>

    <p>Aucun.</p>

<?php endif ?>