<?php

use Structure\Entity\Db\StructureConcreteInterface;
use Structure\Entity\Db\TypeStructure;
use Structure\Provider\Privilege\SubstitutionPrivileges;

/**
  * @see \Soutenance\Controller\IndexController::indexStructureAction()
  * @var string $type
  * @var StructureConcreteInterface[] $structures
  */

 $libelle = 'Structure';
 $canEdit = false;
 $canView = $this->isAllowed(SubstitutionPrivileges::getResourceId(SubstitutionPrivileges::SUBSTITUTION_CONSULTATION_TOUTES_STRUCTURES))
        OR  $this->isAllowed(SubstitutionPrivileges::getResourceId(SubstitutionPrivileges::SUBSTITUTION_CONSULTATION_SA_STRUCTURE));
$canEdit =  $this->isAllowed(SubstitutionPrivileges::getResourceId(SubstitutionPrivileges::SUBSTITUTION_MODIFICATION_TOUTES_STRUCTURES))
        OR  $this->isAllowed(SubstitutionPrivileges::getResourceId(SubstitutionPrivileges::SUBSTITUTION_MODIFICATION_SA_STRUCTURE));
  switch($type) {
     case TypeStructure::CODE_ECOLE_DOCTORALE :
         $libelle   = 'École doctorale';
         break;
     case TypeStructure::CODE_UNITE_RECHERCHE :
         $libelle   = 'Unité de recherche';
         break;
     case TypeStructure::CODE_ETABLISSEMENT :
         $libelle   = 'Établissement';
         break;
 }


?>

<?php if ($canView): ?>
    <div class="box card">
        <div class="card-header bg-info">
            <h2>
                <?php echo $libelle; ?>
                <span class="badge bg-secondary">
                    <?php echo count($structures); ?>
                </span>
            </h2>

        </div>
        <div class="card-body">

            <?php if($canEdit): ?>
                <p>
                    <a
                        data-event="edition-substitution"
                        href="<?php echo $this->url('substitution-creer', ['type' => $type], [], true); ?>"
                        class="zajax-modal"
                    >
                        <button class="btn btn-primary">
                            <span class="icon icon-plus"></span>
                            Créer une structure de substitution
                        </button>
                    </a>
                </p>
            <?php endif; ?>

            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th> Libellé </th>
                        <th> #Structures </th>
                        <th> Actions </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($structures as $structure): ?>
                        <tr>
                            <td> <?php echo $structure->getLibelle(); ?> </td>
                            <td> <?php echo count($structure->getStructuresSubstituees()); ?> </td>
                            <td style="text-align:center;">
                                <a
                                    data-event="edition-substitution"
                                    href="<?php echo $this->url('substitution-modifier', ['cible' => $structure->getId()], [], true); ?>"
                                    class="zajax-modal"
                                >
                                    <span class="icon icon-edit"></span>
                                </a>
                                &nbsp;
                                <?php if ($canEdit): ?>
                                        <span id="detruire"
                                              ref="<?php echo $structure->getId(); ?>"
<!--                                              href="--><?php //echo $this->url('substitution-detruire', ['cible' => $structure->getId()], [], true); ?><!--"-->
                                              type="<?php echo $type; ?>"
                                              class="text-danger icon icon-delete iconly"

                                        ></span>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
<?php endif; ?>

<style>
    span#detruire:hover{
        cursor: pointer;
    }
</style>
