<?php

namespace These\Fieldset\TitreAcces;

use Application\Entity\Db\Pays;
use DoctrineModule\Form\Element\ObjectSelect;
use Laminas\Form\Element\Hidden;
use Laminas\Form\Element\Select;
use Laminas\Form\Element\Text;
use Laminas\Form\Fieldset;
use Laminas\Form\FormInterface;
use Laminas\InputFilter\InputFilterProviderInterface;
use Laminas\Validator\NotEmpty;
use Structure\Entity\Db\Etablissement;
use Structure\Service\Etablissement\EtablissementServiceAwareTrait;
use These\Entity\Db\These;
use UnicaenApp\Service\EntityManagerAwareTrait;

class TitreAccesFieldset extends Fieldset implements InputFilterProviderInterface
{
    use EtablissementServiceAwareTrait;
    use EntityManagerAwareTrait;
    
    public function prepareElement(FormInterface $form): void
    {
        /** @var These $these */
        $these = $this->getObject();
        $estModifiable = !$these->getSource()->getImportable();
        
        $this->get('titreAccesInterneExterne')->setAttribute('disabled', !$estModifiable);
        $this->get('libelleTitreAcces')->setAttribute('readonly', !$estModifiable);
        $this->get('pays')->setAttribute('disabled', !$estModifiable);
        $this->get('etablissement')->setAttribute('disabled', !$estModifiable);
        $this->get('codeDeptTitreAcces')->setAttribute('disabled', !$estModifiable);
        $this->get('nomDeptTitreAcces')->setAttribute('disabled', !$estModifiable);

        parent::prepareElement($form); // TODO: Change the autogenerated stub
    }

    public function init()
    {
        $this->add([
            'type' => Hidden::class,
            'name' => 'id',
        ]);

        $this->add(
            (new Select("titreAccesInterneExterne"))
                ->setEmptyOption("Sélectionnez une option")
                ->setValueOptions([
                    'E' => 'Externe',
                    'I' => 'Interne',
                ])
                ->setLabel("Accès : *")
                ->setAttributes([
                    'class' => 'selectpicker show-tick',
                    'id' => "titreAccesInterneExterne"
                ])
        );

        $this->add(
            (new Text("libelleTitreAcces"))
                ->setLabel("Libellé : *")
        );

        $this->add([
            'type' => ObjectSelect::class,
            'name' => 'pays',
            'options' => [
                'label' => "Pays d'obtention : *",
                'target_class' => Pays::class,
                'disable_inarray_validator' => true,
            ],
            'attributes' => [
                'id' => 'pays',
                'class' => 'selectpicker show-menu-arrow',
                'title' => "Sélectionner le pays",
                'data-live-search' => 'true',
            ],
        ]);

        $this->add(
            (new Text('nomDeptTitreAcces'))
                ->setLabel("Département :")
                ->setAttributes([
                    'id' => "nomDeptTitreAcces",
                    'placeholder' => "Entrez les deux premières lettres...",
                    'class' => 'selectpicker show-tick',
                ])
        );

        $this->add(
            (new Hidden('codeDeptTitreAcces'))
            ->setAttribute('id', "codeDeptTitreAcces")
        );

        $this->add([
            'type' => ObjectSelect::class,
            'name' => 'etablissement',
            'options' => [
                'label' => 'Établissement : *',
                'target_class' => Etablissement::class,
                'label_generator' => function($targetEntity) {
                    $sigle = $targetEntity->getStructure() && $targetEntity->getStructure()->getSigle() ? " (".$targetEntity->getStructure()->getSigle().")" : null;
                    return $targetEntity->getStructure()?->getLibelle() . $sigle;
                },
            ],
            'attributes' => [
                'id' => 'etablissement',
                'class' => 'selectpicker show-menu-arrow',
                'title' => "Sélectionner l'établissement",
                'data-live-search' => 'true',
            ],
        ]);
    }

    /**
     * @inheritDoc
     */
    public function getInputFilterSpecification()
    {
        /** @var These $these */
        $these = $this->getObject();
        $estModifiable = !$these->getSource()->getImportable();
        return [
            'titreAccesInterneExterne' => [
                'required' => $estModifiable,
            ],
            'libelleTitreAcces' => [
                'required' => $estModifiable,
            ],
            'pays' => [
                'required' => $estModifiable,
                'validators' => [
                    [
                        'name' => NotEmpty::class,
                        'options' => [
                            'messages' => [
                                NotEmpty::IS_EMPTY => 'Veuillez sélectionner un pays.',
                            ],
                        ],
                    ],
                ],
            ],
            'etablissement' => [
                'required' => $estModifiable,
                'validators' => [
                    [
                        'name' => NotEmpty::class,
                        'options' => [
                            'messages' => [
                                NotEmpty::IS_EMPTY => 'Veuillez sélectionner un établissement.',
                            ],
                        ],
                    ],
                ],
            ],
        ];
    }
}