<?php

namespace Individu;

global $unite;

use Application\Filter\IdifyFilter;
use Application\View\Renderer\PhpRenderer;
use Individu\Provider\Privilege\IndividuPrivileges;
use Substitution\Constants;
use UnicaenAuth\Provider\Privilege\Privileges;

/**
 * @var PhpRenderer $this
 * @var \Laminas\Paginator\Paginator $paginator
 * @var \Application\Search\Filter\SearchFilter[] $filters
 *
 * @see \Individu\Controller\IndividuController::indexAction()
 */

$canAjouter = $this->isAllowed(Privileges::getResourceId(IndividuPrivileges::INDIVIDU_AJOUTER));
?>

<?php $this->headTitle($this->translate("Individus")) ?>

<h1 class="page-header">
    <span class="fas fa-user-friends"></span>
    <?php echo $this->translate("Individus"); ?>

    <?php if ($canAjouter): ?>
        <a class="btn btn-primary float-end"
           title="Création d'un nouvel individu..."
           href="<?php echo $this->url('individu/ajouter') ?>"><?php echo $this->translate("Nouvel individu...") ?></a>
    <?php endif ?>
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace(); ?>

<?php echo $this->filtersPanel($filters) ?>

<p>
    <?php echo $paginator->getTotalItemCount() . " " . $this->translate("individu(s) trouvé(s).") ?>
</p>

<?php if (!empty($paginator)): ?>
    <table class="table table-bordered table-extra-condensed">
        <tr>
            <th>Id</th>
            <th>Nom d'usage</th>
            <th>Nom patronymique</th>
            <th>Prénom 1</th>
            <th>Autres prénoms</th>
            <th>Date de naissance</th>
            <th>Adresse électronique</th>
            <th title="Complément d'individu">Compl.</th>
            <th>Source</th>
            <th class="action">Action</th>
        </tr>
        <?php /** @var \Individu\Entity\Db\Individu $individu */
        foreach ($paginator as $individu): ?>
            <?php
            $canModifier = $this->isAllowed($individu, IndividuPrivileges::INDIVIDU_MODIFIER);
            $canSupprimer = $this->isAllowed($individu, IndividuPrivileges::INDIVIDU_SUPPRIMER);
            ?>
            <tr class="individu <?php echo $individu->estHistorise() ? 'historise' : '' ?>">
                <td>
                    <span class="<?php echo $individu->estHistorise() ? 'historise' : '' ?>">
                        <a href="<?php echo $this->url('individu/voir', ['individu' => IdifyFilter::id($individu)]) ?>"
                           title="Accéder à la fiche détaillée de cet individu">
                            <?php echo $individu->getId() ?>
                        </a>
                    </span>
                </td>
                <td>
                    <?php echo $individu->getNomUsuel() ?>
                </td>
                <td>
                    <?php echo $individu->getNomPatronymique() ?>
                </td>
                <td>
                    <?php echo $individu->getPrenom1() ?>
                </td>
                <td>
                    <span class="text-secondary">
                        <?php echo implode(', ', array_filter([$individu->getPrenom2(), $individu->getPrenom3()])) ?>
                    </span>
                </td>
                <td>
                    <?php echo $individu->getDateNaissanceToString() ?>
                </td>
                <td>
                    <?php if ($email = $individu->getEmailProComplement()) : ?>
                        <em title="Valeur forcée issue du complément d'individu"><?php echo $email ?></em>
                    <?php else: ?>
                        <?php echo $individu->getEmailPro(); ?>
                    <?php endif; ?>
                </td>
                <td>
                    <?php if ($complement = $individu->getComplement()): ?>
                        <a href="<?php echo $this->url('individu-compl/afficher', ['individu-compl' => $complement->getId()]) ?>"
                            title="Voir le complément d'individu">
                            <span class="icon icon-voir"></span>
                        </a>
                    <?php endif ?>
                </td>
                <td>
                    <?php echo $individu->getSource(); ?>
                    <?php if ($individu->estSubstituant()) : ?>
                        <a href="<?php echo $this->url('substitution/substitution/voir', ['type' => Constants::TYPE_individu, 'id' => $individu->getId()]) ?>"
                           title="Accéder aux détails de cette substitution">
                            <span class="badge bg-light text-info" title="Cet enregistrement substitue d'autres enregistrements, cliquez pour en savoir plus...">Substitution</span></a>
                    <?php endif; ?>
                </td>
                <td class="action">
                    <?php if ($canSupprimer): ?>
                        <?php if ($individu->estHistorise()): ?>
                            <a href="<?php echo $this->url('individu/restaurer', ['individu' => $individu->getId()], [], true); ?>"
                               title="Restaurer cet individu"
                               data-toggle="confirmationx">
                                <span class="icon icon-restaurer"></span></a>
                        <?php else: ?>
                            <a href="<?php echo $this->url('individu/supprimer', ['individu' => $individu->getId()], [], true); ?>"
                               title="Supprimer cet individu"
                               data-toggle="confirmationx">
                                <span class="icon icon-supprimer"></span></a>
                        <?php endif ?>
                    <?php endif ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
    <?php echo $this->paginationControl($paginator, 'sliding', 'application/paginator.phtml', ['route' => 'individu']) ?>
<?php else: ?>
    <p>Aucun individu trouvé.</p>
<?php endif ?>
