<?php

use Application\View\Renderer\PhpRenderer;
use UnicaenIdref\Domain\Index1;

/**
 * @var \Individu\Form\IndividuForm $form
 * @var PhpRenderer $this
 *
 * @see \Individu\Controller\IndividuController::ajouterAction()
 */

$form->setAttribute('class', 'row')->prepare();
?>

<?php $this->headTitle($title = $this->translate("Modification d'un individu")) ?>

<h1 class="page-header"><?php echo $title ?> </h1>

<div class="row">
    <div class="col-6">
        <?php echo $this->form()->openTag($form) ?>
        <div class="col-3">
            <?php echo $this->formControlGroup($form->get('civilite')) ?>
        </div>
        <div class="row">
            <div class="col-md-6">
                <?php echo $this->formControlGroup($form->get('nomUsuel')->setAttribute('id', 'nomUsuel')) ?>
            </div>
            <div class="col-md-6">
                <?php echo $this->formControlGroup($form->get('nomPatronymique')) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <?php echo $this->formControlGroup($form->get('prenom1')->setAttribute('id', 'prenom1')) ?>
            </div>
            <div class="col-md-4">
                <?php echo $this->formControlGroup($form->get('prenom2')) ?>
            </div>
            <div class="col-md-4">
                <?php echo $this->formControlGroup($form->get('prenom3')) ?>
            </div>
        </div>
        <div class="col-6">
            <?php echo $this->formControlGroup($form->get('email')) ?>
        </div>
        <div class="col-md-4">
            <?php echo $this->formControlGroup($form->get('dateNaissance')) ?>
        </div>
        <div class="col-md-6">
            <?php echo $this->formControlGroup($form->get('paysNationalite')) ?>
        </div>
        <div class="col-md-4">
            <?php echo $this->formControlGroup($form->get('supannId')) ?>
        </div>
        <div class="row">
            <div class="col-md-5">
                <?php echo $this->formControlGroup($form->get('idRef')->setAttribute('id', 'idRef')) ?>
            </div>
            <div class="col-md-2">
                <?php echo $this->idrefPopupTrigger([
                    ['Index1' => Index1::INDEX_Ppn, 'Index1Value' => ['idRef']],
                    ['Index1' => Index1::INDEX_NomDePersonne, 'Index1Value' => ['nomUsuel', 'prenom1']],
                ], 'idRef') ?>
            </div>
        </div>
        <?php echo $this->formSubmit($form->get('submit')) ?>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>