<?php

use Individu\Entity\Db\Individu;
use Application\Entity\Db\Role;
use Structure\Provider\Privilege\StructurePrivileges;


/**
 * @var string                          $type                  (etablissment|ecole-doctorale|unite-recherche)
 * @var Role[]                          $roles              (la liste des roles associés à la structure)
 * @var Individu[]                      $membres             (la liste des individus associés à la structure)
 * @var Individu[][]                    $repartition        (la liste des roles avec les individus associés)
 */

$structure = $roles[0]->getStructure();
$canModifier = $this->isAllowed(StructurePrivileges::getResourceId(StructurePrivileges::STRUCTURE_MODIFICATION_TOUTES_STRUCTURES)) || $this->isAllowed($structure, StructurePrivileges::STRUCTURE_MODIFICATION_TOUTES_STRUCTURES);
?>

<?php //echo $this->messenger()->addCurrentMessagesFromFlashMessenger() ?>

<h3 xmlns="http://www.w3.org/1999/html">
    Rôles
    <span class="badge bg-secondary"> <?php echo count($roles); ?> </span>
</h3>

<table class="table table-extra-condensed">
    <thead>
        <tr>
            <th>
                Libellé du rôle
            </th>
            <th>
                Effectif
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($roles as $role): ?>
        <tr>
            <td>
                <?php echo $role->getLibelle(); ?>
            </td>
            <td>
                <?php echo count($repartition[$role->getId()]); ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<h3>
    Membres
    <span class="badge bg-secondary"> <?php echo count($membres); ?> </span>
</h3>

<table class="table table-extra-condensed">
    <thead>
    <tr>
        <th>
            Utilisateur
        </th>
        <th>
            Rôle
        </th>
        <th>
            Actions
        </th>
    </tr>
    </thead>
    <tbody>
        <?php foreach($roles as $role): ?>
            <?php
                /** @var Individu $membre */
            foreach($repartition[$role->getId()] as $membre): ?>
                <tr>
                    <td>
                        <?php echo $membre->getPrenom() . " " . $membre->getNomUsuel(); ?>
                    </td>
                    <td>
                        <?php echo $role->getLibelle(); ?>
                    </td>
                    <td>
                        <?php if ($canModifier): ?>
                            <span id="<?php echo $membre->getId();?>_<?php echo $role->getId();?>" class="remove-role icon icon-delete iconly"> </span>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endforeach; ?>
    </tbody>
</table>

<script>
    // $(document).ready(function () {
    //     $(".remove-role").on("click", function () {
    //         var id = $(this).attr("id");
    //         var splits = id.split("_");
    //         var role = splits[1];
    //         var individu = splits[0];
    //
    //         var url = "../../utilisateur/retirer-role/" + individu + "/" + role;
    //
    //         $.ajax({
    //             url: url
    //         });
    //     });
    // });
</script>

<style>
    .remove-role:hover {
        cursor: pointer;
    }
</style>