<?php

/**
 * @see \Soutenance\Controller\IndexController::indexRapporteurAction()
 *
 * @var Proposition $proposition
 * @var These[] $theses
 * @var Membre $membre
 * @var ActeurThese|null $acteurMembre
 * @var boolean $depot
 * @var These $these
 * @var ValidationThese $engagement
 * @var Avis $avis
 * @var string $telecharger
 * @var string $typeProposition
 */

use Acteur\Entity\Db\ActeurThese;
use Application\Constants;
use Application\Entity\Db\Role;
use Soutenance\Entity\Avis;
use Soutenance\Entity\Membre;
use Soutenance\Entity\Proposition;
use Soutenance\Provider\Privilege\AvisSoutenancePrivileges;
use These\Entity\Db\These;
use Validation\Entity\Db\ValidationThese;

$canEngagement = true;
$canTelecharger = true;
$canAvis = true;
$canAnnuler = ($membre)?$this->isAllowed($acteurMembre, AvisSoutenancePrivileges::AVIS_ANNULER):false;

$libelleEntite = $typeProposition === Proposition::ROUTE_PARAM_PROPOSITION_THESE ? "thèse" : "HDR";
?>

<?php /** Plusieurs thèses ont été trouvées, le rapporteurs doit alors sélectionner celle sur laquelle il veut travailler */ ?>
<?php if (isset($theses)) : ?>
    <h1 class="page-header">
        Tableau de bord des soutenances / Dashboard of the defenses
    </h1>

    <p class="lead">
        Vous êtes actuellement rapporteur de plusieurs thèses en cours.
        Veuillez sélectionner la thèse sur laquelle vous souhaitez intervenir.
    </p>

    <table class="table table-sm">
        <thead>
            <tr>
                <th class="these-titre">    Titre </th>
                <th class="">               Doctorant </th>
                <th class="">               Encadrement </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($theses as $these) : ?>
                <tr>
                    <td>
                        <a  <?php /** @see \Soutenance\Controller\IndexController::indexRapporteurAction()*/ ?>
                            href="<?php echo $this->url("soutenance_{$typeProposition}/index-rapporteur", ['id' => $these->getId()], [], true); ?>">
                            <?php echo $these->getTitre(); ?>
                        </a>
                    </td>
                    <td> <?php echo $these->getApprenant()->getIndividu(); ?> </td>
                    <td>
                        <?php foreach ($these->getEncadrements() as $encadrement) : ?>
                            <?php if ($encadrement->getRole()->getCode() !== Role::CODE_DIRECTEUR_THESE || $encadrement->getRole()->getCode() !== Role::CODE_HDR_GARANT) echo "<i>"; ?>
                            <?php echo $encadrement->getIndividu() ; ?>
                            <?php if ($encadrement->getRole()->getCode() !== Role::CODE_DIRECTEUR_THESE || $encadrement->getRole()->getCode() !== Role::CODE_HDR_GARANT) echo "</i>"; ?>
                            <br/>
                        <?php endforeach; ?>
                    </td>

                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

<?php else : ?>


<h1 class="page-header">
    Tableau de bord de la soutenance / Dashboard of the defense
    <small><?php echo $this->partial('these/these/partial/titre') ?></small>
</h1>

<div class="box card">
    <div class="card-header bg-dark text-white">
        <h2> Proposition de jury / Jury Proposal </h2>
    </div>
    <div class="card-body">
        <?php if ($proposition !== null) : ?>
            <h3> Date et lieu </h3>
            <?php if($proposition->getDate()): ?>
                <p>La soutenance est prévue pour le <strong><?php echo $proposition->getDate()->format(Constants::DATETIME_FORMAT); ?></strong>
                dans <strong><?php echo $proposition->getLieu(); ?></strong>.</p>
            <?php else: ?>
                <p>
                    <span class="icon icon-warning"></span>
                    Aucune date n'a encore été renseignée dans la proposition.
                </p>
            <?php endif; ?>
            <h3> Jury </h3>
            <table class="table table-sm">
                <thead>
                    <tr>
                        <th> Dénomination </th>
                        <th> Qualité </th>
                        <th> Établissement </th>
                        <th> Rôle </th>
                    </tr>
                </thead>
                <tbody>
                    <?php /** @var Membre $jury  */ ?>
                    <?php foreach ($proposition->getMembres() as $jury) : ?>
                        <tr>
                            <td> <?php echo $jury->getDenomination(); ?> </td>
                            <td> <?php echo ($jury->getQualite())?$jury->getQualite()->getLibelle():"Non définie"; ?> </td>
                            <td> <?php echo $jury->getEtablissement(); ?> </td>
                            <td> <?php echo $jury->getRole(); ?> </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php else : ?>
            Aucune proposition de soutenance de trouvée.
        <?php endif; ?>
    </div>
</div>

<div class="box card">
    <div class="card-header <?php echo ($engagement !== null)?"bg-success":"bg-warning"; ?> text-white">
        <h2> Engagement d'impartialité / Impartiality Commitment </h2>
    </div>
    <div class="card-body">
        <?php if ($engagement !== null) : ?>
            <p>Vous avez signé l'engagement pour la thèse de <?php echo $these->getApprenant(); ?>.</p>
            <?php echo $this->validation($engagement, "success") ?>
        <?php else : ?>
            <p class="lead">
                Pour être enregistré comme rapporteur de thèse, vous devez signer l'engagement d'impartialité. <br/>
            </p>
            <p class="lead">
                To be registered as external referee you must sign the impartiality commitment
            </p>
            <?php if ($membre) : ?>
            <a
                    <?php /** @see \Soutenance\Controller\EngagementImpartialiteController::engagementImpartialiteAction() */?>
                    href="<?php echo $this->url("soutenance_{$typeProposition}/engagement-impartialite", ['id' => $these->getId(), 'membre' => $membre->getId()], [], true); ?>"
               class="btn btn-primary float-end"
            >
                <span class="icon icon-edit"></span>
<!--                Signer / Sign-->
                Accès à l'engagement d'impartialité / Access to the impartiality commitment
            </a>
            <?php endif; ?>

        <?php endif; ?>
    </div>
</div>

<div class="box card">
    <div class="card-header <?php echo ($depot !== null)?"bg-dark":"bg-warning"; ?>">
        <h2> Téléchargement de la thèse / Downloading the manuscrit </h2>
    </div>
    <div class="card-body">
        <?php if ($engagement === null) : ?>
            <p class="lead">Vous ne pourrez télécharger la version électronique de la thèse qu'après avoir signé l'engagement d'impartialité.</p>
        <?php else : ?>
            <?php if ($depot !== null) : ?>
                Vous pouvez télécharger la version électronique de la thèse via <?php echo $this->appInfos()->nom; ?>.
                <a
                    <?php /** @see \These\Controller\TheseController::fusionAction() */ ?>
                        href="<?php echo $this->url("these/fusion", ["these" => $these->getId()], [], true); ?>"
                        class="btn btn-primary float-end"
                >
                    <span class="icon icon-download"></span>
                    Télécharger la thèse / Downloading manuscrit
                </a>
            <?php else : ?>
                <span class="fas fa-exclamation-triangle"></span>
                La thèse de <?php echo $these->getApprenant()->getIndividu(); ?> n'a pas encore été déposée dans <?php echo $this->appInfos()->nom; ?>.
                Une fois le dépôt réalisé, vous pourrez télécharger celle-ci via cette page.
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>

<div class="box card">
    <div class="card-header <?php echo ($engagement !== null && $avis !== null)?"bg-success":"bg-warning"; ?>">
        <h2> Avis de soutenance / Notification on the defense </h2>
    </div>
    <div class="card-body">
    <?php if ($engagement !== null) : ?>
            <?php if ($avis !== null) : ?>
        <p>Vous avez rendu votre avis de soutenance pour la thèse de <?php echo $these->getApprenant()->getIndividu(); ?>.</p>

            <div>
                <div class="col-md-5">
                    <div class="card">
                        <div class="card-header <?php echo ($avis->getAvis() === 'Favorable')?"bg-success":"bg-danger"; ?>">
                            Avis de soutenance : <strong><?php echo $avis->getAvis(); ?></strong>
                        </div>
                        <div class="card-body">
                            <ul>
                                <li>Rendu le <?php echo $avis->getValidation()->getHistoModification()->format(Constants::DATETIME_FORMAT); ?> par <?php echo $avis->getValidation()->getIndividu(); ?></li>
                            </ul>

                            <dl>
                                <?php if ($avis->getAvis() !== 'Favorable') : ?>
                                    <dt> Motif de refus </dt>
                                    <dd> <?php echo $avis->getMotif(); ?> </dd>
                                <?php endif; ?>
                            </dl>

<!--                            <a href=" --><?php //echo $this->urlFichierThese->telechargerFichierThese($these, $avis->getFichier()); ?><!--" >-->
                            <a
                                <?php /** @see TELECHARGEMENT FICHIER */ ?>
                                href=" <?php echo $telecharger; ?>" >
                                Pré-rapport de soutenance
                            </a>
                        </div>
                    </div>

                    <a
                        <?php /** @see \Soutenance\Controller\AvisController::annulerAction() */ ?>
                        href="<?php echo $this->url("soutenance_{$typeProposition}/avis-soutenance/annuler", ['id' => $these->getId(), 'rapporteur' => $membre->getId()], [] , true); ?>"
                        class="btn btn-danger" style="margin-top: 1rem;"
                        data-toggle="confirmationx"
                        data-bs-toggle="tooltip"
                        data-bs-html="true"
                        title="Une confirmation avant l'annulation vous sera demandée">
                        <span class="icon icon-delete"></span>
                        Annuler l'avis de soutenance
                    </a>
                    </div>
                </div>
            </div>
            <?php else : ?>
                <p class="lead">
                    Afin de valider la soutenance de thèse de <?php echo $these->getApprenant()->getIndividu(); ?>, vous devez rendre votre
                    avis de soutenance et votre pré-rapport de soutenance.
                </p>
                <div class="alert alert-<?php echo (new DateTime() > $proposition->getRenduRapport()) ? 'danger' : 'warning'; ?>" style="margin-left: 1rem !important;">
                    <span class="icon icon-attention"></span>
                    Attention, la date limite de rendu des pré-rapports est le <strong><?php echo $proposition->getRenduRapport()->format('d/m/Y'); ?></strong>.
                </div>
            <?php if ($canAnnuler) : ?>
            <div>
                <a
                    <?php /** @see \Soutenance\Controller\AvisController::indexAction() */ ?>
                    href="<?php echo $this->url("soutenance_{$typeProposition}/avis-soutenance", ['id' => $these->getId(), 'rapporteur' => $membre->getId()], [], true); ?>"
                   class="btn btn-primary float-end"
                >
                    <span class="icon icon-edit"></span>
                    Rendre l'avis de soutenance / Give our report
                </a>
            </div>
            <?php endif; ?>

            <?php endif; ?>
        <?php else : ?>
            <p class="lead">Pour pouvoir rendre votre avis de soutenance, vous devez avoir signé l'engagement d'impartialité.</p>
        <?php endif; ?>
</div>

<?php endif; ?>