
<?php

use Zend\Feed\Reader\Entry\Rss;
use Zend\Feed\Reader\Reader;
use Zend\Http\Client\Adapter\Exception\RuntimeException;

$url = "https://www.normandie-univ.fr/adminsite/webservices/export_rss.jsp?objet=actualite&TYPE_EVENEMENT=3ZZ125GT&THEMATIQUE=3WKWANK3&TRI_DATE=DATE_ASC&TYPE_FLUX_FEED=rss_2.0&DESCRIPTION=FluxSyGAL";
$exception = null;
try {
    $channel = Reader::import($url);
} catch (RuntimeException $e) {
    $channel = null;
    $exception = $e;
}
?>
<ul class="menu-actualites nav nav-pills nav-stacked">
    <?php if ($channel !== null): ?>
    <?php foreach (array_reverse(iterator_to_array($channel)) as $item): /** @var Rss $item */ ?>
        <li>
            <h2>
                <span class="label label-info">Actualité</span>
                <a target="_blank" title="Cliquez pour ouvrir dans un nouvel onglet"
                   href="<?php echo $item->getLink() ?>"><?php echo $item->getTitle() ?> <i class="fa fa-external-link-alt"></i></a>
            </h2>
            <p class="date"><?php echo $item->getDateCreated()->format('d/m/Y H:i') ?></p>
        </li>
    <?php endforeach ?>
    <?php else: ?>
        <li><?php echo $exception->getMessage() ?></li>
    <?php endif ?>
</ul>