<?php

/**
 * @var string|null $url
 **/

use Zend\Feed\Reader\Entry\Rss;
use Zend\Feed\Reader\Reader;

?>
<ul class="menu-actualites nav nav-pills nav-stacked">
    <?php if ($url !== null) : ?>
        <?php $channel = Reader::import($url); ?>
        <?php foreach (array_reverse(iterator_to_array($channel)) as $item): /** @var Rss $item */ ?>
            <li>
                <h2>
                    <span class="label label-info">Actualité</span>
                    <a target="_blank" title="Cliquez pour ouvrir dans un nouvel onglet"
                       href="<?php echo $item->getLink() ?>"><?php echo $item->getTitle() ?> <i class="fa fa-external-link-alt"></i></a>
                </h2>
                <p class="date"><?php echo $item->getDateCreated()->format('d/m/Y H:i') ?></p>
            </li>
        <?php endforeach ?>
    <?php else : ?>
        Le fil d'actualité est désactivé.
    <?php endif; ?>
</ul>