<?php
/**
 * @var These[] $theses
 */

use Application\Entity\Db\These;
?>

<p>
    SoDoct vous alerte lorsque la BU a validé le dépôt avant soutenance. <br>
    Vous pourrez demander l’autorisation de soutenance au Président dès réception par courrier interne de la convention de mise en ligne de la thèse signée du doctorant.
</p>
<p>
    <em>Rappel : SoDoct offre aux différents acteurs des thèses UNICAEN une vision d’ensemble des thèses préparées telles qu’elles sont signalées dans Apogée : en cours, soutenues, transférées, abandonnées. <br>
        Les informations sont importées dès l’inscription en première année de doctorat puis mises à jour en temps réel. SoDoct étant une application dédiée à la période de soutenance, seules les données sur les thèses en cours ont été fiabilisées dans Apogée : les thèses soutenues, transférées et abandonnées n’apparaissent donc qu’à titre indicatif. </em>
</p>
