<?php
/**
 * @var These[] $theses
 */

use Application\Entity\Db\These;
?>

<p>
    SyGAL vous permet de gérer le dépôt en ligne.
</p>
<p>
    SyGAL vous informe lorsque le doctorant a effectué son dépôt, décrit sa thèse et indiqué ses disponibilités pour
    que vous lui proposiez un RDV. Lors du RV, vous validez avec le doctorant les informations et fichier(s) fourni(s).
    Votre validation finale informe le Bureau des doctorats de votre établissement de l’envoi par courrier interne de
    la convention de mise en ligne et qu’il peut, dès réception, procéder à la demande d’autorisation de soutenance
    auprès du Président.
</p>
<p>
    SyGAL vous notifie lorsque le doctorant est admis, la thèse peut alors être traitée dans STAR.
</p>
<p>
    <em>
        Rappel : SyGAL offre aux différents acteurs des thèses une vision d’ensemble des thèses préparées telles
        qu’elles sont signalées dans Apogée : en cours, soutenues, transférées, abandonnées. <br>
        Les informations sont importées dès l’inscription en première année de doctorat puis mises à jour en temps réel.
        SyGAL étant une application dédiée à la période de soutenance, seules les données sur les thèses en cours ont
        été fiabilisées dans Apogée : les thèses soutenues, transférées et abandonnées n’apparaissent donc qu’à titre
        indicatif.
    </em>
</p>
