<?php
/**
 * @var These[] $theses
 */

use Application\Entity\Db\These;

$appName = $this->appInfos()->nom;
?>

<p>
    <?php echo $appName ?> vous offre une vue sur les thèses que vous dirigez au sein de votre établissement.
    Les informations sont importées d’Apogée dès l’inscription en première année de doctorat puis mises à jour en temps réel.
    <?php echo $appName ?> étant une application dédiée à la période de soutenance, seules les données sur les thèses en cours ont été fiabilisées :
    les thèses soutenues, transférées et abandonnées que vous avez dirigées n’apparaissent qu’à titre indicatif.
</p>
<p>
    <em><?php echo $appName ?> permet au doctorant de déposer en ligne le fichier numérique de sa thèse un mois avant la soutenance, de décrire
        sa thèse en lien avec la BU pour le signalement dans <a href="http://www.theses.fr/">theses.fr</a>, d’indiquer ses
        choix de mise en ligne et de suivre les différentes étapes du processus de dépôt et de validation grâce à sa « feuille de route ».</em>
</p>
<p>
    <em>
        Le dépôt avant soutenance et la réception des pré-rapports favorables conditionnent la demande d’autorisation de
        soutenance au Président par la Maison du doctorat.
    </em>
</p>