<?php
/**
 * @var These[] $theses
 */

use Application\Entity\Db\These;

$appName = $this->appInfos()->nom;
?>

<p>
    <?php echo $appName ?> vous offre une vue sur les thèses que vous dirigez au sein de votre établissement.
</p>
<p>
    <?php echo $appName ?> vous permet d’effectuer et valider en ligne les différentes étapes de la soutenance de thèse
    de vos doctorants, de la proposition de la composition du jury à l’autorisation de soutenance.
</p>
<p>
    La réception des rapports favorables conditionne l’autorisation de soutenance par votre chef d’établissement.
</p>