<?php
/**
 * @var These[] $theses
 */

use These\Entity\Db\These;

$appName = $this->appInfos()->nom;
?>

        <h2><?php echo count($theses) > 1 ? "Vos thèses" : "Votre thèse" ?></h2>
        <?php foreach ($theses as $these): ?>
            <?php echo $this->partial('these/these/partial/panel', ['these' => $these]) ?>
        <?php endforeach ?>

<p>
    Avec <?php echo $appName ?>, vous allez pouvoir :
</p>
<ul>
    <li> Déposer vos rapports ;</li>
    <li>
        Remplir le dossier de demande de soutenance de thèse en accord avec votre directeur(trice) de thèse.
        Attention, la réception puis validation par l’établissement doit s’effectuer <strong>deux mois avant la soutenance</strong>.
        Les règles de composition du jury sont rappelées dans la page d'accueil <q>Guide de la thèse</q> ;
    </li>
    <li>
        Déposer le fichier de votre thèse de manière sécurisée <strong>un mois avant la soutenance</strong> ;
    </li>
    <li>
        Suivre les différentes étapes de la demande de soutenance et du processus de dépôt de votre manuscrit grâce à vos « feuilles de route ».
    </li>
</ul>
<p>
    Le dépôt du manuscrit de thèse et la réception des rapports favorables conditionnent l’autorisation de soutenance par votre chef d’établissement.
</p>
