<?php
/**
 * @var These[] $theses
 */

use Application\Entity\Db\These;

$appName = $this->appInfos()->nom;
?>

        <h2><?php echo count($theses) > 1 ? "Vos thèses" : "Votre thèse" ?></h2>
        <?php foreach ($theses as $these): ?>
            <?php echo $this->partial('application/these/partial/panel', ['these' => $these]) ?>
        <?php endforeach ?>

<p>
    Avec <?php echo $appName ?>, vous allez :
</p>
<ul>
    <li>déposer le fichier de votre thèse simplement et de manière sécurisée un mois avant la soutenance ;</li>
    <li>décrire votre thèse en lien avec la BU pour le signalement dans <a href="http://www.theses.fr/">theses.fr</a> ;</li>
    <li>indiquer vos choix de mise en ligne ;</li>
    <li>suivre les différentes étapes du processus de dépôt et de validation grâce à votre « feuille de route ».</li>
</ul>
<p>
    <em>À l'issue du dépôt, vous recevrez une notification de validation qui conditionne la demande d’autorisation de soutenance auprès du Président.</em>
</p>
