<?php
/**
 * @var These[] $theses
 */

use These\Entity\Db\These;

$appName = $this->appInfos()->nom;
?>

<p>
    <?php echo $appName ?> vous offre une vue sur toutes les thèses préparées dans votre ED.
    Les informations sont importées d’Apogée dès l’inscription en première année de doctorat puis mises à jour en temps réel.
    <?php echo $appName ?> étant une application dédiée à la période de soutenance, seules les données sur les thèses en cours ont été fiabilisées :
    les thèses soutenues, transférées et abandonnées que vous avez dirigées n’apparaissent qu’à titre indicatif.
</p>
<p>
    <em><?php echo $appName ?> permet à vos doctorants de déposer en ligne le fichier numérique de leur thèse un mois avant la soutenance,
        de décrire leur thèse en lien avec la bibliothèque universitaire pour le signalement dans <a href="http://www.theses.fr/">theses.fr</a>,
        d’indiquer leur choix de mise en ligne et de suivre les différentes étapes du processus de dépôt et de validation
        grâce leur « feuille de route ».</em>
</p>
<p>
    <em>
        Le dépôt avant soutenance et la réception des pré-rapports favorables conditionnent la demande d’autorisation de
        soutenance au Président par la Maison du doctorat.
    </em>
</p>
