<?php

/**
 * @var Information[] $informations
 * @var InformationLangue[] $langues
 **/

$langues = [];
foreach ($informations as $information) $langues[$information->getLangue()->getId()] = $information->getLangue();

use Information\Entity\Db\Information;
use Information\Entity\Db\InformationLangue;


?>

<div id="menu-informations" class="card">
    <div class="card-header">
        <p>Informations</p>
        <p>
            <?php foreach ($langues as $langue) : ?>
                <span class="flag langue" id="<?php echo $langue->getId(); ?>">
                    <img alt="Drapeau <?php $langue->getLibelle() ?>" src="<?php echo $langue->getDrapeau(); ?>" style="width: 30px;">
                </span>
            <?php endforeach; ?>
        </p>
    </div>
    <ul class="card-body nav flex-column">
        <?php foreach ($informations as $information) : ?>
            <li class="nav-item <?php echo $information->getLangue()->getId(); ?>">
                <a class="nav-link" href="<?php echo $this->url('informations/afficher', ['id' => $information->getId()], [], true); ?>">
                    <?php echo $information->getTitre(); ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
</div>


<style>
    .selected {
        font-weight: bold;
        border: 3px solid #337ab7;
        background: #337ab7;

    }

    .flag {
        height: 30px;
        display: inline-block;
        margin: 5px;
    }

    .langue {
        cursor: pointer;
    }
</style>

<script>
    function showBonneLangue(langue) {
        $('#menu-informations li').hide();
        $('span.langue').removeClass('selected');
        $('#menu-informations li.' + langue).show();
        $('span.langue#' + langue).addClass('selected');
    }

    showBonneLangue('FR');

    $(function() {
        $('span.langue').on('click', function(event) {
            let langue = $(this).attr('id');
            // $('#menu-informations li').hide();
            // $('#menu-informations li.' + langue).show();
            showBonneLangue(langue);
        });
    });
</script>