<?php

/**
 * @var Information[] $informations
 * @var InformationLangue[] $langues
 **/

$langues = [];
foreach ($informations as $information) $langues[$information->getLangue()->getId()] = $information->getLangue();

use Information\Entity\Db\Information;
use Information\Entity\Db\InformationLangue;


?>

    <ul class="nav nav-pills nav-stacked menu-secondaire informations">
        <?php foreach ($langues as $langue) : ?>
            <span class="flag langue" id="<?php echo $langue->getId(); ?>">
            <img src="<?php echo $langue->getDrapeau(); ?>" style="width: 30px;">
        </span>
        <?php endforeach; ?>

        <?php foreach ($informations as $information) : ?>
        <li class="<?php echo $information->getLangue()->getId(); ?>">
            <a href="<?php echo $this->url('informations/afficher', ['id' => $information->getId()], [], true); ?>">
            <?php echo $information->getTitre(); ?>
            </a>
        </li>
        <?php endforeach; ?>
    </ul>

<style>
    .selected {
        font-weight: bold;
        border: 3px solid #337ab7;
        background: #337ab7;

    }

    .flag {
        height: 30px;
        display: inline-block;
        margin: 5px;
    }

    .langue {
        cursor: pointer;
    }
</style>

<script>
    function showBonneLangue(langue) {
        $('ul.informations li').hide();
        $('span.langue').removeClass('selected');
        $('ul.informations li.' + langue).show();
        $('span.langue#' + langue).addClass('selected');
    }

    showBonneLangue('FR');

    $(function() {
        $('span.langue').on('click', function(event) {
            let langue = $(this).attr('id');
            // $('ul.informations li').hide();
            // $('ul.informations li.' + langue).show();
            showBonneLangue(langue);
        });
    });
</script>