<?php

/** @var string $current */

?>

<a href="<?php echo $this->url('actualite',[], [], true); ?>"
   class="btn <?php echo ($current==='actualite')?'btn-primary':'btn-secondary'; ?> menu-lateral">
    Actualités
</a>
<a href="<?php echo $this->url('offre-these',[], [], true); ?>"
   class="btn <?php echo ($current==='offre')?'btn-primary':'btn-secondary'; ?> menu-lateral">
    Offres de thèses
</a>
<a href="<?php echo $this->url('soutenances-actuelles',[], [], true); ?>"
   class="btn  <?php echo ($current==='soutenance')?'btn-primary':'btn-secondary'; ?>  menu-lateral">
    Soutenances actuelles
</a>

<style>
    .menu-lateral {
        width:100%;
        margin-top: 0.5rem;
    }

    .btn-secondary {
        background-color: rgb(0, 73, 128);
    }

    .btn-secondary:hover,
    .btn-secondary:focus  {
        background-color: rgb(13, 110, 253);
    }
</style>
