<?php

/** @var string $current */

?>

<a href="<?php echo $this->url('actualite',[], [], true); ?>"
   class="btn <?php echo ($current==='actualite')?'btn-primary focus':'btn-primary'; ?> menu-lateral">
    Actualités
</a>
<a href="<?php echo $this->url('offre-these',[], [], true); ?>"
   class="btn <?php echo ($current==='offre')?'btn-primary focus':'btn-primary'; ?> menu-lateral">
    Offres de thèses
</a>
<a href="<?php echo $this->url('soutenances-actuelles',[], [], true); ?>"
   class="btn  <?php echo ($current==='soutenance')?'btn-primary focus':'btn-primary'; ?>  menu-lateral">
    Soutenances actuelles
</a>

<style>
    .menu-lateral {
        width:100%;
        margin-top: 0.5rem;
    }
    .btn-primary.focus  {
        background-color: var(--primary-color);
    }
</style>
