<?php

/**
 * @var EcoleDoctorale[] $ecoles
 **/

use Structure\Entity\Db\EcoleDoctorale;

?>

    <ul>
        <?php foreach ($ecoles as $ecole) : ?>
            <li>
                <a
                   href="<?php echo $this->url('soutenances-par-ecole-doctorale', ['ecole' => $ecole->getId()], [], true); ?>"
                ><?php echo ($ecole->getStructure()->getSigle())??$ecole->getStructure()->getLibelle(); ?></a>
            </li>
        <?php endforeach; ?>
    </ul>
