<?php

/**
 * @var array $offre
 **/


?>

<ul>
    <?php foreach ($offre as $theme => $lien) : ?>
        <li class="nav-item">
            <?php if ($lien) : ?>
            <a
               href="<?php echo $lien; ?>" title="Lien vers l'offre des thèses du thème <?php echo $theme; ?>">
                <?php endif; ?>
                <?php echo $theme; ?>
                <?php if ($lien) : ?>
            </a>
        <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>
