<?php

/**
 * @var array $offre
 **/


?>

<div id="menu-offretheses" class="card">
    <div class="card-header">
       Offre de thèses
    </div>
    <ul class="card-body nav flex-column">
        <?php foreach ($offre as $theme => $lien) : ?>
            <li class="nav-item">
                <?php if ($lien) : ?>
                <a class="nav-link"
                   href="<?php echo $lien; ?>" title="Lien vers l'offre des thèses du thème <?php echo $theme; ?>">
                    <?php endif; ?>
                    <?php echo $theme; ?>
                    <?php if ($lien) : ?>
                </a>
            <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>