<?php
/**
 * @var These[] $theses
 */

use Application\Entity\Db\These;

$appName = $this->appInfos()->nom;
?>

<p>
    <?php echo $appName ?> vous offre une vue sur les thèses de votre unité de recherche.

</p>
<p>
    <?php echo $appName ?> permet de suivre et valider en ligne les différentes étapes de la soutenance de thèse des doctorants de votre Unité,
    de la proposition de la composition du jury à l’autorisation de soutenance.
</p>
<p>
    La réception des rapports favorables conditionne l’autorisation de soutenance par votre chef d’établissement.
</p>

