<?php
/**
 * @var These[] $theses
 */

use Application\Entity\Db\These;
?>

<p>
    SoDoct vous offre une vue sur toutes les thèses préparées dans votre UR à l’Université de Caen Normandie. Les informations sont importées d’Apogée dès l’inscription en première année de doctorat puis mises à jour en temps réel. SoDoct étant une application dédiée à la période de soutenance, seules les données sur les thèses en cours ont été fiabilisées : les thèses soutenues, transférées et abandonnées que vous avez dirigées n’apparaissent qu’à titre indicatif.
</p>
<p>
    <em>SoDoct permet à vos doctorants de déposer en ligne le fichier numérique de leur thèse un mois avant la soutenance, de décrire leur thèse en lien avec la BU pour le signalement dans <a href="http://www.theses.fr/">theses.fr</a>, d’indiquer leur choix de mise en ligne et de suivre les différentes étapes du processus de dépôt et de validation grâce leur « feuille de route ».</em>
</p>
<p>
    <em>C’est à la BU que revient la validation finale du dépôt de la thèse dans SoDoct et l’envoi au Bureau des Doctorats de la convention de mise en ligne signée par vos soins. Le bureau des doctorats  procéde dès réception à la demande d’autorisation de soutenance auprès du Président.</em>
</p>
