<?php

namespace Substitution;

use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var string $type
 * @var \Doctrine\DBAL\Result $result
 *
 * @see \Substitution\Controller\IndexController::individuAction()
 */
?>

<?php echo $this->partial('substitution/substitution/_partial/liste', [
    'type' => $type,
    'result' => $result,
    'attributes' => ['to_nom_patronymique' => 'Nom patronymique', 'to_prenom1' => 'Prénom 1', 'to_date_naissance' => 'Date de naissance'],
]); ?>
