<?php

namespace Substitution;

use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var \Doctrine\DBAL\Result $result
 *
 * @see \Substitution\Controller\IndexController::individuAction()
 */
?>

<?php $this->headTitle($this->translate("Substitutions d'individus")) ?>

<h1 class="page-header">
    <span class="fas fa-object-group"></span>
    <?php echo $this->translate("Substitutions d'individus"); ?>
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace(); ?>

<?php echo $this->partial('substitution/substitution/_partial/liste', [
    'result' => $result,
    'attributes' => ['to_nom_patronymique' => 'Nom patronymique', 'to_prenom1' => 'Prénom 1', 'to_date_naissance' => 'Date de naissance'],
    'routeName' => 'individu/voir',
    'routeParamName' => 'individu',
]); ?>
