<?php

namespace Admission\Hydrator\Document;

use Admission\Entity\Db\Document;
use Doctrine\Inflector\Inflector;
use Doctrine\Laminas\Hydrator\DoctrineObject;
use Doctrine\Persistence\ObjectManager;
use Fichier\Entity\Db\Fichier;
use Laminas\Hydrator\Strategy\BooleanStrategy;

/**
 * @author Unicaen
 */
class DocumentHydrator extends DoctrineObject
{
    public function extract(object $object): array
    {
        /** @var Document $object */
        $data = parent::extract($object);

        $data['verificationDocument'] = $object->getVerificationDocument()->first() ?: null;

        return $data; // TODO: Change the autogenerated stub
    }

    public function hydrate(array $data, object $object): object
    {
        if (isset($data['verificationDocument']) && !is_array($data['verificationDocument'])) {
            $data['verificationDocument'] = [$data['verificationDocument']];
        }
        return parent::hydrate($data, $object); // TODO: Change the autogenerated stub
    }

}