<?php

namespace Admission\Hydrator\Document;

use Admission\Entity\Db\Document;
use Doctrine\Inflector\Inflector;
use Doctrine\Laminas\Hydrator\DoctrineObject;
use Doctrine\Persistence\ObjectManager;
use Fichier\Entity\Db\Fichier;
use Laminas\Hydrator\Strategy\BooleanStrategy;

/**
 * @author Unicaen
 */
class DocumentHydrator extends DoctrineObject
{
    public function extract(object $object): array
    {
        return parent::extract($object); // TODO: Change the autogenerated stub
    }

    public function hydrate(array $data, object $object): object
    {
        return parent::hydrate($data, $object); // TODO: Change the autogenerated stub
    }

}