<?php

use Application\Entity\Db\Validation;
use Application\View\Renderer\PhpRenderer;
use Individu\Entity\Db\Individu;
use Soutenance\Entity\Proposition;
use These\Service\FichierThese\PdcData;

/**
 * @var PhpRenderer             $this
 * @var Proposition $proposition
 * @var Validation[] $validations
 * @var Validation $validation
 * @var array $logos
 * @var int $nbCodirecteur
 * @var PdcData                 $informations
 * @see
 */
?>

<style>
    body {
        font-size: 9pt;
    }

    span.warning {
        font-weight: bold;
        color: darkred;
    }

    img {
        height:2.5cm;
    }

    h1 {
        font-size: x-large;
    }
    h2 {
        font-size: large;
    }
    table {
        width:100%;
    }

    table.recapitulatif {
        border:solid 1px black;
    }

    table.recapitulatif td.head {
        font-weight: bold;
        width: 33.3%
    }

    table.composition {
        border-collapse: collapse;
    }

    table.composition th{
        border-bottom:solid 2px black;
    }

    table.composition td{
        border-bottom:solid 1px gray;
    }

    table.composition tbody tr {
        border-bottom: 1px gray solid ;
    }

    table.informations {
    }

    table.informations td.head {
        width: 50%
    }

    table.informations td.info {
        text-align: right;
    }

    table.validation {
        border-collapse: collapse;
    }

    table.validation th{
        border-bottom:solid 2px black;
    }

    table.validation td{
        border-bottom:solid 1px gray;
        margin: 1rem;
    }

    span.to-complete {
        background-color: pink;
        color: darkred;
    }

</style>
<!-- SECTION DU LOGO DE LA COMUE -------------------------------------------------------------------------------------->

<div style="width:25%; float:left; position:absolute; top: 20px; left: 20px">
    <?php if ($informations->getLogoCOMUE() !== null): ?>
        <img src="<?php echo $informations->getLogoCOMUE() ?>" />
    <?php else : ?>
        <span style='background-color:red;'>
                Logo COMUE manquant
            </span>
    <?php endif; ?>
</div>
<div style="width:25%; float:right; position:absolute; top: 20px; right: 20px ">
    <?php if ($informations->getLogoEtablissement() !== null): ?>
        <img src="<?php echo $informations->getLogoEtablissement() ?>" />
    <?php else : ?>
        <span style='background-color:red;'>
                Logo ETAB manquant
        </span>
    <?php endif; ?>
</div>

<h1 style="text-align:center; position:absolute; top: 60px; left: 30%" >
    COMUE Normandie Université <br/>
    Arrété du 25 mai 2016
</h1>

<br/>
<br/>
<br/>

<h2 style="text-align:center;">
    Année université
    <?php if ($informations->getAnneeUniversitaire() !== null) : ?>
        <?php echo $informations->getAnneeUniversitaire(); ?>
    <?php else : ?>
        <span style='background-color:red;'>
                Année universitaire manquante
        </span>
    <?php endif; ?>
    <br/>
    <u>Procès-verbal de soutenance de thèse</u>
</h2>


<p>
    <table class="jury">
        <tr>
            <td style="width:33%;"> Nom du candidat </td>
            <td> <?php echo $informations->getDoctorant(); ?> </td>
        </tr>
    <tr>
        <td> Date de soutenance </td>
        <td> <?php if ($informations->getDate() !== null): ?>
                <?php echo $informations->getDate(); ?>
            <?php else : ?>
                <span style='background-color:red;'>
                Date manquante
        </span>
            <?php endif; ?> </td>
    </tr>
</table>
</p>


<p>
    <table class="jury">
        <tr>
            <td style="width:33%;"> Résultat </td>
            <td>
                &#9744; Admis&middot;e <br/>
                &#9744; Ajourné&middot;e
            </td>
        </tr>
    </table>
</p>

<p>
<table class="jury">
    <tr>
        <td style="width:33%;"> Nom du président de jury désigné </td>
        <td> Mme / M ...................................................................................................
        </td>
    </tr>
</table>
</p>

<p>
<table class="jury">
    <tr>
        <td>
            <strong>Avis de reproduction de la thèse</strong>
            Status du dépôt effectué avant la soutenance

    <br/>
    <br/>

        &#9744; <strong>Pas de corrections demandées</strong>, le dépôt effectué avant la soutenance, conforme à la version envoyée au jury, est valide.

    <br/>
    <br/>

    &#9744; <strong>Modification / Corrections demandées </strong>(précisez) :

            <br/>
            <br/>

            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            &#9744; <strong>Modifications de forme facultatives (coquilles, ...).</strong><br/>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <u>Délai:</u> 1 mois. <strong>À défaut, la version déposée avant soutenance est valide.</strong>

            <br/>
            <br/>

            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            &#9744; <strong>Corrections majeures obligatoires</strong>.<br/>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            Joindre les corrections demandées par le jury à ce provés-verbal<br/>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <strong>Version déposée avant soutenance détruite : second dépôt obligatoire</strong><br/>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <u>Délai:</u> 3 mois. <strong>À défaut, le diplôme ne sera pas délivré.</strong>

            <br/>
            <br/>

    En cas de second dépôt, sa conformité devra être attestée par le directeur de thèse ou, à défaut, par le Président de jury.
        </td>
    </tr>
</table>
</p>

<p>
    Fait à ........................................, le ........................................
</p>

<p>
    <strong>Noms et signatures des membres du jury</strong>

    <?php $position = 0; ?>
    <table>

    <?php
    /** @var Individu $signataire */
    foreach ($informations->getSignataires() as $signataire) :
    ?>

    <?php if ($position % 2 == 0 and $position !== 0) : ?>
        </tr>
    <?php endif; ?>
    <?php if ($position % 2 == 0) : ?>
        <tr>
    <?php endif; ?>

        <td>
            <?php echo $signataire->getNomComplet(true, true, false, true); ?>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
        </td>

    <?php $position++; ?>

    <?php endforeach; ?>

        </tr>
    </table>
</p>

