<?php

/**
 * @see \Soutenance\Controller\PropositionRechercheController::indexAction()
 *
 * @var \Application\Search\SearchResultPaginator $propositions
 * @var \Application\Entity\Db\Role $role
 */

use Application\Entity\Db\Role;
use Soutenance\Entity\Proposition;
use Soutenance\Provider\Privilege\PropositionPrivileges;
use These\Provider\Privilege\ThesePrivileges;
use UnicaenApp\Util;

$canVoirThese = $this->isAllowed(ThesePrivileges::getResourceId(ThesePrivileges::THESE_CONSULTATION_FICHE));
?>

<h1 class="page-header">
    Index des propositions en cours
    <span class="badge bg-secondary">
        <?php echo $propositions->getTotalItemCount(); ?>
    </span>
</h1>

<!-- Formulaire de filtrage -->
<div class="float-start">
    <?php $loadFiltersUrl = $this->url('soutenances/recherche/filters', [], ['query' => $this->queryParams()], true); ?>
    <div class="filters" id="proposition-filters" data-url="<?php echo $loadFiltersUrl ?>">
        <!-- Contenu chargé en AJAX -->
    </div>
</div>
<div class="clearfix"></div>


<table class="table table-sm">
    <thead>
    <tr>
        <th class="title-column">
            These
        </th>
        <th>
            Doctorant
        </th>
        <th>
            Direction
        </th>
        <th>
            Structures
        </th>
        <th>
            État
        </th>
        <th>
            Actions
        </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($propositions as $proposition) : ?>
        <?php
        /** @var Proposition $proposition **/
        $these = $proposition->getThese();
        $unite = $these->getUniteRecherche();
        $canSuppression = ($this->isAllowed($these, PropositionPrivileges::PROPOSITION_SUPPRIMER_INFORMATIONS));
        ?>
        <tr>
            <td>
                <?php if ($canVoirThese) : ?>
                <a  <?php /** @see \These\Controller\TheseController::detailIdentiteAction() */ ?>
                        href="<?php echo $this->url('these/identite', ['these' => $proposition->getThese()->getId()], [] ,true); ?>">
                    <?php endif; ?>
                    <?php echo Util::truncatedString($proposition->getThese()->getTitre()); ?>
                    <?php if ($canVoirThese) : ?>
                </a>
            <?php if ($proposition->getDate()) : ?>
                <br>
                Date de soutenance prévue : <?php echo $proposition->getDate()->format('d/m/Y à H:i'); ?>
            <?php endif; ?>
            <?php endif; ?>
            </td>
            <td> <?php echo $proposition->getThese()->getDoctorant()->getIndividu(); ?> </td>
            <td>
                <?php foreach ($proposition->getThese()->getEncadrements() as $encadrement) : ?>
                    <?php if ($encadrement->getRole()->getCode() !== Role::CODE_DIRECTEUR_THESE) echo "<i>"; ?>
                    <?php echo $encadrement->getIndividu() ; ?>
                    <?php if ($encadrement->getRole()->getCode() !== Role::CODE_DIRECTEUR_THESE) echo "</i>"; ?>
                    <br/>
                <?php endforeach; ?>
            </td>
            <td>
                <?php if ($these->getEtablissement()) : ?>
                    <span class="structure etablissement"
                          title="Établissement : <?php echo $these->getEtablissement()->getStructure()->getLibelle(); ?> (<?php echo $these->getEtablissement()->getStructure()->getSourceCode(); ?>)"
                    >
                                <?php echo $these->getEtablissement()->getStructure()->getLibelle(); ?>
                            </span>
                <?php else : ?>
                    <strong style="color:darkred;">
                        Établissement  : Aucun
                    </strong>
                <?php endif; ?>
                <br/>

                <?php if ($these->getEcoleDoctorale()) : ?>
                    <span class="structure ecole-doctorale"
                          title="École doctorale : <?php echo $these->getEcoleDoctorale()->getStructure()->getLibelle(); ?> <?php echo "(".$these->getEcoleDoctorale()->getStructure()->getSigle() .")"; ?>"
                    >
                                <?php echo $these->getEcoleDoctorale()->getStructure()->getLibelle(); ?>
                            </span>
                <?php else : ?>
                    <strong style="color:darkred;">
                        École doctorale  : Aucune
                    </strong>
                <?php endif; ?>
                <br/>

                <?php if ($these->getUniteRecherche()) : ?>
                    <span class="structure unite-recherche"
                          title="Unité de recherche : <?php echo $these->getUniteRecherche()->getStructure()->getLibelle(); ?> <?php echo "(".$these->getUniteRecherche()->getStructure()->getSigle() .")"; ?>"
                    >
                                <?php echo $these->getUniteRecherche()->getStructure()->getLibelle(); ?>
                            </span>
                <?php endif; ?>
            </td>
            <td>
                <?php echo $this->etatSoutenance()->render($proposition->getEtat()); ?>
            </td>
            <td>
                <a
                    <?php /** @see \Soutenance\Controller\PropositionController::propositionAction() */ ?>
                        href="<?php echo $this->url('soutenance/proposition', ['these' => $proposition->getThese()->getId()], [], true); ?>"
                        title="Visualiser la proposition de soutenance"
                >
                    Proposition
                </a>
                <br/>
                <a
                    <?php /** @see \Soutenance\Controller\PresoutenanceController::presoutenanceAction() */ ?>
                        href="<?php echo $this->url('soutenance/presoutenance', ['these' => $proposition->getThese()->getId()], [], true); ?>"
                        title="Visualiser la préparation de la soutenance"
                >
                    Présoutenance
                </a>
                <br/>
                <?php if ($canSuppression) : ?>
                    <a
                        <?php
                        $returnUrl = $this->url('soutenances/index-structure', [], [], true);
                        /** @see \Soutenance\Controller\PropositionController::suppressionAction() */ ?>
                            href="<?php echo $this->url('soutenance/proposition/suppression', ['these' => $proposition->getThese()->getId()], ['query' => ['redirect' => $returnUrl]], true); ?>"
                            data-toggle="confirmationx" data-event="modification"
                            data-bs-toggle="tooltip"
                            data-bs-html="true"
                            title="Suppression des informations de la soutenance <br>(Une confirmation avant la suppression vous sera demandée)"
                            data-message="Attention, cela supprimera l'ensemble des informations rentrées pour cette proposition de soutenance, êtes-vous sûr(e) ?">
                        Suppression
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<style>
    #proposition-filters {
        min-width: 30px;
        min-height: 120px;
    }

    span.structure {
        display: inline-block;
        margin-bottom: 0.5rem;
        /*font-weight: 500;*/
    }
    span.etablissement {
        /*color:darkred;*/
    }

    span.ecole-doctorale {
        /*color:darkblue;*/
    }

    span.unite-recherche {
        /*color:darkgreen;*/
    }
</style>


<script>
    $(function() {
        $("#proposition-filters").addClass("loading").refresh(null, function() { $(this).removeClass("loading"); });
    });
</script>