<?php

/**
 * @see \Formation\Controller\SeanceController::indexAction()
 * @var Seance[] $seances
 */

use Formation\Entity\Db\Seance;
use Formation\Provider\Privilege\SeancePrivileges;
use Formation\Provider\Privilege\SessionPrivileges;

$canHistoriserSeance    = $this->isAllowed(SeancePrivileges::getResourceId(SeancePrivileges::SEANCE_HISTORISER));
$canSupprimerSeance     = $this->isAllowed(SeancePrivileges::getResourceId(SeancePrivileges::SEANCE_SUPPRIMER));

$canAfficherSession     = $this->isAllowed(SessionPrivileges::getResourceId(SessionPrivileges::SESSION_AFFICHER));

?>

<h1> Liste des seances </h1>

<table class="table table-sm">
    <thead>
    <tr>
        <th>Identifiant</th>
        <th>Formation liée</th>
        <th>Période</th>
        <th>Lieu</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($seances as $seance) : ?>
        <tr>
            <td> <?php echo $seance->getId(); ?> </td>
            <td>
                <?php echo $seance->getSession()->getFormation()->getLibelle(); ?>
                - #<?php echo $seance->getSession()->getIndex(); ?>
            </td>
            <td>
                <?php echo $seance->getDebut()->format('d/m/Y à H:i'); ?>
                &rightarrow;
                <?php echo $seance->getFin()->format('d/m/Y à H:i'); ?>
                <br/>
                <?php echo $seance->getDuree(); ?> h.
            </td>
            <td> <?php echo $seance->getLieu(); ?> </td>
            <td>
                <?php if ($canAfficherSession AND $seance->getSession() !== null) : ?>
                    <?php /** @see \Formation\Controller\SessionController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('formation/session/afficher', ['session' => $seance->getSession()->getId()], [], true); ?>"
                       title="Accéder à la session associée" data-bs-toggle="tooltip" data-bs-html="true"
                    >
                    <span class="fas fa-list-alt"></span>
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriserSeance) : ?>
                    <?php if ($seance->estNonHistorise()) : ?>
                        <?php /** @see \Formation\Controller\SeanceController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('formation/seance/historiser', ['seance' => $seance->getId()], [], true); ?>"
                           title="Historiser la seance" data-bs-toggle="tooltip" data-bs-html="true"
                        >
                            <span class="icon icon-historiser"></span>
                        </a>
                    <?php else : ?>
                        <?php /** @see \Formation\Controller\SeanceController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url('formation/seance/restaurer', ['seance' => $seance->getId()], [], true); ?>"
                           title="Restaurer la seance" data-bs-toggle="tooltip" data-bs-html="true"
                        >
                            <span class="icon icon-restaurer"></span>
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canSupprimerSeance) : ?>
                    <?php /** @see \Formation\Controller\SeanceController::supprimerAction() */?>
                    <a href="<?php echo $this->url('formation/seance/supprimer',['seance' => $seance->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification"
                       title="Suppression de la seance #<?php echo $seance->getId(); ?>" data-bs-toggle="tooltip" data-bs-html="true">
                        <span class="icon icon-detruire"></span>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>