<?php

use Application\View\Renderer\PhpRenderer;
use Substitution\Constants;

/**
 * @var PhpRenderer $this
 * @var string $type
 * @var \Doctrine\DBAL\Result $result
 * @var string[] $attributes [name => label]
 * @var string $routeName
 * @var string $routeParamName
 */

$tableName = (Constants::USE_TABLE_PREFIX ? 'pre_' : '') . $type;
$null = '<span class="text-secondary">NULL</span>';
?>

<?php $this->headTitle($this->translate("Doublons : $type")) ?>

<h1 class="page-header">
    <span class="far fa-clone"></span>
    <?php echo $this->translate("Doublons") ?> <span class="badge bg-primary text-uppercase p-1"><?php echo $type ?></span>
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace(); ?>

<p class="lead">
    Voici la liste des enregistrements considérés en doublon (au regard de leur
    <abbr title="Valeur calculée pour un enregistrement à partir de ses attributs discriminants et utilisé pour trouver les doublons">NPD</abbr>)
    et non encore détectés et substitués automatiquement (ce qui ne devrait pas arriver théoriquement).
    Si la liste n'est pas vide, vérifiez que le trigger de détection est bien activé sur la table
    <span class="monospace"><?php echo strtoupper($tableName) ?></span>.
</p>

<?php if ($count = $result->rowCount()): ?>
    <p><?php echo $count ?> doublons trouvés.</p>

    <table class="table table-bordered table-extra-condensed">
        <tr>
            <th>NPD</th>
            <th>Id</th>
            <th>SOURCE_CODE</th>
            <th><?php echo implode(', ', $attributes) ?></th>
        </tr>
        <?php while ($row = $result->fetchAssociative()): ?>
            <?php
            $url = sprintf(
                '<a href="%s"><span title="Accéder à la fiche détaillée de cet enregistrement en doublon">%s</span></a>',
                $routeName ? $this->url($routeName, [$routeParamName => $row['id']]) : "#",
                $row['id'],
            );
            ?>
            <tr>
                <td><?php echo $row['npd'] ?></td>
                <td><?php echo $url ?></td>
                <td><?php echo $row['source_code'] ?></td>
                <td><?php echo implode(', ', array_map(fn($name) => $row[$name] ?? $null, array_keys($attributes))) ?></td>
            </tr>
        <?php endwhile ?>
    </table>
<?php else: ?>
    <p>Aucun.</p>
<?php endif ?>
