<?php

use Application\Entity\Db\UniteRecherche;
use Application\Provider\Privilege\StructurePrivileges;
use Application\Provider\Privilege\SubstitutionPrivileges;

/**
 * @var UniteRecherche[] $unites
 *
 * @see \Application\Controller\UniteRechercheController::indexAction()
 */

$canModifier = $this->isAllowed(StructurePrivileges::getResourceId(StructurePrivileges::STRUCTURE_MODIFICATION_TOUTES_STRUCTURES));
$canAjouter = $this->isAllowed(StructurePrivileges::getResourceId(StructurePrivileges::STRUCTURE_MODIFICATION_TOUTES_STRUCTURES));
$canSubstituer = $this->isAllowed(SubstitutionPrivileges::getResourceId(SubstitutionPrivileges::SUBSTITUTION_CONSULTATION_TOUTES_STRUCTURES))
    OR $this->isAllowed(SubstitutionPrivileges::getResourceId(SubstitutionPrivileges::SUBSTITUTION_CONSULTATION_SA_STRUCTURE));
?>


<?php $this->headTitle($this->translate("Unités de recherche")) ?>

<h1 class="page-header first">
    <?php echo $this->translate("Unités de recherche") ?>
    <span class="badge badge-secondary"><?php echo count($unites); ?></span>
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace() ?>

<?php if ($canAjouter): ?>

    <a href="<?php echo $this->url('unite-recherche/ajouter', [], [], true) ?>"
       class="btn btn-primary"
       title="<?php echo $this->translate("Créer une nouvelle unité de recherche"); ?>">
        <span class="icon icon-plus"></span>
        <?php echo $this->translate("Ajouter une nouvelle unité de recherche"); ?>
    </a>
<?php endif ?>

<div>
    <table class="table table-sm">
        <thead>
        <tr>
            <th> Libellé</th>
            <th> Source</th>
            <th> Code</th>
            <th> Sigle</th>
            <th> Identifiant RNSR</th>
<!--            <th> #these</th>-->
            <th> Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($unites as $unite): ?>

            <?php
            $historisee = (!$unite->estNonHistorise());
            $hasSousStructure = !($unite->getStructure()->getStructuresSubstituees()->isEmpty());
            $canModifierCetteUnite = $this->isAllowed($unite->getStructure(),StructurePrivileges::STRUCTURE_MODIFICATION_SES_STRUCTURES);
            ?>

            <tr>
                <td>
                    <a href="<?php echo $this->url('unite-recherche/information', ['structure' => $unite->getStructure()->getId()], [], true); ?>">
                        <?php echo $unite->getLibelle(); ?>
                        <?php if ($unite->getStructure()->estFermee()) : ?>
                            &nbsp;<span class="badge badge-danger">Structure fermée</span>
                        <?php endif; ?>
                    </a>
                </td>
                <td>
                    <?php echo $unite->getSource(); ?>
                </td>
                <td>
                    <?php echo $unite->getStructure()->getCode(); ?>
                </td>
                <td> <?php echo $unite->getSigle(); ?> </td>
                <td> <?php echo $unite->getRNSR(); ?> </td>
<!--                <td> --><?php //echo count($unite->getTheses()); ?><!-- </td>-->
                <td>
                    <?php if (($canModifier OR $canModifierCetteUnite) && !$historisee) : ?>
                        <a href="<?php echo $this->url('unite-recherche/supprimer', ['structure' => $unite->getStructure()->getId()], [], true); ?>"
                           title="Historiser l'établissement">
                            <span class="icon icon-delete iconly"></span>
                        </a>
                    <?php endif; ?>

                    <?php if ($canSubstituer && !$historisee && $hasSousStructure) : ?>
                        <a href="<?php echo $this->url('substitution-modifier', ['cible' => $unite->getStructure()->getId(), [], true]); ?>"
                           title="Historiser l'établissement">
                            <span class="fas fa-link" title="Éditer la substitution"></span>
                        </a>
                    <?php endif; ?>

                    <?php if (($canModifier OR $canModifierCetteUnite) && $historisee) : ?>
                        <a href="<?php echo $this->url('unite-recherche/restaurer', ['structure' => $unite->getStructure()->getId()], [], true); ?>"
                           title="Restaurer l'établissement">
                            Restaurer
                        </a>
                    <?php endif; ?>
                </td>
            </tr>

        <?php endforeach; ?>

        </tbody>
    </table>
</div>