<?php

use Application\Entity\Db\StructureConcreteInterface;
use Application\Provider\Privilege\UniteRecherchePrivileges;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var StructureConcreteInterface[] $structuresPrincipales
 * @var string      $selected
 * @var array|null  $etablissementIndividus
 */
?>

<?php $this->headTitle($this->translate("Unités de recherche")) ?>

<h1 class="page-header first">
    <?php echo $this->translate("Unités de recherche") ?>
    <span class="badge"><?php echo count($structuresPrincipales); ?></span>
</h1>
<?php echo $this->messenger()->addCurrentMessagesFromFlashMessenger() ?>

<div>
    <?php echo $this->structureArrayHelper()->generateTable($structuresPrincipales, $roles, $effectifs, $selected, $this); ?>
</div>

<?php if ($this->isAllowed(UniteRecherchePrivileges::getResourceId(UniteRecherchePrivileges::UNITE_RECH_MODIFICATION))): ?>
    <?php $url = $this->url('unite-recherche/ajouter', [], [], true) ?>
    <a class="btn btn-default btn-sm" href="<?php echo $url ?>"
       title="<?php echo $this->translate("Créer une nouvelle unité de recherche");?>">
        <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate("Ajouter");?>
    </a>
<?php endif ?>



<script type="text/javascript">
    $(function () {
        $(".retirer-individu").click(function() {
            var individu = $(this).data('individu');
            return confirm("<?php echo $this->translate("Êtes-vous sûr-e de vouloir retirer ");?>" + "'" + individu + "'" + " " + "<?php echo $this->translate("de la liste des membres ?");?>");
        });
        $(".supprimer-unite-recherche").click(function() {
            var unite = $(this).data('unite-recherche');
            return confirm("<?php echo $this->translate("Êtes-vous sûr-e de vouloir supprimer l'unite de recherche ");?>" + "'" + unite + "'" + " ? ");
        });
    });
</script>