<?php

namespace Admission\Hydrator\ConventionFormationDoctorale;

use Doctrine\Laminas\Hydrator\DoctrineObject;

/**
 * @author Unicaen
 */
class ConventionFormationDoctoraleHydrator extends DoctrineObject
{
    public function extract(object $object): array
    {
        return parent::extract($object); // TODO: Change the autogenerated stub
    }

    public function hydrate(array $data, object $object): object
    {
        //Si l'input motivationDemandeConfidentialite n'est pas présent, on met à null la valeurs du champ relié
        if (!array_key_exists("motivationDemandeConfidentialite", $data)) {
            $data["motivationDemandeConfidentialite"] = null;
        }
        return parent::hydrate($data, $object); // TODO: Change the autogenerated stub
    }

}