<?php

use Application\Entity\Db\Variable;
use Structure\Controller\StructureController;
use Structure\Entity\Db\Etablissement;
use Structure\Provider\Privilege\StructurePrivileges;

/**
 * @var Variable[] $variables
 * @var Etablissement $etablissement
 *
 * @see \Structure\Controller\EtablissementController::indexAction()
 */

$appName = $this->appInfos()->nom;

$canModifier = $this->isAllowed(StructurePrivileges::getResourceId(StructurePrivileges::STRUCTURE_MODIFICATION_TOUTES_STRUCTURES));
?>


<?php $this->headTitle($this->translate("Variables")) ?>

<p class="float-end">
    <?php if ($canModifier): ?>
        <a href="<?php echo $this->url('etablissement/saisir-variable', ['etablissement'=> $etablissement->getId()], [], true); ?>"
           class="btn btn-primary action ajax-modal" data-event="modification"
        >
            <span class="icon icon-plus"></span> Ajouter une variable
        </a>
    <?php endif ?>
</p>

<h2 class="first">
    <?php echo $this->translate("Variables") ?>
    <span class="badge bg-secondary">
        <?php echo count($variables); ?>
    </span>
</h2>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace() ?>

<div>
    <table class="table table-sm">
        <thead>
        <tr>
            <th> Source </th>
            <th> Code </th>
            <th> Description </th>
            <th> Valeur </th>
            <th> Début de validité </th>
            <th> Fin de validité </th>
            <th> Actions </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($variables as $variable): ?>

            <?php
                $historisee = (!$etablissement->estNonHistorise());
            ?>

            <tr>
                <td>
                    <?php echo $variable->getSource(); ?>
                </td>
                <td>
                    <?php echo $variable->getCode(); ?>
                </td>
                <td>
                    <?php echo $variable->getDescription(); ?>
                </td>
                <td>
                    <?php echo $variable->getValeur(); ?>
                </td>
                <td>
                    <?php echo $variable->getDateDebutValidite()?->format('d/m/Y'); ?>
                </td>
                <td>
                    <?php echo $variable->getDateFinValidite()?->format('d/m/Y'); ?>
                </td>
                <td>
                    <?php if ((!$variable->getSource()->getImportable() && $canModifier) && !$historisee) : ?>
                        <?php
                        $redirectUrl =  $this->url('etablissement/voir', ['etablissement'=> $etablissement->getId()], ['query' => ['tab' => StructureController::TAB_variables]], true);
                        ?>
                        <a  <?php /**  @see \Structure\Controller\VariableController::saisirVariableAction() */ ?>
                                class="ajax-modal" data-event="modification"
                                href="<?php echo $this->url('etablissement/saisir-variable', ['id' => $variable->getId(), 'etablissement'=> $etablissement->getId()], [], true); ?>">
                            <span class="icon icon-edit iconly" title="Modifier la variable"></span>
                        </a>
                        <a  <?php /**  @see \Structure\Controller\VariableController::supprimerAction() */ ?>
                                data-event="modification" data-toggle="confirmationx"
                                href="<?php echo $this->url('etablissement/supprimer-variable', ['id' => $variable->getId()], ['query' => ['redirect' => $redirectUrl]], true); ?>">
                                <span class="icon icon-delete iconly text-danger" title="Supprimer la variable"></span>
                        </a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>