<?php
/**
 * @var \Structure\Entity\Db\Etablissement $entity
 * @var bool $includeGotoDetailsLink
 */
?>

<h3>
    Informations générales
</h3>
<dl>
    <dt>Libelle :</dt>
    <dd><?php echo $entity->getStructure()->getLibelle(); ?></dd>
    <dt>Code :</dt>
    <dd><?php echo $entity->getStructure()->getCode(); ?></dd>
    <dt>Sigle :</dt>
    <dd><?php echo $entity->getStructure()->getSigle() ?: "(Non renseigné)"; ?></dd>
    <dt>Site internet :</dt>
    <dd><?php echo $entity->getStructure()->getSiteWeb() ?: "(Non renseigné)"; ?></dd>
</dl>

<h3>
    Coordonnées
</h3>
<dl>
    <dt>Adresse :</dt>
    <dd><?php echo $entity->getStructure()->getAdresse() ?: "(Non renseignée)"; ?></dd>
    <dt>Téléphone :</dt>
    <dd><?php echo $entity->getStructure()->getTelephone() ?: "(Non renseigné)"; ?></dd>
    <dt>Fax :</dt>
    <dd><?php echo $entity->getStructure()->getFax() ?: "(Non renseigné)"; ?></dd>
</dl>

<h3>
    Contact
</h3>
<dl>
    <dt>Adresse électronique :</dt>
    <dd><?php echo $entity->getStructure()->getEmail() ?: "(Non renseignée)"; ?></dd>
    <dt>Adresse électronique d'Assistance:</dt>
    <dd><?php echo $entity->getEmailAssistance() ?: "(Non renseignée)"; ?></dd>
    <dt>Adresse électronique pour les aspects Bibliothèque :</dt>
    <dd><?php echo $entity->getEmailBibliotheque() ?: "(Non renseignée)"; ?></dd>
    <dt>Adresse électronique pour les aspects Doctorat :</dt>
    <dd><?php echo $entity->getEmailDoctorat() ?: "(Non renseignée)"; ?></dd>
</dl>

<h3>
    Informations techniques
</h3>
<dl>
    <dt>Id interne :</dt>
    <dd><?php echo $entity->getId(); ?></dd>
    <dt>Id interne structure :</dt>
    <dd><?php echo $entity->getStructure()->getId(); ?></dd>

    <dt>Source Code :</dt>
    <dd><?php echo $entity->getStructure()->getSourceCode(); ?></dd>
    <dt>IdRef :</dt>
    <dd>
        <?php if ($entity->getStructure()->getIdRef() !== null and trim($entity->getStructure()->getIdRef()) !== "") : ?>
            <?php echo $this->idrefLink($entity->getStructure()->getIdRef()); ?>
        <?php else : ?>
            (Non renseigné)
        <?php endif; ?>
    </dd>
    <dt>Id HAL :</dt>
    <dd>
        <?php if ($entity->getStructure()->getIdHal() !== null and trim($entity->getStructure()->getIdHal()) !== "") : ?>
            <?php echo $entity->getStructure()->getIdHal(); ?>
        <?php else : ?>
            (Non renseigné)
        <?php endif; ?>
    </dd>
    <dt>Domaine :</dt>
    <dd><?php echo $entity->getDomaine() ?: "(Non renseigné)"; ?></dd>

    <dt>Création</dt>
    <dd><?php echo $entity->getHistoCreation()->format('d/m/Y à H:i:s') ?></dd>

    <dt>Modification</dt>
    <?php if ($entity->getHistoModification() && $entity->getHistoModification() <> $entity->getHistoCreation()): ?>
        <dd><?php echo $entity->getHistoModification()->format('d/m/Y à H:i:s') ?></dd>
    <?php else: ?>
        <dd>(Aucune)</dd>
    <?php endif ?>
</dl>

<?php if ($entity->estHistorise()): ?>
    <h3 class="text-danger">
        Historisé
    </h3>
    <dl class="text-danger">
        <dt>Date :</dt>
        <dd><?php echo $entity->getHistoDestruction()->format('d/m/Y à H:i:s') ?></dd>
    </dl>
<?php endif ?>

<?php if ($includeGotoDetailsLink ?? false): ?>
    <a href="<?php echo $this->url('etablissement/voir', ['etablissement' => $entity->getId()], [], true); ?>"
       class="action"><span class="icon icon-voir"></span> Voir la fiche détaillée de cet établissement
    </a>
<?php endif ?>
