<?php

namespace Soutenance\Provider\Template;

class MailTemplates
{
    const TRANSMETTRE_DOCUMENTS_DIRECTION       = "TRANSMETTRE_DOCUMENTS_DIRECTION";

    /** ENGAGEMENT D'IMPARTIALITE *************************************************************************************/
    const DEMANDE_ENGAGEMENT_IMPARTIALITE       = 'DEMANDE_ENGAGEMENT_IMPARTIALITE';
    const SIGNATURE_ENGAGEMENT_IMPARTIALITE     = 'SIGNATURE_ENGAGEMENT_IMPARTIALITE';
    const REFUS_ENGAGEMENT_IMPARTIALITE         = 'REFUS_ENGAGEMENT_IMPARTIALITE';
    const ANNULATION_ENGAGEMENT_IMPARTIALITE    = 'ANNULATION_ENGAGEMENT_IMPARTIALITE';
}