<?php

namespace Soutenance\Provider\Template;

class PdfTemplates {

    const SOUTENANCE_THESE_SERMENT_DU_DOCTEUR = "SOUTENANCE_THESE_SERMENT_DU_DOCTEUR";
    const SOUTENANCE_HDR_SERMENT_DU_DOCTEUR = "SOUTENANCE_HDR_SERMENT_DU_DOCTEUR";

}