<?php

namespace Soutenance\Provider\Template;

class TexteTemplates {

    const SOUTENANCE_HDR_ENGAGEMENT_IMPARTIALITE = 'SOUTENANCE_HDR_ENGAGEMENT_IMPARTIALITE';
    const SOUTENANCE_THESE_ENGAGEMENT_IMPARTIALITE = 'SOUTENANCE_THESE_ENGAGEMENT_IMPARTIALITE';
}