<?php

namespace HDR\Fieldset\Generalites;

use Application\Entity\Db\VersionDiplome;
use Application\Service\Discipline\DisciplineServiceAwareTrait;
use Application\Service\VersionDiplome\VersionDiplomeServiceAwareTrait;
use HDR\Entity\Db\HDR;
use Laminas\Form\Element\Date;
use Laminas\Form\Element\Hidden;
use Laminas\Form\Element\Radio;
use Laminas\Form\Element\Select;
use Laminas\Form\Element\Text;
use Laminas\Form\Fieldset;
use Laminas\Form\FormInterface;
use Laminas\InputFilter\InputFilterProviderInterface;
use Laminas\Validator\Callback;
use Structure\Entity\Db\Etablissement;
use Structure\Service\Etablissement\EtablissementServiceAwareTrait;
use UnicaenApp\Form\Element\SearchAndSelect;

class GeneralitesFieldset extends Fieldset implements InputFilterProviderInterface
{
    use DisciplineServiceAwareTrait;
    use VersionDiplomeServiceAwareTrait;
    use EtablissementServiceAwareTrait;

    private ?Etablissement $etablissement = null;
    private string $urlAutocompleteIndividu;

    public function setEtablissement(?Etablissement $etablissement): void
    {
        $this->etablissement = $etablissement;
    }

    public function setUrlAutocompleteIndividu(string $urlAutocompleteIndividu): void
    {
        $this->urlAutocompleteIndividu = $urlAutocompleteIndividu;
    }

    public function prepareElement(FormInterface $form): void
    {
        /** @var HDR $hdr */
        $hdr = $this->getObject();
        $this->get('candidat')->setAttribute('readonly', $hdr->getCandidat());

        parent::prepareElement($form); // TODO: Change the autogenerated stub
    }

    public function init()
    {
        $this->add([
            'type' => Hidden::class,
            'name' => 'id',
        ]);

        $doctorant = new SearchAndSelect('candidat', [
            'label' => "Candidat·e <span class='icon icon-obligatoire' style='color: darkred;font-size: 0.8em;' data-bs-toggle='tooltip' title='Obligatoire'></span> :",
            'label_options' => [ 'disable_html_escape' => true, ],
            ]);
        $doctorant
            ->setAutocompleteSource($this->urlAutocompleteIndividu)
            ->setRequired()
            ->setSelectionRequired(true)
            ->setAttributes([
                'id' => 'candidat',
                'placeholder' => "Rechercher un·e candidat·e ...",
            ]);
        $this->add($doctorant);

        $this->add([
            'type' => Select::class,
            'name' => 'discipline',
            'options' => [
                'label' => "Discipline :",
                'value_options' => $this->disciplineService->getDisciplinesAsOptions("libelle", "ASC", "id"),
                'empty_option' => "Sélectionner une discipline",
            ],
            'attributes' => [
                'id' => 'discipline',
                'class' => 'selectpicker show-menu-arrow',
                'data-live-search' => 'true',
                'data-bs-html' => 'true',
            ]
        ]);

        if ($this->etablissement !== null) {
            $this->add([
                'type' => Select::class,
                'name' => 'versionDiplome',
                'options' => [
                    'label' => "Version de diplôme :",
                    'value_options' => array_map(
                        fn(VersionDiplome $vdi) => $vdi->getLibelleLong(),
                        $this->versionDiplomeService->getRepository()->findForEtablissement($this->etablissement)
                    ),
                    'empty_option' => "Sélectionner une version de diplôme",
                ],
                'attributes' => [
                    'id' => 'versionDiplome',
                    'class' => 'selectpicker show-menu-arrow',
                    'data-live-search' => 'true',
                    'data-bs-html' => 'true',
                ]
            ]);
        }

        $this->add(
            (new Text('cnu'))
                ->setLabel("CNU : ")
        );

        $this->add([
            'type' => Radio::class,
            'name' => 'confidentialite',
            'options' => [
                'value_options' => [
                    0 => "Non confidentielle ",
                    1 => "Confidentielle ",
                ],
            ],
            'attributes' => [
                'id' => 'confidentialite',
            ],
        ]);

        $this->add([
            'type' => Date::class,
            'name' => 'dateFinConfidentialite',
            'options' => [
                'label' => "Date de fin de confidentialité <span class='icon icon-obligatoire' style='color: darkred;font-size: 0.8em;' data-bs-toggle='tooltip' title='Obligatoire'></span> : ",
                'label_options' => [ 'disable_html_escape' => true, ],
            ],
            'attributes' => [
                'id' => 'fin-confidentialite',
            ],
        ]);

        $this->add(
            (new Date("datePremiereInscription"))
                ->setLabel("Date de première inscription :")
        );

        $this->add([
            'type' => Date::class,
            'name' => 'dateAbandon',
            'options' => [
                'label' => "Date d'abandon : ",
            ],
            'attributes' => [
                'id' => 'date-abandon',
            ],
        ]);

        $this->add(
            (new Select("resultat"))
                ->setEmptyOption("Sélectionnez une option")
                ->setValueOptions([
                    HDR::RESULTAT_AJOURNE => HDR::$resultatsLibellesLongs[HDR::RESULTAT_AJOURNE],
                    HDR::RESULTAT_ADMIS => HDR::$resultatsLibellesLongs[HDR::RESULTAT_ADMIS],
                ])
                ->setLabel("Résultat : ")
                ->setAttributes([
                    'class' => 'selectpicker show-tick',
                    'id' => "resultat"
                ])
        );
    }

    public function getInputFilterSpecification(): array
    {
        return [
            'datePremiereInscription' => [
                'required' => false,
            ],
            // NB : ne pas déclarer le SearchAndSelect ici, sinon pas de validation correcte !
//            'candidat' => [
//                'required' => true,
//            ],
            'discipline' => [
                'required' => false,
            ],
            'versionDiplome' => [
                'required' => false,
            ],
            'cnu' => [
                'required' => false,
            ],
            'confidentialite' => [
                'name' => 'confidentialite',
                'required' => false,
                'validators' => [
                    [
                        'name' => Callback::class,
                        'options' => [
                            'messages' => [
                                Callback::INVALID_VALUE => "La date de fin de confidentialité est requise",
                            ],
                            'callback' => function ($value, $context = []) {
                                if ((isset($context['confidentialite']) && $context['confidentialite'] === "1") && empty($context['dateFinConfidentialite'])) {
                                    return false;
                                }
                                return true;
                            },
                            'break_chain_on_failure' => true,
                        ],
                    ],
                ],
            ],
            'dateFinConfidentialite' => [
                'required' => false,
            ],
            'dateAbandon' => [
                'required' => false,
            ],
            'resultat' => [
                'required' => false,
            ],
        ];
    }
}