<?php

use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var \Doctrine\DBAL\Result $result
 * @var \Doctrine\DBAL\Result $operations
 * @var string $logRoute
 */

$operation = $this->queryParams()['operation'] ?? null;
?>

<p class="lead">

</p>

<?php if ($count = $result->rowCount()): ?>
    <p><?php echo $count ?> lignes de logs trouvées.</p>

    <div class="card mb-4">
        <div class="card-header p-2">Filtres</div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                Opérations :
                <span class="<?php echo ($o = '*') === $operation ? 'border border-success' : 'text-bg-light' ?> p-1 mx-1">
                    <a href="<?php echo $this->url($logRoute, [], ['query' => ['operation' => $o]], true) ?>" title="Toutes"><?php echo $o ?></a>
                </span>
                <?php foreach ($operations->fetchFirstColumn() as $o): ?>
                    <span class="<?php echo $o === $operation ? 'border border-success' : 'text-bg-light' ?> p-1 mx-1">
                        <a href="<?php echo $this->url($logRoute, [], ['query' => ['operation' => $o]], true) ?>"><?php echo $o ?></a>
                    </span>
                <?php endforeach; ?>
            </li>
        </ul>
    </div>

    <table class="table table-bordered table-extra-condensed">
        <tr>
            <th>Id</th>
            <th>Opération</th>
            <th>Substitué</th>
            <th>Substituant</th>
            <th>NPD</th>
            <th>Log</th>
            <th>Date</th>
        </tr>
        <?php while ($row = $result->fetchAssociative()): ?>
            <tr>
                <td><?php echo $row['id'] ?></td>
                <td><?php echo $row['operation'] ?></td>
                <td><?php echo $row['substitue_id'] ?></td>
                <td><?php echo $row['substituant_id'] ?></td>
                <td><?php echo $row['npd'] ?></td>
                <td><?php echo $row['log'] ?></td>
                <td><?php echo $row['created_on'] ?></td>
            </tr>
        <?php endwhile ?>
    </table>
<?php else: ?>
    <p>Aucun.</p>
<?php endif ?>
