<?php
/**
 * @var \Laminas\Form\Form $form
 */

use Acteur\Entity\Db\ActeurHDR;
use Application\Entity\Db\Role;
use HDR\Entity\Db\HDR;

?>

<fieldset>
    <?php
        $fs = $form->get('direction');
        $form->prepare();
        /** @var HDR $hdr */
        $hdr = $fs->getObject();
        $estImportable = $hdr?->getSource()->getImportable();
        echo $this->form()->openTag($form);
    ?>

    <div class="mb-3 these-saisie-form-section">
        <h3 class="these-saisie-title-section">Garant·e de HDR <span class="icon icon-information" data-bs-toggle="tooltip"
                                                                              title="Un·e seul·e garant·e de HDR"></span></h3>
        <div class="row directeur">
            <div class="col-md-4">
                <div class="row">
                    <div class="col-md-10">
                        <?php echo $this->formControlGroup($fs->get('garant-individu')); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-10">
                        <?php if(!$estImportable){ ?>
                            <?php echo $this->formControlGroup($fs->get('garant-qualite')); ?>
                        <?php }else{
                            /** @var ActeurHDR $garant */
                            $garant = $hdr->getActeursByRoleCode(Role::CODE_HDR_GARANT)->first();
                            echo "Qualité : ";
                            echo trim($garant?->getLibelleQualite()) !== null ? $garant->getLibelleQualite() : "<i>Aucune qualité renseignée</i>";
                        } ?>
                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <?php echo $this->formControlGroup($fs->get('garant-etablissement')); ?>
<!--                --><?php //echo $this->formControlGroup($fs->get('garant-ecoleDoctorale')); ?>
                <?php echo $this->formControlGroup($fs->get('garant-uniteRecherche')); ?>
            </div>
            <div class="col-md-2">

            </div>
            <?php if(!$estImportable): ?>
                <div class="col-md-1 pull-right">
                    <span data-target-id="directeur" class="erase-direction-acteur icon icon-historiser"
                          title="Vider les champs concernant le garant"></span>
                </div>
            <?php endif ?>
        </div>
    </div>
    <?php if($fs->useAsBaseFieldset()): ?>
        <?php echo $this->formHidden($form->get('security')); ?>
        <?php echo $this->formControlGroup($form->get('submit')); ?>
        <?php echo $this->form()->closeTag(); ?>
        <script>
             $(function () {
                $('[data-bs-toggle="tooltip"]').tooltip({});
                 $('select.selectpicker').selectpicker(); // ne pas appliquer le selectpicker sur TOUS les <select> !
             });
        </script>
    <?php endif ?>
</fieldset>


<script>
    $(function() {
        const updateCodirecteurDiv = function($enabler) {
            const codirId = $enabler.data('codirecteur-id');
            if ($enabler.is(':checked')) {
                $("div.codirecteur" + codirId).show();
                if (codirId === 1) {
                    // activer le 1er codir redonne la possibilité d'activer le 2nd
                    $(".codirecteur-enabler").not($enabler).prop('disabled', false);
                }
            } else {
                if (codirId === 1) {
                    // désactiver le 1er codir désactive et interdit d'activer le 2nd
                    $("div.codirecteur").hide();
                    $(".codirecteur-enabler").prop('checked', false);
                    $(".codirecteur-enabler").not($enabler).prop('disabled', true);
                } else {
                    $("div.codirecteur" + codirId).hide();
                }
            }
        };
        $(".codirecteur-enabler").on('change', function() {
            updateCodirecteurDiv($(this));
        });
        $(".codirecteur-enabler").each(function() {
            updateCodirecteurDiv($(this));
        });

        $('.erase-direction-acteur').click(function() {
            let container = $("div." + $(this).data('target-id'));
            container.find("input").val('');
            container.find("select").val(null).trigger('change');
        });
    });
</script>