<?php
/**
 * @var \Application\View\Renderer\PhpRenderer $this
 * @var Form $form
 */

use HDR\Entity\Db\HDR;
use Laminas\Form\Form;
use HDR\Fieldset\Generalites\GeneralitesFieldset;

?>

<fieldset>
    <?php
        /** @var GeneralitesFieldset $fs */
        $fs = $form->get('generalites');
        /** @var HDR $hdr */
        $hdr = $fs->getObject();
        $form->prepare();
        echo $this->form()->openTag($form);
    ?>
    <div class="row these-saisie-form-section">
        <div class="col-8">
            <h3 class="these-saisie-title-section">
                Informations générales
            </h3>
            <div class="row">
                <div class="col-md-9">
                    <?php echo $this->formControlGroup($fs->get('candidat')) ?>
                </div>
            </div>

            <div class="row">
                <div id="etablissement-select2" class="col-md-9">
                    <?php
                    /** @var \UnicaenApp\Form\Element\Select2 $etablissementSelect */
                    $etablissementSelect = $fs->get('etablissement');
                    $etablissementSelect->setDropdownParent('$("#etablissement-select2")');
                    echo $this->formControlGroup($etablissementSelect);
                    ?>
                </div>
            </div>

            <div class="row">
                <div id="versionDiplome-select2" class="col-md-9">
                    <?php
                    /** @var \UnicaenApp\Form\Element\Select2 $versionDiplomeSelect */
                    $versionDiplomeSelect = $fs->get('versionDiplome');
                    $versionDiplomeSelect->setDropdownParent('$("#versionDiplome-select2")');
                    $formSelect2 = $this->formSelect2();
                    //$formSelect2->setTemplateForDataAttribute('<small><code>%s</code></small>', 'extra');
                    echo $this->formControlGroup($fs->get('versionDiplome'), $formSelect2);
                    ?>
                </div>
            </div>

            <div class="row mb-3">
                <div class="col-md-9">
                    <?php echo $this->formControlGroup($fs->get('cnu')) ?>
                </div>
            </div>

            <div class="row">
                <h3 class="these-saisie-title-section">
                    Confidentialité de l'HDR
                </h3>
                <div class="col-md-9">
                    <?php echo $this->formControlGroup($fs->get('confidentialite')); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-9" id="date-fin-confidentialite">
                    <?php echo $this->formControlGroup($fs->get('dateFinConfidentialite')); ?>
                </div>
            </div>

        </div>
    </div>

    <?php if($hdr->getId() !== null && !$hdr->getSource()->getImportable()): ?>
        <div class="separator"></div>
        <div class="row these-saisie-form-section">
            <div class="row ">
                <h3 class="these-saisie-title-section">
                    Gestion de l'HDR
                </h3>
                <div class="col-4">
                    <?php echo $this->formControlGroup($fs->get('dateAbandon')); ?>
                </div>
            </div>

<!--            <div class="row">-->
<!--                <div class="col-4">-->
<!--                    --><?php //echo $this->formControlGroup($fs->get('resultat')); ?>
<!--                </div>-->
<!--            </div>-->
        </div>
    <?php endif ?>

    <?php if($fs->useAsBaseFieldset()): ?>
        <?php echo $this->formHidden($form->get('security')); ?>
        <?php echo $this->formControlGroup($form->get('submit')); ?>
        <?php echo $this->form()->closeTag(); ?>
        <script>
            $('select.selectpicker').selectpicker(); // ne pas appliquer le selectpicker sur TOUS les <select> !
            $(function () {
                $('[data-bs-toggle="tooltip"]').tooltip({});
            });
        </script>
    <?php endif ?>

</fieldset>


<script>
    $(function () {
        const $etablissementSelect2 = $('#etablissement');
        const $versionDiplomeSelect2 = $("#versionDiplome");

        const updateVersionDiplomeOptionsForSelectedEtablissement = function() {
            // filtrage des versions de diplômes en fonction de l'établissement sélectionné
            const sourcecode = $etablissementSelect2.select2('data')[0].sourcecode;
            if (!sourcecode) {
                $versionDiplomeSelect2.val('').attr('disabled', 'disabled');
                return;
            }
            const $options = $versionDiplomeSelect2.find("option.etablissement");
            const $optionsToShow = $options.filter('.' + sourcecode);
            $options.attr('disabled', 'disabled');
            $optionsToShow.removeAttr('disabled');
            $versionDiplomeSelect2.trigger('change'); // NB #versionDiplome est un Select2
        }
        updateVersionDiplomeOptionsForSelectedEtablissement();

        $etablissementSelect2
            .on('select2:select', function (e) {
                updateVersionDiplomeOptionsForSelectedEtablissement();
                $versionDiplomeSelect2.val('').removeAttr('disabled').trigger('change');
            });

        //met à jour les checkbox pour la confidentialité
        updateFields()
    });
</script>