<?php
/**
 * @var int[] $substitutionsCount
 * @var int[] $doublonsCount
 */

use Substitution\Constants;

$this->headTitle($this->translate("Module &laquo; Substitutions &raquo;"))

?>

<h1 class="page-header"><span class="fas fa-object-group"></span> Module Substitution</h1>

<p class="lead">

</p>

<div class="row">
    <div class="col-md-10 mb-1">
        <div class="card text-center">
            <div class="card-body">
                <h5 class="card-title">Structures</h5>
                <a class="card-link" href="<?php echo $this->url('substitution/substitution/lister', ['type' => Constants::TYPE_structure]) ?>">
                    Substitutions existantes <span class="badge bg-secondary"><?php echo $substitutionsCount['structure'] ?> substituants</span>
                </a><br>
                <a class="card-link" href="<?php echo $this->url('substitution/doublon/lister', ['type' => Constants::TYPE_structure]) ?>">
                    Substitutions possibles <span class="badge bg-secondary"><?php echo $doublonsCount['structure'] ?> doublons</span>
                </a><br>
                <a class="card-link" href="<?php echo $this->url('substitution/foreign-key/lister', ['type' => Constants::TYPE_structure]) ?>">
                    Clés étrangères
                </a><br>
                <a class="card-link" href="<?php echo $this->url('substitution/log/lister', ['type' => Constants::TYPE_structure]) ?>">
                    Logs
                </a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-10 mb-1">
        <div class="card-group mb-5">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Établissements</h5>
                    <a class="card-link" href="<?php echo $this->url('substitution/substitution/lister', ['type' => Constants::TYPE_etablissement]) ?>">
                        Substitutions existantes <span class="badge bg-secondary"><?php echo $substitutionsCount['etablissement'] ?> substituants</span>
                    </a><br>
                    <a class="card-link" href="<?php echo $this->url('substitution/doublon/lister', ['type' => Constants::TYPE_etablissement]) ?>">
                        Substitutions possibles <span class="badge bg-secondary"><?php echo $doublonsCount['etablissement'] ?> doublons</span>
                    </a><br>
                    <a class="card-link" href="<?php echo $this->url('substitution/foreign-key/lister', ['type' => Constants::TYPE_etablissement]) ?>">
                        Clés étrangères
                    </a><br>
                    <a class="card-link" href="<?php echo $this->url('substitution/log/lister', ['type' => Constants::TYPE_etablissement]) ?>">
                        Logs
                    </a>
                </div>
            </div>
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Écoles doctorales</h5>
                    <a class="card-link" href="<?php echo $this->url('substitution/substitution/lister', ['type' => Constants::TYPE_ecole_doct]) ?>">
                        Substitutions existantes <span class="badge bg-secondary"><?php echo $substitutionsCount['ecole-doct'] ?> substituants</span>
                    </a><br>
                    <a class="card-link" href="<?php echo $this->url('substitution/doublon/lister', ['type' => Constants::TYPE_ecole_doct]) ?>">
                        Substitutions possibles <span class="badge bg-secondary"><?php echo $doublonsCount['ecole-doct'] ?> doublons</span>
                    </a><br>
                    <a class="card-link" href="<?php echo $this->url('substitution/foreign-key/lister', ['type' => Constants::TYPE_ecole_doct]) ?>">
                        Clés étrangères
                    </a><br>
                    <a class="card-link" href="<?php echo $this->url('substitution/log/lister', ['type' => Constants::TYPE_ecole_doct]) ?>">
                        Logs
                    </a>
                </div>
            </div>
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Unités de recherche</h5>
                    <a class="card-link" href="<?php echo $this->url('substitution/substitution/lister', ['type' => Constants::TYPE_unite_rech]) ?>">
                        Substitutions existantes <span class="badge bg-secondary"><?php echo $substitutionsCount['unite-rech'] ?> substituants</span>
                    </a><br>
                    <a class="card-link" href="<?php echo $this->url('substitution/doublon/lister', ['type' => Constants::TYPE_unite_rech]) ?>">
                        Substitutions possibles <span class="badge bg-secondary"><?php echo $doublonsCount['unite-rech'] ?> doublons</span>
                    </a><br>
                    <a class="card-link" href="<?php echo $this->url('substitution/foreign-key/lister', ['type' => Constants::TYPE_unite_rech]) ?>">
                        Clés étrangères
                    </a><br>
                    <a class="card-link" href="<?php echo $this->url('substitution/log/lister', ['type' => Constants::TYPE_unite_rech]) ?>">
                        Logs
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-10 mb-1">
        <div class="card text-center">
            <div class="card-body">
                <h5 class="card-title">Individus</h5>
                <a class="card-link" href="<?php echo $this->url('substitution/substitution/lister', ['type' => Constants::TYPE_individu]) ?>">
                    Substitutions existantes <span class="badge bg-secondary"><?php echo $substitutionsCount['individu'] ?> substituants</span>
                </a><br>
                <a class="card-link" href="<?php echo $this->url('substitution/doublon/lister', ['type' => Constants::TYPE_individu]) ?>">
                    Substitutions possibles <span class="badge bg-secondary"><?php echo $doublonsCount['individu'] ?> doublons</span>
                </a><br>
                <a class="card-link" href="<?php echo $this->url('substitution/foreign-key/lister', ['type' => Constants::TYPE_individu]) ?>">
                    Clés étrangères
                </a><br>
                <a class="card-link" href="<?php echo $this->url('substitution/log/lister', ['type' => Constants::TYPE_individu]) ?>">
                    Logs
                </a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4 mb-1">
        <div class="card-group mb-5">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Doctorants</h5>
                    <a class="card-link" href="<?php echo $this->url('substitution/substitution/lister', ['type' => Constants::TYPE_doctorant]) ?>">
                        Substitutions existantes <span class="badge bg-secondary"><?php echo $substitutionsCount['doctorant'] ?> substituants</span>
                    </a><br>
                    <a class="card-link" href="<?php echo $this->url('substitution/doublon/lister', ['type' => Constants::TYPE_doctorant]) ?>">
                        Substitutions possibles <span class="badge bg-secondary"><?php echo $doublonsCount['doctorant'] ?> doublons</span>
                    </a><br>
                    <a class="card-link" href="<?php echo $this->url('substitution/foreign-key/lister', ['type' => Constants::TYPE_doctorant]) ?>">
                        Clés étrangères
                    </a><br>
                    <a class="card-link" href="<?php echo $this->url('substitution/log/lister', ['type' => Constants::TYPE_doctorant]) ?>">
                        Logs
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
