<?php
/**
 * @var int[] $substitutionsCount
 * @var int[] $doublonsCount
 */

$this->headTitle($this->translate("Module &laquo; Substitution &raquo;"))

?>

<h1 class="page-header">Module &laquo; Substitution &raquo;</h1>

<p class="lead">

</p>

<div class="row">
    <div class="col-md-8 mb-1">
        <div class="card text-center">
            <div class="card-body">
                <h5 class="card-title">Structures</h5>
                <!--<h6 class="card-subtitle mb-2 text-body-secondary">Card subtitle</h6>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
                <a class="card-link" href="<?php echo $this->url('substitution/substitution/structure') ?>">Substitutions existantes
                    <span class="badge bg-secondary"><?php echo $substitutionsCount['structure'] ?></span></a><br>
                <a class="card-link" href="<?php echo $this->url('substitution/doublon/structure') ?>">Doublons non substitués
                    <span class="badge bg-secondary"><?php echo $doublonsCount['structure'] ?></span></a><br>
                <a class="card-link" href="<?php echo $this->url('substitution/foreign-key/structure') ?>">Clés étrangères</a><br>
                <a class="card-link" href="<?php echo $this->url('substitution/log/structure') ?>">Logs</a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-8 mb-1">
        <div class="card-group mb-5">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Établissements</h5>
                    <!--<h6 class="card-subtitle mb-2 text-body-secondary">Card subtitle</h6>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
                    <a class="card-link" href="<?php echo $this->url('substitution/substitution/etablissement') ?>">Substitutions existantes
                        <span class="badge bg-secondary"><?php echo $substitutionsCount['etablissement'] ?></span></a><br>
                    <a class="card-link" href="<?php echo $this->url('substitution/doublon/etablissement') ?>">Doublons non substitués
                        <span class="badge bg-secondary"><?php echo $doublonsCount['etablissement'] ?></span></a><br>
                    <a class="card-link" href="<?php echo $this->url('substitution/foreign-key/etablissement') ?>">Clés étrangères</a><br>
                    <a class="card-link" href="<?php echo $this->url('substitution/log/etablissement') ?>">Logs</a>
                </div>
            </div>
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Écoles doctorales</h5>
                    <!--<h6 class="card-subtitle mb-2 text-body-secondary">Card subtitle</h6>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
                    <a class="card-link" href="<?php echo $this->url('substitution/substitution/ecole-doct') ?>">Substitutions existantes
                        <span class="badge bg-secondary"><?php echo $substitutionsCount['ecole-doct'] ?></span></a><br>
                    <a class="card-link" href="<?php echo $this->url('substitution/doublon/ecole-doct') ?>">Doublons non substitués
                        <span class="badge bg-secondary"><?php echo $doublonsCount['ecole-doct'] ?></span></a><br>
                    <a class="card-link" href="<?php echo $this->url('substitution/foreign-key/ecole-doct') ?>">Clés étrangères</a><br>
                    <a class="card-link" href="<?php echo $this->url('substitution/log/ecole-doct') ?>">Logs</a>
                </div>
            </div>
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Unités de recherche</h5>
                    <!--<h6 class="card-subtitle mb-2 text-body-secondary">Card subtitle</h6>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
                    <a class="card-link" href="<?php echo $this->url('substitution/substitution/unite-rech') ?>">Substitutions existantes
                        <span class="badge bg-secondary"><?php echo $substitutionsCount['unite-rech'] ?></span></a><br>
                    <a class="card-link" href="<?php echo $this->url('substitution/doublon/unite-rech') ?>">Doublons non substitués
                        <span class="badge bg-secondary"><?php echo $doublonsCount['unite-rech'] ?></span></a><br>
                    <a class="card-link" href="<?php echo $this->url('substitution/foreign-key/unite-rech') ?>">Clés étrangères</a><br>
                    <a class="card-link" href="<?php echo $this->url('substitution/log/unite-rech') ?>">Logs</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4 mb-1">
        <div class="card text-center">
            <div class="card-body">
                <h5 class="card-title">Individus</h5>
                <!--<h6 class="card-subtitle mb-2 text-body-secondary">Card subtitle</h6>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
                <a class="card-link" href="<?php echo $this->url('substitution/substitution/individu') ?>">Substitutions existantes
                    <span class="badge bg-secondary"><?php echo $substitutionsCount['individu'] ?></span></a><br>
                <a class="card-link" href="<?php echo $this->url('substitution/doublon/individu') ?>">Doublons non substitués
                    <span class="badge bg-secondary"><?php echo $doublonsCount['individu'] ?></span></a><br>
                <a class="card-link" href="<?php echo $this->url('substitution/foreign-key/individu') ?>">Clés étrangères</a><br>
                <a class="card-link" href="<?php echo $this->url('substitution/log/individu') ?>">Logs</a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4 mb-1">
        <div class="card-group mb-5">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Doctorants</h5>
                    <!--<h6 class="card-subtitle mb-2 text-body-secondary">Card subtitle</h6>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
                    <a class="card-link" href="<?php echo $this->url('substitution/substitution/doctorant') ?>">Substitutions existantes
                        <span class="badge bg-secondary"><?php echo $substitutionsCount['doctorant'] ?></span></a><br>
                    <a class="card-link" href="<?php echo $this->url('substitution/doublon/doctorant') ?>">Doublons non substitués
                        <span class="badge bg-secondary"><?php echo $doublonsCount['doctorant'] ?></span></a><br>
                    <a class="card-link" href="<?php echo $this->url('substitution/foreign-key/doctorant') ?>">Clés étrangères</a><br>
                    <a class="card-link" href="<?php echo $this->url('substitution/log/doctorant') ?>">Logs</a>
                </div>
            </div>
        </div>
    </div>
</div>
