<?php

use Structure\Entity\Db\UniteRecherche;
use Structure\Provider\Privilege\StructurePrivileges;

/**
 * @var UniteRecherche[] $unites
 *
 * @see \Structure\Controller\UniteRechercheController::indexAction()
 */

$canModifier = $this->isAllowed(StructurePrivileges::getResourceId(StructurePrivileges::STRUCTURE_MODIFICATION_TOUTES_STRUCTURES));
$canAjouter = $this->isAllowed(StructurePrivileges::getResourceId(StructurePrivileges::STRUCTURE_MODIFICATION_TOUTES_STRUCTURES));
//$canSubstituer = $this->isAllowed(SubstitutionPrivileges::getResourceId(SubstitutionPrivileges::SUBSTITUTION_CONSULTATION_TOUTES_STRUCTURES))
//    || $this->isAllowed(SubstitutionPrivileges::getResourceId(SubstitutionPrivileges::SUBSTITUTION_CONSULTATION_SA_STRUCTURE));
?>


<?php $this->headTitle($this->translate("Unités de recherche")) ?>

<h1 class="page-header first">
    <?php echo $this->translate("Unités de recherche") ?>
    <span class="badge bg-secondary"><?php echo count($unites); ?></span>
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace() ?>

<p>
    <?php if ($canAjouter): ?>
        <a href="<?php echo $this->url('unite-recherche/ajouter', [], [], true) ?>"
           class="btn btn-primary"
           title="<?php echo $this->translate("Créer une nouvelle unité de recherche"); ?>">
            <span class="icon icon-plus"></span>
            <?php echo $this->translate("Ajouter une nouvelle unité de recherche"); ?>
        </a>
    <?php endif ?>
</p>

<div>
    <table class="table table-sm">
        <thead>
        <tr>
            <th> Libellé</th>
            <th> Source</th>
            <th> Code</th>
            <th> Sigle</th>
            <th> Identifiant RNSR</th>
<!--            <th> #these</th>-->
            <th> Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($unites as $unite): ?>

            <?php
            $historisee = (!$unite->estNonHistorise());
            $canModifierCetteUnite = $this->isAllowed($unite->getStructure(),StructurePrivileges::STRUCTURE_MODIFICATION_SES_STRUCTURES);
            ?>

            <tr>
                <td>
                    <a href="<?php echo $this->url('unite-recherche/voir', ['unite-recherche' => $unite->getId()], [], true); ?>">
                        <?php echo $unite->getStructure()->getLibelle(); ?>
                    </a>
                    <?php if ($unite->estSubstituant()) : ?>
                        &nbsp;<span class="badge bg-info" title="Cet enregistrement substitue d'autres enregistrements">Substituant</span>
                    <?php endif; ?>
                    <?php if ($unite->getStructure()->estFermee()) : ?>
                        &nbsp;<span class="badge bg-danger">Structure fermée</span>
                    <?php endif; ?>
                </td>
                <td>
                    <?php echo $unite->getSource(); ?>
                </td>
                <td>
                    <?php echo $unite->getStructure()->getCode(); ?>
                </td>
                <td> <?php echo $unite->getStructure()->getSigle(); ?> </td>
                <td> <?php echo $unite->getRNSR(); ?> </td>
<!--                <td> --><?php //echo count($unite->getTheses()); ?><!-- </td>-->
                <td>
                    <?php if (($canModifier OR $canModifierCetteUnite) && !$historisee) : ?>
                        <a href="<?php echo $this->url('unite-recherche/supprimer', ['unite-recherche' => $unite->getId()], [], true); ?>"
                           title="Historiser l'établissement">
                            <span class="icon icon-delete iconly"></span>
                        </a>
                    <?php endif; ?>

                    <?php if (($canModifier OR $canModifierCetteUnite) && $historisee) : ?>
                        <a href="<?php echo $this->url('unite-recherche/restaurer', ['unite-recherche' => $unite->getId()], [], true); ?>"
                           title="Restaurer l'établissement">
                            Restaurer
                        </a>
                    <?php endif; ?>
                </td>
            </tr>

        <?php endforeach; ?>

        </tbody>
    </table>
</div>