<?php

use Application\Entity\Db\DomaineScientifique;
use Structure\Entity\Db\Etablissement;
use Structure\Entity\Db\EtablissementRattachement;
use Structure\Entity\Db\Structure;
use Structure\Entity\Db\UniteRecherche;
use Structure\Form\UniteRechercheForm;
use Application\View\Helper\SelectHelper;
use Application\View\Helper\FiltersPanel\FiltersPanelHelper;
use Application\View\Renderer\PhpRenderer;
use UnicaenIdref\Domain\Index1;

/**
 * @var PhpRenderer                 $this
 * @var string                      $title
 * @var UniteRechercheForm          $form
 * @var EtablissementRattachement[] $etablissementsRattachements
 * @var Etablissement[]             $etablissements
 * @var DomaineScientifique[]       $domainesAssocies
 * @var DomaineScientifique[]       $domainesScientifiques
 * @var string|null                 $logoContent
 * @var mixed                       $structure
 *
 * @method string formControlGroup()
 *
 * @see \Structure\Controller\UniteRechercheController::modifierAction()
 */

$logoContent = $logoContent ?? null;
$structure = $structure ?? null;

/** @var UniteRecherche $unite */
$unite = $form->getObject();
$idUniteRecherche = $unite->getStructure()->getId();
$isNew = $unite->getId() === null;
$estImportee = $unite->getSource()?->getImportable() ?? false;
$fcg = $this->formControlGroup();

$editable = $isNew || !$estImportee;
$form->get('libelle')->setAttribute('readonly', !$editable);
$form->get('sigle')->setAttribute('readonly', !$editable);
$form->get('code')->setAttribute('readonly', !$editable);

$this->headTitle("Modification de l'UR " . $unite->getStructure()->getCode());
?>

<h1 class="page-header">
    <?php if ($isNew): ?>
        Création d'une nouvelle unité de recherche
    <?php else: ?>
        Modification de l'unité de recherche &laquo; <?php echo $unite ?> &raquo;
    <?php endif ?>
</h1>

<?php echo $this->messenger()->addCurrentMessagesFromFlashMessengerWithNoNamespace(); ?>

<?php if ($estImportee) : ?>
    <p class="alert alert-warning">
        <span class="icon icon-attention"></span>
        <strong>La source (<?php echo $unite->getSource()->getLibelle(); ?>) ne permet pas la modification de certains attributs.</strong>
        <br/>
        Par conséquent, vous ne pouvez pas modifier les champs : libellé, sigle et code.
    </p>
<?php endif; ?>

<!-- BLOC DES INFORMATIONS GENERALES ---------------------------------------------------------------------------------->

<?php echo $this->form()->openTag($form->prepare()->setAttribute('class', 'unite-recherche')) ?>

<div class="row">

    <div class="col-md-6">
        <fieldset>
            <legend><h2>Informations générales</h2></legend>
            <?php echo $fcg($form->get('libelle')->setAttribute('id', 'libelle')) ?>
            <?php echo $fcg($form->get('sigle')) ?>
        </fieldset>
        <fieldset>
            <legend><h2>Informations techniques</h2></legend>
            <div class="row">
                <div class="col-md-5">
                    <?php echo $fcg($form->get('id_ref')->setAttribute('id', 'idRef')) ?>
                </div>
                <div class="col-md-2">
                    <?php echo $this->idrefPopupTrigger([
                        ['Index1' => Index1::INDEX_Ppn, 'Index1Value' => ['idRef']],
                        ['Index1' => Index1::INDEX_NomDeCollectivité, 'Index1Value' => ['libelle']],
                    ], 'idRef') ?>
                </div>
            </div>
            <?php echo $fcg($form->get('id_hal')) ?>
            <?php echo $fcg($form->get('RNSR')) ?>
            <?php echo $fcg($form->get('code')) ?>
        </fieldset>
    </div>

    <div class="col-md-6">
        <fieldset>
            <legend><h2>Étiquettes associées</h2></legend>
            <?php if ($form->has('estFerme')) : ?>
                <?php echo $fcg($form->get('estFerme')) ?>
            <?php else: ?>
                Aucune.
            <?php endif ?>
        </fieldset>

        <fieldset id="logo-div">
            <legend><h2>Logo</h2></legend>
            <?php
            /** @var \Laminas\Form\Element\File $logoFile */
            $logoFile = $form->get('cheminLogo');

            $content = $logoContent;
            if ($content === null) {
                $unite->getStructure()->setCheminLogo(null);
            }
            ?>
            <div>
                <?php if ($logoContent): ?>
                <img
                        id="logo"
                        alt="Logo de la structure"
                        style="max-width: 200px; max-height: 200px; border: 1px solid black; background-color: white;"
                        src="data:image/*;base64,<?php echo base64_encode($logoContent); ?>"
                />
                <?php else: ?>
                    Aucun logo défini.
                <?php endif; ?>
            </div>
            <div style="padding:20px;">
                <?php echo $this->formControlGroup($logoFile) ?>
                <div class="alert alert-warning text-md">
                    <span class="icon icon-warning"></span>
                    Le logo de la structure doit être fourni dans l'un des formats suivants :
                    <?php echo implode(', ', Structure::LOGO_ALLOWED_FILE_EXTENSIONS) ?>.
                </div>
                <?php if ($unite->getId()): ?>
                    <a data-toggle="confirmationx" id="supprimer-logo" class="btn btn-danger"
                       href="<?php echo $this->url('unite-recherche/supprimer-logo', ["unite-recherche" => $unite->getId()]); ?>"
                       data-bs-toggle="tooltip"
                       data-bs-html="true"
                       title="Une confirmation avant la suppression vous sera demandée"
                    >
                        <span class="icon icon-delete"></span>
                        Supprimer le logo
                    </a>
                <?php endif; ?>
            </div>
        </fieldset>
    </div>

</div>

<?php echo $this->formHidden($form->get('id')) ?>
<?php echo $this->formHidden($form->get('csrf')) ?>
<?php echo $this->formElement($form->get('submit')) ?>
<?php echo $this->form()->closeTag() ?>


<hr>

<!-- BLOC DES ETABLISSEMENT DE RATTACHEMENT --------------------------------------------------------------------------->

<h2> Établissements de rattachement </h2>

<?php if(!$structure): ?>
    <p> Les établissements de rattachement ne peuvent être ajoutés qu'après l'enregistrement de l'unité de recherche.</p>
<?php else : ?>
    <div class="row">

    <div class="col-md-6">
        <table class="table table-extra-condensed">
            <thead>
            <tr>
                <th> Libellé</th>
                <th style="width:15%;"> Action</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($etablissementsRattachements as $etablissementRattachement): ?>
                <tr>
                    <td> <?php echo $etablissementRattachement->getEtablissement()->getStructure()->getLibelle(); ?> </td>
                    <td>
                        <a
                                href="<?php echo $this->url("unite-recherche/modifier/retirer-etablissement-rattachement", ["unite-recherche" => $idUniteRecherche, "etablissement" => $etablissementRattachement->getEtablissement()->getId()], [], true); ?>"
                                data-toggle="confirmationx"
                                data-bs-toggle="tooltip"
                                data-bs-html="true"
                                title="Retirer l'établissement de rattachement <br>(Une confirmation avant la suppression vous sera demandée)"
                        >
                            <span class="icon icon-delete iconly text-danger"></span>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <div class="col-md-6">
        <?php
        $selectDomaine = new SelectHelper("etablissements", $etablissements, "Choisissez un établissement de rattachement ...");
        ?>

        <select title=""
                class="filter selectpicker show-menu-arrow"
                name="etablissements"
                id="etablissements"
                data-live-search="true"
                data-width="450px">
            <?php foreach ($selectDomaine->asDataArray() as $data): ?>
                <?php
                $value = $data['value'];
                $label = $data['label'];
                $subtext = $data['subtext'] ?? '';
                ?>
                <option value="<?php echo $value ?>" data-subtext="<?php echo $subtext ?>">
                    <?php echo $label ?>
                </option>
            <?php endforeach ?>
        </select>

        <br/>
        <br/>

        <a
                class="btn btn-success"
                id="ajout-rattachement"
                href="<?php echo $this->url("unite-recherche/modifier/ajouter-etablissement-rattachement", ["unite-recherche" => $idUniteRecherche, "etablissement" => 0], [], true); ?>"
        >
            <span class="icon icon-plus"></span>
            Ajouter un établissement de rattachement
        </a>
    </div>
</div>
<?php endif; ?>

<hr>

<!-- BLOC DES DOMAINES SCIENTIFIQUES ---------------------------------------------------------------------------------->


<h2> Domaines scientifiques</h2>

<?php if(!$structure): ?>
    <p> Les domaines scientifiques ne peuvent être ajoutés qu'après l'enregistrement de l'unité de recherche.</p>
<?php else : ?>
<div class="row">
    <div class="col-md-6">
        <table class="table table-extra-condensed">
            <thead>
            <tr>
                <th>Libellé</th>
                <th style="width:15%;">Action</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($domainesAssocies as $domaineScientifique) : ?>
                <tr>
                    <td>
                        <?php echo $domaineScientifique->getLibelle(); ?>
                    </td>
                    <td>
                        <a
                                href="<?php echo $this->url('unite-recherche/modifier/retirer-domaine-scientifique', ["unite-recherche" => $idUniteRecherche, 'domaineScientifique' => $domaineScientifique->getId()], [], true); ?>"
                                data-toggle="confirmationx"
                                data-bs-toggle="tooltip"
                                data-bs-html="true"
                                title="Retirer le domaine scientifique <br>(Une confirmation avant la suppression vous sera demandée)"
                        >
                            <span class="icon icon-delete iconly text-danger"></span>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>


    <div class="col-md-6">
        <?php
        $selectDomaine = new SelectHelper("domaines", $domainesScientifiques, 'Choisissez un domaine scientifique ...');
        ?>

        <input type="hidden" id="unite" value="<?php echo $unite->getStructure()->getId(); ?>">
        <select title=""
                class="filter selectpicker show-menu-arrow"
                name="domaines"
                id="domaines"
                data-live-search="true"
                data-width="450px">
            <?php foreach ($selectDomaine->asDataArray() as $data): ?>
                <?php
                $value = $data['value'];
                $label = $data['label'];
                $subtext = $data['subtext'] ?? '';
                ?>
                <option value="<?php echo $value ?>" data-subtext="<?php echo $subtext ?>">
                    <?php echo $label ?>
                </option>
            <?php endforeach ?>
        </select>


        <br/>
        <br/>
        <a class="btn btn-success"
           id="ajout-domaine"
           href="<?php echo $this->url("unite-recherche/modifier/ajouter-domaine-scientifique", ["unite-recherche" => $idUniteRecherche, "domaineScientifique" => 0], [], true); ?>">
            <span class="icon icon-plus"></span>
            Ajouter un domaine scientifique
        </a>
    </div>
    <?php endif; ?>
</div>



<script>
    $(document).ready(function () {

        //remplacement dans la structure cible
        $("input[name='cheminLogo']").on("change", function () {

            var myFile = $("input[name='cheminLogo']").prop('files');
            console.log(myFile[0]);
            fr = new FileReader();
            fr.onload = function () {
                var content = fr.result;
                console.log(content);
                $('#logo').attr("src", content);
            };
            fr.readAsDataURL(myFile[0]);
        });

        $("#etablissements").on("change", function () {
            var etablissementId = $("#etablissements").val();
            var uniteId = $("#unite").val();
            $("a#ajout-rattachement").attr("href", uniteId + "/ajouter-etablissement-rattachement/" + etablissementId);
        });

        $("#domaines").on("change", function () {
            var domaineId = $("#domaines").val();
            var uniteId = $("#unite").val();
            $("a#ajout-domaine").attr("href",  uniteId + "/ajouter-domaine-scientifique/" + domaineId);
        });
    });
</script>

<script>
    $(function() {
        $("#domaines").refresh();
    });
    $(function() {
        $("#etablissements").refresh();
    });
</script>