<?php

use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var array       $etatsThese
 * @var array       $etablissements
 * @var array       $ecolesDoctorales
 * @var array       $unitesRecherches
 * @var array       $anneesPremiereInscription
 */

/**
 * @param string $paramName
 * @param string $paramValue
 * @param array $queryParams
 * @return string
 */
$urlFiltrer = function ($paramName, $paramValue, $queryParams) {
    $queryParams[$paramName] = $paramValue;
    return $this->url('these/rechercher', [], ['query' => $queryParams], true);
};

echo $this->selectsFilterPanel([
    $this->translate("État") => [
        'paramName' => 'etatThese',
        'paramConfig' => $etatsThese,
        'filterUrl' => $urlFiltrer,
    ],
    $this->translate("Établissement") => [
        'paramName' => 'etablissement',
        'paramConfig' => $etablissements,
        'filterUrl' => $urlFiltrer,
    ],
    $this->translate("ED") => [
        'paramName' => 'ecoleDoctorale',
        'paramConfig' => $ecolesDoctorales,
        'filterUrl' => $urlFiltrer,
    ],
    $this->translate("UR") => [
        'paramName' => 'uniteRecherche',
        'paramConfig' => $unitesRecherches,
        'filterUrl' => $urlFiltrer,
    ],
    $this->translate("1ère inscr.") => [
        'paramName' => 'anneePremiereInscription',
        'paramConfig' => $anneesPremiereInscription,
        'filterUrl' => $urlFiltrer,
    ],
]);


