<?php

namespace Application;

use Application\Entity\Db\Rapport;
use Application\Entity\Db\These;
use Application\Filter\IdifyFilter;
use Application\Form\RapportActiviteForm;
use Application\Provider\Privilege\RapportPrivileges;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var These $these
 * @var Rapport[] $rapports
 * @var RapportActiviteForm $form
 * @var bool $tousLesRapportsTeleverses
 *
 * @see \Application\Controller\RapportActiviteController::indexAction()
 */

$form->prepare();
$rapportProto = (new Rapport())->setThese($these);
$canAdd = $this->isAllowed($rapportProto, RapportPrivileges::RAPPORT_ACTIVITE_TELEVERSER_TOUT) || $this->isAllowed($rapportProto, RapportPrivileges::RAPPORT_ACTIVITE_TELEVERSER_SIEN);
if ($tousLesRapportsTeleverses) {
    $canAdd = false;
}
?>

<?php $this->headTitle($this->translate($title = "Rapports d'activité"))
    ->prepend($these->getDoctorant()->getIndividu()->getNomUsuel()) ?>

<h1 class="page-header">
    <?php echo $this->translate($title); ?>
    <small><?php echo $this->partial('application/these/partial/titre') ?></small>
</h1>

<h2>Selon l'état d'avancement de votre thèse</h2>

<ul>
    <li>
        <strong>Si votre soutenance n'est pas prévue avant le 31 décembre</strong> de l'année en cours,
        <strong>vous devez rédiger un rapport d'activité annuel</strong> qui doit <strong>être déposé ci-dessous avant le 31 juillet</strong>.
        Son dépôt conditionne l'autorisation de réinscription en thèse.
        <a href="<?php echo $this->url('fichier/telecharger-permanent', ['idPermanent' => 'RAPPORT_ACTIVITE_MODELE']) ?>">Cliquez ici pour télécharger le modèle de rapport annuel.</a>
    </li>
    <li>
        <strong>Si votre soutenance est programmée avant le 31 décembre</strong> de l'année en cours,
        <strong>vous devez rédiger un rapport d'activité de fin de thèse</strong> qui doit <strong>être déposé ci-dessous avant le 31 juillet</strong>.
        Dans ce cas, les données indiquées doivent couvrir l'ensemble de la thèse.
        <a href="<?php echo $this->url('fichier/telecharger-permanent', ['idPermanent' => 'RAPPORT_ACTIVITE_MODELE']) ?>">Cliquez ici pour télécharger le modèle de rapport de fin de thèse.</a>
    </li>
</ul>
<p>
    Les rapports d'activité doivent être concis (suivez les indications de taille maximum pour chaque item).
</p>
<ul>
    <li>Complétez le document téléchargé, faites le signer par vos directions de thèse et de laboratoire</li>
    <li>Scannez le document signé et téléversez le en version PDF</li>
</ul>

<div class="row">
    <div class="col-md-11">

        <h2>Rapports téléversés</h2>

        <?php if (count($rapports) > 0): ?>

            <table class="table table-bordered">
            <thead>
            <tr>
                <th>Type</th>
                <th>Année universitaire</th>
                <th>Document téléversé</th>
                <th>Téléversé le</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($rapports as $rapport): ?>
            <tr>
                <?php
                $canDel = $this->isAllowed($rapport, RapportPrivileges::RAPPORT_ACTIVITE_SUPPRIMER_TOUT) || $this->isAllowed($rapport, RapportPrivileges::RAPPORT_ACTIVITE_SUPPRIMER_SIEN);
                $canDl = $this->isAllowed($rapport, RapportPrivileges::RAPPORT_ACTIVITE_TELECHARGER_TOUT) || $this->isAllowed($rapport, RapportPrivileges::RAPPORT_ACTIVITE_TELECHARGER_SIEN);
                ?>
                <td>
                    <span class="label label-info"><?php echo $rapport->getTypeRapport()->getLibelleCourt() ?></span>
                </td>
                <td>
                    <?php echo $rapport->getAnneeUnivToString() ?>
                </td>
                <td>
                    <?php if ($canDl): ?>
                        <a href="<?php echo $this->url('rapport-activite/telecharger', ['rapport' => IdifyFilter::id($rapport)]) ?>"
                           title="Cliquez pour télécharger">
                            <?php echo $rapport->getFichier()->getNom() ?>
                        </a>
                    <?php else: ?>
                        <span title="<?php echo $title ?>">
                            <?php echo $rapport->getFichier()->getNom() ?>
                        </span>
                    <?php endif; ?>
                </td>
                <td>
                    <?php echo "Le " . $rapport->getHistoCreation()->format('d/m/Y à H:i:s') . " par " . $rapport->getHistoCreateur() ?>
                </td>
                <td class="action">
                    <?php if ($canDel): ?>
                        <a href="<?php echo $this->url('rapport-activite/supprimer', ['rapport' => $rapport->getId()]) ?>"
                           title="Supprimer ce rapport ?"
                           data-toggle="confirmation"><span class="glyphicon glyphicon-trash"></span></a>
                    <?php endif; ?>
                </td>
            </tr>
            <?php endforeach; ?>
            </tbody>
        </table>

        <?php else: ?>

            Aucun.

        <?php endif; ?>

    </div>
</div>

<div class="row">
    <div class="col-md-offset-1 col-md-8">

        <?php $ajouterFormVisible = !empty($form->getMessages()); ?>
        <div id="ajouterDiv">
            <div class="row">
                <div class="col-md-4">
                    <a href="#" id="ajouterBtn" class="btn btn-primary <?php echo $canAdd ? '' : 'disabled' ?>"
                       style="display: <?php echo !$ajouterFormVisible ? 'inherit' : 'none' ?>">
                        <span class="glyphicon glyphicon-plus"></span> Téléverser un rapport</a>
                </div>
            </div>

            <div id="ajouterForm" style="display: <?php echo $ajouterFormVisible ? 'inherit' : 'none' ?>">
                <h3>Formulaire de téléversement</h3>

                <?php echo $this->form()->openTag($form) ?>
                <div class="row">
                    <div class="col-md-6">
                        <?php echo $this->formControlGroup($form->get('estFinal')); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <?php echo $this->formControlGroup($form->get('anneeUniv')) ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-7">
                        <?php
                        echo $this->formControlGroup($form->get('files'));
                        echo $this->formControlGroup($form->get('security'));
                        echo $this->formSubmit($form->get('submit')->setAttributes(['class' => 'btn btn-primary']));
                        ?>
                    </div>
                </div>
                <?php echo $this->form()->closeTag() ?>
                <div class="row">
                    <div class="col-md-3">
                        <a href="#" id="annulerBtn" class="btn btn-danger">Annuler</a>
                    </div>
                </div>
            </div>
        </div>

        <?php if ($tousLesRapportsTeleverses): ?>
            <div class="row">
                <div class="col-md-6 text-success">
                    <span class="glyphicon glyphicon-info-sign"></span>
                    Toutes les années universitaires d'inscription du doctorant ont fait l'objet d'un téléversement de rapport.
                </div>
            </div>
        <?php endif ?>

    </div>
</div>


<script>
    $(function() {
        var $ajouterBtn = $("#ajouterBtn");
        var $annulerBtn = $("#annulerBtn");
        var $ajouterForm = $("#ajouterForm");

        $ajouterBtn.on('click', function() {
            $ajouterForm.show();
            $ajouterBtn.hide();
            return false;
        });
        $annulerBtn.on('click', function() {
            $ajouterForm.hide();
            $ajouterBtn.show();
            return false;
        });
        $('[data-toggle=confirmation]').confirmation({
            rootSelector: '[data-toggle=confirmation]',
            container: 'body',
            title: "Êtes-vous sûr(e) ?",
            btnOkLabel: "Oui",
            btnCancelLabel: "Non",
        });
    });
</script>
