<?php

/**
 * @var Information[] $informations
 */

use Application\Provider\Privilege\FichierPrivileges;
use Information\Entity\Db\Information;
use Information\Provider\Privilege\InformationPrivileges;

$this->headTitle("Index des informations");

$canView    = true;
$canEdit    = $this->isAllowed(InformationPrivileges::getResourceId(InformationPrivileges::INFORMATION_MODIFIER));
$canDelete  = $this->isAllowed(InformationPrivileges::getResourceId(InformationPrivileges::INFORMATION_MODIFIER));
$canFichier = $this->isAllowed(FichierPrivileges::getResourceId(FichierPrivileges::FICHIER_DIVERS_TELEVERSER));
?>

<style>
    a.action {
        width: 30rem;
    }
</style>

<h1 class="page-header">
    Pages d'information
</h1>

<a href="<?php echo $this->url('informations/ajouter', [], [], true); ?>"
   class="btn btn-primary action"
>
    <span class="glyphicon glyphicon-plus"></span>
    Ajouter une page d'information
</a>

<?php if ($canFichier) : ?>
    <a href="<?php echo $this->url('informations/fichiers', [], [], true); ?>"
       class="btn btn-primary action"
    >
        <span class="glyphicon glyphicon-folder-open "></span>
        Gestion des fichiers
    </a>
<?php endif; ?>

<table class="table table-extra-condensed">
    <thead>
        <tr>
            <th> Id </th>
            <th> Titre </th>
            <th> Priorité </th>
            <th> Visible </th>
            <th> Dernière modification </th>
            <th> Dernier  modificateur </th>
            <th> Action </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($informations as $information) : ?>
            <tr>
                <td> <?php echo $information->getId(); ?> </td>
                <td> <?php echo $information->getTitre(); ?> </td>
                <td> <?php echo $information->getPriorite(); ?> </td>
                <td> <?php echo $information->isVisible(); ?> </td>
                <td> <?php echo $information->getHistoModification()->format("H:i  d/m/Y"); ?> </td>
                <td> <?php echo $information->getHistoModificateur()->getDisplayName(); ?> </td>
                <td>
                    <?php if ($canView) : ?>
                        <a href="<?php echo $this->url('informations/afficher', ['id' => $information->getId()], [], true); ?>">
                            <span class="glyphicon glyphicon-eye-open"></span>
                        </a>
                    <?php endif; ?>
                    <?php if ($canEdit) : ?>
                        <a href="<?php echo $this->url('informations/modifier', ['id' => $information->getId()], [], true); ?>">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                    <?php endif; ?>
                    <?php if ($canDelete) : ?>
                        <a href="<?php echo $this->url('informations/supprimer', ['id' => $information->getId()], [], true); ?>">
                            <span class="glyphicon glyphicon-trash"></span>
                        </a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>