<?php

/**
 * @var InformationForm $form
 */

use Information\Form\InformationForm;


$this->headTitle("Modification d'une page d'information");
?>

    <h1 class="page-header">
        Modification d'une page d'information
    </h1>


<?php
echo $this->form($form);
?>

<script>
    $(function () {

        $(document).ready(function() {
            tinymce.init({
                selector: '.contenu-page',
                toolbar: 'undo redo | styleselect | bold italic | bullist numlist | table link email',
                plugins: 'lists link table email',
                style_formats: [
                    {title: 'Titre 1', block: 'h2'},
                    {title: 'Titre 2', block: 'h3'},
                    {title: 'Titre 3', block: 'h4'}
                ],
                table_toolbar: "tabledelete | tableinsertrowbefore tableinsertrowafter tabledeleterow | tableinsertcolbefore tableinsertcolafter tabledeletecol",
                //
                statusbar: true,
                resize: true,
                browser_spellcheck: true,
                branding: false,
                language: 'fr_FR',
                menu: {},

                body_id: 'contenu',
                link_context_toolbar: true,
                setup: function (editor) {
                    editor.on("focusout", function () {
                $('textarea#specificite').val(tinymce.get('contenu').getContent());
                });
                }
            });
        });
    });
</script>