-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sygaldb.unicaen.fr;sid=SYGLPROD;port=1523

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW src_financement (id, source_code, source_id, these_id, annee, origine_financement_id, complement_financement, quotite_financement, date_debut, date_fin, code_type_financement, libelle_type_financement) AS SELECT 
    NULL                  AS id,
    tmp.SOURCE_CODE       AS SOURCE_CODE,
    src.ID                AS source_id,
    --e.id                  AS etablissement_id,
    t.id                  AS THESE_ID,
    (tmp.ANNEE)::numeric   AS ANNEE,
    ofi.id                AS ORIGINE_FINANCEMENT_ID,
    tmp.COMPLEMENT_FINANCEMENT,
    tmp.QUOTITE_FINANCEMENT,
    tmp.DATE_DEBUT_FINANCEMENT as DATE_DEBUT,
    tmp.DATE_FIN_FINANCEMENT as DATE_FIN,
    tmp.CODE_TYPE_FINANCEMENT,
    tmp.LIBELLE_TYPE_FINANCEMENT
 FROM TMP_FINANCEMENT tmp
         JOIN SOURCE src ON src.CODE = tmp.SOURCE_ID
         JOIN THESE t on t.SOURCE_CODE = tmp.THESE_ID
         JOIN ORIGINE_FINANCEMENT ofi on ofi.SOURCE_CODE = tmp.ORIGINE_FINANCEMENT_ID;

