-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sygaldb.unicaen.fr;sid=SYGLPROD;port=1523

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW src_acteur (id, source_code, source_id, individu_id, these_id, role_id, acteur_etablissement_id, qualite, lib_role_compl) AS SELECT 
  NULL                                     AS id,
  tmp.SOURCE_CODE,
  src.ID                                   AS SOURCE_ID,
  i.id                                     AS INDIVIDU_ID,
  t.id                                     AS THESE_ID,
  r.id                                     AS ROLE_ID,
  coalesce(etab_substit.id, eact.id)       AS ACTEUR_ETABLISSEMENT_ID,
  tmp.LIB_CPS                              AS QUALITE,
  tmp.LIB_ROJ_COMPL                        AS LIB_ROLE_COMPL
 FROM TMP_ACTEUR tmp
       JOIN SOURCE src ON src.CODE = tmp.SOURCE_ID
       JOIN INDIVIDU i ON i.SOURCE_CODE = tmp.INDIVIDU_ID
       JOIN THESE t ON t.SOURCE_CODE = tmp.THESE_ID
       JOIN ROLE r ON r.SOURCE_CODE = tmp.ROLE_ID
       LEFT JOIN ETABLISSEMENT eact ON eact.SOURCE_CODE = tmp.ACTEUR_ETABLISSEMENT_ID
       LEFT JOIN STRUCTURE_SUBSTIT ss_ed on ss_ed.FROM_STRUCTURE_ID = eact.STRUCTURE_ID
       LEFT JOIN ETABLISSEMENT etab_substit on etab_substit.STRUCTURE_ID = ss_ed.TO_STRUCTURE_ID;

