-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sygaldb.unicaen.fr;sid=SYGLPROD;port=1523

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW src_role (id, source_code, source_id, libelle, code, role_id, these_dep, structure_id, type_structure_dependant_id) AS SELECT 
    NULL                       AS id,
    tmp.SOURCE_CODE            AS SOURCE_CODE,
    src.ID                     AS source_id,
    tmp.LIB_ROJ                AS libelle,
    tmp.id::varchar            AS code,
    tmp.LIB_ROJ||' '||s.CODE   AS role_id,
    1                          AS these_dep,
    s.ID                       AS STRUCTURE_ID,
    NULL::bigint AS TYPE_STRUCTURE_DEPENDANT_ID
 FROM TMP_ROLE tmp
         JOIN STRUCTURE s ON s.SOURCE_CODE = tmp.ETABLISSEMENT_ID
         JOIN ETABLISSEMENT e ON e.STRUCTURE_ID = s.ID
         JOIN SOURCE src ON src.CODE = tmp.SOURCE_ID;

