-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sygaldb.unicaen.fr;sid=SYGLPROD;port=1523

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW src_unite_rech (id, source_code, source_id, structure_id) AS SELECT 
  NULL              AS id,
  tmp.SOURCE_CODE   as SOURCE_CODE,
  src.id            AS SOURCE_ID,
  s.ID              as STRUCTURE_ID
 FROM TMP_UNITE_RECH tmp
       JOIN STRUCTURE s on s.SOURCE_CODE = tmp.STRUCTURE_ID
       JOIN SOURCE src ON src.CODE = tmp.SOURCE_ID;

