-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sygaldb.unicaen.fr;sid=SYGLPROD;port=1523

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW src_doctorant (id, source_code, ine, source_id, individu_id, etablissement_id) AS SELECT 
    NULL                                     AS id,
    tmp.SOURCE_CODE,
    tmp.INE,
    src.id                                   AS source_id,
    i.id                                     AS individu_id,
    e.id                                     AS etablissement_id
 FROM TMP_DOCTORANT tmp
         JOIN STRUCTURE s ON s.SOURCE_CODE = tmp.ETABLISSEMENT_ID
         JOIN ETABLISSEMENT e ON e.STRUCTURE_ID = s.ID
         JOIN SOURCE src ON src.CODE = tmp.SOURCE_ID
         JOIN INDIVIDU i ON i.SOURCE_CODE = tmp.INDIVIDU_ID;

