-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sygaldb.unicaen.fr;sid=SYGLPROD;port=1523

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW src_variable (id, source_code, source_id, etablissement_id, code, description, valeur, date_deb_validite, date_fin_validite) AS SELECT 
  NULL                   AS id,
  tmp.SOURCE_CODE,
  src.ID                 AS SOURCE_ID,
  e.id                   AS ETABLISSEMENT_ID,
  tmp.COD_VAP            AS CODE,
  tmp.lib_vap            AS DESCRIPTION,
  tmp.par_vap            AS VALEUR,
  tmp.DATE_DEB_VALIDITE,
  tmp.DATE_FIN_VALIDITE
 FROM TMP_VARIABLE tmp
       JOIN STRUCTURE s ON s.SOURCE_CODE = tmp.ETABLISSEMENT_ID
       JOIN ETABLISSEMENT e ON e.STRUCTURE_ID = s.ID
       JOIN SOURCE src ON src.CODE = tmp.SOURCE_ID;

