-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sygaldb.unicaen.fr;sid=SYGLPROD;port=1523

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW src_titre_acces (id, source_code, source_id, these_id, titre_acces_interne_externe, libelle_titre_acces, type_etb_titre_acces, libelle_etb_titre_acces, code_dept_titre_acces, code_pays_titre_acces) AS SELECT 
  NULL                 AS id,
  tmp.SOURCE_CODE   AS SOURCE_CODE,
  src.ID            AS source_id,
  --e.id              AS etablissement_id,
  t.id              AS these_id,
  tmp.TITRE_ACCES_INTERNE_EXTERNE,
  tmp.LIBELLE_TITRE_ACCES,
  tmp.TYPE_ETB_TITRE_ACCES,
  tmp.LIBELLE_ETB_TITRE_ACCES,
  tmp.CODE_DEPT_TITRE_ACCES,
  tmp.CODE_PAYS_TITRE_ACCES
 FROM TMP_TITRE_ACCES tmp
       JOIN STRUCTURE s ON s.SOURCE_CODE = tmp.ETABLISSEMENT_ID
       JOIN ETABLISSEMENT e ON e.STRUCTURE_ID = s.ID
       JOIN SOURCE src ON src.CODE = tmp.SOURCE_ID
       JOIN THESE t ON t.SOURCE_CODE = tmp.THESE_ID;

