-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sygaldb.unicaen.fr;sid=SYGLPROD;port=1523

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW v_diff_structure (source_code, source_id, operation, u_code, u_type_structure_id, u_sigle, u_libelle, s_code, s_type_structure_id, s_sigle, s_libelle, d_code, d_type_structure_id, d_sigle, d_libelle) AS with diff as (
        SELECT 
            coalesce(s.SOURCE_CODE, d.SOURCE_CODE) SOURCE_CODE,
            coalesce(s.source_id, d.source_id) source_id,

            case
            when(s.SOURCE_CODE IS NOT NULL AND d.SOURCE_CODE IS NULL) then 'insert'
            when(s.SOURCE_CODE IS NOT NULL AND d.SOURCE_CODE IS NOT NULL and (d.HISTO_DESTRUCTION IS NULL or d.HISTO_DESTRUCTION > LOCALTIMESTAMP)) then 'update'
            when(s.SOURCE_CODE IS NOT NULL AND d.SOURCE_CODE IS NOT NULL and (d.HISTO_DESTRUCTION IS NOT NULL and d.HISTO_DESTRUCTION <= LOCALTIMESTAMP)) then 'undelete'
            when(s.SOURCE_CODE IS NULL AND d.SOURCE_CODE IS NOT NULL and (d.HISTO_DESTRUCTION IS NULL or d.HISTO_DESTRUCTION > LOCALTIMESTAMP)) then 'delete' end as operation,

            CASE WHEN d.CODE <> s.CODE OR (d.CODE IS NULL AND s.CODE IS NOT NULL) OR (d.CODE IS NOT NULL AND s.CODE IS NULL) THEN 1 ELSE 0 END as U_CODE,
    CASE WHEN d.TYPE_STRUCTURE_ID <> s.TYPE_STRUCTURE_ID OR (d.TYPE_STRUCTURE_ID IS NULL AND s.TYPE_STRUCTURE_ID IS NOT NULL) OR (d.TYPE_STRUCTURE_ID IS NOT NULL AND s.TYPE_STRUCTURE_ID IS NULL) THEN 1 ELSE 0 END as U_TYPE_STRUCTURE_ID,
    CASE WHEN d.SIGLE <> s.SIGLE OR (d.SIGLE IS NULL AND s.SIGLE IS NOT NULL) OR (d.SIGLE IS NOT NULL AND s.SIGLE IS NULL) THEN 1 ELSE 0 END as U_SIGLE,
    CASE WHEN d.LIBELLE <> s.LIBELLE OR (d.LIBELLE IS NULL AND s.LIBELLE IS NOT NULL) OR (d.LIBELLE IS NOT NULL AND s.LIBELLE IS NULL) THEN 1 ELSE 0 END as U_LIBELLE,

            s.CODE AS S_CODE,
    s.TYPE_STRUCTURE_ID AS S_TYPE_STRUCTURE_ID,
    s.SIGLE AS S_SIGLE,
    s.LIBELLE AS S_LIBELLE,

            d.CODE AS D_CODE,
    d.TYPE_STRUCTURE_ID AS D_TYPE_STRUCTURE_ID,
    d.SIGLE AS D_SIGLE,
    d.LIBELLE AS D_LIBELLE

         FROM STRUCTURE d
        JOIN source src ON src.id = d.source_id AND src.importable = 1
        FULL OUTER JOIN SRC_STRUCTURE s ON s.source_id = d.source_id AND s.SOURCE_CODE = d.SOURCE_CODE
    )
    select "SOURCE_CODE","SOURCE_ID","OPERATION","U_CODE","U_TYPE_STRUCTURE_ID","U_SIGLE","U_LIBELLE","S_CODE","S_TYPE_STRUCTURE_ID","S_SIGLE","S_LIBELLE","D_CODE","D_TYPE_STRUCTURE_ID","D_SIGLE","D_LIBELLE" from diff
    where operation is not null
    and (operation = 'undelete' or 0 < U_CODE+U_TYPE_STRUCTURE_ID+U_SIGLE+U_LIBELLE);

