-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sygaldb.unicaen.fr;sid=SYGLPROD;port=1523

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW v_diff_doctorant (source_code, source_id, operation, u_ine, u_individu_id, u_etablissement_id, s_ine, s_individu_id, s_etablissement_id, d_ine, d_individu_id, d_etablissement_id) AS with diff as (
        SELECT 
            coalesce(s.SOURCE_CODE, d.SOURCE_CODE) SOURCE_CODE,
            coalesce(s.source_id, d.source_id) source_id,

            case
            when(s.SOURCE_CODE IS NOT NULL AND d.SOURCE_CODE IS NULL) then 'insert'
            when(s.SOURCE_CODE IS NOT NULL AND d.SOURCE_CODE IS NOT NULL and (d.HISTO_DESTRUCTION IS NULL or d.HISTO_DESTRUCTION > LOCALTIMESTAMP)) then 'update'
            when(s.SOURCE_CODE IS NOT NULL AND d.SOURCE_CODE IS NOT NULL and (d.HISTO_DESTRUCTION IS NOT NULL and d.HISTO_DESTRUCTION <= LOCALTIMESTAMP)) then 'undelete'
            when(s.SOURCE_CODE IS NULL AND d.SOURCE_CODE IS NOT NULL and (d.HISTO_DESTRUCTION IS NULL or d.HISTO_DESTRUCTION > LOCALTIMESTAMP)) then 'delete' end as operation,

            CASE WHEN d.INE <> s.INE OR (d.INE IS NULL AND s.INE IS NOT NULL) OR (d.INE IS NOT NULL AND s.INE IS NULL) THEN 1 ELSE 0 END as U_INE,
    CASE WHEN d.INDIVIDU_ID <> s.INDIVIDU_ID OR (d.INDIVIDU_ID IS NULL AND s.INDIVIDU_ID IS NOT NULL) OR (d.INDIVIDU_ID IS NOT NULL AND s.INDIVIDU_ID IS NULL) THEN 1 ELSE 0 END as U_INDIVIDU_ID,
    CASE WHEN d.ETABLISSEMENT_ID <> s.ETABLISSEMENT_ID OR (d.ETABLISSEMENT_ID IS NULL AND s.ETABLISSEMENT_ID IS NOT NULL) OR (d.ETABLISSEMENT_ID IS NOT NULL AND s.ETABLISSEMENT_ID IS NULL) THEN 1 ELSE 0 END as U_ETABLISSEMENT_ID,

            s.INE AS S_INE,
    s.INDIVIDU_ID AS S_INDIVIDU_ID,
    s.ETABLISSEMENT_ID AS S_ETABLISSEMENT_ID,

            d.INE AS D_INE,
    d.INDIVIDU_ID AS D_INDIVIDU_ID,
    d.ETABLISSEMENT_ID AS D_ETABLISSEMENT_ID

         FROM DOCTORANT d
        JOIN source src ON src.id = d.source_id AND src.importable = 1
        FULL OUTER JOIN SRC_DOCTORANT s ON s.source_id = d.source_id AND s.SOURCE_CODE = d.SOURCE_CODE
    )
    select "SOURCE_CODE","SOURCE_ID","OPERATION","U_INE","U_INDIVIDU_ID","U_ETABLISSEMENT_ID","S_INE","S_INDIVIDU_ID","S_ETABLISSEMENT_ID","D_INE","D_INDIVIDU_ID","D_ETABLISSEMENT_ID" from diff
    where operation is not null
    and (operation = 'undelete' or 0 < U_INE+U_INDIVIDU_ID+U_ETABLISSEMENT_ID);

