-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sygaldb.unicaen.fr;sid=SYGLPROD;port=1523

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW v_situ_depot_vc_valid_pres (id, these_id, individu_id, valide) AS WITH validations_attendues AS (
    SELECT  a.THESE_ID, a.INDIVIDU_ID, tv.ID as TYPE_VALIDATION_ID
     FROM ACTEUR a
             JOIN ROLE r on a.ROLE_ID = r.ID and r.CODE = 'P' -- Président du jury
             JOIN TYPE_VALIDATION tv on tv.code = 'CORRECTION_THESE'
    where a.HISTO_DESTRUCTION is null
)
SELECT
    va.these_id||'_'||va.INDIVIDU_ID as id,
    va.these_id,
    va.INDIVIDU_ID,
    CASE WHEN v.id is not null THEN 1 ELSE 0 END valide
FROM validations_attendues va
         LEFT JOIN VALIDATION v ON
            v.THESE_ID = va.THESE_ID and
            v.INDIVIDU_ID = va.INDIVIDU_ID and -- suppose que l'INDIVIDU_ID soit enregistré lors de la validation
            v.HISTO_DESTRUCTEUR_ID is null and
            v.TYPE_VALIDATION_ID = va.TYPE_VALIDATION_ID;

