-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sygaldb.unicaen.fr;sid=SYGLPROD;port=1523

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW v_situ_attestations (these_id, attestation_id) AS SELECT 
    a.these_id,
    a.id AS attestation_id
 FROM ATTESTATION a
where a.VERSION_CORRIGEE = false and a.HISTO_DESTRUCTEUR_ID is null;

