-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sygaldb.unicaen.fr;sid=SYGLPROD;port=1523

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW v_tmp_anomalie (id, etablissement_id, table_name, source_code, table_column, column_value, description) AS with ds(ETABLISSEMENT_ID, TABLE_NAME, SOURCE_CODE, TABLE_COLUMN, COLUMN_VALUE, DESCRIPTION) as (
    --
    -- TMP_ACTEUR
    --
    SELECT 
        ETABLISSEMENT_ID,
        'TMP_ACTEUR',
        SOURCE_CODE,
        'ETABLISSEMENT_ID',
        ETABLISSEMENT_ID,
        'Aucun enregistrement existant dans ETABLISSEMENT avec CODE = ' || ETABLISSEMENT_ID
     FROM TMP_ACTEUR tmp
    where not exists (select *
                     from STRUCTURE t
                     where t.CODE = tmp.ETABLISSEMENT_ID)

union all

    select
        ETABLISSEMENT_ID,
        'TMP_ACTEUR',
        SOURCE_CODE,
        'SOURCE_ID',
        SOURCE_ID,
        'Aucun enregistrement existant dans SOURCE avec CODE = ' || SOURCE_ID
    from TMP_ACTEUR tmp
    where not exists (select *
                     from SOURCE t
                     where t.CODE = tmp.SOURCE_ID)
    
union all

    select
        ETABLISSEMENT_ID,
        'TMP_ACTEUR',
        SOURCE_CODE,
        'INDIVIDU_ID',
        INDIVIDU_ID,
        'Aucun enregistrement existant dans TMP_INDIVIDU avec SOURCE_CODE = ' || INDIVIDU_ID
    from TMP_ACTEUR tmp
    where not exists (select *
                     from TMP_INDIVIDU t
                     where t.SOURCE_CODE = tmp.INDIVIDU_ID)
    
union all

    select
        ETABLISSEMENT_ID,
        'TMP_ACTEUR',
        SOURCE_CODE,
        'THESE_ID',
        THESE_ID,
        'Aucun enregistrement existant dans TMP_THESE avec SOURCE_CODE = ' || THESE_ID
    from TMP_ACTEUR tmp
    where not exists (select *
                     from TMP_THESE t
                     where t.SOURCE_CODE = tmp.THESE_ID)
    
union all

    select
        ETABLISSEMENT_ID,
        'TMP_ACTEUR',
        SOURCE_CODE,
        'ROLE_ID',
        ROLE_ID,
        'Aucun enregistrement existant dans TMP_ROLE avec SOURCE_CODE = ' || ROLE_ID
    from TMP_ACTEUR tmp
    where not exists (select *
                     from TMP_ROLE t
                     where t.SOURCE_CODE = tmp.ROLE_ID)
    
union all


    --
    -- TMP_DOCTORANT
    --
    select
        ETABLISSEMENT_ID,
        'TMP_DOCTORANT',
        SOURCE_CODE,
        'ETABLISSEMENT_ID',
        ETABLISSEMENT_ID,
        'Aucun enregistrement existant dans ETABLISSEMENT avec CODE = ' || ETABLISSEMENT_ID
    from TMP_DOCTORANT tmp
    where not exists (select *
                     from STRUCTURE t
                     where t.CODE = tmp.ETABLISSEMENT_ID)
    
union all

    select
        ETABLISSEMENT_ID,
        'TMP_DOCTORANT',
        SOURCE_CODE,
        'SOURCE_ID',
        SOURCE_ID,
        'Aucun enregistrement existant dans SOURCE avec CODE = ' || SOURCE_ID
    from TMP_DOCTORANT tmp
    where not exists (select *
                     from SOURCE t
                     where t.CODE = tmp.SOURCE_ID)
    
union all

    select
        ETABLISSEMENT_ID,
        'TMP_DOCTORANT',
        SOURCE_CODE,
        'INDIVIDU_ID',
        INDIVIDU_ID,
        'Aucun enregistrement existant dans TMP_INDIVIDU avec SOURCE_CODE = ' || INDIVIDU_ID
    from TMP_DOCTORANT tmp
    where not exists (select *
                     from TMP_INDIVIDU t
                     where t.SOURCE_CODE = tmp.INDIVIDU_ID)
    
union all


    --
    -- TMP_ECOLE_DOCT
    --
    select
        ETABLISSEMENT_ID,
        'TMP_ECOLE_DOCT',
        SOURCE_CODE,
        'ETABLISSEMENT_ID',
        ETABLISSEMENT_ID,
        'Aucun enregistrement existant dans ETABLISSEMENT avec CODE = ' || ETABLISSEMENT_ID
    from TMP_ECOLE_DOCT tmp
    where not exists (select *
                     from STRUCTURE t
                     where t.CODE = tmp.ETABLISSEMENT_ID)
    
union all

    select
        ETABLISSEMENT_ID,
        'TMP_ECOLE_DOCT',
        SOURCE_CODE,
        'SOURCE_ID',
        SOURCE_ID,
        'Aucun enregistrement existant dans SOURCE avec CODE = ' || SOURCE_ID
    from TMP_ECOLE_DOCT tmp
    where not exists (select *
                     from SOURCE t
                     where t.CODE = tmp.SOURCE_ID)
    
union all

    select
        ETABLISSEMENT_ID,
        'TMP_ECOLE_DOCT',
        SOURCE_CODE,
        'STRUCTURE_ID',
        STRUCTURE_ID,
        'Aucun enregistrement existant dans TMP_STRUCTURE avec SOURCE_CODE = ' || STRUCTURE_ID
    from TMP_ECOLE_DOCT tmp
    where not exists (select *
                     from TMP_STRUCTURE t
                     where t.SOURCE_CODE = tmp.STRUCTURE_ID)
    
union all


    --
    -- TMP_ETABLISSEMENT
    --
    select
        ETABLISSEMENT_ID,
        'TMP_ETABLISSEMENT',
        SOURCE_CODE,
        'ETABLISSEMENT_ID',
        ETABLISSEMENT_ID,
        'Aucun enregistrement existant dans ETABLISSEMENT avec CODE = ' || ETABLISSEMENT_ID
    from TMP_STRUCTURE tmp
    where not exists (select *
                     from STRUCTURE t
                     where t.CODE = tmp.ETABLISSEMENT_ID)
    
union all

    select
        ETABLISSEMENT_ID,
        'TMP_ETABLISSEMENT',
        SOURCE_CODE,
        'SOURCE_ID',
        SOURCE_ID,
        'Aucun enregistrement existant dans SOURCE avec CODE = ' || SOURCE_ID
    from TMP_ETABLISSEMENT tmp
    where not exists (select *
                     from SOURCE t
                     where t.CODE = tmp.SOURCE_ID)
    
union all

    select
        ETABLISSEMENT_ID,
        'TMP_ETABLISSEMENT',
        SOURCE_CODE,
        'STRUCTURE_ID',
        STRUCTURE_ID,
        'Aucun enregistrement existant dans TMP_STRUCTURE avec SOURCE_CODE = ' || STRUCTURE_ID
    from TMP_ETABLISSEMENT tmp
    where not exists (select *
                     from TMP_ETABLISSEMENT t
                     where t.SOURCE_CODE = tmp.STRUCTURE_ID)
    
union all


    --
    -- TMP_INDIVIDU
    --
    select
        ETABLISSEMENT_ID,
        'TMP_INDIVIDU',
        SOURCE_CODE,
        'ETABLISSEMENT_ID',
        ETABLISSEMENT_ID,
        'Aucun enregistrement existant dans ETABLISSEMENT avec CODE = ' || ETABLISSEMENT_ID
    from TMP_INDIVIDU tmp
    where not exists (select *
                     from STRUCTURE t
                     where t.CODE = tmp.ETABLISSEMENT_ID)
    
union all

    select
        ETABLISSEMENT_ID,
        'TMP_INDIVIDU',
        SOURCE_CODE,
        'SOURCE_ID',
        SOURCE_ID,
        'Aucun enregistrement existant dans SOURCE avec CODE = ' || SOURCE_ID
    from TMP_INDIVIDU tmp
    where not exists (select *
                     from SOURCE t
                     where t.CODE = tmp.SOURCE_ID)
    
union all


    --
    -- TMP_ROLE
    --
    select
        ETABLISSEMENT_ID,
        'TMP_ROLE',
        SOURCE_CODE,
        'ETABLISSEMENT_ID',
        ETABLISSEMENT_ID,
        'Aucun enregistrement existant dans ETABLISSEMENT avec CODE = ' || ETABLISSEMENT_ID
    from TMP_ROLE tmp
    where not exists (select *
                     from STRUCTURE t
                     where t.CODE = tmp.ETABLISSEMENT_ID)
    
union all

    select
        ETABLISSEMENT_ID,
        'TMP_ROLE',
        SOURCE_CODE,
        'SOURCE_ID',
        SOURCE_ID,
        'Aucun enregistrement existant dans SOURCE avec CODE = ' || SOURCE_ID
    from TMP_ROLE tmp
    where not exists (select *
                     from SOURCE t
                     where t.CODE = tmp.SOURCE_ID)
    
union all


    --
    -- TMP_STRUCTURE
    --
    select
        ETABLISSEMENT_ID,
        'TMP_STRUCTURE',
        SOURCE_CODE,
        'ETABLISSEMENT_ID',
        ETABLISSEMENT_ID,
        'Aucun enregistrement existant dans ETABLISSEMENT avec CODE = ' || ETABLISSEMENT_ID
    from TMP_STRUCTURE tmp
    where not exists (select *
                     from STRUCTURE t
                     where t.CODE = tmp.ETABLISSEMENT_ID)
    
union all

    select
        ETABLISSEMENT_ID,
        'TMP_STRUCTURE',
        SOURCE_CODE,
        'SOURCE_ID',
        SOURCE_ID,
        'Aucun enregistrement existant dans SOURCE avec CODE = ' || SOURCE_ID
    from TMP_STRUCTURE tmp
    where not exists (select *
                     from SOURCE t
                     where t.CODE = tmp.SOURCE_ID)
    
union all

    select
        ETABLISSEMENT_ID,
        'TMP_STRUCTURE',
        SOURCE_CODE,
        'TYPE_STRUCTURE_ID',
        TYPE_STRUCTURE_ID,
        'Aucun enregistrement existant dans TYPE_STRUCTURE avec CODE = ' || TYPE_STRUCTURE_ID
    from TMP_STRUCTURE tmp
    where not exists (select *
                     from TYPE_STRUCTURE t
                     where t.CODE = tmp.TYPE_STRUCTURE_ID)
    
union all


    --
    -- TMP_THESE
    --
    select
        ETABLISSEMENT_ID,
        'TMP_THESE',
        SOURCE_CODE,
        'ETABLISSEMENT_ID',
        ETABLISSEMENT_ID,
        'Aucun enregistrement existant dans ETABLISSEMENT avec CODE = ' || ETABLISSEMENT_ID
    from TMP_THESE tmp
    where not exists (select *
                     from STRUCTURE t
                     where t.CODE = tmp.ETABLISSEMENT_ID)
    
union all

    select
        ETABLISSEMENT_ID,
        'TMP_THESE',
        SOURCE_CODE,
        'SOURCE_ID',
        SOURCE_ID,
        'Aucun enregistrement existant dans SOURCE avec CODE = ' || SOURCE_ID
    from TMP_THESE tmp
    where not exists (select *
                     from SOURCE t
                     where t.CODE = tmp.SOURCE_ID)
    
union all

    select
        ETABLISSEMENT_ID,
        'TMP_THESE',
        SOURCE_CODE,
        'DOCTORANT_ID',
        DOCTORANT_ID,
        'Aucun enregistrement existant dans TMP_DOCTORANT avec SOURCE_CODE = ' || DOCTORANT_ID
    from TMP_THESE tmp
    where not exists (select *
                     from TMP_DOCTORANT t
                     where t.SOURCE_CODE = tmp.DOCTORANT_ID)
    
union all

    select
        ETABLISSEMENT_ID,
        'TMP_THESE',
        SOURCE_CODE,
        'ECOLE_DOCT_ID',
        ECOLE_DOCT_ID,
        'Aucun enregistrement existant dans TMP_ECOLE_DOCT avec SOURCE_CODE = ' || ECOLE_DOCT_ID
    from TMP_THESE tmp
    where not exists (select *
                     from TMP_ECOLE_DOCT t
                     where t.SOURCE_CODE = tmp.ECOLE_DOCT_ID)
    
union all

    select
        ETABLISSEMENT_ID,
        'TMP_THESE',
        SOURCE_CODE,
        'UNITE_RECH_ID',
        UNITE_RECH_ID,
        'Aucun enregistrement existant dans TMP_UNITE_RECH avec SOURCE_CODE = ' || UNITE_RECH_ID
    from TMP_THESE tmp
    where not exists (select *
                     from TMP_UNITE_RECH t
                     where t.SOURCE_CODE = tmp.UNITE_RECH_ID)
    
union all


    --
    -- TMP_UNITE_RECH
    --
    select
        ETABLISSEMENT_ID,
        'TMP_UNITE_RECH',
        SOURCE_CODE,
        'ETABLISSEMENT_ID',
        ETABLISSEMENT_ID,
        'Aucun enregistrement existant dans ETABLISSEMENT avec CODE = ' || ETABLISSEMENT_ID
    from TMP_UNITE_RECH tmp
    where not exists (select *
                     from STRUCTURE t
                     where t.CODE = tmp.ETABLISSEMENT_ID)
    
union all

    select
        ETABLISSEMENT_ID,
        'TMP_UNITE_RECH',
        SOURCE_CODE,
        'SOURCE_ID',
        SOURCE_ID,
        'Aucun enregistrement existant dans SOURCE avec CODE = ' || SOURCE_ID
    from TMP_UNITE_RECH tmp
    where not exists (select *
                     from SOURCE t
                     where t.CODE = tmp.SOURCE_ID)
    
union all

    select
        ETABLISSEMENT_ID,
        'TMP_UNITE_RECH',
        SOURCE_CODE,
        'STRUCTURE_ID',
        STRUCTURE_ID,
        'Aucun enregistrement existant dans TMP_STRUCTURE avec SOURCE_CODE = ' || STRUCTURE_ID
    from TMP_UNITE_RECH tmp
    where not exists (select *
                     from TMP_STRUCTURE t
                     where t.SOURCE_CODE = tmp.STRUCTURE_ID)
    
union all


    --
    -- TMP_VARIABLE
    --
    select
        ETABLISSEMENT_ID,
        'TMP_VARIABLE',
        SOURCE_CODE,
        'ETABLISSEMENT_ID',
        ETABLISSEMENT_ID,
        'Aucun enregistrement existant dans ETABLISSEMENT avec CODE = ' || ETABLISSEMENT_ID
    from TMP_VARIABLE tmp
    where not exists (select *
                     from STRUCTURE t
                     where t.CODE = tmp.ETABLISSEMENT_ID)
    
union all

    select
        ETABLISSEMENT_ID,
        'TMP_VARIABLE',
        SOURCE_CODE,
        'SOURCE_ID',
        SOURCE_ID,
        'Aucun enregistrement existant dans SOURCE avec CODE = ' || SOURCE_ID
    from TMP_VARIABLE tmp
    where not exists (select *
                     from SOURCE t
                     where t.CODE = tmp.SOURCE_ID)
)

select row_number() over (order by 1,2,3,4,5,6) as id, ETABLISSEMENT_ID, TABLE_NAME, SOURCE_CODE, TABLE_COLUMN, COLUMN_VALUE, DESCRIPTION
from ds;

