-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sygaldb.unicaen.fr;sid=SYGLPROD;port=1523

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

\i ./schema/views/V_SITU_ARCHIVAB_VO_view.sql
\i ./schema/views/SRC_TITRE_ACCES_view.sql
\i ./schema/views/V_SITU_ARCHIVAB_VAC_view.sql
\i ./schema/views/SRC_FINANCEMENT_view.sql
\i ./schema/views/V_SITU_RDV_BU_SAISIE_BU_view.sql
\i ./schema/views/V_INDIVIDU_ROLE_view.sql
\i ./schema/views/V_SITU_DEPOT_VO_view.sql
\i ./schema/views/SRC_ETABLISSEMENT_view.sql
\i ./schema/views/V_SITU_DEPOT_PV_SOUT_view.sql
\i ./schema/views/V_SITU_ARCHIVAB_VOC_view.sql
\i ./schema/views/V_SITU_DEPOT_VA_view.sql
\i ./schema/views/V_SITU_ATTESTATIONS_VOC_view.sql
\i ./schema/views/V_SITU_RDV_BU_SAISIE_DOCT_view.sql
\i ./schema/views/V_SITU_ARCHIVAB_VA_view.sql
\i ./schema/views/V_SITU_DEPOT_VC_VALID_PRES_view.sql
\i ./schema/views/V_TMP_ANOMALIE_view.sql
\i ./schema/views/V_SITU_VERIF_VA_view.sql
\i ./schema/views/SRC_INDIVIDU_view.sql
\i ./schema/views/SRC_ORIGINE_FINANCEMENT_view.sql
\i ./schema/views/SRC_UNITE_RECH_view.sql
\i ./schema/views/SRC_ROLE_view.sql
\i ./schema/views/SRC_THESE_ANNEE_UNIV_view.sql
\i ./schema/views/SRC_VARIABLE_view.sql
\i ./schema/views/V_SITU_AUTORIS_DIFF_THESE_view.sql
\i ./schema/views/V_SITU_DEPOT_VOC_view.sql
\i ./schema/views/SRC_ACTEUR_view.sql
\i ./schema/views/V_SITU_ATTESTATIONS_view.sql
\i ./schema/views/V_SITU_RDV_BU_VALIDATION_BU_view.sql
\i ./schema/views/SRC_THESE_view.sql
\i ./schema/views/V_SITU_SIGNALEMENT_THESE_view.sql
\i ./schema/views/V_SITU_DEPOT_VC_VALID_PRES_NEW_view.sql
\i ./schema/views/SRC_DOCTORANT_view.sql
\i ./schema/views/V_SITU_AUTORIS_DIFF_THESE_VOC_view.sql
\i ./schema/views/V_SITU_DEPOT_RAPPORT_SOUT_view.sql
\i ./schema/views/V_SITU_VERSION_PAPIER_CORRIGEE_view.sql
\i ./schema/views/SRC_ECOLE_DOCT_view.sql
\i ./schema/views/V_SITU_VERIF_VAC_view.sql
\i ./schema/views/V_SITU_DEPOT_VC_VALID_DOCT_view.sql
\i ./schema/views/V_THESE_ANNEE_UNIV_FIRST_view.sql
\i ./schema/views/SRC_STRUCTURE_view.sql
\i ./schema/views/V_SITU_DEPOT_VAC_view.sql
\i ./schema/views/V_SITU_VALIDATION_PAGE_COUV_view.sql
\i ./schema/views/V_WF_ETAPE_PERTIN_view.sql
\i ./schema/views/V_DIFF_ROLE_view.sql
\i ./schema/views/V_DIFF_THESE_ANNEE_UNIV_view.sql
\i ./schema/views/V_DIFF_INDIVIDU_view.sql
\i ./schema/views/V_DIFF_ORIGINE_FINANCEMENT_view.sql
\i ./schema/views/V_DIFF_DOCTORANT_view.sql
\i ./schema/views/V_DIFF_ACTEUR_view.sql
\i ./schema/views/V_DIFF_THESE_view.sql
\i ./schema/views/V_DIFF_UNITE_RECH_view.sql
\i ./schema/views/V_DIFF_ETABLISSEMENT_view.sql
\i ./schema/views/V_DIFF_ECOLE_DOCT_view.sql
\i ./schema/views/V_DIFF_TITRE_ACCES_view.sql
\i ./schema/views/V_DIFF_FINANCEMENT_view.sql
\i ./schema/views/V_DIFF_VARIABLE_view.sql
\i ./schema/views/V_DIFF_STRUCTURE_view.sql
\i ./schema/views/V_DIFF_INDIVIDU_INDICATEUR_view.sql
\i ./schema/views/V_WORKFLOW_view.sql

