<?php
/**
 * @var \Laminas\Form\Form $form
 */

use These\Fieldset\Direction\DirectionFieldset;

?>

<fieldset>
    <?php
    $fs = $form->get('direction');
//    echo $this->formHidden($fs->get('id'));
    ?>

    <h3>Directeur·trice de thèse <span class="icon icon-information"
                                        title="Un·e seul·e directeur·trice de thèse"></span></h3>
    <div class="mb-3">
        <div class="row directeur">
            <div class="col-md-4">
                <div class="row">
                    <div class="col-md-12">
                        <?php echo $this->formControlGroup($fs->get('directeur-individu')); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-10">
                        <?php echo $this->formControlGroup($fs->get('directeur-qualite')); ?>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <?php echo $this->formControlGroup($fs->get('directeur-uniteRecherche')); ?>
                <?php echo $this->formControlGroup($fs->get('directeur-ecoleDoctorale')); ?>
                <?php echo $this->formControlGroup($fs->get('directeur-etablissement')); ?>
            </div>
            <div class="col-md-1">

            </div>
            <div class="col-md-1 pull-right">
                <span data-target-id="directeur" class="erase-acteur icon icon-historiser"
                      title="Vider les champs concernant le directeur"></span>
            </div>
        </div>
    </div>

    <div class="mb-3">
        <?php for ($i = 1; $i <= DirectionFieldset::NBCODIR; $i++)  : ?>
            <hr>
            <h3>
                <?php echo $this->formElement($fs->get('codirecteur' . $i . '-enabled')); ?>
                Codirecteur·trice de thèse n°<?php echo $i ?>
            </h3>

            <div class="row codirecteur codirecteur<?php echo $i ?>">
                <div class="col-md-4">
                    <div class="row">
                        <div class="col-md-12">
                            <?php echo $this->formControlGroup($fs->get('codirecteur' . $i . '-individu')); ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-10">
                            <?php echo $this->formControlGroup($fs->get('codirecteur' . $i . '-qualite')); ?>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <?php echo $this->formControlGroup($fs->get('codirecteur' . $i . '-uniteRecherche')); ?>
                    <?php echo $this->formControlGroup($fs->get('codirecteur' . $i . '-ecoleDoctorale')); ?>
                    <?php echo $this->formControlGroup($fs->get('codirecteur' . $i . '-etablissement')); ?>
                </div>
                <div class="col-md-1">
                    <?php if ($fs->has($name = 'codirecteur' . $i . '-principal')): ?>
                        <?php echo $this->formControlGroup($fs->get($name)); ?>
                    <?php endif ?>
                    <?php if ($fs->has($name = 'codirecteur' . $i . '-exterieur')): ?>
                        <?php echo $this->formControlGroup($fs->get($name)); ?>
                    <?php endif ?>
                </div>
                <div class="col-md-1 pull-right">
                    <span data-target-id="codirecteur<?php echo $i; ?>" class="erase-acteur icon icon-historiser"
                          title="Vider les champs concernant ce codirecteur"></span>
                </div>
            </div>
        <?php endfor; ?>
    </div>

</fieldset>


<script>
    $(function() {
        $("select.select2").select2();

        const updateCodirecteurDiv = function($enabler) {
            const codirId = $enabler.data('codirecteur-id');
            if ($enabler.is(':checked')) {
                $("div.codirecteur" + codirId).show();
                if (codirId === 1) {
                    // activer le 1er codir redonne la possibilité d'activer le 2nd
                    $(".codirecteur-enabler").not($enabler).prop('disabled', false);
                }
            } else {
                if (codirId === 1) {
                    // désactiver le 1er codir désactive et interdit d'activer le 2nd
                    $("div.codirecteur").hide();
                    $(".codirecteur-enabler").prop('checked', false);
                    $(".codirecteur-enabler").not($enabler).prop('disabled', true);
                } else {
                    $("div.codirecteur" + codirId).hide();
                }
            }
        };
        $(".codirecteur-enabler").on('change', function() {
            updateCodirecteurDiv($(this));
        });
        $(".codirecteur-enabler").each(function() {
            updateCodirecteurDiv($(this));
        });

        $('.erase-acteur').click(function() {
            let container = $("div." + $(this).data('target-id'));
            container.find("input").val('');
            container.find("select").val(null).trigger('change');
        });
    });
</script>

<style>
    span.erase-acteur {
        cursor: pointer;
    }
</style>
