<?php
/**
 * @var \Laminas\Form\Form $form
 */

use These\Fieldset\Encadrement\EncadrementFieldset;

?>

<fieldset>
    <legend>Encadrement</legend>

    <?php
    $fs = $form->get('encadrements');
    echo $this->formHidden($fs->get('id'));
    ?>

    <h3>Coencadrant·e de thèse</h3>
    <div class="mb-3">
        <?php for ($i = 1; $i <= EncadrementFieldset::NB_COENCADRANTS_MAXI; $i++)  : ?>
            <div class="row coencadrant<?php echo $i ?>">
                <div class="col-md-4"><?php echo $this->formControlGroup($fs->get('coencadrant' . $i . '-individu')); ?></div>
                <div class="col-md-1 pull-right">
                    <span data-target-id="coencadrant<?php echo $i; ?>" class="erase-acteur icon icon-historiser"
                          title="Remise à zéro"></span>
                </div>
            </div>
        <?php endfor; ?>
    </div>

</fieldset>


<script>
    $(function() {
        $('.erase-acteur').click(function() {
            let container = $("div." + $(this).data('target-id'));
            container.find("input").val('');
            container.find("select.selectpicker").selectpicker('val', '');
        });
    });
</script>

<style>
    span.erase-acteur {
        cursor: pointer;
    }
</style>
