<?php

use Application\Constants;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var \DateTime $date
 *
 * @see \These\Controller\TheseController::accorderSursisCorrectionAction()
 */

echo $this->confirm(sprintf(
    "Confirmez-vous l'accord d'un sursis d'une semaine à compter d'aujourd'hui, portant la date butoir au %s ?",
    $date->format(Constants::DATE_FORMAT)
));
