<?php

use Application\Constants;
use Application\Entity\Db\DomaineHal;
use Application\Entity\Db\Utilisateur;
use Application\Entity\Db\Validation;
use Application\Filter\FinancementFormatter;
use Application\Provider\Privilege\UtilisateurPrivileges;
use Application\View\Renderer\PhpRenderer;
use Depot\Provider\Privilege\DepotPrivileges;
use Doctorant\Provider\Privilege\DoctorantPrivileges;
use Doctorant\Provider\Privilege\MissionEnseignementPrivileges;
use Doctrine\ORM\PersistentCollection;
use Individu\Provider\Privilege\IndividuPrivileges;
use Individu\View\Helper\IndividuUsurpationHelper;
use Structure\Entity\Db\EtablissementRattachement;
use These\Controller\TheseController;
use These\Entity\Db\Acteur;
use These\Entity\Db\These;
use These\Filter\ActeursFormatter;
use These\Provider\Privilege\ActeurPrivileges;
use These\Provider\Privilege\CoEncadrantPrivileges;
use These\Provider\Privilege\ThesePrivileges;

/**
 * @var PhpRenderer  $this
 * @var These        $these
 * @var string       $modifierEmailContactUrl
 * @var string       $modifierEmailContactConsentUrl
 * @var bool         $estDoctorant
 * @var string       $modifierCorrecAutorUrl
 * @var string       $accorderSursisCorrecUrl
 * @var string       $nextStepUrl
 * @var Validation[] $validationsDesCorrectionsEnAttente
 * @var Utilisateur[] $utilisateurs
 * @var EtablissementRattachement[] $rattachements
 *
 * @see TheseController::detailIdentiteAction()
 */

$canVoirEmailContact = $this->isAllowed($these, DoctorantPrivileges::DOCTORANT_AFFICHER_EMAIL_CONTACT);
$canEditEmailContact = $this->isAllowed($these, DoctorantPrivileges::DOCTORANT_MODIFIER_EMAIL_CONTACT);
$canEditEmailContactConsent = $this->isAllowed($these, DoctorantPrivileges::DOCTORANT_MODIFIER_EMAIL_CONTACT);
$emailContactModifiedEvent = 'email-contact-modified-event';
$emailContactConsentModifiedEvent = 'email-contact-consent-modified-event';
$canCreate = $this->isAllowed(UtilisateurPrivileges::getResourceId(UtilisateurPrivileges::UTILISATEUR_CREATE_FROM_INDIVIDU));

$canCoEncadrantAfficher = $this->isAllowed(CoEncadrantPrivileges::getResourceId(CoEncadrantPrivileges::COENCADRANT_AFFICHER));
$canCoEncadrantGerer    = $this->isAllowed(CoEncadrantPrivileges::getResourceId(CoEncadrantPrivileges::COENCADRANT_GERER));

$canMissionAfficher = $this->isAllowed(MissionEnseignementPrivileges::getResourceId(MissionEnseignementPrivileges::MISSION_ENSEIGNEMENT_VISUALISER));
$canMissionGerer    = $this->isAllowed(MissionEnseignementPrivileges::getResourceId(MissionEnseignementPrivileges::MISSION_ENSEIGNEMENT_MODIFIER));

$canDomaineHalModifier = $this->isAllowed($these,ThesePrivileges::THESE_MODIFICATION_DOMAINES_HAL_THESE);

$canEditForcageCorrectionAutorisee = $this->isAllowed($these, DepotPrivileges::THESE_SAISIE_CORREC_AUTORISEE_FORCEE);

$financementFormatter = $this->financementFormatter();
$financementFormatter->setSortBy(FinancementFormatter::SORT_BY_DATE);
$financementFormatter->setDisplayAs(FinancementFormatter::DISPLAY_AS_HTML_LINES);

$acteursFormatter = new ActeursFormatter();
$acteursFormatter->paramDisplay(["role" => true, "complement" => true, "qualite" => true, "etablissement" => true, "uniteRecherche" => true]);
$acteursFormatter->asArray(true);
$acteursFormatted = $acteursFormatter->doFormat($these->getActeursSorted()->toArray());

$hasCoEncadrant = false;
?>

<?php $this->headTitle($this->translate("Thèse"))->prepend($these->getDoctorant()->getIndividu()->getNomUsuel()) ?>

<?php echo $this->alertes()
    ->addAlertesFromDatabase()
    ->addAlertesFromFlashMessenger()
    ->renderAsBootstrapToasts() ?>

<h1 class="page-header">
    <?php echo $this->translate("Thèse"); ?>
    <small><?php echo $this->partial('these/these/partial/titre') ?></small>
</h1>

<div class="box card">

    <div class="card-header bg-dark text-white">
        <h2 class="first">
            <?php echo $this->translate("Fiche"); ?>
        </h2>
    </div>

    <div class="card-body">

        <div id="photo-div" class="float-end">
            <!--            <div class="photo-placeholder loading"-->
            <!--                 data-src="-->
            <?php //echo $this->url('leocarte/photo', ['id' => $these->getDoctorant()->getSourceCodeSansPrefix()]) ?><!--"></div>-->
        </div>

        <dl class="row these">

            <dt class="col-md-3">
                <?php echo $this->translate("Doctorant"); ?>
            </dt>
            <dd class="col-md-9">
                <?php echo sprintf("%s (%s)",
                    $these->getDoctorant()->getIndividu()->getNomComplet(true, true, true),
                    $these->getDoctorant()->getIndividu()->getDateNaissanceToString());
                ?>
                <?php
                $canVisualiserIndividu = $this->isAllowed($these->getDoctorant()->getIndividu(), IndividuPrivileges::INDIVIDU_CONSULTER);
                if ($canVisualiserIndividu) {
                echo " <a href='".$this->url('individu/voir', ['individu' => $these->getDoctorant()->getIndividu()->getId()], [], true) ."'>";
                echo "<span class='icon icon-voir' title='Accéder à la fiche détaillée de cet individu'></span></a>";
                }
                ?>
                <?php
                // bouton d'usurpation d'identité
                $individuUsurpationHelper = $this->plugin('individuUsurpation'); /* @var $individuUsurpationHelper IndividuUsurpationHelper */
                $individuUsurpationHelper->setIndividu($these->getDoctorant()->getIndividu());
                echo $individuUsurpationHelper();
                ?>
                <br>

                <strong>
                    <?php echo $this->translate("Nationalité :"); ?>
                </strong>
                <?php echo $these->getDoctorant()->getNationalite() ?> <br>

                <strong>
                    <?php echo $this->translate("N° étudiant :"); ?>
                </strong>
                <?php echo $these->getDoctorant()->getNumeroEtudiant() ?> <br>

                <strong>
                    <?php echo $this->translate("Adresse institutionnelle :"); ?>
                </strong>
                <?php if ($email = $these->getDoctorant()->getIndividu()->getEmailPro()): ?>
                    <a href="mailto: <?php echo $email ?>"><?php echo $email ?></a>
                <?php else: ?>
                    <?php echo $this->translate("(Inconnu)"); ?>
                <?php endif ?>

                <?php if ($canVoirEmailContact) : ?>
                    <br>
                    <strong>
                        <?php echo $this->translate("Adresse de contact :"); ?>
                    </strong>
                    <?php if ($mailContact = $these->getDoctorant()->getIndividu()->getEmailContact()): ?>
                        <a href="mailto: <?php echo $mailContact = $these->getDoctorant()->getIndividu()->getEmailContact() ?>"><?php echo $mailContact ?></a>
                    <?php else: ?>
                        (Non renseignée)
                    <?php endif; ?>
                    <?php if ($canEditEmailContact): ?>
                        <a href="<?php echo $modifierEmailContactUrl ?>"
                           title="Modifer l'adresse de contact"
                           data-event="<?php echo $emailContactModifiedEvent ?>"
                           class="btn btn-secondary btn-sm ajax-modal">
                            <?php echo $this->translate(($mailContact ? "Modifier" : "Renseigner") .  " l'adresse de contact"); ?>
                        </a>
                    <?php endif ?>
                    <?php if ($canEditEmailContactConsent): ?>
                        <a href="<?php echo $modifierEmailContactConsentUrl ?>"
                           title="Votre consentement à utiliser l'adresse de contact"
                           data-event="<?php echo $emailContactConsentModifiedEvent ?>"
                           class="btn btn-secondary btn-sm ajax-modal">
                            <?php echo $this->translate("Consentement"); ?>
                        </a>
                    <?php endif ?>
                <?php endif; ?>
            </dd>

            <?php /** @var \Application\Entity\Db\Role $role */ ?>
            <?php foreach ($acteursFormatted as $role => $acteurs): ?>
                <dt class="col-md-3">
                    <?php echo $role ?>
                </dt>
                <dd class="col-md-9 acteurs">
                    <table class="table table-extra-condensed">
                    <?php foreach ($acteurs as $i => $result): ?>
                        <?php
                        /** @var Acteur $acteur */
                        $acteur = $result["acteur"];
                        if ($acteur->getRole()->isCoEncadrant()) $hasCoEncadrant = true;
                        ?>
                        <tr>
                            <td style="width: 30%">
                                <?php
                                $ligne = [];
                                $canVisualiserIndividu = $this->isAllowed($acteur->getIndividu(), IndividuPrivileges::INDIVIDU_CONSULTER);
                                if ($canVisualiserIndividu) {
                                    $identite = " <a href='".$this->url('individu/voir', ['individu' => $acteur->getIndividu()->getId()], [], true) ."'>" .
                                        "<span title='Accéder à la fiche détaillée de cet individu'>" . $result["nom"] . "</span></a>";
                                } else {
                                    $identite = $result["nom"];
                                }
                                if ($acteur->getRole()->estUsurpable() && ! isset($result['alerte-supann-id'])) {
                                    // bouton d'usurpation d'identité
                                    $individuUsurpationHelper = $this->plugin('individuUsurpation');
                                    /* @var $individuUsurpationHelper IndividuUsurpationHelper */
                                    $individuUsurpationHelper->setIndividu($acteur->getIndividu());
                                    $identite .= $individuUsurpationHelper();
                                }
                                $ligne[] = $identite;
                                if (isset($result["complement"])) {
                                    $ligne[] = "<strong>" . $result["complement"] . "</strong>";
                                }
                                if (isset($result["qualite"]) && trim($result["qualite"]) != "") {
                                    $ligne[] = $result["qualite"];
                                }
                                echo implode('<br>', $ligne);
                                ?>
                            </td>
                            <td style="width: 55%">
                                <?php
                                $ligne = [];
                                if (isset($result["etablissementForce"]) && trim($result["etablissementForce"]) != "") {
                                    $ligne[] = sprintf("<span class='text-structure etablissement'><em title='Valeur forcée (initialement : %s)'>%s</em></span>",
                                        $result["etablissement"] ?? 'vide',
                                        $result["etablissementForce"],
                                    );
                                }
                                elseif (isset($result["etablissement"]) && trim($result["etablissement"]) != "") {
                                    $ligne[] = "<span class='text-structure etablissement'>" . $result["etablissement"] . "</span>";
                                }

                                if (isset($result["uniteRecherche"]) && trim($result["uniteRecherche"]) != "") {
                                    $ligne[] = "<span class='text-structure ur'>" . $result["uniteRecherche"] . "</span>";
                                }
                                echo implode('<br>', $ligne);
                                ?>
                            </td>
                            <td>
                                <div class="float-end">
                                    <?php if ($canCoEncadrantGerer && $acteur->estCoEncadrant()): /**  @see CoEncadrantController::ajouterCoEncadrantAction() */ ?>
                                        <a class="iconly ajax-modal" data-event="modification"
                                           href="<?php echo $this->url('co-encadrant/ajouter-co-encadrant', ['these' => $these->getId()], [], true); ?>"
                                           title="Ajouter un·e co-encadrant·e">
                                            <span class="icon icon-plus"></span></a>
                                    <?php endif; ?>
                                    <?php if ($canCoEncadrantAfficher && $acteur->estCoEncadrant()): /** @see \These\Controller\CoEncadrantController::historiqueAction() */ ?>
                                        <a href="<?php echo $this->url('co-encadrant/historique', ['co-encadrant' => $acteur->getId()], [], true) ?>">
                                            <span class='icon icon-listing' title='Voir historique de co-encadrement'></span></a>
                                    <?php endif ?>
                                    <?php if ($canCoEncadrantGerer && $acteur->estCoEncadrant()): /** @see \These\Controller\CoEncadrantController::retirerCoEncadrantAction() */ ?>
                                        <a href="<?php echo $this->url('co-encadrant/retirer-co-encadrant', ['these' => $these->getId(), 'co-encadrant' => $acteur->getId()], [], true) ?>"
                                           data-toggle="confirmationx" data-message="Êtes-vous sûr·e de vouloir retirer ce·tte co-encadrant·e ?">
                                            <span class='icon icon-delete iconly' title='Retirer le co-encadrant'></span></a>
                                    <?php endif ?>
                                    <?php
                                    $canEditActeur =
                                        $this->isAllowed($acteur, ActeurPrivileges::MODIFIER_ACTEUR_TOUTES_THESES) ||
                                        $this->isAllowed($acteur, ActeurPrivileges::MODIFIER_ACTEUR_SES_THESES);
                                    ?>
                                    <?php if ($canEditActeur): ?>
                                        <a href="<?php echo $this->url('these/acteur/modifier', ['acteur' => $acteur->getId()], [], true) ?>"
                                           class="ajax-modal" data-event="modification">
                                            <span class='icon icon-edit iconly' title='Modifier cet acteur'></span></a>
                                    <?php endif ?>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach ?>
                    </table>
                </dd>
            <?php endforeach ?>

            <?php if (!$hasCoEncadrant && $canCoEncadrantGerer) : ?>
                <dt class="col-md-3">
                    Co-encadrant
                </dt>
                <dd class="col-md-9 acteurs">
                    <table class="table table-extra-condensed">
                        <tr>
                            <td style="width: 30%">
                                Aucun.
                            </td>
                            <td style="width: 55%">

                            </td>
                            <td>
                                <div class="float-end">
                                    <a <?php /**  @see CoEncadrantController::ajouterCoEncadrantAction() */ ?>
                                            class="iconly ajax-modal" data-event="modification"
                                            href="<?php echo $this->url('co-encadrant/ajouter-co-encadrant', ['these' => $these->getId()], [], true); ?>"
                                            title="Ajouter un·e co-encadrant·e"><span class="icon icon-plus"></span></a>
                                </div>
                            </td>
                        </tr>
                    </table>
                </dd>
            <?php endif; ?>

            <dt class="col-md-3">
                <?php echo $this->translate("Établissement d'inscription"); ?>
            </dt>
            <dd class="col-md-9">
                <?php if ($these->getEtablissement()): ?>
                    <span class="text-structure etablissement"><?php echo $these->getEtablissement()->getStructure()->getLibelle() ?></span>
                <?php else: ?>
                    <div class='alert alert-sm alert-warning'>
                        <span class='fas fa-exclamation-triangle'></span> Aucun établissement n'est renseignée.
                    </div>
                <?php endif; ?>
            </dd>

            <dt class="col-md-3">
                <?php echo $this->translate("Titre d'accès à l'inscr. en thèse") ?>
            </dt>
            <dd class="col-md-9">
                <?php
                echo ($titreAcces = $these->getTitreAcces()) ?: "(Non renseigné)";
                ?>
            </dd>

            <dt class="col-md-3">
                <?php echo $this->translate("Unité de recherche (UR)"); ?>
            </dt>
            <dd class="col-md-9">

                <?php if ($these->getUniteRecherche()): ?>
                    <span class="text-structure ur"><?php echo $these->getUniteRecherche() ?></span>
                <?php elseif ($these->getCodeUniteRecherche() && $these->getLibelleUniteRecherche()): ?>
                    <?php echo $these->getCodeUniteRecherche() . " - " . $these->getLibelleUniteRecherche() ?>
                    <div class='alert alert-sm alert-warning'>
                        <span class='fas fa-exclamation-triangle'></span> Utilisation du champs libre (unité de recherche mal renseignée).
                    </div>
                <?php else: ?>
                    <div class='alert alert-sm alert-warning'>
                        <span class='fas fa-exclamation-triangle'></span> Aucune unité de recherche n'est renseignée
                    </div>
                <?php endif; ?>
            </dd>

            <dt class="col-md-3 ps-4">
                Établ. de rattachement de l'UR
            </dt>
            <dd class="col-md-9 ps-4">
                <?php if (empty($rattachements)): ?>
                (Aucun établissement de rattachement renseigné)
                <?php else: ?>
                <ul>
                <?php foreach ($rattachements as $rattachement): ?>
                    <li><?php echo $rattachement->getEtablissement()->getStructure() ?></li>
                <?php endforeach ?>
                </ul>
                <?php endif ?>
            </dd>

            <dt class="col-md-3">
                <?php echo $this->translate("École doctorale (ED)"); ?>
            </dt>
            <dd class="col-md-9">
                <?php if ($these->getEcoleDoctorale()): ?>
                    <span class="text-structure ed"><?php echo $these->getEcoleDoctorale() ?></span>
                <?php else: ?>
                    <div class='alert alert-sm alert-warning'>
                        <span class='fas fa-exclamation-triangle'></span> Aucune école doctorale n'est renseignée.
                    </div>
                <?php endif ?>
            </dd>

            <dt class="col-md-3">
                Financement·s
            </dt>
            <dd class="col-md-9">
                <?php if ($these->getFinancements()->isEmpty()): ?>
                    (Non renseigné)
                <?php else: ?>
                    <?php echo $financementFormatter->format($these->getFinancements()->toArray()); ?>
                <?php endif ?>
            </dd>

            <?php if ($canMissionAfficher) : ?>
                <dt class="col-md-3">
                    Mission·s d'enseignement
                </dt>
                <dd class="col-md-9">
                <?php if ($canMissionGerer) : ?>
                    <a  <?php /**  @see \Doctorant\Controller\MissionEnseignementController::ajouterAction() */ ?>
                            class="icon icon-plus iconly ajax-modal float-end" data-event="modification"
                            href="<?php echo $this->url('doctorant/mission-enseignement/ajouter', ['doctorant' => $these->getDoctorant()->getId()], [], true); ?>"
                            title="Ajouter une mission d'enseignement"></a>
                <?php endif; ?>
                <?php if (empty($missions)) : ?>
                    (Aucune mission renseignée)
                <?php else: ?>
                    <ul>
                    <?php foreach ($missions as $mission) : ?>
                        <li>Mission d'enseignement pour l'année <?php echo $mission->getAnneeUniversitaire(); ?>/<?php echo ($mission->getAnneeUniversitaire()+1); ?>
                        <?php if ($canMissionGerer) : ?>
                            <a  <?php /**  @see \Doctorant\Controller\MissionEnseignementController::retirerAction() */ ?>
                                    class="ajax-modal" data-event="modification"
                                    data-toggle="confirmationx" data-message="Êtes-vous sûr·e de vouloir retirer cette mission d'enseignement ?"
                                    href="<?php echo $this->url('doctorant/mission-enseignement/retirer', ['mission' => $mission->getId(), 'doctorant' => $these->getDoctorant()->getId()], [], true); ?>"
                            ><span class="icon icon-supprimer"></span></a>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </dd>
            <?php endif; ?>

            <dt class="col-md-3">
                <?php echo $this->translate("Titre"); ?>
            </dt>
            <dd class="col-md-9">
                <?php echo $these->getTitre() ?>
            </dd>

            <dt class="col-md-3">
                <?php echo $this->translate("Confidentialité"); ?>
            </dt>
            <?php if ($these->etaitConfidentielle()): ?>
                <dd class="col-md-9">Confidentielle, jusqu'au <?php echo $these->getDateFinConfidentialiteToString() ?></dd>
            <?php elseif ($these->estConfidentielle()): ?>
                <dd class="col-md-9 text-danger">Confidentielle,
                    jusqu'au <?php echo $these->getDateFinConfidentialiteToString() ?></dd>
            <?php else: ?>
                <dd class="col-md-9">Non confidentielle</dd>
            <?php endif ?>

            <dt class="col-md-3">État</dt>
            <dd class="col-md-9">
                <span class="badge bg-secondary"><?php echo $these->getEtatTheseToString() ?></span>
            </dd>

            <?php if ($resultat = $these->getResultatToString(false)): ?>
                <dt class="col-md-3">Résultat</dt>
                <dd class="col-md-9">
                    <?php echo $resultat ?>
                </dd>
            <?php endif ?>

            <dt class="col-md-3">Discipline</dt>
            <dd class="col-md-9"><?php echo $these->getLibelleDiscipline() ?></dd>

            <dt class="col-md-3">Domaine(s) HAL</dt>
            <dd class="col-md-9">
                <?php
                if ($these->getDomainesHal() instanceof PersistentCollection && $these->getDomainesHal()->isEmpty()){ ?>
                    <em> Aucun domaine HAL de renseigné </em><br>
                <?php }else{ ?>
                    <ul>
                        <?php foreach($these->getDomainesHal() as $domaine){ ?>
                            <li>
                                <?php
                                /** @var DomaineHal $domaine */
                                echo $domaine->getFrDomainS();
                                ?>
                            </li>
                        <?php } ?>
                    </ul>
                <?php }
                if($canDomaineHalModifier){?>
                    <a  <?php /**  @see \These\Controller\DomaineHalSaisieController::saisieDomaineHalAction() */ ?>
                        class="btn btn-primary ajax-modal" data-event="modification"
                        href="<?php echo $this->url('these/saisie-domaine-hal', ['these' => $these->getId()], [], true); ?>"
                    >
                        <span class="icon icon-plus"></span>
                        Saisir le(s) domaine(s)
                    </a>
                <?php } ?>
            </dd>

            <dt class="col-md-3">Date de 1ère<br>inscription</dt>
            <dd class="col-md-9"><?php echo $these->getDatePremiereInscriptionToString() ?: "(Non renseignée)" ?></dd>

            <dt class="col-md-3">Année universitaire<br>de 1ère inscription</dt>
            <dd class="col-md-9"><?php echo $these->getAnneeUniv1ereInscription() ?></dd>

            <dt class="col-md-3">Années universitaires<br>d'inscription</dt>
            <dd class="col-md-9"><?php echo $these->getAnneesUnivInscriptionToString('<br>') ?: "(Non renseignée)" ?></dd>

            <?php if ($these->getDateAbandon()): ?>
            <dt class="col-md-3">Date d'abandon</dt>
            <dd class="col-md-9"><?php echo $these->getDateAbandonToString() ?></dd>
            <?php endif ?>

            <?php if ($these->getDateTransfert()): ?>
            <dt class="col-md-3">Date de transfert
            <dd class="col-md-9"><?php echo $these->getDateTransfertToString() ?></dd>
            <?php endif ?>

            <?php if ($these->getSoutenanceAutorisee()): ?>
                <dt class="col-md-3">Soutenance autorisée</dt>
                <dd class="col-md-9"><?php echo $these->getSoutenanceAutorisee() === 'O' ? "Oui" : "Non" ?></dd>
            <?php endif ?>

            <?php if ($these->getDateSoutenance()): ?>
                <dt class="col-md-3">Date réelle de soutenance</dt>
                <dd class="col-md-9"><?php echo $these->getDateSoutenanceToString() ?></dd>
            <?php else: ?>
                <!--<dt>Date prévisionnelle de soutenance</dt>
                <dd><?php /*echo $these->getDatePrevisionSoutenanceToString() ?: "(Non renseignée)" */?></dd>-->
            <?php endif ?>

            <?php if ($these->getLibelleEtabCotutelle()): ?>
                <dt class="col-md-3">Cotutelle</dt>
                <dd class="col-md-9">En cotutelle avec <?php echo $these->getLibelleEtabCotutelle() ?>,
                    <?php echo $these->getLibellePaysCotutelle() ?></dd>
            <?php endif ?>

            <!------------------------------- Corrections attendues --------------------------------->
            <?php
            $titre = "Corrections attendues";
            $reponse = "Non.";
            $message = null;
            $class = null;

            $validationsDesCorrectionsEnAttente = [1]; //////////////////////

            if ($these->isCorrectionAutorisee()) {
                $dateButoirDepassee =
                    $these->isDateButoirDepotVersionCorrigeeDepassee($these->getDateSoutenance()) &&
                    ! empty($validationsDesCorrectionsEnAttente);

                if ($these->getCorrectionAutoriseeEstFacultative()) {
                    $class = "text-warning";
                    $reponse = "Oui, facultatives.";
                    $message = $dateButoirDepassee ?
                        "<strong>Trop tard, le délai pour corrections facultatives est écoulé : la version déposée avant soutenance constitue désormais la version de référence.</strong>" :
                        null;
                } elseif ($these->getCorrectionAutoriseeEstObligatoire()) {
                    $class = "text-danger";
                    $reponse = "Oui, obligatoires.";
                    $message = $dateButoirDepassee ?
                        "<strong>Trop tard, le délai pour corrections obligatoires est écoulé : ni l’attestation de réussite ni le diplôme ne peuvent désormais être délivrés.</strong>" :
                        null;
                }
                if (is_array($validationsDesCorrectionsEnAttente) && empty($validationsDesCorrectionsEnAttente)) {
                    $titre = "Corrections";
                    $message = sprintf("Les corrections %s ont été validées.", lcfirst($these->getCorrectionAutoriseeToString(true)));
                    $canEditForcageCorrectionAutorisee = false;
                }
            }
            ?>
            <dt class="col-md-3 <?php echo $class ?>"><?php echo $titre ?></dt>
            <dd class="col-md-9 <?php echo $class ?>">
                <p>
                    <?php echo $reponse ?>
                    <?php if ($canEditForcageCorrectionAutorisee): ?>
                        <?php if ($these->isCorrectionAutoriseeForcee()): ?>
                            <em>Cette valeur est forcée.</em>
                        <?php endif ?>
                        <a href="<?php echo $modifierCorrecAutorUrl ?>" class="btn btn-xs btn-info ajax-modal"
                           data-event="event-correction-autorisee-forcee-modified"
                           title="Forçage du témoin de corrections attendues"
                        >Forçage</a>
                    <?php endif ?>
                </p>
                <?php if ($these->isCorrectionAutorisee()): ?>
                    <?php if ($dateSoutenance = $these->getDateSoutenance()): ?>
                        <p>
                            Date butoir :
                            <?php if ($these->getDateButoirDepotVersionCorrigeeAvecSursis()): ?>
                                <?php echo $these->getDateButoirDepotVersionCorrigeeAvecSursisToString() ?> (sursis inclus)
                            <?php else: ?>
                                <abbr title="<?php echo $these->getDelaiDepotVersionCorrigeeToString() ?> après la date de soutenance">
                                    <?php echo $these->getDateButoirDepotVersionCorrigeeFromDateSoutenanceToString($dateSoutenance) ?>
                                </abbr>
                            <?php endif ?>
                            <?php if ($this->isAllowed($these, DepotPrivileges::THESE_CORREC_AUTORISEE_ACCORDER_SURSIS)): ?>
                                <a href="<?php echo $accorderSursisCorrecUrl ?>" class="btn btn-xs btn-info ajax-modal"
                                   data-event="event-sursis-correction-modified"
                                   title="Accorder un sursis"
                                >Accorder un sursis</a>
                            <?php endif ?>
                        </p>
                    <?php endif ?>
                <?php endif ?>
                <?php if ($message): ?>
                    <p>
                        <?php echo $message ?>
                    </p>
                <?php endif ?>
            </dd>

        </dl>
    </div>

</div>


<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });

    $(function () {
        var body = $("body");

        body.on("<?php echo $emailContactModifiedEvent ?>", function (event, data) {
            // L'email de contact vient d'être modifié.
            event.div.modal('hide'); // ferme la fenêtre modale
            window.location.reload();
        });
        body.on("<?php echo $emailContactConsentModifiedEvent ?>", function (event, data) {
            // Le consentement vient d'être modifié.
            event.div.modal('hide'); // ferme la fenêtre modale
        });
        body.on("event-correction-autorisee-forcee-modified", function (event) {
            event.div.modal('hide'); // ferme la fenêtre modale
            window.location.reload();
        });
        body.on("event-sursis-correction-modified", function (event) {
            event.div.modal('hide'); // ferme la fenêtre modale
            window.location.reload();
        });
    });
</script>