<?php

use Application\Constants;
use Application\Entity\Db\Utilisateur;
use Application\Entity\Db\Validation;
use Application\Filter\FinancementFormatter;
use Application\Provider\Privilege\UtilisateurPrivileges;
use Application\View\Renderer\PhpRenderer;
use Depot\Provider\Privilege\DepotPrivileges;
use Doctorant\Provider\Privilege\DoctorantPrivileges;
use Individu\Provider\Privilege\IndividuPrivileges;
use Individu\View\Helper\IndividuUsurpationHelper;
use Structure\Entity\Db\EtablissementRattachement;
use These\Controller\TheseController;
use These\Entity\Db\Acteur;
use These\Entity\Db\These;
use These\Filter\ActeursFormatter;
use These\Provider\Privilege\CoEncadrantPrivileges;

/**
 * @var PhpRenderer  $this
 * @var These        $these
 * @var string       $modifierEmailContactUrl
 * @var string       $modifierEmailContactConsentUrl
 * @var bool         $estDoctorant
 * @var string       $modifierCorrecAutorUrl
 * @var string       $accorderSursisCorrecUrl
 * @var string       $nextStepUrl
 * @var Validation[] $validationsDesCorrectionsEnAttente
 * @var Utilisateur[] $utilisateurs
 * @var EtablissementRattachement[] $rattachements
 *
 * @see TheseController::detailIdentiteAction()
 */

$canVoirEmailContact = $this->isAllowed($these, DoctorantPrivileges::DOCTORANT_AFFICHER_EMAIL_CONTACT);
$canEditEmailContact = $this->isAllowed($these, DoctorantPrivileges::DOCTORANT_MODIFIER_EMAIL_CONTACT);
$canEditEmailContactConsent = $this->isAllowed($these, DoctorantPrivileges::DOCTORANT_MODIFIER_EMAIL_CONTACT);
$emailContactModifiedEvent = 'email-contact-modified-event';
$emailContactConsentModifiedEvent = 'email-contact-consent-modified-event';
$canCreate = $this->isAllowed(UtilisateurPrivileges::getResourceId(UtilisateurPrivileges::UTILISATEUR_CREATE_FROM_INDIVIDU));

$canCoEncadrantAfficher = $this->isAllowed(CoEncadrantPrivileges::getResourceId(CoEncadrantPrivileges::COENCADRANT_AFFICHER));
$canCoEncadrantGerer    = $this->isAllowed(CoEncadrantPrivileges::getResourceId(CoEncadrantPrivileges::COENCADRANT_GERER));


$canEditForcageCorrectionAutorisee = $this->isAllowed($these, DepotPrivileges::THESE_SAISIE_CORREC_AUTORISEE_FORCEE);

$financementFormatter = $this->financementFormatter();
$financementFormatter->setSortBy(FinancementFormatter::SORT_BY_DATE);
$financementFormatter->setDisplayAs(FinancementFormatter::DISPLAY_AS_HTML_LINES);
?>

<?php $this->headTitle($this->translate("Thèse"))->prepend($these->getDoctorant()->getNomUsuel()) ?>

<?php echo $this->alertes()
    ->withCode(Constants::ALERTE_FERMETURE_ESTIVALE)
    ->withMatchingPlanning()
    ->renderAsBootstrapToasts() ?>

<h1 class="page-header">
    <?php echo $this->translate("Thèse"); ?>
    <small><?php echo $this->partial('these/these/partial/titre') ?></small>
</h1>

<div class="box card">

    <div class="card-header bg-dark text-white">
        <h2 class="first">
            <?php echo $this->translate("Fiche"); ?>
        </h2>
    </div>

    <div class="card-body">

        <div id="photo-div" class="float-end">
            <!--            <div class="photo-placeholder loading"-->
            <!--                 data-src="-->
            <?php //echo $this->url('leocarte/photo', ['id' => $these->getDoctorant()->getSourceCodeSansPrefix()]) ?><!--"></div>-->
        </div>

        <dl class="row">

            <dt class="col-md-4">
                <?php echo $this->translate("Doctorant"); ?>
            </dt>
            <dd class="col-md-8">
                <?php echo sprintf("%s (%s)",
                    $these->getDoctorant()->getIndividu()->getNomComplet(true, true, true),
                    $these->getDoctorant()->getIndividu()->getDateNaissanceToString());
                ?>
                <?php
                $canVisualiserIndividu = $this->isAllowed($these->getDoctorant()->getIndividu(), IndividuPrivileges::INDIVIDU_CONSULTER);
                if ($canVisualiserIndividu) {
                echo " <a href='".$this->url('individu/voir', ['individu' => $these->getDoctorant()->getIndividu()->getId()], [], true) ."'>";
                echo "<span class='icon icon-voir' title='Accéder à la fiche détaillée de cet individu'></span></a>";
                }
                ?>
                <?php
                // bouton d'usurpation d'identité
                $individuUsurpationHelper = $this->plugin('individuUsurpation'); /* @var $individuUsurpationHelper IndividuUsurpationHelper */
                $individuUsurpationHelper->setIndividu($these->getDoctorant()->getIndividu());
                echo $individuUsurpationHelper();
                ?>
                <br>

                <strong>
                    <?php echo $this->translate("Nationalité :"); ?>
                </strong>
                <?php echo $these->getDoctorant()->getNationalite() ?> <br>

                <strong>
                    <?php echo $this->translate("N° étudiant :"); ?>
                </strong>
                <?php echo $these->getDoctorant()->getNumeroEtudiant() ?> <br>

                <strong>
                    <?php echo $this->translate("Adresse institutionnelle :"); ?>
                </strong>
                <?php if ($email = $these->getDoctorant()->getIndividu()->getEmailPro()): ?>
                    <a href="mailto: <?php echo $email ?>"><?php echo $email ?></a>
                <?php else: ?>
                    <?php echo $this->translate("(Inconnu)"); ?>
                <?php endif ?>

                <?php if ($canVoirEmailContact) : ?>
                    <br>
                    <strong>
                        <?php echo $this->translate("Adresse de contact :"); ?>
                    </strong>
                    <?php if ($mailContact = $these->getDoctorant()->getIndividu()->getEmailContact()): ?>
                        <a href="mailto: <?php echo $mailContact = $these->getDoctorant()->getIndividu()->getEmailContact() ?>"><?php echo $mailContact ?></a>
                    <?php else: ?>
                        (Non renseignée)
                    <?php endif; ?>
                    <?php if ($canEditEmailContact): ?>
                        <a href="<?php echo $modifierEmailContactUrl ?>"
                           title="Modifer l'adresse de contact"
                           data-event="<?php echo $emailContactModifiedEvent ?>"
                           class="btn btn-secondary btn-sm ajax-modal">
                            <?php echo $this->translate(($mailContact ? "Modifier" : "Renseigner") .  " l'adresse de contact"); ?>
                        </a>
                    <?php endif ?>
                    <?php if ($canEditEmailContactConsent): ?>
                        <a href="<?php echo $modifierEmailContactConsentUrl ?>"
                           title="Votre consentement à utiliser l'adresse de contact"
                           data-event="<?php echo $emailContactConsentModifiedEvent ?>"
                           class="btn btn-secondary btn-sm ajax-modal">
                            <?php echo $this->translate("Consentement"); ?>
                        </a>
                    <?php endif ?>
                <?php endif; ?>
            </dd>

            <?php
            // Affichage des acteurs de la these
            $acteursFormatter = new ActeursFormatter();
            $acteursFormatter->paramDisplay(["role" => true, "complement" => true, "qualite" => true, "etablissement" => true]);
            $acteursFormatter->asArray();
            $acteurs = $these->getActeursSorted();
            $results = $acteursFormatter->doFormat($acteurs->toArray());
            $previous = "";
            foreach ($results as $result) {
                /** @var Acteur $acteur */
                $acteur = $result["acteur"];
                if ($previous != $result["role"]) {
                    echo "</dd>";
                    echo '<dt class="col-md-4">' . $result["role"] . "</dt>";
                    echo '<dd class="col-md-8">';
                    $previous = $result["role"];
                }
                $ligne = [];
                if (isset($result["nom"])) {
                    $ligne[] = $result["nom"];
                }
                if (isset($result["complement"])) {
                    $ligne[] = "<strong>" . $result["complement"] . "</strong>";
                }
                if (isset($result["qualite"]) && trim($result["qualite"]) != "") {
                    $ligne[] = $result["qualite"];
                }
                if (isset($result["etablissement"]) && trim($result["etablissement"]) != "") {
                    $ligne[] = $result["etablissement"];
                }

                $ligne = implode(" &ndash; ", $ligne);
                echo $ligne;

                $canVisualiserIndividu = $this->isAllowed($acteur->getIndividu(), IndividuPrivileges::INDIVIDU_CONSULTER);
                if ($canVisualiserIndividu) {
                    echo " <a href='".$this->url('individu/voir', ['individu' => $acteur->getIndividu()->getId()], [], true) ."'>";
                    echo "<span class='icon icon-voir' title='Accéder à la fiche détaillée de cet individu'></span></a>";
                }

                if ($acteur->getRole()->estUsurpable() && ! isset($result['alerte-supann-id'])) {
                    // bouton d'usurpation d'identité
                    $individuUsurpationHelper = $this->plugin('individuUsurpation');
                    /* @var $individuUsurpationHelper IndividuUsurpationHelper */
                    $individuUsurpationHelper->setIndividu($acteur->getIndividu());
                    echo $individuUsurpationHelper();
                }

                echo " &nbsp;";

                if ($canCoEncadrantAfficher AND $acteur->estCoEncadrant()) {
                    echo " <a href='".$this->url('co-encadrant/historique', ['co-encadrant' => $acteur->getId()], [], true) ."'>";
                    echo "<span class='icon icon-voir' title='Voir historique de co-encadrement'></span></a>";
                }
                if ($canCoEncadrantGerer AND $acteur->estCoEncadrant()) {
                    echo " <a href='".$this->url('co-encadrant/retirer-co-encadrant', ['these' => $these->getId(), 'co-encadrant' => $acteur->getId()], [], true) ."'>";
                    echo "<span class='icon icon-delete iconly' title='Retirer le co-encadrant'></span></a>";
                }

                echo "<br/>";
            }
            ?>

            <?php if ($canCoEncadrantGerer) : ?>
                <dt class="col-md-4"></dt>
                <dd class="col-md-8">
                    <a  <?php /**  @see CoEncadrantController::ajouterCoEncadrantAction() */ ?>
                        class="btn btn-primary ajax-modal" data-event="modification"
                        href="<?php echo $this->url('co-encadrant/ajouter-co-encadrant', ['these' => $these->getId()], [], true); ?>"
                    >
                        <span class="icon icon-plus"></span>
                        Ajouter un co-encadrant
                    </a>
                </dd>
            <?php endif; ?>
            <dt class="col-md-4">
                <?php echo $this->translate("Établissement <br/> d'inscription"); ?>
            </dt>
            <dd class="col-md-8">
                <?php
                if ($these->getEtablissement()) {
                    echo /*$these->getEtablissement()->getCode() . " - " .*/
                    $these->getEtablissement()->getStructure()->getLibelle();
                } else {
                    echo "<div class='alert alert-sm alert-warning'>";
                    echo "<span class='fas fa-exclamation-triangle'></span> Aucun établissement n'est renseignée.";
                    echo "</div>";
                }
                ?>
            </dd>

            <dt class="col-md-4">
                <?php echo $this->translate("Titre d'accès<br/>à l'inscr. en thèse") ?>
            </dt>
            <dd class="col-md-8">
                <?php
                echo ($titreAcces = $these->getTitreAcces()) ?: "(Non renseigné)";
                ?>
            </dd>

            <dt class="col-md-4">
                <?php echo $this->translate("Unité de recherche"); ?>
            </dt>
            <dd class="col-md-8">
                <?php
                if ($these->getUniteRecherche()) {
                    echo $these->getUniteRecherche();
                } elseif ($these->getCodeUniteRecherche() && $these->getLibelleUniteRecherche()) {
                    echo $these->getCodeUniteRecherche() . " - " . $these->getLibelleUniteRecherche();
                    echo "<div class='alert alert-sm alert-warning'>";
                    echo "<span class='fas fa-exclamation-triangle'></span> Utilisation du champs libre (unité de recherche mal renseignée).";
                    echo "</div>";
                } else {
                    echo "<div class='alert alert-sm alert-warning'>";
                    echo "<span class='fas fa-exclamation-triangle'></span> Aucune unité de recherche n'est renseignée";
                    echo "</div>";
                }
                ?>

            </dd>

            <dt class="col-md-4">
                Établissements de <br/>
                rattachement de <br/>
                l'unité de recherche
            </dt>
            <dd class="col-md-8">
                <?php
                if (empty($rattachements)) {
                    echo "(Aucun établissement de rattachement renseigné)";
                } else {
                    foreach ($rattachements as $rattachement) {
                        echo $rattachement->getEtablissement()->getStructure()->getLibelle();
                        echo "<br/>";
                    }
                }
                ?>
            </dd>

            <dt class="col-md-4">
                <?php echo $this->translate("École doctorale"); ?>
            </dt>
            <dd class="col-md-8">
                <?php if ($these->getEcoleDoctorale()) {
                    echo $these->getEcoleDoctorale();
                } else {
                    echo "<div class='alert alert-sm alert-warning'>";
                    echo "<span class='fas fa-exclamation-triangle'></span> Aucune école doctorale n'est renseignée.";
                    echo "</div>";
                }
                ?>
            </dd>

            <dt class="col-md-4">
                Financement(s)
            </dt>
            <dd class="col-md-8">
                <?php if ($these->getFinancements()->isEmpty()): ?>
                    (Non renseigné)
                <?php else: ?>
                    <?php echo $financementFormatter->format($these->getFinancements()->toArray()); ?>
                <?php endif ?>
            </dd>

            <dt class="col-md-4">
                <?php echo $this->translate("Titre"); ?>
            </dt>
            <dd class="col-md-8">
                <?php echo $these->getTitre() ?>
            </dd>

            <dt class="col-md-4">
                <?php echo $this->translate("Confidentialité"); ?>
            </dt>
            <?php if ($these->etaitConfidentielle()): ?>
                <dd class="col-md-8">Confidentielle, jusqu'au <?php echo $these->getDateFinConfidentialiteToString() ?></dd>
            <?php elseif ($these->estConfidentielle()): ?>
                <dd class="col-md-8 text-danger">Confidentielle,
                    jusqu'au <?php echo $these->getDateFinConfidentialiteToString() ?></dd>
            <?php else: ?>
                <dd class="col-md-8">Non confidentielle</dd>
            <?php endif ?>

            <dt class="col-md-4">État</dt>
            <dd class="col-md-8">
                <span class="badge bg-secondary"><?php echo $these->getEtatTheseToString() ?></span>
            </dd>

            <?php if ($resultat = $these->getResultatToString(false)): ?>
                <dt class="col-md-4">Résultat</dt>
                <dd class="col-md-8">
                    <?php echo $resultat ?>
                </dd>
            <?php endif ?>

            <dt class="col-md-4">Discipline</dt>
            <dd class="col-md-8"><?php echo $these->getLibelleDiscipline() ?></dd>

            <dt class="col-md-4">Date de 1ère<br>inscription</dt>
            <dd class="col-md-8"><?php echo $these->getDatePremiereInscriptionToString() ?: "(Non renseignée)" ?></dd>

            <dt class="col-md-4">Année universitaire<br>de 1ère inscription</dt>
            <dd class="col-md-8"><?php echo $these->getAnneeUniv1ereInscription() ?></dd>

            <dt class="col-md-4">Années universitaires<br>d'inscription</dt>
            <dd class="col-md-8"><?php echo $these->getAnneesUnivInscriptionToString('<br>') ?: "(Non renseignée)" ?></dd>

            <?php if ($these->getDateAbandon()): ?>
            <dt class="col-md-4">Date d'abandon</dt>
            <dd class="col-md-8"><?php echo $these->getDateAbandonToString() ?></dd>
            <?php endif ?>

            <?php if ($these->getDateTransfert()): ?>
            <dt class="col-md-4">Date de transfert
            <dd class="col-md-8"><?php echo $these->getDateTransfertToString() ?></dd>
            <?php endif ?>

            <?php if ($these->getSoutenanceAutorisee()): ?>
                <dt class="col-md-4">Soutenance autorisée</dt>
                <dd class="col-md-8"><?php echo $these->getSoutenanceAutorisee() === 'O' ? "Oui" : "Non" ?></dd>
            <?php endif ?>

            <?php if ($these->getDateSoutenance()): ?>
                <dt class="col-md-4">Date réelle<br>de soutenance</dt>
                <dd class="col-md-8"><?php echo $these->getDateSoutenanceToString() ?></dd>
            <?php else: ?>
                <!--<dt>Date prévisionnelle<br>de soutenance</dt>
                <dd><?php /*echo $these->getDatePrevisionSoutenanceToString() ?: "(Non renseignée)" */?></dd>-->
            <?php endif ?>

            <?php if ($these->getLibelleEtabCotutelle()): ?>
                <dt class="col-md-4">Cotutelle</dt>
                <dd class="col-md-8">En cotutelle avec <?php echo $these->getLibelleEtabCotutelle() ?>,
                    <?php echo $these->getLibellePaysCotutelle() ?></dd>
            <?php endif ?>

            <!------------------------------- Corrections attendues --------------------------------->
            <?php
            $titre = "Corrections attendues";
            $reponse = "Non.";
            $message = null;
            $class = null;

            $validationsDesCorrectionsEnAttente = [1]; //////////////////////

            if ($these->isCorrectionAutorisee()) {
                $dateButoirDepassee =
                    $these->isDateButoirDepotVersionCorrigeeDepassee($these->getDateSoutenance()) &&
                    ! empty($validationsDesCorrectionsEnAttente);

                if ($these->getCorrectionAutoriseeEstFacultative()) {
                    $class = "text-warning";
                    $reponse = "Oui, facultatives.";
                    $message = $dateButoirDepassee ?
                        "<strong>Trop tard, le délai pour corrections facultatives est écoulé : la version déposée avant soutenance constitue désormais la version de référence.</strong>" :
                        null;
                } elseif ($these->getCorrectionAutoriseeEstObligatoire()) {
                    $class = "text-danger";
                    $reponse = "Oui, obligatoires.";
                    $message = $dateButoirDepassee ?
                        "<strong>Trop tard, le délai pour corrections obligatoires est écoulé : ni l’attestation de réussite ni le diplôme ne peuvent désormais être délivrés.</strong>" :
                        null;
                }
                if (is_array($validationsDesCorrectionsEnAttente) && empty($validationsDesCorrectionsEnAttente)) {
                    $titre = "Corrections";
                    $message = sprintf("Les corrections %s ont été validées.", lcfirst($these->getCorrectionAutoriseeToString(true)));
                    $canEditForcageCorrectionAutorisee = false;
                }
            }
            ?>
            <dt class="col-md-4 <?php echo $class ?>"><?php echo $titre ?></dt>
            <dd class="col-md-8 <?php echo $class ?>">
                <p>
                    <?php echo $reponse ?>
                    <?php if ($canEditForcageCorrectionAutorisee): ?>
                        <?php if ($these->isCorrectionAutoriseeForcee()): ?>
                            <em>Cette valeur est forcée.</em>
                        <?php endif ?>
                        <a href="<?php echo $modifierCorrecAutorUrl ?>" class="btn btn-xs btn-info ajax-modal"
                           data-event="event-correction-autorisee-forcee-modified"
                           title="Forçage du témoin de corrections attendues"
                        >Forçage</a>
                    <?php endif ?>
                </p>
                <?php if ($these->isCorrectionAutorisee()): ?>
                    <?php if ($dateSoutenance = $these->getDateSoutenance()): ?>
                        <p>
                            Date butoir :
                            <?php if ($these->getDateButoirDepotVersionCorrigeeAvecSursis()): ?>
                                <?php echo $these->getDateButoirDepotVersionCorrigeeAvecSursisToString() ?> (sursis inclus)
                            <?php else: ?>
                                <abbr title="<?php echo $these->getDelaiDepotVersionCorrigeeToString() ?> après la date de soutenance">
                                    <?php echo $these->getDateButoirDepotVersionCorrigeeFromDateSoutenanceToString($dateSoutenance) ?>
                                </abbr>
                            <?php endif ?>
                            <?php if ($this->isAllowed($these, DepotPrivileges::THESE_CORREC_AUTORISEE_ACCORDER_SURSIS)): ?>
                                <a href="<?php echo $accorderSursisCorrecUrl ?>" class="btn btn-xs btn-info ajax-modal"
                                   data-event="event-sursis-correction-modified"
                                   title="Accorder un sursis"
                                >Accorder un sursis</a>
                            <?php endif ?>
                        </p>
                    <?php endif ?>
                <?php endif ?>
                <?php if ($message): ?>
                    <p>
                        <?php echo $message ?>
                    </p>
                <?php endif ?>
            </dd>

        </dl>
    </div>

</div>


<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });

    $(function () {
        var body = $("body");

        body.on("<?php echo $emailContactModifiedEvent ?>", function (event, data) {
            // L'email de contact vient d'être modifié.
            event.div.modal('hide'); // ferme la fenêtre modale
            window.location.reload();
        });
        body.on("<?php echo $emailContactConsentModifiedEvent ?>", function (event, data) {
            // Le consentement vient d'être modifié.
            event.div.modal('hide'); // ferme la fenêtre modale
        });
        body.on("event-correction-autorisee-forcee-modified", function (event) {
            event.div.modal('hide'); // ferme la fenêtre modale
            window.location.reload();
        });
        body.on("event-sursis-correction-modified", function (event) {
            event.div.modal('hide'); // ferme la fenêtre modale
            window.location.reload();
        });
    });
</script>