<?php

use Application\Entity\Db\Utilisateur;
use Application\Entity\Db\Validation;
use Application\Filter\FinancementFormatter;
use Application\Provider\Privilege\UtilisateurPrivileges;
use Application\View\Renderer\PhpRenderer;
use Depot\Provider\Privilege\DepotPrivileges;
use Doctorant\Provider\Privilege\DoctorantPrivileges;
use Doctorant\Provider\Privilege\MissionEnseignementPrivileges;
use Structure\Entity\Db\EtablissementRattachement;
use These\Controller\TheseController;
use These\Entity\Db\These;
use These\Filter\ActeursFormatter;
use These\Provider\Privilege\CoEncadrantPrivileges;
use These\Provider\Privilege\ThesePrivileges;

/**
 * @var PhpRenderer  $this
 * @var These        $these
 * @var string       $modifierEmailContactUrl
 * @var string       $modifierEmailContactConsentUrl
 * @var bool         $estDoctorant
 * @var string       $modifierCorrecAutorUrl
 * @var string       $accorderSursisCorrecUrl
 * @var string       $nextStepUrl
 * @var Validation[] $validationsDesCorrectionsEnAttente
 * @var Utilisateur[] $utilisateurs
 * @var EtablissementRattachement[] $rattachements
 *
 * @see TheseController::detailIdentiteAction()
 */

$canVoirEmailContact = $this->isAllowed($these, DoctorantPrivileges::DOCTORANT_AFFICHER_EMAIL_CONTACT);
$canEditEmailContact = $this->isAllowed($these, DoctorantPrivileges::DOCTORANT_MODIFIER_EMAIL_CONTACT);
$canEditEmailContactConsent = $this->isAllowed($these, DoctorantPrivileges::DOCTORANT_MODIFIER_EMAIL_CONTACT);
$emailContactModifiedEvent = 'email-contact-modified-event';
$emailContactConsentModifiedEvent = 'email-contact-consent-modified-event';
$canCreate = $this->isAllowed(UtilisateurPrivileges::getResourceId(UtilisateurPrivileges::UTILISATEUR_CREATE_FROM_INDIVIDU));

$canCoEncadrantAfficher = $this->isAllowed(CoEncadrantPrivileges::getResourceId(CoEncadrantPrivileges::COENCADRANT_AFFICHER));
$canCoEncadrantGerer    = $this->isAllowed(CoEncadrantPrivileges::getResourceId(CoEncadrantPrivileges::COENCADRANT_GERER));

$canMissionAfficher = $this->isAllowed(MissionEnseignementPrivileges::getResourceId(MissionEnseignementPrivileges::MISSION_ENSEIGNEMENT_VISUALISER));
$canMissionGerer    = $this->isAllowed(MissionEnseignementPrivileges::getResourceId(MissionEnseignementPrivileges::MISSION_ENSEIGNEMENT_MODIFIER));

$canDomaineHalModifier = $this->isAllowed($these,ThesePrivileges::THESE_MODIFICATION_DOMAINES_HAL_THESE);

$canEditForcageCorrectionAutorisee = $this->isAllowed($these, DepotPrivileges::THESE_SAISIE_CORREC_AUTORISEE_FORCEE);

$financementFormatter = $this->financementFormatter();
$financementFormatter->setSortBy(FinancementFormatter::SORT_BY_DATE);
$financementFormatter->setDisplayAs(FinancementFormatter::DISPLAY_AS_HTML_LINES);

$acteursFormatter = new ActeursFormatter();
$acteursFormatter->paramDisplay(["role" => true, "complement" => true, "qualite" => true, "etablissement" => true, "uniteRecherche" => true]);
$acteursFormatter->asArray(true);
$acteursFormatted = $acteursFormatter->doFormat($these->getActeursSorted()->toArray());

$hasCoEncadrant = false;

$modifierGeneralitesEvent = 'event-modifier-generalites';
$modifierStructuresEvent = 'event-modifier-structures';
$modifierEncadrementEvent = 'event-modifier-encadrement';

?>

<?php $this->headTitle($this->translate("Thèse"))->prepend($these->getDoctorant()->getIndividu()->getNomUsuel()) ?>

<?php echo $this->alertes()
    ->addAlertesFromDatabase()
    ->addAlertesFromFlashMessenger()
    ->renderAsBootstrapToasts() ?>

<h1 class="page-header">
    <?php echo $this->translate("Thèse"); ?>
    <small><?php echo $this->partial('these/these/partial/titre') ?></small>
</h1>

<div class="box card">
    <div class="card-header bg-dark text-white">
        <h2 class="first">
            <?php echo $this->translate("Généralités"); ?>
        </h2>
    </div>
    <div class="card-body">
        <?php if ($canEditGeneralites = true/*$this->isAllowed($these, ThesePrivileges::THESE_SAISIE_XXX)*/): ?>
            <a href="<?php echo $this->url('these/modifier', ['these' => $these->getId()], [], true). '#informations' ?>"
               data-event="<?php echo $modifierGeneralitesEvent ?>"
               class="btn btn-outline-primary float-end ajax-modal">
                <span class="icon icon-edit"></span>
                <?php echo $this->translate("Modifier les généralités"); ?>
            </a>
        <?php endif ?>
        <?php echo $this->partial('these/these/partial/generalites') ?>
    </div>
</div>

<div class="box card">
    <div class="card-header bg-dark text-white">
        <h2 class="first">
            <?php echo $this->translate("Structures"); ?>
        </h2>
    </div>
    <div class="card-body">
        <?php if ($canEditStructures = true/*$this->isAllowed($these, ThesePrivileges::THESE_SAISIE_XXX)*/): ?>
            <a href="<?php echo $this->url('these/modifier', ['these' => $these->getId()], [], true). '#structures' ?>"
               data-event="<?php echo $modifierStructuresEvent ?>"
               class="btn btn-outline-primary float-end ajax-modal">
                <span class="icon icon-edit"></span>
                <?php echo $this->translate("Modifier les structures"); ?>
            </a>
        <?php endif ?>
        <?php echo $this->partial('these/these/partial/structures') ?>
    </div>
</div>

<div class="box card">
    <div class="card-header bg-dark text-white">
        <h2 class="first">
            <?php echo $this->translate("Direction"); ?>
        </h2>
    </div>
    <div class="card-body">
        <?php echo $this->partial('these/these/partial/direction') ?>
    </div>
</div>

<div class="box card">
    <div class="card-header bg-dark text-white">
        <h2 class="first">
            <?php echo $this->translate("Encadrement"); ?>
        </h2>
    </div>
    <div class="card-body">
        <?php echo $this->partial('these/these/partial/encadrement') ?>
    </div>
</div>

<div class="box card">

    <div class="card-header bg-dark text-white">
        <h2 class="first">
            <?php echo $this->translate("Fiche"); ?>
        </h2>
    </div>

    <div class="card-body">

        <div id="photo-div" class="float-end">
            <!--            <div class="photo-placeholder loading"-->
            <!--                 data-src="-->
            <?php //echo $this->url('leocarte/photo', ['id' => $these->getDoctorant()->getSourceCodeSansPrefix()]) ?><!--"></div>-->
        </div>

        <dl class="row these">
            <dt class="col-md-3">
                <?php echo $this->translate("Titre d'accès à l'inscr. en thèse") ?>
            </dt>
            <dd class="col-md-9">
                <?php
                echo ($titreAcces = $these->getTitreAcces()) ?: "(Non renseigné)";
                ?>
            </dd>

            <dt class="col-md-3">
                Financement·s
            </dt>
            <dd class="col-md-9">
                <?php if ($these->getFinancements()->isEmpty()): ?>
                    (Non renseigné)
                <?php else: ?>
                    <?php echo $financementFormatter->format($these->getFinancements()->toArray()); ?>
                <?php endif ?>
            </dd>

            <?php if ($canMissionAfficher) : ?>
                <dt class="col-md-3">
                    Mission·s d'enseignement
                </dt>
                <dd class="col-md-9">
                <?php if ($canMissionGerer) : ?>
                    <a  <?php /**  @see \Doctorant\Controller\MissionEnseignementController::ajouterAction() */ ?>
                            class="icon icon-plus iconly ajax-modal float-end" data-event="modification"
                            href="<?php echo $this->url('doctorant/mission-enseignement/ajouter', ['doctorant' => $these->getDoctorant()->getId()], [], true); ?>"
                            title="Ajouter une mission d'enseignement"></a>
                <?php endif; ?>
                <?php if (empty($missions)) : ?>
                    (Aucune mission renseignée)
                <?php else: ?>
                    <ul>
                    <?php foreach ($missions as $mission) : ?>
                        <li>Mission d'enseignement pour l'année <?php echo $mission->getAnneeUniversitaire(); ?>/<?php echo ($mission->getAnneeUniversitaire()+1); ?>
                        <?php if ($canMissionGerer) : ?>
                            <a  <?php /**  @see \Doctorant\Controller\MissionEnseignementController::retirerAction() */ ?>
                                    class="ajax-modal" data-event="modification"
                                    data-toggle="confirmationx" data-message="Êtes-vous sûr·e de vouloir retirer cette mission d'enseignement ?"
                                    href="<?php echo $this->url('doctorant/mission-enseignement/retirer', ['mission' => $mission->getId(), 'doctorant' => $these->getDoctorant()->getId()], [], true); ?>"
                            ><span class="icon icon-supprimer"></span></a>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </dd>
            <?php endif; ?>

            <dt class="col-md-3">
                <?php echo $this->translate("Confidentialité"); ?>
            </dt>
            <?php if ($these->etaitConfidentielle()): ?>
                <dd class="col-md-9">Confidentielle, jusqu'au <?php echo $these->getDateFinConfidentialiteToString() ?></dd>
            <?php elseif ($these->estConfidentielle()): ?>
                <dd class="col-md-9 text-danger">Confidentielle,
                    jusqu'au <?php echo $these->getDateFinConfidentialiteToString() ?></dd>
            <?php else: ?>
                <dd class="col-md-9">Non confidentielle</dd>
            <?php endif ?>

            <dt class="col-md-3">État</dt>
            <dd class="col-md-9">
                <span class="badge bg-secondary"><?php echo $these->getEtatTheseToString() ?></span>
            </dd>

            <?php if ($resultat = $these->getResultatToString()): ?>
                <dt class="col-md-3">Résultat</dt>
                <dd class="col-md-9">
                    <?php echo $resultat ?>
                </dd>
            <?php endif ?>

            <dt class="col-md-3">Date de 1ère<br>inscription</dt>
            <dd class="col-md-9"><?php echo $these->getDatePremiereInscriptionToString() ?: "(Non renseignée)" ?></dd>

            <dt class="col-md-3">Année universitaire<br>de 1ère inscription</dt>
            <dd class="col-md-9"><?php echo $these->getAnneeUniv1ereInscription() ?></dd>

            <dt class="col-md-3">Années universitaires<br>d'inscription</dt>
            <dd class="col-md-9"><?php echo $these->getAnneesUnivInscriptionToString('<br>') ?: "(Non renseignée)" ?></dd>

            <?php if ($these->getDateAbandon()): ?>
            <dt class="col-md-3">Date d'abandon</dt>
            <dd class="col-md-9"><?php echo $these->getDateAbandonToString() ?></dd>
            <?php endif ?>

            <?php if ($these->getDateTransfert()): ?>
            <dt class="col-md-3">Date de transfert
            <dd class="col-md-9"><?php echo $these->getDateTransfertToString() ?></dd>
            <?php endif ?>

            <?php if ($these->getSoutenanceAutorisee()): ?>
                <dt class="col-md-3">Soutenance autorisée</dt>
                <dd class="col-md-9"><?php echo $these->getSoutenanceAutorisee() === 'O' ? "Oui" : "Non" ?></dd>
            <?php endif ?>

            <?php if ($these->getDateSoutenance()): ?>
                <dt class="col-md-3">Date réelle de soutenance</dt>
                <dd class="col-md-9"><?php echo $these->getDateSoutenanceToString() ?></dd>
            <?php else: ?>
                <!--<dt>Date prévisionnelle de soutenance</dt>
                <dd><?php /*echo $these->getDatePrevisionSoutenanceToString() ?: "(Non renseignée)" */?></dd>-->
            <?php endif ?>

            <?php if ($these->getLibelleEtabCotutelle()): ?>
                <dt class="col-md-3">Cotutelle</dt>
                <dd class="col-md-9">En cotutelle avec <?php echo $these->getLibelleEtabCotutelle() ?>,
                    <?php echo $these->getLibellePaysCotutelle() ?></dd>
            <?php endif ?>

            <!------------------------------- Corrections attendues --------------------------------->
            <?php
            $titre = "Corrections attendues";
            $reponse = "Non.";
            $message = null;
            $class = null;

            $validationsDesCorrectionsEnAttente = [1]; //////////////////////

            if ($these->isCorrectionAutorisee()) {
                $dateButoirDepassee =
                    $these->isDateButoirDepotVersionCorrigeeDepassee($these->getDateSoutenance()) &&
                    ! empty($validationsDesCorrectionsEnAttente);

                if ($these->getCorrectionAutoriseeEstFacultative()) {
                    $class = "text-warning";
                    $reponse = "Oui, facultatives.";
                    $message = $dateButoirDepassee ?
                        "<strong>Trop tard, le délai pour corrections facultatives est écoulé : la version déposée avant soutenance constitue désormais la version de référence.</strong>" :
                        null;
                } elseif ($these->getCorrectionAutoriseeEstObligatoire()) {
                    $class = "text-danger";
                    $reponse = "Oui, obligatoires.";
                    $message = $dateButoirDepassee ?
                        "<strong>Trop tard, le délai pour corrections obligatoires est écoulé : ni l’attestation de réussite ni le diplôme ne peuvent désormais être délivrés.</strong>" :
                        null;
                }
                if (is_array($validationsDesCorrectionsEnAttente) && empty($validationsDesCorrectionsEnAttente)) {
                    $titre = "Corrections";
                    $message = sprintf("Les corrections %s ont été validées.", lcfirst($these->getCorrectionAutoriseeToString(true)));
                    $canEditForcageCorrectionAutorisee = false;
                }
            }
            ?>
            <dt class="col-md-3 <?php echo $class ?>"><?php echo $titre ?></dt>
            <dd class="col-md-9 <?php echo $class ?>">
                <p>
                    <?php echo $reponse ?>
                    <?php if ($canEditForcageCorrectionAutorisee): ?>
                        <?php if ($these->isCorrectionAutoriseeForcee()): ?>
                            <em>Cette valeur est forcée.</em>
                        <?php endif ?>
                        <a href="<?php echo $modifierCorrecAutorUrl ?>" class="btn btn-xs btn-info ajax-modal"
                           data-event="event-correction-autorisee-forcee-modified"
                           title="Forçage du témoin de corrections attendues"
                        >Forçage</a>
                    <?php endif ?>
                </p>
                <?php if ($these->isCorrectionAutorisee()): ?>
                    <?php if ($dateSoutenance = $these->getDateSoutenance()): ?>
                        <p>
                            Date butoir :
                            <?php if ($these->getDateButoirDepotVersionCorrigeeAvecSursis()): ?>
                                <?php echo $these->getDateButoirDepotVersionCorrigeeAvecSursisToString() ?> (sursis inclus)
                            <?php else: ?>
                                <abbr title="<?php echo $these->getDelaiDepotVersionCorrigeeToString() ?> après la date de soutenance">
                                    <?php echo $these->getDateButoirDepotVersionCorrigeeFromDateSoutenanceToString($dateSoutenance) ?>
                                </abbr>
                            <?php endif ?>
                            <?php if ($this->isAllowed($these, DepotPrivileges::THESE_CORREC_AUTORISEE_ACCORDER_SURSIS)): ?>
                                <a href="<?php echo $accorderSursisCorrecUrl ?>" class="btn btn-xs btn-info ajax-modal"
                                   data-event="event-sursis-correction-modified"
                                   title="Accorder un sursis"
                                >Accorder un sursis</a>
                            <?php endif ?>
                        </p>
                    <?php endif ?>
                <?php endif ?>
                <?php if ($message): ?>
                    <p>
                        <?php echo $message ?>
                    </p>
                <?php endif ?>
            </dd>

        </dl>
    </div>

</div>


<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });

    $(function () {
        var body = $("body");

        body.on("<?php echo $emailContactModifiedEvent ?>", function (event) {
            // L'email de contact vient d'être modifié.
            event.div.modal('hide'); // ferme la fenêtre modale
            window.location.reload();
        });
        body.on("<?php echo $emailContactConsentModifiedEvent ?>", function (event) {
            // Le consentement vient d'être modifié.
            event.div.modal('hide'); // ferme la fenêtre modale
        });
        body.on("event-correction-autorisee-forcee-modified", function (event) {
            event.div.modal('hide'); // ferme la fenêtre modale
            window.location.reload();
        });
        body.on("event-sursis-correction-modified", function (event) {
            event.div.modal('hide'); // ferme la fenêtre modale
            window.location.reload();
        });
    });
</script>