<?php

use These\Entity\Db\Attestation;
use These\Entity\Db\These;
use These\Form\Attestation\AttestationTheseForm;
use These\Provider\Privilege\ThesePrivileges;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer          $this
 * @var These                $these
 * @var Attestation          $attestation
 * @var \These\Form\Attestation\AttestationTheseForm $form
 * @var string               $modifierAttestationUrl
 *
 * @see TheseController::modifierCorrectionAutoriseeForceeAction()
 */

$canEdit = $this->isAllowed($these, ThesePrivileges::THESE_SAISIE_CORREC_AUTORISEE_FORCEE);
$form->prepare();
?>

<p class="lead">
    <?php echo $form->getLabel() ?>
</p>
<p>
    Que voulez-vous faire ?
</p>
<?php echo $this->form()->openTag($form) ?>
<?php echo $this->formControlGroup()->render($form->get('forcage')) ?>
<?php echo $this->formElement($form->get('submit')->setAttribute('class', 'btn btn-primary')) ?>
<?php echo $this->form()->closeTag() ?>
