<?php

use These\Entity\Db\These;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var These       $these
 */
?>

<?php $this->headTitle("Feuille de route")->prepend($these->getDoctorant()->getNomUsuel()) ?>

<h1 class="page-header">Feuille de route <small><?php echo $this->partial('these/these/partial/titre') ?></small></h1>

<?php echo $this->roadmap($these) ?: "Néant." ?>

<?php
$wfHelper = $this->wf($these);
$wfStepHelper = $wfHelper->current();
?>

<?php if ($wfStepHelper->step() === null): ?>
    <?php if (in_array($these->getEtatThese(), [These::ETAT_EN_COURS, These::ETAT_SOUTENUE])): ?>
        <div class="box roadmap-next-step">
            <p class="lead"><!--<span class="fas fa-thumbs-up"></span>--> Dépôt validé.</p>
        </div>
    <?php endif ?>
<?php endif ?>

<?php echo $this->partial('next-step-box', ['these' => $these]) ?>
