<?php
/**
 * Affichage des métadonnées de la thèse.
 *
 * @var These $these
 */

use Depot\Entity\Db\MetadonneeThese;
use These\Entity\Db\These;
use Depot\Filter\MotsClesFormatter;

$metadonnee = $these->getMetadonnee();
$motsClesFormatter = new MotsClesFormatter(['separator' => MetadonneeThese::SEPARATEUR_MOTS_CLES]);

$langueAutreTitre = function() use ($metadonnee) {
    return $metadonnee->getLangue() === MetadonneeThese::LANGUE_FRANCAIS ?
        MetadonneeThese::LANGUE_ANGLAIS :
        MetadonneeThese::LANGUE_FRANCAIS;
};
?>

<div class="row">
    <div class="col-md-6">
        <dl class="metadonnees">
            <dt>Titre</dt>
            <dd><?php echo $this->escapeHtml($these->getTitre()) ?></dd>
            <dt>Langue</dt>
            <dd><?php echo MetadonneeThese::$langues[$metadonnee->getLangue()] ?></dd>
            <dt>Titre en <?php echo strtolower(MetadonneeThese::$langues[$langueAutreTitre()]) ?></dt>
            <dd><?php echo $this->escapeHtml($metadonnee->getTitreAutreLangue()) ?></dd>
        </dl>
    </div>
    <div class="col-md-6">
        <dl class="metadonnees">
            <dt>Proposition de mots-clés en français</dt>
            <dd><?php echo $motsClesFormatter->filter($metadonnee->getMotsClesLibresFrancais()) ?></dd>
            <dt>Proposition de mots-clés en anglais</dt>
            <dd><?php echo $motsClesFormatter->filter($metadonnee->getMotsClesLibresAnglais()) ?: "(Non renseignés)" ?></dd>
        </dl>
    </div>
</div>
        <dl class="metadonnees">
            <dt>Résumé</dt>
            <dd><p class="pre-scrollable"><?php echo $this->escapeText()->render($metadonnee->getResume()) ?></p></dd>
            <dt>Résumé en anglais</dt>
            <dd><p class="pre-scrollable"><?php echo $this->escapeText()->render($metadonnee->getResumeAnglais()) ?></p></dd>
        </dl>