<?php

namespace Application;

use Formation\Provider\Privilege\ModulePrivileges;
use Formation\Service\Module\Search\ModuleSearchService;
use Laminas\Paginator\Paginator as LaminasPaginator;

/**
 * @var string $title
 * @var LaminasPaginator $paginator
 * @var string $routeName
 * @var string $returnUrl
 *
 * @see \Formation\Controller\Recherche\ModuleRechercheController::indexAction()
 */

$this->headTitle($this->translate($title));

$canAfficherModule = $this->isAllowed(ModulePrivileges::getResourceId(ModulePrivileges::MODULE_AFFICHER));
$canAjouterModule = $this->isAllowed(ModulePrivileges::getResourceId(ModulePrivileges::MODULE_AJOUTER));
$canHistoriserModule = $this->isAllowed(ModulePrivileges::getResourceId(ModulePrivileges::MODULE_HISTORISER));
$canSupprimerModule = $this->isAllowed(ModulePrivileges::getResourceId(ModulePrivileges::MODULE_SUPPRIMER));
?>

<h1 class="page-header"><?php echo $title ?></h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace(); ?>


<!-- Formulaire de filtrage -->
<div class="float-start">
    <?php $loadFiltersUrl = $this->url($routeName . '/filters', [], ['query' => $this->queryParams()], true); ?>
    <div id="filters" data-url="<?php echo $loadFiltersUrl ?>" style="min-height: 160px">
        <!-- Contenu chargé en AJAX -->
    </div>
</div>
<div class="clearfix"></div>

<?php if ($canAjouterModule) : ?>
    <a
        <?php /** @see \Formation\Controller\ModuleController::ajouterAction() */ ?>
            href="<?php echo $this->url('formation/module/ajouter', [], [], true); ?>"
            class="btn btn-primary ajax-modal" data-event="modification">
        <span class="icon icon-ajouter"></span>
        Ajouter un module
    </a>
<?php endif; ?>

<div class="index-result">
<?php if (count($paginator) > 0): ?>

    <p>
        <?php echo $paginator->getTotalItemCount() . ' ' . $this->translate("module·s trouvé·s.") ?>
    </p>

    <table class="table table-sm table-hover">
        <thead>
        <tr>
            <th>
                <a href="<?php echo $s = $this->sortable(ModuleSearchService::NAME_libelle) ?>"
                   title="<?php echo $this->translate("Libellé") ?> ">
                    <?php echo $this->translate("Libellé") ?>
                </a> <?php echo $s->icon() ?>
            </th>
            <th>
                Nb formations
            </th>
            <th>
                Action
            </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($paginator as $module): ?>
            <tr>
                <td>
                    <span class=" <?php if ($module->estHistorise()) echo " historisee text-danger"; ?>">
                    <?php echo $module->getLibelle(); ?>
                        <?php if ($module->getDescription() !== null and trim($module->getDescription()) !== null) : ?>
                            <span class="icon icon-info"
                                  title="<?php echo $module->getDescription(); ?>" data-bs-toggle="tooltip"
                                  data-bs-html="true"

                            ></span>
                        <?php endif; ?>
                    </span>

                </td>
                <td> <?php echo count($module->getFormations()); ?> </td>
                <td>
                    <?php if ($canAfficherModule) : ?>
                        <?php /** @see \Formation\Controller\ModuleController::afficherAction() */ ?>
                        <a href="<?php echo $this->url('formation/module/afficher', ['module' => $module->getId()], [], true); ?>"
                           title="afficher le module de formation #<?php echo $module->getId(); ?>"
                           data-bs-toggle="tooltip" data-bs-html="true">
                            <span class="icon icon-voir"></span>
                        </a>
                    <?php endif; ?>
                    <?php if ($canHistoriserModule) : ?>
                        <?php if ($module->estNonHistorise()) : ?>
                            <?php /** @see \Formation\Controller\ModuleController::historiserAction() */ ?>
                            <a href="<?php echo $this->url('formation/module/historiser', ['module' => $module->getId()], [], true); ?>"
                               title="Historiser le module de  formation #<?php echo $module->getId(); ?>"
                               data-bs-toggle="tooltip" data-bs-html="true">
                                <span class="icon icon-historiser"></span>
                            </a>
                        <?php else : ?>
                            <?php /** @see \Formation\Controller\ModuleController::restaurerAction() */ ?>
                            <a href="<?php echo $this->url('formation/module/restaurer', ['module' => $module->getId()], [], true); ?>"
                               title="Restaurer le module de  formation #<?php echo $module->getId(); ?>"
                               data-bs-toggle="tooltip" data-bs-html="true">
                                <span class="icon icon-restaurer"></span>
                            </a>
                        <?php endif; ?>
                    <?php endif; ?>

                    <?php if ($canSupprimerModule and $module->estHistorise()) : ?>
                        <?php /** @see \Formation\Controller\ModuleController::supprimerAction() */ ?>
                        <a href="<?php echo $this->url('formation/module/supprimer', ['module' => $module->getId()], [], true); ?>"
                           class="ajax-modal" data-event="modification"
                           title="Suppression du module de formation #<?php echo $module->getId(); ?>"
                           data-bs-toggle="tooltip" data-bs-html="true">
                            <span class="icon icon-detruire text-danger"></span>
                        </a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>


<?php echo $this->paginationControl($paginator, 'sliding', 'paginator', ['route' => $routeName . '/recherche/index']) ?>

<?php else: ?>

    <p>Aucun module trouvé.</p>

<?php endif ?>


<script>
    $(function () {
        $("#filters").addClass("loading").refresh(null, function () {
            $(this).removeClass("loading");
        });
    });

    $(function () {
        $('[data-bs-toggle="tooltip"]').tooltip({});
    });

    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });

    });
</script>