<?php

use Application\Entity\Db\Acteur;
use Application\Entity\Db\Anomalie;
use Application\Entity\Db\These;

/**
 * @see \Indicateur\Controller\IndicateurController::indexAction()
 * @var array $effectifs
 * @var Acteur[] $acteursSansMail
 * @var These[] $doctorantsSansMail
 * @var These[] $theses
 * @var These[] $anciennes
 * @var Anomalie[] $anomalies
 */
?>


<h1 class="page-header first">
    Indicateurs de SyGAL
</h1>

<div>

    <div class="row">

        <div class="col-md-4">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <?php
                        $date = new \DateTime();
                        $annee= $date->format("Y");
                        ?>
                    <h4>
                        État des thèses pour l'année <?php echo $annee; ?>
                    </h4>
                </div>
                <div class="panel-body">
                    <table class="table table-extra-condensed">
                        <thead>
                            <tr>
                                <th> Etablissement</th>
                                <th> En cours </th>
                                <th> Inscription </th>
                                <th> Soutenance </th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($effectifs as $etablissement => $effectif): ?>
                            <tr>
                                <td> <?php echo $etablissement; ?> </td>
                                <td> <?php echo $effectif[0]; ?> </td>
                                <td> <?php echo $effectif[1]; ?> </td>
                                <td> <?php echo $effectif[2]; ?> </td>
                            </tr>
                            <?php endforeach;?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="panel panel-warning">
                <div class="panel-heading">
                    <h4>
                        Thèses avec soutenance dépassée
                        <span class="badge"> <?echo count($theses); ?> </span>
                    </h4>
                </div>
                <div class="panel-body">
                    <table class="table table-extra-condensed">
                        <thead>
                        <tr>
                            <th> These</th>
                            <th> État </th>
                            <th> Date de soutenance </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php for($i = 0; $i < 5 && $i < count($theses); $i++): ?>
                        <tr>
                            <td> <?php echo $theses[$i]->getSourceCode(); ?></td>
                            <td> <?php echo $theses[$i]->getEtatThese(); ?></td>
                            <td> <?php echo $theses[$i]->getDateSoutenance()->format("d/m/Y"); ?></td>
                        </tr>
                        <?php endfor; ?>
                        <?php if(count($theses) >= 5): ?>
                        <tr>
                            <td colspan="3"> ... </td>
                        </tr>
                        <?php endif; ?>
                        </tbody>
                    </table>
                    <div class="pull-right">
                    <a class="btn btn-success" href="<?php echo $this->url('indicateur/soutenance-depassee', [], [], true);?>">
                        <span class="glyphicon glyphicon-eye-open"></span> Visualiser les données
                    </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="panel panel-warning">
                <div class="panel-heading">
                    <h4>
                        Thèses anciennes (plus de 6 ans)
                        <span class="badge"> <?echo count($anciennes); ?> </span>
                    </h4>
                </div>
                <div class="panel-body">
                    <table class="table table-extra-condensed">
                        <thead>
                        <tr>
                            <th> These</th>
                            <th> État </th>
                            <th> Première inscription </th>
                            <th> Soutenance </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php for($i = 0; $i < 5 && $i < count($anciennes); $i++): ?>
                            <tr>
                                <td> <?php echo $anciennes[$i]->getSourceCode(); ?></td>
                                <td> <?php echo $anciennes[$i]->getEtatThese(); ?></td>
                                <td> <?php echo $anciennes[$i]->getDatePremiereInscription()->format("d/m/Y"); ?></td>
                                <td> <?php echo ($anciennes[$i]->getDateSoutenance())?$anciennes[$i]->getDateSoutenance()->format("d/m/Y"):""; ?></td>
                            </tr>
                        <?php endfor; ?>
                        <?php if(count($anciennes) >= 5): ?>
                            <tr>
                                <td colspan="4"> ... </td>
                            </tr>
                        <?php endif; ?>
                        </tbody>
                    </table>
                    <div class="pull-right">
                        <a class="btn btn-success" href="<?php echo $this->url('indicateur/theses-anciennes', [], [], true);?>">
                            <span class="glyphicon glyphicon-eye-open"></span> Visualiser les données
                        </a>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="row">

        <div class="col-md-4">
            <div class="panel panel-warning">
                <div class="panel-heading">
                    <h4>
                        Doctorants sans eMail
                        <span class="badge"> <?echo count($doctorantsSansMail); ?> </span>
                    </h4>
                </div>
                <div class="panel-body">
                    <table class="table table-extra-condensed">
                        <thead>
                        <tr>
                            <th> Thèse </th>
                            <th> Identifiant</th>
                            <th> Nom </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php for($i = 0; $i < 5 && $i < count($doctorantsSansMail); $i++): ?>
                            <tr>
                                <td> <?php echo $doctorantsSansMail[$i]->getSourceCode(); ?></td>
                                <td> <?php echo $doctorantsSansMail[$i]->getDoctorant()->getSourceCode(); ?></td>
                                <td> <?php echo $doctorantsSansMail[$i]->getDoctorant()->getIndividu()->getNomComplet(); ?></td>


                            </tr>
                        <?php endfor; ?>
                        <?php if(count($doctorantsSansMail) >= 5): ?>
                            <tr>
                                <td colspan="3"> ... </td>
                            </tr>
                        <?php endif; ?>
                        </tbody>
                    </table>
                    <div class="pull-right">
                        <a class="btn btn-success" href="<?php echo $this->url('indicateur/doctorants-sans-mail', [], [], true);?>">
                            <span class="glyphicon glyphicon-eye-open"></span> Visualiser les données
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="panel panel-warning">
                <div class="panel-heading">
                    <h4>
                        Acteurs sans eMail
                        <span class="badge"> <?echo count($acteursSansMail); ?> </span>
                    </h4>
                </div>
                <div class="panel-body">
                    <table class="table table-extra-condensed">
                        <thead>
                        <tr>
                            <th> Thèse </th>
                            <th> Identifiant</th>
                            <th> Rôle </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php for($i = 0; $i < 5 && $i < count($acteursSansMail); $i++): ?>
                            <tr>
                                <td> <?php echo $acteursSansMail[$i]->getThese()->getSourceCode(); ?></td>
                                <td> <?php echo $acteursSansMail[$i]->getSourceCode(); ?></td>
                                <td> <?php echo $acteursSansMail[$i]->getRole()->getLibelle(); ?></td>


                            </tr>
                        <?php endfor; ?>
                        <?php if(count($acteursSansMail) >= 5): ?>
                            <tr>
                                <td colspan="3"> ... </td>
                            </tr>
                        <?php endif; ?>
                        </tbody>
                    </table>
                    <div class="pull-right">
                        <a class="btn btn-success" href="<?php echo $this->url('indicateur/acteurs-sans-mail', [], [], true);?>">
                            <span class="glyphicon glyphicon-eye-open"></span> Visualiser les données
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h4>
                        Anomalie de clefs étrangères
                        <span class="badge"> <?echo count($anomalies); ?> </span>
                    </h4>
                </div>
                <div class="panel-body">
                    <table class="table table-extra-condensed">
                        <thead>
                        <tr>
                            <th> Nom de la table </th>
                            <th> Attribut</th>
                            <th> Valeur </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php for($i = 0; $i < 5 && $i < count($anomalies); $i++): ?>
                            <tr>
                                <td> <?php echo $anomalies[$i]->getTableName(); ?></td>
                                <td> <?php echo $anomalies[$i]->getTableColumn(); ?></td>
                                <td> <?php echo $anomalies[$i]->getColumnValue(); ?></td>


                            </tr>
                        <?php endfor; ?>
                        <?php if(count($anomalies) >= 5): ?>
                            <tr>
                                <td colspan="3"> ... </td>
                            </tr>
                        <?php endif; ?>
                        </tbody>
                    </table>
                    <div class="pull-right">
                        <a class="btn btn-success" href="<?php echo $this->url('tableau-de-bord/anomalie', [], [], true);?>">
                            <span class="glyphicon glyphicon-eye-open"></span> Visualiser les données
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
