<?php

use Application\Entity\Db\Acteur;
use Application\Entity\Db\Anomalie;
use Application\Entity\Db\These;

/**
 * @see \Indicateur\Controller\IndicateurController::indexAction()
 * @var array $effectifs
 * @var Acteur[] $sansMail
 * @var These[] $theses
 * @var Anomalie[] $anomalies
 */
?>


<h1>
    Indicateurs de SyGAL
</h1>

<div>
    <div class="col-md-4">
        <div class="panel panel-info">
            <div class="panel-heading">
                <?php
                    $date = new \DateTime();
                    $annee= $date->format("Y");
                    ?>
                <h4>
                    Thèses par établissements pour l'année <?php echo $annee; ?>
                </h4>
            </div>
            <div class="panel-body">
                <table class="table table-extra-condensed">
                    <thead>
                        <tr>
                            <th> Etablissement</th>
                            <th> En cours </th>
                            <th> Inscription </th>
                            <th> Soutenance </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($effectifs as $etablissement => $effectif): ?>
                        <tr>
                            <td> <?php echo $etablissement; ?> </td>
                            <td> <?php echo $effectif[0]; ?> </td>
                            <td> <?php echo $effectif[1]; ?> </td>
                            <td> <?php echo $effectif[2]; ?> </td>
                        </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h4>
                    Thèses en cours malgré soutenance dépassée
                    <span class="badge"> <?echo count($theses); ?> </span>
                </h4>
            </div>
            <div class="panel-body">
                <table class="table table-extra-condensed">
                    <thead>
                    <tr>
                        <th> These</th>
                        <th> État </th>
                        <th> Date de soutenance </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php for($i = 0; $i < 5 && $i < count($theses); $i++): ?>
                    <tr>
                        <td> <?php echo $theses[$i]->getSourceCode(); ?></td>
                        <td> <?php echo $theses[$i]->getEtatThese(); ?></td>
                        <td> <?php echo $theses[$i]->getDateSoutenance()->format("d/m/Y"); ?></td>
                    </tr>
                    <?php endfor; ?>
                    <?php if(count($theses) >= 5): ?>
                    <tr>
                        <td colspan="3"> ... </td>
                    </tr>
                    <?php endif; ?>
                    </tbody>
                </table>
                <div class="pull-right">
                <a class="btn btn-success" href="<?php echo $this->url('indicateur/soutenance-depassee', [], [], true);?>">
                    <span class="glyphicon glyphicon-eye-open"></span> Visualiser les données
                </a>
                </div>
            </div>
        </div>
    </div>
</div>

<div>
    <div class="col-md-4">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h4>
                    Acteurs sans adresse électronique
                    <span class="badge"> <?echo count($sansMail); ?> </span>
                </h4>
            </div>
            <div class="panel-body">
                <table class="table table-extra-condensed">
                    <thead>
                    <tr>
                        <th> Thèse </th>
                        <th> Identifiant</th>
                        <th> Rôle </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php for($i = 0; $i < 5 && $i < count($sansMail); $i++): ?>
                        <tr>
                            <td> <?php echo $sansMail[$i]->getThese()->getSourceCode(); ?></td>
                            <td> <?php echo $sansMail[$i]->getSourceCode(); ?></td>
                            <td> <?php echo $sansMail[$i]->getRole()->getLibelle(); ?></td>


                        </tr>
                    <?php endfor; ?>
                    <?php if(count($theses) >= 5): ?>
                        <tr>
                            <td colspan="3"> ... </td>
                        </tr>
                    <?php endif; ?>
                    </tbody>
                </table>
                <div class="pull-right">
                    <a class="btn btn-success" href="">
                        <span class="glyphicon glyphicon-eye-open"></span> Visualiser les données
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<div>
    <div class="col-md-4">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h4>
                    Anomalie de clefs étrangères
                    <span class="badge"> <?echo count($anomalies); ?> </span>
                </h4>
            </div>
            <div class="panel-body">
                <table class="table table-extra-condensed">
                    <thead>
                    <tr>
                        <th> Nom de la table </th>
                        <th> Attribut</th>
                        <th> Valeur </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php for($i = 0; $i < 5 && $i < count($sansMail); $i++): ?>
                        <tr>
                            <td> <?php echo $anomalies[$i]->getTableName(); ?></td>
                            <td> <?php echo $anomalies[$i]->getTableColumn(); ?></td>
                            <td> <?php echo $anomalies[$i]->getColumnValue(); ?></td>


                        </tr>
                    <?php endfor; ?>
                    <?php if(count($theses) >= 5): ?>
                        <tr>
                            <td colspan="3"> ... </td>
                        </tr>
                    <?php endif; ?>
                    </tbody>
                </table>
                <div class="pull-right">
                    <a class="btn btn-success" href="">
                        <span class="glyphicon glyphicon-eye-open"></span> Visualiser les données
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
