<?php

use Application\Entity\Db\Acteur;
use Application\Entity\Db\Anomalie;
use Application\Entity\Db\These;use Indicateur\Model\Indicateur;

/**
 * @see \Indicateur\Controller\IndicateurController::indexAction()
 * @var array $effectifs
 * @var Acteur[] $acteursSansMail
 * @var These[] $doctorantsSansMail
 * @var These[] $theses
 * @var These[] $anciennes
 * @var These[] $soutenancesSansCouverture
 * @var These[] $thesesASoutenir
 * @var Anomalie[] $anomalies
 *
 * @var Indicateur[] $indicateurs
 */
?>


<h1 class="page-header first">
    Indicateurs de SyGAL
</h1>

<h2>
    Liste des indicateurs enregistrés en base
</h2>

<table class="table table-extra-condensed">
    <thead>
        <tr>
            <th> Libelle </th>
            <th> Description </th>
            <th> Actif </th>
            <th> Action </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($indicateurs as $indicateur): ?>
            <tr>
                <td> <?php echo $indicateur->getLibelle(); ?> </td>
                <td> <?php echo $indicateur->getDescription(); ?> </td>
                <td> <?php echo $indicateur->isActif(); ?> </td>
                <td>
                    <span class="glyphicon glyphicon-pencil"></span>
                    <span class="glyphicon glyphicon-refresh"></span>
                    <span class="glyphicon glyphicon-off"></span>
                    <span class="glyphicon glyphicon-trash"></span>
                </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>

<?php echo $this->resumeIndicateurThese()->render($indicateurs[0], $result_ind0); ?>
<?php echo $this->resumeIndicateurThese()->render($indicateurs[1], $result_ind1); ?>
<?php echo $this->resumeIndicateurThese()->render($indicateurs[2], $result_ind2); ?>
<?php echo $this->resumeIndicateurIndividu()->render($indicateurs[3], $result_ind3); ?>
<?php echo $this->resumeIndicateurIndividu()->render($indicateurs[4], $result_ind4); ?>

</div>
