<?php

/**
 * @var Indicateur[] $indicateurs
 */

use Indicateur\Model\Indicateur;
use Indicateur\Provider\Privilege\IndicateurPrivileges;


$canEdit    = $this->isAllowed(IndicateurPrivileges::getResourceId(IndicateurPrivileges::INDICATEUR_EDITION));
$canRefresh = $this->isAllowed(IndicateurPrivileges::getResourceId(IndicateurPrivileges::INDICATEUR_RAFRAICHISSEMENT));
$canToggle  = $this->isAllowed(IndicateurPrivileges::getResourceId(IndicateurPrivileges::INDICATEUR_EDITION));
$canDelete  = $this->isAllowed(IndicateurPrivileges::getResourceId(IndicateurPrivileges::INDICATEUR_EDITION));

?>

<h1 class="page-header">
    Liste des indicateurs enregistrés en base
    <span class="badge bg-secondary"><?php echo count($indicateurs); ?></span>
</h1>

<a href="<?php echo $this->url('indicateur', [], [], true); ?>"
   class="btn btn-primary"
>
    <span class="fas fa-th"></span> Retourner à la liste des indicateurs
</a>

<?php if($canEdit):?>
    <a href="<?php echo $this->url('indicateur/editer', [], [], true); ?>"
       class="btn btn-primary"
    >
        <span class="icon icon-plus"></span> Ajouter un nouvel indicateur
    </a>
<?php endif; ?>

<br/><br/>

<table class="table table-sm">
    <thead>
    <tr>
<!--        <th> Id </th>-->
        <th> Libelle </th>
        <th> Description </th>
        <th> Actif </th>
        <th> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($indicateurs as $indicateur): ?>
        <tr>
<!--            <td> --><?php //echo $indicateur->getId(); ?><!-- </td>-->
            <td> <?php echo $indicateur->getLibelle(); ?> </td>
            <td> <?php echo $indicateur->getDescription(); ?> </td>
            <td> <?php echo $indicateur->isActif(); ?> </td>
            <td>
                <?php if($canEdit):?>
                    <a href="<?php echo $this->url('indicateur/editer',['indicateur'=>$indicateur->getId()],[], true); ?>">
                        <span class="icon icon-edit iconly" title="Éditer un indicateur"></span>
                    </a>
                <?php endif; ?>
                <?php if($canRefresh):?>
                    <a href="<?php echo $this->url('indicateur/rafraichir',['indicateur'=>$indicateur->getId()],[], true); ?>">
                        <span class="icon icon-refresh iconly" title="Rafraichir un indicateur"></span>
                    </a>
                <?php endif; ?>
                <?php if($canToggle):?>
                    <a href="<?php echo $this->url('indicateur/toggle',['indicateur'=>$indicateur->getId()],[], true); ?>">
                        <span class="fas fa-power-off" title="Activer/Désactiver un indicateur"></span>
                    </a>
                <?php endif;?>
                <?php if($canDelete):?>
                    <a data-toggle="confirmationx" href="<?php echo $this->url('indicateur/effacer',['indicateur'=>$indicateur->getId()],[], true); ?>">
                        <span class="icon icon-delete iconly text-danger" title="Effacer définitivement un indicateur <br>(Une confirmation avant la suppression vous sera demandée)" data-bs-toggle="tooltip"
                              data-bs-html="true"></span>
                    </a>
                <?php endif;?>
            </td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>