<?php

use Indicateur\Model\Indicateur;
use Indicateur\Provider\Privilege\IndicateurPrivileges;

/**
 * @var Indicateur $indicateur
 * @var array $data
 * @var \Application\Service\Structure\StructureService $structureService
 *
 * @see \Indicateur\Controller\IndicateurController::viewAction()
 */

?>

<?php $canExport = IndicateurPrivileges::getResourceId(IndicateurPrivileges::INDICATEUR_EXPORTATION); ?>

<h1 class="page-header">
    <?php echo $indicateur->getLibelle(); ?>
    <span class="badge">
        <?php echo count($data); ?>
    </span>
</h1>

<p>
<?php if($canExport): ?>
    <a href="<?php echo $this->url('indicateur/export', ['indicateur' => $indicateur->getId()], [] , true);?>" class="btn btn-primary">
        <span class="glyphicon glyphicon-export"></span>
        Export les données au format CSV
    </a>
<?php endif; ?>
<!--    <a href="--><?php //echo $this->url('indicateur/rafraichir', ['indicateur' => $indicateur->getId()], [] , true);?><!--" class="btn btn-primary">-->
<!--        <span class="glyphicon glyphicon-refresh"></span>-->
<!--        Forcer le rafraîchissement de l'indicateur-->
<!--    </a>-->
</p>

<?php if ($indicateur->getDisplayAs() === Indicateur::THESE): ?>
    <?php echo $this->completIndicateurThese()->render($indicateur, $data, $structureService); ?>
<?php endif; ?>

<?php if ($indicateur->getDisplayAs() === Indicateur::INDIVIDU): ?>
    <?php echo $this->completIndicateurIndividu()->render($indicateur, $data); ?>
<?php endif; ?>

<?php if ($indicateur->getDisplayAs() === Indicateur::STRUCTURE): ?>
    <?php echo $this->completIndicateurStructure()->render($indicateur, $data); ?>
<?php endif; ?>

