<?php /** @noinspection PhpUnusedAliasInspection */

use Formation\Entity\Db\Formateur;
use Formation\Entity\Db\Seance;
use Formation\Entity\Db\Session;

/**
 * @see \Formation\View\Helper\EtatViewHelper
 * @var Session $session
 * @var array $options
 */

$displayType = $options['display-type']??null;

/** @var Formateur[] $formateurs */
$formateurs = $session->getFormateurs()->toArray();
$formateurs = array_filter($formateurs, function (Formateur $a) { return $a->estNonHistorise();});
usort($formateurs, function(Formateur $a, Formateur $b) { return $a->getIndividu()->getNomComplet() > $b->getIndividu()->getNomComplet();});

?>

<?php if (!empty($formateurs)) : ?>
    <?php if ($displayType === 'liste') : ?>
        <ul>
            <?php foreach ($formateurs as $formateur) : ?>
            <li>
                <?php echo $formateur->getIndividu()->getNomComplet(); ?>
            </li>
            <?php endforeach; ?>
        </ul>
    <?php else : ?>
        <?php $array = []; foreach ($formateurs as $formateur) { $array[] = $formateur->getIndividu()->getNomComplet();} ?>
        <?php echo implode('<br/>', $array); ?>
    <?php endif; ?>
<?php else : ?>
    <span class="text-danger">Aucun·e formateur&middot;trice</span>
<?php endif; ?>

