<?php

/**
 * @see \Formation\View\Helper\InscriptionViewHelper
 * @var Inscription $inscription
 * @var array $options
 */

use Application\Entity\Db\These;
use Application\Entity\Db\TheseAnneeUniv;
use Formation\Entity\Db\Inscription;

$actionListePrincipale = (!isset($options['action-liste-principale']) OR $options['action-liste-principale'] !== false);
$actionListeComplementaire = (!isset($options['action-liste-complementaire']) OR $options['action-liste-complementaire'] !== false);
$actionHistoriser = (!isset($options['action-historiser']) OR $options['action-historiser'] !== false);
$actionSupprimer = (!isset($options['action-supprimer']) OR $options['action-supprimer'] !== false);

$doctorant = $inscription->getDoctorant();
$session = $inscription->getSession();
//todo trouver solution pour récupèrer la bonne thèse dans le cas des thèses multiples

/** @var These $these */
$these = current($doctorant->getTheses());
//todo faire fonction pour le calcul dans l'entité
$annee = ((int) "2021");
$inscriptions = array_filter($these->getAnneesUnivInscription()->toArray(), function (TheseAnneeUniv $a) use ($annee) { return $a->getAnneeUniv() <= $annee; });

?>

<li>
    <?php

    echo $doctorant->getIndividu()->getNomComplet(); ?>
    <?php if ($inscription->estHistorise()) : ?>
    <span class="historisee"></span>
    <?php endif; ?>
    <?php foreach ($doctorant->getTheses() as $these) {
        if ($these->getEtatThese() === These::ETAT_EN_COURS) {
            echo "<br/>";
            echo $this->site($these->getEtablissement());
            echo " - ";
            echo $this->site($these->getEcoleDoctorale());
            echo " - ";
            echo $this->site($these->getUniteRecherche());
            echo " - ";
            echo "D" . count($inscriptions);
        }
    }
    ?>
    <br/>
    Inscrit le <?php echo $inscription->getHistoCreation()->format("d/m/Y à H:i"); ?>

    <?php if ($actionListePrincipale OR $actionListeComplementaire OR $actionHistoriser OR $actionSupprimer) : ?>
        <br/>
        <?php if ($inscription->estNonHistorise() AND $actionListePrincipale) : ?>
            <a
                <?php /** @see \Formation\Controller\InscriptionController::passerListePrincipaleAction() */?>
                    href="<?php echo $this->url('formation/inscription/passer-liste-principale', ['inscription' => $inscription->getId()], ['query' => ['retour' => $this->url('formation/session/afficher', ['session' => $session->getId()])]], true); ?>"
                    title="Passer <?php echo $doctorant->getIndividu()->getNomComplet(); ?> en liste principale" data-bs-toggle="tooltip" data-bs-html="true"
            >
                <strong>P</strong></a>
        <?php endif; ?>
        <?php if ($inscription->estNonHistorise() AND $actionListeComplementaire) : ?>
        <a <?php /** @see \Formation\Controller\InscriptionController::passerListeComplementaireAction() */?>
                href="<?php echo $this->url('formation/inscription/passer-liste-complementaire', ['inscription' => $inscription->getId()], ['query' => ['retour' => $this->url('formation/session/afficher', ['session' => $session->getId()])]], true); ?>"
                title="Passer <?php echo $doctorant->getIndividu()->getNomComplet(); ?> en liste complémentaire" data-bs-toggle="tooltip" data-bs-html="true"
        >
            <strong>C</strong></a>
        <?php endif; ?>
        <?php if (($inscription->getListe() !== null) AND $inscription->getListe()) : ?>
            <a <?php /** @see \Formation\Controller\InscriptionController::retirerListeAction() */?>
                    href="<?php echo $this->url('formation/inscription/retirer-liste', ['inscription' => $inscription->getId()], ['query' => ['retour' => $this->url('formation/session/afficher', ['session' => $session->getId()])]], true); ?>"
                    title="Retirer des liste l'inscription de  <?php echo $doctorant->getIndividu()->getNomComplet(); ?>" data-bs-toggle="tooltip" data-bs-html="true"
            >
                <strong>∅</strong></a>
        <?php endif; ?>
        <?php if ($actionHistoriser) : ?>
            <?php if ($inscription->estNonHistorise()) : ?>
                <?php /** @see \Formation\Controller\InscriptionController::historiserAction() */ ?>
                <a href="<?php echo $this->url('formation/inscription/historiser', ['inscription' => $inscription->getId()], ['query' => ['retour' => $this->url('formation/session/afficher', ['session' => $session->getId()])]], true); ?>">
                    <span class="icon icon-historiser"></span></a>
            <?php else : ?>
                <?php /** @see \Formation\Controller\InscriptionController::restaurerAction() */ ?>
                <a href="<?php echo $this->url('formation/inscription/restaurer', ['inscription' => $inscription->getId()], ['query' => ['retour' => $this->url('formation/session/afficher', ['session' => $session->getId()])]], true); ?>">
                    <span class="icon icon-restaurer"></span></a>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($actionSupprimer AND $inscription->estHistorise()) : ?>
            <?php /** @see \Formation\Controller\InscriptionController::supprimerAction() */ ?>
            <a href="<?php echo $this->url('formation/inscription/supprimer', ['inscription' => $inscription->getId()], [], true); ?>"
               class="ajax-modal" data-event="modification"
            >
                <span class="icon icon-detruire text-danger"></span></a>
        <?php endif; ?>
    <?php endif; ?>
</li>


