<?php

/**
 * @see \Formation\View\Helper\InscriptionViewHelper
 * @var Inscription $inscription
 * @var array $options
 */

use Application\Entity\Db\These;
use Formation\Entity\Db\Inscription;

$actionListePrincipale = (!isset($options['action-liste-principale']) OR $options['action-liste-principale'] !== false);
$actionListeComplementaire = (!isset($options['action-liste-complementaire']) OR $options['action-liste-complementaire'] !== false);
$actionHistoriser = (!isset($options['action-historiser']) OR $options['action-historiser'] !== false);
$actionSupprimer = (!isset($options['action-supprimer']) OR $options['action-supprimer'] !== false);

$doctorant = $inscription->getDoctorant();
$session = $inscription->getSession();
?>

<li>
    <?php

    echo $doctorant->getIndividu()->getNomComplet();
    foreach ($doctorant->getTheses() as $these) {
        if ($these->getEtatThese() === These::ETAT_EN_COURS) {
            echo "<br/>";
            echo $this->site($these->getEtablissement());
            echo " - ";
            echo $this->site($these->getEcoleDoctorale());
            echo " - ";
            echo $this->site($these->getUniteRecherche());
        }
    }
    ?>
    <br/>
    Inscrit le <?php echo $inscription->getHistoCreation()->format("d/m/Y à H:i"); ?>

    <?php if ($actionListePrincipale OR $actionListeComplementaire OR $actionHistoriser OR $actionSupprimer) : ?>
        <br/>
        <?php if ($actionListePrincipale) : ?>
            <a
                <?php /** @see \Formation\Controller\InscriptionController::passerListePrincipaleAction() */?>
                    href="<?php echo $this->url('formation/inscription/passer-liste-principale', ['inscription' => $inscription->getId()], ['query' => ['retour' => $this->url('formation/session/afficher', ['session' => $session->getId()])]], true); ?>"
                    title="Passer <?php echo $doctorant->getIndividu()->getNomComplet(); ?> en liste principale" data-toggle="tooltip" data-html="true"
            >
                <strong>P</strong>
            </a>
        <?php endif; ?>
        <?php if ($actionListeComplementaire) : ?>
        <a <?php /** @see \Formation\Controller\InscriptionController::passerListeComplementaireAction() */?>
                href="<?php echo $this->url('formation/inscription/passer-liste-complementaire', ['inscription' => $inscription->getId()], ['query' => ['retour' => $this->url('formation/session/afficher', ['session' => $session->getId()])]], true); ?>"
                title="Passer <?php echo $doctorant->getIndividu()->getNomComplet(); ?> en liste complémentaire" data-toggle="tooltip" data-html="true"
        >
            <strong>C</strong>
        </a>
        <?php endif; ?>
        <?php if ($actionHistoriser) : ?>
            <?php if ($inscription->estNonHistorise()) : ?>
                <?php /** @see \Formation\Controller\InscriptionController::historiserAction() */ ?>
                <a href="<?php echo $this->url('formation/inscription/historiser', ['inscription' => $inscription->getId()], ['query' => ['retour' => $this->url('formation/session/afficher', ['session' => $session->getId()])]], true); ?>">
                    <span class="glyphicon glyphicon-trash"></span>
                </a>
            <?php else : ?>
                <?php /** @see \Formation\Controller\InscriptionController::restaurerAction() */ ?>
                <a href="<?php echo $this->url('formation/inscription/restaurer', ['inscription' => $inscription->getId()], ['query' => ['retour' => $this->url('formation/session/afficher', ['session' => $session->getId()])]], true); ?>">
                    <span class="glyphicon glyphicon-leaf"></span>
                </a>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($actionSupprimer) : ?>
            <?php /** @see \Formation\Controller\InscriptionController::supprimerAction() */ ?>
            <a href="<?php echo $this->url('formation/inscription/supprimer', ['inscription' => $inscription->getId()], [], true); ?>"
               class="ajax-modal" data-event="modification"
            >
                <span class="glyphicon glyphicon-remove"></span>
            </a>
        <?php endif; ?>
    <?php endif; ?>
</li>


