<?php

use Structure\Entity\Db\Etablissement;

/**
 * @see \Formation\View\Helper\SiteViewHelper
 * @var Etablissement|null $site
 * @var array $options
 */

$long = $options['long']??false;
?>

<?php if ($site !== null) : ?>
    <span class="site" title="<?php echo $site->getStructure()->getLibelle(); ?>"
          data-bs-toggle="tooltip" data-bs-html="true">
        <?php if ($long) : ?>
            <?php echo $site->getStructure()->getLibelle(); ?>
        <?php else : ?>
            <?php echo $site->getStructure()->getSigle(); ?>
        <?php endif; ?>
    </span>
<?php else : ?>
    <span class="site" title="Formation dispensée pour tous les sites"
          data-bs-toggle="tooltip" data-bs-html="true">
        Multi-site
    </span>
<?php endif; ?>

