<?php

use Application\View\Renderer\PhpRenderer;
use Fichier\Entity\Db\NatureFichier;
use Fichier\Entity\Db\VersionFichier;
use Fichier\Provider\Privilege\FichierPrivileges;
use These\Entity\Db\These;

/**
 * @var PhpRenderer $this
 * @var These $these
 * @var string $uploadUrl
 * @var string $fichiersListUrl
 * @var NatureFichier $nature
 * @var VersionFichier $version
 * @var bool $isVisible
 * @var bool $readonly
 * @var string $message
 * @var int $maxUploadableFilesCount
 */

$readonly = $readonly ?? false;
$canEdit = !$readonly && $this->isAllowed($these, $p = FichierPrivileges::privilegeTeleverserFor($nature, $version));
$maxUploadableFilesCount = $maxUploadableFilesCount ?? 1;
$isVisible = $isVisible ?? true;
$message = $message ?? null;
?>

<div class="box card">
    <div class="card-header bg-dark text-white">
        <h2 class="first"><?php echo $nature ?></h2>
    </div>
    <div class="card-body">
        <?php if ($message !== null): ?>
            <span class="fas fa-info-circle"></span> <?php echo $message ?>
        <?php endif ?>
        <?php if ($isVisible): ?>
            <?php echo $this->partial('depot/depot/depot/partial/fichier', [
                'canUpload' => $canEdit,
                'class' => (new NatureFichier)->setCode($nature->getCode())->getCodeToLowerAndDash(),
                'uploadUrl' => $uploadUrl,
                'uploadedFilesListUrl' => $fichiersListUrl,
                'maxUploadableFilesCount' => $maxUploadableFilesCount,
            ]) ?>
        <?php endif ?>
    </div>
</div>
