<?php

namespace Substitution;

use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var \Doctrine\DBAL\Result $result
 *
 * @see \Substitution\Controller\IndexController::ecoleDoctAction()
 */
?>

<?php echo $this->partial('substitution/doublon/_partial/liste', [
    'type' => 'ecole-doct',
    'result' => $result,
    'attributes' => ['code' => 'Code'],
    'routeName' => 'ecole-doctorale/voir',
    'routeParamName' => 'ecole-doctorale',
]); ?>
