<?php

/**
 * @see PresoutenanceTheseController::presoutenanceAction()
 * @var These\Entity\Db\These $these
 * @var Validation\Entity\Db\Validation $validationBDD
 * @var Soutenance\Entity\PropositionThese $proposition
 * @var ValidationThese $validationPDC
 * @var Membre[] $membres
 * @var ActeurThese[] $acteursMembres
 * @var Membre[] $rapporteurs
 * @var ActeurThese[] $acteursRapporteurs
 * @var ValidationThese[] $engagements
 * @var Avis[] $avis
 * @var Adresse $adresse
 * @var bool $justificatifsOk
 * @var array $justificatifs
 * @var UrlFichierThese $urlFichierThese
 * @var string $typeProposition
 *
 * @var array $documentsLiesSoutenance
 */

use Acteur\Entity\Db\ActeurThese;
use Application\Constants;
use Validation\Entity\Db\ValidationThese;
use Depot\Controller\Plugin\UrlFichierThese;
use Soutenance\Entity\Adresse;
use Soutenance\Entity\Avis;
use Soutenance\Entity\Etat;
use Soutenance\Entity\Justificatif;
use Soutenance\Entity\Membre;
use Soutenance\Provider\Privilege\PresoutenancePrivileges;
use Soutenance\Service\Horodatage\HorodatageService;

$tousLesEngagements = false;
foreach($rapporteurs as $rapporteur) {
//    $individu = $rapporteur->getIndividu();
    $individu = $acteursRapporteurs[$rapporteur->getId()] ?? null;
    $found = false;
    foreach ($engagements as $engagement) {
        if ($engagement->getIndividu() === $individu) {
            $found = true;
            break;
        }
        $tousLesEngagements = $found;
    }
    if ($found === false) {
        $tousLesEngagements = false;
        break;
    }
}

$tousLesAvis = true;
foreach($rapporteurs as $rapporteur) {
// NB : la méthode Membre::getIndividu() a été supprimée (car utilise la relation "acteur" supprimée)
// => le test ci-dessous peut comparer les Membre plutôt que les Individu...
//    $individu = $rapporteur->getIndividu();
    $found = false;
    foreach ($avis as $avi) {
//        if ($avi->getMembre()->getIndividu() === $individu) {
        if ($avi->getMembre() === $rapporteur) {
            $found = true;
            break;
        }
    }
    if ($found === false) {
        $tousLesAvis = false;
        break;
    }
}

$canFeuVert = ($justificatifsOk === true AND $this->isAllowed(PresoutenancePrivileges::getResourceId(PresoutenancePrivileges::PRESOUTENANCE_ASSOCIATION_MEMBRE_INDIVIDU)));
$this->headTitle('Préparation de la soutenance de '.$these->getDoctorant()->getIndividu());
$canModifierAdresse = $canFeuVert;
$canGenererDocument = $canFeuVert;

$canSimulerRemonter = $this->isAllowed(PresoutenancePrivileges::getResourceId(PresoutenancePrivileges::PRESOUTENANCE_SIMULER_REMONTEES));

?>

<h1 class="page-header">
    Préparation de la soutenance
    <small><?php echo $this->partial('these/these/partial/titre') ?></small>
</h1>

<?php echo $this->alertes()
    ->addAlertesFromFlashMessenger()
    ->renderAsBootstrapToasts()
?>

<?php if (! $validationBDD) : ?>

    <p class="lead text-danger">
        La proposition de soutenance n'a pas encore été validée.
    </p>

<?php else: ?>

    <?php if ($canSimulerRemonter) : ?>
        <div>
            <?php /** @see \Soutenance\Controller\PresoutenanceController::genererSimulationAction() */ ?>
            <a href="<?php echo $this->url("soutenance_{$typeProposition}/presoutenance/generer-simulation", ['id' => $these->getId()], [], true); ?>" class="btn btn-warning action text-white">
                Simulation de la remontée SI
            </a>

            <?php /** @see \Soutenance\Controller\PresoutenanceController::nettoyerSimulationAction() */ ?>
            <a href="<?php echo $this->url("soutenance_{$typeProposition}/presoutenance/nettoyer-simulation", ['id' => $these->getId()], [], true); ?>" class="btn btn-warning action text-white">
                Nettoyer la simulation
            </a>
            <br/>
            <br/>
        </div>
    <?php endif; ?>

    <?php if ($proposition->getNouveauTitre() !== null) : ?>
        <div class="box card">
            <div class="card-header bg-warning">
                <h2>
                Une modification de titre a été proposée
                </h2>
            </div>
            <div class="card-body">
                <?php echo $proposition->getNouveauTitre(); ?>
            </div>
        </div>
    <?php endif; ?>

    <?php if ($justificatifsOk !== true) : ?>
        <div class="box card">
            <div class="card-header <?php echo ($justificatifsOk === null)?'bg-warning':'bg-danger'; ?>">
                <h2>
                    Des justificatifs sont manquants
                </h2>
            </div>
            <div class="card-body">
                    <span class="icon icon-warning"></span>
                    Liste des justificatifs manquants :
                <ul>
                    <?php foreach ($justificatifs as $justificatif) : ?>
                        <?php if($justificatif['justificatif'] === null) : ?>
                            <li>
                                <?php echo $justificatif['label'] ?>
                                <?php if (isset($justificatif['membre'])) : ?>
                                    -
                                    <?php
                                    /** @var Membre $membre */
                                    $membre = $justificatif['membre'];
                                    echo $membre->getDenomination();
                                    ?>
                                <?php endif; ?>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    <?php endif; ?>

    <div class="row">
        <div class="col-lg-6">
            <!-- DATE DE RENDU DE RAPPORT ----------------------------------------------------------------------------------------->
            <?php echo $this->partial('soutenance/presoutenance/partial/date-de-retour'); ?>
        </div>
        <div class="col-lg-6">
            <?php if (true): ?>
                <div class="box card">
                    <div class="card-header <?= $proposition->getAdresseActive() ? "bg-success" : "bg-danger"; ?>">
                        <h2>Adresse exacte de la soutenance</h2>
                    </div>
                    <div class="card-body">
                        <?php echo $this->partial('soutenance/presoutenance/partial/adresse', ['proposition' => $proposition, 'typeProposition' => $typeProposition]); ?>
                        <div>
                            <?php echo $this->horodatagesParType($proposition, HorodatageService::TYPE_MODIFICATION, "Adresse du lieu de soutenance"); ?>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>

    <br>
    <div class="separator"></div>
    <br>

    <!-- MEMBRES DU JURY ET PERSOPASS ------------------------------------------------------------------------------------->
    <?php echo $this->partial('soutenance/presoutenance/partial/association-jury'); ?>

    <!-- ENGAGEMENT IMPARTIALITE------------------------------------------------------------------------------------------->
    <?php echo $this->partial('soutenance/presoutenance/partial/engagement-impartialite'); ?>

    <div class="box card">
        <?php
        $ok_rapporteurs = false;
        $tousLesRapporteurs = true;
        foreach ($rapporteurs as $rapporteur) {
            if (($acteursRapporteurs[$rapporteur->getId()] ?? null) === null) {
                $tousLesRapporteurs = false;
                break;
            }
        }
        $tousLesEngagements = !empty($engagements) && count($rapporteurs) === count($engagements) ;
        if($tousLesEngagements && (current($validationPDC) !== null && current($validationPDC) !== false)){
            $cssColor = "bg-success";
        }elseif($tousLesEngagements && (current($validationPDC) === null || current($validationPDC) === false)){
            $cssColor = "bg-warning";
        }else{
            $cssColor = "bg-danger";
        }
        ?>
        <div class="card-header <?= $cssColor ?>">
            <h2>Validation de la page de couverture</h2>
        </div>
        <div class="card-body">
            <?php if ($tousLesEngagements) : ?>
                <?php if (current($validationPDC) !== null AND current($validationPDC) !== false) : ?>
                    <?php
                        /** @var ValidationThese $validation_pdc */
                        $validation_pdc = current($validationPDC);
                    ?>
                    <div class="alert alert-info">
                        <span class="icon icon-ok"></span>
                        La page de couverture a été validée le
                        <?php echo $validation_pdc->getHistoModification()->format(Constants::DATETIME_FORMAT); ?>
                        par
                        <?php echo $validation_pdc->getHistoModificateur()->getDisplayName(); ?>.
                    </div>
                <?php else : ?>
                    <div class="row">
                        <div class="col-md-8">
                            <p>Vous pouvez maintenant valider la page de couverture.</p>
                        </div>
                        <div class="float-end" style="margin-right: 2rem;">
                            <a
                                <?php /** @see \These\Controller\TheseController::validationPageDeCouvertureAction() */ ?>
                                href="<?php echo $this->url('these/validation-page-de-couverture', ['these'=> $these->getId()], [], true); ?>" class="btn btn-primary">
                                Accéder à la validation de la PDC
                            </a>
                        </div>
                    </div>
                <?php endif; ?>
            <?php else : ?>
                <div class="col-md-8">
                    <?php if (empty($rapporteurs)) : ?>
                        <div class="alert alert-warning">
                            <span class="icon icon-attention"></span>
                            Aucun rapporteur déclaré dans la proposition de soutenance
                        </div>
                    <?php else: ?>
                        <div class="alert alert-warning">
                            <span class="icon icon-attention"></span>
                            Tous les engagements d'impartialité n'ont pas encore été signés.
                        </div>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
    <!-- AVIS SOUTENANCE -------------------------------------------------------------------------------------------------->
    <?php echo $this->partial('soutenance/presoutenance/partial/avis-soutenance'); ?>


    <!-- En attente de validation de l'établissement ------------------------------------------------------------------>

<?php
    $bgcolor = "bg-danger";
    $tousLesAvisSontFavorables = count(array_filter($avis, fn($avis) => $avis->getAvis() === 'Favorable')) === count($avis);
    if (!$tousLesAvis || !$tousLesAvisSontFavorables) $bgcolor = "bg-danger";
    else {
        switch ($proposition->getEtat()->getCode()) {
            case Etat::VALIDEE :
            case Etat::COMPLET :
                $bgcolor = "bg-success";
                break;
            case Etat::REJETEE :
                $bgcolor = "bg-danger";
                break;
        }
    }
?>

    <div class="box card">
        <div class="card-header <?php echo $bgcolor; ?> text-white">
            <h2>Complétion du dossier et validation de l'établissement</h2>
        </div>
        <div class="card-body">
            <?php if ($proposition->getEtat()->getCode() === Etat::ETABLISSEMENT) : ?>

                <p class="lead">
                    Pour permettre de faire avancer le dossier, veuillez vérifier que les rapports de pré-soutenance sont valides.
                </p>

                <?php if (count($avis) === 0 || !$tousLesAvis) : ?>
                    <div class="alert alert-warning" style="margin-left: 1rem !important;">
                        <span class="icon icon-attention"></span>
                        Tous les rapports n'ont pas été rendus.
                    </div>
                <?php else : ?>
                    <?php if (!$tousLesAvisSontFavorables) : ?>
                        <div class="alert alert-warning">
                            <span class="icon icon-attention"></span>
                            Tous les rapports doivent être favorables pour déclarer le dossier comme complet.
                        </div>
                    <?php else : ?>
                        <?php /** @see PresoutenanceController::indiquerDossierCompletAction() */ ?>
                        <a href="<?php echo $this->url("soutenance_{$typeProposition}/presoutenance/indiquer-dossier-complet", ['id' => $these->getId()], [], true); ?>"
                           class="btn btn-success"
                        >
                            <span class="icon icon-checked"></span>
                            Dossier complet
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
            <?php elseif($proposition->getEtat()->getCode() === Etat::EN_COURS): ?>
                <p class="lead">
                    La direction de l'établissement n'a pas encore validé la proposition de soutenance
                </p>
            <?php endif; ?>

            <?php if ($proposition->getEtat()->getCode() === Etat::COMPLET || $proposition->getEtat()->getCode() === Etat::VALIDEE) : ?>
                <span class="badge bg-success text-white" style="margin-left: 1rem !important; font-size: unset;">
                        <span class="icon icon-checked"></span>
                        Dossier complet
                    </span>
            <?php elseif($proposition->getEtat()->getCode() === Etat::REJETEE): ?>
                <span class="badge bg-danger text-white" style="margin-left: 1rem !important; font-size: unset;">
                    <span class="icon icon-checked"></span>
                        Dossier incomplet
                </span>
            <?php endif; ?>

            <?php echo $this->horodatagesParType($proposition, HorodatageService::TYPE_ETAT, "Dossier complet"); ?>
        </div>
    </div>

    <!-- Feu vert ----------------------------------------------------------------------------------------------------->

    <?php
    $bgcolor = "bg-danger";
    if (!$tousLesAvis) $bgcolor = "bg-danger";
    else {
        switch ($proposition->getEtat()->getCode()) {
            case Etat::VALIDEE :
                $bgcolor = "bg-success";
                break;
            case Etat::REJETEE :
                $bgcolor = "bg-danger";
                break;
        }
    }
    ?>

    <div class="box card">
        <div class="card-header <?php echo $bgcolor; ?> text-white">
            <h2>  Validation finale de la proposition de soutenance </h2>
        </div>
        <div class="card-body">

            <p class="lead"> Le feu vert pour la soutenance ne peut être donné qu'une fois le dossier complet et validé par l'établissement. </p>
            <?php if ($canFeuVert) : ?>
                <?php if($proposition->getEtat()->getCode() === Etat::COMPLET) :?>
                    <?php /** @see \Soutenance\Controller\PresoutenanceController::feuVertAction() */ ?>
                    <a href="<?php echo $this->url("soutenance_{$typeProposition}/presoutenance/feu-vert", ['id' => $these->getId()], [], true); ?>"
                        class="btn btn-success action"
                    >
                        <span class="fas fa-thumbs-up"></span>
                        Donner le feu vert
                    </a>

                    <?php /** @see \Soutenance\Controller\PresoutenanceController::stopperDemarcheAction() */ ?>
                    <a href="<?php echo $this->url("soutenance_{$typeProposition}/presoutenance/stopper-demarche", ['id' => $these->getId()], [], true); ?>"
                       class="btn btn-danger action ajax-modal" data-event="annuler-soutenance"
                    >
                        <span class="fas fa-thumbs-down"></span>
                        Annuler/Rejeter la proposition de soutenance
                    </a>
                <?php endif; ?>
            <?php endif ?>

            <?php echo $this->horodatagesParTypes($proposition, [
                [HorodatageService::TYPE_ETAT, "Annulation de la soutenance"],
                [HorodatageService::TYPE_ETAT, "Feu vert pour la soutenance"],
            ]); ?>

            <?php if ($proposition->getEtat()->getCode() === Etat::VALIDEE) : ?>
                <div class="bg-success text-white" style="padding-left:1rem; font-size: x-large; "> Soutenance autorisée </div>
            <?php endif; ?>
            <?php if ($proposition->getEtat()->getCode() === Etat::REJETEE) : ?>
                <div class="bg-danger text-white" style="padding-left:1rem; font-size: x-large; "> Soutenance rejetée </div>
            <?php endif; ?>
        </div>
    </div>

    <br>
    <div class="separator"></div>
    <br>

    <!-- DOCUMENT ----------------------------------------------------------------------------------------------------->
    <?php echo $this->partial('soutenance/presoutenance/partial/documents',
        [
            'documentsLiesSoutenance' => $documentsLiesSoutenance,
            'proposition' => $proposition,
            'urlFichier' => $urlFichierThese,
            'typeProposition' => $typeProposition,
            'canGenererDocument' => $canGenererDocument,
        ]
    ); ?>

<?php endif; ?>

<style>
    div.adresse-block {
        border-left: 2px gray solid;
        padding: 0.5rem;
    }
</style>

<script>
    $(function() {
        $("body").on("annuler-soutenance", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });

    $(function() {
        $("body").on("modification-date-rendu-rapport", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });

    $(function() {
        $("body").on("modification-association-jury", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });

    $(function() {
        $("body").on("modification-adresse", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>