<?php
/**
 * @var string[] $infos
 * @var \StepStar\Entity\Db\Log $lastLog
 *
 * @see \StepStar\Controller\IndexController::infosAction()
 */

use Application\Constants;

?>

<h1 class="page-header">Module STEP-STAR</h1>

<div class="row">

    <div class="col-md-6">

        <h2>Config</h2>

        <dl>
            <?php foreach ($infos as $k => $v): ?>
                <dt><?php echo $k ?></dt>
                <dd><?php echo $v ?></dd>
            <?php endforeach; ?>
        </dl>

    </div>

    <div class="col-md-6">

        <h2>Dernier log</h2>

        <?php if ($lastLog !== null): ?>
            <dl>
                <dt>Id</dt>
                <dd>
                    <a href="<?php echo $this->url('step-star/log/consulter', ['log' => $lastLog->getId()]) ?>"
                       title="Voir les détails de ce log"><?php echo $lastLog->getId() ?></a>
                </dd>
                <dt>Début - Fin</dt>
                <dd>
                    <?php echo $lastLog->getStartedOn()->format(Constants::DATETIME_FORMAT) ?> -
                    <?php echo $lastLog->getEndedOn()->format(Constants::DATETIME_FORMAT) ?>
                </dd>
                <dt>Succès ?</dt>
                <dd>
                    <?php if ($lastLog->isSuccess()): ?>
                        <span class="icon iconly icon-success text-success"></span>
                    <?php else: ?>
                        <span class="icon iconly icon-failure text-danger"></span>
                    <?php endif ?>
                </dd>
            </dl>

        <?php else: ?>

            Aucun.

        <?php endif ?>
    </div>

</div>