<?php

use Application\Entity\Db\Acteur;
use Application\Entity\Db\These;
use Application\View\Renderer\PhpRenderer;

/**
 * @see \Application\Service\CoEncadrant\Exporter\JustificatifCoencadrements\JustificatifCoencadrementPdfExporter
 * @var PhpRenderer             $this
 * @var Acteur $coencadrant
 * @var These[] $theses
 * @var array $logos
 */
?>

<style>
    body {
        font-size: 9pt;
    }

    span.warning {
        font-weight: bold;
        color: darkred;
    }

    img {
        height:2.5cm;
    }

    h1 {
        font-size: x-large;
    }
    h2 {
        font-size: large;
    }
    table {
        width:100%;
    }

    table.recapitulatif {
        border:solid 1px black;
    }

    table.recapitulatif td.head {
        font-weight: bold;
        width: 33.3%
    }

    table.composition {
        border-collapse: collapse;
    }

    table.composition th{
        border-bottom:solid 2px black;
    }

    table.composition td{
        border-bottom:solid 1px gray;
    }

    table.composition tbody tr {
        border-bottom: 1px gray solid ;
    }

    table.informations {
    }

    table.informations td.head {
        width: 50%
    }

    table.informations td.info {
        text-align: right;
    }

    table.validation {
        border-collapse: collapse;
    }

    table.validation th{
        border-bottom:solid 2px black;
    }

    table.validation td{
        border-bottom:solid 1px gray;
        margin: 1rem;
    }

    span.to-complete {
        background-color: pink;
        color: darkred;
    }

    div.signature {
        position:relative;
        /*top: 80%;*/
        left:500px;
    }

</style>

<!-- SECTION DU LOGO DE LA COMUE -------------------------------------------------------------------------------------->

<div>
    <div style="width:25%; position:absolute; top: 20px; left: 20px ">
        <?php if ($logos['etablissement'] !== null): ?>
            <img src="<?php echo $logos['etablissement']; ?>" />
        <?php else : ?>
        <span style='background-color:red;'>
                Logo ETAB manquant
        </span>
        <?php endif; ?>
    </div>

    <h1 style="text-align:center; position:absolute; top: 60px; left: 30%" >
        Justificatif de co-encadrements
    </h1>
</div>

<!-- Presentation du co-encdrant -------------------------------------------------------------------------------------->

<p>
    Ce document certifie que <?php echo $coencadrant->getIndividu()->getPrenom1(); ?> <?php echo $coencadrant->getIndividu()->getNomUsuel(); ?>,
    actuellement <?php echo ($coencadrant->getQualite() !== " ")?$coencadrant->getQualite():""; ?> à
    <?php echo ($coencadrant->getEtablissement())?$coencadrant->getEtablissement()->getLibelle():"<span style='color:darkred;'>établissement manquant</span>"; ?>,
    a assuré la fonction de co-encadrant sur pour les thèses suivantes :
</p>

<ul>
<?php foreach ($theses as $these) : ?>
    <li>
        <?php echo $these->getTitre(); ?>
        (<?php echo $these->getAnneeUniv1ereInscription(); ?>)
        <br/>
        <?php echo $these->getDoctorant()->getIndividu()->getPrenom1(); ?>
        <?php echo $these->getDoctorant()->getIndividu()->getNomUsuel(); ?>
        -
        <?php echo $these->getEtablissement()->getLibelle(); ?>
        -
        <?php echo $these->getUniteRecherche()->getLibelle(); ?> (<?php echo $these->getUniteRecherche()->getSigle(); ?>)
    </li>
<?php endforeach; ?>
</ul>

<!--<br/>-->
<!--<br/>-->
<!--<br/>-->
<!--<br/>-->
<!---->
<!--<h2 style="text-align:center;">-->
<!--    Désignation des rapporteurs et des membres du jury-->
<!--    <br/>-->
<!--    Autorisation de soutenance de doctorat-->
<!--    <br/>-->
<!--    Avis de soutenance-->
<!--</h2>-->
<!---->
<!--    <br/>-->
<!--    <br/>-->
<!---->
<!--<p>-->
<!--    <strong>-->
<!--    --><?php //if ($informations->getDoctorant() !== null): ?>
<!--        --><?php //echo $informations->getDoctorant(); ?>
<!--    --><?php //else : ?>
<!--        <span style='background-color:red;'>-->
<!--                Doctorant manquant-->
<!--        </span>-->
<!--    --><?php //endif; ?>
<!--    </strong>-->
<!--    présente ses travaux en soutenance le-->
<!--    <strong>-->
<!--    --><?php //if ($informations->getDate() !== null): ?>
<!--        --><?php //echo $informations->getDate(); ?>
<!--    --><?php //else : ?>
<!--        <span style='background-color:red;'>-->
<!--                Date manquante-->
<!--        </span>-->
<!--    --><?php //endif; ?>
<!--    </strong>-->
<!--    à l'adresse suivante : <br/>-->
<!--    --><?php //if ($proposition->getAdresse() !== null): ?>
<!--        --><?php //echo $proposition->getAdresse(); ?>
<!--    --><?php //else : ?>
<!--        <span style='background-color:red;'>-->
<!--                    Adresse manquante-->
<!--            </span>-->
<!--        <br/>-->
<!--    --><?php //endif; ?>
<!--    en vue de l'obtention du diplôme de <strong>Doctorat spécialité-->
<!---->
<!--    --><?php //if ($informations->getSpecialite() !== null): ?>
<!--        --><?php //echo $informations->getSpecialite(); ?><!--.-->
<!--    --><?php //else: ?>
<!--        <span style='background-color:red;'> Spécialité manquante. </span>-->
<!--    --><?php //endif; ?>
<!--    </strong>-->
<!--</p>-->
<!---->
<!--<p>-->
<!--    La soutenance-->
<!--    --><?php //if ($proposition && $proposition->isHuitClos() !== null): ?>
<!--        --><?php //if ($proposition->isHuitClos()) : ?>
<!--            se déroulera en huis clos.-->
<!--        --><?php //else : ?>
<!--            est public.-->
<!--        --><?php //endif ; ?>
<!--    --><?php //else: ?>
<!--        <span style='background-color:red;'> information sur l'aspect public manquante </span>-->
<!--    --><?php //endif; ?>
<!--</p>-->
<!---->
<!--<br/>-->
<!--<br/>-->
<!---->
<!--    <table class='jury'>-->
<!--    <tr>-->
<!--        <th colspan='3'>-->
<!--            Information sur la thèse-->
<!--        </th>-->
<!--    </tr>-->
<!--    <tr>-->
<!--        <td>Titre :</td>-->
<!--        <td>-->
<!--            --><?php //if ($informations->getTitre() !== null): ?>
<!--                --><?php //echo $informations->getTitre(); ?>
<!--            --><?php //else: ?>
<!--                <span style='background-color:red;'> Aucun titre </span>-->
<!--            --><?php //endif; ?>
<!--        </td>-->
<!--    </tr>-->
<!--    <tr>-->
<!--        <td>École doctorale </td>-->
<!--        <td>-->
<!--            --><?php //if ($informations->getEcoleDoctorale() !== null): ?>
<!--                --><?php //echo $informations->getEcoleDoctorale(); ?>
<!--            --><?php //else: ?>
<!--                <span style='background-color:red;'> École doctorale manquante</span>-->
<!--            --><?php //endif; ?>
<!--        </td>-->
<!--    </tr>-->
<!--    <tr>-->
<!--        <td>Unité de recherche </td>-->
<!--        <td>-->
<!--            --><?php //if ($informations->getUniteRecherche() !== null): ?>
<!--                --><?php //echo $informations->getUniteRecherche(); ?>
<!--            --><?php //else: ?>
<!--                <span style='background-color:red;'> Unité de recherche manquante</span>-->
<!--            --><?php //endif; ?>
<!--        </td>-->
<!--    </tr>-->
<!--    --><?php
//        /**
//         * @var Acteur[] $directeurs
//         * @var Acteur[] $codirecteurs
//         */
//        $directeurs = $informations->getDirecteurs();
//        $codirecteurs = $informations->getCodirecteurs();
//    ?>
<!---->
<!--    <tr>-->
<!--        <td>Directeur :</td>-->
<!--        <td>-->
<!--            --><?php //$first = true; ?>
<!--            --><?php //foreach ($directeurs as $directeur) : ?>
<!--                --><?php //if (!$first): ?>
<!--                    <br/>-->
<!--                --><?php //endif; ?>
<!--                --><?php
//                    $first = false;
//                    $denomination = $directeur->getIndividu()->getNomComplet(true, true, false, true);
//                    $qualite = $directeur->getQualite();
//                ?>
<!--                --><?php //echo  $denomination . ", ".$qualite; ?>
<!--            --><?php //endforeach; ?>
<!--        </td>-->
<!--    </tr>-->
<!--    --><?php //if (!empty($informations->getCodirecteurs())) : ?>
<!--    <tr>-->
<!--        <td>Co-directeur(s) :</td>-->
<!--        <td>-->
<!--            --><?php //$first = true; ?>
<!--            --><?php //foreach ($codirecteurs as $directeur) : ?>
<!--                --><?php //if (!$first): ?>
<!--                    <br/>-->
<!--                --><?php //endif; ?>
<!--                --><?php
//                $first = false;
//                $denomination = $directeur->getIndividu()->getNomComplet(true, true, false, true);
//                $qualite = $directeur->getQualite();
//                ?>
<!--                --><?php //echo  $denomination . ", ".$qualite; ?>
<!--            --><?php //endforeach; ?>
<!--        </td>-->
<!--    </tr>-->
<!--    --><?php //endif; ?>
<!--</table>-->
<!---->
<!--<br/>-->
<!--<br/>-->

    <!-- SECTION JURY ----------------------------------------------------------------------------------------------------->

<!--    <table class='jury'>-->
<!--        <tr>-->
<!--            <th colspan='3'>-->
<!--                Composition du jury-->
<!--            </th>-->
<!--        </tr>-->
<!---->
<!--        --><?php //foreach ($informations->getActeursEnCouverture() as $acteur) : ?>
<!--            <tr>-->
<!--                <td> --><?php //echo $acteur->getDenomination(); ?><!-- </td>-->
<!--                <td> --><?php //echo trim($acteur->getQualite()); ?><!--,  --><?php //echo $acteur->getEtablissement(); ?><!--</td>-->
<!--                <td> --><?php //echo $acteur->getRole(); ?><!-- </td>-->
<!--            </tr>-->
<!--        --><?php //endforeach; ?>
<!---->
<!--    </table>-->
<!---->
<!---->
<!--<br/>-->
<!--<br/>-->

    <!-- Signature ---------------------------------------------------------------------------------------------------->

<!--<table>-->
<!--    <tr>-->
<!--        <td width="60%"></td>-->
<!--        <td>-->
<!--            Fait à ................., le ........................<br/>-->
<!--            Pour le Président et p.o.<br/>-->
<!--            Le Vice-Président Recherche-->
<!--        </td>-->
<!--    </tr>-->
<!--</table>-->

