<?php

use Application\Entity\AnneeUniv;
use Application\View\Renderer\PhpRenderer;
use Fichier\Controller\Plugin\UrlFichier;
use Formation\Entity\Db\Formation;
use Formation\Entity\Db\Seance;
use Formation\Entity\Db\Session;
use Formation\Provider\Privilege\FormationPrivileges;
use Formation\Provider\Privilege\ModulePrivileges;
use Formation\Provider\Privilege\SessionPrivileges;

/**
 * @var PhpRenderer $this
 * @see \Formation\Controller\FormationController::afficherAction()
 * @var Formation $formation
 * @var Session[] $sessions
 * @var array $anneesUniv
 * @var AnneeUniv $anneeUnivCourante
 * @var UrlFichier $urlFichierPlugin
 */

$pageTitle = '' . $formation->getLibelle();
$this->headTitle($pageTitle);

$canAfficherModule      = $this->isAllowed(ModulePrivileges::getResourceId(ModulePrivileges::MODULE_AFFICHER));

$canIndexFormation      = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::FORMATION_INDEX));
$canModifierFormation   = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::FORMATION_MODIFIER));

$canAfficherSession     = $this->isAllowed(SessionPrivileges::getResourceId(SessionPrivileges::SESSION_AFFICHER));
$canAjouterSession      = $this->isAllowed(SessionPrivileges::getResourceId(SessionPrivileges::SESSION_AJOUTER));
$canHistoriserSession   = $this->isAllowed(SessionPrivileges::getResourceId(SessionPrivileges::SESSION_HISTORISER));
$canSupprimerSession    = $this->isAllowed(SessionPrivileges::getResourceId(SessionPrivileges::SESSION_SUPPRIMER));
echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace();

?>

<h1 class="page-header">
    <?php echo $pageTitle; ?>
</h1>

<div style="display: flex; gap: 2px;">
    <?php if ($canIndexFormation) : ?>
        <?php /** @see \Formation\Controller\FormationController::indexAction() */?>
        <a class="btn btn-primary action"
           href="<?php echo $this->url('formation/formation', [], [], true); ?>"
        >
            <span class="icon icon-retour"></span>
            Retourner à la liste des formations
        </a>
    <?php endif; ?>

    <?php if ($canIndexFormation && $canModifierFormation) : ?>
        <div class="separator-vertical"></div>
    <?php endif; ?>

    <?php if ($canModifierFormation) : ?>
        <?php /** @see \Formation\Controller\FormationController::modifierAction() */?>
        <a class="btn btn-primary action ajax-modal" data-event="modification"
           href="<?php echo $this->url('formation/formation/modifier', ['formation' => $formation->getId()], [], true); ?>"
        >
            <span class="icon icon-modifier"></span>
            Modifier les informations
        </a>
    <?php endif; ?>
</div>

<h2> Informations sur la formation </h2>

<dl class="row">
    <dt class="col-md-3"> Module </dt>
    <dd class="col-md-9">
        <?php if($formation->getModule()) : ?>
            <?php if ($canAfficherModule) : ?>
                <a href="<?php echo $this->url('formation/module/afficher', ['module' => $formation->getModule()->getId() ], [], true); ?>"
                   title="Accéder au module <strong><?php echo $formation->getModule()->getLibelle(); ?></strong>" data-bs-toggle='tooltip' data-bs-html='true'
                >
                    <?php echo $formation->getModule()->getLibelle(); ?></a>
            <?php else : ?>
                <?php echo $formation->getModule()->getLibelle(); ?>
            <?php endif; ?>
        <?php else : ?>
            <i>Aucun module associé à cette formation</i>
        <?php endif; ?>
    </dd>
    <dt class="col-md-3"> Formation </dt>
    <dd class="col-md-9"> <?php echo $formation->getLibelle(); ?> </dd>
    <?php if ($formation->getDescription()) : ?>
        <dt class="col-md-3"> Description de la formation </dt>
        <dd class="col-md-9"> <?php echo $formation->getDescription(); ?> </dd>
    <?php endif ?>
    <dt class="col-md-3"> Code </dt>
    <dd class="col-md-9"> <code><?php echo $formation->getCode(); ?></code></dd>
    <?php if ($formation->getFiche()) : ?>
        <dt class="col-md-3"> Fiche </dt>
        <dd class="col-md-9">
            <?php echo $this->fichier($formation->getFiche(),
                $this->url('formation/formation/telecharger-fiche', ["formation"=> $formation->getId()],[], true),
                $this->url('formation/formation/supprimer-fiche', ["formation"=>$formation->getId(), "fichier" => $formation->getFiche()->getId()], ['query' => ['redirect' => $this->url('formation/formation/afficher', ["formation" => $formation->getId()])]], true),
                $canModifierFormation,
                "Fiche de la formation",
                false,
                false
            ); ?>
        </dd>
    <?php else: ?>
        <?php if ($formation->getLien()) : ?>
            <dt class="col-md-3"> Lien vers la fiche </dt>
            <dd class="col-md-9"> <a href="<?php echo $formation->getLien(); ?>" target="_blank"><?php echo $formation->getLien(); ?></a> </dd>
        <?php endif ?>
    <?php endif ?>
    <?php if ($formation->getObjectif() !== null) : ?>
        <dt class="col-md-3">Objectif </dt>
        <dd class="col-md-9">
                <?php echo $formation->getObjectif(); ?>
        </dd>
    <?php endif; ?>
    <?php if ($formation->getProgramme() !== null) : ?>
        <dt class="col-md-3">Programme </dt>
        <dd class="col-md-9">
            <?php echo $formation->getProgramme(); ?>
        </dd>
    <?php endif; ?>
</dl>

<h2> Valeurs par défaut transmises aux sessions </h2>

<dl class="row">
    <?php if ($formation->getSite()) : ?>
        <dt class="col-md-3"> Établissement organisateur</dt>
        <dd class="col-md-9"> <?php echo $this->site($formation); ?> </dd>
    <?php endif; ?>
    <?php if ($formation->getResponsable()) : ?>
        <dt class="col-md-3"> Responsable</dt>
        <dd class="col-md-9"> <?php echo $formation->getResponsable()->getNomComplet(); ?> </dd>
    <?php endif; ?>
    <?php if ($formation->getModalite()) : ?>
        <dt class="col-md-3"> Modalité</dt>
        <dd class="col-md-9"> <?php echo $this->modalite($formation); ?> </dd>
    <?php endif; ?>
    <?php if ($formation->getType()) : ?>
        <dt class="col-md-3"> Type</dt>
        <dd class="col-md-9"> <?php echo $this->type($formation); ?> </dd>
    <?php endif; ?>
    <?php if ($formation->getTailleListePrincipale()) : ?>
        <dt class="col-md-3"> Effectif de la liste principale </dt>
        <dd class="col-md-9"> <?php echo $formation->getTailleListePrincipale(); ?> </dd>
    <?php endif; ?>
    <?php if ($formation->getTailleListeComplementaire()) : ?>
        <dt class="col-md-3"> Effectif de la liste complémentaire </dt>
        <dd class="col-md-9"> <?php echo $formation->getTailleListeComplementaire(); ?> </dd>
    <?php endif; ?>
</dl>

<h2> Liste des sessions </h2>

<div class="row">
    <div class="col-md-12">

        <?php if ($canAjouterSession) : ?>
            <?php /** @see \Formation\Controller\SessionController::ajouterAction() */ ?>
            <a href="<?php echo $this->url('formation/session/ajouter', ['formation' => $formation->getId()], [], true); ?>"
               class="btn btn-primary action ajax-modal" data-event="modification"
               title="Ajouter une session"
               data-bs-toggle="tooltip" data-bs-html="true">
                <span class="icon icon-ajouter"></span>
                Ajouter une session
            </a>
        <?php endif; ?>

        <div class="float-end">
            <label for="annee"> Filtre sur l'année :</label>
            <select id="annee" name="annee">
                <?php foreach($anneesUniv as $annee => $anneeUniv) : ?>
                    <option value="<?php echo $annee; ?>" <?php if ($annee === $anneeUnivCourante->getPremiereAnnee()) echo " selected "; ?> ><?php echo $anneeUniv; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
</div>

<div class="index-result">
    <?php if (empty($sessions)) : ?>
    Aucune session d'associée à cette formation.
<?php else : ?>
    <table class="table table-sm table-hover">
    <thead>
    <tr>
        <th>Index</th>
        <th>Établissement organisateur</th>
        <th>Responsable</th>
        <th>Modalité</th>
        <th>Type</th>
        <th>État</th>
        <th>Séances</th>
        <?php if ($canAfficherSession || $canSupprimerSession || $canHistoriserSession) : ?>
            <th>Action</th>
        <?php endif; ?>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($sessions as $session) :
        if($session["session"]->estVisible()) : ?>
            <tr class="<?php echo $session["anneeUniv"]; ?>">
        <?php else: ?>
            <tr class="session-non-visible <?php echo $session["anneeUniv"]; ?>" data-bs-toggle="tooltip"
            title="Cette session est cachée aux doctorants jusqu'au <?= $session["session"]->getDatePublication()?->format('d/m/Y'); ?>">
        <?php endif; ?>
            <td>
                <span class=" <?php if ($session["session"]->estHistorise()) echo "historise text-danger"; ?> ">
                <?php echo $session["session"]->getIndex(); ?>
                </span>
            </td>
            <td> <?php echo $this->site($session["session"]); ?> </td>
            <td>
                <?php if ($session["session"]->getResponsable()) : ?>
                    <?php echo $session["session"]->getResponsable()->getNomComplet(); ?>
                <?php else : ?>
                    Aucun responsable
                <?php endif; ?>
            </td>
            <td> <?php echo $this->modalite($session["session"]); ?> </td>
            <td> <?php echo $this->type($session["session"]); ?> </td>
            <td> <?php echo $this->etat($session["session"]); ?></td>
            <td>
                <?php echo count($session["session"]->getSeances()); ?>
                séance<?php if (count($session["session"]->getSeances())>1) echo "s"; ?>
                -
                <?php echo $session["session"]->getDuree(); ?> h.
                <ul>
                <?php
                /** @var Seance[] $seances */
                $seances = $session["session"]->getSeances()->toArray();
                usort($seances, function (Seance $a, Seance $b) { return $a->getDebut() > $b->getDebut();});
                ?>
                <?php foreach ($seances as $seance) : ?>
                    <?php /** @var Seance $seance*/?>
                    <li>
                        <?php echo $seance->getDebut()->format('d/m/Y'); ?>
                        <?php echo $seance->getDebut()->format('H:i'); ?>
                        &rightarrow;
                        <?php echo $seance->getFin()->format('H:i'); ?>
                    </li>
                <?php endforeach;?>
                </ul>
            </td>
            <td>
                <?php if ($canAfficherSession) : ?>
                    <?php /** @see \Formation\Controller\SessionController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('formation/session/afficher', ['session' => $session["session"]->getId()], [], true); ?>">
                        <span class="icon icon-voir"></span>
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriserSession) : ?>
                    <?php if ($session["session"]->estNonHistorise()) : ?>
                        <?php /** @see \Formation\Controller\SessionController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('formation/session/historiser', ['session' => $session["session"]->getId()], ['query' => ['retour' => $this->url('formation/formation/afficher', ['formation' => $formation->getId()], [], true)]], true); ?>"
                           data-toggle="confirmationx"
                           data-bs-toggle="tooltip"
                           data-bs-html="true"
                           title="Une confirmation avant l'historisation vous sera demandée"
                        >
                            <span class="icon icon-historiser"></span>
                        </a>
                    <?php else : ?>
                        <?php /** @see \Formation\Controller\SessionController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url('formation/session/restaurer', ['session' => $session["session"]->getId()], ['query' => ['retour' => $this->url('formation/formation/afficher', ['formation' => $formation->getId()], [], true)]], true); ?>"
                        >
                            <span class="icon icon-restaurer"></span>
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canSupprimerSession AND $session["session"]->estHistorise()) : ?>
                    <?php /** @see \Formation\Controller\SessionController::supprimerAction() */ ?>
                    <a href="<?php echo $this->url('formation/session/supprimer', ['session' => $session["session"]->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification"
                       title="Supprimer une session <br>(Une confirmation avant la suppression vous sera demandée)"
                       data-bs-toggle="tooltip" data-bs-html="true">
                        <span class="icon icon-detruire text-danger"></span>
                    </a>
                <?php endif; ?>

            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>
</div>


<script>
    function toggleAnnee() {
        let anneeSelected = $('#annee option:selected').val();
        // alert(anneeSelected);
        $('tbody tr').hide();
        $('tbody tr.' + anneeSelected).show();
    }

    $(function() {
        toggleAnnee();
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });

        $("select#annee").on("change", toggleAnnee).selectpicker();
    });
</script>