<?php

use Formation\Entity\Db\Formation;
use Formation\Entity\Db\Seance;
use Formation\Entity\Db\Session;
use Formation\Provider\Privilege\FormationPrivileges;
use Formation\Provider\Privilege\ModulePrivileges;
use Formation\Provider\Privilege\SessionPrivileges;

/**
 * @see \Formation\Controller\FormationController::afficherAction()
 * @var Formation $formation
 */

$pageTitle = '' . $formation->getLibelle();
$this->headTitle($pageTitle);

$canAfficherModule      = $this->isAllowed(ModulePrivileges::getResourceId(ModulePrivileges::MODULE_AFFICHER));

$canIndexFormation      = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::FORMATION_INDEX));
$canModifierFormation   = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::FORMATION_MODIFIER));

$canAfficherSession     = $this->isAllowed(SessionPrivileges::getResourceId(SessionPrivileges::SESSION_AFFICHER));
$canAjouterSession      = $this->isAllowed(SessionPrivileges::getResourceId(SessionPrivileges::SESSION_AJOUTER));
$canHistoriserSession   = $this->isAllowed(SessionPrivileges::getResourceId(SessionPrivileges::SESSION_HISTORISER));
$canSupprimerSession    = $this->isAllowed(SessionPrivileges::getResourceId(SessionPrivileges::SESSION_SUPPRIMER));

/** @var Session[] $sessions */
$sessions = $formation->getSessions()->toArray();
usort($sessions, function(Session $a, Session $b) { return $a->getIndex() > $b->getIndex();});
?>

<h1 class="page-header">
    <?php echo $pageTitle; ?>
</h1>

<div class="row">
    <div class="col-md-8">

        <h2> Informations sur la formation </h2>

        <dl class="row">
            <dt class="col-md-3"> Module </dt>
            <dd class="col-md-9">
                <?php if($formation->getModule()) : ?>
                    <?php echo $formation->getModule()->getLibelle(); ?>
                <?php else : ?>
                    <i>Aucun module associé à cette formation</i>
                <?php endif; ?>
            </dd>
            <dt class="col-md-3"> Formation </dt>
            <dd class="col-md-9"> <?php echo $formation->getLibelle(); ?> </dd>
            <?php if ($formation->getDescription()) : ?>
                <dt class="col-md-3"> Description de la formation </dt>
                <dd class="col-md-9"> <?php echo $formation->getDescription(); ?> </dd>
            <?php endif ?>
            <?php if ($formation->getLien()) : ?>
                <dt class="col-md-3"> Lien vers de la fiche </dt>
                <dd class="col-md-9"> <a href="<?php echo $formation->getLien(); ?>" target="_blank"><?php echo $formation->getLien(); ?></a> </dd>
            <?php endif ?>
        </dl>

        <h2> Valeurs par défaut transmises aux sessions </h2>

        <dl class="row">
            <?php if ($formation->getSite()) : ?>
                <dt class="col-md-3"> Site organisateur</dt>
                <dd class="col-md-9"> <?php echo $this->site($formation); ?> </dd>
            <?php endif; ?>
            <?php if ($formation->getResponsable()) : ?>
                <dt class="col-md-3"> Responsable</dt>
                <dd class="col-md-9"> <?php echo $formation->getResponsable()->getNomComplet(); ?> </dd>
            <?php endif; ?>
            <?php if ($formation->getModalite()) : ?>
                <dt class="col-md-3"> Modalité</dt>
                <dd class="col-md-9"> <?php echo $this->modalite($formation); ?> </dd>
            <?php endif; ?>
            <?php if ($formation->getType()) : ?>
                <dt class="col-md-3"> Type</dt>
                <dd class="col-md-9"> <?php echo $this->type($formation); ?> </dd>
            <?php endif; ?>
            <?php if ($formation->getTailleListePrincipale()) : ?>
                <dt class="col-md-3"> Effectif de la liste principale </dt>
                <dd class="col-md-9"> <?php echo $formation->getTailleListePrincipale(); ?> </dd>
            <?php endif; ?>
            <?php if ($formation->getTailleListeComplementaire()) : ?>
                <dt class="col-md-3"> Effectif de la liste complémentaire </dt>
                <dd class="col-md-9"> <?php echo $formation->getTailleListeComplementaire(); ?> </dd>
            <?php endif; ?>
        </dl>
    </div>

    <div class="col-md-4">
        <?php if ($canIndexFormation) : ?>
            <?php /** @see \Formation\Controller\FormationController::indexAction() */?>
            <a class="btn btn-primary action"
               href="<?php echo $this->url('formation/formation', [], [], true); ?>"
            >
                <span class="icon icon-chevron-up"></span>
                Retour à la liste des formations
            </a>
            <br/>
            <br/>
            <?php if ($canAfficherModule AND $formation->getModule() !== null) : ?>
                <?php /** @see \Formation\Controller\ModuleController::afficherAction() */?>
                <a class="btn btn-primary action"
                   href="<?php echo $this->url('formation/module/afficher', ['module' => $formation->getModule()->getId() ], [], true); ?>"
                >
                    <span class="fas fa-share-alt"></span>
                    Accéder au module
                </a>
                <br/>
                <br/>
            <?php endif; ?>
        <?php endif; ?>

        <?php if ($canModifierFormation) : ?>
            <?php /** @see \Formation\Controller\FormationController::modifierAction() */?>
            <a class="btn btn-primary action ajax-modal" data-event="modification"
               href="<?php echo $this->url('formation/formation/modifier', ['formation' => $formation->getId()], [], true); ?>"
            >
                <span class="icon icon-modifier"></span>
                Modifier les informations
            </a>
        <br/>
        <br/>
        <?php endif; ?>
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        <h2> Liste des sessions </h2>
    </div>
    <div class="col-md-4">
        <?php if ($canAjouterSession) : ?>
            <?php /** @see \Formation\Controller\SessionController::ajouterAction() */ ?>
            <a href="<?php echo $this->url('formation/session/ajouter', ['formation' => $formation->getId()], [], true); ?>"
               class="btn btn-primary action ajax-modal" data-event="modification"
               title="Ajouter une session"
               data-bs-toggle="tooltip" data-bs-html="true">
                <span class="icon icon-ajouter"></span>
                Ajouter une session
            </a>
        <?php endif; ?>
    </div>
</div>

<?php if (empty($sessions)) : ?>
Aucune session d'associée à cette formation.
<?php else : ?>
    <table class="table table-sm table-hover">
    <thead>
    <tr>
        <th>Index</th>
        <th>Site</th>
        <th>Responsable</th>
        <th>Modalité</th>
        <th>Type</th>
        <th>État</th>
        <th>Séances</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($sessions as $session) : ?>
        <tr>
            <td> <?php echo $session->getIndex(); ?> </td>
            <td> <?php echo $this->site($session); ?> </td>
            <td>
                <?php if ($session->getResponsable()) : ?>
                    <?php echo $session->getResponsable()->getNomComplet(); ?>
                <?php else : ?>
                    Aucun responsable
                <?php endif; ?>
            </td>
            <td> <?php echo $this->modalite($session); ?> </td>
            <td> <?php echo $this->type($session); ?> </td>
            <td> <?php echo $this->etat($session); ?></td>
            <td>
                <?php echo count($session->getSeances()); ?>
                séance<?php if (count($session->getSeances())>1) echo "s"; ?>
                -
                <?php echo $session->getDuree(); ?> h.
                <ul>
                <?php foreach ($session->getSeances() as $seance) : ?>
                    <?php /** @var Seance $seance*/?>
                    <li>
                        <?php echo $seance->getDebut()->format('d/m/Y'); ?>
                        <?php echo $seance->getDebut()->format('H:i'); ?>
                        &rightarrow;
                        <?php echo $seance->getFin()->format('H:i'); ?>
                    </li>
                <?php endforeach;?>
                </ul>
            </td>
            <td>
                <?php if ($canAfficherSession) : ?>
                    <?php /** @see \Formation\Controller\SessionController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('formation/session/afficher', ['session' => $session->getId()], [], true); ?>">
                        <span class="icon icon-voir"></span>
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriserSession) : ?>
                    <?php if ($session->estNonHistorise()) : ?>
                        <?php /** @see \Formation\Controller\SessionController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('formation/session/historiser', ['session' => $session->getId()], ['query' => ['retour' => $this->url('formation/formation/afficher', ['formation' => $formation->getId()], [], true)]], true); ?>"
                        >
                            <span class="icon icon-historiser"></span>
                        </a>
                    <?php else : ?>
                        <?php /** @see \Formation\Controller\SessionController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url('formation/session/restaurer', ['session' => $session->getId()], ['query' => ['retour' => $this->url('formation/formation/afficher', ['formation' => $formation->getId()], [], true)]], true); ?>"
                        >
                            <span class="icon icon-restaurer"></span>
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canSupprimerSession) : ?>
                    <?php /** @see \Formation\Controller\SessionController::supprimerAction() */ ?>
                    <a href="<?php echo $this->url('formation/session/supprimer', ['session' => $session->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification"
                       title="supprimer une session"
                       data-bs-toggle="tooltip" data-bs-html="true">
                        <span class="icon icon-detruire"></span>
                    </a>
                <?php endif; ?>

            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>



<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>


