<?php

/**
 * @see \Formation\Controller\FormationController::indexAction()
 * @var Formation[] $formations
 */

use Formation\Entity\Db\Formation;
use Formation\Entity\Db\Session;

$canAjouter = true;
$canModifier = true;
$canHistoriser = true;
$canSupprimer = true;
?>

<h1> Index des formations </h1>


<?php if ($canAjouter) : ?>
    <a
        <?php /** @see \Formation\Controller\FormationController::ajouterAction() */ ?>
        href="<?php echo $this->url('formation/formation/ajouter', [], [], true); ?>"
        class="btn btn-primary action ajax-modal" data-event="modification">
        <span class="glyphicon glyphicon-plus"></span>
        Ajouter une formation
    </a>
<?php endif; ?>


<table class="table table-condensed">
    <thead>
        <tr>
<!--            <th>Identifiant</th>-->
            <th>Libellé</th>
            <th>Site<span title="valeur par défaut">*</span></th>
            <th>Responsable<span title="valeur par défaut">*</span></th>
            <th>Modalité<span title="valeur par défaut">*</span> </th>
            <th>Type<span title="valeur par défaut">*</span> </th>
            <th>Taille des listes<span title="valeur par défaut">*</span> </th>
            <th>#Session</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($formations as $formation) : ?>
        <tr>
<!--            <td> --><?php //echo $formation->getId(); ?><!-- </td>-->
            <td>
                <?php echo $formation->getLibelle(); ?>
                <?php if ($formation->getDescription() !== null AND trim($formation->getDescription()) !== null) : ?>
                    <span class="glyphicon glyphicon-info-sign"
                          title="<?php echo $formation->getDescription(); ?>" data-toggle="tooltip" data-html="true"

                    ></span>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($formation->getSite()) : ?>
                    <?php echo $formation->getSite()->getSigle(); ?>
                <?php else : ?>
                    N.C.
                <?php endif; ?>
            </td>
            <td>
                <?php if ($formation->getResponsable()) : ?>
                    <?php echo $formation->getResponsable()->getNomComplet(); ?>
                <?php else : ?>
                    N.C.
                <?php endif; ?>
            </td>
            <td>
                <?php
                $modalite = null;
                switch($formation->getModalite()) {
                    case Session::MODALITE_PRESENTIEL:
                        $modalite = "Présentielle";
                        break;
                    case Session::MODALITE_DISTANCIEL:
                        $modalite = "Distancielle";
                        break;
                    default :
                        $modalite = "N.C.";
                        break;
                };
                echo $modalite;
                ?>
            </td>
            <td>
                <?php
                $type = null;
                switch($formation->getType()) {
                    case Session::TYPE_SPECIFIQUE:
                        $type = "Spécifique";
                        break;
                    case Session::TYPE_TRANSVERSALE:
                        $type = "Transerversale";
                        break;
                    default :
                        $type = "N.C.";
                        break;
                };
                echo $type;
                if ($formation->getType() === Session::TYPE_SPECIFIQUE AND $formation->getTypeStructure() !== null) {
                    echo "<br/>" . $formation->getTypeStructure()->getSigle();
                }
                ?>
            </td>
            <td>
                Liste principale :
                <?php echo $formation->getTailleListePrincipale()?:"N.C."; ?>
                <br/>
                Liste complémentaire :
                <?php echo $formation->getTailleListeComplementaire()?:"N.C."; ?>
            </td>
            <td>
                <?php echo count($formation->getSessions()); ?>
            </td>
            <td>
                <?php if ($canModifier) : ?>
                    <?php /** @see \Formation\Controller\FormationController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('formation/formation/modifier', ['formation' => $formation->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification"
                       title="Modifier le module de  formation #<?php echo $formation->getId(); ?>"
                       data-toggle="tooltip" data-html="true">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                <?php endif; ?>

                <?php if ($canHistoriser) : ?>
                    <?php if ($formation->estNonHistorise()) : ?>
                        <?php /** @see \Formation\Controller\FormationController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('formation/formation/historiser', ['formation' => $formation->getId()], [], true); ?>"
                           title="Modifier le module de  formation #<?php echo $formation->getId(); ?>"
                           data-toggle="tooltip" data-html="true">
                            <span class="glyphicon glyphicon-trash"></span>
                        </a>
                    <?php else : ?>
                        <?php /** @see \Formation\Controller\FormationController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url('formation/formation/restaurer', ['formation' => $formation->getId()], [], true); ?>"
                           title="Modifier le module de  formation #<?php echo $formation->getId(); ?>"
                           data-toggle="tooltip" data-html="true">
                            <span class="glyphicon glyphicon-leaf"></span>
                        </a>
                    <?php endif; ?>
                <?php endif; ?>

                <?php if ($canSupprimer) : ?>
                    <?php /** @see \Formation\Controller\FormationController::supprimerAction() */?>
                    <a href="<?php echo $this->url('formation/formation/supprimer',['formation' => $formation->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification"
                       title="Suppression du module de formation #<?php echo $formation->getId(); ?>" data-toggle="tooltip" data-html="true">
                        <span class="glyphicon glyphicon-remove"></span>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip({});
    });
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });

    });
</script>