<?php
/**
 * @var PhpRenderer $this
 * @see \Formation\Controller\FormationController::ajouterAction()
 * @see \Formation\Controller\FormationController::modifierAction()
 * @var FormationForm $form
 * @var UrlFichier $urlFichierPlugin
 */

use Application\View\Renderer\PhpRenderer;
use Fichier\Controller\Plugin\UrlFichier;
use Formation\Form\Formation\FormationForm;
use Formation\Provider\Privilege\FormationPrivileges;

$canModifierFormation   = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::FORMATION_MODIFIER));

?>

<h2> Information sur la formation </h2>

<?php
$form->prepare();
echo $this->form()->openTag($form);
?>

<?php echo $this->formControlGroup($form->get('libelle')); ?>
<?php echo $this->formControlGroup($form->get('description')); ?>
<?php echo $this->formControlGroup($form->get('lien')); ?>
<?php if ($form->getObject()?->getFiche()): ?>
    <div class="row mb-3">
        <div class="col">
            Fiche existante :
            <?php echo $this->fichier($form->getObject()->getFiche(),
                $urlFichierPlugin->telechargerFichier($form->getObject()->getFiche()),
                $this->url('formation/formation/supprimer-fiche', ["formation"=>$form->getObject()->getId(), "fichier" => $form->getObject()->getFiche()->getId()], [], true),
                $canModifierFormation,
                "Fiche de la formation",
                false
            ); ?>
        </div>

    </div>
    <a type="button" class="btn btn-primary mb-4" data-bs-target="#upload-file-container" data-bs-toggle="collapse" aria-expanded="true" aria-controls="upload-file-container">
        <span class="icon icon-pdf"></span>
        Remplacer la fiche existante
    </a>
    <div class="collapse row subfield mb-4" id="upload-file-container">
        <div class="alert alert-info">
            <span class="icon icon-info"></span>
            Cela remplacera automatiquement la fiche déjà présente
        </div>
        <?php echo $this->formControlGroup($form->get('fiche')); ?>
    </div>
<?php else: ?>
    <?php echo $this->formControlGroup($form->get('fiche')); ?>
<?php endif; ?>

<?php echo $this->formControlGroup($form->get('module')); ?>

<h2> Valeur par défaut des sessions de cette formation </h2>

<?php echo $this->formControlGroup($form->get('site')); ?>
<?php echo $this->formControlGroup($form->get('responsable')); ?>
<?php echo $this->formControlGroup($form->get('modalite')); ?>
<?php echo $this->formControlGroup($form->get('type')); ?>
<div id="type_structure">
    <?php echo $this->formControlGroup($form->get('type_structure')); ?>
</div>

<?php echo $this->formControlGroup($form->get('taille_liste_principale')); ?>
<?php echo $this->formControlGroup($form->get('taille_liste_complementaire')); ?>

<?php echo $this->formControlGroup($form->get('objectif')); ?>
<?php echo $this->formControlGroup($form->get('programme')); ?>

<?php echo $this->formControlGroup($form->get('submit')); ?>

<?php echo $this->form()->closeTag(); ?>

<script>
    function updateType() {
        console.log('here');
        let val =  $('select#type').val();
        console.log(val);
        if (val === 'S') {
            $('div#type_structure').show();
        } else {
            $('div#type_structure').hide();
        }
    }

    updateType();
    $('select#type').change(function() {
        updateType();
    });

    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });

    $(document).ready(function() {
        tinymce.remove();
        tinymce.init({
            selector: '.tinymce',
            toolbar: 'newdocument undo redo | bold italic removeformat | bullist',
            resize: true,
            language: 'fr_FR',
            plugins: 'lists',
            statusbar: true,
            browser_spellcheck : true,
            branding: false,
            menu: {},
            body_id: 'description',
            setup: function (editor) {
                editor.on("focusout", function () {
                    console.log(tinymce.get('description').getContent());
                    $('textarea').val(tinymce.get('description').getContent());
                });
            }
        });
        $('select').selectpicker();
        $('[data-bs-toggle="tooltip"]').tooltip({});
    });
</script>