-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sygaldb.unicaen.fr;sid=SYGLPROD;port=1523

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE MATERIALIZED VIEW MV_RECHERCHE_THESE
BUILD IMMEDIATE
REFRESH FORCE ON DEMAND
AS with acteurs as (
    select a.these_id, i.nom_usuel, INDIVIDU_ID
    from individu i
             join acteur a on i.id = a.individu_id
             join these t on t.id = a.these_id
             join role r on a.role_id = r.id and r.CODE in ('D', 'K') -- (co)directeur de thèse
)
select
            sysdate as date_creation,
            t.source_code code_these,
            d.source_code code_doctorant,
            ed.source_code code_ecole_doct,
            trim(str_reduce(
                        'code-ed{' || eds.code || '} ' ||
                        'code-ur{' || urs.code || '} ' ||
                        'titre{' || t.TITRE || '} ' ||
                        'doctorant-numero{' || substr(d.SOURCE_CODE, instr(d.SOURCE_CODE, '::')+2) || '} ' ||
                        'doctorant-nom{' || id.NOM_PATRONYMIQUE || ' ' || id.NOM_USUEL || '} ' ||
                        'doctorant-prenom{' || id.PRENOM1 || '} ' ||
                        'directeur-nom{' || a.nom_usuel || '} '
                )) as haystack
from these t
         join doctorant d on d.id = t.doctorant_id
         join individu id on id.id = d.INDIVIDU_ID
         join these th on th.source_code = t.source_code
         left join ecole_doct ed on t.ecole_doct_id = ed.id
         left join structure eds on ed.STRUCTURE_ID = eds.id
         left join UNITE_RECH ur on t.UNITE_RECH_ID = ur.id
         left join structure urs on ur.STRUCTURE_ID = urs.id
         left join acteurs a on a.these_id = t.id
         left join individu ia on ia.id = a.INDIVIDU_ID USING NO INDEX;



