
  ALTER TABLE "STRUCTURE" ADD CONSTRAINT "STRUCTURE_SOURCE_FK" FOREIGN KEY ("SOURCE_ID")
	  REFERENCES "SOURCE" ("ID") ENABLE;
  ALTER TABLE "STRUCTURE" ADD CONSTRAINT "STRUCTURE_HMFK" FOREIGN KEY ("HISTO_MODIFICATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "STRUCTURE" ADD CONSTRAINT "STRUCTURE_HDFK" FOREIGN KEY ("HISTO_DESTRUCTEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "STRUCTURE" ADD CONSTRAINT "STRUCTURE_HCFK" FOREIGN KEY ("HISTO_CREATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "PROFIL_TO_ROLE" ADD CONSTRAINT "PROFIL_TO_ROLE_ROLE_ID_FK" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "ROLE" ("ID") ENABLE;
  ALTER TABLE "PROFIL_TO_ROLE" ADD CONSTRAINT "PROFIL_TO_ROLE_PROFIL_ID_FK" FOREIGN KEY ("PROFIL_ID")
	  REFERENCES "PROFIL" ("ID") ENABLE;
  ALTER TABLE "INFORMATION" ADD CONSTRAINT "INFORMATION_HDFK" FOREIGN KEY ("HISTO_DESTRUCTEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "INFORMATION" ADD CONSTRAINT "INFORMATION_HMFK" FOREIGN KEY ("HISTO_MODIFICATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "INFORMATION" ADD CONSTRAINT "INFORMATION_HCFK" FOREIGN KEY ("HISTO_CREATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "THESE_ANNEE_UNIV" ADD CONSTRAINT "THESE_ANNEE_UNIV_HD_FK" FOREIGN KEY ("HISTO_DESTRUCTEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "THESE_ANNEE_UNIV" ADD CONSTRAINT "THESE_ANNEE_UNIV_HM_FK" FOREIGN KEY ("HISTO_MODIFICATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "THESE_ANNEE_UNIV" ADD CONSTRAINT "THESE_ANNEE_UNIV_HC_FK" FOREIGN KEY ("HISTO_CREATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "THESE_ANNEE_UNIV" ADD CONSTRAINT "THESE_ANNEE_UNIV_THESE_ID_FK" FOREIGN KEY ("THESE_ID")
	  REFERENCES "THESE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "THESE_ANNEE_UNIV" ADD CONSTRAINT "THESE_ANNEE_UNIV_SOURCE_FK" FOREIGN KEY ("SOURCE_ID")
	  REFERENCES "SOURCE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PROFIL_PRIVILEGE" ADD CONSTRAINT "PROFIL_PRIVILEGE_PROFIL_ID_FK" FOREIGN KEY ("PROFIL_ID")
	  REFERENCES "PROFIL" ("ID") ENABLE;
  ALTER TABLE "SOURCE" ADD CONSTRAINT "SOURCE_ETABLISSEMENT_ID_FK" FOREIGN KEY ("ETABLISSEMENT_ID")
	  REFERENCES "ETABLISSEMENT" ("ID") ENABLE;
  ALTER TABLE "FINANCEMENT" ADD CONSTRAINT "FINANCEMENT_HDFK" FOREIGN KEY ("HISTO_DESTRUCTEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "FINANCEMENT" ADD CONSTRAINT "FINANCEMENT_HMFK" FOREIGN KEY ("HISTO_MODIFICATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "FINANCEMENT" ADD CONSTRAINT "FINANCEMENT_HCFK" FOREIGN KEY ("HISTO_CREATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "FINANCEMENT" ADD CONSTRAINT "FINANCEMENT_SOURCE_FK" FOREIGN KEY ("SOURCE_ID")
	  REFERENCES "SOURCE" ("ID") ENABLE;
  ALTER TABLE "ORIGINE_FINANCEMENT" ADD CONSTRAINT "ORIGINE_FINANCEMENT_HDFK" FOREIGN KEY ("HISTO_DESTRUCTEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "ORIGINE_FINANCEMENT" ADD CONSTRAINT "ORIGINE_FINANCEMENT_HMFK" FOREIGN KEY ("HISTO_MODIFICATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "ORIGINE_FINANCEMENT" ADD CONSTRAINT "ORIGINE_FINANCEMENT_HCFK" FOREIGN KEY ("HISTO_CREATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "ORIGINE_FINANCEMENT" ADD CONSTRAINT "ORIGINE_FINANCEMENT_SOURCE_FK" FOREIGN KEY ("SOURCE_ID")
	  REFERENCES "SOURCE" ("ID") ENABLE;
  ALTER TABLE "TITRE_ACCES" ADD CONSTRAINT "TITRE_ACCES_HD_FK" FOREIGN KEY ("HISTO_DESTRUCTEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "TITRE_ACCES" ADD CONSTRAINT "TITRE_ACCES_HM_FK" FOREIGN KEY ("HISTO_MODIFICATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "TITRE_ACCES" ADD CONSTRAINT "TITRE_ACCES_HC_FK" FOREIGN KEY ("HISTO_CREATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "TITRE_ACCES" ADD CONSTRAINT "TITRE_ACCES_THESE_ID_FK" FOREIGN KEY ("THESE_ID")
	  REFERENCES "THESE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "TITRE_ACCES" ADD CONSTRAINT "TITRE_ACCES_SOURCE_FK" FOREIGN KEY ("SOURCE_ID")
	  REFERENCES "SOURCE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ACTEUR" ADD CONSTRAINT "ACTEUR_ETAB_ID_FK" FOREIGN KEY ("ACTEUR_ETABLISSEMENT_ID")
	  REFERENCES "ETABLISSEMENT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "THESE" ADD CONSTRAINT "THESE_UNITE_RECH_FK" FOREIGN KEY ("UNITE_RECH_ID")
	  REFERENCES "UNITE_RECH" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "THESE" ADD CONSTRAINT "THESE_ECOLE_DOCT_FK" FOREIGN KEY ("ECOLE_DOCT_ID")
	  REFERENCES "ECOLE_DOCT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ETABLISSEMENT_RATTACH" ADD CONSTRAINT "RATTACHEMENT_ETAB_ID" FOREIGN KEY ("ETABLISSEMENT_ID")
	  REFERENCES "ETABLISSEMENT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ETABLISSEMENT_RATTACH" ADD CONSTRAINT "RATTACHEMENT_UNITE_ID" FOREIGN KEY ("UNITE_ID")
	  REFERENCES "UNITE_RECH" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "STRUCTURE_SUBSTIT" ADD CONSTRAINT "STR_SUBSTIT_DESTRUCTEUR_FK" FOREIGN KEY ("HISTO_DESTRUCTEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "STRUCTURE_SUBSTIT" ADD CONSTRAINT "STR_SUBSTIT_MODIFICATEUR_FK" FOREIGN KEY ("HISTO_MODIFICATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "STRUCTURE_SUBSTIT" ADD CONSTRAINT "STR_SUBSTIT_CREATEUR_FK" FOREIGN KEY ("HISTO_CREATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "STRUCTURE_SUBSTIT" ADD CONSTRAINT "STR_SUBSTIT_STR_TO_FK" FOREIGN KEY ("TO_STRUCTURE_ID")
	  REFERENCES "STRUCTURE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "STRUCTURE_SUBSTIT" ADD CONSTRAINT "STR_SUBSTIT_STR_FROM_FK" FOREIGN KEY ("FROM_STRUCTURE_ID")
	  REFERENCES "STRUCTURE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MAIL_CONFIRMATION" ADD CONSTRAINT "MAILCONFIRMATION_INDIVIDUID_FK" FOREIGN KEY ("INDIVIDU_ID")
	  REFERENCES "INDIVIDU" ("ID") ENABLE;
  ALTER TABLE "PROFIL" ADD CONSTRAINT "ROLEMODELE_STRUCTURETYPE_FK" FOREIGN KEY ("STRUCTURE_TYPE")
	  REFERENCES "TYPE_STRUCTURE" ("ID") ENABLE;
  ALTER TABLE "PROFIL_PRIVILEGE" ADD CONSTRAINT "ROLE_PRIV_MOD_PRIV_ID_FK" FOREIGN KEY ("PRIVILEGE_ID")
	  REFERENCES "PRIVILEGE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ROLE_PRIVILEGE" ADD CONSTRAINT "ROLE_PRIVILEGE_PRIV_ID_FK" FOREIGN KEY ("PRIVILEGE_ID")
	  REFERENCES "PRIVILEGE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ROLE_PRIVILEGE" ADD CONSTRAINT "ROLE_PRIVILEGE_ROLE_ID_FK" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "ROLE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "INDIVIDU_ROLE" ADD CONSTRAINT "INDIVIDU_ROLE_ROLE_ID_FK" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "ROLE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "INDIVIDU_ROLE" ADD CONSTRAINT "INDIVIDU_ROLE_IND_ID_FK" FOREIGN KEY ("INDIVIDU_ID")
	  REFERENCES "INDIVIDU" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ROLE" ADD CONSTRAINT "ROLE_TYPE_STRUCT_ID_FK" FOREIGN KEY ("TYPE_STRUCTURE_DEPENDANT_ID")
	  REFERENCES "TYPE_STRUCTURE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ROLE" ADD CONSTRAINT "ROLE_STRUCTURE_ID_FK" FOREIGN KEY ("STRUCTURE_ID")
	  REFERENCES "STRUCTURE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ROLE" ADD CONSTRAINT "ROLE_HD_FK" FOREIGN KEY ("HISTO_DESTRUCTEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ROLE" ADD CONSTRAINT "ROLE_HM_FK" FOREIGN KEY ("HISTO_MODIFICATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ROLE" ADD CONSTRAINT "ROLE_HC_FK" FOREIGN KEY ("HISTO_CREATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ROLE" ADD CONSTRAINT "ROLE_SOURCE_FK" FOREIGN KEY ("SOURCE_ID")
	  REFERENCES "SOURCE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ACTEUR" ADD CONSTRAINT "ACTEUR_HD_FK" FOREIGN KEY ("HISTO_DESTRUCTEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ACTEUR" ADD CONSTRAINT "ACTEUR_HM_FK" FOREIGN KEY ("HISTO_MODIFICATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ACTEUR" ADD CONSTRAINT "ACTEUR_HC_FK" FOREIGN KEY ("HISTO_CREATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ACTEUR" ADD CONSTRAINT "ACTEUR_SOURCE_FK" FOREIGN KEY ("SOURCE_ID")
	  REFERENCES "SOURCE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ACTEUR" ADD CONSTRAINT "ACTEUR_THESE_FK" FOREIGN KEY ("THESE_ID")
	  REFERENCES "THESE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ACTEUR" ADD CONSTRAINT "ACTEUR_INDIV_FK" FOREIGN KEY ("INDIVIDU_ID")
	  REFERENCES "INDIVIDU" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "RDV_BU" ADD CONSTRAINT "RDV_BU_HD_FK" FOREIGN KEY ("HISTO_DESTRUCTEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "RDV_BU" ADD CONSTRAINT "RDV_BU_HM_FK" FOREIGN KEY ("HISTO_MODIFICATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "RDV_BU" ADD CONSTRAINT "RDV_BU_HC_FK" FOREIGN KEY ("HISTO_CREATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "RDV_BU" ADD CONSTRAINT "RDV_BU_FK" FOREIGN KEY ("THESE_ID")
	  REFERENCES "THESE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "VALIDITE_FICHIER" ADD CONSTRAINT "VALIDITE_FICHIER_HDFK" FOREIGN KEY ("HISTO_DESTRUCTEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "VALIDITE_FICHIER" ADD CONSTRAINT "VALIDITE_FICHIER_HMFK" FOREIGN KEY ("HISTO_MODIFICATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "VALIDITE_FICHIER" ADD CONSTRAINT "VALIDITE_FICHIER_HCFK" FOREIGN KEY ("HISTO_CREATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "VALIDITE_FICHIER" ADD CONSTRAINT "CONFORMITE_FICHIER_FFK" FOREIGN KEY ("FICHIER_ID")
	  REFERENCES "FICHIER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "VALIDATION" ADD CONSTRAINT "VALIDATION_HDFK" FOREIGN KEY ("HISTO_DESTRUCTEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "VALIDATION" ADD CONSTRAINT "VALIDATION_HMFK" FOREIGN KEY ("HISTO_MODIFICATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "VALIDATION" ADD CONSTRAINT "VALIDATION_HCFK" FOREIGN KEY ("HISTO_CREATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "VALIDATION" ADD CONSTRAINT "VALIDATION_INDIVIDU_ID_FK" FOREIGN KEY ("INDIVIDU_ID")
	  REFERENCES "INDIVIDU" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "VALIDATION" ADD CONSTRAINT "VALIDATION_THESE_FK" FOREIGN KEY ("THESE_ID")
	  REFERENCES "THESE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "VALIDATION" ADD CONSTRAINT "VALIDATION_TYPE_VALIDATION_FK" FOREIGN KEY ("TYPE_VALIDATION_ID")
	  REFERENCES "TYPE_VALIDATION" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "UNITE_RECH" ADD CONSTRAINT "UNITE_RECH_STRUCT_FK" FOREIGN KEY ("STRUCTURE_ID")
	  REFERENCES "STRUCTURE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "UNITE_RECH" ADD CONSTRAINT "UNITE_RECH_COMPL_HDFK" FOREIGN KEY ("HISTO_DESTRUCTEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "UNITE_RECH" ADD CONSTRAINT "UNITE_RECH_COMPL_HMFK" FOREIGN KEY ("HISTO_MODIFICATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "UNITE_RECH" ADD CONSTRAINT "UNITE_RECH_COMPL_HCFK" FOREIGN KEY ("HISTO_CREATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "UNITE_RECH" ADD CONSTRAINT "UNITE_RECH_SOURCE_FK" FOREIGN KEY ("SOURCE_ID")
	  REFERENCES "SOURCE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DOCTORANT_COMPL" ADD CONSTRAINT "THESARD_COMPL_HDFK" FOREIGN KEY ("HISTO_DESTRUCTEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "DOCTORANT_COMPL" ADD CONSTRAINT "THESARD_COMPL_HMFK" FOREIGN KEY ("HISTO_MODIFICATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "DOCTORANT_COMPL" ADD CONSTRAINT "THESARD_COMPL_HCFK" FOREIGN KEY ("HISTO_CREATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "DOCTORANT_COMPL" ADD CONSTRAINT "DOCTORANT_COMPL_DOCTORANT_FK" FOREIGN KEY ("DOCTORANT_ID")
	  REFERENCES "DOCTORANT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ECOLE_DOCT" ADD CONSTRAINT "ECOLE_DOCT_STRUCT_FK" FOREIGN KEY ("STRUCTURE_ID")
	  REFERENCES "STRUCTURE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ECOLE_DOCT" ADD CONSTRAINT "ECOLE_DOCT_SOURCE_FK" FOREIGN KEY ("SOURCE_ID")
	  REFERENCES "SOURCE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ECOLE_DOCT" ADD CONSTRAINT "ECOLE_DOCT_HDFK" FOREIGN KEY ("HISTO_DESTRUCTEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ECOLE_DOCT" ADD CONSTRAINT "ECOLE_DOCT_HMFK" FOREIGN KEY ("HISTO_MODIFICATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ECOLE_DOCT" ADD CONSTRAINT "ECOLE_DOCT_HCFK" FOREIGN KEY ("HISTO_CREATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DIFFUSION" ADD CONSTRAINT "DIFFUSION_HD_FK" FOREIGN KEY ("HISTO_DESTRUCTEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DIFFUSION" ADD CONSTRAINT "DIFFUSION_HM_FK" FOREIGN KEY ("HISTO_MODIFICATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DIFFUSION" ADD CONSTRAINT "DIFFUSION_HC_FK" FOREIGN KEY ("HISTO_CREATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DIFFUSION" ADD CONSTRAINT "MISE_EN_LIGNE_THESE_FK" FOREIGN KEY ("THESE_ID")
	  REFERENCES "THESE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FICHIER" ADD CONSTRAINT "FICHIER_NATURE_FICHIER_ID_FK" FOREIGN KEY ("NATURE_ID")
	  REFERENCES "NATURE_FICHIER" ("ID") ENABLE;
  ALTER TABLE "FICHIER" ADD CONSTRAINT "FICHIER_HDFK" FOREIGN KEY ("HISTO_DESTRUCTEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "FICHIER" ADD CONSTRAINT "FICHIER_HMFK" FOREIGN KEY ("HISTO_MODIFICATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "FICHIER" ADD CONSTRAINT "FICHIER_HCFK" FOREIGN KEY ("HISTO_CREATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ENABLE;
  ALTER TABLE "FICHIER" ADD CONSTRAINT "FICHIER_VERSION_FK" FOREIGN KEY ("VERSION_FICHIER_ID")
	  REFERENCES "VERSION_FICHIER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FICHIER" ADD CONSTRAINT "FICHIER_THESE_FK" FOREIGN KEY ("THESE_ID")
	  REFERENCES "THESE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ATTESTATION" ADD CONSTRAINT "ATTESTATION_HD_FK" FOREIGN KEY ("HISTO_DESTRUCTEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ATTESTATION" ADD CONSTRAINT "ATTESTATION_HM_FK" FOREIGN KEY ("HISTO_MODIFICATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ATTESTATION" ADD CONSTRAINT "ATTESTATION_HC_FK" FOREIGN KEY ("HISTO_CREATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ATTESTATION" ADD CONSTRAINT "ATTESTATION_THESE_FK" FOREIGN KEY ("THESE_ID")
	  REFERENCES "THESE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "VARIABLE" ADD CONSTRAINT "VARIABLE_HD_FK" FOREIGN KEY ("HISTO_MODIFICATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "VARIABLE" ADD CONSTRAINT "VARIABLE_HM_FK" FOREIGN KEY ("HISTO_DESTRUCTEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "VARIABLE" ADD CONSTRAINT "VARIABLE_HC_FK" FOREIGN KEY ("HISTO_CREATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "VARIABLE" ADD CONSTRAINT "VARIABLE_SOURCE_FK" FOREIGN KEY ("SOURCE_ID")
	  REFERENCES "SOURCE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "VARIABLE" ADD CONSTRAINT "VARIABLE_ETAB_FK" FOREIGN KEY ("ETABLISSEMENT_ID")
	  REFERENCES "ETABLISSEMENT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "METADONNEE_THESE" ADD CONSTRAINT "METADONNEE_THESE_THESE_ID_FK" FOREIGN KEY ("THESE_ID")
	  REFERENCES "THESE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "THESE" ADD CONSTRAINT "THESE_HD_FK" FOREIGN KEY ("HISTO_DESTRUCTEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "THESE" ADD CONSTRAINT "THESE_HM_FK" FOREIGN KEY ("HISTO_MODIFICATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "THESE" ADD CONSTRAINT "THESE_HC_FK" FOREIGN KEY ("HISTO_CREATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "THESE" ADD CONSTRAINT "THESE_SOURCE_FK" FOREIGN KEY ("SOURCE_ID")
	  REFERENCES "SOURCE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "THESE" ADD CONSTRAINT "THESE_DOCTORANT_FK" FOREIGN KEY ("DOCTORANT_ID")
	  REFERENCES "DOCTORANT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "THESE" ADD CONSTRAINT "THESE_ETAB_FK" FOREIGN KEY ("ETABLISSEMENT_ID")
	  REFERENCES "ETABLISSEMENT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DOCTORANT" ADD CONSTRAINT "DOCTORANT_HD_FK" FOREIGN KEY ("HISTO_DESTRUCTEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DOCTORANT" ADD CONSTRAINT "DOCTORANT_HM_FK" FOREIGN KEY ("HISTO_MODIFICATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DOCTORANT" ADD CONSTRAINT "DOCTORANT_HC_FK" FOREIGN KEY ("HISTO_CREATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DOCTORANT" ADD CONSTRAINT "DOCTORANT_SOURCE_FK" FOREIGN KEY ("SOURCE_ID")
	  REFERENCES "SOURCE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DOCTORANT" ADD CONSTRAINT "DOCTORANT_INDIV_FK" FOREIGN KEY ("INDIVIDU_ID")
	  REFERENCES "INDIVIDU" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DOCTORANT" ADD CONSTRAINT "DOCTORANT_ETAB_FK" FOREIGN KEY ("ETABLISSEMENT_ID")
	  REFERENCES "ETABLISSEMENT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ETABLISSEMENT" ADD CONSTRAINT "ETABLISSEMENT_SOURCE_FK" FOREIGN KEY ("SOURCE_ID")
	  REFERENCES "SOURCE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ETABLISSEMENT" ADD CONSTRAINT "ETAB_UTIL_DESTRUCTEUR_FK" FOREIGN KEY ("HISTO_DESTRUCTEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ETABLISSEMENT" ADD CONSTRAINT "ETAB_UTIL_MODIFICATEUR_FK" FOREIGN KEY ("HISTO_MODIFICATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ETABLISSEMENT" ADD CONSTRAINT "ETAB_UTIL_CREATEUR_FK" FOREIGN KEY ("HISTO_CREATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ETABLISSEMENT" ADD CONSTRAINT "ETAB_STRUCT_FK" FOREIGN KEY ("STRUCTURE_ID")
	  REFERENCES "STRUCTURE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "STRUCTURE" ADD CONSTRAINT "STRUCTURE_TYPE_STRUCTURE_ID_FK" FOREIGN KEY ("TYPE_STRUCTURE_ID")
	  REFERENCES "TYPE_STRUCTURE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "IMPORT_OBS_RESULT_NOTIF" ADD CONSTRAINT "IORNR__NR_FK" FOREIGN KEY ("NOTIF_RESULT_ID")
	  REFERENCES "NOTIF_RESULT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "IMPORT_OBS_RESULT_NOTIF" ADD CONSTRAINT "IORNR__IOR_FK" FOREIGN KEY ("IMPORT_OBSERV_RESULT_ID")
	  REFERENCES "IMPORT_OBSERV_RESULT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "IMPORT_OBS_NOTIF" ADD CONSTRAINT "IOND__N_FK" FOREIGN KEY ("NOTIF_ID")
	  REFERENCES "NOTIF" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "IMPORT_OBS_NOTIF" ADD CONSTRAINT "IOND__IO_FK" FOREIGN KEY ("IMPORT_OBSERV_ID")
	  REFERENCES "IMPORT_OBSERV" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "IMPORT_OBSERV_RESULT" ADD CONSTRAINT "IMPORT_OBSERV_RESULT__IO_FK" FOREIGN KEY ("IMPORT_OBSERV_ID")
	  REFERENCES "IMPORT_OBSERV" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "NOTIF_RESULT" ADD CONSTRAINT "NOTIF_RESULT__NOTIF_FK" FOREIGN KEY ("NOTIF_ID")
	  REFERENCES "NOTIF" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "UTILISATEUR" ADD CONSTRAINT "UTILISATEUR_INDIVIDU_FK" FOREIGN KEY ("INDIVIDU_ID")
	  REFERENCES "INDIVIDU" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "INDIVIDU" ADD CONSTRAINT "INDIVIDU_HD_FK" FOREIGN KEY ("HISTO_DESTRUCTEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "INDIVIDU" ADD CONSTRAINT "INDIVIDU_HM_FK" FOREIGN KEY ("HISTO_MODIFICATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "INDIVIDU" ADD CONSTRAINT "INDIVIDU_HC_FK" FOREIGN KEY ("HISTO_CREATEUR_ID")
	  REFERENCES "UTILISATEUR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "INDIVIDU" ADD CONSTRAINT "INDIVIDU_SOURCE_FK" FOREIGN KEY ("SOURCE_ID")
	  REFERENCES "SOURCE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PRIVILEGE" ADD FOREIGN KEY ("CATEGORIE_ID")
	  REFERENCES "CATEGORIE_PRIVILEGE" ("ID") ON DELETE CASCADE ENABLE;