#!/usr/bin/env php
<?php

use Application\Assertion\These\GeneratedTheseEntityAssertion;
use Application\Assertion\These\Generator\TheseEntityAssertionGenerator;

include __DIR__ . '/../../vendor/autoload.php';


//use Zend\Console;
//
//$rules = array(
//    'help|h'        => 'Get usage message',
////    'library|l-s'   => 'Library to parse; if none provided, assumes current directory',
////    'output|o-s'    => 'Where to write plugin map file; if not provided, assumes "plugin_classmap.php" in library directory',
////    'append|a'      => 'Append to plugin map file if it exists',
////    'overwrite|w'   => 'Whether or not to overwrite existing autoload file',
//);
//try {
//    $opts = new Console\Getopt($rules);
//    $opts->parse();
//} catch (Console\Exception\RuntimeException $e) {
//    echo $e->getUsageMessage();
//    exit(2);
//}
//if ($opts->getOption('h')) {
//    echo $opts->getUsageMessage();
//    exit();
//}

$config = [
    GeneratedTheseEntityAssertion::class => [
        'input_file'        => __DIR__ . "/assertion-rules.csv",
        'tmp_output_file'   => "/tmp/GeneratedTheseEntityAssertion.php",
        'target_class_file' => __DIR__ . '/../../module/Application/src/Application/Assertion/These/GeneratedTheseEntityAssertion.php',
    ],
];

foreach ($config as $class => $item) {
    $inputFilePath = $item['input_file'];
    $outputFilePath = $item['tmp_output_file'];
    $classFilePath = $item['target_class_file'];

    $generator = new TheseEntityAssertionGenerator($inputFilePath, $class);
    $generator->writeToFile($outputFilePath);

    exec("mv $outputFilePath $classFilePath");
    echo sprintf("La classe %s a été générée à partir de %s.", $class, $inputFilePath) . PHP_EOL;
}
