<?php

namespace Application;

use Application\Controller\AutorisationInscriptionController;
use Application\Entity\Db\AutorisationInscription;
use Application\Entity\Db\Rapport;
use Application\Entity\Db\Role;
use Application\Entity\Db\TypeValidation;
use Application\Filter\IdifyFilter;
use Application\Provider\Privilege\AutorisationInscriptionPrivileges;
use Application\Service\Rapport\RapportSearchService;
use Application\View\Renderer\PhpRenderer;
use Structure\Search\EcoleDoctorale\EcoleDoctoraleSearchFilter;
use Structure\Search\Etablissement\EtablissementSearchFilter;
use Structure\Search\UniteRecherche\UniteRechercheSearchFilter;
use These\Filter\ActeursFormatter;

/**
 * @var PhpRenderer $this
 * @var array{
 *      rapport: Rapport,
 *      autorisationInscription: AutorisationInscription
 *  } | array<Rapport> $rapports
 * @var AutorisationInscription[] $autorisationsInscription
 *
 * @var string $routeName
 * @var TypeValidation $typeValidation
 * @var string $privilege_TELEVERSER_TOUT
 * @var string $privilege_TELEVERSER_SIEN
 * @var string $privilege_SUPPRIMER_TOUT
 * @var string $privilege_SUPPRIMER_SIEN
 * @var string $privilege_TELECHARGER_TOUT
 * @var string $privilege_TELECHARGER_SIEN
 * @var string $privilege_VALIDER_TOUT
 * @var string $privilege_VALIDER_SIEN
 * @var string $privilege_DEVALIDER_TOUT
 * @var string $privilege_DEVALIDER_SIEN
 * @var string $privilege_AJOUTER_AVIS_TOUT
 * @var string $privilege_AJOUTER_AVIS_SIEN
 * @var string $privilege_SUPPRIMER_AVIS_TOUT
 * @var string $privilege_SUPPRIMER_AVIS_SIEN
 *
 * @var bool $displayEtablissement
 * @var bool $displayType
 * @var bool $displayDoctorant
 * @var bool $displayDirecteurThese
 * @var bool $displayEcoleDoctorale
 * @var bool $displayUniteRecherche
 * @var bool $displayValidation
 * @var bool $displayAvis
 *
 * @var string $returnUrl
 *
 * @see \Application\Controller\Rapport\RapportActiviteController::consulterAction()
 */

$acteursFormatterDirecteurs = new ActeursFormatter();
$acteursFormatterDirecteurs->asSeparated()
    ->paramDisplay(['role' => false, "qualite" => false, "etablissement" => false,])
    ->paramFilter((['role' => Role::CODE_DIRECTEUR_THESE]));
$acteursFormatterCodirecteurs = new ActeursFormatter();
$acteursFormatterCodirecteurs->asSeparated()
    ->paramDisplay(['role' => false, "qualite" => false, "etablissement" => false,])
    ->paramFilter((['role' => Role::CODE_CODIRECTEUR_THESE]));

?>
<table class="table table-bordered">
    <thead>
    <tr>
        <?php if ($displayEtablissement): ?>
        <th>
            <a href="<?php echo $s = $this->sortable(EtablissementSearchFilter::NAME) ?>"
               title="<?php echo $this->translate("Établissement") ?> ">
                <?php echo $this->translate("Étab.") ?>
            </a> <?php echo $s->icon() ?>
        </th>
        <?php endif ?>

        <?php if ($displayType): ?>
        <th>
            <a href="<?php echo $s = $this->sortable(RapportSearchService::NAME_type); ?>"
               title="<?php echo $this->translate("Type"); ?>">
                <?php echo $this->translate("Type"); ?>
            </a> <?php echo $s->icon() ?>
        </th>
        <?php endif ?>

        <th>
            <a href="<?php echo $s = $this->sortable('anneeRapport'); ?>"
               title="<?php echo $this->translate("Année universitaire du rapport"); ?>">
                <?php echo $this->translate("Année"); ?>
            </a> <?php echo $s->icon() ?>
        </th>

        <?php if ($displayDoctorant): ?>
        <th>
            <a href="<?php echo $s = $this->sortable(RapportSearchService::NAME_nom_doctorant) ?>"
               title="<?php echo $this->translate("Identité du doctorant") ?>">
                <?php echo $this->translate("Doctorant") ?>
            </a> <?php echo $s->icon() ?>
        </th>
        <?php endif ?>

        <?php if ($displayDirecteurThese): ?>
        <th>
            <?php echo $this->translate("Directeur(s) de thèse"); ?>
        </th>
        <?php endif ?>

        <?php if ($displayEcoleDoctorale): ?>
        <th>
            <a href="<?php echo $s = $this->sortable(EcoleDoctoraleSearchFilter::NAME); ?>"
               title="<?php echo $this->translate("École doctorale"); ?>">
                <?php echo $this->translate("École<br>doct."); ?>
            </a> <?php echo $s->icon() ?>
        </th>
        <?php endif ?>

        <?php if ($displayUniteRecherche): ?>
        <th>
            <a href="<?php echo $s = $this->sortable(UniteRechercheSearchFilter::NAME); ?>"
               title="<?php echo $this->translate("Unité de recherche"); ?>">
                <?php echo $this->translate("Unité<br>rech."); ?>
            </a> <?php echo $s->icon() ?>
        </th>
        <?php endif ?>

        <th>
            Téléversement
        </th>

        <th>
            Document
        </th>

        <?php if ($displayAvis ?? false): ?>
            <th>
                <a href="<?php echo $s = $this->sortable(RapportSearchService::NAME_avis); ?>"
                   title="<?php echo $this->translate("Avis"); ?>">
                    <?php echo $this->translate("Avis"); ?>
                </a> <?php echo $s->icon() ?>
            </th>
        <?php endif ?>

        <?php if ($displayValidation): ?>
        <th>
            <a href="<?php echo $s = $this->sortable(RapportSearchService::NAME_validation); ?>"
               title="<?php echo $this->translate("Validation"); ?>">
                <?php echo $this->translate("Validation"); ?>
            </a> <?php echo $s->icon() ?>
        </th>
        <?php endif ?>

        <th></th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($rapports as $ra): ?>
        <tr>
            <?php
            $rapport = is_array($ra) && $ra["rapport"] ? $ra["rapport"] : $ra;
            $these = $rapport->getThese();
            $rapportValidation = $rapport->getRapportValidation();
            $rapportAvis = $rapport->getRapportAvis();
            $classRapport = $rapportValidation !== null ? 'valide' : '';
            $canDel = $this->isAllowed($rapport, $privilege_SUPPRIMER_TOUT) || $this->isAllowed($rapport, $privilege_SUPPRIMER_SIEN);
            $canDl = $this->isAllowed($rapport, $privilege_TELECHARGER_TOUT) || $this->isAllowed($rapport, $privilege_TELECHARGER_SIEN);
            ?>

            <?php if ($displayEtablissement): ?>
            <td>
                <abbr title="<?php echo $these->getEtablissement()->getStructure()->getLibelle() ?>">
                    <?php echo $these->getEtablissement()->getStructure()->getSourceCode() ?>
                </abbr>
            </td>
            <?php endif ?>

            <?php if ($displayType): ?>
            <td>
                <?php echo $rapport->getTypeRapportToString() ?>
            </td>
            <?php endif ?>

            <td>
                <?php echo $rapport->getAnneeUniv() ?>
            </td>

            <?php if ($displayDoctorant): ?>
            <td>
                <a href="<?php echo $this->url('these/identite', ['these' => $these->getId()], [], true) ?>"
                   title="<?php echo $these->getTitre() ?>">
                    <?php echo $these->getDoctorant()->getIndividu()->getNomComplet() ?>
                </a>
            </td>
            <?php endif ?>

            <?php if ($displayDirecteurThese): ?>
            <td class="acteurs text-sm">
                <?php
                $directeurs = $acteursFormatterDirecteurs->filter($these->getActeurs());
                foreach ($directeurs as $directeur) {
                    echo $acteursFormatterDirecteurs->htmlifyActeur($directeur)."<br/>";
                }
                $codirecteurs = $acteursFormatterCodirecteurs->filter($these->getActeurs());
                foreach ($codirecteurs as $codirecteur) {
                    echo $acteursFormatterCodirecteurs->htmlifyActeur($codirecteur)."<br/>";
                }
                ?>
            </td>
            <?php endif ?>

            <?php if ($displayEcoleDoctorale): ?>
            <td>
                <?php if ($ed = $these->getEcoleDoctorale()): ?>
                    <abbr title="<?php echo $ed->getStructure()->getLibelle() ?>">
                        <?php echo $ed->getStructure()->getSourceCode(); ?>
                    </abbr>
                <?php endif ?>
            </td>
            <?php endif ?>

            <?php if ($displayUniteRecherche): ?>
            <td>
                <?php if ($ur = $these->getUniteRecherche()): ?>
                    <abbr title="<?php echo $ur->getStructure()->getLibelle() ?>">
                        <?php echo $ur->getStructure()->getSourceCode(); ?>
                    </abbr>
                <?php endif ?>
            </td>
            <?php endif ?>

            <td class="text-sm">
                <?php echo $rapport->getHistoCreateur() ?><br>
                <?php echo $rapport->getHistoCreation()->format('d/m/Y H:i') ?>
            </td>

            <td>
                <?php if ($canDl): ?>
                    <a href="<?php echo $this->url($routeName . '/telecharger', ['rapport' => IdifyFilter::id($rapport)]) ?>"
                       title="Cliquez pour télécharger">
                        <?php echo $rapport->getFichier()->getNom() ?>
                    </a>
                <?php else: ?>
                    <?php echo $rapport->getFichier()->getNom() ?>
                <?php endif; ?>
            </td>

            <?php if ($displayAvis ?? false): ?>
                <td>
                    <?php
                    $returnUrl = $returnUrl ?: $this->url($routeName . '/consulter', ['these' => $these->getId()]);
                    $canAjouterAvis = $this->isAllowed($rapport, $privilege_AJOUTER_AVIS_TOUT) || $this->isAllowed($rapport, $privilege_AJOUTER_AVIS_SIEN);
                    $canModifierAvis = $canAjouterAvis;
                    ?>
                    <?php if ($rapportAvis !== null): ?>
                        <p>
                            <span class="fas fa-thumbs-<?php echo $rapportAvis->getAvisAsBoolean() ? 'up' :'down' ?>"></span>
                            <abbr title="Commentaires : <?php echo $rapportAvis->getCommentaires() ?>"><strong><?php echo $rapportAvis->getAvis() ?></strong></abbr> <br>
                            <span class="text-sm"><?php echo $rapportAvis->getHistoModificateur() ?: $rapportAvis->getHistoCreateur() ?><br>
                            <?php echo ($rapportAvis->getHistoModification() ?: $rapportAvis->getHistoCreation())->format('d/m/Y H:i') ?></span>
                        </p>
                        <?php $canSupprimerAvis = $this->isAllowed($rapport, $privilege_SUPPRIMER_AVIS_TOUT) || $this->isAllowed($rapport, $privilege_SUPPRIMER_AVIS_SIEN) ?>
                        <?php if ($canModifierAvis): ?>
                            <a href="<?php echo $this->url($routeName . '/avis/modifier', ['rapportAvis' => $rapportAvis->getId()], ['query' => ['redirect' => $returnUrl]]) ?>"
                               class="btn btn-warning"
                               title="Modifier cet avis ?"
                               data-bs-toggle="confirmation">Modifier l'avis</span></a>
                        <?php endif ?>
                        <?php if ($canSupprimerAvis): ?>
                            <a href="<?php echo $this->url($routeName . '/avis/supprimer', ['rapportAvis' => $rapportAvis->getId()], ['query' => ['redirect' => $returnUrl]]) ?>"
                               class="btn btn-danger"
                               title="Supprimer cet avis ?"
                               data-bs-toggle="confirmation">Supprimer l'avis</span></a>
                        <?php endif ?>
                    <?php else: ?>
                        <?php if ($canAjouterAvis): ?>
                            <p>Aucun</p>
                            <a href="<?php echo $this->url($routeName . '/avis/ajouter', ['rapport' => $rapport->getId()], ['query' => ['redirect' => $returnUrl]]) ?>"
                               class="btn btn-secondary">Nouvel avis</span></a>
                        <?php endif ?>
                    <?php endif ?>
                </td>
            <?php endif; ?>

            <?php if ($displayValidation): ?>
            <td class="<?php echo $classRapport ?>">
                <?php $returnUrl = $returnUrl ?: $this->url($routeName . '/consulter', ['these' => $these->getId()]) ?>
                <?php if ($rapportValidation !== null): ?>
                    <p>
                        <span class="icon icon-ok"></span> <strong>Validé</strong> <br>
                        <span class="text-sm"><?php echo $rapportValidation->getHistoCreateur() ?><br>
                            <?php echo $rapportValidation->getHistoCreation()->format('d/m/Y H:i') ?></span>
                    </p>
                    <?php $canDevalider = $this->isAllowed($rapport, $privilege_DEVALIDER_TOUT) || $this->isAllowed($rapport, $privilege_DEVALIDER_SIEN) ?>
                    <?php if ($canDevalider): ?>
                        <a href="<?php echo $this->url($routeName . '/devalider', ['rapportValidation' => $rapportValidation->getId()], ['query' => ['redirect' => $returnUrl]]) ?>"
                           class="btn btn-danger"
                           title="Dévalider ce rapport ? <br>(Une confirmation avant la dévalidation vous sera demandée)"
                           data-toggle="confirmationx"
                           data-bs-toggle="tooltip"
                           data-bs-html="true"
                           data-message="Êtes-vous sûr·e de vouloir dévalider ?">Dévalider</span></a>
                    <?php endif ?>
                <?php else: ?>
                    <p>Non validé</p>
                    <?php $canValider = $this->isAllowed($rapport, $privilege_VALIDER_TOUT) || $this->isAllowed($rapport, $privilege_VALIDER_SIEN) ?>
                    <?php if ($canValider): ?>
                        <a href="<?php echo $this->url($routeName . '/valider', ['rapport' => $rapport->getId(), 'typeValidation' => $typeValidation->getId()], ['query' => ['redirect' => $returnUrl]]) ?>"
                           class="btn btn-success"
                           title="Valider ce rapport ?  <br>(Une confirmation avant la validation vous sera demandée)"
                           data-toggle="confirmationx"
                           data-bs-toggle="tooltip"
                           data-bs-html="true"
                           data-message="Êtes-vous sûr·e de vouloir valider ce rapport ?">Valider</span></a>
                    <?php endif ?>
                <?php endif ?>
            </td>
            <?php endif; ?>

            <td class="action">
                <?php
                /** @var AutorisationInscription|null $autorisationInscription */
                if (!(is_array($ra) && $ra["autorisationInscription"])) {
                    $autorisationInscription = new AutorisationInscription();
                    $autorisationInscription->setRapport($rapport);
                } else {
                    $autorisationInscription = $ra["autorisationInscription"];
                }
                $canAjouterAutorisationInscription = $this->isAllowed($autorisationInscription, AutorisationInscriptionPrivileges::AUTORISATION_INSCRIPTION_AJOUTER);
                if ($canAjouterAutorisationInscription): ?>
                    <a <?php /**  @see AutorisationInscriptionController::ajouterAction() */ ?>
                            class="action ajax-modal"
                            data-event="ajout-autorisation-inscription"
                            data-bs-toggle="tooltip"
                            data-bs-html="true"
                            title="Autoriser la réinscription dans l'année suivante ?"
                            class="btn btn-success"
                            href="<?php echo $this->url('autoriser-inscription/ajouter', ['rapport' => $rapport->getId()], [], true); ?>"
                    >
                        <span class="fa fa-redo"></span>
                    </a>
                <?php endif; ?>
                <?php if ($autorisationInscription->getAutorisationInscription() === true) :?>
                    <div class="alert alert-info" style="margin-left: 1rem;max-width: initial;">
                        <span class="icon icon-ok"></span>
                        Autorisé·e à se réinscrire dans l'année
                        suivante <?= $autorisationInscription->getAnneeUniv()->getAnneeUnivToString() ?>
                        <div class="card-subtitle mt-2 mb-2 text-sm text-muted">
                            Par <?php echo $autorisationInscription->getHistoModificateur() ?: $autorisationInscription->getHistoCreateur() ?>
                            ,
                            le <?php echo ($autorisationInscription->getHistoModification() ?: $autorisationInscription->getHistoCreation())->format(Constants::DATETIME_FORMAT) ?>
                        </div>
                        <?php if ($autorisationInscription->getCommentaires()): ?>
                            <a type="button" class="card-link text-sm" data-bs-toggle="modal"
                               data-bs-target="#commentairesAutorisationInscrModal">
                                <span class="fas fa-glasses" title="Voir les commentaires concernant l'autorisation"></span>
                                Détails
                            </a>
                            <div class="log-full-content d-none">
                                <h3>Commentaires</h3>
                                <p class="avis-complement">
                                    <span class="avis-complem-textarea">
                                        <span class="avis-complem-valeur"><?= $autorisationInscription->getCommentaires() ?></span>
                                    </span>
                                </p>
                            </div>
                        <?php endif; ?>
                    </div>
                <?php elseif ($autorisationInscription->getAutorisationInscription() === false): ?>
                    <div class="alert alert-danger" style="margin-left: 1rem;max-width: initial;">
                        <span class="icon icon-ko"></span>
                        Non autorisé·e à se réinscrire dans l'année
                        suivante <?= $autorisationInscription->getAnneeUniv()->getAnneeUnivToString() ?>
                        <div class="card-subtitle mt-2 mb-2 text-sm text-muted">
                            Par <?php echo $autorisationInscription->getHistoModificateur() ?: $autorisationInscription->getHistoCreateur() ?>
                            ,
                            le <?php echo ($autorisationInscription->getHistoModification() ?: $autorisationInscription->getHistoCreation())->format(Constants::DATETIME_FORMAT) ?>
                        </div>
                        <?php if ($autorisationInscription->getCommentaires()): ?>
                            <a type="button" class="card-link text-sm" data-bs-toggle="modal"
                               data-bs-target="#commentairesAutorisationInscrModal">
                                <span class="fas fa-glasses" title="Voir le motif de la non-autorisation"></span>
                                Détails
                            </a>
                            <div class="log-full-content d-none">
                                <h3>Motif de la non-autorisation</h3>
                                <p class="avis-complement">
                                    <span class="avis-complem-textarea">
                                        <span class="avis-complem-valeur"><?= $autorisationInscription->getCommentaires() ?></span>
                                    </span>
                                </p>
                            </div>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
                <?php if ($canDel && !$autorisationInscription->getId()): ?>
                    <a href="<?php echo $this->url($routeName . '/supprimer', ['rapport' => $rapport->getId()], ['query' => ['redirect' => $returnUrl ?? '']]) ?>"
                       title="Supprimer ce rapport ? <br>(Une confirmation avant la suppression vous sera demandée)"
                       data-toggle="confirmationx"
                       data-bs-toggle="tooltip"
                       data-bs-html="true"
                       data-message="Êtes-vous sûr·e de vouloir supprimer ce rapport ?"><span class="fa fa-trash"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="modal fade" id="commentairesAutorisationInscrModal" tabindex="-1" aria-labelledby="commentairesAutorisationInscrModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="commentairesAutorisationInscrModalLabel">Détails de l'avis</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button>
            </div>
            <div class="modal-body">
                <!-- rempli dynamiquement -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(function() {
        $("body").on("ajout-autorisation-inscription", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    })

    $(function() {
        const avisComplemsModal = document.getElementById('commentairesAutorisationInscrModal')
        avisComplemsModal.addEventListener('show.bs.modal', function (event) {
            const button = event.relatedTarget;
            const logFullContent = $(button).siblings(".log-full-content").html();

            const modalBody = avisComplemsModal.querySelector('.modal-body');
            $(modalBody).html(logFullContent);
        });
    })
</script>