<?php

use These\Entity\Db\FichierThese;
use These\Entity\Db\These;
use Application\Entity\Db\WfEtape;
use These\Provider\Privilege\ThesePrivileges;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var These       $these
 * @var FichierThese $fichier
 * @var bool        $retraite
 * @var string      $contact
 */

$validiteFichier = $fichier ? $fichier->getFichier()->getValidite() : null;
$originaleOuRetraitee = $retraite ? "retraitée" : "";
?>

<?php if ($fichier): ?>

    <div class="card box">

        <div class="card-header bg-info">
            <?php $heading = $fichier->getFichier()->getVersion()->estVersionCorrigee() ?
                "Archivabilité de la thèse corrigée $originaleOuRetraitee" : "Archivabilité de la thèse $originaleOuRetraitee"; ?>
            <h2 class="first"><?php echo $heading ?></h2>
        </div>

        <div class="card-body">

            <?php if (!$validiteFichier): ?>

                <p>L'archivabilité de la thèse <?php echo $originaleOuRetraitee ?> n'a pas encore été testée.</p>

            <?php elseif ($validiteFichier->getEstValide() === null): ?>

                <p class="text-warning lead">L'archivabilité de la thèse <?php echo $originaleOuRetraitee ?> est indéterminée.</p>

            <?php elseif ($validiteFichier->getEstValide() === false): ?>

                <?php if ($fichier->isRetraitementAuto()): ?>
                    <p class="text-danger lead">
                        <span class="fas fa-thumbs-down"></span>
                        Thèse retraitée automatiquement par l'application non archivable.
                    </p>
                    <p>
                        Vous pouvez opter pour la solution "Retraitement par vos soins" si vous le souhaitez.
                    </p>
                <?php else: ?>
                    <p class="text-danger lead">
                        <span class="fas fa-thumbs-down"></span>
                        Thèse retraitée par vos soins non archivable.
                    </p>
                    <p>
                        Dans ce cas, vous êtes encouragé-e à essayer l'autre solution de retraitement.
                    </p>
                <?php endif ?>
                <p>
                    En cas d'échec, contactez <a href="mailto:<?php echo $contact ?>"><?php echo $contact ?></a>
                    pour obtenir de l'aide.
                </p>

            <?php elseif ($validiteFichier->getEstValide() === true): ?>

                <?php if ($fichier->isRetraitementAuto()): ?>
                    <p class="text-success lead">
                        <span class="fas fa-thumbs-up"></span>
                        Thèse <?php echo $retraite ? "retraitée" : "" ?> automatiquement archivable
                    </p>
                <?php else: ?>
                    <p class="text-success lead">
                        <span class="fas fa-thumbs-up"></span>
                        Thèse <?php echo $retraite ? "retraitée" : "" ?> par vos soins archivable
                    </p>
                <?php endif ?>

            <?php endif ?>

        </div>

    </div>

<?php endif ?>


<?php /*echo $this->partial('next-step-box', [
    'these' => $these,
    'etape' => WfEtape::CODE_ARCHIVABILITE_VERSION_ARCHIVAGE,
    // Pas de lien si la prochaine étape est "vérification de conformité" car elle pointe sur la page courante :
    'except' => WfEtape::CODE_VERIFICATION_VERSION_ARCHIVAGE,
])*/ ?>