INSERT INTO ROLE (ID, CODE, LIBELLE, SOURCE_CODE, SOURCE_ID, ROLE_ID, THESE_DEP, HISTO_CREATEUR_ID, HISTO_MODIFICATEUR_ID, ORDRE_AFFICHAGE)
VALUES (1001, 'CST_E', 'Examinateur (CST)', 'SyGAL::CST_E', 1, 'Examinateur (CST)', 1, 1, 1, 'zzzz_1');
INSERT INTO ROLE (ID, CODE, LIBELLE, SOURCE_CODE, SOURCE_ID, ROLE_ID, THESE_DEP, HISTO_CREATEUR_ID, HISTO_MODIFICATEUR_ID, ORDRE_AFFICHAGE)
VALUES (1002, 'CST_O', 'Observateur (CST)', 'SyGAL::CST_O', 1, 'Observateur (CST)', 1, 1, 1, 'zzzz_2');