<?php

use Application\Controller\TheseController;
use Application\Entity\Db\Attestation;
use Application\Entity\Db\These;
use Fichier\Entity\Db\VersionFichier;
use Application\Form\AttestationTheseForm;
use Application\Provider\Privilege\ThesePrivileges;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer          $this
 * @var These                $these
 * @var VersionFichier       $version
 * @var Attestation          $attestation
 * @var AttestationTheseForm $form
 * @var string               $modifierAttestationUrl
 * @var bool                 $resaisirAttestationsVersionCorrigee
 *
 * @see TheseController::attestationAction()
 */

$privilege = ThesePrivileges::THESE_SAISIE_ATTESTATIONS_($version);
$canEdit = $this->isAllowed($these, $privilege);
if ($version->estVersionCorrigee() && ! $resaisirAttestationsVersionCorrigee) {
    $canEdit = false;
}
?>

<div class="box card">

    <div class="card-header bg-info">
        <h2>Attestation
            <?php if ($attestation && $attestation->estCreationAuto()): ?><span>(Rappel)</span><?php endif ?></h2>
    </div>

    <div class="card-body">
        <?php if ($hasFichierThese): ?>

            <?php if ($attestation): ?>
                <?php
                // NB: les réponses aux attestations ne sont pas modifiables
                echo $this->partial('application/these/partial/attestation');
                ?>
            <?php else: ?>
                <?php if ($canEdit): ?>
                    <p><a href="<?php echo $modifierAttestationUrl ?>"
                          class="btn btn-primary ajax-modal"
                          data-event="event-attestation-modified"><span class="icon icon-edit"></span> Compléter</a></p>
                <?php endif ?>
            <?php endif ?>

        <?php else: ?>

            <p>Vous devez d'abord téléverser la thèse au format PDF.</p>

        <?php endif ?>
    </div>
</div>

