<?php

use Application\Controller\TheseController;
use Application\Entity\Db\Diffusion;
use Application\Entity\Db\These;
use Application\Entity\Db\VersionFichier;
use Application\Form\DiffusionTheseForm;
use Application\Provider\Privilege\ThesePrivileges;
use Application\View\Renderer\PhpRenderer;

/**
 * @var                    $this PhpRenderer
 * @var These              $these
 * @var VersionFichier     $version
 * @var Diffusion          $diffusion
 * @var DiffusionTheseForm $form
 * @var array              $theseFichiersExpurgesItems
 * @var array              $annexesFichiersExpurgesItems
 * @var bool               $resaisirAutorisationDiffusionVersionCorrigee
 * @var string             $modifierDiffusionUrl
 * @var string             $exporterConventionMelUrl
 *
 * @see TheseController::diffusionAction()
 */

$privilege = ThesePrivileges::THESE_SAISIE_AUTORISATION_DIFFUSION_($version);
$canEdit = $this->isAllowed($these, $privilege);
if ($version->estVersionCorrigee() && ! $resaisirAutorisationDiffusionVersionCorrigee) {
    $canEdit = false;
}
?>

<div class="box panel panel-info">

    <div class="panel-heading">
        <h2 class="first">Autorisation de diffusion
            <?php if ($diffusion && $diffusion->estCreationAuto()): ?><span>(Rappel)</span><?php endif ?></h2>
    </div>

    <div class="panel-body">
        <?php if ($hasFichierThese): ?>

            <!-------------------------------------- Questionnaire --------------------------------------->
            <?php if ($diffusion): ?>
                <?php echo $this->partial('application/these/partial/diffusion') ?>
                <?php if ($canEdit): ?>
                    <p><a href="<?php echo $modifierDiffusionUrl ?>"
                          class="btn btn-default zajax-modal"
                          data-event="event-diffusion-modified"><span class="glyphicon glyphicon-pencil"></span> Modifier</a></p>
                <?php endif ?>
            <?php else: ?>
                <?php if ($canEdit): ?>
                    <p><a href="<?php echo $modifierDiffusionUrl ?>"
                          class="btn btn-primary zajax-modal"
                          data-event="event-diffusion-modified"><span class="glyphicon glyphicon-pencil"></span> Compléter</a></p>
                <?php endif ?>
            <?php endif ?>

            <!-------------------------------------- Convention de mise en ligne --------------------------------------->
            <?php if ($diffusion && ! $diffusion->estCreationAuto()): ?>
                <hr>

                <h2>Convention de mise en ligne</h2>
                <p><a href="<?php echo $exporterConventionMelUrl ?>" target="_blank"
                      class="btn btn-primary"><span class="glyphicon glyphicon-export"></span>
                        Éditer la convention de mise en ligne</a></p>
            <?php endif ?>

        <?php else: ?>

            <p>Vous devez d'abord téléverser la thèse au format PDF.</p>

        <?php endif ?>
    </div>
</div>