<?php

use Application\Entity\Db\These;

define(PATH,"/webapp/public/");

/**
 * @param \Application\Entity\Db\Acteur $acteur
 * @param bool $civilite
 */
function getActeurDenomination($acteur, $civilite = false) {
    $texte = "";
    if ($civilite) $texte .=$acteur->getIndividu()->getCivilite(). " ";
    $texte .= ucwords(strtolower($acteur->getIndividu()->getPrenom1(). " "), " -");
    $texte .= $acteur->getIndividu()->getNomUsuel();
    if ($acteur->getIndividu()->getNomUsuel() != $acteur->getIndividu()->getNomPatronymique()) {
        $texte .= "-".$acteur->getIndividu()->getNomPatronymique();
    }
    return $texte;

}

function generateLogoComue(These $these) {


    $img_src = PATH . "ressources/normandie-universite.png";

    $texte  = "<div class='logo-comue'>";
    $texte .= "<img src='".$img_src."'/>";
    $texte .= "</div><br/>";

    return $texte;
}

function generateDiplomeInfos(These $these) {

    $specialite = ucwords(mb_strtolower($these->getLibelleDiscipline()));
    $etablissement = $these->getEtablissement()->getLibelle();

    $texte  = "<div class='bandeau-these'>THÈSE</div>";
    $texte .= "<div class='infos-diplome'>";
    $texte .= "<span class='larger-infos'>Pour obtenir le diplôme de doctorat" ."</span><br/>";
    $texte .= "Spécialité ". $specialite ."<br/>";
    $texte .= "Préparé au sein de l'". $etablissement ."<br/>";
    $texte .= "</div>";

    return $texte;
}

function generateTitre(These $these) {

    $titre = $these->getTitre();

    $texte  = "<div class='bandeau-titre'>".$titre."</div>";
    return $texte;

}

function generateDoctorantInfos(These $these) {

    $nom = mb_strtoupper($these->getDoctorant()->getIndividu()->getNomUsuel());
    $prenom = $these->getDoctorant()->getIndividu()->getPrenom1();

    $texte  = "<div class='infos-doctorant' style=''>";
    $texte .= "Présentée et soutenue par" . "<br/>";
    $texte .= $prenom ." ".$nom . "<br/>";
    $texte .= "</div>";

    return $texte;
}

function generateJuryInfos(These $these) {

    $date = $these->getDateSoutenance()->format("d/m/Y");
    $publiquement = "publiquement";
    $jury = $these->getActeurs()->toArray();

    $texte  = "<table class='jury'>";
    $texte .= "<tr><th colspan='3'>";
    $texte .= "Thèse soutenue ".$publiquement." le ".$date." <br/>";
    $texte .= "devant le jury composé de";
    $texte .= "</th></tr>";

    $rapporteurs = array_filter($jury, "estRapporteur");
    $directeurs = array_filter($jury, "estDirecteur");
    $membres =  array_diff(array_diff($jury, $rapporteurs), $directeurs);
    $roles = [$rapporteurs, $membres, $directeurs];

    /** @var \Application\Entity\Db\Acteur $acteur */
    foreach ($roles as $subroles) {
    foreach ($subroles as $acteur) {

        $nom  = getActeurDenomination($acteur, true);

        $qualite = $acteur->getQualite();
        $etablissement = $acteur->getEtablissement();

        $role = $acteur->getRole()->getRoleId();

        $texte .= "<tr>";
        $texte .= "<td>".$nom."</td>";
        $texte .= "<td>".$qualite.", ".$etablissement."</td>";
        $texte .= "<td>".$role."</td>";
        $texte .= "</tr>";
    }}
    $texte .= "</table>";
    return $texte;
}


/** @var \Application\Entity\Db\Acteur $var */
function estDirecteur($var) {
    $role = $var->getRole()->getSourceCode();
    return  (explode("::", $role)[1] == "D");
}

/** @var \Application\Entity\Db\Acteur $var */
function estRapporteur($var) {
    $role = $var->getRole()->getSourceCode();
    return  (explode("::", $role)[1] == "R");
}

function generateEncadrementInfos(These $these) {

    $ur = $these->getUniteRecherche()->getLibelle();
    $directeurs = array_filter($these->getActeurs()->toArray(), "estDirecteur");
    $texte  = "<div class='infos-encadrement'>";
    $texte .= "Thèse dirigée par ";
    /** @var \Application\Entity\Db\Acteur $directeur */
    $directeurs_array = [];
    foreach ($directeurs as $directeur) {
        $directeurs_array[] = getActeurDenomination($directeur);
    }
    $texte .= implode(" et ", $directeurs_array);
    $texte .= ", ";
    $texte .= $ur;
    $texte .= "</div>";
    return $texte;
}

function generateLogos(These $these) {

    $logouni = PATH. "ressources/unicaen.png";
    $logoed = PATH. "ressources/ednbise.png";
    if($these->getEcoleDoctorale()->getSigle() == "ED 590 MIIS") $logoed = PATH. "ressources/edmiis.png";
    $logour = PATH. "ressources/cermn.png";
    var_dump($these->getCodeUniteRecherche());
    if($these->getCodeUniteRecherche() == "UMR6072") $logour = PATH. "ressources/greyc.png";

    $texte = "";
//    $texte  .= "<div class='logos'>";
    $texte .= "<table style='border:none;' class='logos'>";
    $texte .= "<tr><td>";
    $texte .= "<img class='logo_small' src='".$logouni."'/>";
    $texte .= "</td><td>";
    $texte .= "<img class='logo_small' src='".$logoed."'/>";
    $texte .= "</td><td>";
    $texte .= "<img class='logo_small' src='".$logour."'/>";
    $texte .= "</td></tr></table>";
//    $texte .= "</div>";
    return $texte;
}

$pdf = new \Mpdf\Mpdf();
$stylesheet = file_get_contents(PATH. "css/page-unicaen.css" );
$pdf->WriteHTML($stylesheet,1);


//$pdf->WriteHTML("<div style='height:2cm;'></div>");

$couverture  = generateLogoComue($these);
$couverture .= generateDiplomeInfos($these);
$couverture .= generateTitre($these);
$couverture .= generateDoctorantInfos($these);
$couverture .= generateJuryInfos($these) . "<br/>";
$couverture .= generateEncadrementInfos($these);
$couverture .= generateLogos($these);

//$couverture  = "<table style='height:28cm;'><tr style='margin:auto;padding:auto;'><td style='margin:auto;padding:auto;'>";
//$couverture .= generateLogoComue($these);
//$couverture .= "</td></tr><tr><td>";
//$couverture .= generateDiplomeInfos($these);
//$couverture .= "</td></tr><tr><td>";
//$couverture .= generateTitre($these);
//$couverture .= "</td></tr><tr><td>";
//$couverture .= generateDoctorantInfos($these);
//$couverture .= "</td></tr><tr><td>";
//$couverture .= generateJuryInfos($these);
//$couverture .= "</td></tr><tr><td>";
//$couverture .= generateEncadrementInfos($these);
//$couverture .= "</td></tr><tr><td>";
//$couverture .= generateLogos($these);
//$couverture .= "</td></tr></table>";

$pdf->WriteHTML( $couverture );

$pdf->Output();




