<?php

use Application\Controller\TheseController;
use Application\Entity\Db\Acteur;
use Application\Entity\Db\EtablissementRattachement;
use Application\Entity\Db\MailConfirmation;
use Application\Entity\Db\These;
use Application\Entity\Db\Utilisateur;
use Application\Entity\Db\Validation;
use Application\Filter\ActeursFormatter;
use Application\Filter\FinancementFormatter;
use Application\Provider\Privilege\CoEncadrantPrivileges;
use Doctorant\Provider\Privilege\DoctorantPrivileges;
use Application\Provider\Privilege\ThesePrivileges;
use Application\Provider\Privilege\UtilisateurPrivileges;
use Application\View\Helper\IndividuUsurpationHelper;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer  $this
 * @var These        $these
 * @var string       $modifierPersopassUrl
 * @var bool         $estDoctorant
 * @var string       $modifierCorrecAutorUrl
 * @var string       $accorderSursisCorrecUrl
 * @var string       $nextStepUrl
 * @var string       $mailContact
 * @var string       $etatMailContact
 * @var Validation[] $validationsDesCorrectionsEnAttente
 * @var Utilisateur[] $utilisateurs
 * @var EtablissementRattachement[] $rattachements
 *
 * @see TheseController::detailIdentiteAction()
 */

$canVoirEmailContact = $this->isAllowed($these,DoctorantPrivileges::DOCTORANT_AFFICHER_EMAIL_CONTACT);
$canEditPersopass = $this->isAllowed($these, DoctorantPrivileges::DOCTORANT_MODIFICATION_PERSOPASS);
$canEditPersopass = $canEditPersopass && (!$estDoctorant || !$these->getDoctorant()->getPersopass());
$persopassModifiedEvent = 'persopass-modified-event';
$canCreate = $this->isAllowed(UtilisateurPrivileges::getResourceId(UtilisateurPrivileges::UTILISATEUR_CREATE_FROM_INDIVIDU));

$canCoEncadrantAfficher = $this->isAllowed(CoEncadrantPrivileges::getResourceId(CoEncadrantPrivileges::COENCADRANT_AFFICHER));
$canCoEncadrantGerer    = $this->isAllowed(CoEncadrantPrivileges::getResourceId(CoEncadrantPrivileges::COENCADRANT_GERER));


$canEditForcageCorrectionAutorisee = $this->isAllowed($these, ThesePrivileges::THESE_SAISIE_CORREC_AUTORISEE_FORCEE);

$financementFormatter = $this->financementFormatter();
$financementFormatter->setSortBy(FinancementFormatter::SORT_BY_DATE);
$financementFormatter->setDisplayAs(FinancementFormatter::DISPLAY_AS_LINE);
?>

<?php $this->headTitle($this->translate("Thèse"))->prepend($these->getDoctorant()->getNomUsuel()) ?>

<h1 class="page-header">
    <?php echo $this->translate("Thèse"); ?>
    <small><?php echo $this->partial('application/these/partial/titre') ?></small>
</h1>

<div class="box panel panel-info">

    <div class="panel-heading">
        <h2 class="first">
            <?php echo $this->translate("Fiche"); ?>
        </h2>
    </div>

    <div class="panel-body">

        <div id="photo-div" class="pull-right">
            <!--            <div class="photo-placeholder loading"-->
            <!--                 data-src="-->
            <?php //echo $this->url('leocarte/photo', ['id' => $these->getDoctorant()->getSourceCodeSansPrefix()]) ?><!--"></div>-->
        </div>

        <dl class="dl-horizontal">

            <dt>
                <?php echo $this->translate("Doctorant"); ?>
            </dt>
            <dd>
                <?php echo sprintf("%s (%s)",
                    $these->getDoctorant()->getIndividu()->getNomComplet(true, true, true),
                    $these->getDoctorant()->getIndividu()->getDateNaissanceToString());
                ?>
                <?php
                // bouton d'usurpation d'identité
                $individuUsurpationHelper = $this->plugin('individuUsurpation'); /* @var $individuUsurpationHelper IndividuUsurpationHelper */
                $individuUsurpationHelper->setIndividu($these->getDoctorant()->getIndividu());
                echo $individuUsurpationHelper();
                ?>
                <br>

                <strong>
                    <?php echo $this->translate("Nationalité :"); ?>
                </strong>
                <?php echo $these->getDoctorant()->getNationalite() ?> <br>

                <strong>
                    <?php echo $this->translate("N° étudiant :"); ?>
                </strong>
                <?php echo $these->getDoctorant()->getNumeroEtudiant() ?> <br>

                <strong>
                    <?php echo $this->translate("Adresse électronique :"); ?>
                </strong>
                <?php if ($email = $these->getDoctorant()->getEmail()): ?>
                    <a href="mailto: <?php echo $email ?>"><?php echo $email ?></a>
                <?php else: ?>
                    <?php echo $this->translate("(Inconnu)"); ?>
                <?php endif ?>

                <?php if ($canVoirEmailContact) : ?>
                    <br/>

                    <strong>
                        <?php echo $this->translate("Adresse électronique de contact :"); ?>
                    </strong>
                    <?php
                    if ($mailContact === null) {
                        echo "(Non renseigné) ";
                    } else {
                        echo $mailContact;
                        if ($etatMailContact === MailConfirmation::ENVOYE) {
                            echo " (en attente) ";
                        }
                    }
                    ?>
                <?php endif; ?>
                <?php if ($canEditPersopass): ?>
                    <a href="<?php echo $modifierPersopassUrl ?>"
                       data-event="<?php echo $persopassModifiedEvent ?>"
                       class="btn btn-default btn-xs ajax-modal">
                        <span class="glyphicon glyphicon-pencil"></span>
                        <?php echo $this->translate("Modifier"); ?>
                    </a>
                <?php endif ?>
            </dd>

            <?php
            // Affichage des acteurs de la these
            $acteursFormatter = new ActeursFormatter();
            $acteursFormatter->paramDisplay(["role" => true, "complement" => true, "qualite" => true, "etablissement" => true]);
            $acteursFormatter->asArray();
            $acteurs = $these->getActeursSorted();
            $results = $acteursFormatter->doFormat($acteurs->toArray());
            $previous = "";
            foreach ($results as $result) {
                $aucunSupannIdDansIndividu = isset($result['alerte-supann-id']);
                /** @var Acteur $acteur */
                $acteur = $result["acteur"];
                if ($previous != $result["role"]) {
                    echo "</dd>";
                    echo "<dt>" . $result["role"] . "</dt>";
                    echo "<dd>";
                    $previous = $result["role"];
                }
                $ligne = [];
                if (isset($result["nom"])) {
                    $ligne[] = $result["nom"];
                }
                if (isset($result["complement"])) {
                    $ligne[] = "<strong>" . $result["complement"] . "</strong>";
                }
                if (isset($result["qualite"]) && trim($result["qualite"]) != "") {
                    $ligne[] = $result["qualite"];
                }
                if (isset($result["etablissement"]) && trim($result["etablissement"]) != "") {
                    $ligne[] = $result["etablissement"];
                }
                if ($acteur->estDirecteur() && $aucunSupannIdDansIndividu) {
                    if (empty($utilisateurs[$acteur->getId()])) {
                        $ligne[] = sprintf('<span class="glyphicon glyphicon-warning-sign text-danger" title="%s"></span>',
                            $result['alerte-supann-id']);
                    } else {
                        $ligne[] = sprintf('<span class="glyphicon glyphicon-info-sign text-warning" title="Compte local"></span>');
                    }
//                    if ($canCreate) {
//                        $ligne[] = sprintf('<a href="%s" class="btn btn-sm btn-warning">Gérer l\'utilisateur</a>',
//                            $this->url('utilisateur/gerer-utilisateur', ['individu' => $acteur->getIndividu()->getId()], [], true));
//                    }
                }


                $ligne = implode(" &ndash; ", $ligne);
                echo $ligne;

                if (($acteur->estDirecteur() || $acteur->estCodirecteur() || $acteur->estRapporteur() || $acteur->estRapporteurAbsent()) && ! isset($result['alerte-supann-id'])) {
                    // bouton d'usurpation d'identité
                    $individuUsurpationHelper = $this->plugin('individuUsurpation');
                    /* @var $individuUsurpationHelper IndividuUsurpationHelper */
                    $individuUsurpationHelper->setIndividu($acteur->getIndividu());
                    echo $individuUsurpationHelper();
                }

                echo " &nbsp;";

                if ($canCoEncadrantAfficher AND $acteur->estCoEncadrant()) {
                    echo " <a href='".$this->url('co-encadrant/historique', ['co-encadrant' => $acteur->getId()], [], true) ."'>";
                    echo "<span class='glyphicon glyphicon-eye-open' title='Voir historique de co-encadrement'></span></a>";
                }
                if ($canCoEncadrantGerer AND $acteur->estCoEncadrant()) {
                    echo " <a href='".$this->url('co-encadrant/retirer-co-encadrant', ['these' => $these->getId(), 'co-encadrant' => $acteur->getId()], [], true) ."'>";
                    echo "<span class='glyphicon glyphicon-remove' title='Retirer le co-encadrant'></span></a>";
                }

                echo "<br/>";
            }
            ?>

            <?php if ($canCoEncadrantGerer) : ?>
                <dd>
                    <a  <?php /**  @see CoEncadrantController::ajouterCoEncadrantAction() */ ?>
                        class="btn btn-primary ajax-modal" data-event="modification"
                        href="<?php echo $this->url('co-encadrant/ajouter-co-encadrant', ['these' => $these->getId()], [], true); ?>"
                    >
                        <span class="glyphicon glyphicon-plus"></span>
                        Ajouter un co-encadrant
                    </a>
                </dd>
            <?php endif; ?>
            <dt>
                <?php echo $this->translate("Établissement <br/> d'inscription"); ?>
            </dt>
            <dd>
                <?php
                if ($these->getEtablissement()) {
                    echo /*$these->getEtablissement()->getCode() . " - " .*/
                    $these->getEtablissement()->getLibelle();
                } else {
                    echo "<div class='alert alert-sm alert-warning'>";
                    echo "<span class='glyphicon glyphicon-warning-sign'></span> Aucun établissement n'est renseignée.";
                    echo "</div>";
                }
                ?>
            </dd>

            <dt>
                <?php echo $this->translate("Titre d'accès<br/>à l'inscr. en thèse") ?>
            </dt>
            <dd>
                <?php
                echo ($titreAcces = $these->getTitreAcces()) ?: "(Non renseigné)";
                ?>
            </dd>

            <dt>
                <?php echo $this->translate("Unité de recherche"); ?>
            </dt>
            <dd>
                <?php
                if ($these->getUniteRecherche()) {
                    echo /*$these->getUniteRecherche()->getSourceCode() . " - " .*/
                    $these->getUniteRecherche()->getLibelle();
                } elseif ($these->getCodeUniteRecherche() && $these->getLibelleUniteRecherche()) {
                    echo $these->getCodeUniteRecherche() . " - " . $these->getLibelleUniteRecherche();
                    echo "<div class='alert alert-sm alert-warning'>";
                    echo "<span class='glyphicon glyphicon-warning-sign'></span> Utilisation du champs libre (unité de recherche mal renseignée).";
                    echo "</div>";
                } else {
                    echo "<div class='alert alert-sm alert-warning'>";
                    echo "<span class='glyphicon glyphicon-warning-sign'></span> Aucune unité de recherche n'est renseignée";
                    echo "</div>";
                }
                ?>

            </dd>

            <dt>
                Établissements de <br/>
                rattachement de <br/>
                l'unité de recherche
            </dt>
            <dd>
                <?php
                if (empty($rattachements)) {
                    echo "(Aucun établissement de rattachement renseigné)";
                } else {
                    foreach ($rattachements as $rattachement) {
                        echo $rattachement->getEtablissement()->getLibelle();
                        echo "<br/>";
                    }
                }
                ?>
            </dd>


            <dt>
                <?php echo $this->translate("École doctorale"); ?>
            </dt>
            <dd>
                <?php if ($these->getEcoleDoctorale()) {
                    echo /*$these->getEcoleDoctorale()->getSourceCode() . " - " .*/
                    $these->getEcoleDoctorale()->getLibelle();
                } else {
                    echo "<div class='alert alert-sm alert-warning'>";
                    echo "<span class='glyphicon glyphicon-warning-sign'></span> Aucune école doctorale n'est renseignée.";
                    echo "</div>";
                }
                ?>
            </dd>

            <dt>
                Financement(s)
            </dt>
            <dd>
                <?php if ($these->getFinancements()->isEmpty()): ?>
                    (Non renseigné)
                <?php else: ?>
                    <?php echo $financementFormatter->format($these->getFinancements()->toArray()); ?>
                <?php endif ?>
            </dd>

            <dt>
                <?php echo $this->translate("Titre"); ?>
            </dt>
            <dd>
                <?php echo $these->getTitre() ?>
            </dd>

            <dt>
                <?php echo $this->translate("Confidentialité"); ?>
            </dt>
            <?php if ($these->etaitConfidentielle()): ?>
                <dd>Confidentielle, jusqu'au <?php echo $these->getDateFinConfidentialiteToString() ?></dd>
            <?php elseif ($these->estConfidentielle()): ?>
                <dd class="text-danger">Confidentielle,
                    jusqu'au <?php echo $these->getDateFinConfidentialiteToString() ?></dd>
            <?php else: ?>
                <dd>Non confidentielle</dd>
            <?php endif ?>

            <dt>État</dt>
            <dd>
                <span class="label label-default"><?php echo $these->getEtatTheseToString() ?></span>
            </dd>

            <?php if ($resultat = $these->getResultatToString(false)): ?>
                <dt>Résultat</dt>
                <dd>
                    <?php echo $resultat ?>
                </dd>
            <?php endif ?>

            <dt>Discipline</dt>
            <dd><?php echo $these->getLibelleDiscipline() ?></dd>

            <dt>Date de 1ère<br>inscription</dt>
            <dd><?php echo $these->getDatePremiereInscriptionToString() ?: "(Non renseignée)" ?></dd>

            <dt>Année universitaire<br>de 1ère inscription</dt>
            <dd><?php echo $these->getAnneeUniv1ereInscription() ?></dd>

            <dt>Années universitaires<br>d'inscription</dt>
            <dd><?php echo $these->getAnneesUnivInscriptionToString('<br>') ?: "(Non renseignée)" ?></dd>

            <?php if ($these->getDateAbandon()): ?>
            <dt>Date d'abandon</dt>
            <dd><?php echo $these->getDateAbandonToString() ?></dd>
            <?php endif ?>

            <?php if ($these->getDateTransfert()): ?>
            <dt>Date de transfert
            <dd><?php echo $these->getDateTransfertToString() ?></dd>
            <?php endif ?>

            <?php if ($these->getSoutenanceAutorisee()): ?>
                <dt>Soutenance autorisée</dt>
                <dd><?php echo $these->getSoutenanceAutorisee() === 'O' ? "Oui" : "Non" ?></dd>
            <?php endif ?>

            <?php if ($these->getDateSoutenance()): ?>
                <dt>Date réelle<br>de soutenance</dt>
                <dd><?php echo $these->getDateSoutenanceToString() ?></dd>
            <?php else: ?>
                <!--<dt>Date prévisionnelle<br>de soutenance</dt>
                <dd><?php /*echo $these->getDatePrevisionSoutenanceToString() ?: "(Non renseignée)" */?></dd>-->
            <?php endif ?>

            <?php if ($these->getLibelleEtabCotutelle()): ?>
                <dt>Cotutelle</dt>
                <dd>En cotutelle avec <?php echo $these->getLibelleEtabCotutelle() ?>,
                    <?php echo $these->getLibellePaysCotutelle() ?></dd>
            <?php endif ?>

            <!------------------------------- Corrections attendues --------------------------------->
            <?php
            $titre = "Corrections attendues";
            $reponse = "Non.";
            $message = null;
            $class = null;

            $validationsDesCorrectionsEnAttente = [1]; //////////////////////

            if ($these->isCorrectionAutorisee()) {
                $dateButoirDepassee =
                    $these->isDateButoirDepotVersionCorrigeeDepassee() &&
                    ! empty($validationsDesCorrectionsEnAttente);

                if ($these->getCorrectionAutoriseeEstFacultative()) {
                    $class = "text-warning";
                    $reponse = "Oui, facultatives.";
                    $message = $dateButoirDepassee ?
                        "<strong>Trop tard, le délai pour corrections facultatives est écoulé : la version déposée avant soutenance constitue désormais la version de référence.</strong>" :
                        null;
                } elseif ($these->getCorrectionAutoriseeEstObligatoire()) {
                    $class = "text-danger";
                    $reponse = "Oui, obligatoires.";
                    $message = $dateButoirDepassee ?
                        "<strong>Trop tard, le délai pour corrections obligatoires est écoulé : ni l’attestation de réussite ni le diplôme ne peuvent désormais être délivrés.</strong>" :
                        null;
                }
                if (is_array($validationsDesCorrectionsEnAttente) && empty($validationsDesCorrectionsEnAttente)) {
                    $titre = "Corrections";
                    $message = sprintf("Les corrections %s ont été validées.", lcfirst($these->getCorrectionAutoriseeToString(true)));
                    $canEditForcageCorrectionAutorisee = false;
                }
            }
            ?>
            <dt class="<?php echo $class ?>"><?php echo $titre ?></dt>
            <dd class="<?php echo $class ?>">
                <p>
                    <?php echo $reponse ?>
                    <?php if ($canEditForcageCorrectionAutorisee): ?>
                        <?php if ($these->isCorrectionAutoriseeForcee()): ?>
                            <em>Cette valeur est forcée.</em>
                        <?php endif ?>
                        <a href="<?php echo $modifierCorrecAutorUrl ?>" class="btn btn-xs btn-info ajax-modal"
                           data-event="event-correction-autorisee-forcee-modified"
                           title="Forçage du témoin de corrections attendues"
                        >Forçage</a>
                    <?php endif ?>
                </p>
                <?php if ($these->isCorrectionAutorisee()): ?>
                    <?php if ($dateSoutenance = $these->getDateSoutenance()): ?>
                        <p>
                            Date butoir :
                            <?php if ($these->getDateButoirDepotVersionCorrigeeAvecSursis()): ?>
                                <?php echo $these->getDateButoirDepotVersionCorrigeeAvecSursisToString() ?> (sursis inclus)
                            <?php else: ?>
                                <abbr title="<?php echo $these->getDelaiDepotVersionCorrigeeToString() ?> après la date de soutenance">
                                    <?php echo $these->getDateButoirDepotVersionCorrigeeFromDateSoutenanceToString($dateSoutenance) ?>
                                </abbr>
                            <?php endif ?>
                            <?php if ($this->isAllowed($these, ThesePrivileges::THESE_CORREC_AUTORISEE_ACCORDER_SURSIS)): ?>
                                <a href="<?php echo $accorderSursisCorrecUrl ?>" class="btn btn-xs btn-info ajax-modal"
                                   data-event="event-sursis-correction-modified"
                                   title="Accorder un sursis"
                                >Accorder un sursis</a>
                            <?php endif ?>
                        </p>
                    <?php endif ?>
                <?php endif ?>
                <?php if ($message): ?>
                    <p>
                        <?php echo $message ?>
                    </p>
                <?php endif ?>
            </dd>

        </dl>
    </div>

</div>


<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });

    $(function () {
        var body = $("body");

        body.one("<?php echo $persopassModifiedEvent ?>", function (event, data) {
            // Le persopass vient d'être modifié.
            event.div.modal('hide'); // ferme la fenêtre modale
            window.location.reload();
        });
        body.one("event-correction-autorisee-forcee-modified", function (event) {
            event.div.modal('hide'); // ferme la fenêtre modale
            window.location.reload();
        });
        body.one("event-sursis-correction-modified", function (event) {
            event.div.modal('hide'); // ferme la fenêtre modale
            window.location.reload();
        });

        // $(window).load(function () {
        //     $(".photo-placeholder").each(function () {
        //         loadPhoto(this);
        //     });
        // });
    });

    // function loadPhoto(photoPlaceholder) {
    //     debugger;
    //     var photoUrl = $(photoPlaceholder).data('src');
    //
    //     //create image to preload:
    //     var imgPreload = new Image();
    //     $(imgPreload).load(function (response, status, xhr) {
    //         if (status == 'error') {
    //             imgPreload = null;
    //         }
    //         insertResult();
    //     });
    //     $(imgPreload).attr({
    //         src: photoUrl,
    //         width: $(photoPlaceholder).css('width')
    //     });
    //
    //     function insertResult() {
    //         var content = imgPreload ? $(imgPreload) : $("<span />").html("Erreur!");
    //         $(photoPlaceholder).removeClass('loading').replaceWith(content);
    //     }
    // }
</script>