<?php

use Application\Entity\Db\Role;
use Application\Entity\Db\These;
use Application\Filter\ActeursFormatter;
use Application\Provider\Privilege\ExportPrivileges;
use Application\Provider\Privilege\ThesePrivileges;
use Application\View\Renderer\PhpRenderer;
use UnicaenAuth\Guard\PrivilegeController;
use UnicaenAuth\Provider\Privilege\Privileges;
use Zend\Paginator\Paginator;

/**
 * @var PhpRenderer $this
 * @var Paginator   $theses
 * @var string      $text
 * @var Role        $roleDirecteurThese
 */

$canExport = $this->isAllowed(Privileges::getResourceId(ThesePrivileges::THESE_EXPORT_CSV));
Locale::setDefault("fr_FR");

$queryParams = $this->queryParams();

$acteursFormatter = new ActeursFormatter();
//TODO (JP) faire quelque chose de plus robuste ...
$acteursFormatter->asSeparated()
    ->paramDisplay(['role' => false, 'complement' => false, "qualite" => false, "etablissement" => false,])
    ->paramFilter((['role' => "Directeur de thèse UCN"]));
?>

<?php $this->headTitle($this->translate("Thèses")); ?>

<h1 class="page-header">
    <?php echo $this->translate("Thèses"); ?>
</h1>
<!-- Formulaire de filtrage -->
<div class="pull-left">
    <?php echo $this->partial('partial/form-filtrage') ?>
</div>
<!-- Formulaire de recherche -->
<div class="pull-right">
    <?php echo $this->partial('partial/form-recherche', ['text' => $text]) ?>
</div>
<div class="clearfix"></div>

<p>
    <?php
        echo $theses->getTotalItemCount();
        echo " ";
        echo $this->translate("thèse(s) trouvée(s).");
    ?>
</p>

<table class="table table-condensed">
    <thead>
    <tr>
        <th>
            <a href="<?php echo $s = $this->sortable('t.titre'); ?>"
               title="<?php echo $this->translate("Titre de la thèse");?> ">
                    <?php echo $this->translate("Titre"); ?>
            </a> <?php echo $s->icon() ?>
        </th>
        <th>
            <a href="<?php echo $s = $this->sortable('t.etatThese'); ?>"
               title="<?php echo $this->translate("État de la thèse");?> ">
                <?php echo $this->translate("État"); ?>
            </a>
        </th>
        <th>
            <a href="<?php echo $s = $this->sortable('th.sourceCode'); ?>"
               title="<?php echo $this->translate("Numéro étudiant"); ?>">
                    <?php echo $this->translate("N°étud."); ?>
            </a> <?php echo $s->icon() ?>
        </th>
        <th>
            <a href="<?php echo $s = $this->sortable('di.nomUsuel+di.prenom1'); ?>"
               title="<?php echo $this->translate("Nom du doctorant"); ?>">
                <?php echo $this->translate("Doctorant"); ?>
            </a> <?php echo $s->icon() ?>
        </th>
        <th>
            <span title="<?php echo $this->translate("Liste des directeurs de thèse"); ?>">
                <?php echo $this->translate("Dir. de thèse"); ?>
            </span>
        </th>
        <th>
            <a href="<?php echo $s = $this->sortable('ed.sourceCode'); ?>"
               title="<?php echo $this->translate("École doctorale");?>">
                <?php echo $this->translate("École<br>doct.");?>
            </a> <?php echo $s->icon() ?>
        </th>
        <th>
            <a href="<?php echo $s = $this->sortable('ur.sourceCode'); ?>"
               title="<?php echo $this->translate("Unité de recherche"); ?>">
                <?php echo $this->translate("Unité<br>rech."); ?>
            </a> <?php echo $s->icon() ?></th>
        <th>
            <a href="<?php echo $s = $this->sortable('t.datePremiereInscription'); ?>"
               title="<?php echo $this->translate("Date de première inscription");?>">
                <?php echo $this->translate("Date 1ère<br>inscr."); ?>
            </a> <?php echo $s->icon() ?>
        </th>
    </tr>
    </thead>

    <tbody>
    <?php /** @var These $these */
    foreach ($theses as $these): ?>
        <tr>
            <td>
                <span title="<?php echo $these->getTitre() ?>">
                    <a href="<?php echo $this->url('these/identite', ['these' => $these->getId()], [], true) ?>">
                        <?php echo $this->partial('application/these/partial/titre', ['these' => $these, 'useTitreThese' => true]) ?>
                    </a>
                </span>
            </td>
            <td><?php echo $these->getEtatThese() ?></td>
            <td><?php echo $these->getDoctorant()->getSourceCode() ?></td>
            <td><?php echo $these->getDoctorant()->getIndividu()->getNomComplet() ?></td>
            <td class="acteurs">

                <?php
                $directeurs = $acteursFormatter->filter($these->getActeurs());
                foreach ($directeurs as $directeur) {
                    echo $acteursFormatter->htmlifyActeur($directeur)."<br/>";
                }
                ?>
            </td>
            <td>
                <?php if($these->getEcoleDoctorale()): ?>
                <abbr title="<?php echo $these->getEcoleDoctorale()->getLibelle() ?>"><?php echo $these->getEcoleDoctorale()->getSourceCode() ?></abbr>
                <?php endif ?>
            </td>
            <td><abbr title="<?php echo $these->getLibelleUniteRecherche() ?>"><?php echo $these->getCodeUniteRecherche() ?></abbr></td>
            <td><?php
                echo $this->dateFormat($these->getDatePremiereInscription(),IntlDateFormatter::MEDIUM);
                ?>
            </td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>

<?php echo $paginationControl = $this->paginationControl($theses, 'sliding', 'partial/paginator.phtml', ['route' => 'these']) ?>

<?php if ($canExport): ?>
    <a class="btn btn-default" href="<?php echo $this->url('export/csv', [], ['query' => $queryParams]) ?>">
        <span class="glyphicon glyphicon-export"></span>
        <?php echo $this->translate("Exporter au format CSV"); ?>
    </a>
<?php endif ?>


<?php
    $this->translate("Filtres");
    $this->translate("État");
    $this->translate("En cours");
    $this->translate("Abandonnée");
    $this->translate("Soutenue");
    $this->translate("Transférée");
    $this->translate("Tous");

    $this->translate("Rechercher");
    $this->translate("Vider");
    $this->translate("Entrez 2 caractères au moins...");
    $this->translate("Recherche possible sur<ul><li>le titre de la thèse</li><li>le numéro étudiant de l'auteur</li><li>le nom de l'auteur</li><li>le nom du directeur ou co-directeur de thèse</li><li>le code national de l'école doctorale concernée (ex: 181)</li><li>l'unité de recherche concernée (ex: umr6211)</li></ul>");
?>
