<?php

use Application\Controller\TheseController;
use Application\Entity\Db\Diffusion;
use Application\Entity\Db\Repository\FichierTheseRepository;
use Application\Entity\Db\These;
use Application\Entity\Db\Validation;
use Application\Provider\Privilege\ThesePrivileges;
use Application\Provider\Privilege\ValidationPrivileges;
use Application\View\Renderer\PhpRenderer;
use UnicaenApp\Service\MessageCollector;

/**
 * @var PhpRenderer            $this
 * @var These                  $these
 * @var Diffusion              $diffusion
 * @var bool                   $estDoctorant
 * @var string                 $modifierUrl
 * @var string                 $validerUrl
 * @var string                 $devaliderUrl
 * @var Validation|null        $validation
 * @var MessageCollector       $msgCollector
 * @var string                 $nextStepUrl
 * @var FichierTheseRepository $fichierRepository
 * @var boolean                $asynchronous
 *
 * @see TheseController::detailRdvBuAction()
 */

$canEdit = $this->isAllowed($these, ThesePrivileges::THESE_SAISIE_RDV_BU);
$canValidate = $this->isAllowed($these, ValidationPrivileges::THESE_VALIDATION_RDV_BU);
$canUnvalidate = $this->isAllowed($these, ValidationPrivileges::THESE_VALIDATION_RDV_BU_SUPPR);

$rdvBu = $these->getRdvBu();
?>

<?php $this->headTitle("Rendez-vous avec la bibliothèque universitaire")->prepend($these->getDoctorant()->getNomUsuel()) ?>

<h1 class="page-header">Rendez-vous avec la bibliothèque universitaire
    <small><?php echo $this->partial('application/these/partial/titre') ?></small>
</h1>

<div class="card box">
    <div class="card-header bg-info">
        <h2 class="first">Téléchargement de la version imprimable</h2>
    </div>
    <div class="card-body">
        <p>
        <?php if ($diffusion->isRemiseExemplairePapierRequise()): ?>
            Suite à votre choix de mise en ligne, vous devez imprimer un exemplaire papier de votre thèse et le rapporter lors du Rendez-vous à la BU.
            Pour obtenir la version imprimable de votre thèse (avec page de couverture), veuillez cliquer sur le bouton ci-dessous.
        <?php else: ?>
            Si vous souhaitez obtenir une version complète de votre thèse (avec page de couverture), cliquez sur le bouton ci-dessous.
        <?php endif ?>
        </p>
        <div class="checkbox checkbox-sm">
            <label for="removal" class="form-label">
                <input type="checkbox" id="removal" class="form-check-input"/>
                <span class="checkbox-label">La 1ère page du corps du mémoire est une page de couverture fournie par le doctorant et je veux retirer cette 1ère page.</span>
            </label>
        </div>
        <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuButton" aria-haspopup="true" aria-expanded="false">
                Version à récupérer
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item complete" href="<?php echo $this->url('these/fusion', ['these' => $these->getId(), 'corrigee' => 0, 'version' => 'VO'], [], true); ?>">Version originale</a>
                <a class="dropdown-item removal" href="<?php echo $this->url('these/fusion', ['these' => $these->getId(), 'corrigee' => 0, 'version' => 'VO', 'removal' => true], [], true); ?>">Version originale</a>
                <?php if ($hasVD): ?>
                    <a class="dropdown-item complete" href="<?php echo $this->url('these/fusion', ['these' => $these->getId(), 'corrigee' => 0, 'version' => 'VD'], [], true); ?>">Version diffusion</a>
                    <a class="dropdown-item removal" href="<?php echo $this->url('these/fusion', ['these' => $these->getId(), 'corrigee' => 0, 'version' => 'VD', 'removal' => true], [], true); ?>">Version diffusion</a>
                <?php endif; ?>
                <?php if ($hasVA): ?>
                    <a class="dropdown-item complete" href="<?php echo $this->url('these/fusion', ['these' => $these->getId(), 'corrigee' => 0, 'version' => 'VA' ], [], true); ?>">Version archivable</a>
                    <a class="dropdown-item removal" href="<?php echo $this->url('these/fusion', ['these' => $these->getId(), 'corrigee' => 0, 'version' => 'VA', 'removal' => true ], [], true); ?>">Version archivable</a>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<?php if ($asynchronous): ?>
<script>
alert("Le traitement peut prendre plusieurs minutes. \n\n" +
    "Une fois celui-ci terminé vous recevrez un courriel électronique vous permettant \n" +
    "de télécharger votre manuscrit complet. "
);
</script>
<?php endif;?>


<div class="card box">
    <div class="card-header bg-info">
        <h2 class="first">Rendez-vous avec la bibliothèque universitaire</h2>
    </div>
    <div class="card-body">
        <?php echo $this->messenger()->addMessagesFromFlashMessengerWithNamespace('RdvBu/*'); ?>
        <?php if ($rdvBu): ?>
            <div class="row">
                <div class="col-md-4">
                    <h2 class="first">Doctorant</h2>
                    <dl class="rdv-bu">
                        <dt>Téléphone :</dt>
                        <dd><?php echo $this->escapeText()->render($rdvBu->getCoordDoctorant()) ?: "(Non renseignées)" ?></dd>
                        <dt>Disponibilités :</dt>
                        <dd><?php echo $this->escapeText()->render($rdvBu->getDispoDoctorant()) ?: "(Non renseignées)" ?></dd>
                    </dl>
                </div>
                <div class="col-md-8">
                    <h2 class="first">Bibliothèque universitaire</h2>
                    <?php echo $this->partial('application/these/partial/rdv-bu') ?>
                </div>
            </div>
            <?php if ($canEdit): ?>
                <a href="<?php echo $modifierUrl ?>"
                   class="btn btn-secondary ajax-modal"
                   data-event="event-rdv-bu-modified"><span class="icon icon-edit"></span> Modifier</a>
            <?php endif ?>
        <?php else: ?>
            <p>Vous n'avez pas encore completé les informations concernant le rendez-vous à la bibliothèque universitaire.</p>
            <?php if ($canEdit): ?>
                <a href="<?php echo $modifierUrl ?>"
                   class="btn btn-primary ajax-modal"
                   data-event="event-rdv-bu-modified"><span class="icon icon-edit"></span> Compléter</a>
            <?php endif ?>
        <?php endif ?>
    </div>
</div>

<div class="card box">
    <div class="card-header bg-info">
        <h2 class="first">Validation</h2>
    </div>
    <div class="card-body">
        <?php if ($validation): ?>
            <?php echo $this->validation($validation) ?>
            <?php if ($canUnvalidate): ?>
                <a href="<?php echo $devaliderUrl ?>"
                   class="btn btn-danger ajax-modal"
                   data-event="event-rdv-bu-validated"><span class="icon icon-delete"></span> Annuler la validation</a>
            <?php endif ?>
        <?php else: ?>
            <p>Aucune.</p>
            <?php if ($canValidate): ?>
                <a href="<?php echo $validerUrl ?>"
                   class="btn btn-success ajax-modal"
                   data-event="event-rdv-bu-validated"><span class="fas fa-thumbs-up"></span> Valider</a>
            <?php //elseif ($msgCollector->hasMessages($etape = WfEtape::CODE_RDV_BU_VALIDATION_BU)): ?>
                <?php
    //            $message = "La validation n'est pas possible pour la raison suivante : " .
    //                lcfirst($msgCollector->getMessage('<br>', WfEtape::CODE_RDV_BU_VALIDATION_BU));
    //            echo $this->messenger()->addMessage($message);
                ?>
            <?php endif ?>
        <?php endif ?>
    </div>
</div>

<!-------------------------------------- Next step --------------------------------------->
<div id="nextStepDiv" data-url="<?php echo $nextStepUrl ?>" style="display: none">
    <!-- màj via ajax -->
</div>

<?php //echo $this->partial('next-step-box', ['these' => $these, 'etape' => WfEtape::CODE_RDV_BU_VALIDATION_BU]) ?>


<script>
    $(".removal").hide();

    $(function () {
        var refreshingNextStep = function(done, effect) {
            return function() {
                $("#nextStepDiv").addClass("loading").refresh(null, function () {
                    $(this).removeClass("loading").show();
                    if (done) done();
                });
            };
        };

        // au chargement de la page, on actualise toutes les div en cascade.
        runInCascade([
            refreshingNextStep
        ], self);

        $("input#removal").on("change", function(event, data) {
            var test = $(this).is(':checked');
            if (test) {
                $(".removal").show();
                $(".complete").hide();
            } else {
                $(".removal").hide();
                $(".complete").show();

            }
        });

        $("body").one("event-rdv-bu-modified", function (event, data) {
            // Les données viennent d'être modifiées.
            event.div.modal('hide'); // ferme la fenêtre modale
            window.location.reload();
        }).one("event-rdv-bu-validated", function (event, data) {
            // La validation vient d'être saisie.
            event.div.modal('hide'); // ferme la fenêtre modale
            window.location.reload();
        });
    });
</script>