<?php

use Application\Entity\Db\Diffusion;
use Application\Entity\Db\These;
use Application\Entity\Db\Validation;
use Application\Provider\Privilege\ThesePrivileges;
use Application\View\Renderer\PhpRenderer;
use UnicaenApp\View\Helper\Messenger;

/**
 * @var                 $this PhpRenderer
 * @var These           $these
 * @var Diffusion       $diffusion
 * @var bool            $estDoctorant
 * @var string          $modifierUrl
 * @var Validation|null $validation
 * @var string          $nextStepUrl
 */

$canEdit = $this->isAllowed($these, ThesePrivileges::THESE_SAISIE_RDV_BU);

$rdvBu = $these->getRdvBu();
?>

<?php $this->headTitle("Rendez-vous avec la bibliothèque universitaire")->prepend($these->getDoctorant()->getNomUsuel()) ?>

<h1 class="page-header">Rendez-vous avec la bibliothèque universitaire
    <small><?php echo $this->partial('application/these/partial/titre') ?></small>
</h1>

<div class="card box">
    <div class="card-header bg-info">
        <h2 class="first">Téléchargement de la version imprimable de votre thèse</h2>
    </div>
    <div class="card-body">

        <p>
            <?php if ($diffusion->isRemiseExemplairePapierRequise()): ?>
                Suite à votre choix de mise en ligne, vous devez imprimer un exemplaire papier de votre thèse et le rapporter lors du Rendez-vous à la bibliothèque universitaire.
                Pour obtenir la version imprimable de votre thèse (avec page de couverture), veuillez cliquer sur le bouton ci-dessous.
            <?php else: ?>
                Si vous souhaitez obtenir une version complète de votre thèse (avec page de couverture), cliquez sur le bouton ci-dessous.
            <?php endif ?>
        </p>

<!--        <div class="float-end">-->
            <a href="<?php echo $this->url("these/fusion", ["these" => $these->getId()], [], true); ?>" target="_blank">
                <button class="btn btn-primary">
                    <span class="icon icon-download"></span>
                    Obtenir la version imprimable de votre thèse
                </button>
            </a>
<!--        </div>-->

    </div>
</div>


<div class="card box">
    <div class="card-header bg-info">
        <h2 class="first">Doctorant</h2>
    </div>
    <div class="card-body">
        <?php if ($rdvBu): ?>
            <dl class="rdv-bu">
                <dt>Téléphone :</dt>
                <dd><?php echo $this->escapeText()->render($rdvBu->getCoordDoctorant()) ?: "(Non renseignées)" ?></dd>
                <dt>Disponibilités :</dt>
                <dd><?php echo $this->escapeText()->render($rdvBu->getDispoDoctorant()) ?: "(Non renseignées)" ?></dd>
            </dl>
            <?php if (! $validation): ?>
                <?php echo $this->messenger()->setMessage(
                    "Votre dépôt est terminé, la BU va prendre contact avec vous pour finaliser la procédure.", Messenger::INFO) ?>
            <?php endif ?>
        <?php endif ?>
        <?php if ($canEdit): ?>
            <?php if ($rdvBu): ?>
                <a href="<?php echo $modifierUrl ?>"
                   class="btn btn-secondary text-center ajax-modal"
                   data-event="event-rdv-bu-modified"><span
                        class="icon icon-edit"></span> Modifier</a>
            <?php else: ?>
                <a href="<?php echo $modifierUrl ?>"
                   class="btn btn-primary text-center ajax-modal"
                   data-event="event-rdv-bu-modified"><span
                        class="icon icon-edit"></span> Compléter les informations nécessaires à la prise de rendez-vous avec la bibliothèque universitaire</a>
            <?php endif ?>

        <?php endif ?>
    </div>
</div>

<div class="card box">
    <div class="card-header bg-info">
        <h2 class="first">Bibliothèque universitaire</h2>
    </div>
    <div class="card-body">
        <?php if ($rdvBu): ?>
            <?php echo $this->partial('application/these/partial/rdv-bu') ?>
        <?php else: ?>
            <p>La bibliothèque universitaire n'a pas encore completé les informations concernant votre rendez-vous avec elle.</p>
        <?php endif ?>
    </div>
</div>

<div class="card box">
    <div class="card-header bg-info">
        <h2 class="first">Validation</h2>
    </div>
    <div class="card-body">
        <?php if ($validation): ?>
            <?php echo $this->validation($validation) ?>
        <?php else: ?>
            <p>Aucune.</p>
        <?php endif ?>
    </div>
</div>

<!-------------------------------------- Next step --------------------------------------->
<div id="nextStepDiv" data-url="<?php echo $nextStepUrl ?>" style="display: none">
    <!-- màj via ajax -->
</div>


<script>
    $(function () {
        var self = this;

        var refreshingNextStep = function(done, effect) {
            return function() {
                $("#nextStepDiv").addClass("loading").refresh(null, function () {
                    $(this).removeClass("loading").show();
                    if (done) done();
                });
            };
        };

        // au chargement de la page, on actualise toutes les div en cascade.
        runInCascade([
            refreshingNextStep
        ], self);

        $("body").one("event-rdv-bu-modified", function (event, data) {
            // Les données viennent d'être modifiées.
            event.div.modal('hide'); // ferme la fenêtre modale
            window.location.reload();
        });
    });
</script>