<?php

use Application\Form\Factory\RecapBuFormFactory;

use Application\Entity\Db\These;
use Application\Form\RecapBuForm;
use Application\Entity\Db\Validation;
use Application\Entity\Db\WfEtape;
use Application\Provider\Privilege\ThesePrivileges;
use Application\Provider\Privilege\ValidationPrivileges;
use Application\View\Renderer\PhpRenderer;
use UnicaenApp\Service\MessageCollector;
use Application\Entity\Db\Repository\FichierRepository;

/**
 * @var These               $these
 * @var RecapBuForm         $form
 */


$recap = new \Application\Form\RecapBuForm();
?>

<?php $this->headTitle("Récapitulatif BU")->prepend($these->getDoctorant()->getNomUsuel()) ?>

<h1 class="page-header">Points de vigilance
    <small><?php echo $this->partial('application/these/partial/titre') ?></small>
</h1>

<?php
$messenger = $this->messenger();
echo $messenger->addMessagesFromFlashMessenger();
?>

<?php if ($form !== null): ?>
    <?php
    $fcg = $this->formControlGroup();
    $form->prepare();

    echo $this->form()->openTag($form->setAttribute('class', 'attestations'));
//    echo $fcg->render($form->get('orcid'));
//    echo $fcg->render($form->get('nnt'));
    echo $fcg->render($form->get('vigilance'));
    echo $fcg->render($form->get('submit'));
    echo $this->form()->closeTag()
    ?>
<?php else:?>
<p>
    L'accés au récapitulatif est disponible une fois les informations de diffusion et du rendez-vous bu saisies.
</p>
<?php endif; ?>

