<?php

use Application\Entity\Db\These;
use Application\Entity\Db\TypeValidation;
use Application\Entity\Db\Validation;
use Application\Provider\Privilege\ThesePrivileges;
use Application\Provider\Privilege\ValidationPrivileges;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer      $this
 * @var These            $these
 * @var string           $validationDepotTheseCorrigeeUrl
 * @var string           $validationCorrectionTheseUrl
 * @var TypeValidation   $typeValidation
 * @var Validation|null  $validation
 * @var string           $nextStepUrl
 * @var bool             $isDoctorant
 * @var bool             $hasVDC
 * @var bool             $hasVAC
 */

$canValidate = $this->isAllowed($these, ValidationPrivileges::VALIDATION_DEPOT_THESE_CORRIGEE);
$canUnvalidate = $this->isAllowed($these, ValidationPrivileges::VALIDATION_DEPOT_THESE_CORRIGEE);

?>

<?php $this->headTitle("Validations")->prepend($these->getDoctorant()->getNomUsuel()) ?>

<h1 class="page-header">Validations
    <small><?php echo $this->partial('application/these/partial/titre') ?></small>
</h1>

<div>
    <div class="panel panel-info">
        <div class="panel-heading"> <h2 class="first">Téléchargement de la thèse corrigée complète </h2></div>
        <div class="panel-body">

        <p>
            Vous pouvez télécharger ici la version finale du manuscrit de thèse.
        </p>

        <!-- if doctorant -->
            <?php if ($isDoctorant): ?>
            <a href="<?php echo $this->url("these/fusion", ["these" => $these->getId(), "corrigee" => 1], [], true); ?>" target="_blank">
                <button class="btn btn-primary">
                    <span class="glyphicon glyphicon-download"></span>
                    Obtenir la version imprimable de votre thèse
                </button>
            </a>
        <!-- else -->
            <?php else: ?>
            <div class="btn-group">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Version à récupérer <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <li class="complete"><a href="<?php echo $this->url('these/fusion', ['these' => $these->getId(), 'corrigee' => 1, 'version' => 'VOC'], [], true); ?>">Version originale corrigée</a></li>
                    <li class="removal"><a href="<?php echo $this->url('these/fusion', ['these' => $these->getId(), 'corrigee' => 1, 'version' => 'VOC', 'removal' => true], [], true); ?>">Version originale corrigée</a></li>
                    <?php if ($hasVDC): ?>
                        <li class="complete"><a href="<?php echo $this->url('these/fusion', ['these' => $these->getId(), 'corrigee' => 1, 'version' => 'VDC'], [], true); ?>">Version diffusion corrigée</a></li>
                        <li class="removal"><a href="<?php echo $this->url('these/fusion', ['these' => $these->getId(), 'corrigee' => 1, 'version' => 'VDC', 'removal' => true], [], true); ?>">Version diffusion corrigée</a></li>
                    <?php endif; ?>
                    <?php if ($hasVAC): ?>
                        <li class="complete"><a href="<?php echo $this->url('these/fusion', ['these' => $these->getId(), 'corrigee' => 1, 'version' => 'VAC' ], [], true); ?>">Version archivable corrigée</a></li>
                        <li class="removal"><a href="<?php echo $this->url('these/fusion', ['these' => $these->getId(), 'corrigee' => 1, 'version' => 'VAC', 'removal' => true ], [], true); ?>">Version archivable corrigée</a></li>
                    <?php endif; ?>
                </ul>
            </div>
            <div>
                <input type="checkbox" id="removal" /> Retrait de la page de couverture fournie par le doctorant.
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>

<!-------------------------------------- Validation dépôt thèse corrigée --------------------------------------->
<div id="validationDepotTheseCorrigeeDiv" data-url="<?php echo $validationDepotTheseCorrigeeUrl ?>">
    <!-- màj via ajax -->
</div>

<!-------------------------------------- Validation correction thèse --------------------------------------->
<div id="validationCorrectionTheseDiv" data-url="<?php echo $validationCorrectionTheseUrl ?>">
    <!-- màj via ajax -->
</div>

<!-------------------------------------- Next step --------------------------------------->
<div id="nextStepDiv" data-url="<?php echo $nextStepUrl ?>" style="display: none">
    <!-- màj via ajax -->
</div>



<script>
    $(".removal").hide();

    $(function () {
        var body = $("body");
        var self = this;

        var validationDepotTheseCorrigeeDiv = $("#validationDepotTheseCorrigeeDiv");
        var validationCorrectionTheseDiv    = $("#validationCorrectionTheseDiv");

        var validationDepotTheseCorrigeeDivLoader = function(done, effect) {
            return function() {
                validationDepotTheseCorrigeeDiv.addClass("loading").refresh(null, function () {
                    $(this).removeClass("loading");
                    if (effect) {
                        $(this).hide().fadeIn(250);
                    } else {
                        $(this).show();
                    }
                    if (done) done();
                });
            };
        };
        var validationCorrectionTheseDivLoader = function(done, effect) {
            return function() {
                validationCorrectionTheseDiv.addClass("loading").refresh(null, function () {
                    $(this).removeClass("loading");
                    if (effect) {
                        $(this).hide().fadeIn(250);
                    } else {
                        $(this).show();
                    }
                    if (done) done();
                });
            };
        };
        var refreshingNextStep = function(done, effect) {
            return function() {
                console.log("refreshingNextStep");
                $("#nextStepDiv").addClass("loading").refresh(null, function () {
                    $(this).removeClass("loading").show();
                    if (done) done();
                });
            };
        };

        // Au chargement de la page, on actualise les div
        runInCascade([
            { func: validationDepotTheseCorrigeeDivLoader, effect: true },
            { func: validationCorrectionTheseDivLoader, effect: true },
            refreshingNextStep
        ], self);

        $("input#removal").on("change", function(event, data) {
            var test = $(this).is(':checked');
            if (test) {
                $(".removal").show();
                $(".complete").hide();
            } else {
                $(".removal").hide();
                $(".complete").show();

            }
        });

        // Validation dépôt thèse corrigée enregistrée dans la modale
        body.on("event-validation-depot-these-corrigee", function (event) {
            // Les métadonnées viennent d'être modifiées.
            event.div.modal('hide'); // ferme la fenêtre modale
            runInCascade([
                { func: validationDepotTheseCorrigeeDivLoader, effect: true },
                { func: validationCorrectionTheseDivLoader, effect: true },
                refreshingNextStep
            ], self);
        });

        // Validation correction thèse enregistrée dans la modale
        body.on("event-validation-correction-these", function (event) {
            // Les métadonnées viennent d'être modifiées.
            event.div.modal('hide'); // ferme la fenêtre modale
            runInCascade([
                { func: validationCorrectionTheseDivLoader, effect: false },
                refreshingNextStep
            ], self);
        });
    });
</script>