<?php

use Application\Controller\TheseController;
use Application\Entity\Db\These;
use Application\Entity\Db\Validation;
use Application\Provider\Privilege\ValidationPrivileges;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var These       $these
 * @var Validation  $validation
 * @var string      $nextStepUrl
 *
 * @see TheseController::validationPageDeCouvertureAction()
 */

$canValidate = $this->isAllowed($these, ValidationPrivileges::VALIDATION_PAGE_DE_COUVERTURE);
$canUnvalidate = $this->isAllowed($these, ValidationPrivileges::VALIDATION_PAGE_DE_COUVERTURE_SUPPR);

$validerUrl = $this->url("validation/page-de-couverture", [], ['query' => ['action' => 'valider']], true);
$devaliderUrl = $this->url("validation/page-de-couverture", [], ['query' => ['action' => 'devalider']], true);
?>

<?php $this->headTitle($this->translate("Page de couverture"))->prepend($these->getDoctorant()->getNomUsuel()) ?>

<h1 class="page-header">
    <?php echo $this->translate("Page de couverture"); ?>
    <small><?php echo $this->partial('application/these/partial/titre') ?></small>
</h1>

<p class="lead">
    Après avoir visualisé la page de couverture générée par l'application, vous devez la valider pour
    que le doctorant puisse procéder au dépôt de sa thèse.
</p>

<div class="box panel panel-info">

    <div class="panel-heading">
        <h2 class="first">
            <?php echo $this->translate("Validation de la page de couverture"); ?>
        </h2>
    </div>

    <div class="panel-body">
        <p>
            <a class="btn btn-info" href="<?php echo $this->url("these/generate", [], [], true) ?>">Visualiser la page
                de couverture</a>
        </p>
        <hr>
        <?php if ($validation): ?>
            <?php echo $this->validation($validation) ?>
            <?php if ($canUnvalidate): ?>
                <a href="<?php echo $devaliderUrl ?>"
                   class="btn btn-danger ajax-modal"
                   data-event="event-page-de-couverture-validated"><span class="glyphicon glyphicon-trash"></span>
                    Annuler la validation la page de couverture</a>
            <?php endif ?>
        <?php else: ?>
            <p>Aucune validation.</p>
            <?php if ($canValidate): ?>
                <a href="<?php echo $validerUrl ?>"
                   class="btn btn-success ajax-modal"
                   data-event="event-page-de-couverture-validated"><span class="glyphicon glyphicon-thumbs-up"></span>
                    Valider la page de couverture</a>
            <?php endif ?>
        <?php endif ?>
    </div>

</div>

<!-------------------------------------- Next step --------------------------------------->
<div id="nextStepDiv" data-url="<?php echo $nextStepUrl ?>" style="display: none">
    <!-- màj via ajax -->
</div>


<script>
    $(function () {
        var refreshingNextStep = function(done, effect) {
            return function() {
                $("#nextStepDiv").addClass("loading").refresh(null, function () {
                    $(this).removeClass("loading").show();
                    if (done) done();
                });
            };
        };

        // au chargement de la page, on actualise toutes les div en cascade.
        runInCascade([
            refreshingNextStep
        ], self);

        $("body").one("event-page-de-couverture-validated", function (event, data) {
            // La validation vient d'être saisie.
            event.div.modal('hide'); // ferme la fenêtre modale
            window.location.reload();
        });
    });
</script>