<?php

use Application\Assertion\BaseAssertion;
use Application\Constants;use Application\Controller\TheseController;
use Application\Entity\Db\These;
use Application\Entity\Db\Validation;
use Application\Provider\Privilege\ThesePrivileges;
use Application\Provider\Privilege\ValidationPrivileges;
use Application\Service\FichierThese\PdcData;
use Application\View\Renderer\PhpRenderer;
use UnicaenApp\Service\MessageCollector;

/**
 * @var PhpRenderer $this
 * @var These       $these
 * @var Validation  $validation
 * @var string      $apercevoirPdcUrl
 * @var string      $refreshTheseUrl
 * @var string      $validerUrl
 * @var string      $devaliderUrl
 * @var string      $nextStepUrl
 * @var MessageCollector    $msgCollector
 * @var PdcData          $informations
 *
 * @see TheseController::validationPageDeCouvertureAction()
 */

$canRefreshThese = $this->isAllowed($these, ThesePrivileges::THESE_REFRESH);
$canValidate = $this->isAllowed($these, ValidationPrivileges::VALIDATION_PAGE_DE_COUVERTURE);
$canUnvalidate = $this->isAllowed($these, ValidationPrivileges::VALIDATION_PAGE_DE_COUVERTURE_SUPPR);
?>

<?php $this->headTitle($this->translate("Page de couverture"))->prepend($these->getDoctorant()->getNomUsuel()) ?>

<h1 class="page-header">
    <?php echo $this->translate("Page de couverture"); ?>
    <small><?php echo $this->partial('application/these/partial/titre') ?></small>
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNamespace('PageDeCouverture/*'); ?>

<div class="box panel panel-info">
    <div class="panel-heading">
        <h2 class="first">
            <?php echo $this->translate("Visualisation"); ?>
        </h2>
    </div>
    <div class="panel-body">
        <p>
            En cliquant sur le bouton ci-dessous, vous visualiserez la page de couverture que l'application est
            en mesure de générer automatiquement en l'état actuel des informations dont elle dispose.
        </p>
        <p>
            <a class="btn btn-info ajax-modal"
               href="<?php echo $apercevoirPdcUrl ?>"
               title="Cliquez pour afficher un aperçu de la page de couverture"
            ><span class="glyphicon glyphicon-eye-open"></span> Visualiser la page de couverture</a>
        </p>
    </div>
</div>

<?php
    $problemes = $informations->getWarnings()
?>

<?php if (!empty($problemes)): ?>
    <div class="box panel panel-warning">
        <div class="panel-heading">
            <h2 class="first">
                Données manquantes pour la génération de la page de couverture
            </h2>
        </div>
        <div class="panel-body">
            Liste des informations manquantes :
            <ul>
            <?php foreach ($problemes as $probleme): ?>
                <li> <?php echo $probleme; ?> </li>
            <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>

<!-- La mise à jour des données peut être faite tant que la page de couverture n'est pas validée -->
<?php if ($canRefreshThese && !$validation): ?>
    <div class="box panel panel-info">
        <div class="panel-heading">
            <h2 class="first">
                Mise à jour des données relatives à la thèse
            </h2>
        </div>
        <div class="panel-body">
            <p>
                Cliquez sur ce bouton pour importer tout de suite à partir de <?php echo $these->getSource() ?>
                les informations nécessaires à la génération de la page de couverture :
            </p>
            <p>
                <a class="btn btn-default btn-sm"
                   id="refresh-these-button"
                   href="<?php echo $refreshTheseUrl ?>"
                ><span class="glyphicon glyphicon-import"></span> <strong>Mettre à jour</strong> la thèse à partir de
                    <?php echo $these->getSource() ?></a>
            </p>
            <p class="small">
                Dernière mise à jour : <?php echo $these->getHistoModification()->format(Constants::DATETIME_FORMAT) ?>.
            </p>
        </div>
    </div>
<?php endif; ?>


<?php if ($validation || $canValidate || $canUnvalidate): ?>
<div class="box panel panel-info">
    <div class="panel-heading">
        <h2 class="first">
            <?php echo $this->translate("Validation"); ?>
        </h2>
    </div>
    <div class="panel-body">
        <?php if ($validation): ?>
            <?php echo $this->validation($validation) ?>
            <?php if ($canUnvalidate): ?>
                <a href="<?php echo $devaliderUrl ?>"
                   class="btn btn-danger ajax-modal"
                   data-event="event-page-de-couverture-validated-or-not"><span
                            class="glyphicon glyphicon-trash"></span>
                    Annuler la validation la page de couverture</a>
            <?php endif ?>
        <?php else: ?>
            <?php if ($canValidate): ?>
                <p>
                    Après avoir visualisé la page de couverture générée par l'application, si vous jugez qu'elle est
                    conforme, vous pouvez la valider en cliquant sur le bouton ci-dessous.
                </p>
                <p>
                    <a href="<?php echo $validerUrl ?>"
                       class="btn btn-success ajax-modal"
                       data-event="event-page-de-couverture-validated-or-not"><span
                                class="glyphicon glyphicon-thumbs-up"></span> Valider la page de couverture</a>
                </p>
                <p>
                    Une fois la page de couverture validée, le doctorant aura la main pour procéder au dépôt de sa thèse.
                </p>
            <?php else: ?>
                <?php
                $msgCollector = $this->messageCollector(BaseAssertion::class);
                $msgCollector->getMessengerHelper()->setContainerClassesToAdd('alert-danger');
                echo $msgCollector->render();
                ?>
            <?php endif ?>
        <?php endif ?>
    </div>
</div>
<?php endif ?>


<!-------------------------------------- Next step --------------------------------------->
<div id="nextStepDiv" data-url="<?php echo $nextStepUrl ?>" style="display: none">
    <!-- màj via ajax -->
</div>


<script>
    $(function () {
        $("#refresh-these-button").click(function() {
            $(this).css('min-width', $(this).width()).data("loading-text", "Patientez, svp...").button('loading');
            $("body").addClass("wait");
        });

        var refreshingNextStep = function (done, effect) {
            return function () {
                $("#nextStepDiv").addClass("loading").refresh(null, function () {
                    $(this).removeClass("loading").show();
                    if (done) done();
                });
            };
        };

        // au chargement de la page, on actualise toutes les div en cascade.
        runInCascade([
            refreshingNextStep
        ], self);

        $("body").one("event-page-de-couverture-validated-or-not", function (event, data) {
            // La validation vient d'être saisie.
            event.div.modal('hide'); // ferme la fenêtre modale
            window.location.reload();
        });
    });
</script>