<?php

use Application\View\Renderer\PhpRenderer;
use Structure\Entity\Db\Etablissement;
use These\Service\FichierThese\PdcData;
use These\Service\These\TheseService;

/**
 * @var PhpRenderer $this
 * @var PdcData $informations
 *
 * @see TheseService::fetchInformationsPageDeCouverture() pour la génération de $informations
 */
?>

<html lang="fr">

    <table class="logos header">
        <tr>
            <?php if ($informations->getLogoCOMUE() !== null): ?>
            <td>
                <?php if ($informations->getLogoCOMUE() !== null): ?>
                    <img src="<?php echo $informations->getLogoCOMUE() ?>" alt="Logo de la COMUE" class="logo"/>
                <?php else: ?>
                    <span style='background-color:red;'> Logo de la COMUE. </span>
                <?php endif; ?>
            </td>
            <?php endif; ?>
            <td>
                <?php if ($informations->getLogoEtablissement() !== null): ?>
                    <img src="<?php echo $informations->getLogoEtablissement() ?>" alt="Logo de l'établissement d'inscription" class="logo"/>
                <?php else: ?>
                    <span style='background-color:red;'> Logo de l'établissement non renseigné. </span>
                <?php endif; ?>
            </td>
        </tr>
    </table>

    <div class='bandeau-these'>
        <h1>
            THÈSE
        </h1>
    </div>

    <div class='infos-diplome'>
        <p>
            <span class="gras">Pour obtenir le diplôme de doctorat</span>
        </p>
        <p>
            Spécialité
            <span class="gras">
                <?php if ($informations->getSpecialite() !== null): ?>
                    <?php echo $informations->getSpecialite(); ?>
                <?php else: ?>
                    <span style='background-color:red;'> non renseignée </span>
                <?php endif; ?>
            </span>
        </p>
        <p>
            Préparée au sein de
            <?php if ($etab = $informations->getEtablissement()): ?>
                <?php echo computeArticleDefiniForEtablissement($etab) ?><span class="gras"><?php echo $etab ?></span>
            <?php else: ?>
                <span style='background-color:red;'> non renseigné </span>
            <?php endif; ?>
        </p>
        <?php if ($informations->isCotutuelle()): ?>
            <p>
                En cotutelle
                <?php if ($informations->getCotutuellePays() !== null): ?>
                    internationale
                <?php endif; ?>
                avec
                <?php echo computeArticleDefiniForEtablissement($etab) ?><span class="gras"><?php echo $informations->getCotutuelleLibelle() ?><?php if ($informations->getCotutuellePays() !== null): ?>, <?php echo ($informations->getCotutuellePays()); ?><?php endif; ?></span>
            </p>
            <?php endif; ?>
    </div>


    <div class='bandeau-titre'>
        <p class="gras">
            <?php if ($informations->getTitre() !== null): ?>
                <?php echo $informations->getTitre(); ?>
            <?php else: ?>
                <span style='background-color:red;'> Aucun titre </span>
            <?php endif; ?>
        </p>
    </div>

    <div class='infos-doctorant' style=''>
        <p>
            Présentée et soutenue par<br>
            <span class="gras">
                <?php if ($informations->getDoctorant() !== null): ?>
                    <?php echo $informations->getDoctorant(); ?>
                <?php else: ?>
                    <span style='background-color:red;'> Aucun doctorant </span>
                <?php endif; ?>
            </span>
        </p>
    </div>

    <div class="infos-soutenance">
        <p>
            <span class="gras">
                Thèse
                <?php if ($informations->getDateFinConfidentialite()) : ?>
                    <em>à caractère confidentiel</em>
                <?php endif; ?>
                soutenue le
                <?php if ($informations->getDate() !== null): ?>
                    <?php echo $informations->getDate(); ?>
                <?php else: ?>
                    <span style='background-color:red;'> Aucune date </span>
                <?php endif; ?>
            </span> <br>
            devant le jury composé de :
        </p>
    </div>

    <table class="jury">
        <?php foreach ($informations->getActeursEnCouverture() as $acteur) : ?>
            <tr>
                <td class="individu"> <?php echo $acteur->getDenomination(); ?> </td>
                <td class="qualite"> <?php echo trim($acteur->getQualite()); ?> - <?php echo $acteur->getEtablissement(); ?></td>
                <td class="role"> <?php echo $acteur->getRole(); ?> </td>
            </tr>
        <?php endforeach; ?>
    </table>

    <p class='infos-encadrement'>
        Thèse dirigée par
        <?php if ($listing = $informations->getDirection()): ?>
            <?php $acteurFormatter = fn($row) => '<span class="gras">' . $row['individu'] . '</span>' .
                (($str = ($row['structure'] ?? null)) ? " ($str)" : null); ?>
            <?php echo implode(' et ', array_map($acteurFormatter, $listing)); ?>
        <?php else : ?>
            <span style='background-color:red;'> non renseigné </span>
        <?php endif; ?>
    </p>

    <div class="footer">
        <table class="logos footer">
            <tr>
                <?php if ($informations->isAssocie()): ?>
                    <td>
                        <?php if ($informations->getLogoAssocie()): ?>
                            <img class="logo_small" src="<?php echo $informations->getLogoAssocie() ?>" alt="Logo établissement associé"/>
                        <?php else: ?>
                            <span style='background-color:red;'> Établissement associé ou logo d'établissement non renseigné. </span>
                        <?php endif; ?>
                    </td>
                <?php endif; ?>
                <td>
                    <?php if ($informations->getLogoEcoleDoctorale()): ?>
                        <img class="logo_small" src="<?php echo $informations->getLogoEcoleDoctorale() ?>" alt="Logo école doctorale"/>
                    <?php else: ?>
                        <span style='background-color:red;'> École doctorale ou logo d'école doctorale non renseigné </span>
                    <?php endif; ?>
                </td>
                <td>
                    <?php if ($informations->getLogoUniteRecherche()): ?>
                        <img class="logo_small" src="<?php echo $informations->getLogoUniteRecherche() ?>" alt="Logo unité de recherche"/>
                    <?php else: ?>
                        <span style='background-color:red;'> Unité de recherche ou logo d'unité de recherche non renseigné </span>
                    <?php endif; ?>
                </td>
            </tr>
        </table>
    </div>

</html>


<?php
/**
 * Détermine l'article défini adapté au libellé d'un établissement.
 *
 * @param string|\Structure\Entity\Db\Etablissement $etablissement
 * @return string Ex : "l'"pour l'établissement "Université de Tataouine".
 */
function computeArticleDefiniForEtablissement(string|Etablissement $etablissement): string
{
    $etabToString = (string) $etablissement;
    $articlesForLetters = ['a' => "l'", 'e' => "l'", 'i' => "l'", 'o' => "l'", 'u' => "l'", 'y' => "l'"];

    return $articlesForLetters[mb_strtolower($etabToString[0])] ?? '';
}
?>