<?php

namespace Soutenance\Provider\Validation;

class TypeValidation {

    const CODE_VALIDATION_DECLARATION_HONNEUR = 'DOCTORANT_DECLARATION_HONNEUR_NON_PLAGIAT';
    const CODE_REFUS_DECLARATION_HONNEUR = 'DOCTORANT_REFUS_HONNEUR_NON_PLAGIAT';

}