<?php

namespace Soutenance\Provider\Parametre\These;

class SoutenanceParametres {

    CONST CATEGORIE = 'SOUTENANCE_THESE';

    CONST NB_MIN_MEMBRE_JURY        = 'NB_MIN_MEMBRE_JURY';
    CONST NB_MAX_MEMBRE_JURY        = 'NB_MAX_MEMBRE_JURY';
    CONST NB_MIN_RAPPORTEUR         = 'NB_MIN_RAPPORTEUR';
    CONST EQUILIBRE_FEMME_HOMME     = 'EQUILIBRE_FEMME_HOMME';
    CONST RATIO_MIN_RANG_A          = 'RATIO_MIN_RANG_A';
    CONST RATIO_MIN_EXTERIEUR       = 'RATIO_MIN_EXTERIEUR';
    CONST RATIO_MAX_EMERITES        = 'RATIO_MAX_EMERITES';

    CONST DELAI_RETOUR              = 'DELAI_RETOUR';
    CONST DELAI_INTERVENTION        = 'DELAI_INTERVENTION';

    CONST DOC_DELOCALISATION        = 'DOC_DELOCALISATION';
    CONST DOC_DELEGATION_SIGNATURE  = 'DOC_DELEGATION_SIGNATURE';
    CONST DOC_LABEL_EUROPEEN        = 'DOC_LABEL_EUROPEEN';
    CONST DOC_REDACTION_ANGLAIS     = 'DOC_REDACTION_ANGLAIS';
    CONST DOC_CONFIDENTIALITE       = 'DOC_CONFIDENTIALITE';
}