<?php

$date = new DateTime();

?>

<table>
    <tr>
        <td>
            <!--            Direction de la recherche et de l'innovation - Pôle formation doctorale<br/>-->
            <!--            Maison du doctorat de --><?php //echo $lieu; ?>
        </td>
        <td>

        </td>
        <td style="text-align:right;">
            Généré par <?php echo $this->appInfos()->nom ?>
            le <?php echo $date->format('d/m/Y à H:i:s'); ?>
        </td>
    </tr>
</table>
