<?php

use Acteur\Entity\Db\ActeurHDR;
use Application\View\Renderer\PhpRenderer;
use HDR\Service\FichierHDR\PdcData;
use Soutenance\Entity\Proposition;
use Validation\Entity\Db\ValidationHDR;

/**
 * @var PhpRenderer             $this
 * @var Proposition $proposition
 * @var ValidationHDR[] $validations
 * @var ValidationHDR $validation
 * @var array $logos
 * @var PdcData                 $informations
 * @see
 */
?>

<style>
    body {
        font-size: 9pt;
    }

    span.warning {
        font-weight: bold;
        color: darkred;
    }

    img {
        height:2.5cm;
    }

    h1 {
        font-size: x-large;
    }
    h2 {
        font-size: large;
    }
    table {
        width:100%;
    }

    table.recapitulatif {
        border:solid 1px black;
    }

    table.recapitulatif td.head {
        font-weight: bold;
        width: 33.3%
    }

    table.composition {
        border-collapse: collapse;
    }

    table.composition th{
        border-bottom:solid 2px black;
    }

    table.composition td{
        border-bottom:solid 1px gray;
    }

    table.composition tbody tr {
        border-bottom: 1px gray solid ;
    }

    table.informations {
    }

    table.informations td.head {
        width: 50%
    }

    table.informations td.info {
        text-align: right;
    }

    table.validation {
        border-collapse: collapse;
    }

    table.validation th{
        border-bottom:solid 2px black;
    }

    table.validation td{
        border-bottom:solid 1px gray;
        margin: 1rem;
    }

    span.to-complete {
        background-color: pink;
        color: darkred;
    }

</style>
<!-- SECTION DU LOGO DE LA COMUE -------------------------------------------------------------------------------------->

    <div style="width:25%; float:left; position:absolute; top: 20px; left: 20px">
        <?php if ($informations->getLogoEtablissement() !== null): ?>
            <img src="<?php echo $informations->getLogoEtablissement() ?>" />
        <?php else : ?>
            <span style='background-color:red;'>
                Logo ETAB manquant
        </span>
        <?php endif; ?>
    </div>

    <h1 style="text-align:center; position:absolute; top: 60px; left: 25%" >
        Arrêté du 23 novembre 1988 <br> relatif à l'habilitation à diriger des recherches <br/>
        (modifié par arrêté le 25 avril 2002)
    </h1>

<br/>
<br/>
<br/>
<br/>

<h2 style="text-align:center;">
    Année universitaire
    <?php if ($informations->getAnneeUniversitaire() !== null) : ?>
        <?php echo $informations->getAnneeUniversitaire(); ?>
    <?php else : ?>
        <span style='background-color:red;'>
                Année universitaire manquante
        </span>
    <?php endif; ?>
    <br/>
    <u>Rapport de soutenance de HDR</u>
</h2>

<p>
    <strong>
    <?php if ($informations->getCandidat() !== null): ?>
        <?php echo $informations->getCandidat(); ?>
    <?php else : ?>
        <span style='background-color:red;'>
                Candidat manquant
        </span>
    <?php endif; ?>
    </strong>
    présente ses travaux en soutenance le
    <strong>
    <?php if ($proposition->getDate() !== null): ?>
        <?php echo $proposition->getDate()->format('d/m/Y à H:i'); ?>
    <?php else : ?>
        <span style='background-color:red;'>
                Date manquante
        </span>
    <?php endif; ?>
    </strong>
    à l'adresse suivante : <br/>
    <?php if ($proposition->getAdresseActive() !== null): ?>
        <?php echo $proposition->getAdresseActive()->format(); ?>
    <?php else : ?>
        <?php if ($proposition->getAdresse() !== null) : ?>
            <?php echo $proposition->getAdresse(); ?>
        <?php else : ?>
            <span style='background-color:red;'>
                    Adresse manquante
            </span>
            <br/>
        <?php endif; ?>
    <?php endif; ?>
</p>
    <br/>
    en vue de l'obtention du diplôme de <strong>Habilitation à Diriger des Recherches en

    <?php if ($informations->getSpecialite() !== null): ?>
        <?php echo $informations->getSpecialite(); ?>.
    <?php else: ?>
        <span style='background-color:red;'> Spécialité manquante. </span>
    <?php endif; ?>
    </strong>

<br/>
<br/>
<table class='jury'>
    <tr>
        <td>Unité de recherche :</td>
        <td>
            <?php if ($informations->getUniteRecherche() !== null): ?>
                <?php echo $informations->getUniteRecherche(); ?>
            <?php else: ?>
                <span style='background-color:red;'> Unité de recherche manquante</span>
            <?php endif; ?>
        </td>
    </tr>
    <?php
    /**
     * @var ActeurHDR[] $garants
     */
    $garants = $informations->getGarants();
    ?>

    <tr>
        <td>Garant :</td>
        <td>
            <?php $first = true; ?>
            <?php foreach ($garants as $garant) : ?>
                <?php if (!$first): ?>
                    <br/>
                <?php endif; ?>
                <?php
                $first = false;
                $denomination = $garant->getIndividu()->getNomCompletFormatter()->avecCivilite()->f();
                $qualite = $garant->getLibelleQualite();
                ?>
                <?php echo  $denomination . ", ".$qualite; ?>
            <?php endforeach; ?>
        </td>
    </tr>
</table>

<p>
    La soutenance
    <?php if ($proposition && $proposition->isHuitClos() !== null): ?>
        <?php if ($proposition->isHuitClos()) : ?>
            se déroulera en huis clos.
        <?php else : ?>
            est publique.
        <?php endif ; ?>
    <?php else: ?>
        <span style='background-color:red;'> information sur l'aspect public manquante </span>
    <?php endif; ?>
</p>

    <!-- SECTION JURY ----------------------------------------------------------------------------------------------------->

    <table class='jury'>
        <tr>
            <th colspan='3'>
                Composition du jury
            </th>
        </tr>

        <?php foreach ($informations->getActeursEnCouverture() as $acteur) : ?>
            <tr>
                <td> <?php echo $acteur->getDenomination(); ?> </td>
                <td> <?php echo trim($acteur->getQualite()); ?>,  <?php echo $acteur->getEtablissement(); ?></td>
                <td> <?php echo $acteur->getRole(); ?> </td>
            </tr>
        <?php endforeach; ?>

    </table>

<?php $a=1; ?>
