<?php
/**
 * @var PhpRenderer $this
 * @var These       $these
 * @var Diffusion   $diffusion
 */

use These\Entity\Db\Diffusion;
use These\Entity\Db\These;
use Application\Service\Message\DiffusionMessages;
use Application\View\Renderer\PhpRenderer;

?>

<style>
    .diffusion-item { margin-top: 10px; margin-bottom: 15px; }
    .diffusion-item .diffusion-item-value { margin-top: 10px; }
    .diffusion-item .autorisation-laius { margin-top: 0; font-size: 80%; }
    .autoris-diffusion-motif-div { margin-left: 30px; margin-top: 3px; }
    p.autoris-diffusion-motif { margin: 0 0 0 10px; }
</style>


<h2>Autorisation de mise en ligne</h2>

<div class="diffusion-item">
    <?php echo $this->message()->render(DiffusionMessages::AUTORIS_MISE_EN_LIGNE_QUESTION, [], $diffusion) ?>
    <div class="diffusion-item-value">
        <?php echo $this->message()->render(DiffusionMessages::AUTORIS_MISE_EN_LIGNE_REPONSE, [], $diffusion) ?>
    </div>
</div>