<table width="100%" style="font-size: 90%; vertical-align: bottom;">
    <tr>
        <td width="33%">{PAGENO}/{nbpg}</td>
        <td width="10%" align="center"><!--<em><strong><?php /*echo $this->footerTitle; */?></strong></em>--></td>
        <td width="33%" style="text-align: right;">
            <address>
                <?php echo ($this->etablissement)?$this->etablissement->getStructure()->getAdresse():""; ?><br>
                <strong>tél.</strong> <?php echo ($this->etablissement)?$this->etablissement->getStructure()->getTelephone():""; ?> &nbsp; <strong>fax</strong> <?php echo ($this->etablissement)?$this->etablissement->getStructure()->getFax():""; ?><br>
                <?php echo ($this->etablissement)?$this->etablissement->getStructure()->getEmail():""; ?> &nbsp; <?php echo ($this->etablissement)?$this->etablissement->getStructure()->getSiteWeb():""; ?>
            </address>
        </td>
    </tr>
</table>
