<?php
/**
 * @var \Individu\Entity\Db\Individu $entity
 * @var bool $verbose
 */

if (!isset($verbose)) $verbose = false;
?>

<h3>
    Informations générales
</h3>
<dl class="row">
    <?php if ($entity->getCivilite()): ?>
        <dt class="col-md-5">Civilité</dt>
        <dd class="col-md-7"><?php echo $entity->getCiviliteToString() ?></dd>
    <?php endif ?>

    <dt class="col-md-5">Nom d'usage</dt>
    <dd class="col-md-7"><strong><?php echo $entity->getNomUsuel() ?></strong></dd>

    <?php if ($entity->getNomPatronymique() && $entity->getNomPatronymique() !== $entity->getNomUsuel()): ?>
        <dt class="col-md-5">Nom patronymique</dt>
        <dd class="col-md-7"><?php echo $entity->getNomPatronymique() ?></dd>
    <?php endif ?>

    <dt class="col-md-5">Prénom</dt>
    <dd class="col-md-7"><?php echo $entity->getPrenom1() ?></dd>

    <?php if ($verbose && $entity->getPrenom2()): ?>
        <dt class="col-md-5">Deuxième prénom</dt>
        <dd class="col-md-7"><?php echo $entity->getPrenom2() ?></dd>
    <?php endif ?>

    <dt class="col-md-5">Date de naissance</dt>
    <dd class="col-md-7"><?php echo $entity->getDateNaissanceToString() ?: "(Non renseignée)" ?></dd>

    <dt class="col-md-5">Adresse électronique</dt>
    <dd class="col-md-7"><?php echo $entity->getEmailPro() ?: "(Non renseignée)" ?></dd>

    <dt class="col-md-5">Adresse électronique de contact</dt>
    <dd class="col-md-7"><?php echo $entity->getEmailContact() ?: "(Non renseignée)" ?></dd>

    <dt class="col-md-5">Nationalité</dt>
    <dd class="col-md-7">
        <?php echo (($pays = $entity->getPaysNationalite()) ? $pays->getLibelleNationalite() : $entity->getNationalite()) ?: "(Non renseignée)" ?>
    </dd>
</dl>

<?php if ($verbose): ?>
    <h3>
        Informations techniques
    </h3>
    <dl class="row">
        <dt class="col-md-5">Id</dt>
        <dd class="col-md-7"><?php echo $entity->getId() ?></dd>

        <dt class="col-md-5">Création</dt>
        <dd class="col-md-7"><?php echo $entity->getHistoCreation()->format('d/m/Y à H:i:s') ?></dd>

        <?php if ($entity->getHistoModification() && $entity->getHistoModification() <> $entity->getHistoCreation()): ?>
            <dt class="col-md-5">Modification</dt>
            <dd class="col-md-7"><?php echo $entity->getHistoModification()->format('d/m/Y à H:i:s') ?></dd>
        <?php endif ?>

        <dt class="col-md-5">Source</dt>
        <dd class="col-md-7"><?php echo $entity->getSource() ?></dd>

        <dt class="col-md-5">Source code</dt>
        <dd class="col-md-7"><code><?php echo $entity->getSourceCode() ?></code></dd>

        <dt class="col-md-5">Supann Id</dt>
        <dd class="col-md-7"><?php echo $entity->getSupannId() ?: "(Non renseigné)" ?></dd>

        <dt class="col-md-5">IdRef</dt>
        <dd class="col-md-7"><?php echo $entity->getIdRef() ? $this->idrefLink($entity->getIdRef()) : "(Non renseigné)" ?></dd>
    </dl>
<?php endif ?>

<?php if ($entity->estHistorise()): ?>
    <h3 class="text-danger">
        Historisé
    </h3>
    <dl class="text-danger">
        <dt class="col-md-5 text-danger">Date :</dt>
        <dd class="col-md-7 text-danger"><?php echo $entity->getHistoDestruction()->format('d/m/Y à H:i:s') ?></dd>
    </dl>
<?php endif ?>

<?php if ($includeGotoDetailsLink ?? false): ?>
    <a href="<?php echo $this->url('individu/voir', ['individu' => $entity->getId()]) ?>"
       class="action btn btn-outline-secondary"><span class="icon icon-voir"></span> Voir la fiche détaillée de cet individu</a>
<?php endif ?>
