<?php
/**
 * @var \Individu\Entity\Db\Individu $entity
 * @var bool $horizontal
 * @var bool $verbose
 */

$horizontal = $horizontal ?? false;

$dlClass = $horizontal ? 'row' : '';
$dtClass = $horizontal ? 'col-md-5' : '';
$ddClass = $horizontal ? 'col-md-7' : '';

if (!isset($verbose)) $verbose = false;
?>

<h3>
    Informations générales
</h3>
<dl class="<?php echo $dlClass ?>">
    <?php if ($entity->getCivilite()): ?>
        <dt class="<?php echo $dtClass ?>">Civilité</dt>
        <dd class="<?php echo $ddClass ?>"><?php echo $entity->getCivilite() ?></dd>
    <?php endif ?>

    <dt class="<?php echo $dtClass ?>">Nom d'usage</dt>
    <dd class="<?php echo $ddClass ?>"><strong><?php echo $entity->getNomUsuel() ?></strong></dd>

    <dt class="<?php echo $dtClass ?>">Nom patronymique</dt>
    <dd class="<?php echo $ddClass ?>"><?php echo $entity->getNomPatronymique() ?></dd>

    <dt class="<?php echo $dtClass ?>">Prénom</dt>
    <dd class="<?php echo $ddClass ?>"><?php echo $entity->getPrenom1() ?></dd>

    <?php if ($verbose): ?>
        <dt class="<?php echo $dtClass ?>">Deuxième prénom</dt>
        <dd class="<?php echo $ddClass ?>"><?php echo $entity->getPrenom2() ?: "(Non renseigné)" ?></dd>
        <dt class="<?php echo $dtClass ?>">Troisième prénom</dt>
        <dd class="<?php echo $ddClass ?>"><?php echo $entity->getPrenom3() ?: "(Non renseigné)" ?></dd>
    <?php endif ?>

    <dt class="<?php echo $dtClass ?>">Date de naissance</dt>
    <dd class="<?php echo $ddClass ?>"><?php echo $entity->getDateNaissanceToString() ?: "(Non renseignée)" ?></dd>

    <dt class="<?php echo $dtClass ?>">Adresse électronique</dt>
    <dd class="<?php echo $ddClass ?>"><?php echo $entity->getEmailPro() ?: "(Non renseignée)" ?></dd>

    <dt class="<?php echo $dtClass ?>">Adresse électronique de contact</dt>
    <dd class="<?php echo $ddClass ?>"><?php echo $entity->getEmailContact() ?: "(Non renseignée)" ?></dd>

    <dt class="<?php echo $dtClass ?>">Nationalité</dt>
    <dd class="<?php echo $ddClass ?>">
        <?php if ($entity->isApatride()): ?>
            Aucune (apatride)
        <?php else: ?>
            <?php echo ($pays = $entity->getPaysNationalite()) ? $pays->getLibelleNationalite() : "(Non renseignée)" ?>
        <?php endif ?>
    </dd>
</dl>

<?php if ($verbose): ?>
    <h3>
        Informations techniques
    </h3>
    <dl class="<?php echo $dlClass ?>">
        <dt class="<?php echo $dtClass ?>">Id</dt>
        <dd class="<?php echo $ddClass ?>"><?php echo $entity->getId() ?></dd>

        <dt class="<?php echo $dtClass ?>">Création</dt>
        <dd class="<?php echo $ddClass ?>"><?php echo $entity->getHistoCreation()->format('d/m/Y à H:i:s') ?></dd>

        <dt class="<?php echo $dtClass ?>">Modification</dt>
        <?php if ($entity->getHistoModification() && $entity->getHistoModification() <> $entity->getHistoCreation()): ?>
            <dd class="<?php echo $ddClass ?>"><?php echo $entity->getHistoModification()->format('d/m/Y à H:i:s') ?></dd>
        <?php else: ?>
            <dd class="<?php echo $ddClass ?>">(Aucune)</dd>
        <?php endif ?>

        <dt class="<?php echo $dtClass ?>">Source</dt>
        <dd class="<?php echo $ddClass ?>"><?php echo $entity->getSource() ?></dd>

        <dt class="<?php echo $dtClass ?>">Source code</dt>
        <dd class="<?php echo $ddClass ?>"><code><?php echo $entity->getSourceCode() ?></code></dd>

        <dt class="<?php echo $dtClass ?>">Supann Id</dt>
        <dd class="<?php echo $ddClass ?>"><?php echo $entity->getSupannId() ?: "(Non renseigné)" ?></dd>

        <dt class="<?php echo $dtClass ?>">IdRef</dt>
        <dd class="<?php echo $ddClass ?>"><?php echo $entity->getIdRef() ? $this->idrefLink($entity->getIdRef()) : "(Non renseigné)" ?></dd>
    </dl>
<?php endif ?>

<?php if ($entity->estHistorise()): ?>
    <h3 class="text-danger">
        Historisé
    </h3>
    <dl class="<?php echo $dlClass ?> text-danger">
        <dt class="<?php echo $dtClass ?> text-danger">Date :</dt>
        <dd class="<?php echo $ddClass ?> text-danger"><?php echo $entity->getHistoDestruction()->format('d/m/Y à H:i:s') ?></dd>
    </dl>
<?php endif ?>

<?php if ($includeGotoDetailsLink ?? false): ?>
    <a href="<?php echo $this->url('individu/voir', ['individu' => $entity->getId()]) ?>"
       class="action btn btn-outline-secondary"><span class="icon icon-voir"></span> Voir la fiche détaillée de cet individu</a>
<?php endif ?>
