<?php

use Application\Service\These\TheseService;
use Application\View\Renderer\PhpRenderer;
use RapportActivite\Entity\Db\RapportActiviteAvis;
use RapportActivite\Service\Fichier\Exporter\PageValidationExportData;

/**
 * @var PhpRenderer $this
 * @var \RapportActivite\Entity\Db\RapportActivite $rapport
 * @var PageValidationExportData $data
 *
 * @see TheseService::fetchInformationsPageDeCouverture() pour la génération de $data
 */
?>

<!-- SECTION DU LOGO DE LA COMUE -------------------------------------------------------------------------------------->
<div style="text-align: center; margin-bottom: 30px;">
    <div class='logo-comue'>
        <?php if ($data->logoCOMUE !== null): ?>
            <img src="<?php echo $data->logoCOMUE ?>" alt="Logo de la COMUE"/>
        <?php else: ?>
            <span style='background-color:red;'> COMUE ou logo de la COMUE non renseigné. </span>
        <?php endif; ?>
    </div>
</div>
<!-- --------------------------------------------------------------------------------------------------------------- -->

<div class='bandeau-titre'>
    <?php echo mb_strtoupper($rapport->getTypeRapportToString()) ?>
</div>

<div class='infos-rapport'>
    <p>
        <?php echo $rapport->getFichier()->getNom() ?>
    </p>
    <p>
        Déposé le <?php echo ($rapport->getHistoModification() ?: $rapport->getHistoCreation())->format('d/m/Y H:i') ?>
    </p>
</div>

<div class="logo-ecole-doctorale">
    <img class="logo" src="<?php echo $data->logoEcoleDoctorale ?>" alt="Logo de l'ED"/>
</div>

<div class='infos-validation'>
    <p>
        La direction de l'ED &laquo; <?php echo $data->ecoleDoctorale ?> &raquo; atteste avoir validé le
        <?php echo $data->validation->getHistoCreation()->format('d/m/Y H:i') ?> le rapport d'activité
        <?php echo $rapport->getTypeRapportToString() ?> de <?php echo $data->doctorant ?>,
        laboratoire &laquo; <?php echo $data->uniteRecherche ?> &raquo;.
    </p>

    <?php if ($data->mostRecentAvis): ?>
        <?php switch ($data->mostRecentAvis->getAvis()->getAvisValeur()->getCode()):
            case RapportActiviteAvis::AVIS_VALEUR__CODE__AVIS_RAPPORT_ACTIVITE_VALEUR_NEGATIF: ?>
                <p>
                    <strong>Mais émet un avis négatif pour la/ou les raisons suivante(s) :</strong>
                </p>
                <?php echo $data->mostRecentAvis->getAvis()->getAvisComplemsToHtml() ?>
                <?php break; ?>

            <?php case RapportActiviteAvis::AVIS_VALEUR__CODE__AVIS_RAPPORT_ACTIVITE_VALEUR_POSITIF: ?>
                <p>

                </p>
                <?php break; ?>
            <?php default: ?>
                <?php break; ?>
            <?php endswitch; ?>
    <?php endif ?>
</div>

<div class="signature-ecole-doctorale">
    <?php if ($data->signatureEcoleDoctorale): ?>
        <img src="data:image/png;base64,<?php echo base64_encode($data->signatureEcoleDoctorale); ?>"
             alt="Signature de la direction d'ED"/>
    <?php endif ?>
    <?php if ($data->signatureEcoleDoctoraleAnomalie): ?>
        <span class="anomalie">ANOMALIE : <?php echo $data->signatureEcoleDoctoraleAnomalie ?></span>
    <?php endif ?>
</div>

<div class='bandeau-titre sous-titre'>
    Thèse
</div>

<div class='bandeau-titre-these'>
    <?php echo $data->titre; ?>
</div>


<!-- SECTION DES LOGOS EN BAS DE PAGE --------------------------------------------------------------------------------->
<div class="logos">
    <table style="border:none;" class="logos">
        <tr>
            <td>
                <?php if ($data->logoEtablissement): ?>
                    <img class="logo logo_small" src="<?php echo $data->logoEtablissement ?>"/>
                <?php else: ?>
                    <span style='background-color:red;'> Établissement d'inscription ou logo d'établissement non renseigné. </span>
                <?php endif; ?>
            </td>
            <!--            <td>-->
            <!--                --><?php //if ($data->logoUniteRecherche): ?>
            <!--                    <img class="logo logo_small" src="--><?php //echo $data->logoUniteRecherche ?><!--"/>-->
            <!--                --><?php //else: ?>
            <!--                    <span style='background-color:red;'> Unité de recherche ou logo d'unité de recherche non renseigné </span>-->
            <!--                --><?php //endif; ?>
            <!--            </td>-->
        </tr>
    </table>
</div>
<!-- --------------------------------------------------------------------------------------------------------------- -->