<?php

/**
 * @var Structure $structure
 * @var string[] $contenus
 */

use Application\Entity\Db\Structure;
use Application\Entity\Db\StructureDocument;

?>

<div class="row">
    <div class="col-md-8">
        <h2> Documents liés à la structure  </h2>
    </div>
    <div class="float-end">
        <br/>
        <a      <?php /** @see \Application\Controller\StructureController::televerserDocumentAction() */?>
            href="<?php echo $this->url('structure/televerser-document', ['structure' => $structure->getId(), 'etablissement' => false], [], true); ?>"
            class="btn btn-primary action ajax-modal" data-event="modification">
            <span class="icon icon-upload"></span>
            Téléverser un document
        </a>
    </div>
</div>
<?php $array = $structure->getDocuments(); ?>
<?php foreach ($array as $clef => $liste) : ?>
    <?php $type = ($liste[0])->getNature(); ?>
    <h3> <?php echo $type->getLibelle(); ?></h3>
    <ul>
        <?php /** @var StructureDocument $document */ ?>
        <?php foreach ($liste as $document) : ?>
            <li>
                <a      <?php /** @see \Application\Controller\StructureController::supprimerDocumentAction() */ ?>
                    href="<?php echo $this->url('structure/supprimer-document', ['structure' => $structure->getId(), 'document' => $document->getId()], [], true); ?>">
                    <span class="icon icon-delete iconly" style="color:darkred;" title="Supprimer le document"></span>
                </a>
                <br/>
                <img alt="document ... " class="signature" src="data:image/png;base64,<?php echo base64_encode($contenus[$document->getId()]); ?>" />
            </li>
        <?php endforeach; ?>
    </ul>
<?php endforeach; ?>


<style>
    img.signature {
        max-width: 400px;
        max-height: 200px;
    }
</style>
