<?php

use Application\Entity\Db\Etablissement;
use Application\Provider\Privilege\EtablissementPrivileges;
use Application\View\Renderer\PhpRenderer;

/**
 * @see \Application\Controller\EtablissementController::indexAction()
 * @var PhpRenderer $this
 * @var Etablissement[] $etablissementsSygal
 * @var Etablissement[] $etablissementsExternes
 */

$canModifier = $this->isAllowed(EtablissementPrivileges::getResourceId(EtablissementPrivileges::ETABLISSEMENT_MODIFICATION));

?>


<?php $this->headTitle($this->translate("Établissements")) ?>

<h1 class="page-header first">
    <?php echo $this->translate("Établissements") ?>
    <span class="badge">
        <?php echo count($etablissementsSygal) + count($etablissementsExternes); ?>
    </span>
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace() ?>

<?php if ($canModifier): ?>

    <a href="<?php echo $this->url('etablissement/ajouter', [], [], true) ?>"
       class="btn btn-primary"
       title="<?php echo $this->translate("Créer un nouvel établissement");?>">
        <span class="glyphicon glyphicon-plus"></span>
        <?php echo $this->translate("Ajouter un nouvel établissement");?>
    </a>
<?php endif ?>

<h2>
    Établissements participant à SyGAL
    <span class="badge">
        <?php echo count($etablissementsSygal); ?>
    </span>
</h2>

<div>
    <table class="table table-condensed">
        <thead>
        <tr>
            <th> Libellé </th>
            <th> Source </th>
            <th> Code </th>
            <th> Sigle </th>
            <th> Actions </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($etablissementsSygal as $etablissement): ?>

            <?php
            $historisee = (!$etablissement->estNonHistorise());
            $hasSousStructure = !($etablissement->getStructure()->getStructuresSubstituees()->isEmpty());
            ?>

            <tr>
                <td>
                    <a href="<?php echo $this->url('etablissement/information', ['etablissement' => $etablissement->getStructure()->getId()], [], true); ?>">
                        <?php echo $etablissement->getLibelle(); ?>
                    </a>
                    <?php if ($etablissement->estMembre()): ?>
                        <span class="label label-primary">Membre</span>
                    <?php endif ?>
                    <?php if ($etablissement->estAssocie()): ?>
                        <span class="label label-info">Associé</span>
                    <?php endif ?>
                </td>
                <td>
                    <?php echo explode("::",$etablissement->getSource()->getCode())[0]; ?>
                </td>
                <td>
                    <?php echo $etablissement->getCode(); ?>
                </td>
                <td> <?php echo $etablissement->getSigle(); ?> </td>
                <td>
                    <?php if ($canModifier && !$historisee) : ?>
                        <a href="<?php echo $this->url('etablissement/supprimer', ["etablissement" => $etablissement->getStructure()->getId()], [], true); ?>"
                           title="Historiser l'établissement">
                            <span class="glyphicon glyphicon-trash"></span>
                        </a>
                    <?php endif; ?>

                    <?php if ($canModifier && !$historisee && $hasSousStructure) : ?>
                        <a href="<?php echo $this->url('substitution-modifier', ['cible' => $etablissement->getStructure()->getId(), [], true]); ?>"
                           title="Historiser l'établissement">
                            <span class="glyphicon glyphicon-link" title="Éditer la substitution"></span>
                        </a>
                    <?php endif; ?>

                    <?php if ($canModifier && $historisee) : ?>
                        <a href="<?php echo $this->url('etablissement/restaurer', ["etablissement" => $etablissement->getStructure()->getId()], [], true); ?>"
                           title="Restaurer l'établissement">
                            Restaurer
                        </a>
                    <?php endif; ?>
                </td>
            </tr>

        <?php endforeach; ?>

        </tbody>
    </table>
</div>

<h2>
    Autres établissements
    <span class="badge">
        <?php echo count($etablissementsExternes); ?>
    </span>
</h2>

<div>
    <table class="table table-condensed">
        <thead>
        <tr>
            <th> Libellé </th>
            <th> Source </th>
            <th> Code </th>
            <th> Sigle </th>
            <th> Actions </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($etablissementsExternes as $etablissement): ?>

            <?php
            $historisee = (!$etablissement->estNonHistorise());
            $hasSousStructure = !($etablissement->getStructure()->getStructuresSubstituees()->isEmpty());
            ?>

            <tr>
                <td>
                    <a href="<?php echo $this->url('etablissement/information', ['etablissement' => $etablissement->getStructure()->getId()], [], true); ?>">
                        <?php echo $etablissement->getLibelle(); ?>
                    </a>
                    <?php if ($etablissement->estMembre()): ?>
                        <span class="label label-primary">Membre</span>
                    <?php endif ?>
                    <?php if ($etablissement->estAssocie()): ?>
                        <span class="label label-info">Associé</span>
                    <?php endif ?>
                </td>
                <td>
                    <?php echo explode("::",$etablissement->getSource()->getCode())[0]; ?>
                </td>
                <td>
                    <?php echo $etablissement->getCode(); ?>
                </td>
                <td> <?php echo $etablissement->getSigle(); ?> </td>
                <td>
                    <?php if ($canModifier && !$historisee) : ?>
                        <a href="<?php echo $this->url('etablissement/supprimer', ["etablissement" => $etablissement->getStructure()->getId()], [], true); ?>"
                           title="Historiser l'établissement">
                            <span class="glyphicon glyphicon-trash"></span>
                        </a>
                    <?php endif; ?>

                    <?php if ($canModifier && !$historisee && $hasSousStructure) : ?>
                        <a href="<?php echo $this->url('substitution-modifier', ['cible' => $etablissement->getStructure()->getId(), [], true]); ?>"
                           title="Historiser l'établissement">
                            <span class="glyphicon glyphicon-link" title="Éditer la substitution"></span>
                        </a>
                    <?php endif; ?>

                    <?php if ($canModifier && $historisee) : ?>
                        <a href="<?php echo $this->url('etablissement/restaurer', ["etablissement" => $etablissement->getStructure()->getId()], [], true); ?>"
                           title="Restaurer l'établissement">
                            Restaurer
                        </a>
                    <?php endif; ?>
                </td>
            </tr>

        <?php endforeach; ?>

        </tbody>
    </table>
</div>