<?php

/**
 * @see \Application\Controller\Etablissement::informationAction()
 * @var Etablissement $etablissement
 * @var array $roleListing (string => int)
 * @var array $individuListing (string => string[])
 * @var string $logoContent
 */

use Application\Entity\Db\Etablissement;
use Application\Entity\Db\TypeStructure;

$this->headTitle('Details de l\'établissement ['.$etablissement->getLibelle().']');

$canEdit = true;
$canAddRole = true;

?>

<h1 class="page-header">
    Details de l'établissement [  <?php echo $etablissement->getLibelle(); ?> ]
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace() ?>

<a href="<?php echo $this->url('etablissement', [], [], true); ?>"
   class="btn btn-primary action"
   >
    <span class="glyphicon glyphicon-th-list"></span> Index des établissements
</a>

<?php if($canEdit): ?>
    <a href="<?php echo $this->url('etablissement/modifier', ['structure'=> $etablissement->getStructure()->getId()], [], true); ?>"
       class="btn btn-primary action"
    >
        <span class="glyphicon glyphicon-pencil"></span> Modifier l'établissement
    </a>
<?php endif; ?>

<?php if ($canAddRole && empty($roleListing)): ?>
    <a
            href="<?php echo $this->url('structure/generer-roles-defauts',
                ['id' => $etablissement->getStructure()->getId(), 'type' => TypeStructure::CODE_ETABLISSEMENT], [], true);?>"
            class="btn btn-warning"
    >
        <span class="glyphicon glyphicon-refresh"></span>
        Générer rôles par défaut
    </a>
<?php endif; ?>

<div>
    <h2>
        Informations générales
    </h2>
    <div class="row">
        <div class="col-md-6">
            <dl>
                <dt> Libelle : </dt>                <dd>    <?php echo $etablissement->getLibelle(); ?>     </dd>
                <dt> Sigle : </dt>                  <dd>    <?php echo $etablissement->getSigle() ?: "(Non renseigné)"; ?></dd>
                <dt> Adresse : </dt>                <dd>    <?php echo $etablissement->getStructure()->getAdresse() ?: "(Non renseignée)"; ?></dd>
                <dt> Téléphone : </dt>              <dd>    <?php echo $etablissement->getStructure()->getTelephone() ?: "(Non renseigné)"; ?></dd>
                <dt> Fax : </dt>                    <dd>    <?php echo $etablissement->getStructure()->getFax() ?: "(Non renseigné)"; ?></dd>
                <dt> Adresse électronique : </dt>   <dd>    <?php echo $etablissement->getStructure()->getEmail() ?: "(Non renseignée)"; ?></dd>
                <dt> Site internet : </dt>          <dd>    <?php echo $etablissement->getStructure()->getSiteWeb() ?: "(Non renseigné)"; ?></dd>
                <dt> Code : </dt>                   <dd>    <?php echo $etablissement->getStructure()->getCode(); ?>        </dd>
                <dt> Domaine : </dt>                <dd>    <?php echo $etablissement->getDomaine() ?: "(Non renseigné)"; ?></dd>
            </dl>
        </div>
        <div class="col-md-4">
            <dl>
                <dt> Statut : </dt>     <dd>
                    <?php if ($etablissement->estMembre()): ?>
                        <span class="label label-primary">Membre</span>
                    <?php endif ?>
                    <?php if ($etablissement->estAssocie()): ?>
                        <span class="label label-info">Associé</span>
                    <?php endif ?>
                    <?php if ($etablissement->getStructure()->isFerme()) : ?>
                        <span class="label" style="background-color:darkred">Structure fermée</span>
                    <?php else : ?>
                        <span class="label" style="background-color:darkgreen">Structure ouverte</span>
                    <?php endif; ?>
                </dd>
                <dt>Logo :</dt>
                <dd>
                    <img id="logo" style="max-width: 200px; max-height: 200px; background-color: white;"
                         src="data:image/png;base64,<?php echo base64_encode($logoContent); ?>"/>
                </dd>
            </dl>
        </div>
    </div>
</div>


<div>
    <h2>
        Rôles et membres
    </h2>
        <div class="row">
            <?php foreach ($roleListing as $roleId => $count) :?>
            <div class="col-md-4">
                <h3>
                    <?php echo $roleId; ?>
                    <span class="badge"><?php echo $count; ?></span>
                </h3>

                <ul>
                <?php foreach($individuListing as $denomination => $roles): ?>
                    <?php foreach($roles as $role): ?>
                        <?php if ($role === $roleId) : ?>
                            <li><?php echo $denomination; ?></li>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                </ul>
            </div>
            <?php endforeach; ?>
        </div>
</div>

<style>
    .action {
        width: 20em;
    }
</style>