<?php

use Application\Controller\EtablissementController;
use Application\Form\EtablissementForm;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer        $this
 * @var string             $title
 * @var EtablissementForm  $form
 * @var string             $logoContent
 *
 * @method string formControlGroup()
 *
 * @see EtablissementController::modifierAction()
 */

$fcg = $this->formControlGroup();
?>

<?php echo $this->form()->openTag($form->prepare()->setAttribute('class', 'etablissement')) ?>
<?php echo $this->formHidden($form->get('id')) ?>
<?php echo $fcg($form->get('libelle')) ?>
<?php echo $fcg($form->get('sigle')) ?>
<?php echo $fcg($form->get('code')) ?>
<?php echo $fcg($form->get('domaine')) ?>
<?php echo $fcg($form->get('estMembre')) ?>
<?php echo $fcg($form->get('estAssocie')) ?>

    <div id="logo-div">
        <?php
        /** @var \Zend\Form\Element\File $logoFile */
        $logoFile = $form->get('cheminLogo');
        echo $this->formLabel($logoFile);
        ?>

        <?php
        $content = $logoContent;
        if ($content === null) {
            $form->getObject()->setCheminLogo(null);
        }
        ?>
        <table>
            <tr>
                <td>
                    <img
                            id="logo"
                        style="max-width: 200px; max-height: 200px; border: 1px solid black; background-color: white;"
                        src="data:image/png;base64,<?php echo base64_encode($logoContent); ?>"
                    />
                </td>
                <td style="padding:20px;">
                    <?php
                    echo $this->formFile($logoFile);
                    echo $this->formElementErrors($logoFile);
                    ?>
                    <br/>
                    <?php if($form->getObject()->getId()): ?>
                    <a id="supprimer-logo" class="btn btn-danger" href="<?php echo $this->url('etablissement/supprimer-logo', ["structure" => $form->getObject()->getStructure()->getId()], [], true); ?>">
                        <span class="glyphicon glyphicon-trash"></span>
                        Supprimer le logo
                    </a>
                    <?php endif; ?>
                </td>
            </tr>
        </table>

        <div class="alert alert-warning">
            <small>
                <span class="glyphicon glyphicon-exclamation-sign"></span>
                Le logo de la structure doit être donné dans un des formats suivant&nbsp;:
                <ul>
                    <li>.bmp</li>
                    <li>.jpg, .jpeg</li>
                    <li>.png</li>
                </ul>
            </small>
        </div>

    </div>
<?php echo $this->formElement($form->get('submit')) ?>
<?php echo $this->form()->closeTag() ?>

    <!-- pour traduction -->
<?php
$this->translate("Libellé :");
$this->translate("Code :");
$this->translate("Enregistrer");
$this->translate("Supprimer le logo");
$this->translate("Logo de l'école doctoral :");
?>

<script>
    $(document).ready(function() {

        //remplacement dans la structure cible
        $("input[name='cheminLogo']").on("change", function () {

            var myFile = $("input[name='cheminLogo']").prop('files');
            console.log(myFile[0]);
            fr = new FileReader();
            fr.onload = function () {
                var content = fr.result;
                console.log(content);
                $('#logo').attr("src", content);
            };
            fr.readAsDataURL( myFile[0] );
        });

        $("button#supprimer-logo").click( function() {
           alert("clic");
        });
    });
</script>
