<?php

use Application\Form\EtablissementForm;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer        $this
 * @var string             $title
 * @var EtablissementForm $form
 *
 * @method string formControlGroup()
 */

$fcg = $this->formControlGroup();
?>

<?php echo $this->form()->openTag($form->prepare()->setAttribute('class', 'etablissement')) ?>
<?php echo $this->formHidden($form->get('id')) ?>
<?php echo $fcg($form->get('libelle')) ?>
<?php echo $fcg($form->get('code')) ?>

    <div id="logo-div">
        <?php
        /** @var \Zend\Form\Element\File $logoFile */
        $logoFile = $form->get('cheminLogo');
        echo $this->formLabel($logoFile);
        ?>
        <table>
            <tr>
                <td>
                    <img
                        style="max-width: 200px; max-height: 200px; border: 1px solid black; background-color: white;"
                        src="data:image/png;base64,<?php echo base64_encode($form->getObject()->getLogoContent()); ?>"
                    />
                </td>
                <td style="padding:20px;">
                    <?php
                    echo $this->formFile($logoFile);
                    echo $this->formElementErrors($logoFile);
                    echo $this->formElement($form->get('supprimer-logo'));
                    ?>
                </td>
            </tr>
        </table>
    </div>
<?php echo $this->formElement($form->get('submit')) ?>
<?php echo $this->form()->closeTag() ?>

    <!-- pour traduction -->
<?php
$this->translate("Libellé :");
$this->translate("Code :");
$this->translate("Enregistrer");
$this->translate("Supprimer le logo");
$this->translate("Logo de l'école doctoral :");
?>