create table FORMATION_ETAT
(
    CODE VARCHAR(1) not null constraint FORMATION_ETAT_PK primary key,
    LIBELLE VARCHAR(1024),
    DESCRIPTION TEXT,
    ICONE VARCHAR(1024),
    COULEUR VARCHAR(1024),
    ORDRE BIGINT
);

create table FORMATION_MODULE
(
    ID BIGINT not null constraint FORMATION_PK primary key,
    LIBELLE VARCHAR(1024) not null,
    DESCRIPTION TEXT,
    LIEN VARCHAR(1024),
    SITE_ID BIGINT constraint FORMATION_ETABLISSEMENT_ID_FK references ETABLISSEMENT on delete set null,
    RESPONSABLE_ID BIGINT constraint FORMATION_INDIVIDU_ID_FK references INDIVIDU on delete set null,
    MODALITE VARCHAR(1),
    TYPE VARCHAR(1),
    TYPE_STRUCTURE_ID BIGINT constraint FORMATION_STRUCTURE_ID_FK references STRUCTURE on delete set null,
    TAILLE_LISTE_PRINCIPALE BIGINT,
    TAILLE_LISTE_COMPLEMENTAIRE BIGINT,
    HISTO_CREATEUR_ID BIGINT not null constraint FORMATION_CREATEUR_FK references UTILISATEUR,
    HISTO_CREATION TIMESTAMP(6) not null,
    HISTO_MODIFICATEUR_ID BIGINT constraint FORMATION_MODIFICATEUR_FK  references UTILISATEUR,
    HISTO_MODIFICATION TIMESTAMP(6),
    HISTO_DESTRUCTEUR_ID BIGINT  constraint FORMATION_DESTRUCTEUR_FK   references UTILISATEUR,
    HISTO_DESTRUCTION TIMESTAMP(6)
);
create sequence formation_module_id_seq;

create table FORMATION_SESSION
(
    ID BIGINT not null constraint FORMATION_INSTANCE_PK primary key,
    MODULE_ID BIGINT not null constraint SESSION_ID_FK references FORMATION_MODULE on delete cascade,
    DESCRIPTION TEXT,
    TAILLE_LISTE_PRINCIPALE BIGINT,
    TAILLE_LISTE_COMPLEMENTAIRE BIGINT,
    TYPE_STRUCTURE_ID BIGINT,
    SITE_ID BIGINT constraint SESSION_SITE_ID_FK references ETABLISSEMENT on delete set null,
    RESPONSABLE_ID BIGINT constraint SESSION_RESPONSABLE_ID_FK references INDIVIDU on delete set null,
    MODALITE VARCHAR(1),
    TYPE VARCHAR(1),
    ETAT_CODE VARCHAR(1) constraint SESSION_ETAT_CODE_FK references FORMATION_ETAT on delete set null,
    SESSION_INDEX BIGINT,
    HISTO_CREATION TIMESTAMP(6) not null,
    HISTO_CREATEUR_ID BIGINT not null constraint SESSION_CREATEUR_FK references UTILISATEUR,
    HISTO_MODIFICATION TIMESTAMP(6),
    HISTO_MODIFICATEUR_ID BIGINT constraint SESSION_MODIFICATEUR_FK  references UTILISATEUR,
    HISTO_DESTRUCTION TIMESTAMP(6),
    HISTO_DESTRUCTEUR_ID BIGINT constraint SESSION_DESTRUCTEUR_FK    references UTILISATEUR
);
create sequence formation_session_id_seq;

create table FORMATION_SEANCE
(
    ID BIGINT not null constraint FORMATION_SEANCE_PK primary key,
    SESSION_ID BIGINT not null constraint FORMATION_SEANCE_SESSION_FK references FORMATION_SESSION on delete cascade,
    DEBUT TIMESTAMP(6) not null,
    FIN TIMESTAMP(6) not null,
    LIEU VARCHAR(1024),
    DESCRIPTION TEXT,
    HISTO_CREATION TIMESTAMP(6) not null,
    HISTO_CREATEUR_ID BIGINT not null constraint SEANCE_CREATEUR_FK references UTILISATEUR,
    HISTO_MODIFICATION TIMESTAMP(6),
    HISTO_MODIFICATEUR_ID BIGINT constraint SEANCE_MODIFICATEUR_FK  references UTILISATEUR,
    HISTO_DESTRUCTION TIMESTAMP(6),
    HISTO_DESTRUCTEUR_ID BIGINT constraint SEANCE_DESTRUCTEUR_FK    references UTILISATEUR
);
create sequence formation_seance_id_seq;

create table FORMATION_FORMATEUR
(
    ID BIGINT not null constraint FORMATION_FORMATEUR_PK primary key,
    INDIVIDU_ID BIGINT not null constraint FORMATEUR_INDIVIDU_ID_FK references INDIVIDU on delete cascade,
    SESSION_ID BIGINT not null  constraint FORMATEUR_SESSION_ID_FK  references FORMATION_SESSION on delete cascade,
    DESCRIPTION TEXT,
    HISTO_CREATION TIMESTAMP(6) not null,
    HISTO_CREATEUR_ID BIGINT not null constraint FORMATEUR_CREATEUR_FK references UTILISATEUR,
    HISTO_MODIFICATION TIMESTAMP(6),
    HISTO_MODIFICATEUR_ID BIGINT constraint FORMATEUR_MODIFICATEUR_FK  references UTILISATEUR,
    HISTO_DESTRUCTION TIMESTAMP(6),
    HISTO_DESTRUCTEUR_ID BIGINT constraint FORMATEUR_DESTRUCTEUR_FK    references UTILISATEUR
);
create sequence formation_formateur_id_seq;

create table FORMATION_INSCRIPTION
(
    ID BIGINT not null constraint FORMATION_INSCRIPTION_PK primary key,
    SESSION_ID BIGINT not null constraint FORMATION_SESSION_FK references FORMATION_SESSION on delete cascade,
    DOCTORANT_ID BIGINT not null constraint INSCRIPTION_DOCTORANT_ID_FK references DOCTORANT on delete cascade,
    LISTE VARCHAR(1),
    DESCRIPTION TEXT,
    HISTO_CREATION TIMESTAMP(6) not null,
    HISTO_CREATEUR_ID BIGINT not null constraint INSCRIPTION_CREATEUR_FK references UTILISATEUR,
    HISTO_MODIFICATION TIMESTAMP(6),
    HISTO_MODIFICATEUR_ID BIGINT constraint INSCRIPTION_MODIFICATEUR_FK  references UTILISATEUR,
    HISTO_DESTRUCTION TIMESTAMP(6),
    HISTO_DESTRUCTEUR_ID BIGINT constraint INSCRIPTION_DESTRUCTEUR_FK    references UTILISATEUR
);
create sequence formation_inscription_id_seq;

create table FORMATION_PRESENCE
(
    ID BIGINT not null constraint FORMATION_PRESENCE_PK primary key,
    INSCRIPTION_ID BIGINT not null constraint PRESENCE_INSCRIPTION_ID_FK references FORMATION_INSCRIPTION on delete cascade,
    SEANCE_ID BIGINT not null constraint PRESENCE_SEANCE_ID_FK references FORMATION_SEANCE on delete cascade,
    TEMOIN VARCHAR(1),
    DESCRIPTION TEXT,
    HISTO_CREATION TIMESTAMP(6) not null,
    HISTO_CREATEUR_ID BIGINT not null constraint PRESENCE_CREATEUR_FK references UTILISATEUR,
    HISTO_MODIFICATION TIMESTAMP(6),
    HISTO_MODIFICATEUR_ID BIGINT constraint PRESENCE_MODIFICATEUR_FK  references UTILISATEUR,
    HISTO_DESTRUCTION TIMESTAMP(6),
    HISTO_DESTRUCTEUR_ID BIGINT constraint PRESENCE_DESTRUCTEUR_FK    references UTILISATEUR
);
create sequence formation_presence_id_seq;

create table FORMATION_ENQUETE_QUESTION
(
    ID BIGINT not null constraint FORMATION_ENQUETE_QUESTION_PK primary key,
    LIBELLE VARCHAR(1024) not null,
    DESCRIPTION TEXT,
    ORDRE BIGINT not null,
    HISTO_CREATION TIMESTAMP(6) not null,
    HISTO_CREATEUR_ID BIGINT not null constraint QUESTION_CREATEUR_FK references UTILISATEUR,
    HISTO_MODIFICATION TIMESTAMP(6),
    HISTO_MODIFICATEUR_ID BIGINT constraint QUESTION_MODIFICATEUR_FK  references UTILISATEUR,
    HISTO_DESTRUCTION TIMESTAMP(6),
    HISTO_DESTRUCTEUR_ID BIGINT constraint QUESTION_DESTRUCTEUR_FK    references UTILISATEUR
);
create sequence formation_enquete_question_id_seq;

create table FORMATION_ENQUETE_REPONSE
(
    ID BIGINT not null constraint FORMATION_ENQUETE_REPONSE_PK primary key,
    INSCRIPTION_ID BIGINT not null constraint REPONSE_INSCRIPTION_ID_FK references FORMATION_INSCRIPTION on delete cascade,
    QUESTION_ID BIGINT not null constraint REPONSE_QUESTION_ID_FK references FORMATION_ENQUETE_QUESTION on delete cascade,
    NIVEAU BIGINT not null,
    DESCRIPTION TEXT,
    HISTO_CREATION TIMESTAMP(6) not null,
    HISTO_CREATEUR_ID BIGINT not null constraint REPONSE_CREATEUR_FK references UTILISATEUR,
    HISTO_MODIFICATION TIMESTAMP(6),
    HISTO_MODIFICATEUR_ID BIGINT constraint REPONSE_MODIFICATEUR_FK  references UTILISATEUR,
    HISTO_DESTRUCTION TIMESTAMP(6),
    HISTO_DESTRUCTEUR_ID BIGINT constraint REPONSE_DESTRUCTEUR_FK    references UTILISATEUR
);
create sequence formation_enquete_reponse_id_seq;


