<?php

/**
 * @see \Formation\Service\Exporter\Convocation\ConvocationExporter;
 * @var Inscription $inscription
 * @var string[] $logos
 * @var string $signature
 */

use Formation\Entity\Db\Inscription;
use Formation\Entity\Db\Seance;

$session = $inscription->getSession();
$doctorant = $inscription->getDoctorant();

$libelle = $session->getFormation()->getLibelle();
$denomination = $doctorant->getIndividu()->getNomComplet(false, false,false,true);
$responsable = null;
if ($individu = $session->getResponsable()) {
    $nom = $individu->getNomComplet(false, false,false,true);
    $email = $individu->getEmailPro();
    $responsable = $nom;
    if ($email) $responsable .= " <i>" .$email."</i>";
}

/** @var Seance[] $seances */
$seances = $session->getSeances()->toArray();
$seances = array_filter($seances, function ($a) { return $a->estNonhistorise();});
usort($seances, function ($a, $b) { return $a->getDebut() > $b->getDebut(); });

?>

<?php if  (isset($logos['comue']))  : ?>
    <div style="width:25%; float:left; position:absolute; top: 20px; left: 20px">
        <?php if ($logos['comue'] !== null): ?>
            <img src="<?php echo $logos['comue']; ?>" alt="Logo de la COMUE" />
        <?php else : ?>
            <span style='background-color:red;'>
                    Logo du site manquant
            </span>
        <?php endif; ?>
    </div>
    <div style="width:25%; float:right; position:absolute; top: 20px; right: 20px">
        <?php if ($logos['site'] !== null): ?>
            <img src="<?php echo $logos['site']; ?>" alt="Logo du site de formation" />
        <?php else : ?>
            <span style='background-color:red;'>
                Logo du site manquant
            </span>
        <?php endif; ?>
    </div>
<?php else : ?>
<div style="width:25%; float:left; position:absolute; top: 20px; left: 20px">
    <?php if ($logos['site'] !== null): ?>
        <img src="<?php echo $logos['site']; ?>" alt="Logo du site de formation" />
    <?php else : ?>
        <span style='background-color:red;'>
            Logo du site manquant
        </span>
    <?php endif; ?>
</div>
<?php endif; ?>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<h1>Convocation à la session de formation
    <br/>
    <?php echo $libelle; ?>
</h1>


<p>
Bonjour <?php echo $denomination; ?>,
</p>

<p>
    Nous avons le plaisir de vous informer que la formation, <q><?php echo $libelle; ?></q>, à laquelle vous êtes inscrit&middot;e se déroulera selon le calendrier ci-dessous :
</p>

<table class="seances">
    <thead>
    <tr>
        <th> Lieu</th>
        <th> Date</th>
        <th> Début</th>
        <th> Fin</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($seances as $seance) : ?>
        <tr>
            <td> <?php echo $seance->getLieu(); ?> </td>
            <td> <?php echo $seance->getDebut()->format('d/m/Y'); ?> </td>
            <td> <?php echo $seance->getDebut()->format('H:i'); ?> </td>
            <td> <?php echo $seance->getFin()->format('H:i'); ?> </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<p>
    En cas d'impossibilité d'assister à tout ou partie de ce stage, merci de bien vouloir informer le&middot;a responsable
    du module de formation (<?php echo $responsable; ?>) dans les meilleurs délais afin de permettre de contacter un&middot;e doctorant&middot;e actuellement sur liste d'attente.
</p>
<p>
    Nous vous souhaitons un stage fructueux.
</p>
<p></p>
<p style="text-align: right;">L'application SyGAL</p>
<br/>
<img id="logo" style="background-color: white; max-width: 50%;" alt="Signature"
     src="data:image/png;base64,<?php echo base64_encode($signature); ?>"/>

<p>
</p>

<p style="text-align: left;">PS: Cette convocation vaut ordre de mission</p>




<style>
    table.seances {
        width:15.5cm;
        display: block;
        margin-left: auto;
        margin-right: auto;
        border-collapse: collapse;
    }

    table.seances th {
        background-color: #F5A756;
        font-family: Arial, Helvetica, sans-serif;
        font-weight: bold;
        font-size:12pt;
        text-align: center;
        border: 0.3mm solid #F5A756;
        border-collapse: collapse;
    }

    table.seances td {
        font-size: 10pt;
        min-width: 4cm;

        font-family: Arial, Helvetica, sans-serif;

        border: 0.3mm solid #F5A756;
        border-collapse: collapse;
        padding: 1mm;
    }
</style>


