<?php

namespace Substitution;

use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var \Doctrine\DBAL\Result $result
 *
 * @see \Substitution\Controller\IndexController::ecoleDoctAction()
 */
?>

<?php $this->headTitle($this->translate("Substitutions d'écoles doctorales")) ?>

<h1 class="page-header">
    <span class="fas fa-object-group"></span>
    <?php echo $this->translate("Substitutions d'écoles doctorales"); ?>
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace(); ?>

<?php echo $this->partial('substitution/substitution/_partial/liste', [
    'result' => $result,
    'attributes' => ['to_code' => 'Code'],
    'routeName' => 'ecole-doctorale/voir',
    'routeParamName' => 'ecole-doctorale',
]); ?>
