<?php

namespace Application;

use Application\Entity\Db\RapportAnnuel;
use Application\Entity\Db\These;
use Application\Filter\IdifyFilter;
use Application\Form\RapportAnnuelForm;
use Application\Provider\Privilege\RapportAnnuelPrivileges;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var These $these
 * @var RapportAnnuel[] $rapportsAnnuels
 * @var RapportAnnuelForm $form
 * @var bool $tousLesRapportsTeleverses
 *
 * @see \Application\Controller\RapportAnnuelController::indexAction()
 */

$form->prepare();
$canAdd = $this->isAllowed((new RapportAnnuel())->setThese($these), RapportAnnuelPrivileges::RAPPORT_ANNUEL_TELEVERSER);
if ($tousLesRapportsTeleverses) {
    $canAdd = false;
}
?>

<?php $this->headTitle($this->translate($title = "Rapports annuels"))
    ->prepend($these->getDoctorant()->getIndividu()->getNomUsuel()) ?>

<h1 class="page-header">
    <?php echo $this->translate($title); ?>
    <small><?php echo $this->partial('application/these/partial/titre') ?></small>
</h1>

<div class="lead">
    Cette page est consacrée au téléversement des rapports annuels. <br>
    Téléchargez le modèle de document à remplir en cliquant sur
    <strong><a href="<?php echo $this->url('fichier/telecharger-permanent', ['idPermanent' => 'RAPPORT_ANNUEL_MODELE']) ?>">ce lien</a></strong>.
</div>

<?php if (count($rapportsAnnuels) > 0): ?>

<div class="row">
    <div class="col-md-10">

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Année universitaire</th>
                <th>Document téléversé</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($rapportsAnnuels as $rapportAnnuel): ?>
            <tr>
                <?php
                $canDel = $this->isAllowed($rapportAnnuel, RapportAnnuelPrivileges::RAPPORT_ANNUEL_SUPPRIMER);
                $canDl = $this->isAllowed($rapportAnnuel, RapportAnnuelPrivileges::RAPPORT_ANNUEL_TELECHARGER);
                ?>
                <td>
                    <?php echo $rapportAnnuel->getAnneeUnivToString() ?>
                    <?php if ($rapportAnnuel->getEstFinal()): ?>
                        <br>
                        <span class="label label-info">Rapport final</span>
                    <?php endif ?>
                </td>
                <td>
                    <?php $title = "Le " . $rapportAnnuel->getHistoCreation()->format('d/m/Y à H:i:s') . " par " . $rapportAnnuel->getHistoCreateur() ?>
                    <?php if ($canDl): ?>
                        <a href="<?php echo $this->url('rapport-annuel/telecharger', ['rapportAnnuel' => IdifyFilter::id($rapportAnnuel)]) ?>"
                           title="<?php echo $title ?>">
                            <?php echo $rapportAnnuel->getFichier()->getNom() ?>
                        </a>
                    <?php else: ?>
                        <span title="<?php echo $title ?>">
                            <?php echo $rapportAnnuel->getFichier()->getNom() ?>
                        </span>
                    <?php endif; ?>
                </td>
                <td class="action">
                    <?php if ($canDel): ?>
                        <a href="<?php echo $this->url('rapport-annuel/supprimer', ['rapportAnnuel' => $rapportAnnuel->getId()]) ?>"
                           title="Supprimer ce rapport ?"
                           data-toggle="confirmation"><span class="glyphicon glyphicon-trash"></span></a>
                    <?php endif; ?>
                </td>
            </tr>
            <?php endforeach; ?>
            </tbody>
        </table>

        <?php else: ?>

            Aucun.

        <?php endif; ?>

    </div>
</div>

<div class="row">
    <div class="col-md-offset-1 col-md-8">

        <?php $ajouterFormVisible = !empty($form->getMessages()); ?>
        <div id="ajouterDiv">
            <div class="row">
                <div class="col-md-4">
                    <a href="#" id="ajouterBtn" class="btn btn-primary <?php echo $canAdd ? '' : 'disabled' ?>"
                       style="display: <?php echo !$ajouterFormVisible ? 'inherit' : 'none' ?>">
                        <span class="glyphicon glyphicon-plus"></span> Téléverser un rapport</a>
                </div>
            </div>
            <div id="ajouterForm" style="display: <?php echo $ajouterFormVisible ? 'inherit' : 'none' ?>">
                <?php echo $this->form()->openTag($form) ?>
                <div class="row">
                    <div class="col-md-4">
                        <?php echo $this->formControlGroup($form->get('anneeUniv')) ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        <?php
                        echo $this->formControlGroup($form->get('files'));
                        echo $this->formControlGroup($form->get('estFinal'));
                        echo $this->formControlGroup($form->get('security'));
                        echo $this->formSubmit($form->get('submit')->setAttributes(['class' => 'btn btn-primary']));
                        ?>
                    </div>
                </div>
                <?php echo $this->form()->closeTag() ?>
                <a href="#" id="annulerBtn" class="btn btn-danger">Annuler</a>
            </div>
        </div>

        <?php if ($tousLesRapportsTeleverses): ?>
            <div class="row">
                <div class="col-md-6 text-success">
                    <span class="glyphicon glyphicon-info-sign"></span>
                    Toutes les années universitaires d'inscription du doctorant ont fait l'objet d'un téléversement de rapport.
                </div>
            </div>
        <?php endif ?>

    </div>
</div>


<script>
    $(function() {
        var $ajouterBtn = $("#ajouterBtn");
        var $annulerBtn = $("#annulerBtn");
        var $ajouterForm = $("#ajouterForm");

        $ajouterBtn.on('click', function() {
            $ajouterForm.show();
            $ajouterBtn.hide();
        });
        $annulerBtn.on('click', function() {
            $ajouterForm.hide();
            $ajouterBtn.show();
        });
        $('[data-toggle=confirmation]').confirmation({
            rootSelector: '[data-toggle=confirmation]',
            container: 'body',
            title: "Êtes-vous sûr(e) ?",
            btnOkLabel: "Oui",
            btnCancelLabel: "Non",
        });
    });
</script>
