<?php
/**
 * @var PhpRenderer $this
 * @var These $these
 * @var RapportAnnuel[] $rapportsAnnuels
 * @var RapportAnnuelForm $form
 * @var bool $tousLesRapportsTeleverses
 *
 * @see \Application\Controller\RapportAnnuelController::indexAction()
 */

use Application\Entity\Db\RapportAnnuel;
use Application\Entity\Db\These;
use Application\Filter\IdifyFilter;
use Application\Form\RapportAnnuelForm;
use Application\Provider\Privilege\RapportAnnuelPrivileges;
use Application\View\Renderer\PhpRenderer;

$form->prepare();
$canAdd = $this->isAllowed((new RapportAnnuel())->setThese($these), RapportAnnuelPrivileges::RAPPORT_ANNUEL_TELEVERSER);
if ($tousLesRapportsTeleverses) {
    $canAdd = false;
}
?>

<h1 class="page-header">
    Rapports annuels
</h1>


<?php if (count($rapportsAnnuels) > 0): ?>

<table class="table table-bordered">
    <thead>
    <tr>
        <th>Année universitaire</th>
        <th>Document</th>
        <th>Téléversement</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($rapportsAnnuels as $rapportAnnuel): ?>
    <tr>
        <?php
        $canDel = $this->isAllowed($rapportAnnuel, RapportAnnuelPrivileges::RAPPORT_ANNUEL_TELEVERSER);
        $canDl = $this->isAllowed($rapportAnnuel, RapportAnnuelPrivileges::RAPPORT_ANNUEL_TELECHARGER);
        ?>
        <td>
            <?php echo $rapportAnnuel->getAnneeUnivToString() ?>
            <?php if ($rapportAnnuel->getEstFinal()): ?>
                <br>
                <span class="label label-info">Rapport final</span>
            <?php endif ?>
        </td>
        <td>
            <?php if ($canDl): ?>
                <a href="<?php echo $this->url('fichier/telecharger', ['fichier' => IdifyFilter::id($rapportAnnuel->getFichier())]) ?>">
                    <?php echo $rapportAnnuel->getFichier()->getNom() ?>
                </a>
            <?php else: ?>
                <?php echo $rapportAnnuel->getFichier()->getNom() ?>
            <?php endif; ?>
        </td>
        <td>
            Le <?php echo $rapportAnnuel->getHistoCreation()->format('d/m/Y à H:i:s') ?> par
            <?php echo $rapportAnnuel->getHistoCreateur() ?>
        </td>
        <td class="action">
            <?php if ($canDel): ?>
                <a href="<?php echo $this->url('rapport-annuel/supprimer', ['rapportAnnuel' => $rapportAnnuel->getId()]) ?>"
                   title="Supprimer ce rapport ?"
                   data-toggle="confirmation"><span class="glyphicon glyphicon-trash"></span></a>
            <?php endif; ?>
        </td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<?php else: ?>

    Aucun.

<?php endif; ?>

<hr>

<?php $ajouterFormVisible = !empty($form->getMessages()); ?>
<div id="ajouterDiv">
    <div class="row">
        <div class="col-md-3">
            <a href="#" id="ajouterBtn" class="btn btn-primary <?php echo $canAdd ? '' : 'disabled' ?>"
               style="display: <?php echo !$ajouterFormVisible ? 'inherit' : 'none' ?>">
                <span class="glyphicon glyphicon-plus"></span> Ajouter un rapport</a>
        </div>
    </div>
    <div id="ajouterForm" style="display: <?php echo $ajouterFormVisible ? 'inherit' : 'none' ?>">
        <?php echo $this->form()->openTag($form) ?>
        <div class="row">
            <div class="col-md-4">
                <?php echo $this->formControlGroup($form->get('anneeUniv')) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-5">
                <?php
                echo $this->formControlGroup($form->get('files'));
                echo $this->formControlGroup($form->get('estFinal'));
                echo $this->formControlGroup($form->get('security'));
                echo $this->formSubmit($form->get('submit')->setAttributes(['class' => 'btn btn-primary']));
                ?>
            </div>
        </div>
        <?php echo $this->form()->closeTag() ?>
        <a href="#" id="annulerBtn" class="btn btn-danger">Annuler</a>
    </div>
</div>

<?php if ($tousLesRapportsTeleverses): ?>
    <div class="row">
        <div class="col-md-6 text-success">
            <span class="glyphicon glyphicon-info-sign"></span>
            Toutes les années universitaires d'inscription du doctorant ont fait l'objet d'un téléversement de rapport.
        </div>
    </div>
<?php endif ?>


<script>
    $(function() {
        var $ajouterBtn = $("#ajouterBtn");
        var $annulerBtn = $("#annulerBtn");
        var $ajouterForm = $("#ajouterForm");

        $ajouterBtn.on('click', function() {
            $ajouterForm.show();
            $ajouterBtn.hide();
        });
        $annulerBtn.on('click', function() {
            $ajouterForm.hide();
            $ajouterBtn.show();
        });
        $('[data-toggle=confirmation]').confirmation({
            rootSelector: '[data-toggle=confirmation]',
            container: 'body',
            title: "Êtes-vous sûr(e) ?",
            btnOkLabel: "Oui",
            btnCancelLabel: "Non",
        });
    });
</script>
