<?php

use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var string      $text
 */

/**
 * @param string $paramName
 * @param string $paramValue
 * @param array $queryParams
 * @return string
 */
$urlFiltrer = function ($paramName, $paramValue, $queryParams) {
    $queryParams[$paramName] = $paramValue;
    return $this->url('fichier/deposes', [], ['query' => $queryParams], true);
};

/**
 * Constantes définissant les codes de "version" du fichier.
 *
 * - 'VO' = Version originale
 * - 'VA' = Version d'archivage, destinée à être déposée sur la plateforme STAR
 * - 'VD' = Version de diffusion, expurgée des contenus confidentiels notamment
 * - 'VOC' = Version originale corrigée
 * - 'VAC' = Version d'archivage corrigée, destinée à être déposée sur la plateforme STAR
 * - 'VDC' = Version de diffusion corrigée, expurgée des contenus confidentiels notamment
 */

echo $this->filterPanel([
    $this->translate("Version") => [
        'paramName' => 'version',
        'paramConfig' => [
            ['value' => '',                             'label' => $this->translate(" - ") ],
            ['value' => $v = "VO",                      'label' => $this->translate("VO") ],
            ['value' => $v = "VA",                      'label' => $this->translate("VA") ],
            ['value' => $v = "VD",                      'label' => $this->translate("VD") ],
            ['value' => $v = "VOC",                     'label' => $this->translate("VOC") ],
            ['value' => $v = "VAC",                     'label' => $this->translate("VAC") ],
            ['value' => $v = "VDC",                     'label' => $this->translate("VDC") ],

        ],
        'filterUrl' => $urlFiltrer,
        'titre' => "Version du fichier",
    ],
]);