<?php

use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var string $username
 * @var string $url
 */
?>

<p>
    Bonjour,
</p>
<p>
    Un compte utilisateur local a été créé pour vous dans l'application <strong> <?php echo $this->appInfos()->nom; ?> </strong>.
    Afin de pouvoir vous connecter à l'application, vous devez à présent choisir un mot de passe.
</p>
<p>
    Votre identifiant de connexion est <strong><?php echo $username; ?></strong>. Veuillez le noter car celui-ci vous sera demandé dans le formulaire
    que vous trouverez à l'adresse suivante : <br/>
    <a href="<?php echo $url; ?>"><?php echo $url;?> </a>
</p>



