<?php

use Application\View\Renderer\PhpRenderer;

/**
 * @see
 *
 * @var PhpRenderer $this
 * @var string $username
 * @var string $url
 */

?>

<p>
    Bonjour,
</p>
<p>
    Un compte local vient de vous êtes créer dans l'application <strong> <?php echo $this->appInfos()->nom; ?> </strong>.
    Afin de pouvoir vous connecter à l'application, vous devez initialiser votre compte dans l'application.
</p>
<p>
    Votre nom d'utilisateur est <strong><?php echo $username; ?></strong>. Celui-ci vous sera demandé dans le formulaire
    d'initialisation que vous trouverez à l'adresse suivante : <br/>
    <a href="<?php echo $url; ?>"><?php echo $url;?> </a>
</p>



