<?php

use Application\View\Renderer\PhpRenderer;

/**
 * @see
 *
 * @var PhpRenderer $this
 * @var string $username
 * @var string $url
 */

?>

<p>
    Bonjour,
</p>
<p>
    La réinitialisation du mot de passe de connexion à l'application <strong> <?php echo $this->appInfos()->nom; ?> </strong> vient d'être demandée.
    Afin de pouvoir vous connecter à nouveau à l'application, vous devez donc saisir un nouveau mot de passe.
</p>
<p>
    Votre identifiant de connexion est <strong><?php echo $username; ?></strong>. Veuillez le noter car celui-ci vous sera demandé dans le formulaire
    d'initialisation que vous trouverez à l'adresse suivante : <br/>
    <a href="<?php echo $url; ?>"><?php echo $url;?> </a>
</p>



