<?php

use Application\Entity\Db\These;
use Application\Entity\Db\Acteur;
use Application\Entity\Db\Doctorant;
use Application\Entity\Db\Individu;
use Application\View\Renderer\PhpRenderer;
use Application\Service\Notification\NotifierService;

/**
 * @var PhpRenderer $this
 * @var These       $these
 * @var NotifierService       $notifier
 */


function decorateProbleme($texte) {
    return "<span style='background-color:red;'>" . $texte . "</span>";
}

/**
 * Cette fonction retourne et formate la denomination d'un acteur
 * @param  Acteur       $acteur
 * @param  bool         $civilite permet d'afficher la civilité de l'acteur
 * @return string       la denomination de l'acteur
 */
function getActeurDenomination(Acteur $acteur, $civilite = false) {
    if ($acteur === null) return decorateProbleme("acteur non renseigné");
   return getIndividuDenomination($acteur->getIndividu(), $civilite);
}
/**
 * Cette fonction retourne et formate la denomination d'un doctorant
 * @param  Doctorant    $doctorant
 * @param  bool         $civilite permet d'afficher la civilité du doctorant
 * @return string       la denomination du doctorant
 */
function getDoctorantDenomination(Doctorant $doctorant, $civilite = false) {
    if ($doctorant === null) return decorateProbleme("doctorant non renseigné");
    return getIndividuDenomination($doctorant->getIndividu(), $civilite);
}
/**
 * Cette fonction retourne et formate la denomination d'un individu
 * @param Individu      $individu
 * @param bool          $civilite
 * @return string       la denomination de l'individu
 *
 * RMQ: en cas où le nom usuel et le nom patronymique sont différent alors les deux sont affichés liés d'un trait d'union
 * RMQ: elle est appellé par les autres fonctions getXXXDenomination
 */
function getIndividuDenomination(Individu $individu, $civilite = false) {

    if ($individu === null) return decorateProbleme("individu non renseigné");

    $texte = "";
    if ($civilite) $texte .= $individu->getCivilite(). " ";
    $texte .= ucwords(strtolower($individu->getPrenom1(). " "), " -");
    $texte .= $individu->getNomUsuel();
    if ($individu->getNomUsuel() != $individu->getNomPatronymique()) {
        $texte .= "-".$individu->getNomPatronymique();
    }
    return $texte;
}

/**
 * Cette fonction retourne le rôle d'un acteur au sein d'une thèse avec la notation "correcte"
 * @param Acteur        $acteur
 * @param bool          $inclusive permet l'utilisation de l'écriture inclusive
 * @return string       le rôle "corrigé"
 *
 * TODO gérer les co-directeurs / co-directrices
 */
function getActeurRole(Acteur $acteur, $inclusive) {
    $roleCode   = $acteur->getRole()->getSourceCode();
    $abrev      = explode("::", $roleCode)[1];
    $femme      = $acteur->getIndividu()->estUneFemme();

    $role = "Inconnu";
    switch ($abrev) {
        case ($abrev == "R" && !$inclusive) :
            $role = "Rapporteur";
            break;
        case ($abrev == "R" && $inclusive && $femme):
            $role = "Rapportrice";
            break;
        case ($abrev == "D" && !$inclusive) :
            $role = "Directeur";
            break;
        case ($abrev == "D" && $inclusive && $femme):
            $role = "Directrice";
            break;
        case ($abrev == "M" && !$inclusive) :
            $role = "Examinateur";
            break;
        case ($abrev == "M" && $inclusive && $femme):
            $role = "Examinatrice";
            break;
        default:
            $role = decorateProbleme("role non renseigné");
            break;
    }
    return $role;

}

/**
 * Cette fonction retourne le code HTML associé au logo de la COMUE
 * @return string
 */
function generateLogoComue() {
    $img_src = APPLICATION_DIR . "/ressources/Logos/Etab/COMUE.png";
    $texte  = "<div class='logo-comue'>";
    $texte .= "<img src='".$img_src."'/>";
    $texte .= "</div>";

    return $texte;
}

/**
 * Cette fonction retourne le code HTML du bloc de description du diplôme
 * @param These         $these
 * @return string
 */
function generateDiplomeInfos(These $these) {

    //Preparation des champs obligatoires ---
    $specialite = null;
    if ($these->getLibelleDiscipline() === null) {
        $specialite = decorateProbleme("Spécialité non renseignée");
    } else {
        $specialite = ucwords(mb_strtolower($these->getLibelleDiscipline()));
    }

    $etablissement = null;
    if ($these->getEtablissement() === null) {
        $etablissement = decorateProbleme("Établissement non renseigné");
    } else {
        $etablissement = $these->getEtablissement()->getLibelle();
    }
    $texte  = "<div class='bandeau-these'>THÈSE</div>";
    $texte .= "<div class='infos-diplome'>";
    $texte .= "<span class='larger-infos'>Pour obtenir le diplôme de doctorat" ."</span><br/>";
    $texte .= "Spécialité ". $specialite ."<br/>";
    $texte .= "Préparé au sein de l'". $etablissement ."<br/>";

    //Preparation des champs associés à la cotutelle
    if ($these->getLibelleEtabCotutelle() !== null && $these->getLibellePaysCotutelle() === null) {
        $texte .= "En cotutelle avec " . $these->getLibelleEtabCotutelle() . "<br/>";
    }
    if ($these->getLibelleEtabCotutelle() !== null && $these->getLibellePaysCotutelle() !== null) {
        $texte .= "En cotutelle internationale de thèse avec " . $these->getLibelleEtabCotutelle() .", ". $these->getLibellePaysCotutelle() . "<br/>";
    }

    $texte .= "</div>";
    return $texte;
}

/**
 * Cette fonction retourne le code HTML du bloc de titre
 * @param These         $these
 * @return string
 */
function generateTitre(These $these) {

    $titre = null;
    if ($these->getTitre() === null) {
        $titre = decorateProbleme("Aucun titre de renseigné");
    } else {
        $titre = $these->getTitre();
    }

    $texte  = "<div class='bandeau-titre'>".$titre."</div>";
    return $texte;
}

/**
 * Cette fonction retourne le code HTML du bloc de description du diplôme
 * @param These         $these
 * @return string
 */
function generateDoctorantInfos(These $these) {
    $texte  = "<div class='infos-doctorant' style=''>";
    $texte .= "Présentée et soutenue par" . "<br/>";
    $texte .= getDoctorantDenomination($these->getDoctorant(), false) . "<br/>";
    $texte .= "</div>";

    return $texte;
}

/**
 * Prédicat testant si un acteur est un directeur de thèse
 * @param Acteur $var
 * @return bool
 */
function estDirecteur(Acteur $var) {
    $role = $var->getRole()->getSourceCode();
    return  (explode("::", $role)[1] == "D");
}
/**
 * Prédicat testant si un acteur est un rapporteur de thèse
 * @param Acteur $var
 * @return bool
 */
function estRapporteur(Acteur $var) {
    $role = $var->getRole()->getSourceCode();
    return  (explode("::", $role)[1] == "R");
}
/**
 * Cette fonction retourne le code HTML du bloc de description du diplôme
 * @param These         $these
 * @param bool          $inclusive gère l'utilisation de l'écriture inclusive pour les rôles
 * @return string
 */
function generateJuryInfos(These $these, $inclusive=false) {

    $dateTxt = "<span style='background-color:red;'> JJ/MM/AAAA </span>";
    if ($these->getDateSoutenance() !== null) {
        $dateTxt = $these->getDateSoutenance()->format("d/m/Y");
    }
    $publiquement = "publiquement";
    $jury = $these->getActeurs()->toArray();

    $texte  = "<table class='jury'>";
    $texte .= "<tr><th colspan='3'>";
    $texte .= "Thèse soutenue ".$publiquement." le ".$dateTxt." <br/>";
    $texte .= "devant le jury composé de";
    $texte .= "</th></tr>";


    $rapporteurs = array_filter($jury, "estRapporteur");
    $directeurs = array_filter($jury, "estDirecteur");
    $membres =  array_diff(array_diff($jury, $rapporteurs), $directeurs);
    $roles = [$rapporteurs, $membres, $directeurs];

    if (count($rapporteurs) === 0 || count($membres) === 0) {
        $texte .= "<tr><td colspan='3'>";
        $texte .= "<span style='background-color:red;'> Le jury doit être renseigné dans SyGAL pour que la page de couverture générée soit valide ! </span>";
        $texte .= "</td></tr>";
    }

    /** @var \Application\Entity\Db\Acteur $acteur */
    foreach ($roles as $subroles) {
        foreach ($subroles as $acteur) {

            $nom  = getActeurDenomination($acteur, true);

            $qualite = null;
            if ($acteur->getQualite() === null || $acteur->getQualite() === " ") {
                $qualite = decorateProbleme("Aucune qualité renseignée");
            } else {
                $qualite = $acteur->getQualite();
            }

            $etablissement = null;
            if ($acteur->getEtablissement() === null || $acteur->getEtablissement() === " ") {
                $etablissement = decorateProbleme("Aucun établissement renseigné");
            } else {
                $etablissement = $acteur->getEtablissement();
            }

            $role = getActeurRole($acteur, $inclusive);

            $texte .= "<tr>";
            $texte .= "<td>".$nom."</td>";
            $texte .= "<td>".$qualite.", ".$etablissement."</td>";
            $texte .= "<td>".$role."</td>";
            $texte .= "</tr>";
        }}
    $texte .= "</table>";
    return $texte;
}

/** Fonction générant le code HTML lié au encradrant
 * @param These         $these
 * @return string
 */
function generateEncadrementInfos(These $these) {

    $ur = null;
    if ($these->getUniteRecherche() === null) {
        $ur = decorateProbleme("unite de recherche non renseignée");
    } else {
        $ur = $these->getUniteRecherche()->getLibelle();
    }

    $directeurs = array_filter($these->getActeurs()->toArray(), "estDirecteur");
    $texte  = "<div class='infos-encadrement'>";
    $texte .= "Thèse dirigée par ";
    /** @var \Application\Entity\Db\Acteur $directeur */
    $directeurs_array = [];
    foreach ($directeurs as $directeur) {
        $directeurs_array[] = getActeurDenomination($directeur);
    }



    $texte .= implode(" et ", $directeurs_array);
    $texte .= ", ";
    $texte .= $ur;
    $texte .= "</div>";
    return $texte;
}

/** Fonction générant le code HTML lié au encradrant
 * @param These         $these
 * @param NotifierService $notifier
 * @return string
 */
function generateLogos(These $these, NotifierService $notifier = null) {

    if ($notifier !== null && $these->getEtablissement()->getCheminLogo() === null)
        $notifier->triggerLogoAbsentEtablissement($these->getEtablissement());
    if ($notifier !== null && $these->getEcoleDoctorale()->getCheminLogo() === null)
        $notifier->triggerLogoAbsentEcoleDoctorale($these->getEcoleDoctorale());
    if ($notifier !== null && $these->getUniteRecherche()->getCheminLogo() === null)
        $notifier->triggerLogoAbsentUniteRecherche($these->getUniteRecherche());



    $logouni = null;
    if ($these->getEtablissement() !== null) $logouni = $these->getEtablissement()->getCheminLogo();
    $logoed  = null;    if ($these->getEcoleDoctorale() !== null) $logoed  = $these->getEcoleDoctorale()->getCheminLogo();
    $logour  = null;    if ($these->getUniteRecherche() !== null) $logour  = $these->getUniteRecherche()->getCheminLogo();

    $texte = "";
    $texte  .= "<div class='logos'>";
    $texte .= "<table style='border:none;' class='logos'>";
    $texte .= "<tr><td>";
    if ($logouni !== null) {
        $texte .= "<img class='logo_small' src='" . APPLICATION_DIR . $logouni . "'/>";
    } else {
        $texte .= "<span style='background-color:red;'>";
        $texte .= "Aucun logo de trouvé <br/>";
        $texte .= "Établissement <br/>";
        if ($these->getEtablissement() !== null) $texte .= $these->getEtablissement()->getLibelle();
        $texte .= "</span>";
    }
    $texte .= "</td><td>";
    if ($these->getLibelleEtabCotutelle() !== null) {
        $texte .= "<span style='background-color:red;'>";
        $texte .= "Aucun logo de trouvé <br/>";
        $texte .= "Co-tutelle <br/>";
        $texte .= "</span>";
        $texte .= "</td><td>";
    }
    if ($logoed !== null) {
        $texte .= "<img class='logo_small' src='" . APPLICATION_DIR . $logoed . "'/>";
    } else {
        $texte .= "<span style='background-color:red;'>";
        $texte .= "Aucun logo de trouvé <br/>";
        $texte .= "École doctorale <br/>";
        if ($these->getEcoleDoctorale() !== null) $texte .= $these->getEcoleDoctorale()->getSigle();
        $texte .= "</span>";
    }
    $texte .= "</td><td>";
    if ($logour !== null) {
        $texte .= "<img class='logo_small' src='" . APPLICATION_DIR . $logour . "'/>";
    } else {
        $texte .= "<span style='background-color:red;'>";
        $texte .= "Aucun logo de trouvé <br/>";
        $texte .= "Unité de recherche <br/>";
        if ($these->getUniteRecherche() !== null) $texte .= $these->getUniteRecherche()->getSigle();
        $texte .= "</span>";
    }
    $texte .= "</td></tr></table>";
    $texte .= "</div>";

    return $texte;
}

?>



<div style="text-align: center; margin-bottom: 30px;">
    <?php echo generateLogoComue(); ?>
</div>
<?php echo generateDiplomeInfos($these); ?>
<?php echo generateTitre($these); ?>
<?php echo generateDoctorantInfos($these); ?>
<br/>
<?php echo generateJuryInfos($these) ?>
<br/>
<?php echo generateEncadrementInfos($these); ?>
<?php echo generateLogos($these, $notifier); ?>
<?php //echo generateLogos($these); ?>

<!-- ATTENTION -->
<!-- Can't open file /var/www/html/sygal/vendor/mpdf/mpdf/ttfontdata/ -->