<table width="100%" style="font-size: 90%; vertical-align: bottom;">
    <tr>
        <td width="33%">{PAGENO}/{nbpg}</td>
        <td width="10%" align="center"><!--<em><strong><?php /*echo $this->footerTitle; */?></strong></em>--></td>
        <td width="33%" style="text-align: right;">
            <address>
                ESPLANADE DE LA PAIX / CS 14032 / 14032 CAEN CEDEX 5<br>
                <strong>tél.</strong> +33 (0)2 31 56 69 57 &nbsp; <strong>fax</strong> +33 (0)2 31 56 69 51<br>
                presidence@normandie-univ.fr &nbsp; www.normandie-univ.fr
            </address>
        </td>
    </tr>
</table>
