<?php

use Application\Entity\Db\These;
use Application\Entity\Db\WfEtape;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer         $this
 * @var These               $these
 * @var null|string|WfEtape $etape
 * @var string[]|WfEtape[]  $except
 */

$wfHelper = $this->wf($these);
$wfStepHelper = isset($etape) ? $wfHelper->next($etape) : $wfHelper->current();

if (!empty($except)) {
    foreach ((array)$except as $e) {
        if ($wfStepHelper->isStep($e)) {
            return;
        }
    }
}
?>

<?php if ($wfStepHelper->isStepAtteignable()): ?>

    <div class="box panel panel-success roadmap-next-step">
        <div class="panel-heading">
            <h2 class="first">Et ensuite ?</h2>
        </div>
        <div class="panel-body">
            <nav aria-label="Etape suivante">
                <ul class="roadmap pagination">
                    <li><?php echo $wfStepHelper->render() ?></li>
                </ul>
            </nav>
        </div>
    </div>

<?php elseif ($wfStepHelper->step() === null): ?>

    <div class="box panel panel-success roadmap-next-step">
        <div class="panel-heading">
            <h2 class="first">Et ensuite ?</h2>
        </div>
        <div class="panel-body">
            <p class="lead"><!--<span class="glyphicon glyphicon-thumbs-up"></span>--> C'est terminé : dépôt validé.</p>
        </div>
    </div>

<?php endif ?>
