<?php

use Application\Entity\Db\These;
use Application\Entity\Db\WfEtape;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer         $this
 * @var These               $these
 * @var null|string|WfEtape $etape
 * @var string[]|WfEtape[]  $except
 * @var string              $message
 */

$wfHelper = $this->wf($these);
$wfStepHelper = isset($etape) ? $wfHelper->next($etape) : $wfHelper->current();

if (!empty($except)) {
    foreach ((array)$except as $e) {
        if ($wfStepHelper->isStep($e)) {
            return;
        }
    }
}
?>

<?php if ($wfStepHelper->isStepAtteignable()): ?>

    <?php if (in_array($these->getEtatThese(), [These::ETAT_EN_COURS, These::ETAT_SOUTENUE])): ?>
        <div class="box panel panel-success roadmap-next-step">
            <div class="panel-heading">
                <h2 class="first">Et ensuite ?</h2>
            </div>
            <div class="panel-body">
                <nav aria-label="Etape suivante">
                    <ul class="roadmap pagination">
                        <?php if ($message): ?>
                            <li><?php echo $message ?></li>
                        <?php else: ?>
                            <li><?php echo $wfStepHelper->render() ?></li>
                        <?php endif ?>
                    </ul>
                </nav>
            </div>
        </div>
    <?php endif ?>

<?php elseif ($wfStepHelper->step() === null): ?>

    <?php if (in_array($these->getEtatThese(), [These::ETAT_EN_COURS, These::ETAT_SOUTENUE])): ?>
        <div class="box panel panel-success roadmap-next-step">
            <div class="panel-heading">
                <h2 class="first">Et ensuite ?</h2>
            </div>
            <div class="panel-body">
                <p class="lead">
                    <?php if ($message): ?>
                        <?php echo $message ?>
                    <?php else: ?>
                        C'est terminé : dépôt validé.
                    <?php endif ?>
                </p>
            </div>
        </div>
    <?php endif ?>

<?php endif ?>
