<?php

use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var \Doctrine\DBAL\Result $result
 * @var string[] $attributes [name => label]
 * @var string $routeName
 * @var string $routeParamName
 */
?>

<style>
    .npd-force {
        font-size: 65%;
        vertical-align: super;
        padding-left: 0.15em;
    }
</style>

<?php if ($count = $result->rowCount()): ?>
    <p><?php echo $count ?> substituants trouvés.</p>

    <table class="table table-bordered table-extra-condensed">
        <tr>
            <th>Substituant</th>
            <th><?php echo implode(', ', $attributes) ?></th>
            <th>NPD</th>
            <th>Substitués</th>
        </tr>
        <?php while ($row = $result->fetchAssociative()): ?>
            <?php
            $fromIds = array_map('trim', explode('|', $row['from_ids']));
            $npdForces = array_combine(
                $fromIds,
                array_map('trim', explode('|', $row['npd_forces']))
            );
            $substitueUrls = array_combine(
                $fromIds,
                array_map(
                    fn($id) => sprintf(
                        '<a href="%s"><span title="Accéder à la fiche détaillée de ce substitué">%s</span></a><i class="%s npd-force text-danger fas fa-hammer" title="%s"></i>',
                        $routeName ? $this->url($routeName, [$routeParamName => $id]) : "#",
                        $id,
                        $npdForces[$id] ? 'visible' : 'invisible',
                        sprintf("NPD forcé (i.e. substitution manuelle) : '%s'", $npdForces[$id]),
                    ),
                    $fromIds
                )
            );
            ?>
            <tr>
                <td>
                    <a href="<?php echo $routeName ? $this->url($routeName, [$routeParamName => $row['to_id']]) : '#' ?>"
                       title="Accéder à la fiche détaillée de ce substituant">
                        <?php echo $row['to_id'] ?></a><i
                            class="<?php echo $row['update_enabled'] === false ? 'visible' : 'invisible' ?> npd-force text-danger fas fa-lock"
                            title="La mise à jour automatique des attributs de ce substituant à partir de ceux des substitués est désactivée"></i>
                </td>
                <td><?php echo implode(', ', array_map(fn($name) => $row[$name], array_keys($attributes))) ?></td>
                <td><?php echo $row['npd'] ?></td>
                <td><?php echo implode(', ', $substitueUrls) ?></td>
            </tr>
        <?php endwhile ?>
    </table>
<?php else: ?>
    <p>Aucune.</p>
<?php endif ?>
