<?php
/**
 * @var \Application\View\Renderer\PhpRenderer $this
 * @var string $type
 * @var array $substitution
 * @var string $informationPartial
 * @var object $substituant
 * @var ?object[] $substitues
 */

$fromDatesCreations = array_combine(array_keys($substitues), explode('|', $substitution['from_dates_creations']));
$fromNpdForces = array_combine(array_keys($substitues), explode('|', $substitution['from_npd_forces']));
$fromSources = array_combine(array_keys($substitues), explode('|', $substitution['from_sources']));
$i = 1;
?>

<h1 class="page-header">
    Détails de la substitution
    <span class="badge bg-primary text-uppercase p-1"><?php echo $type ?></span>
    <code><abbr title="NPD"><?php echo $substitution['npd'] ?></abbr></code>
</h1>

<div class="row align-items-start py-3">
    <div class="col">
        <div class="card mb-3" style="border-width: 4px">
            <div class="card-header">
                <h2 style="margin: 0">Substituant<br><?php echo $substituant->getId() ?></h2>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <dl>
                        <dt>Source</dt>
                        <dd><?php echo $substituant->getSource()->getCode() ?></dd>
                        <dt>Créé le</dt>
                        <dd><?php echo $substituant->getHistoCreation()->format('d/m/Y à H:i:s') ?></dd>
                        <dt>Mise à jour automatique
                            <span class="fas fa-info-circle"
                                  title="Mise à jour automatique des attributs du substituant en cas de mise à jour des attributs d'un substitué ?"></span>
                        </dt>
                        <dd>
                            <?php if ($substituant->estSubstituantModifiable()): ?>
                                <span class="badge bg-success">Activée</span>
                            <?php else: ?>
                                <span class="badge bg-danger">Désactivée</span>
                            <?php endif ?>
                        </dd>
                    </dl>
                </li>
                <li class="list-group-item">
                    <?php echo $this->partial($informationPartial, ['entity' => $substituant, 'verbose' => true, 'includeGotoDetailsLink' => true]) ?>
                </li>
            </ul>
        </div>
    </div>
    <?php foreach ($substitues as $id => $substitue): ?>
        <div class="col">
            <div class="card mb-3" style="opacity: 70%">
                <div class="card-header">
                    <span class="float-end"><?php echo $i++ . '/' . count($substitues) ?></span>
                    <h2 style="margin: 0">Substitué<br><?php echo $id ?></h2>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <dl>
                            <dt>Source</dt>
                            <dd><?php echo $fromSources[$id] ?></dd>
                            <dt>Substitué le</dt>
                            <dd><?php echo $fromDatesCreations[$id] ?></dd>
                            <dt>NPD forcé</dt>
                            <dd>
                                <?php if ($fromNpdForces[$id] <> ''): ?>
                                    <?php echo $fromNpdForces[$id] ?>
                                <?php else: ?>
                                    (Aucun)
                                <?php endif ?>
                            </dd>
                        </dl>
                    </li>
                    <li class="list-group-item <?php echo $substitue === null ? 'text-danger' : '' ?>">
                        <?php if ($substitue === null): ?>
                            <h3>Enregistrement introuvable !</h3>
                            <p><?php echo \Substitution\Constants::MSG_SUBSTITUE_INTROUVABLE ?></p>
                        <?php else: ?>
                            <?php echo $this->partial($informationPartial, ['entity' => $substitue, 'verbose' => true, 'includeGotoDetailsLink' => true]) ?>
                        <?php endif ?>
                    </li>
                </ul>
            </div>
        </div>
    <?php endforeach; ?>
</div>

