<?php

use Formation\Entity\Db\Inscription;

/**
 * @see \Formation\Service\Notification\NotificationService::triggerInscriptionListePrincipale()
 * @var Inscription $inscription
 * @var string $lilbelle
 */

$session = $inscription->getSession();
$libelle = $session->getFormation()->getLibelle();
$date = $session->getDateDebut()->format('d/m/Y');
$horaire = $session->getDateDebut()->format('H:i');
$gestionnaire = ($session->getFormation()->getResponsable())?$session->getFormation()->getResponsable()->getNomComplet():$this->appInfos()->nom;
?>
<p>
Cher&middot;e doctorant&middot;e,
</p>

<p>
    Vous êtes inscrit&middot;e en <strong>liste principale</strong> de la formation <?php echo $libelle; ?> le <?php echo $date; ?> de <?php echo $horaire; ?>.
    Pensez à bien reserver cette date dans votre agenda.
</p>
<p>
    Si vous avez besoin d'une convocation, vous pouvez retrouver celle-ci dans <?php echo $this->appInfos()->nom ?> dans la partie
    '<em>Mes formations</em>' onglet '<em>Mes inscriptions en cours</em>'.
</p>
<p>
    En cas d'empèchement pensez à vous desinscrire afin de libérer votre place pour une personne de la liste complémentaire.
</p>
<p>
    Cordialement,<br/>
    <?php echo $gestionnaire; ?>
</p>