<?php

use Formation\Entity\Db\Inscription;

/**
 * @see \Formation\Service\Notification\NotificationService::triggerInscriptionListeComplementaire()
 * @var Inscription $inscription
 * @var string $lilbelle
 */

$session = $inscription->getSession();
$libelle = $session->getFormation()->getLibelle();
$date = $session->getDateDebut()->format('d/m/Y');
$horaire = $session->getDateDebut()->format('H:i');
$gestionnaire = ($session->getFormation()->getResponsable())?$session->getFormation()->getResponsable()->getNomComplet():$this->appInfos()->nom;

?>
<p>
Cher&middot;e doctorant&middot;e,
</p>

<p>
    Vous êtes inscrit&middot;e sur la <strong>liste complementaire</strong> de la formation <?php echo $libelle; ?> le <?php echo $date; ?> de <?php echo $horaire; ?>.
    Si une place en liste principale se libère vous serez informé&middot;e par l'application <?php echo $this->appInfos()->nom ?>.
</p>
<p>
    Cordialement,<br/>
    <?php echo $gestionnaire; ?>
</p>