<?php

namespace Application;

use Application\Entity\Db\Rapport;
use Application\Entity\Db\Role;
use Application\Filter\ActeursFormatter;
use Application\Filter\IdifyFilter;
use Application\Provider\Privilege\RapportPrivileges;
use Application\Search\EcoleDoctorale\EcoleDoctoraleSearchFilter;
use Application\Search\Etablissement\EtablissementSearchFilter;
use Application\Search\Rapport\AnneeRapportActiviteSearchFilter;
use Application\Search\UniteRecherche\UniteRechercheSearchFilter;
use Application\Service\Rapport\RapportSearchService;
use UnicaenAuth\Provider\Privilege\Privileges;
use Zend\Paginator\Paginator as ZendPaginator;

/**
 * @var ZendPaginator $paginator
 */

$canDlZip = $this->isAllowed(Privileges::getResourceId(RapportPrivileges::RAPPORT_ACTIVITE_TELECHARGER_ZIP));
$queryParams = $this->queryParams();

$acteursFormatterDirecteurs = new ActeursFormatter();
$acteursFormatterDirecteurs->asSeparated()
    ->paramDisplay(['role' => false, 'complement' => false, "qualite" => false, "etablissement" => false,])
    ->paramFilter((['role' => Role::CODE_DIRECTEUR_THESE]));
$acteursFormatterCodirecteurs = new ActeursFormatter();
$acteursFormatterCodirecteurs->asSeparated()
    ->paramDisplay(['role' => false, 'complement' => false, "qualite" => false, "etablissement" => false,])
    ->paramFilter((['role' => Role::CODE_CODIRECTEUR_THESE]));

$this->headTitle($this->translate($title = "Rapports d'activité"));
?>

<h1 class="page-header">Rapports d'activité</h1>

<!-- Formulaire de filtrage -->
<div class="pull-left">
    <?php $loadFiltersUrl = $this->url('rapport-activite/recherche/filters', [], ['query' => $this->queryParams()], true); ?>
    <div id="filters" data-url="<?php echo $loadFiltersUrl ?>" style="min-height: 130px">
        <!-- Contenu chargé en AJAX -->
    </div>
</div>
<div class="clearfix"></div>


<?php if (count($paginator) > 0): ?>

    <p>
        <?php
        echo $paginator->getTotalItemCount();
        echo " ";
        echo $this->translate("rapport(s) trouvé(s).");
        ?>
    </p>

    <table class="table table-condensed">
        <thead>
        <tr>
            <?php if ($displayEtablissement = true): ?>
                <th>
                    <a href="<?php echo $s = $this->sortable(EtablissementSearchFilter::NAME) ?>"
                       title="<?php echo $this->translate("Établissement") ?> ">
                        <?php echo $this->translate("Étab.") ?>
                    </a> <?php echo $s->icon() ?>
                </th>
            <?php endif ?>
            <th>
                <a href="<?php echo $s = $this->sortable(RapportSearchService::NAME_nom_doctorant) ?>"
                   title="<?php echo $this->translate("Identité du doctorant") ?>">
                    <?php echo $this->translate("Doctorant") ?>
                </a> <?php echo $s->icon() ?>
            </th>
            <th>
                <?php echo $this->translate("Directeur(s) de thèse"); ?>
            </th>
            <th>
                <a href="<?php echo $s = $this->sortable(EcoleDoctoraleSearchFilter::NAME); ?>"
                   title="<?php echo $this->translate("École doctorale"); ?>">
                    <?php echo $this->translate("École<br>doct."); ?>
                </a> <?php echo $s->icon() ?>
            </th>
            <th>
                <a href="<?php echo $s = $this->sortable(UniteRechercheSearchFilter::NAME); ?>"
                   title="<?php echo $this->translate("Unité de recherche"); ?>">
                    <?php echo $this->translate("Unité<br>rech."); ?>
                </a> <?php echo $s->icon() ?>
            </th>
            <th>
                <a href="<?php echo $s = $this->sortable(AnneeRapportActiviteSearchFilter::NAME); ?>"
                   title="<?php echo $this->translate("Année universitaire concernée par le rapport"); ?>">
                    <?php echo $this->translate("Année du<br>rapport"); ?>
                </a> <?php echo $s->icon() ?>
            </th>
            <th>
                Type
            </th>
            <th>
                Téléversé le
            </th>
            <th>
                Document
            </th>
        </tr>
        </thead>

        <tbody>
        <?php /** @var Rapport $rapport */
        foreach ($paginator as $rapport): ?>
            <?php
            $these = $rapport->getThese();
            $canDl = $this->isAllowed($rapport, RapportPrivileges::RAPPORT_ACTIVITE_TELECHARGER_TOUT) || $this->isAllowed($rapport, RapportPrivileges::RAPPORT_ACTIVITE_TELECHARGER_SIEN);
            ?>
            <tr>
                <?php
                if ($displayEtablissement) {
                    echo "<td>";
                    echo "<abbr title='";
                    echo $these->getEtablissement()->getLibelle();
                    echo "'>";
                    echo $these->getEtablissement()->getCode();
                    echo "</abbr>";
                    echo "</td>";
                }
                ?>
                <td>
                    <a href="<?php echo $this->url('these/identite', ['these' => $these->getId()], [], true) ?>"
                       title="<?php echo $these->getTitre() ?>">
                        <?php echo $these->getDoctorant()->getIndividu()->getNomComplet() ?>
                    </a>
                </td>
                <td class="acteurs">
                    <?php
                    $directeurs = $acteursFormatterDirecteurs->filter($these->getActeurs());
                    foreach ($directeurs as $directeur) {
                        echo $acteursFormatterDirecteurs->htmlifyActeur($directeur)."<br/>";
                    }
                    $codirecteurs = $acteursFormatterCodirecteurs->filter($these->getActeurs());
                    foreach ($codirecteurs as $codirecteur) {
                        echo $acteursFormatterCodirecteurs->htmlifyActeur($codirecteur)."<br/>";
                    }
                    ?>
                </td>
                <td>
                    <?php if ($ed = $these->getEcoleDoctorale()): ?>
                        <abbr title="<?php echo $ed->getLibelle() ?>">
                            <?php echo $ed->getStructure()->getCode(); ?>
                        </abbr>
                    <?php endif ?>
                </td>
                <td>
                    <?php if ($ur = $these->getUniteRecherche()): ?>
                        <abbr title="<?php echo $ur->getLibelle() ?>">
                            <?php echo $ur->getStructure()->getCode(); ?>
                        </abbr>
                    <?php endif ?>
                </td>
                <td>
                    <?php echo $rapport->getAnneeUnivToString() ?>
                </td>
                <td>
                    <span class="label label-info"><?php echo $rapport->getTypeRapport()->getLibelleCourt() ?></span>
                </td>
                <td class="text-sm">
                    <?php echo "Le " . $rapport->getHistoCreation()->format('d/m/Y H:i') . " par " . $rapport->getHistoCreateur() ?>
                </td>
                <td>
                    <?php $title = "Téléversé le " . $rapport->getHistoCreation()->format('d/m/Y à H:i:s') . " par " . (string) $rapport->getHistoCreateur() ?>
                    <?php if ($canDl): ?>
                        <a href="<?php echo $this->url('rapport-activite/telecharger', ['rapport' => IdifyFilter::id($rapport)]) ?>"
                        title="<?php echo $title ?>">
                            <?php echo $rapport->getFichier()->getNom() ?>
                        </a>
                    <?php else: ?>
                        <span title="<?php echo $title ?>"><?php echo $rapport->getFichier()->getNom() ?>
                        </span>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>

    <?php echo $paginationControl = $this->paginationControl($paginator, 'sliding', 'partial/paginator.phtml', ['route' => 'these']) ?>

    <?php if ($canDlZip): ?>
        <a class="btn btn-default" href="<?php echo $this->url('rapport-activite/recherche/telecharger-zip', [], ['query' => $queryParams]) ?>"
           title="Télécharger tous ces rapports sous la forme d'une archive compressée (.zip)">
            <span class="glyphicon glyphicon-export"></span>
            <?php echo $this->translate("Télécharger les rapports"); ?>
        </a>
    <?php endif ?>

<?php else: ?>

    <p>Aucun rapport trouvé.</p>

<?php endif ?>


<script>
    $(function() {
        $("#filters").refresh();
    });
</script>