<?php

/**
 * @var bool $enabled
 * @var string $url
 **/

use Laminas\Feed\Reader\Entry\Rss;
use Laminas\Feed\Reader\Reader;

?>

<?php if ($enabled): ?>

    <ul class="menu-actualites nav nav-pills nav-stacked">
        <?php
        try {
            $channel = Reader::import($url);
            $items = array_reverse(iterator_to_array($channel));
            $error = null;
        } catch (Exception $e) {
            $items = [];
            $error = "Erreur lors de l'interrogation du fil d'actualités : " . $e->getMessage();
            error_log($error);
        }
        ?>
        <?php foreach ($items as $item): /** @var Rss $item */ ?>
            <li>
                <h2>
                    <span class="label label-info">Actualité</span>
                    <a target="_blank" title="Cliquez pour ouvrir dans un nouvel onglet"
                       href="<?php echo $item->getLink() ?>"><?php echo $item->getTitle() ?> <i
                                class="fa fa-external-link-alt"></i></a>
                </h2>
                <p class="date"><?php echo $item->getDateCreated()->format('d/m/Y H:i') ?></p>
            </li>
        <?php endforeach ?>
        <?php if ($error !== null): ?>
            <li class="text-danger"><?php echo $error ?></li>
        <?php endif; ?>
    </ul>

<?php endif; ?>