<?php

/**
 * @var bool $enabled
 * @var string $url
 **/

use Laminas\Feed\Reader\Entry\Rss;
use Laminas\Feed\Reader\Reader;

?>

<?php if ($enabled): ?>

    <div id="menu-actualites" class="card">
        <div class="card-header">
            Actualités
        </div>
        <?php
        try {
            $channel = Reader::import($url);
            $items = array_reverse(iterator_to_array($channel));
            $error = null;
        } catch (Exception $e) {
            $items = [];
            $error = "Erreur lors de l'interrogation du fil d'actualités : " . $e->getMessage();
            error_log($error);
        }
        ?>
        <ul class="card-body nav flex-column">
        <?php foreach ($items as $item): /** @var Rss $item */ ?>
            <li class="nav-item">
                <h2>
                    <a class="nav-link" target="_blank" title="Cliquez pour ouvrir dans un nouvel onglet"
                       href="<?php echo $item->getLink() ?>"><?php echo $item->getTitle() ?> <i
                                class="fa fa-external-link-alt"></i>
                        <p class="date"><?php echo $item->getDateCreated()->format('d/m/Y H:i') ?></p></a>
                </h2>
            </li>
        <?php endforeach ?>
        <?php if ($error !== null): ?>
            <li class="text-danger"><?php echo $error ?></li>
        <?php endif; ?>
        </ul>
    </div>

<?php endif; ?>