-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sygaldb.unicaen.fr;sid=SYGLPROD;port=1523

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

function individu_haystack(
    NOM_USUEL varchar2,
    NOM_PATRONYMIQUE varchar2,
    PRENOM1 varchar2,
    EMAIL varchar2,
    SOURCE_CODE varchar2) RETURN VARCHAR2
AS
BEGIN
    return trim(str_reduce(
                NOM_USUEL || ' ' || PRENOM1 || ' ' || NOM_PATRONYMIQUE || ' ' || PRENOM1 || ' ' ||
                PRENOM1 || ' ' || NOM_USUEL || ' ' || PRENOM1 || ' ' || NOM_PATRONYMIQUE || ' ' ||
                EMAIL || ' ' ||
                SOURCE_CODE
        ));
END;

