<?php

/**
 * @var string[] $keys
 * @var array $queryParams
 */

?>

<button id="tout" class="btn btn-primary">
    <span class="glyphicon glyphicon-ok-circle"></span> Tout sélectionner
</button>
<button id="aucun" class="btn btn-primary">
    <span class="glyphicon glyphicon-ban-circle"></span> Tout désélectionner
</button>

<form method="POST" action="<?php echo $this->url('export/csv', [], ["query" => $queryParams], true); ?>">
    <input type="submit" class="btn btn-primary" value="Exporter les données">
    <?php foreach ($keys as $position => $key): ?>
        <div class="checkbox">
            <label>
                <input type="checkbox" id="<?php echo $position; ?>" name="<?php echo $position; ?>" checked > <?php echo $key; ?>
            </label>
        </div>
    <?php endforeach; ?>

</form>

<script>
    $(function() {
        $("button#tout").on("click", function () {
            $("input[type=checkbox]").prop("checked", true);
        });
        $("button#aucun").on("click", function () {
            $("input[type=checkbox]").prop("checked", false);
        });
        $("input[type=submit]").on("click", function (event) {
            console.log("submit");
            console.log(event);
            // $('.modal').modal("hide");
        });
    });
</script>