<?php

namespace Application;

use Application\Entity\Db\Role;
use Application\Entity\Db\TypeValidation;
use These\Filter\ActeursFormatter;
use Laminas\Paginator\Paginator as LaminasPaginator;
use RapportActivite\Provider\Privilege\RapportActivitePrivileges;
use UnicaenAuth\Provider\Privilege\Privileges;

/**
 * @var string $title
 * @var LaminasPaginator $paginator
 * @var string $text
 *
 * @var array[] $operationss
 * @var TypeValidation $typeValidation
 * @var string $routeName
 *
 * @var string $returnUrl
 *
 * @var bool $displayEtablissement
 * @var bool $displayType
 * @var bool $displayDoctorant
 * @var bool $displayDirecteurThese
 * @var bool $displayEcoleDoctorale
 * @var bool $displayUniteRecherche
 * @var bool $displayValidation
 * @var bool $displayAvis
 *
 * @see \RapportActivite\Controller\Recherche\RapportActiviteRechercheController::indexAction()
 */

$canDlZip = $this->isAllowed(Privileges::getResourceId(RapportActivitePrivileges::RAPPORT_ACTIVITE_TELECHARGER_ZIP));
$queryParams = $this->queryParams();

$acteursFormatterDirecteurs = new ActeursFormatter();
$acteursFormatterDirecteurs->asSeparated()
    ->paramDisplay(['role' => false, "qualite" => false, "etablissement" => false,])
    ->paramFilter((['role' => Role::CODE_DIRECTEUR_THESE]));
$acteursFormatterCodirecteurs = new ActeursFormatter();
$acteursFormatterCodirecteurs->asSeparated()
    ->paramDisplay(['role' => false, "qualite" => false, "etablissement" => false,])
    ->paramFilter((['role' => Role::CODE_CODIRECTEUR_THESE]));

$this->headTitle($this->translate($title));
?>

<h1 class="page-header"><?php echo $title ?></h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace(); ?>

<!-- Formulaire de filtrage -->
<div class="float-start">
    <?php $loadFiltersUrl = $this->url($routeName . '/recherche/filters', [], ['query' => $this->queryParams()], true); ?>
    <div id="filters" data-url="<?php echo $loadFiltersUrl ?>" style="min-height: 160px">
        <!-- Contenu chargé en AJAX -->
    </div>
</div>
<div class="clearfix"></div>


<?php if (count($paginator) > 0): ?>

    <p>
        <?php
        echo $paginator->getTotalItemCount();
        echo " ";
        echo $this->translate("rapport(s) trouvé(s).");
        ?>
    </p>

    <?php echo $this->partial('rapport-activite/partial/rapports-table', [
        'rapports' => $paginator,
        'routeName' => $routeName,
        'typeValidation' => $typeValidation,
        'operationss' => $operationss,
        'returnUrl' => $returnUrl,

        'displayEtablissement' => $displayEtablissement,
        'displayType' => $displayType,
        'displayDoctorant' => $displayDoctorant,
        'displayDirecteurThese' => $displayDirecteurThese,
        'displayEcoleDoctorale' => $displayEcoleDoctorale,
        'displayUniteRecherche' => $displayUniteRecherche,
        'displayAvis' => $displayAvis,
        'displayValidation' => $displayValidation,
    ]) ?>

    <?php echo $this->paginationControl($paginator, 'sliding', 'application/paginator.phtml', ['route' => $routeName . '/recherche/index']) ?>

    <?php if ($canDlZip): ?>
        <?php $queryParams['redirect'] = $this->url($routeName . '/recherche/index', [], ['query' => $queryParams], true); ?>
        <a class="btn btn-secondary" href="<?php echo $this->url($routeName . '/recherche/telecharger-zip', [], ['query' => $queryParams]) ?>"
           title="Télécharger tous ces rapports sous la forme d'une archive compressée (.zip)">
            <span class="icon icon-export"></span>
            <?php echo $this->translate("Télécharger les rapports"); ?>
        </a>
    <?php endif ?>

<?php else: ?>

    <p>Aucun rapport trouvé.</p>

<?php endif ?>


<script>
    $(function() {
        $("#filters").addClass("loading").refresh(null, function() { $(this).removeClass("loading"); });
    });
</script>