<?php

use Depot\Controller\Plugin\UrlFichierHDR;
use Depot\Controller\Plugin\UrlFichierThese;
use Fichier\Entity\Db\NatureFichier;
use HDR\Entity\Db\HDR;
use These\Entity\Db\These;
use Soutenance\Entity\Intervention;
use Soutenance\Entity\Membre;
use Soutenance\Entity\Proposition;
use Soutenance\Provider\Privilege\InterventionPrivileges;

/**
 * @see \Soutenance\Controller\InterventionController::afficherAction()
 * @var These|HDR $object
 * @var Intervention $distanciel
 * @var Intervention[]|null $visios
 * @var Proposition $proposition
 * @var Membre[] $membres
 * @var array $justificatifs
 * @var string $FORMULAIRE_DELEGUATION
 * @var UrlFichierThese|UrlFichierHDR $urlFichier
 * @var string $typeProposition
 */

if($typeProposition === Proposition::ROUTE_PARAM_PROPOSITION_THESE){
    $this->headTitle("Intervention sur la soutenance de thèse de " . $object->getApprenant()->getIndividu()->getNomComplet());
}else{
    $this->headTitle("Intervention sur la soutenance de HDR de " . $object->getApprenant()->getIndividu()->getNomComplet());
}

$libelleEntite = $typeProposition === Proposition::ROUTE_PARAM_PROPOSITION_THESE ? "thèse" : "HDR";

function getJustificatif(array $justificatifs, string $type, Membre $membre) {
    foreach ($justificatifs as $justificatif) {
        if ($justificatif['type'] === $type AND $justificatif['membre'] === $membre) return $justificatif['justificatif'];
    }
    return null;
}


$canAfficher = $this->isAllowed($object, InterventionPrivileges::INTERVENTION_AFFICHER);
$canModifier = $this->isAllowed($object, InterventionPrivileges::INTERVENTION_MODIFIER);

//var_dump([
//    'canAfficher' => $canAfficher,
//    'canModifier' => $canModifier,
//]);
?>

<h1 class="page-header">
    Intervention sur la soutenance de <?= $libelleEntite ?> de <?php echo  $object->getApprenant()->getIndividu()->getNomComplet(); ?>
</h1>

<?php if (!$canAfficher) : ?>
    <div class="alert alert-danger">
        <p class="lead">
            Vous n'êtes pas habilité&middot;e à afficher la liste des interventions sur la soutenance de la <?= $libelleEntite ?> de <?php echo $object->getApprenant()->getIndividu()->getNomComplet(); ?>
        </p>
    </div>
<?php else : ?>

    <?php /** LIEN VERS LE FORMULAIRE DOC **************************************************************/ ?>
    <div class="alert alert-info">
        <span class="icon icon-info"></span>
        Vous pouvez télécharger les formulaires de délégation grâce au lien suivant :
        <strong><u>
                <a href="<?php echo $FORMULAIRE_DELEGUATION; ?>">
                    formulaire de demande de délégation
                </a>
            </u></strong>.
    </div>

    <?php
    $classe_distanciel = 'bg-warning';
    if ($distanciel !== null) {
        $classe_distanciel = 'bg-success';
        foreach ($proposition->getMembres() as $membre) {
            if (getJustificatif($justificatifs, NatureFichier::CODE_DELEGUATION_SIGNATURE, $membre) === null) {
                $classe_distanciel = 'bg-danger';
                break;
            }
        }
    }
    ?>
    <div class="box card">
        <div class="card-header <?php echo $classe_distanciel; ?>">
            <h2>Déclaration du président du jury en distanciel</h2>
        </div>
        <div class="card-body">

            <?php if ($distanciel !== null) : ?>
                <?php /** IL EXISTE UNE DECLARATATION DE DISTANCIEL POUR LE PRESIDENT  *****************************/ ?>

                <?php /** DECLARATION ******************************************************************/ ?>
                <div class="row">
                    <div class="col-md-8">
                        Déclaration que le président du jury sera en distanciel
                        faite le <?php echo $distanciel->getHistoCreation()->format('d/m/Y'); ?>
                        par <?php echo $distanciel->getHistoCreateur()->getDisplayName(); ?>.
                    </div>
                    <?php if ($canModifier) : ?>
                        <div class="float-end" style="margin-right: 1rem; margin-top:10px">
                            <a      <?php /** @see \Soutenance\Controller\InterventionController::togglePresidentDistancielAction() */?>
                                    href="<?php echo $this->url("soutenance_{$typeProposition}/intervention/toggle-president-distanciel", ['id' => $object->getId()], [], true); ?>" class="btn btn-primary action">
                                <span class="icon icon-minus"></span> Président en distanciel
                            </a>
                        </div>
                    <?php endif; ?>
                </div>

                <br/>

                <?php /** LISTE DES JUSTIFICATIFS ******************************************************************/ ?>
                <div>
                    Liste des délégations de signatures :
                    <?php foreach ($proposition->getMembres() as $membre) : ?>
                        <?php $justificatif = getJustificatif($justificatifs, NatureFichier::CODE_DELEGUATION_SIGNATURE, $membre); ?>
                            <?php if ($justificatif !== null) :
                                /** @see \Soutenance\Controller\JustificatifController::retirerAction() */
                                $urlSuppressionJustificatif = $this->url("soutenance_{$typeProposition}/justificatif/retirer", ['id' => $object->getId(), "justificatif" => $justificatif->getId()], ["query" => ["retour" => $this->url("soutenance_{$typeProposition}/intervention/afficher", ['id' => $object->getId(),], [], true)]], true); ?>
                                <?php echo $this->justificatif()->render($justificatif, $urlFichier, $urlSuppressionJustificatif, $canModifier, ['court' => true]); ?>
                            <?php else : ?>
                                <span class="text text-danger">Délégation de signature manquante pour <strong style="font-variant:small-caps;"><?php echo $membre->getDenomination(); ?></strong></span>
                                <?php if ($canModifier) : ?>
                                    <a      <?php /** @see \Soutenance\Controller\JustificatifController::ajouterAction() */?>
                                            href="<?php echo $this->url("soutenance_{$typeProposition}/justificatif/ajouter", ['id' => $object->getId(), "proposition" => $proposition->getId(), "nature" => NatureFichier::CODE_DELEGUATION_SIGNATURE, "membre" => $membre->getId()], [], true); ?>"
                                            class="btn btn-sm btn-primary ajax-modal" data-event='modification' style="margin: 1px;">
                                    <span class="icon icon-upload"></span> Déposer le justificatif </a>
                                <?php endif; ?>
                            <?php endif; ?>
                    <?php endforeach; ?>
                </div>


            <?php else: ?>

                <?php /** AUCUNE DECLARATATION DE DISTANCIEL POUR LE PRESIDENT  ************************************/ ?>
                <div class="row">
                    <div class="col-md-8">
                        <p class="lead">
                            Vous pouvez déclarer ici que le président du jury examinera la soutenance en distanciel.
                        </p>
                    </div>
                    <?php if ($canModifier) : ?>
                    <div class="float-end" style="margin-right: 1rem; margin-top:10px;">
                        <a      <?php /** @see \Soutenance\Controller\InterventionController::togglePresidentDistancielAction() */?>
                                href="<?php echo $this->url("soutenance_{$typeProposition}/intervention/toggle-president-distanciel", ['id' => $object->getId()], [], true); ?>" class="btn btn-primary action">
                            <span class="icon icon-ajouter"></span> Président en distanciel
                        </a>
                    </div>
                    <?php endif; ?>
                </div>

                <div class="alert alert-warning">
                    <span class="fas fa-exclamation-triangle"></span> Si le Président du jury est en distanciel tous les membres du jury devront remplir une délégation de signature.
                </div>
            <?php endif; ?>
        </div>
    </div>

    <br/>

    <div class="box card">
        <div class="card-header bg-dark text-white">
            <h2>Déclaration tardive de membre en visioconférence</h2>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-8">
                    <?php if ($visios === null or empty($visios)) : ?>
                        Aucune déclaration de visio-conférence tardive
                    <?php else : ?>
                        Liste des déclarations tardives d'un membre en visio-conférence :
                        <ul>
                        <?php foreach ($visios as $visio) : ?>
                            <li>
                                <?php echo $membres[$visio->getComplement()]->getDenomination(); ?>
                                <?php
                                    $justificatif = null;
                                    foreach ($justificatifs as $justificatif_) {
                                        if ($justificatif_['type'] === NatureFichier::CODE_DELEGUATION_SIGNATURE AND $justificatif_['membre'] === $membres[$visio->getComplement()]) {
                                            $justificatif = $justificatif_;
                                            break;
                                        }
                                    }
                                ?>

                                <?php if ($justificatif !== null) :
                                    /** @see \Soutenance\Controller\InterventionController::supprimerVisioconferenceTardiveAction() */
                                    $urlSuppressionJustificatif = $this->url("soutenance_{$typeProposition}/intervention/supprimer-visioconference-tardive", ['id' => $object->getId(), 'intervention' => $visio->getId()], [], true); ?>
                                    <?php echo $this->justificatif()->render($justificatif['justificatif'], $urlFichier, $urlSuppressionJustificatif, $canModifier, ['court' => true]); ?>
                                <?php else : ?>
                                    (<span class="text-danger">justificatif manquant</span>)
                                <?php endif; ?>
                            </li>
                        <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                </div>
                <div class="col-md-1"></div>
                <div class="col-md-3">
                    <?php if ($canModifier) : ?>
                        <?php /** @see \Soutenance\Controller\InterventionController::ajouterVisioconferenceTardiveAction() */ ?>
                        <a href="<?php echo $this->url("soutenance_{$typeProposition}/intervention/ajouter-visioconference-tardive", ['id' => $object->getId()],[], true); ?>" class="btn btn-primary action ajax-modal" data-event="modification">
                            <span class="icon icon-ajouter"></span>
                            Ajout d'une déclaration
                        </a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>