<?php

/**
 * @see \Soutenance\Controller\InterventionController::ajouterVisioconferenceTardiveAction()
 * @var These $these
 * @var Membre[] $membres
 */

use Application\Entity\Db\These;
use Soutenance\Entity\Membre;

?>

<form method="post" action="<?php echo $this->url('soutenance/intervention/ajouter-visioconference-tardive', ['these' => $these->getId()], [], true); ?>">
    <label for="membre">Membre du jury en visioconférence : </label>
    <select id="membre" name="membre" class="selectpicker" data-live-search="true">
        <option>Sélectionner un membre du jury ... </option>
        <?php foreach ($membres as $membre) : ?>
            <option value="<?php echo $membre->getId(); ?>">
                <?php echo $membre->getDenomination(); ?>
            </option>
        <?php endforeach; ?>
    </select>

    <br/>

    <label for="justificatif">Justificatif signé de délégation de signature : </label>
    <input type="file" id="justificatif" name="justificatif">

    <input type="submit" class="btn btn-primary" value="Finaliser la déclaration">

</form>

<script>
    $('select').selectpicker();
</script>