<?php

use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var string      $text
 * @var \UnicaenPrivilege\Entity\Db\PrivilegeCategorie[] $categoriesPrivilegesForFilter
 */

/**
 * @param string $paramName
 * @param string $paramValue
 * @param array  $queryParams
 * @return string
 */
$urlFiltrer = function ($paramName, $paramValue, $queryParams) {
    $queryParams[$paramName] = $paramValue;

    return $this->url('profil', [], ['query' => $queryParams], true);
};

$values = [
    ['value' => '', 'label' => $this->translate("(Peu importe)")],
];
foreach ($categoriesPrivilegesForFilter as $categorie) {
    $values[$categorie->getCode()] = [
        'value' => $categorie->getCode(),
        'label' => $this->translate($categorie->getLibelle()),
    ];
}

echo $this->filterPanel([
    $this->translate("Catégorie") => [
        'paramName'   => 'categorie',
        'paramConfig' => $values,
        'filterUrl'   => $urlFiltrer,
        'titre'       => "Filtrage en fonction de la catégorie du privilège",
    ],
]);
