<?php

/** @var Fichier[] $fichiers */

use Application\Entity\Db\Fichier;
use Application\Provider\Privilege\FichierPrivileges;

$this->headTitle("Fichiers associés aux pages d'information");

$canFichier = $this->isAllowed(FichierPrivileges::getResourceId(FichierPrivileges::FICHIER_DIVERS_TELEVERSER));
?>

<style>
    .form-control {
        height: auto;
    }
</style>

<h1 class="page-header">
    Fichiers associés aux pages d'information
</h1>


<?php if ($canFichier) : ?>
    <h2> Téléversement d'un fichier </h2>

    <?php echo $this->form($form); ?>
<?php endif; ?>

<h2> Listing des fichiers téléversés pour le module informations </h2>

<?php if ($fichiers) : ?>
    <?php echo count($fichiers); ?> fichiers déposés.
<?php endif; ?>


<table class="table table-condensed">
    <thead>
        <tr>
            <th> Fichier </th>
            <th> Déposé par </th>
            <th> Déposé le  </th>
            <th> Action </th>
        </tr>
    </thead>
    <tbody>
    <?php if ($fichiers) : ?>
        <?php foreach ($fichiers as $fichier): ?>
            <tr>
                <td>
                    <a href="<?php
                            echo $this->url('informations/fichiers/telecharger', ['id' => $fichier->getId()], [], true);  ?>">
                        <?php echo $fichier->getNomOriginal(); ?>
                    </a>
                </td>
                <td>
                    <?php echo $fichier->getHistoCreateur()->getDisplayName(); ?>
                </td>
                <td>
                    <?php echo $fichier->getHistoCreation()->format("d/m/Y à H:i"); ?>
                </td>
                <td>
                    <?php if ($canFichier) : ?>
                        <a href="<?php echo $this->url("informations/fichiers/supprimer", ['id' => $fichier->getId()], [], true); ?>">
                            <span class="glyphicon glyphicon-remove"></span>
                        </a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php endif; ?>
    </tbody>
</table>