<?php

use Application\Controller\UtilisateurController;
use Zend\Form\Form;
use Application\View\Renderer\PhpRenderer;

/**
 * @var Form $form
 * @var PhpRenderer $this
 *
 * @see UtilisateurController::ajouterAction()
 */
?>

<?php $this->headTitle($this->translate("Création d'utilisateur")) ?>

<h1 class="page-header"><?php echo $this->translate("Création d'utilisateur"); ?> </h1>

<p class="lead">
    Cette page permet de créer un utilisateur <em>manuellement</em>.
    Un individu sera également créé à l'aide des informations fournies dans ce formulaire.
</p>
<p class="lead">
    <strong>Remarque :</strong> l'adresse électronique saisie sera l'identifiant de connexion de l'utilisateur,
    elle doit donc être unique.
</p>

<?php
$form->prepare();
echo $this->form($form);
