<?php

use Application\Entity\Db\Individu;
use Application\Entity\Db\Role;
use Application\View\Helper\RoleHelper;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var string $type
 * @var Role $role
 * @var Individu $individu
 */

$appName = $this->appInfos()->nom;
$vh = new RoleHelper();
?>

<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application <?php echo $appName ?>.
</p>

<?php if ($type === "ajout"): ?>
    <p>
        Vous venez de recevoir le rôle <?php echo $vh->render($role); ?> dans l'application <?php echo $appName ?>.
    </p>
<?php endif; ?>

<?php if ($type === "retrait"): ?>
    <p>
        Vous venez de perdre le rôle <?php echo $vh->render($role); ?> dans l'application <?php echo $appName ?>.
    </p>
<?php endif; ?>