<?php

use Application\View\Renderer\PhpRenderer;
use UnicaenApp\Form\Element\SearchAndSelect;
use Application\Entity\Db\Individu;
use Application\Entity\Db\Role;
use Application\Entity\Db\UniteRecherche;
use Application\Entity\Db\EcoleDoctorale;
use Application\Entity\Db\Etablissement;
use Application\Entity\Db\TypeStructure;

/**
 * @var PhpRenderer $this
 * @var Etablissement[] etablissements
 * @var EcoleDoctorale[] ecoles
 * @var UniteRecherche[] unites
 */

?>


<?php $this->headTitle($this->translate("Utilisateurs")) ?>

<h1 class="page-header"><?php echo $this->translate("Utilisateurs"); ?>
</h1>

<form method='post' class="form-inline " style="margin-bottom:10px;">
    <?php
        $sas = new SearchAndSelect('individu');
        $sas->setAttribute('placeholder','Recherchez un utilisateur');
        $sas->setAttribute('class', 'individu-finder');
        $sas->setAutocompleteSource($this->url('utilisateur/rechercher-individu', [], [], true));
        echo $this->formControlGroup($sas, 'formSearchAndSelect');
    ?>
    <input type="submit" class="" value="Sélection l'utilisateur"/>
</form>

<!--<a href="--><?php //echo $this->url('creation-utilisateur', [], [], true); ?><!--">-->
<!--    <button class="btn btn-primary">-->
<!--        <span class="glyphicon glyphicon-plus"></span> Ajouter un nouvel utilisateur-->
<!--    </button>-->
<!--</a>-->

<?php if ($individu) { ?>
    <div class="box panel panel-info">

        <div class="panel-heading">
            <h2 class="first">
                <?php echo $this->translate("Fiche"); ?>
            </h2>
        </div>

        <div class="panel-body">
            <dl>
                <dt>État civil</dt>
                <dd>
                    <?php
                    /** @var Individu $individu */
                    echo $individu->getNomComplet(false, true, true);
                    echo "<br/>";
                    echo $individu->getDateNaissanceToString();
                    echo "<br/>";
                    echo $individu->getNationalite();
                    ?>
                </dd>
                <dt>Dernière modification</dt>
                <dd>
                    <?php
                    echo $individu->getHistoModification()->format("H:i:s d/m/y");
                    echo "<br/>";
                    ?>
                </dd>
            </dl>
        </div>
    </div>

    <div class="box panel panel-info">

        <div class="panel-heading">
            <h2 class="first">
                <?php echo $this->translate("Rôles"); ?>
            </h2>
        </div>

        <div class="panel-body">

            <div class="col-md-4">
                <dl>
                    <dt>
                        Rôles affectés
                    </dt>
                    <dd>
                        <?php
                        /** @var Role $role */
                        echo generateRoleAffecte($individu, $roles, $rolesAffectes);
                        ?>
                    </dd>
                </dl>
            </div>

            <div class="col-md-8">

                <dl>
                    <?php
                    echo generateRoleStatique($individu, $roles, $rolesAffectes);
                    echo generateRoleEtablissement($individu, $roles, $rolesAffectes, $etablissements);
                    echo generateRoleEcole($individu, $roles, $rolesAffectes, $ecoles);
                    echo generateRoleUnite($individu, $roles, $rolesAffectes, $unites);
                    ?>
                </dl>

            </div>
        </div>
    </div>


<?php } ?>


<?php
/**
 * @param Etablissement[]|UniteRecherche[]|EcoleDoctorale[] $structures
 * @param string $id
 * @param Role[] $roles
 * @return string
 */
function generateSelect($structures, $id, $roles = null)
{
    $texte = '<div class="form-group">';
    $texte .= '<select class="form-control" id="' . $id . '">';
    $texte .= '<option value=""></option>';

    $structuresValides = [];
    if ($roles === null) {
        $structuresValides = $structures;
    } else {
        foreach ($structures as $structure) {
            foreach ($roles as $role) {
                if ($role->getStructure() !== null && $role->getStructure()->getId() === $structure->getStructure()->getId()) {
                    $structuresValides[] = $structure;
                    break;
                }
            }
        }
    }
    foreach ($structuresValides as $structure) {
        $texte .= '<option value="' . $structure->getStructure()->getId() . '">' . $structure->getStructure()->getLibelle() . '</option>';
    }
    $texte .= "</select>";
    $texte .= "</div>";
    return $texte;
}


/**
 * @param Individu $individu
 * @param Role[] $roles
 * @param Role[] $rolesAffectes
 * @return string
 */
function generateRoleAffecte($individu, $roles, $rolesAffectes)
{
    $texte = "";
    foreach ($roles as $role) {
        $texte .= '<div id="affecte_' . $role->getId() . '"';
        if (array_search($role, $rolesAffectes) === false) $texte .= ' style="display:none;" ';
        $texte .= '>';
        $texte .= '<span class="remove-role glyphicon glyphicon-remove text-danger" id="' . $individu->getId() . '_' . $role->getId() . '"></span>';
        $texte .= $role->getRoleId();
        $texte .= '</div>';
    }
    return $texte;
}

/**
 * @param Individu $individu
 * @param Role[] $roles
 * @param Role[] $rolesAffectes
 * @return string
 */
function generateRoleStatique($individu, $roles, $rolesAffectes)
{
    $texte = "";
    $texte .= "<dt> Rôles Statiques </dt>";
    $texte .= "<dd>";
    foreach ($roles as $role) {
        if ($role->getTypeStructureDependant() === null && $role->isTheseDependant() === false) {
            $texte .= '<div id="disponible_' . $role->getId() . '"';
            if (array_search($role, $rolesAffectes) !== false) $texte .= ' style="display:none;" ';
            $texte .= '>';
            $texte .= '<span class="add-role glyphicon glyphicon-plus text-success" id="' . $individu->getId() . '_' . $role->getId() . '"></span>';
            $texte .= $role->getRoleId();
            $texte .= '</div>';
        }
    }
    $texte .= "</dd>";
    return $texte;
}

/**
 * @param Individu $individu
 * @param Role[] $roles
 * @param Role[] $rolesAffectes
 * @param Etablissement[] $etablissements
 * @return string
 */
function generateRoleEtablissement($individu, $roles, $rolesAffectes, $etablissements)
{
    $texte = "";
    $texte .= "<dt> Rôles liés aux établissements </dt>";
    $texte .= "<dd>";
    $texte .= generateSelect($etablissements, "etablissements", $roles);
    foreach ($etablissements as $structureConcrete) {
        $structureId = $structureConcrete->getStructure()->getId();
        $rolesFiltres = array_filter($roles, function ($role) use ($structureId) {
            return $role->getStructure() !== null && $role->getStructure()->getId() === $structureId;
        });

        if (!empty($rolesFiltres)) {
            $texte .= '<div id="etablissement_' . $structureId . '" style="display:none;">';
            foreach ($rolesFiltres as $role) {
                $texte .= '<div id="disponible_' . $role->getId() . '"';
                if (array_search($role, $rolesAffectes) !== false) $texte .= ' style="display:none;" ';
                $texte .= '>';
                $texte .= '<span class="add-role glyphicon glyphicon-plus text-success" id="' . $individu->getId() . '_' . $role->getId() . '"></span>';
                $texte .= $role->getRoleId();
                $texte .= '</div>';
            }
            $texte .= '</div>';
        }
    }
    $texte .= "</dd>";
    return $texte;
}

/**
 * @param Individu $individu
 * @param Role[] $roles
 * @param Role[] $rolesAffectes
 * @param EcoleDoctorale[] $ecoles
 * @return string
 */
function generateRoleEcole($individu, $roles, $rolesAffectes, $ecoles)
{
    $texte = "";
    $texte .= "<dt> Rôles liés aux écoles doctorales </dt>";
    $texte .= "<dd>";
    $texte .= generateSelect($ecoles, "ecoles");
    foreach ($ecoles as $structureConcrete) {
        $structureId = $structureConcrete->getStructure()->getId();
        $rolesFiltres = array_filter($roles, function ($role) use ($structureId) {
            return $role->getStructure() !== null && $role->getStructure()->getId() === $structureId;
        });

        if (!empty($rolesFiltres)) {
            $texte .= '<div id="ecole_' . $structureId . '" style="display:none;">';
            foreach ($rolesFiltres as $role) {
                $texte .= '<div id="disponible_' . $role->getId() . '"';
                if (array_search($role, $rolesAffectes) !== false) $texte .= ' style="display:none;" ';
                $texte .= '>';
                $texte .= '<span class="add-role glyphicon glyphicon-plus text-success" id="' . $individu->getId() . '_' . $role->getId() . '"></span>';
                $texte .= $role->getRoleId();
                $texte .= '</div>';
            }
            $texte .= '</div>';
        }
    }
    $texte .= "</dd>";
    return $texte;
}

/**
 * @param Individu $individu
 * @param Role[] $roles
 * @param Role[] $rolesAffectes
 * @param UniteRecherche[] $unites
 * @return string
 */
function generateRoleUnite($individu, $roles, $rolesAffectes, $unites)
{
    $texte = "";
    $texte .= "<dt> Rôles liés aux unités de recherche </dt>";
    $texte .= "<dd>";
    $texte .= generateSelect($unites, "unites");
    foreach ($unites as $structureConcrete) {
        $structureId = $structureConcrete->getStructure()->getId();
        $rolesFiltres = array_filter($roles, function ($role) use ($structureId) {
            return $role->getStructure() !== null && $role->getStructure()->getId() === $structureId;
        });

        if (!empty($rolesFiltres)) {
            $texte .= '<div id="unite_' . $structureId . '" style="display:none;">';
            foreach ($rolesFiltres as $role) {
                $texte .= '<div id="disponible_' . $role->getId() . '"';
                if (array_search($role, $rolesAffectes) !== false) $texte .= ' style="display:none;" ';
                $texte .= '>';
                $texte .= '<span class="add-role glyphicon glyphicon-plus text-success" id="' . $individu->getId() . '_' . $role->getId() . '"></span>';
                $texte .= $role->getRoleId();
                $texte .= '</div>';
            }
            $texte .= '</div>';
        }
    }
    $texte .= "</dd>";
    return $texte;
}

?>


<script>
    $(document).ready(function () {
        $(".remove-role").click(function () {
            var id = $(this).attr("id");
            var splits = id.split("_");
            var role = splits[1];
            var individu = splits[0];

            var url = "retirer-role/" + individu + "/" + role;
            $("#affecte_" + role).hide();
            $("#disponible_" + role).show();

            $.ajax({
                url: url
            });
        });
    });
    $(document).ready(function () {
        $(".add-role").click(function () {
            var id = $(this).attr("id");
            var splits = id.split("_");
            var role = splits[1];
            var individu = splits[0];

            var url = "ajouter-role/" + individu + "/" + role;
            $("#affecte_" + role).show();
            $("#disponible_" + role).hide();

            $.ajax({
                url: url
            });
        });
    });
    $(document).ready(function () {
        $("#etablissements").change(function () {
            $("div[id^=etablissement]").hide();
            var val = $("#etablissements").val();
            $("#etablissement_" + val).show();
        });
    });
    $(document).ready(function () {
        $("#ecoles").change(function () {
            $("div[id^=etablissement]").hide();
            var val = $("#ecoles").val();
            $("#ecole_" + val).show();
        });
    });
    $(document).ready(function () {
        $("#unites").change(function () {
            $("div[id^=etablissement]").hide();
            var val = $("#unites").val();
            $("#unite_" + val).show();
        });
    });
</script>
<style>
    .remove-role:hover {
        cursor: pointer;
    }

    .add-role:hover {
        cursor: pointer;
    }

    select {
        margin-top: 5px;
    }

    span {
        margin: 5px 5px 5px 5px;
    }


</style>
