<?php

use Application\View\Renderer\PhpRenderer;
use UnicaenApp\Form\Element\SearchAndSelect;
use Application\Entity\Db\Individu;
use Application\Entity\Db\Role;

/**
 * PhpRenderer $this
 */

?>


<?php $this->headTitle($this->translate("Utilisateurs")) ?>

<h1 class="page-header"><?php echo $this->translate("Utilisateurs"); ?>
<!--    <span class="badge">--><?php //echo $utilisateurs->getTotalItemCount() ?><!--</span>-->
</h1>

<p>
<?php
    echo "<form method='post'>";
    $sas = new SearchAndSelect('individu');
    $sas->setLabel($this->translate("Recherche d'un individu à ajouter :"));
    $sas->setAttribute('class', 'individu-finder');
    $sas->setAutocompleteSource($this->url('utilisateur/rechercher-individu',[],[],true));
    echo $this->formControlGroup($sas, 'formSearchAndSelect');
    echo "<input type='submit' value='Selectionner'/>";
    echo "</form>";
?>
</p>

<?php if ($individu) { ?>
<div class="box panel panel-info">

    <div class="panel-heading">
        <h2 class="first">
            <?php echo $this->translate("Fiche"); ?>
        </h2>
    </div>

    <div class="panel-body">
        <dl>
            <dt>État civil</dt>
            <dd>
                <?php
                    /** @var Individu $individu */
                    echo $individu->getNomComplet(false, true, true);
                    echo "<br/>";
                    echo $individu->getDateNaissanceToString();
                    echo "<br/>";
                    echo $individu->getNationalite();
                ?>
            </dd>
            <dt>Dernière modification</dt>
            <dd>
                <?php
                    echo $individu->getHistoModification()->format("H:i:s d/m/y");
                    echo "<br/>";
                ?>
            </dd>
        </dl>
    </div>
</div>

<div class="box panel panel-info">

    <div class="panel-heading">
        <h2 class="first">
            <?php echo $this->translate("Rôles"); ?>
        </h2>
    </div>

    <div class="panel-body">
        <dl>
            <dt>Rôles affectés (<?php echo count($roles); ?>)</dt>
            <dd>
                <?php
                    /** @var Role $role */
                foreach($roles as $role) {
                        echo '<span class="remove-role glyphicon glyphicon-remove text-danger" id="'.$individu->getId().'_'.$role->getId().'"></span>';
                        echo '&nbsp;';
                        echo $role->getRoleId();
                        echo "<br/>";
                    }
                ?>
            </dd>
        </dl>
    </div>
</div>



<?php } ?>

<script>
    $(document).ready(function() {
        $(".remove-role").click( function() {
            var id = $(this).attr("id");
            var splits = id.split("_");
            var role = splits[1];
            var individu = splits[0];

            var url = "retirer-role/" + individu + "/" + role;

            $.ajax({
                url : url,
                // beforeSend:
                //     function () {
                //         document.getElementById(id).innerHTML = "<img style='height:40px;' src='css/loading.gif'/>";
                //     },
                // success:
                // function(retour){
                //     var texte = "";
                //     if (retour == 1) texte = "<span class='glyphicon glyphicon-ok text-success'></span>";
                //     else var texte = "<span class='glyphicon glyphicon-remove text-danger'></span>";
                //     document.getElementById(id).innerHTML = texte;
                // }
            });

            alert("clicked on u:" + individu + " r:" + role + "!");

        });
        $("td").click(function() {

            var canModifier =  Boolean(<?php echo $canModifier; ?>);
            if (!canModifier) {
                alert("Vous n'êtes pas autorisé à modifier les privilèges associés à un rôle.");
                return;
            }

            var id = $(this).attr("id");
            var splits = id.split("_");
            var role = splits[1];
            var privilege = splits[0];
            var url = "modifier-privilege/" + role + "/" + privilege;

            $.ajax({
                url : url,
                beforeSend:
                    function () {
                        document.getElementById(id).innerHTML = "<img style='height:40px;' src='css/loading.gif'/>";
                    },
                success:
                    function(retour){
                        var texte = "";
                        if (retour == 1) texte = "<span class='glyphicon glyphicon-ok text-success'></span>";
                        else var texte = "<span class='glyphicon glyphicon-remove text-danger'></span>";
                        document.getElementById(id).innerHTML = texte;
                    }
            });


        });
    });
</script>
<style>
    .remove-role:hover {
        cursor: pointer;
    }
</style>
