<?php

/**
 * @see \Application\Controller\UtilisateurController::lierIndividuAction();
 * @var Utilisateur $utilisateur
 */

use UnicaenApp\Util;
use Application\Entity\Db\Utilisateur;
use UnicaenApp\Form\Element\SearchAndSelect;

?>

<div class="box panel panel-info">
    <div class="panel-heading">
        <h2 class="first">
            <?php echo $this->translate("Utilisateur") ?>
        </h2>
    </div>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>Id</dt>
            <dd><?php echo $utilisateur->getId() ?></dd>
            <dt>Username</dt>
            <dd><code><?php echo $utilisateur->getUsername() ?></code></dd>
            <dt>Email</dt>
            <dd><?php echo $utilisateur->getEmail() ?></dd>
            <dt>Display name</dt>
            <dd><?php echo $utilisateur->getDisplayName() ?></dd>
            <dt>Password</dt>
            <dd><?php echo Util::truncatedString($utilisateur->getPassword(), 10) ?></dd>
            <?php if ($token = $utilisateur->getPasswordResetToken()): ?>
                <dt>Password reset token</dt>
                <dd><?php echo Util::truncatedString($token, 8) ?></dd>
            <?php endif ?>
        </dl>
    </div>
</div>

<form method="post" action="<?php echo $this->url('utilisateur/lier-individu', ['utilisateur' => $utilisateur->getId()], [], true); ?>">
    <?php
    $sas = new SearchAndSelect('individu');
    $sas->setLabel($this->translate("Recherche d'un individu"));
    $sas->setAttribute('class', 'individu-finder');
    $sas->setAutocompleteSource($this->url('utilisateur/rechercher-individu', [], [], true));
    echo $this->formControlGroup($sas, 'formSearchAndSelect');
    ?>

    <input type="submit" class="btn btn-primary action" value="Lier l'individu à l'utilisateur">
</form>
