<?php

/**
 * @see \Application\Controller\UtilisateurController::lierIndividuAction();
 * @var Utilisateur $utilisateur
 * @var Individu $individu
 * @var ActeurThese[] $acteurs
 * @var Role[] $roles
 */

use Acteur\Entity\Db\ActeurThese;
use Individu\Entity\Db\Individu;
use Application\Entity\Db\Role;
use UnicaenApp\Util;
use Application\Entity\Db\Utilisateur;
use UnicaenApp\Form\Element\SearchAndSelect;
?>

<?php if (isset($individu) and $utilisateur !== null and $utilisateur->getIndividu() === $individu) : ?>

    <div class="alert alert-success">
        Le compte utilisateur &laquo; <?php echo $utilisateur->getDisplayName(); ?> &raquo;
        a été lié à l'individu &laquo; <?php echo $individu->getNomComplet(); ?> &raquo;.
    </div>

<?php else : ?>

    <div class="box card">
        <div class="card-header bg-dark text-white">
            <h2 class="first">
                <?php echo $this->translate("Compte utilisateur") ?>
            </h2>
        </div>
        <div class="card-body">
            <dl class="row">
                <dt class="col-md-5">Identifiant de connexion (username)</dt>
                <dd class="col-md-5"><code><?php echo $utilisateur->getUsername() ?></code></dd>
                <dt class="col-md-5">Adresse électronique</dt>
                <dd class="col-md-5"><?php echo $utilisateur->getEmail() ?></dd>
                <dt class="col-md-5">Nom d'affichage</dt>
                <dd class="col-md-5"><?php echo $utilisateur->getDisplayName() ?></dd>
                <dt class="col-md-5">Mot de passe</dt>
                <dd class="col-md-5"><?php echo Util::truncatedString($utilisateur->getPassword(), 10) ?></dd>
                <dt class="col-md-5">Id</dt>
                <dd class="col-md-5"><?php echo $utilisateur->getId() ?></dd>
                <?php if ($token = $utilisateur->getPasswordResetToken()): ?>
                    <dt class="col-md-5">Jeton de changement de mot de passe</dt>
                    <dd class="col-md-5"><?php echo Util::truncatedString($token, 8) ?></dd>
                <?php endif ?>
            </dl>
        </div>
    </div>

    <?php if (isset($individu))  : ?>
        <div class="box card">
            <div class="card-header bg-dark text-white">
                <h2 class="first">
                    <?php echo $this->translate("Individu") ?>
                </h2>
            </div>
            <div class="card-body">
                <dl class="row">
                    <dt class="col-md-5">Nom complet</dt>
                    <dd class="col-md-5"><?php echo $individu->getNomComplet() ?></dd>
                    <dt class="col-md-5">Adresse électronique</dt>
                    <dd class="col-md-5"><?php echo $individu->getEmailPro() ?></dd>
                    <dt class="col-md-5">Id</dt>
                    <dd class="col-md-5"><?php echo $individu->getId() ?></dd>
                </dl>

                <h3> Rôles statiques associés à l'individu </h3>

                <?php if (empty($roles)): ?>

                    <p>Aucun.</p>

                <?php else: ?>

                    <table class="table table-extra-condensed">
                        <thead>
                        <tr>
                            <th> Role</th>
                            <th> Structure</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($roles as $role) : ?>
                            <tr>
                                <td> <?php echo $role->getLibelle(); ?> </td>
                                <td>
                                    <?php if ($role->getStructure()) : ?>
                                        <?php echo $role->getStructure()->getLibelle(); ?>
                                        (<?php echo $role->getStructure()->getSigle(); ?>)
                                    <?php else : ?>
                                        Aucune
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>

                <?php endif ?>

                <h3> Acteurs associés à l'individu </h3>

                <?php if (empty($acteurs)): ?>

                    <p>Aucun.</p>

                <?php else: ?>

                    <table class="table table-extra-condensed">
                        <thead>
                        <tr>
                            <th> These Id</th>
                            <th> Doctorant</th>
                            <th> Role</th>
                            <th> Qualité</th>
                            <th> Établissement</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($acteurs as $acteur) : ?>
                            <tr>
                                <td>
                                    <a href="<?php echo $this->url('these/identite', ['these' => $acteur->getThese()->getId()], [], true); ?>"
                                       title="<?php echo $acteur->getThese()->getDoctorant()->getIndividu()->getNomComplet(); ?> - <?php echo $acteur->getThese()->getTitre(); ?>"
                                    >
                                        <?php echo $acteur->getThese()->getId(); ?>
                                    </a>
                                </td>
                                <td>
                                    <?php echo $acteur->getThese()->getDoctorant()->getIndividu()->getNomComplet(); ?>
                                </td>
                                <td>
                                    <?php echo $acteur->getRole()->getLibelle(); ?>
                                </td>
                                <td>
                                    <?php echo $acteur->getLibelleQualite(); ?>
                                </td>
                                <td>
                                    <?php if ($acteur->getEtablissement() !== null) : ?>
                                        <?php echo $acteur->getEtablissement()->getStructure()->getLibelle(); ?>
                                    <?php else : ?>
                                        Aucun établissement
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>

                <?php endif ?>
            </div>
        </div>

        <a href="<?php echo $this->url('utilisateur/lier-individu', ['utilisateur' => $utilisateur->getId()], [], true); ?>"
           class="btn btn-secondary action">< Retour à la recherche</a>
        <a href="<?php echo $this->url('utilisateur/lier-individu', ['utilisateur' => $utilisateur->getId(), 'individu' => $individu->getId()], [], true); ?>"
           class="btn btn-primary action">Lier l'utilisateur à cet individu</a>
        <a href="<?php echo $this->url('utilisateur/lier-nouvel-individu', ['utilisateur' => $utilisateur->getId()], [], true); ?>"
           class="btn btn-warning float-end action">Créer un nouvel individu</a>

    <?php endif; ?>

    <?php if ($this->ajouterIndividuChildView) : ?>

        <?php echo $this->ajouterIndividuChildView ?>

    <?php elseif (!isset($individu)) : ?>

        <form method="post"
              action="<?php echo $this->url('utilisateur/lier-individu', ['utilisateur' => $utilisateur->getId()], [], true); ?>">
            <?php
            $sas = new SearchAndSelect('individu');
            $sas->setAttribute('id', $sasId = uniqid('sas_'));
            $sas->setLabel($this->translate("Recherche d'un individu"));
            $sas->setAttribute('class', 'individu-finder');
            /** @see IndividuController::rechercherAction() */
            $sas->setAutocompleteSource($this->url('individu/rechercher', [], [], true));
            echo $this->formControlGroup($sas, 'formSearchAndSelect');
            ?>

            <input type="submit" id="examiner-btn" class="btn btn-primary action" value="Examiner l'individu">
        </form>

        <a href="<?php echo $this->url('utilisateur/lier-nouvel-individu', ['utilisateur' => $utilisateur->getId()], [], true); ?>"
           class="btn btn-warning float-end action">Créer un nouvel individu</a>

        <script>
            $(function () {
                // Gestion de l'interdiction du bouton "Examiner l'individu"
                let examBtn = $("#examiner-btn").attr('disabled', true);
                $("#<?php echo $sasId . '-autocomplete' ?>").on("autocompleteselect", function () {
                    examBtn.attr('disabled', false);
                }).on("autocompletesearch", function () {
                    examBtn.attr('disabled', true);
                });
            });
        </script>

    <?php endif; ?>

<?php endif; ?>
