<?php

namespace Application;

use Application\Controller\UtilisateurController;
use Application\Entity\Db\Utilisateur;
use Application\View\Renderer\PhpRenderer;
use Individu\Entity\Db\Individu;
use UnicaenApp\Util;
use UnicaenAuth\View\Helper\UserUsurpationHelper;
use UnicaenAuthToken\Entity\Db\UserToken;

/**
 * @see UtilisateurController::voirAction()
 * @var PhpRenderer $this
 * @var Utilisateur $utilisateur
 * @var Individu $individu
 * @var array $rolesData
 * @var UserToken[] $tokens
 * @var string $redirect
 *
 * @see \Application\Controller\UtilisateurController::voirAction()
 */
?>

<?php $this->headTitle($this->translate("Utilisateur"))->append($utilisateur->getUsername()) ?>

<h1 class="page-header">
    <?php echo $this->translate("Utilisateur") ?> &laquo; <?php echo $utilisateur->getUsername() ?> &raquo;
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace() ?>

<div class="row">

    <div class="col-md-6">

        <div class="box card">
            <div class="card-header bg-dark text-white">
                <h2 class="first">
                    <?php echo $this->translate("Utilisateur") ?>
                    <div class="float-end">
                        <?php
                        // bouton d'usurpation d'identité
                        $userUsurpationHelper = $this->plugin('userUsurpation');
                        /* @var $userUsurpationHelper UserUsurpationHelper */
                        echo $userUsurpationHelper->renderAsButton($utilisateur);
                        ?>
                    </div>
                </h2>
            </div>
            <div class="card-body">
                <dl class="row">
                    <dt class="col-md-5">Identifiant de connexion</dt>
                    <dd class="col-md-5"><code><?php echo $utilisateur->getUsername() ?></code></dd>
                    <?php if ($utilisateur->getNom()): ?>
                        <dt class="col-md-5">Nom d'usage</dt>
                        <dd class="col-md-5"><?php echo $utilisateur->getNom() ?></dd>
                        <dt class="col-md-5">Prénom</dt>
                        <dd class="col-md-5"><?php echo $utilisateur->getPrenom() ?></dd>
                    <?php endif ?>
                    <dt class="col-md-5">Nom d'affichage</dt>
                    <dd class="col-md-5"><?php echo $utilisateur->getDisplayName() ?></dd>
                    <dt class="col-md-5">Adresse électronique</dt>
                    <dd class="col-md-5"><?php echo $utilisateur->getEmail() ?></dd>
                    <dt class="col-md-5">Mot de passe</dt>
                    <dd class="col-md-5"><?php echo Util::truncatedString($utilisateur->getPassword(), 10) ?></dd>
                    <dt class="col-md-5">Id</dt>
                    <dd class="col-md-5"><?php echo $utilisateur->getId() ?></dd>
                    <?php if ($token = $utilisateur->getPasswordResetToken()): ?>
                        <dt class="col-md-5">Password reset token</dt>
                        <dd class="col-md-5"><?php echo Util::truncatedString($token, 8) ?></dd>
                    <?php endif ?>
                </dl>
            </div>
        </div>

    </div>

    <div class="col-md-6">

        <?php if ($individu = $utilisateur->getIndividu()) : ?>

            <div class="box card">
                <div class="card-header <?php echo $individu->estHistorise() ? 'bg-danger' : 'bg-info' ?>">
                    <h2 class="first">
                        <?php echo $this->translate("Individu lié") ?> <?php echo $individu->estHistorise() ? 'SUPPRIMÉ' : '' ?>
                        <div class="float-end">
                            <a href="<?php echo $this->url('utilisateur/delier-individu', ['utilisateur' => $utilisateur->getId()], [], true);?>"
                               class="btn btn-danger"
                               data-toggle="confirmationx">Délier de l'utilisateur</a>
                        </div>
                    </h2>
                </div>
                <div class="card-body">
                    <?php echo $this->partial('individu/individu/partial/dl', ['individu' => $individu]) ?>

                    <a href="<?php echo $this->url('individu/voir', ['individu' => $individu->getId()]) ?>"
                       class="text-center"><i class="icon icon-voir"></i> Voir la fiche détaillée de l'individu</a>
                </div>
            </div>

        <?php else: ?>

            <p>Cet utilisateur n'est associé à aucun individu.</p>
            <a
                <?php /** @see UtilisateurController::lierIndividuAction() */?>
                href="<?php echo $this->url('utilisateur/lier-individu', ['utilisateur' => $utilisateur->getId()], [], true); ?>"
                class="btn btn-primary action ajax-modal"
            >
                <span class="fas fa-link"></span>
                Lier à un individu...
            </a>

        <?php endif ?>

    </div>

</div>

<!-- TOKEN D'AUTHENTIFICATION ----------------------------------------------------------------------------------------->

<div class="box card">
    <div class="card-header bg-dark text-white">
        <h2 class="first">
            <?php echo $this->translate("Jeton d'authentification") ?>
            <div class="float-end">
                <?php echo $this->partial('unicaen-auth-token/token/partial/add-button', [
                    'redirect' => $redirect,
                    'user' => $utilisateur->getId(),
                ]) ?>
            </div>
        </h2>
    </div>
    <div class="card-body">
        <?php if (empty($tokens)): ?>
            L'utilisateur n'a aucun jeton d'authentification.
        <?php else: ?>
            <?php echo $this->partial('unicaen-auth-token/token/partial/table', ['paginator' => $tokens, 'redirect' => $redirect]); ?>
        <?php endif ?>
    </div>
</div>

<?php if ($rolesData) : ?>

    <div class="box card">
        <div class="card-header bg-dark text-white">
            <h2 class="first">
                <?php echo $this->translate("Rôles de l'individu") ?>
            </h2>
        </div>
        <div class="row card-body">
            <?php echo $this->partial('individu/individu/partial/roles', $rolesData) ?>
        </div>
    </div>

<?php endif ?>


<script>
    $(function() {
        $(document).on('hide.bs.modal','.modal', function () {
            // alert('fermeture modal');
            window.parent.location.reload();
        });
    });
</script>
