<?php

namespace Application;

use Application\Controller\PrivilegeController;
use Application\Controller\UtilisateurController;
use Application\Entity\Db\Utilisateur;
use Application\Provider\Privilege\UtilisateurPrivileges;
use Application\View\Renderer\PhpRenderer;
use Individu\Entity\Db\Individu;
use UnicaenApp\Util;
use UnicaenAuthentification\View\Helper\UserUsurpationHelper;
use UnicaenAuthToken\Entity\Db\UserToken;

/**
 * @var PhpRenderer $this
 * @var Utilisateur $utilisateur
 * @var array $rolesData
 * @var UserToken[] $tokens
 * @var string $redirect
 *
 * @see \Application\Controller\UtilisateurController::voirAction()
 */

$individu = $utilisateur->getIndividu();
$canEdit = $this->isAllowed(UtilisateurPrivileges::getResourceId(UtilisateurPrivileges::UTILISATEUR_MODIFICATION));
?>

<?php $this->headTitle($this->translate("Compte utilisateur"))->append($utilisateur->getUsername()) ?>

<h1 class="page-header">
    <?php echo $this->translate("Compte utilisateur") ?> <code><?php echo $utilisateur->getUsername() ?></code>
</h1>

<?php echo $this->alertes()->addAlertesFromFlashMessenger()->renderAsBootstrapToasts() ?>

<div class="row">

    <div class="col-md-6">

        <div class="box card">
            <div class="card-header bg-dark text-white">
                <h2 class="first">
                    <?php echo $this->translate("Compte utilisateur") ?>
                    <div class="float-end">
                        <?php
                        // bouton d'usurpation d'identité
                        $userUsurpationHelper = $this->plugin('userUsurpation');
                        /* @var $userUsurpationHelper UserUsurpationHelper */
                        echo $userUsurpationHelper->renderAsButton($utilisateur);
                        ?>
                    </div>
                </h2>
            </div>
            <div class="card-body">
                <dl class="row">
                    <dt class="col-md-5">Identifiant de connexion</dt>
                    <dd class="col-md-5"><code><?php echo $utilisateur->getUsername() ?></code></dd>
                    <?php if ($utilisateur->getNom()): ?>
                        <dt class="col-md-5">Nom d'usage</dt>
                        <dd class="col-md-5"><?php echo $utilisateur->getNom() ?></dd>
                        <dt class="col-md-5">Prénom</dt>
                        <dd class="col-md-5"><?php echo $utilisateur->getPrenom() ?></dd>
                    <?php endif ?>
                    <dt class="col-md-5">Nom d'affichage</dt>
                    <dd class="col-md-5"><?php echo $utilisateur->getDisplayName() ?></dd>
                    <dt class="col-md-5">Adresse électronique</dt>
                    <dd class="col-md-5"><?php echo $utilisateur->getEmail() ?></dd>
                    <dt class="col-md-5">Mot de passe</dt>
                    <dd class="col-md-5"><?php echo Util::truncatedString($utilisateur->getPassword(), 10) ?></dd>
                    <dt class="col-md-5">Id</dt>
                    <dd class="col-md-5"><?php echo $utilisateur->getId() ?></dd>
                    <?php if ($token = $utilisateur->getPasswordResetToken()): ?>
                        <dt class="col-md-5">Password reset token</dt>
                        <dd class="col-md-5"><?php echo Util::truncatedString($token, 8) ?></dd>
                    <?php endif ?>
                </dl>

                <?php if ($canEdit): ?>
                    <form method="post" action="<?php echo $this->url('unicaen-utilisateur/supprimer', ['utilisateur' => $utilisateur->getId()]) ?>">
                        <input type="hidden" name="utilisateur" value="<?php echo $utilisateur->getId() ?>">
                        <button type="submit" value="<?php echo $this->translate("Supprimer ce compte utilisateur") ?>"
                               onclick="return confirm('Êtes-vous certain·e de vouloir supprimer ce compte utilisateur ?')"
                               class="btn btn-danger float-end">
                            <span class="icon icon-delete"></span>
                            <?php echo $this->translate("Supprimer ce compte utilisateur") ?>
                        </button>
                    </form>
                <?php endif ?>
            </div>
        </div>

    </div>

    <div class="col-md-6">

        <?php if ($individu) : ?>

            <div class="box card">
                <div class="card-header <?php echo $individu->estHistorise() ? 'bg-danger' : 'bg-info' ?>">
                    <h2 class="first">
                        <?php echo $this->translate("Individu lié") ?> <?php echo $individu->estHistorise() ? 'SUPPRIMÉ' : '' ?>
                        <div class="float-end">
                            <a href="<?php echo $this->url('utilisateur/delier-individu', ['utilisateur' => $utilisateur->getId()], [], true);?>"
                               class="btn btn-danger"
                               data-bs-toggle="tooltip"
                               data-bs-html="true"
                               title="Une confirmation avant la désunion vous sera demandée"
                               data-toggle="confirmationx">Délier du compte utilisateur</a>
                        </div>
                    </h2>
                </div>
                <div class="card-body">
                    <?php echo $this->partial('individu/individu/partial/dl', ['entity' => $individu, 'horizontal' => true]) ?>

                    <a href="<?php echo $this->url('individu/voir', ['individu' => $individu->getId()]) ?>"
                       class="text-center"><i class="icon icon-voir"></i> Voir la fiche détaillée de l'individu</a>
                </div>
            </div>

        <?php else: ?>

            <p>Ce compte utilisateur n'est associé à aucun individu.</p>
            <a
                <?php /** @see UtilisateurController::lierIndividuAction() */?>
                href="<?php echo $this->url('utilisateur/lier-individu', ['utilisateur' => $utilisateur->getId()], [], true); ?>"
                class="btn btn-primary action ajax-modal"
            >
                <span class="fas fa-link"></span>
                Lier à un individu...
            </a>

        <?php endif ?>

    </div>

</div>

<!-- TOKEN D'AUTHENTIFICATION ----------------------------------------------------------------------------------------->

<div class="box card">
    <div class="card-header bg-dark text-white">
        <h2 class="first">
            <?php echo $this->translate("Jeton d'authentification") ?>
            <div class="float-end">
                <?php echo $this->partial('unicaen-auth-token/token/partial/add-button', [
                    'route' => null,
                    'redirect' => $redirect,
                    'user' => $utilisateur->getId(),
                ]) ?>
            </div>
        </h2>
    </div>
    <div class="card-body">
        <?php if (empty($tokens)): ?>
            Le compte utilisateur n'a aucun jeton d'authentification.
        <?php else: ?>
            <?php echo $this->partial('unicaen-auth-token/token/partial/table', ['paginator' => $tokens, 'redirect' => $redirect]); ?>
        <?php endif ?>
    </div>
</div>

<!-- ROLES ----------------------------------------------------------------------------------------->

<div class="box card">
    <div class="card-header bg-dark text-white">
        <h2 class="first">
            <?php echo $this->translate("Rôles de l'individu") ?>
        </h2>
    </div>
    <div class="card-body">
        <?php if ($individu) : ?>
            Rendez-vous sur la <a href="<?php echo $this->url('individu/voir', ['individu' => $individu->getId()]) ?>"
            >fiche détaillée de l'individu</a>...
        <?php else: ?>
            Vous devez lier ce compte utilisateur à un individu pour pouvoir ensuite attribuer un rôle à l'individu.
        <?php endif ?>
    </div>
</div>


<script>
    $(function() {
        $(document).on('hide.bs.modal','.modal', function () {
            // alert('fermeture modal');
            window.parent.location.reload();
        });
    });
</script>
