<?php
 /**
  * @var Proposition $proposition
  * @var array $indicateurs
  * @var bool $canModifier
  * @var string $FORMULAIRE_DELEGATION
  * @var string $typeProposition
  */

use Soutenance\Entity\Membre;
use Soutenance\Entity\Proposition;
use Soutenance\Service\Horodatage\HorodatageService;

$object = $proposition->getObject();
?>

<div id="BOXDIV_JURY">
<div class="box card">
    <div class="card-header <?php echo ($indicateurs["valide"])?'bg-success':'bg-danger'; ?>">
        <h2>
            Composition du jury
        </h2>
    </div>
    <div class="card-body">

        <div class="row mb-2">
            <div class="col-md-4">
                <p class="mb-1">
                    <strong>Équilibre Femme/Homme</strong>
                </p>
                <div class="progress">
                    <div class="progress-bar femme-bar" style="width:<?php echo $indicateurs["parité"]["Femme"]*100; ?>%;">
                        Femme
                    </div>
                    <div class="progress-bar homme-bar"  style="width:<?php echo $indicateurs["parité"]["Homme"]*100; ?>%;">
                        Homme
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <p class="mb-1">
                    <strong>Nombre de membres</strong>
                    <?php if ($indicateurs["membre"]["valide"]):?>
                        <span class="badge bg-success"> Valide </span>
                    <?php else: ?>
                        <span class="badge bg-danger">
                            Non valide
                            <?php if ($alerte = $indicateurs['membre']['alerte'] ?? null): ?>
                                <span class="fa fa-info-circle" data-toggle="tooltip" title="<?php echo $alerte ?>"></span>
                            <?php endif ?>
                        </span>
                    <?php endif; ?>
                </p>

                <div class="progress">
                    <div class="progress-bar progress-bar-info" style="width:<?php echo $indicateurs["membre"]["Ratio"]*100; ?>%; <?php if ($indicateurs["membre"]["valide"] !== true) echo "background-color:darkred;"; ?>" >
                        <?php echo $indicateurs["membre"]["Nombre"]; ?>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <p class="mb-1">
                    <strong>Nombre de rapporteurs</strong>
                    <?php if ($indicateurs["rapporteur"]["valide"]):?>
                        <span class="badge bg-success"> Valide </span>
                    <?php else: ?>
                        <span class="badge bg-danger">
                            Non valide
                            <?php if ($alerte = $indicateurs['rapporteur']['alerte'] ?? null): ?>
                                <span class="fa fa-info-circle" data-toggle="tooltip" title="<?php echo $alerte ?>"></span>
                            <?php endif ?>
                        </span>
                    <?php endif; ?>
                </p>
                <div class="progress">
                    <div class="progress-bar progress-bar-info" style="width:<?php echo $indicateurs["rapporteur"]["Ratio"]*100; ?>%; <?php if ($indicateurs["rapporteur"]["valide"] !== true) echo "background-color:darkred;"; ?>">
                        <?php echo $indicateurs["rapporteur"]["Nombre"]; ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="row mb-2">
            <div class="col-md-4">
                <p class="mb-1">
                    <strong>Nombre de rang A</strong>
                    <?php if ($indicateurs["rang A"]["valide"]):?>
                        <span class="badge bg-success"> Valide </span>
                    <?php else: ?>
                        <span class="badge bg-danger">
                            Non valide
                            <?php if ($alerte = $indicateurs['rang A']['alerte'] ?? null): ?>
                                <span class="fa fa-info-circle" data-toggle="tooltip" title="<?php echo $alerte ?>"></span>
                            <?php endif ?>
                        </span>
                    <?php endif; ?>
                </p>
                <div class="progress">
                    <div class="progress-bar progress-bar-info" style="width:<?php echo $indicateurs["rang A"]["Ratio"]*100; ?>%; <?php if ($indicateurs["rang A"]["valide"] !== true) echo "background-color:darkred;"; ?>">
                        <?php echo $indicateurs["rang A"]["Nombre"]; ?>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <p class="mb-1">
                    <strong>Nombre d'extérieurs</strong>
                    <?php if ($indicateurs["exterieur"]["valide"]):?>
                        <span class="badge bg-success"> Valide </span>
                    <?php else: ?>
                        <span class="badge bg-danger">
                            Non valide
                            <?php if ($alerte = $indicateurs['exterieur']['alerte'] ?? null): ?>
                                <span class="fa fa-info-circle" data-toggle="tooltip" title="<?php echo $alerte ?>"></span>
                            <?php endif ?>
                        </span>
                    <?php endif; ?>
                </p>
                <div class="progress">
                    <div class="progress-bar progress-bar-info" style="width:<?php echo $indicateurs["exterieur"]["Ratio"]*100; ?>%; <?php if ($indicateurs["exterieur"]["valide"] !== true) echo "background-color:darkred;"; ?>">
                        <?php echo $indicateurs["exterieur"]["Nombre"]; ?>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <p class="mb-1">
                    <strong>Rapporteurs non valides</strong>
                    <?php if ($indicateurs["bad-rapporteur"]["valide"]):?>
                        <span class="badge bg-success"> Valide </span>
                    <?php else: ?>
                        <span class="badge bg-danger">
                            Non valide
                            <?php if ($alerte = $indicateurs['bad-rapporteur']['alerte'] ?? null): ?>
                                <span class="fa fa-info-circle" data-toggle="tooltip" title="<?php echo $alerte ?>"></span>
                            <?php endif ?>
                        </span>
                    <?php endif; ?>
                </p>
                <div class="progress">
                    <div class="progress-bar progress-bar-danger" style="width:<?php echo $indicateurs["bad-rapporteur"]["Nombre"]/(max(1,$indicateurs["rapporteur"]["Nombre"]))*100; ?>%; ">
                        <?php echo $indicateurs["bad-rapporteur"]["Nombre"]; ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <p class="mb-1">
                    <strong>Nombre d'émérites</strong>
                    <?php if ($indicateurs["emerites"]["valide"]):?>
                        <span class="badge bg-success"> Valide </span>
                    <?php else: ?>
                        <span class="badge bg-danger">
                            Non valide
                            <?php if ($alerte = $indicateurs['emerites']['alerte'] ?? null): ?>
                                <span class="fa fa-info-circle" data-toggle="tooltip" title="<?php echo $alerte ?>"></span>
                            <?php endif ?>
                        </span>
                    <?php endif; ?>
                </p>
                <div class="progress">
                    <div class="progress-bar progress-bar-info" style="width:<?php echo $indicateurs["emerites"]["Ratio"]*100; ?>%; <?php if ($indicateurs["emerites"]["valide"] !== true) echo "background-color:darkred;"; ?>">
                        <?php echo $indicateurs["emerites"]["Nombre"]; ?>
                    </div>
                </div>
            </div>
        </div>

        <table class="table table-extra-condensed table-hover table-composition-jury">
            <thead>
            <tr>
                <th>Civilité</th>
                <th>Prénom</th>
                <th>Nom</th>
                <th>Adresse électronique</th>
                <th>Qualité</th>
                <th>Rang</th>
                <th>Extérieur</th>
                <th>Etablissement</th>
                <th>Rôle</th>
                <th>En visio</th>
                <?php if ($canModifier): ?>
                    <th>Action</th>
                <?php endif; ?>
            </tr>
            </thead>
            <tbody>
            <?php $hasVisio = false; ?>
            <?php
                /** @var Membre $membre */
                $membres = $proposition->getMembres()->toArray();
                usort($membres, function (Membre $a, Membre $b) { return $a->getNom() . " " . $a->getPrenom() > $b->getNom() . " " . $b->getPrenom();});
                $str = "Rapporteur de rang B non titulaire d'une HDR";
            ?>
            <?php foreach($membres as $membre): ?>
                <tr <?php if ($membre->estRapporteur() AND $membre->getQualite()->isRangB() AND $membre->getQualite()->getHdr() !== 'O') echo " data-toggle='tooltip' title='".htmlentities($str, ENT_QUOTES)."' style='background:lightsalmon;' "; ?>>
                    <td> <?php echo $membre->getCiviliteCourte(); ?> </td>
                    <td> <?php echo $membre->getPrenom(); ?> </td>
                    <td> <?php echo $membre->getNom(); ?> </td>
                    <td> <?php echo ($membre->getEmail() !== null)?$membre->getEmail():"<strong><span class='text-danger'><span class='fas fa-exclamation-triangle'></span> AUCUN MAIL</span></strong>"; ?> </td>
                    <td> <?php echo ($membre->getQualite())?$membre->getQualite()->getLibelle():"Non définie"; ?> </td>
                    <td> <?php echo $membre->getRang(); ?> </td>
                    <td>
                        <?php if ($membre->isExterieur()): ?>
                            <span class="icon icon-oui iconly text-success"></span>
                        <?php else: ?>
                            <span class="icon icon-non iconly text-danger"></span>
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php echo $membre->getEtablissement(); ?> <br/>
                        <?php echo ($membre->getAdresse())??"N.C."; ?>
                    </td>
                    <td> <?php echo $membre->getRole(); ?> </td>
                    <td>
                        <?php if ($membre->isVisio()): ?>
                            <span class="icon icon-oui iconly text-success"></span>
                            <?php $hasVisio = true; ?>
                        <?php else: ?>
                            <span class="icon icon-non iconly text-danger"></span>
                        <?php endif; ?>
                    </td>
                    <?php if ($canModifier): ?>
                    <td>

                            <a  <?php /** @see \Soutenance\Controller\PropositionController::modifierMembreAction(); */ ?>
                                href="<?php echo $this->url("soutenance_{$typeProposition}/proposition/modifier-membre", ['id' => $object->getId(), 'membre' => $membre->getId()], [] ,true); ?>"
                                class="ajax-modal"
                                data-event="edition-membre">
                                <span class="icon icon-edit iconly"></span>
                            </a>
                            <a  <?php /** @see \Soutenance\Controller\PropositionController::effacerMembreAction(); */ ?>
                                href="<?php echo $this->url("soutenance_{$typeProposition}/proposition/effacer-membre", ['id' => $object->getId(), 'membre' => $membre->getId()], [] ,true); ?>"
                                data-toggle="confirmationx"
                                data-bs-toggle="tooltip"
                                data-bs-html="true"
                                title="Une confirmation avant la suppression vous sera demandée">
                                <span class="icon icon-delete iconly"></span>
                            </a>

                    </td>
                    <?php endif; ?>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <!--        </div>-->

        <div class="row">
            <div class="col-md-7">
                <?php if ($hasVisio) : ?>
                    <div class="alert alert-warning">
                        <span class="fas fa-exclamation-triangle"></span>
                        Les membres du jury participant à la soutenance en visioconférence doivent au préalable remplir la demande
                        de délégation de signature suivante :
                        <a href="<?php echo $FORMULAIRE_DELEGATION; ?>">formulaire de demande de délégation</a>.
                    </div>
                <?php endif; ?>
            </div>
            <div class="col-md-7">
                <?php if (isset($indicateurs["membresMail"]["valide"]) && !$indicateurs["membresMail"]["valide"]):?>
                    <div class="alert alert-danger">
                        <span class="fas fa-exclamation-triangle"></span>
                        <?php echo $indicateurs["membresMail"]["alerte"] ?>
                    </div>
                <?php endif; ?>
            </div>

            <div class="col-md-4 float-end">
                <?php if ($canModifier): ?>
                    <a  <?php /** @see \Soutenance\Controller\PropositionController::modifierMembreAction(); */ ?>
                        href="<?php echo $this->url("soutenance_{$typeProposition}/proposition/modifier-membre", ['id' => $object->getId()], [], true); ?>"
                        class="btn btn-primary action ajax-modal"
                        data-event="edition-membre">
                        <span class="icon icon-plus"></span> Ajouter un membre de jury
                    </a>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <?php echo $this->horodatagesParType($proposition, HorodatageService::TYPE_MODIFICATION, "Jury"); ?>
</div>
</div>

<style>
    div.femme-bar {
        background-color: seagreen;
    }
    div.homme-bar {
        background-color: salmon;
    }
    .table-composition-jury{
        margin-top: 15px;
    }
    .card-body{
        max-width:100%;
    }
</style>