<?php
 /**
  * @var Proposition $proposition
  * @var array $indicateurs
  * @var bool $canModifier
  * @var string $FORMULAIRE_DELEGUATION
  */

use Soutenance\Entity\Membre;
use Soutenance\Entity\Proposition;

$these = $proposition->getThese();
?>

<div id="BOXDIV_JURY">
<div class="box panel <?php echo ($indicateurs["valide"])?'panel-success':'panel-danger'; ?>">
    <div class="panel-heading">
        <h2>
            Composition du jury
        </h2>
    </div>
    <div class="panel-body">

        <div class="col-md-4">
            <h5>
                Parité de genre
            </h5>
            <div class="progress">
                <div class="progress-bar femme-bar" style="width:<?php echo $indicateurs["parité"]["Femme"]*100; ?>%;">
                    Femme
                </div>
                <div class="progress-bar homme-bar"  style="width:<?php echo $indicateurs["parité"]["Homme"]*100; ?>%;">
                    Homme
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <h5>
                Nombre de membres
                <?php if ($indicateurs["membre"]["valide"]):?>
                    <span class="badge badge-success"> Valide </span>
                <?php else: ?>
                    <span class="badge badge-error"> Non valide </span>
                <?php endif; ?>
            </h5>

            <div class="progress">
                <div class="progress-bar progress-bar-info" style="width:<?php echo $indicateurs["membre"]["Ratio"]*100; ?>%; <?php if ($indicateurs["membre"]["valide"] !== true) echo "background-color:darkred;"; ?>" >
                    <?php echo $indicateurs["membre"]["Nombre"]; ?>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <h5>
                Nombre de rapporteurs
                <?php if ($indicateurs["rapporteur"]["valide"]):?>
                    <span class="badge badge-success"> Valide </span>
                <?php else: ?>
                    <span class="badge badge-error"> Non valide </span>
                <?php endif; ?>
            </h5>
            <div class="progress">
                <div class="progress-bar progress-bar-info" style="width:<?php echo $indicateurs["rapporteur"]["Ratio"]*100; ?>%; <?php if ($indicateurs["rapporteur"]["valide"] !== true) echo "background-color:darkred;"; ?>">
                    <?php echo $indicateurs["rapporteur"]["Nombre"]; ?>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <h5>
                Nombre de rang A
                <?php if ($indicateurs["rang A"]["valide"]):?>
                    <span class="badge badge-success"> Valide </span>
                <?php else: ?>
                    <span class="badge badge-error"> Non valide </span>
                <?php endif; ?>
            </h5>
            <div class="progress">
                <div class="progress">
                    <div class="progress-bar progress-bar-info" style="width:<?php echo $indicateurs["rang A"]["Ratio"]*100; ?>%; <?php if ($indicateurs["rang A"]["valide"] !== true) echo "background-color:darkred;"; ?>">
                        <?php echo $indicateurs["rang A"]["Nombre"]; ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <h5>
                Nombre d'extérieurs
                <?php if ($indicateurs["exterieur"]["valide"]):?>
                    <span class="badge badge-success"> Valide </span>
                <?php else: ?>
                    <span class="badge badge-error"> Non valide </span>
                <?php endif; ?>
            </h5>
            <div class="progress">
                <div class="progress-bar progress-bar-info" style="width:<?php echo $indicateurs["exterieur"]["Ratio"]*100; ?>%; <?php if ($indicateurs["exterieur"]["valide"] !== true) echo "background-color:darkred;"; ?>">
                    <?php echo $indicateurs["exterieur"]["Nombre"]; ?>
                </div>
            </div>
        </div>

        <table class="table table-extra-condensed">
            <thead>
            <tr>
                <th>Civilité</th>
                <th>Prénom</th>
                <th>Nom</th>
                <th>Adresse électronique</th>
                <th>Qualité</th>
                <th>Rang</th>
                <th>Extérieur</th>
                <th>Etablissement</th>
                <th>Rôle</th>
                <th>En visio</th>
                <?php if ($canModifier): ?>
                    <th>Action</th>
                <?php endif; ?>
            </tr>
            </thead>
            <tbody>
            <?php $hasVisio = false; ?>
            <?php
                /** @var Membre $membre */
                $membres = $proposition->getMembres()->toArray();
                usort($membres, function (Membre $a, Membre $b) { return $a->getNom() . " " . $a->getPrenom() > $b->getNom() . " " . $b->getPrenom();});
            ?>
            <?php foreach($membres as $membre): ?>
                <tr>
                    <td> <?php echo ($membre->getGenre()==='F')?"Madame":"Monsieur"; ?> </td>
                    <td> <?php echo $membre->getPrenom(); ?> </td>
                    <td> <?php echo $membre->getNom(); ?> </td>
                    <td> <?php echo ($membre->getEmail() !== null)?$membre->getEmail():"<strong><span class='text-danger'><span class='glyphicon glyphicon-warning-sign'></span> AUCUN MAIL</span></strong>"; ?> </td>
                    <td> <?php echo ($membre->getQualite())?$membre->getQualite()->getLibelle():"Non définie"; ?> </td>
                    <td> <?php echo $membre->getRang(); ?> </td>
                    <td>
                        <?php if ($membre->isExterieur()): ?>
                            <span class="glyphicon glyphicon-ok text-success"></span>
                        <?php else: ?>
                            <span class="glyphicon glyphicon-remove text-danger"></span>
                        <?php endif; ?>
                    </td>
                    <td> <?php echo $membre->getEtablissement(); ?> </td>
                    <td> <?php echo $membre->getRole(); ?> </td>
                    <td>
                        <?php if ($membre->isVisio()): ?>
                            <span class="glyphicon glyphicon-ok text-success"></span>
                            <?php $hasVisio = true; ?>
                        <?php else: ?>
                            <span class="glyphicon glyphicon-remove text-danger"></span>
                        <?php endif; ?>
                    </td>
                    <?php if ($canModifier): ?>
                    <td>

                            <a  <?php /** @see \Soutenance\Controller\Proposition\PropositionController::modifierMembreAction(); */ ?>
                                href="<?php echo $this->url('soutenance/proposition/modifier-membre', ['these' => $these->getId(), 'membre' => $membre->getId()], [] ,true); ?>"
                                class="ajax-modal"
                                data-event="edition-membre">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </a>
                            <a  <?php /** @see \Soutenance\Controller\Proposition\PropositionController::effacerMembreAction(); */ ?>
                                href="<?php echo $this->url('soutenance/proposition/effacer-membre', ['these' => $these->getId(), 'membre' => $membre->getId()], [] ,true); ?>">
                                <span class="glyphicon glyphicon-trash"></span>
                            </a>

                    </td>
                    <?php endif; ?>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <!--        </div>-->

        <div class="row">
            <div class="col-md-7">
                <?php if ($hasVisio) : ?>
                    <div class="alert alert-warning">
                        <span class="glyphicon glyphicon-warning-sign"></span>
                        Les membres du jury participant à la soutenance en visioconférence doivent au préalable remplir la demande
                        de déléguation de signature suivante :
                        <a href="<?php echo $FORMULAIRE_DELEGUATION; ?>">formulaire de demande de déléguation</a>.
                    </div>
                <?php endif; ?>
            </div>
            <div class="col-md-4 pull-right">
                <?php if ($canModifier): ?>
                    <a  <?php /** @see \Soutenance\Controller\Proposition\PropositionController::modifierMembreAction(); */ ?>
                        href="<?php echo $this->url('soutenance/proposition/modifier-membre', ['these' => $these->getId()], [], true); ?>"
                        class="btn btn-primary action ajax-modal"
                        data-event="edition-membre">
                        <span class="glyphicon glyphicon-plus"></span> Ajouter un membre de jury
                    </a>
                <?php endif; ?>
            </div>
        </div>

    </div>
</div>
</div>

<style>
    div.femme-bar {
        background-color: hotpink;
    }
    div.homme-bar {
        background-color: dodgerblue;
    }
</style>