<?php

/**
 * @var Proposition $proposition
 * @var string $FORMULAIRE_DELOCALISATION
 * @var boolean $canModifier
 */

use Soutenance\Entity\Proposition;

$these = $proposition->getThese();

?>

<div id="BOXDIV_DATE_LIEU">
<div class="box panel <?php echo ($proposition->hasDateEtLieu())?'panel-success':'panel-danger'; ?>" >

    <div class="panel-heading">
        <h2>
            Date et lieu de la soutenance
        </h2>
    </div>

    <div class="panel-body">

        <div class="row">
            <div class="col-md-8">
                <dl>
                    <dt> Date de la soutenance </dt>
                    <dd>
                        <?php if ($proposition->getDate() !== null) : ?>
                            <?php echo $proposition->getDate()->format("d/m/Y"); ?>
                        <?php else : ?>
                            <strong>Date de la soutenance non communiquée </strong>
                        <?php endif; ?>
                    </dd>
                    <dt> Heure de la soutenance </dt>
                    <dd>
                        <?php if ($proposition->getDate() !== null) : ?>
                            <?php echo $proposition->getDate()->format("H:i"); ?>
                        <?php else : ?>
                            <strong>Heure de la soutenance non communiquée </strong>
                        <?php endif; ?>
                    </dd>
                    <dt> Lieu de la Soutenance </dt>
                    <dd>
                        <?php if ($proposition->getLieu() !== null) : ?>
                            <?php echo $proposition->getLieu(); ?>
                        <?php else : ?>
                            <strong>Lieu de la soutenance non communiqué </strong>
                        <?php endif; ?>
                        <?php echo ($proposition->isExterieur())?" (extérieur)":""; ?>
                    </dd>
                </dl>
            </div>

            <div class="col-md-4">
                <div class="pull-right">
                    <?php if ($canModifier) : ?>
                        <a  <?php /**  @see \Soutenance\Controller\Proposition\PropositionController::modifierDateLieuAction() */ ?>
                            href="<?php echo $this->url('soutenance/proposition/modifier-date-lieu', ['these' => $these->getId()], [], true); ?>"
                            class="btn btn-primary action ajax-modal"
                            data-event="edition-datelieu"
                        >
                            <span class="glyphicon glyphicon-pencil"></span>
                            Éditer lieu et date de la soutenance
                        </a>
                    <?php endif; ?>

                    <?php if ($proposition->isExterieur()) : ?>
                        <div class="alert alert-warning">
                            <span class="glyphicon glyphicon-warning-sign"> </span>
                            Si la soutenance ne se déroule pas dans les locaux de l'établissement d'inscription alors il est nécessaire de signer une demande de délocalisation&nbsp;:
                            <a href="<?php echo $FORMULAIRE_DELOCALISATION; ?>">
                                formulaire de demande de délocalisation</a>.
                        </div>
                    <?php endif; ?>
                </div>


            </div>

        </div>
    </div>

</div>
</div>