<?php

/**
 * @see view/soutenance/proposition/proposition.phtml
 *
 * Formation "Intégrité Scientifique"
 * @var bool $canModifier
 * @var Justificatif[] $attestationsIntegriteScientifique
 * @var UrlFichierThese $urlFichierThese
 *
 * @var Validation[] $validation
 * @var Validation[] $refus
 * @var These $these
 * @var Proposition $proposition
 *
 */

$canModifier = true;

use Depot\Controller\Plugin\UrlFichierThese;
use Fichier\Entity\Db\NatureFichier;
use Soutenance\Entity\Justificatif;
use Soutenance\Entity\Proposition;
use Soutenance\Service\Horodatage\HorodatageService;
use These\Entity\Db\These;
use Application\Entity\Db\Validation;
use Soutenance\Provider\Privilege\PropositionPrivileges;

$isValider = null;
if (!empty($validation)) $isValider = true;
if (!empty($refus)) $isValider = false;


$canValider = $this->isAllowed($these, PropositionPrivileges::PROPOSITION_DECLARATION_HONNEUR_VALIDER);
$canRevoquer = $this->isAllowed($these,PropositionPrivileges::PROPOSITION_DECLARATION_HONNEUR_REVOQUER);

?>

<div class="box card">
    <div class="card-header
    <?php
    if ($isValider === null OR empty($attestationsIntegriteScientifique) )  echo " bg-warning";
    if ($isValider === true AND !empty($attestationsIntegriteScientifique))  echo " bg-success";
    if ($isValider === false) echo " bg-danger";
    ?>
">
    <h2> Intégrité scientifique </h2>
    </div>
    <div class="card-body">

        <div id="formation_integrite_scientifique">
            <h3> Formation à propos de l'intégrité scientifique </h3>

            <p class="lead">
                Afin d'être autorisé·e à soutenir, vous devez avoir suivi une formation sur l'intégrité scientifique.
            </p>

            <?php if ($attestationsIntegriteScientifique === []) : ?>
                <div class="row">
                    <div class="col-md-8">
                        <div class="alert alert-warning">
                            <span class="icon icon-info"></span>
                            Veuillez déposer ici une attestation de suivi pour cette formation.
                        </div>
                    </div>
                    <div class="col-md-4">
                        <?php if ($canModifier) : ?>
                            <?php /** @see \Soutenance\Controller\JustificatifController::ajouterJustificatifAction() */ ?>
                            <a href="<?php echo $this->url('soutenance/justificatif/ajouter-justificatif', ['these' => $these->getId(), 'nature' => NatureFichier::CODE_FORMATION_INTEGRITE_SCIENTIFIQUE], [], true); ?>"
                               class="btn btn-primary ajax-modal" data-event="modification">
                                <span class="icon icon-televerser"></span>
                                Téléversement une attestation
                            </a>
                        <?php endif; ?>
                    </div>
                </div>
            <?php else : ?>
                <ul>
                    <?php foreach ($attestationsIntegriteScientifique as $attestation) : ?>
                    <li>
                        <?php echo $this->justificatif()->render($attestation, $urlFichierThese, ['court' => true]); ?>
                        <?php if ($canModifier) : ?>
                            <?php /** @see \Soutenance\Controller\JustificatifController::retirerAction() */ ?>
                            <?php $retour = $this->url('soutenance/proposition', ['these' => $these->getId()],['force_canonical' => true ], true); ?>
                            <a href="<?php echo $this->url('soutenance/justificatif/retirer',
                                ['these' => $these->getId(), 'justificatif'=>$attestation->getId()],
                                ["query" => ["retour" => $retour]],
                                true); ?>
                           ">
                                <span style='color:darkred;' class="icon icon-delete iconly" title="Supprimer le justificatif"></span>
                            </a>
                        <?php endif; ?>
                    </li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </div>

        <div id="declaration_non_plagiat">
            <h3> Déclaration sur l'honneur de non plagiat </h3>

            <p class="lead">
                Afin de pouvoir valider votre proposition vous devez accepter la déclaration sur l'honneur de non-plagiat.
            </p>

            <div class="row">

            <div class="col-md-8">
                <?php if (!empty($validation)) : ?>
                    Déclaration sur l'honneur faite <br/>
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            <?php echo $this->validation(current($validation)); ?>
                        </div>
                    </div>
                <?php endif; ?>
                <?php if (!empty($refus)) : ?>
                    Déclaration sur l'honneur refusée <br/>
                    <div class="panel panel-danger">
                        <div class="panel-heading">
                            <?php echo $this->validation(current($refus)); ?>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
            <div class="col-md-4">
                <?php if (empty($refus) AND empty($validation)) : ?>
                    <?php if ($canValider) : ?>
                        <a href="<?php echo $this->url('soutenance/proposition/declaration-non-plagiat', ['these' => $these->getId() ], [], true); ?>"
                           class="btn btn-primary" data-event="modification"
                        >
                            <span class="icon icon-checked"></span>
                            Accéder à la déclaration
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if (!empty($refus) OR !empty($validation)) : ?>
                    <?php if ($canRevoquer) : ?>
                        <?php /** @see \Soutenance\Controller\PropositionController::revoquerDeclarationNonPlagiatAction() */ ?>
                        <a href="<?php echo $this->url('soutenance/proposition/declaration-non-plagiat/revoquer', ['these' => $these->getId()], [], true); ?>"
                           class="btn btn-danger"
                        >
                            <span class="icon icon-unchecked"></span>
                            Révoquer la déclaration
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        </div>
        </div>

        <div id="serment_du_docteur">

            <h3> Serment du docteur </h3>

            <div class="row">
                <div class="col-md-8">
                    <p class="lead"> Vous pouvez télécharger le serment du docteur que vous pourrez préter à l'issue de votre soutenance.</p>
                </div>
                <div class="col-md-4">
                    <?php /** @see \Soutenance\Controller\PropositionController::genererSermentAction() */ ?>
                    <a href="<?php echo $this->url('soutenance/proposition/generer-serment', ['these' => $these->getId()], [], true); ?>" class="btn btn-primary" target="_blank">
                        <span class="icon icon-pdf"></span>
                        Télécharger le serment du docteur
                    </a>
                </div>
            </div>
            <?php echo $this->horodatagesParType($proposition, HorodatageService::TYPE_EDITION, "Serment du docteur"); ?>
        </div>

    </div>
</div>