<?php

/**
 * @var Validation[] $validation
 * @var Validation[] $refus
 * @var These $these
 */

use These\Entity\Db\These;
use Application\Entity\Db\Validation;
use Soutenance\Provider\Privilege\PropositionPrivileges;

$isValider = null;
if (!empty($validation)) $isValider = true;
if (!empty($refus)) $isValider = false;

$canValider = $this->isAllowed($these, PropositionPrivileges::PROPOSITION_DECLARATION_HONNEUR_VALIDER);
$canRevoquer = $this->isAllowed($these,PropositionPrivileges::PROPOSITION_DECLARATION_HONNEUR_REVOQUER);
?>

<div class="box card">
    <div class="card-header
    <?php
    if ($isValider === null)  echo " bg-warning";
    if ($isValider === true)  echo " bg-success";
    if ($isValider === false) echo " bg-danger";
    ?>
">

    <h2> Intégrité scientifique </h2>
    </div>
    <div class="card-body">
        <h3> Déclaration sur l'honneur de non plagiat</h3>
        <div class="col-md-8">
            Afin de pouvoir valider votre proposition vous devez accepter la déclaration sur l'honneur de non plagiat.
        </div>
        <div class="col-md-4">

        <?php if ($canValider) : ?>
            <?php if ($isValider === null) : ?>
                <a href="<?php echo $this->url('soutenance/proposition/declaration-non-plagiat', ['these' => $these->getId() ], [], true); ?>"
                   class="btn btn-primary" data-event="modification"
                >
                    <span class="glyphicon glyphicon-pencil"></span>
                    Accéder à la déclaration
                </a>
            <?php endif; ?>
        <?php endif; ?>
        </div>

        <div class="row">
            <div class="col-md-9">
                <div style="width:80%;margin:0 auto; ">
                <?php if ($isValider === true) : ?>
                    Déclaration sur l'honneur faite <br/>
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            <?php echo $this->validation(current($validation)); ?>
                        </div>
                    </div>
                <?php endif; ?>
                <?php if ($isValider === false) : ?>
                    Déclaration sur l'honneur refusée <br/>
                    <div class="panel panel-danger">
                        <div class="panel-heading">
                            <?php echo $this->validation(current($refus)); ?>
                        </div>
                    </div>
                <?php endif; ?>
                </div>
            </div>
            <div class="col-md-3">
                <?php if ($isValider !== null AND $canRevoquer) : ?>
                    <?php /** @see \Soutenance\Controller\PropositionController::revoquerDeclarationNonPlagiatAction() */ ?>
                    <a href="<?php echo $this->url('soutenance/proposition/declaration-non-plagiat/revoquer', ['these' => $these->getId()], [], true); ?>"
                       class="btn btn-danger"
                   >
                        <span class="icon icon-unchecked"></span>
                        Révoquer la déclaration
                    </a>
                <?php endif; ?>
            </div>
        </div>

        <br/>

        <h3> Serment du docteur </h3>

        <div class="row">
            <div class="col-md-8">
                Vous pouvez télécharger le serment du docteur que vous pourrez préter à l'issue de votre soutenance
            </div>
            <div class="col-md-4">
                <?php /** @see \Soutenance\Controller\PropositionController::genererSermentAction() */ ?>
                <a href="<?php echo $this->url('soutenance/proposition/generer-serment', ['these' => $these->getId()], [], true); ?>" class="btn btn-secondary" target="_blank">
                    <span class="icon icon-pdf"></span>
                    Télécharger le serment du docteur
                </a>
            </div>
        </div>

    </div>
</div>