<?php
/**
 * @var \Soutenance\Entity\Proposition $proposition
 * @var \Application\Entity\Db\These $these
 */

use Soutenance\Provider\Privilege\PropositionPrivileges;

$canModifier = $this->isAllowed($these, PropositionPrivileges::PROPOSITION_MODIFIER);
?>

<div class="box panel panel-info">
    <div class="panel-heading">
        <h2>
            Informations sur la thèse et la soutenance
        </h2>
    </div>
    <div class="panel-body">

        <div class="row">
            <div class="col-md-8">
                <dl>

                    <!-- COTUTELLE -->
                    <?php if ($these->getLibelleEtabCotutelle() || $these->getLibellePaysCotutelle()) : ?>

                        <dt> Établissement de co-tutelle </dt>
                        <dd> <?php echo ($these->getLibelleEtabCotutelle())?$these->getLibelleEtabCotutelle():"non renseigné"; ?></dd>
                        <dt> Pays de co-tutelle </dt>
                        <dd> <?php echo ($these->getLibellePaysCotutelle())?$these->getLibellePaysCotutelle():"non renseigné"; ?></dd>
                    <?php else : ?>
                        <dt> Cotutelle  </dt>
                        <dd> Pas de cotutuelle. </dd>
                    <?php endif; ?>

                    <!-- LABEL -->
                    <dt>Label européen </dt>
                    <dd>
                        <?php echo ($proposition->isLabelEuropeen())?"Oui":"Non"; ?>
                    </dd>

                </dl>
            </div>

            <div class="col-md-4">
                <?php if ($canModifier) : ?>

                    <div class="pull-right">
                        <a href="<?php echo $this->url('soutenance/proposition/label-europeen', ['these' => $these->getId()], [], true); ?>"
                           class="btn btn-primary action ajax-modal"
                           data-event="edition-confidentialite"
                        >
                            <span class="glyphicon glyphicon-plus"></span>
                            Renseigner un label européen
                        </a>
                    </div>

                    <br/>
                    <br/>
                    <br/>

                <?php endif; ?>

                <?php if($proposition->isLabelEuropeen()): ?>
                    <div class="alert alert-sm alert-warning">
                        <span class="glyphicon glyphicon-warning-sign"> </span>
                        Afin de réaliser la demande de label européen, vous devez remplir le formulaire de demande suivant :
                        <a href="../../informations/fichiers/telecharger/402">formulaire de demande de label européen</a>.
                    </div>
                <?php endif; ?>
            </div>
        </div>

        <!-- THESE EN ANGLAIS ----------------------------------------------------------------------------------------->
        <div class="row">
            <div class="col-md-8">
                <dl>
                    <dt>Thèse en anglais </dt>

                    <?php if ($proposition->isManuscritAnglais() || $proposition->isSoutenanceAnglais()) : ?>
                        <?php if ($proposition->isManuscritAnglais()) : ?>
                            <dd>
                                Manuscrit en anglais
                            </dd>
                        <?php endif; ?>
                        <?php if ($proposition->isSoutenanceAnglais()) : ?>
                            <dd>
                                Soutenance en anglais
                            </dd>
                        <?php endif; ?>
                    <?php else : ?>
                        <dd> Non </dd>
                    <?php endif;?>

                </dl>
            </div>

            <div class="col-md-4">
                <?php if ($canModifier) : ?>

                    <div class="pull-right">
                        <a href="<?php echo $this->url('soutenance/proposition/anglais', ['these' => $these->getId()], [], true); ?>"
                           class="btn btn-primary action ajax-modal"
                           data-event="edition-confidentialite"
                        >
                            <span class="glyphicon glyphicon-plus"></span>
                            Renseigner thèse en anglais
                        </a>
                    </div>

                    <br/>
                    <br/>
                    <br/>

                <?php endif; ?>

                <?php if($proposition->isManuscritAnglais() || $proposition->isSoutenanceAnglais()): ?>
                    <div class="alert alert-sm alert-warning">
                        <span class="glyphicon glyphicon-warning-sign"> </span>
                        Afin de réaliser la demande de rédaction ou de soutenance en anglais vous devez motiver votre demande via la demande suivante :
                        <a href="../../informations/fichiers/telecharger/404">demande de redaction ou de soutenance en anglais</a>.
                    </div>
                <?php endif; ?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-8">
                <dl>
                    <dt> Confidentialité de la thèse</dt>
                    <?php if($proposition->getConfidentialite()): ?>
                        <dd> Date de fin de confidentialité : <?php echo $proposition->getConfidentialite()->format("d/m/Y"); ?> </dd>
                        <?php if($proposition->isHuitClos()): ?>
                            <dd> Soutenance en huis clos </dd>
                        <?php endif; ?>
                    <?php else : ?>
                        <dd> Thèse non confidentielle </dd>
                    <?php endif; ?>
                </dl>
            </div>

            <div class="col-md-4">
                <?php if ($canModifier) : ?>
                    <div class="pull-right">
                        <a href="<?php echo $this->url('soutenance/proposition/confidentialite', ['these' => $these->getId()], [], true); ?>"
                           class="btn btn-primary action ajax-modal"
                           data-event="edition-confidentialite"
                        >
                            <span class="glyphicon glyphicon-plus"></span>
                            Renseigner une confidentialité
                        </a>
                    </div>

                    <br/>
                    <br/>
                    <br/>

                <?php endif; ?>

                <?php if($proposition->getConfidentialite()): ?>
                    <div class="alert alert-sm alert-warning">
                        <span class="glyphicon glyphicon-warning-sign"> </span>
                        Afin de réaliser de demande de confidentialité un accord doit au préalable être rempli :
                        <a href="../../informations/fichiers/telecharger/403">demande d'accord de confidentialité</a>.
                    </div>
                <?php endif; ?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-8">
                <dl>
                    <dt> Titre de la thèse </dt>
                    <dd> <?php echo ($proposition->getNouveauTitre())?:$proposition->getThese()->getTitre(); ?> </dd>
                </dl>
            </div>

            <div class="col-md-4">
                <?php if ($canModifier) : ?>
                    <div class="pull-right">
                        <a href="<?php echo $this->url('soutenance/proposition/changement-titre', ['these' => $these->getId()], [], true); ?>"
                           class="btn btn-primary action ajax-modal"
                           data-event="edition-confidentialite"
                        >
                            <span class="glyphicon glyphicon-plus"></span>
                            Modifier le titre de la thèse
                        </a>
                    </div>

                    <br/>
                    <br/>
                    <br/>

                <?php endif; ?>

            </div>
        </div>
    </div>
</div>