<?php

/**
 * @var Proposition $proposition
 * @var string $FORMULAIRE_DELOCALISATION
 * @var boolean $canModifier
 * @var boolean $informationsOk
 *
 * @var IndividuRole[] $ecoleResponsables
 * @var IndividuRole[] $uniteResponsables
 * @var string[] $emailsAspectDoctorats
 *
 * @var Acteur[] $directeurs
 */

use These\Entity\Db\Acteur;
use Individu\Entity\Db\IndividuRole;
use Soutenance\Entity\Proposition;

$these = $proposition->getThese();


$unite = $these->getUniteRecherche();
$ecole = $these->getEcoleDoctorale();
$etablissement = $these->getEtablissement();

?>



<div id="BOXDIV_INFORMATIONS">
<div class="box card" >

    <div class="card-header <?php echo ($informationsOk)?'bg-success':'bg-danger'; ?>">
        <h2>
            Informations sur les intervenants (Directeurs, Responsables d'UR, Responsable d'ED, ...)
        </h2>
    </div>

    <div class="card-body">

        <div class="row">
            <div class="col-md-6">
                <h3>Direction de la thèse</h3>

                <ul>
                    <?php foreach ($directeurs as $directeur) : ?>
                        <li>
                            <?php echo $directeur->getIndividu()->getNomComplet(); ?>
                            (<?php echo ($directeur->getIndividu()->getEmailPro())?:'<span class="text-danger">Adresse électronique manquante</span>'; ?>)
                            <br/>
                            Établissement :
                            <?php echo ($directeur->getIndividu()->getEtablissement())?:'<span class="text-danger">Établissement manquant</span>'; ?>
                            <br/>
                            Unité de recherche :
                            <?php echo ($directeur->getIndividu()->getUniteRecherche())?:'<span class="text-danger">Unité de recherche manquante</span>'; ?>
                            <br/>
                            <?php if ($canModifier) : ?>
                                <?php /** @see \Individu\Controller\IndividuComplController::gererAction() */ ?>
                                <a href="<?php echo $this->url("individu-compl/gerer", ['individu' => $directeur->getIndividu()->getId()], [], true); ?>" class="btn btn-primary btn-sm ajax-modal" data-event="modification">
                                    <span class="icon icon-editer"></span> Compléter les informations
                                </a>
                            <?php endif; ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <div class="col-md-6">
                <h3>Structures associées</h3>
                    <dl>
                        <dt> Unité de recherche </dt>
                        <dd>
                            <?php if (!$unite) : ?>
                                <strong class="text-danger">Aucune unité de recherche !</strong>
                            <?php else : ?>
                                <?php echo $unite->getStructure()->getLibelle(); ?>
                                    <?php if (empty($uniteResponsables)) : ?>
                                        <div class="alert alert-danger">
                                            <span class="icon icon-attention"></span>
                                            Aucun responsable d'UR trouvé associé à l'établissement d'inscription (site)
                                        </div>
                                    <?php else : ?>
                                        <ul>
                                        <?php foreach ($uniteResponsables as $uniteResponsable) : ?>
                                            <li>
                                                <?php echo $uniteResponsable->getIndividu()->getNomComplet(); ?>
                                                (<?php echo ($uniteResponsable->getIndividu()->getEmailPro())?:"<span class='text-danger'>Adresse électronique manquante</span>"; ?>)
                                            </li>
                                        <?php endforeach; ?>
                                        </ul>
                                    <?php endif; ?>
                            <?php endif; ?>
                        </dd>
                        <dt> École doctorale </dt>
                        <dd>
                            <?php if (!$ecole) : ?>
                                <strong class="text-danger">Aucune école doctorale !</strong>
                            <?php else : ?>
                                <?php echo $ecole->getStructure()->getLibelle(); ?>
                                <?php if (empty($ecoleResponsables)) : ?>
                                    <div class="alert alert-danger">
                                        <span class="icon icon-attention"></span>
                                        Aucun responsable d'ED trouvé associé à l'établissement d'inscription (site)
                                    </div>
                                <?php else : ?>
                                    <ul>
                                        <?php foreach ($ecoleResponsables as $ecoleResponsable) : ?>
                                            <li>
                                                <?php echo $ecoleResponsable->getIndividu()->getNomComplet(); ?>
                                                (<?php echo ($ecoleResponsable->getIndividu()->getEmailPro())?:"<span class='text-danger'>Adresse électronique manquante</span>"; ?>)
                                            </li>
                                        <?php endforeach; ?>
                                    </ul>
                                <?php endif; ?>
                            <?php endif; ?>
                        </dd>
                        <dt> Établissement </dt>
                        <dd>
                            <?php echo $etablissement->getStructure()->getLibelle(); ?>
                            <?php if (empty($emailsAspectDoctorats)) : ?>
                                <div class="alert alert-danger">
                                    <span class="icon icon-attention"></span>
                                    Aucun destinataire trouvé, une adresse générique doit être renseignée sur la fiche
                                    de l'établissement d'inscription '<?php echo $etablissement->getStructure()->getLibelle(); ?>'
                                    pour l'aspect "Doctorat".
                                </div>
                            <?php else : ?>
                                <ul>
                                    <?php foreach ($emailsAspectDoctorats as $emailsAspectDoctorat) : ?>
                                        <li>
                                            <?php echo $emailsAspectDoctorat; ?>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            <?php endif; ?>
                        </dd>
                    </dl>
            </div>

        </div>
    </div>
</div>
</div>