<?php
/**
 * @var Proposition $proposition
 * @var string $FORMULAIRE_DEMANDE_LABEL
 * @var string $FORMULAIRE_DEMANDE_ANGLAIS
 * @var string $FORMULAIRE_DEMANDE_CONFIDENTIALITE
 * @var bool $canModifier
 */

use Soutenance\Entity\Proposition;


$these = $proposition->getThese();
?>

<div id="BOXDIV_INFORMATIONS">
<div class="box panel panel-info">
    <div class="panel-heading">
        <h2>
            Informations sur la thèse et la soutenance
        </h2>
    </div>
    <div class="panel-body">

            <div class="col-md-8">
                <dl>

                    <!-- COTUTELLE -->
                    <?php if ($these->getLibelleEtabCotutelle() || $these->getLibellePaysCotutelle()) : ?>

                        <dt> Établissement de co-tutelle </dt>
                        <dd> <?php echo ($these->getLibelleEtabCotutelle())?$these->getLibelleEtabCotutelle():"non renseigné"; ?></dd>
                        <dt> Pays de co-tutelle </dt>
                        <dd> <?php echo ($these->getLibellePaysCotutelle())?$these->getLibellePaysCotutelle():"non renseigné"; ?></dd>
                    <?php else : ?>
                        <dt> Cotutelle  </dt>
                        <dd> Pas de cotutuelle. </dd>
                    <?php endif; ?>

                    <!-- LABEL -->
                    <dt>Label européen </dt>
                    <dd>
                        <?php echo ($proposition->isLabelEuropeen())?"Oui":"Non"; ?>
                    </dd>

                </dl>
            </div>

            <div class="col-md-4">
                <?php if ($canModifier) : ?>
                    <a <?php /** @see \Soutenance\Controller\PropositionController::labelEuropeenAction(); */ ?>
                       href="<?php echo $this->url('soutenance/proposition/label-europeen', ['these' => $these->getId()], [], true); ?>"
                       class="btn btn-primary action ajax-modal"
                       data-event="edition-informations"
                    >
                        <span class="glyphicon glyphicon-plus"></span>
                        Renseigner un label européen
                    </a>
                <?php endif; ?>

                <?php if($proposition->isLabelEuropeen()): ?>
                    <div class="alert alert-warning">
                        <span class="glyphicon glyphicon-warning-sign"> </span>
                        Afin de réaliser la demande de label européen, vous devez remplir le formulaire de demande suivant :
                        <a href="<?php echo $FORMULAIRE_DEMANDE_LABEL; ?>">formulaire de demande de label européen</a>.
                    </div>
                <?php endif; ?>
        </div>

        <!-- THESE EN ANGLAIS ----------------------------------------------------------------------------------------->
        <div class="col-md-8">
            <dl>
                <dt>Thèse en anglais </dt>

                <?php if (/*$proposition->isManuscritAnglais() ||*/ $proposition->isSoutenanceAnglais()) : ?>
<!--                    --><?php //if ($proposition->isManuscritAnglais()) : ?>
<!--                        <dd>-->
<!--                            Manuscrit en anglais-->
<!--                        </dd>-->
<!--                    --><?php //endif; ?>
                    <?php if ($proposition->isSoutenanceAnglais()) : ?>
                        <dd>
                            Soutenance en anglais
                        </dd>
                    <?php endif; ?>
                <?php else : ?>
                    <dd> Non </dd>
                <?php endif;?>

            </dl>
        </div>

        <div class="col-md-4">
            <?php if ($canModifier) : ?>
                <a <?php /** @see \Soutenance\Controller\PropositionController::anglaisAction(); */ ?>
                   href="<?php echo $this->url('soutenance/proposition/anglais', ['these' => $these->getId()], [], true); ?>"
                   class="btn btn-primary action ajax-modal"
                   data-event="edition-informations"
                >
                    <span class="glyphicon glyphicon-plus"></span>
                    Renseigner thèse en anglais
                </a>
            <?php endif; ?>

<!--            --><?php //if($proposition->isManuscritAnglais() || $proposition->isSoutenanceAnglais()): ?>
<!--                <div class="alert alert-warning">-->
<!--                    <span class="glyphicon glyphicon-warning-sign"> </span>-->
<!--                    Afin de réaliser la demande de rédaction ou de soutenance en anglais vous devez motiver votre demande via la demande suivante :-->
<!--                    <a href="--><?php //echo $FORMULAIRE_DEMANDE_ANGLAIS; ?><!--">demande de redaction ou de soutenance en anglais</a>.-->
<!--                </div>-->
<!--            --><?php //endif; ?>
        </div>

        <div class="col-md-8">
            <dl>
                <dt> Confidentialité de la thèse</dt>
                <?php if ($these->getDateFinConfidentialite() !== null): ?>
                    Thèse confidentiel jusqu'au <?php echo $these->getDateFinConfidentialite()->format('d/m/Y'); ?>
                    <?php if($proposition->isHuitClos()): ?>
                        <dd> Soutenance en huis clos </dd>
                    <?php endif; ?>
                <?php else: ?>
                    <?php if($proposition->getConfidentialite()): ?>
                        <dd> Date de fin de confidentialité : <?php echo $proposition->getConfidentialite()->format("d/m/Y"); ?> </dd>
                        <?php if($proposition->isHuitClos()): ?>
                            <dd> Soutenance en huis clos </dd>
                        <?php endif; ?>
                    <?php else : ?>
                        <dd> Thèse non confidentielle </dd>
                    <?php endif; ?>
                <?php endif; ?>
            </dl>
        </div>

        <div class="col-md-4">
            <?php if ($canModifier) : ?>
                <a <?php /** @see \Soutenance\Controller\PropositionController::confidentialiteAction(); */ ?>
                   href="<?php echo $this->url('soutenance/proposition/confidentialite', ['these' => $these->getId()], [], true); ?>"
                   class="btn btn-primary action ajax-modal"
                   data-event="edition-informations"
                >
                    <span class="glyphicon glyphicon-plus"></span>
                    Renseigner une confidentialité et huis clos
                </a>
            <?php endif; ?>

            <?php if($proposition->getConfidentialite()): ?>
                <div class="alert alert-warning">
                    <span class="glyphicon glyphicon-warning-sign"> </span>
                    Afin de réaliser de demande de confidentialité un accord doit au préalable être rempli :
                    <a href="<?php echo $FORMULAIRE_DEMANDE_CONFIDENTIALITE; ?>">demande d'accord de confidentialité</a>.
                </div>
            <?php endif; ?>
        </div>

        <div class="col-md-8">
            <dl>
                <dt> Titre de la thèse </dt>
                <dd> <?php echo ($proposition->getNouveauTitre())?:$proposition->getThese()->getTitre(); ?> </dd>
            </dl>
        </div>

        <div class="col-md-4">
            <?php if ($canModifier) : ?>
                <a <?php /** @see \Soutenance\Controller\PropositionController::changementTitreAction(); */ ?>
                   href="<?php echo $this->url('soutenance/proposition/changement-titre', ['these' => $these->getId()], [], true); ?>"
                   class="btn btn-primary action ajax-modal"
                   data-event="edition-informations"
                >
                    <span class="glyphicon glyphicon-plus"></span>
                    Modifier le titre de la thèse
                </a>
            <?php endif; ?>
        </div>
    </div>
</div>
</div>