<?php

/**
 * @var Proposition $proposition
 * @var Avis[] $avis
 * @var string $typeProposition
 */

use Soutenance\Entity\Avis;
use Soutenance\Entity\Proposition;

$object = $proposition->getObject();
?>

<div class="box card">
    <div class="card-header bg-dark text-white">
        <h2>Pré-rapports de soutenance</h2>
    </div>
    <div class="card-body">
        <div>
            <?php if (empty($avis)) : ?>
                <div class="alert alert-info">
                    <span class="icon icon-info"></span>
                    Aucun pré-rapport déposé pour le moment.
                </div>
            <?php else : ?>
            <table class="table table-condensed">
                <thead>
                <tr>
                    <th> Rapporteur </th>
                    <th> Avis </th>
                    <th> Pré-rapport </th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($avis as $avi) : ?>
                    <tr>
                        <td> <?php echo $avi->getMembre()->getDenomination(); ?> </td>
                        <td>
                            <?php if ($avi->getAvis() === Avis::FAVORABLE) : ?>
                                <span class="badge bg-success text-white">
                                    <span class="icon icon-ok"></span>
                                    Avis favorable
                                </span>
                            <?php else : ?>
                                <span class="badge bg-danger text-white">
                                    <span class="icon icon-ko"></span>
                                    Avis défavorable
                                </span>
                            <?php endif; ?>
                        <td>
                            <?php /** @see \Soutenance\Controller\AvisController::telechargerAction() ?> */?>
                            <a href="<?php echo $this->url("soutenance_{$typeProposition}/avis-soutenance/telecharger", ['id' => $object->getId(), 'rapporteur' => $avi->getMembre()->getId()], true); ?>"
                            class="btn btn-primary"
                            >
                                <span class="icon icon-pdf"></span> Télécharger le pré-rapport
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <?php endif; ?>
        </div>
    </div>
</div>