<?php
/**
 * @var Proposition $proposition
 * @var Validation[][] $validations
 *
 * @var boolean $isOk
 * @var boolean $canValiderActeur
 * @var boolean $canSursis
 *

 * @var Doctorant $doctorant
 * @var Acteur[] $directeurs
 * @var Individu $currentIndividu
 * @var boolean $validationActeur
 *
 * @var bool $informationsOk
 */


use Application\Entity\Db\Acteur;
use Doctorant\Entity\Db\Doctorant;
use Individu\Entity\Db\Individu;
use Application\Entity\Db\Role;
use Application\Entity\Db\Validation;
use Soutenance\Entity\Proposition;
use Soutenance\Provider\Validation\TypeValidation;

$these = $proposition->getThese();

$declarationHonneur = !empty($validations[TypeValidation::CODE_VALIDATION_DECLARATION_HONNEUR]);
$a=1;
?>

<div class="box card">
    <div class="card-header bg-info">
        <h2>
            Validation de la proposition de soutenance
        </h2>
    </div>
    <div class="card-body">

        <?php if (!$informationsOk) : ?>
            <div class="alert alert-danger">
                <span class="icon icon-attention"></span>
                Au moins une information sur la direction ou l'encadrement de la thèse est manquante.
            </div>
        <?php endif; ?>
        <?php if (!$declarationHonneur) : ?>
            <div class="alert alert-danger">
                <span class="icon icon-attention"></span>
                La déclaration sur l'honneur de non-plagiat doit être validée avant de permettre la validation de la proposition.
            </div>
        <?php endif; ?>

        <div class="row">
            <div class="col-md-6" >
                <h4>
                    Liste des validations
                </h4>

                <?php if ($declarationHonneur === true) : ?>
                    <ul>
                    <li>
                        <?php echo $doctorant->getIndividu(); ?>
                        <br/>
                        <?php if ($validations[Role::CODE_DOCTORANT]) : ?>
                            <?php $validation = current($validations[Role::CODE_DOCTORANT]); ?>
                            <span class="badge bg-success"> Validée</span>
                            Le <?php echo $validation->getHistoModification()->format('d/m/Y à H:i'); ?>
                        <?php else: ?>
                            <span class="badge bg-secondary"> Aucune validation</span>
                        <?php endif; ?>

                    </li>

                    <?php $validationsDirecteurs = array_merge($validations[Role::CODE_DIRECTEUR_THESE], $validations[Role::CODE_CODIRECTEUR_THESE]); ?>
                    <?php foreach ($directeurs as $directeur): ?>
                        <?php $validation = current(array_filter($validationsDirecteurs, function (Validation $v) use ($directeur) { return $v->getIndividu()->getId() === $directeur->getIndividu()->getId();})); ?>
                        <li>
                            <?php echo $directeur->getIndividu(); ?>
                            (<?php echo $directeur->getRole()->getLibelle();?>)
                            <br/>
                            <?php if ($validation) : ?>
                                <span class="badge bg-success"> Validée</span>
                                Le <?php echo $validation->getHistoModification()->format('d/m/Y à H:i'); ?>
                            <?php else: ?>
                                <span class="badge bg-secondary"> Aucune validation</span>
                            <?php endif; ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
                <?php endif; ?>
            </div>

            <div class="col-md-6 float-end" >
                <?php if (! $validationActeur) : ?>
                    <?php if (!$isOk): ?>
                        <div class="alert card-bodywarning">
                            <span class="fas fa-exclamation-triangle"></span>
                            Pour pouvoir être valider la proposition de soutenance doit être recevable : date et lieu, composition du jury, ...
                        </div>
                    <?php endif; ?>
                    <?php if (!$canValiderActeur) : ?>
                        <?php if (!$proposition->hasSursis()) : ?>
                            <div class="alert alert-warning">
                                <span class="fas fa-exclamation-triangle"></span>
                               Il est possible de valider une proposition seulement si le délai de deux mois entre la date de validation et la date de soutenance est respecté.
                            </div>
                        <?php endif; ?>
                    <?php else : ?>
                            <a
                                <?php /** @see \Soutenance\Controller\PropositionController::validerActeurAction(); */ ?>
                                href="<?php echo $this->url('soutenance/proposition/valider', ['these' => $these->getId()], [], true); ?>"
                                class="btn btn-success action ">
                                <span class="icon icon-ok"></span> Valider la proposition de soutenance
                            </a>
                    <?php endif; ?>
                <?php endif; ?>
            </div>

            <?php if ($canSursis) : ?>
                <div class="col-md-6" >
                    <?php /** @see \Soutenance\Controller\PropositionController::toggleSursisAction() */ ?>
                    <a href="<?php echo $this->url('soutenance/proposition/sursis', ['these' => $these->getId()], [], true); ?>" class="btn btn-primary action float-end">
                        <?php if (!$proposition->hasSursis()) : ?>
                            <span class="icon icon-plus-sign"></span>
                            Accorder un sursis
                        <?php else : ?>
                            <span class="icon icon-minus"></span>
                            Retirer le sursis
                        <?php endif; ?>
                    </a>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>