<?php
/**
 * @var Proposition $proposition
 * @var ValidationThese[]|ValidationHDR[] $validations
 * @var boolean $canStructureValider
 * @var boolean $canStructureRevoquer
 * @var boolean $canPresidence
 * @var string $typeProposition
 */

use Application\Entity\Db\Role;
use These\Entity\Db\These;
use Validation\Entity\Db\ValidationHDR;
use Validation\Entity\Db\ValidationThese;
use Soutenance\Entity\Proposition;
use Soutenance\Entity\PropositionThese;
use Soutenance\Service\Horodatage\HorodatageService;

$object = $proposition->getObject();

$cssClass = "";
if($object instanceof These){
    // Rôles à valider
    $rolesToValidate = [
        Role::CODE_RESP_UR,
        Role::CODE_RESP_ED,
        Role::CODE_BDD,
    ];
}else{
    // Rôles à valider
    $rolesToValidate = [
        Role::CODE_RESP_UR,
        Role::CODE_GEST_HDR,
    ];
}

$validatedCount = 0;
foreach ($rolesToValidate as $roleCode) {
    if (!empty($validations[$roleCode])) {
        $validatedCount++;
    }
}

//Si tout n'est pas OK pour pour pouvoir valider
//ou si tout est OK pour pour pouvoir valider mais qu'aucune validation n'a encore été effectuée
if ($validatedCount === 0) {
    $cssClass = "bg-danger";
//Si tout est OK pour pour pouvoir valider et que le circuit de validations est déjà commencé
} elseif ($validatedCount < count($rolesToValidate)) {
    $cssClass = "bg-warning";
} else {
    $cssClass = "bg-success";
}
?>

<div id="BOXDIV_VALIDATIONS_STRUCTURES">
    <div class="box card">
        <div class="card-header <?php echo $cssClass; ?>">
            <?php if($object instanceof These): ?>
                <h2> Validation par les structures encadrant la thèse </h2>
            <?php else: ?>
                <h2> Validation par les structures encadrant l'HDR </h2>
            <?php endif; ?>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-8">
                    <h4>
                        Liste des validations
                    </h4>
                    <ul>
                        <li>
                            <?php if ($object->getUniteRecherche()) : ?>
                                <?php echo $object->getUniteRecherche()->getStructure()->getLibelle(); ?>  (Unité de recherche) <br/>
                            <?php endif; ?>
                            <?php if (isset($validations[Role::CODE_RESP_UR]) && $validations[Role::CODE_RESP_UR]) : ?>
                                <?php $validation = current($validations[Role::CODE_RESP_UR]); ?>
                                <span class="badge bg-success">
                                    <span class="icon icon-checked"></span>
                                    Validée
                                </span>
                                Le <?php echo $validation->getHistoModification()->format('d/m/Y à H:i'); ?>
                                par <?php echo $validation->getIndividu(); ?>
                            <?php else: ?>
                                <span class="badge bg-secondary"> Aucune validation</span>
                            <?php endif; ?>
                        </li>
                        <?php if($proposition instanceof PropositionThese): ?>
                            <li>
                                <?php if ($object->getEcoleDoctorale()) : ?>
                                    <?php echo $object->getEcoleDoctorale()->getStructure()->getLibelle(); ?>  (École Doctorale) <br/>
                                <?php else: ?>
                                    <strong style="color:darkred;">
                                        Aucune
                                        (École Doctorale)
                                    </strong>
                                    <br/>
                                <?php endif; ?>
                                <?php if (isset($validations[Role::CODE_RESP_ED]) && $validations[Role::CODE_RESP_ED]) : ?>
                                    <?php $validation = current($validations[Role::CODE_RESP_ED]); ?>
                                    <span class="badge bg-success">
                                        <span class="icon icon-checked"></span>
                                        Validée
                                    </span>
                                    Le <?php echo $validation->getHistoModification()->format('d/m/Y à H:i'); ?>
                                    par <?php echo $validation->getIndividu(); ?>
                                <?php else: ?>
                                    <span class="badge bg-secondary"> Aucune validation</span>
                                <?php endif; ?>
                            </li>
                            <li>
                                <?php echo $object->getEtablissement()->getStructure()->getLibelle(); ?>
                                (Signature de la proposition de soutenance par la direction de l'établissement) <br/>
                                <?php if (isset($validations[Role::CODE_BDD]) && $validations[Role::CODE_BDD]) : ?>
                                    <?php $validation = current($validations[Role::CODE_BDD]); ?>
                                    <span class="badge bg-success">
                                        <span class="icon icon-checked"></span>
                                        Validée
                                    </span>
                                    Le <?php echo $validation->getHistoModification()->format('d/m/Y à H:i'); ?>
                                    par <?php echo $validation->getIndividu(); ?>
                                <?php else: ?>
                                    <span class="badge bg-secondary"> Aucune validation</span>
                                <?php endif; ?>
                            </li>
                        <?php else: ?>
                            <li>
                                <?php echo $object->getEtablissement()->getStructure()->getLibelle(); ?>
                                (Signature de la proposition de soutenance par la direction de l'établissement) <br/>
                                <?php if (isset($validations[Role::CODE_GEST_HDR]) && $validations[Role::CODE_GEST_HDR]) : ?>
                                    <?php $validation = current($validations[Role::CODE_GEST_HDR]); ?>
                                    <span class="badge bg-success">
                                        <span class="icon icon-checked"></span>
                                        Validée
                                    </span>
                                    Le <?php echo $validation->getHistoModification()->format('d/m/Y à H:i'); ?>
                                    par <?php echo $validation->getIndividu(); ?>
                                <?php else: ?>
                                    <span class="badge bg-secondary"> Aucune validation</span>
                                <?php endif; ?>
                            </li>
                        <?php endif; ?>

                    </ul>
                </div>
                <div class="col-md-4">
                    <?php
                        $validationMDD = null;
                        if (isset($validations[Role::CODE_BDD]) && $validations[Role::CODE_BDD]) { $validationMDD = current($validations[Role::CODE_BDD]); }
                        if (isset($validations[Role::CODE_GEST_HDR]) && $validations[Role::CODE_GEST_HDR]) { $validationMDD = current($validations[Role::CODE_GEST_HDR]); }
                        if ($canPresidence /**AND $validationMDD === null*/): ?>
                        <p>
                            <a  <?php /** @see PropositionHDRController::signaturePresidenceAction() */ ?>
                                <?php /** @see PropositionTheseController::signaturePresidenceAction() */ ?>
                                href="<?php echo $this->url("soutenance_{$typeProposition}/proposition/signature-presidence", ['id' => $object->getId()], true); ?>"
                                class="btn btn-primary action"
                                target="_blank"
                            >
                                <span class="icon icon-pdf"></span>Générer document pour signature
                            </a>
                        </p>
                    <?php endif; ?>

                    <?php echo $this->horodatagesParType($proposition, HorodatageService::TYPE_EDITION, "Autorisation de soutenance"); ?>

                    <?php if ($canStructureValider): ?>
                        <p>
                            <a <?php /** @see PropositionHDRController::validerStructureAction() */ ?>
                                <?php /** @see PropositionTheseController::validerStructureAction() */ ?>
                               href="<?php echo $this->url("soutenance_{$typeProposition}/proposition/valider-structure", ['id' => $object->getId()], [], true); ?>"
                               class="btn btn-success action">
                                <span class="icon icon-ok"></span> Valider la proposition de soutenance
                            </a>
                        </p>
                        <p>
                            <a
                                <?php /** @see \Soutenance\Controller\PropositionController::refuserStructureAction(); */ ?>
                                href="<?php echo $this->url("soutenance_{$typeProposition}/proposition/refuser-structure", ['id' => $object->getId()], [], true); ?>"
                                class="btn btn-danger action ajax-modal"
                                data-event="refus-proposition">
                                <span class="icon icon-delete"></span> Refuser la proposition de soutenance
                            </a>
                        </p>
                    <?php endif; ?>

                    <?php if ($canStructureRevoquer): ?>
                        <p>
                            <a <?php /** @see PropositionTheseController::revoquerStructureAction(); */ ?>
                                <?php /** @see PropositionHDRController::revoquerStructureAction(); */ ?>
                                    href="<?php echo $this->url("soutenance_{$typeProposition}/proposition/revoquer-structure", ['id' => $object->getId()], [], true); ?>"
                                    class="btn btn-danger action ajax-modal" data-event="modification">
                                <span class="icon icon-unchecked"></span> Révoquer la validation
                            </a>
                        </p>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>
