<?php
/**
 * @var Proposition $proposition
 * @var Validation[][] $validations
 * @var Justificatif[] $attestationsIntegriteScientifique
 *
 * @var boolean $isOk
 * @var boolean $canValiderActeur
 * @var boolean $canSursis
 *

 * @var Doctorant $doctorant
 * @var Acteur[] $directeurs
 * @var Individu $currentIndividu
 * @var boolean $validationActeur
 *
 * @var bool $isInformationsOk
 */


use Soutenance\Entity\Etat;
use Soutenance\Entity\Justificatif;
use Soutenance\Service\Horodatage\HorodatageService;
use These\Entity\Db\Acteur;
use Doctorant\Entity\Db\Doctorant;
use Individu\Entity\Db\Individu;
use Application\Entity\Db\Role;
use Application\Entity\Db\Validation;
use Soutenance\Entity\Proposition;
use Soutenance\Provider\Validation\TypeValidation;

$these = $proposition->getThese();

$hasDeclaration= !empty($validations[TypeValidation::CODE_VALIDATION_DECLARATION_HONNEUR]);
$hasAttestation = !empty($attestationsIntegriteScientifique);
$hasSursis = $proposition->hasSursis();

$isDateOk = (new DateTime())->add(new DateInterval('P2M')) < $proposition->getDate() || $hasSursis;
$isAllOk = $hasDeclaration && $hasAttestation && $isDateOk && $isInformationsOk;
?>

<div class="box card">
    <div class="card-header bg-dark text-white">
        <h2>
            Validation de la proposition de soutenance
        </h2>
    </div>
    <div class="card-body">

        <?php if ($proposition->getEtat()->getCode() === Etat::EN_COURS && !$isAllOk) : ?>
         <div class="alert alert-danger">
            <strong>
                <span class="icon icon-attention"></span>
                Au moins une information ou validation est manquante ; ceci bloque la validation de votre proposition.
            </strong>
            <ul>
            <?php if (!$isInformationsOk) : ?>
                <li> Au moins une information sur la direction ou l'encadrement de la thèse est manquante. </li>
            <?php endif; ?>
            <?php if (!$isOk): ?>
                <li> La proposition de soutenance doit être recevable : date et lieu, composition du jury, ... </li>
            <?php endif; ?>
            <?php if (!$isDateOk): ?>
                <li> Le délai de deux mois entre la date de validation et la date de soutenance est non respecté </li>
            <?php endif; ?>
            <?php if (!$hasDeclaration) : ?>
                <li> La déclaration sur l'honneur de non-plagiat doit être validée avant de permettre la validation de la proposition. </li>
            <?php endif; ?>
            <?php if (!$hasAttestation) : ?>
                <li> L'attestation de suivi de la formation "Intégrité Scientifique" est manquante. </li>
            <?php endif; ?>
            </ul>
         </div>
        <?php endif; ?>

        <div class="row">
            <div class="col-md-8" >
                <h4>
                    Liste des validations
                </h4>
                <ul>
                        <!-- Validation du doctorant -->
                        <li>
                            <?php echo $doctorant->getIndividu(); ?>
                            <br/>
                            <?php if ($validations[Role::CODE_DOCTORANT]) : ?>
                                <?php $validation = current($validations[Role::CODE_DOCTORANT]); ?>
                                <span class="badge bg-success"> Validée</span>
                                Le <?php echo $validation->getHistoModification()->format('d/m/Y à H:i'); ?>
                            <?php else: ?>
                                <span class="badge bg-secondary"> Aucune validation</span>
                            <?php endif; ?>
                        </li>
                        <!-- Validation des directeurs -->
                        <?php $validationsDirecteurs = array_merge($validations[Role::CODE_DIRECTEUR_THESE], $validations[Role::CODE_CODIRECTEUR_THESE]); ?>
                        <?php foreach ($directeurs as $directeur): ?>
                            <?php $validation = current(array_filter($validationsDirecteurs, function (Validation $v) use ($directeur) { return $v->getIndividu()->getId() === $directeur->getIndividu()->getId();})); ?>
                            <li>
                                <?php echo $directeur->getIndividu(); ?>
                                (<?php echo $directeur->getRole()->getLibelle();?>)
                                <br/>
                                <?php if ($validation) : ?>
                                    <span class="badge bg-success"> Validée</span>
                                    Le <?php echo $validation->getHistoModification()->format('d/m/Y à H:i'); ?>
                                <?php else: ?>
                                    <span class="badge bg-secondary"> Aucune validation</span>
                                <?php endif; ?>
                            </li>
                        <?php endforeach; ?>
                </ul>
            </div>

            <div class="col-md-4" >
                <?php if ($canValiderActeur AND $isAllOk) : ?>
                        <a
                            <?php /** @see \Soutenance\Controller\PropositionController::validerActeurAction(); */ ?>
                            href="<?php echo $this->url('soutenance/proposition/valider', ['these' => $these->getId()], [], true); ?>"
                            class="btn btn-success action ">
                            <span class="icon icon-ok"></span>
                            Valider la proposition de soutenance
                        </a>
                <?php endif; ?>
            </div>
        </div>

        <?php if ($canSursis) : ?>
                <?php /** @see \Soutenance\Controller\PropositionController::toggleSursisAction() */ ?>
                <a href="<?php echo $this->url('soutenance/proposition/sursis', ['these' => $these->getId()], [], true); ?>" class="btn btn-primary action">
                    <?php if (!$proposition->hasSursis()) : ?>
                        <span class="icon icon-plus-sign"></span>
                        Accorder un sursis
                    <?php else : ?>
                        <span class="icon icon-minus"></span>
                        Retirer le sursis
                    <?php endif; ?>
                </a>

                <?php echo $this->dernierHorodatage($proposition, HorodatageService::TYPE_ETAT, "Sursis"); ?>
        <?php endif; ?>

    </div>
</div>
