<?php

use Application\View\Renderer\PhpRenderer;
use Depot\Entity\Db\Attestation;
use Depot\Form\Attestation\AttestationTheseForm;
use Depot\Provider\Privilege\DepotPrivileges;
use Fichier\Entity\Db\VersionFichier;
use These\Entity\Db\These;

/**
 * @var PhpRenderer          $this
 * @var These                $these
 * @var VersionFichier       $version
 * @var Attestation          $attestation
 * @var AttestationTheseForm $form
 * @var string               $modifierAttestationUrl
 * @var bool                 $resaisirAttestationsVersionCorrigee
 * @var bool                 $hasFichierThese
 *
 * @see \Depot\Controller\DepotController::attestationAction()
 */

$privilege = DepotPrivileges::THESE_SAISIE_ATTESTATIONS_($version);
$canEdit = $this->isAllowed($these, $privilege);
if ($version->estVersionCorrigee() && ! $resaisirAttestationsVersionCorrigee) {
    $canEdit = false;
}
?>

<div class="box card">

    <div class="card-header bg-dark text-white">
        <h2>
            Attestation
            <?php if ($attestation && $attestation->estCreationAuto() && !$resaisirAttestationsVersionCorrigee): ?>
                <span>(Rappel)</span>
            <?php endif ?>
        </h2>
    </div>

    <div class="card-body">
        <?php if ($hasFichierThese): ?>

            <?php if ($attestation): ?>
                <?php echo $this->partial('depot/depot/partial/attestation') ?>
                <?php
                // NB : modifier les réponses existantes aux attestations n'a pas de sens puisque ce sont des cases
                // qu'il faut obligatoirement cocher. (Par contre, elles peuvent être supprimées selon les réponses
                // au formulaire d'autorisation de diffusion.)
                // Donc théoriquement, le bouton "Modifier" ci-après n'apparaît jamais (cf. assertion), mais on le
                // laisse quand même, si un jour la logique change.
                if ($canEdit): ?>
                    <p><a href="<?php echo $modifierAttestationUrl ?>"
                          class="btn btn-secondary ajax-modal"
                          data-event="event-attestation-modified"><span class="icon icon-edit"></span> Modifier</a></p>
                <?php endif ?>
            <?php else: ?>
                <?php if ($canEdit): ?>
                    <p><a href="<?php echo $modifierAttestationUrl ?>"
                          class="btn btn-primary ajax-modal"
                          data-event="event-attestation-modified"><span class="icon icon-edit"></span> Compléter</a></p>
                <?php endif ?>
            <?php endif ?>

        <?php else: ?>

            <p>Vous devez d'abord téléverser la thèse au format PDF.</p>

        <?php endif ?>
    </div>
</div>

