<?php

use Application\View\Renderer\PhpRenderer;
use Depot\Provider\Privilege\DepotPrivileges;
use These\Entity\Db\These;

/**
 * Dépot de fichiers divers liés à une thèse.
 *
 * @var PhpRenderer $this
 * @var These $these
 * @var string $pvSoutenanceUrl
 * @var string $rapportSoutenanceUrl
 * @var string $preRapportSoutenanceUrl
 * @var string $demandeConfidentUrl
 * @var string $prolongConfidentUrl
 * @var string $convMiseEnLigneUrl
 * @var string $convMiseEnLigneAvenantUrl
 * @var string $charteDoctoratUrl
 * @var string $charteDoctoratAvenantUrl
 * @var string $convFormationDoctoraleUrl
 * @var string $convFormationDoctoraleAvenantUrl
 *
 * @see \Depot\Controller\DepotController::detailDepotDiversAction()
 */

?>

<?php $this->headTitle($this->translate("Fichiers divers"))
    ->prepend($these->getDoctorant()->getIndividu()->getNomUsuel()) ?>

<h1 class="page-header">
    <?php echo $this->translate("Dépôt de fichiers divers"); ?>
    <small><?php echo $this->partial('these/these/partial/titre') ?></small>
</h1>

<p class="lead">
    Cette page vous permet de téléverser/télécharger divers fichiers <strong>liés à la thèse</strong> de
    <?php echo $these->getDoctorant() ?>.
</p>

<?php if ($this->isAllowed($these, DepotPrivileges::THESE_FICHIER_DIVERS_CONSULTER)): ?>

    <h2>Charte</h2>

    <div class="row">
        <div class="col-md-4">
            <div id="charteDoctoratDiv" class="" data-url="<?php echo $charteDoctoratUrl ?>">
                <!-- màj via ajax -->
            </div>
        </div>

        <div class="col-md-4">
            <div id="charteDoctoratAvenantDiv" class="" data-url="<?php echo $charteDoctoratAvenantUrl ?>">
                <!-- màj via ajax -->
            </div>
        </div>
    </div>

    <h2>Confidentialité</h2>

    <div class="row">
        <div class="col-md-4">
            <div id="demandeConfidentDiv" class="" data-url="<?php echo $demandeConfidentUrl ?>">
                <!-- màj via ajax -->
            </div>
        </div>

        <div class="col-md-4">
            <div id="prolongConfidentDiv" class="" data-url="<?php echo $prolongConfidentUrl ?>">
                <!-- màj via ajax -->
            </div>
        </div>
    </div>

    <h2>Formation doctorale</h2>

    <div class="row">
        <div class="col-md-4">
            <div id="convFormationDoctoraleDiv" class="" data-url="<?php echo $convFormationDoctoraleUrl ?>">
                <!-- màj via ajax -->
            </div>
        </div>

        <div class="col-md-4">
            <div id="convFormationDoctoraleAvenantDiv" class="" data-url="<?php echo $convFormationDoctoraleAvenantUrl ?>">
                <!-- màj via ajax -->
            </div>
        </div>
    </div>

    <h2>Soutenance</h2>

    <div class="row">
        <div class="col-md-4">
            <div id="pvSoutenanceDiv" class="" data-url="<?php echo $pvSoutenanceUrl ?>">
                <!-- màj via ajax -->
            </div>
        </div>

        <div class="col-md-4">
            <div id="preRapportSoutenanceDiv" class="" data-url="<?php echo $preRapportSoutenanceUrl ?>">
                <!-- màj via ajax -->
            </div>
        </div>

        <div class="col-md-4">
            <div id="rapportSoutenanceDiv" class="" data-url="<?php echo $rapportSoutenanceUrl ?>">
                <!-- màj via ajax -->
            </div>
        </div>
    </div>

    <h2>Mise en ligne</h2>

    <div class="row">
        <div class="col-md-4">
            <div id="convMiseEnLigneDiv" class="" data-url="<?php echo $convMiseEnLigneUrl ?>">
                <!-- màj via ajax -->
            </div>
        </div>

        <div class="col-md-4">
            <div id="convMiseEnLigneAvenantDiv" class="" data-url="<?php echo $convMiseEnLigneAvenantUrl ?>">
                <!-- màj via ajax -->
            </div>
        </div>
    </div>
<?php endif ?>


<script>
    $(function () {
        var self = this;

        var loaderFactory = function (divName) {
            return function (done, effect) {
                return function () {
                    $("#" + divName).addClass("loading").refresh(null, function () {
                        $(this).removeClass("loading").show();
                        if (done) done();
                    });
                };
            };
        };

        var pvSoutenanceLoader = loaderFactory("pvSoutenanceDiv");
        var rapportSoutenanceLoader = loaderFactory("rapportSoutenanceDiv");
        var preRapportSoutenanceLoader = loaderFactory("preRapportSoutenanceDiv");

        var demandeConfidentLoader = loaderFactory("demandeConfidentDiv");
        var prolongConfidentLoader = loaderFactory("prolongConfidentDiv");

        var convMiseEnLigneLoader = loaderFactory("convMiseEnLigneDiv");
        var convMiseEnLigneAvenantLoader = loaderFactory("convMiseEnLigneAvenantDiv");

        var charteDoctoratLoader = loaderFactory("charteDoctoratDiv");
        var charteDoctoratAvenantLoader = loaderFactory("charteDoctoratAvenantDiv");

        var convFormationDoctoraleLoader = loaderFactory("convFormationDoctoraleDiv");
        var convFormationDoctoraleAvenantLoader = loaderFactory("convFormationDoctoraleAvenantDiv");

        // Au chargement de la page, on actualise les div
        runInCascade([
            charteDoctoratLoader,
            charteDoctoratAvenantLoader,

            demandeConfidentLoader,
            prolongConfidentLoader,

            convFormationDoctoraleLoader,
            convFormationDoctoraleAvenantLoader,

            pvSoutenanceLoader,
            preRapportSoutenanceLoader,
            rapportSoutenanceLoader,

            convMiseEnLigneLoader,
            convMiseEnLigneAvenantLoader,
        ], self);
    });
</script>