<?php

use Depot\Entity\Db\MetadonneeThese;
use These\Entity\Db\These;
use Depot\Filter\MotsClesFormatter;
use Depot\Form\RdvBuTheseForm;
use Depot\Provider\Privilege\DepotPrivileges;
use Application\View\Renderer\PhpRenderer;

/**
 * @var                $this PhpRenderer
 * @var These          $these
 * @var string         $title
 * @var \Depot\Form\RdvBuTheseForm $form
 * @var bool           $pageCouvValidee
 *
 * @method string formControlGroup()
 */

$canEditMotsClesRameau = $this->isAllowed(DepotPrivileges::getResourceId(DepotPrivileges::THESE_SAISIE_MOT_CLE_RAMEAU));

$motsClesFormatter = new MotsClesFormatter(['separator' => MetadonneeThese::SEPARATEUR_MOTS_CLES]);

$desc = $these->getMetadonnee();
$motsClesLibresFrancais = $desc ? $motsClesFormatter->filter($desc->getMotsClesLibresFrancais()) : "(Aucun)";
$motsClesLibresAnglais  = $desc ? $motsClesFormatter->filter($desc->getMotsClesLibresAnglais())  : "(Aucun)";

$fcg = $this->formControlGroup();
?>

<?php echo $this->form()->openTag($form->prepare()->setAttribute('class', 'rdv-bu')) ?>

<fieldset>
    <legend>Doctorant</legend>
    <div class="row">
        <div class="col-md-6">
            <?php echo $fcg($form->get('coordDoctorant')) ?>
        </div>
        <div class="col-md-6">
            <?php echo $fcg($form->get('dispoDoctorant')) ?>
        </div>
    </div>
</fieldset>

<fieldset>
    <legend>Bibliothèque universitaire</legend>

    <div class="row">
        <div class="col-md-6">
            <label for="" class="form-label">Conformité de la page de couverture</label><br/>
            <?php echo $fcg($form->get('pageTitreConforme')->setValue($pageCouvValidee)) ?>
            <label for="" class="form-label">Version en ligne et papier</label><br/>
            <?php echo $fcg($form->get('versionArchivableFournie')) ?>
            <?php echo $fcg($form->get('conventionMelSignee')) ?>
            <?php if ($form->has('exemplPapierFourni')): ?>
            <?php echo $fcg($form->get('exemplPapierFourni')) ?>
            <?php endif ?>
        </div>
        <div class="col-md-6">
            <?php echo $fcg($form->get('divers')->setAttribute('rows', 2)) ?>
            <?php echo $fcg($form->get('idOrcid')) ?>
            <?php echo $fcg($form->get('halId')) ?>
            <?php echo $fcg($form->get('nnt')) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <p>
                <label for="" class="form-label">Rappel des propositions de mots-clés en français :</label><br>
                <?php echo $motsClesLibresFrancais ?>
            </p>
        </div>
        <div class="col-md-6">
            <p>
                <label for="" class="form-label">Rappel des propositions de mots-clés en anglais :</label><br>
                <?php echo $motsClesLibresAnglais ?>
            </p>
        </div>
    </div>

    <?php
    $motsClesRameau = $form->get('motsClesRameau')->setAttribute('class', 'taggable');
    if (! $canEditMotsClesRameau) {
        $motsClesRameau->setAttribute('disabled', 'disabled');
    }
    echo $fcg()
        ->setHelpContent($motsClesRameau->getAttribute('title'))
        ->render($motsClesRameau);
    ?>
</fieldset>

<?php echo $this->formElement($form->get('submit')) ?>

<?php echo $this->form()->closeTag() ?>


<!--<link href="--><?php //echo $this->basePath('/css/jquery.tag-editor.css') ?><!--" rel="stylesheet" />-->
<!--<script src="--><?php //echo $this->basePath('/js/jquery.tag-editor.min.js') ?><!--"></script>-->

<script>
    $(function () {
        /**
         * Saisie des mots-clés comme des tags.
         *
         * @see https://goodies.pixabay.com/jquery/tag-editor/demo.html
         * @todo: tagEditor semble être le meilleur SAUF que l'attribut "disabled" n'est pas supporté!
         */
//        $("input.taggable").tagEditor({
//            delimiter: ';'
//        });
    });
</script>