<?php

use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var array       $config
 * Exemple :
 [
    "État" => [
        'paramName' => 'etatThese',
        'paramConfig' => [
            ['value' => '', 'label' => "Tous"],
            ['value' => $v = These::ETAT_EN_COURS, 'label' => These::$etatsLibelles[$v]],
            ['value' => $v = These::ETAT_ABANDONNEE, 'label' => These::$etatsLibelles[$v]],
            ['value' => $v = These::ETAT_SOUTENUE, 'label' => These::$etatsLibelles[$v]],
        ],
        'filterUrl' => function ($param, $value, $queryParams) {
            $queryParams[$param] = $value;
            return $this->url('these/rechercher', [], ['query' => $queryParams], true);
        },
    ],
 ]
 *
 */

$titre = "Filtres";
if (isset($config)) {
    $value = null;
    if (isset(current($config)['titre'])) $value = current($config)['titre'];
    if ($value) $titre = $value;
}
?>

<div class="card filters">
    <div class="card-header bg-secondary">
        <span class="icon icon-filter"></span> <?php echo $titre; ?>
    </div>
    <table class="table table-bordered">
        <?php foreach ($config as $label => $data): ?>
        <tr>
            <th>
                <?php if ($titre === "Filtres") echo $label; ?>
            </th>
            <td>
                <?php $data['queryParams'] = $this->queryParams(); ?>
                <?php echo $this->partial('filter-form-item', $data) ?>
            </td>
        </tr>
        <?php endforeach ?>
    </table>
</div>