<?php

use Application\Assertion\BaseAssertion;
use Application\Constants;
use These\Entity\Db\These;
use Application\Entity\Db\TypeValidation;
use Application\Entity\Db\Utilisateur;
use Application\Entity\Db\Validation;
use Depot\Entity\Db\VSitu\DepotVersionCorrigeeValidationPresident;
use Depot\Provider\Privilege\ValidationPrivileges;
use Application\View\Renderer\PhpRenderer;

/**
 * @see \Depot\Controller\ValidationController::validationCorrectionTheseAction()
 * @var PhpRenderer                               $this
 * @var These                                     $these
 * @var string                                    $validerUrl
 * @var string                                    $devaliderUrl
 * @var TypeValidation                            $typeValidation
 * @var Validation[]                              $validations
 * @var DepotVersionCorrigeeValidationPresident[] $attendues
 * @var Utilisateur[]                             $utilisateurs
 */

$canValidate = $this->isAllowed($these, ValidationPrivileges::VALIDATION_CORRECTION_THESE);
$canUnvalidate = $this->isAllowed($these, ValidationPrivileges::VALIDATION_CORRECTION_THESE_SUPPR);
?>

<div class="card box">
    <div class="card-header bg-dark text-white">
        <h2><?php echo $typeValidation ?></h2>
    </div>
    <div class="card-body">

        <?php if (count($validations)): ?>
            <ul class="validation">
            <?php foreach ($validations as $validation): ?>
                <li>
                    <?php echo $validation->getIndividu() ?> a validé le
                    <?php echo $validation->getHistoModification()->format(Constants::DATETIME_FORMAT) ?>.
                </li>
            <?php endforeach ?>
            </ul>
        <?php endif ?>

        <?php if (count($attendues)): ?>
            <ul class="validation-attendue">
            <?php foreach ($attendues as $validation): ?>
                <li>
                    <?php echo $i = $validation->getIndividu() ?> n'a pas encore validé.
                    <?php if (! $i->getSupannId()): ?>
                        <?php if (empty($utilisateurs[$i->getId()])) : ?>
                            <?php
                            $message = sprintf(
                                "Cette personne ne possèdent aucune adresse électronique connue par l'application. <br/>
                                        &nbsp; &nbsp;&nbsp;&nbsp;
                                        L'école doctorale a été notifiée du souci et va pouvoir associer un compte au Président de jury.",
                                $validation->getIndividu()->getSource(),
                                $validation->getIndividu()->getSourceCode());
                            ?>
                            <p class="text-danger"><small><span class="fas fa-exclamation-triangle"></span> <?php echo $message ?></small></p>
                        <?php else: ?>
                            <p class="text-warning"><small>
                                    <span class="fas fa-info-circle"></span>
                                    Cet utilisateur utilise un compte local
                            </small></p>
                        <?php endif; ?>
                    <?php elseif (! $i->getEmailPro()): ?>
                        <?php
                        $message = sprintf(
                            "L'application n'a pas pu notifier cette personne car son email n'est pas connu dans %s (source code '%s').",
                            $validation->getIndividu()->getSource(),
                            $validation->getIndividu()->getSourceCode());
                        ?>
                        <p class="text-danger"><small><span class="fas fa-exclamation-triangle"></span> <?php echo $message ?></small></p>
                    <?php endif ?>
                </li>
            <?php endforeach ?>
            </ul>
        <?php endif ?>

        <?php if ($canValidate): ?>
            <a href="<?php echo $validerUrl ?>"
               class="btn btn-success ajax-modal"
               data-event="event-validation-correction-these"><span class="fas fa-thumbs-up"></span> Valider</a>
        <?php endif ?>
        <?php if ($canUnvalidate): ?>
            <br>
            <a href="<?php echo $devaliderUrl ?>"
               class="btn btn-danger ajax-modal"
               data-event="event-validation-correction-these"><span class="icon icon-delete"></span> Annuler la validation</a>
        <?php endif ?>

        <?php
        $msgCollector = $this->messageCollector(BaseAssertion::class);
        $msgCollector->getMessengerHelper()->setContainerClassesToAdd('alert-sm');
        echo $msgCollector->render();
        ?>
    </div>
</div>


<?php echo $this->messenger()
    ->setContainerClassesToAdd('alert-md')
    ->addMessagesFromFlashMessengerWithNamespace($typeValidation->getCode() . '/*') ?>