<?php

use Application\Assertion\BaseAssertion;
use Application\Constants;
use Validation\Entity\Db\TypeValidation;
use Validation\Entity\Db\ValidationThese;
use Application\View\Renderer\PhpRenderer;
use Depot\Provider\Privilege\ValidationPrivileges;
use These\Entity\Db\These;

/**
 * @var PhpRenderer      $this
 * @var These            $these
 * @var string           $validerUrl
 * @var string           $devaliderUrl
 * @var TypeValidation   $typeValidation
 * @var ValidationThese|null  $validation
 */

$canValidate = $this->isAllowed($these, ValidationPrivileges::VALIDATION_DEPOT_THESE_CORRIGEE);
$canUnvalidate = $this->isAllowed($these, ValidationPrivileges::VALIDATION_DEPOT_THESE_CORRIGEE_SUPPR);
?>

<div class="card box">
    <div class="card-header bg-dark text-white">
        <h2 class="first"><?php echo $typeValidation ?></h2>
    </div>
    <div class="card-body">

        <?php if ($validation): ?>
            <ul class="validation">
                <li>
                    <?php echo $validation->getHistoModificateur()->getDisplayName() ?> a validé le
                    <?php echo $validation->getHistoModification()->format(Constants::DATETIME_FORMAT) ?>.
                </li>
            </ul>
            <?php if ($canUnvalidate): ?>
                <a href="<?php echo $devaliderUrl ?>"
                   class="btn btn-danger ajax-modal"
                   data-bs-toggle="tooltip"
                   data-bs-html="true"
                   title="Une confirmation avant l'annulation vous sera demandée"
                   data-event="event-validation-depot-these-corrigee"><span class="icon icon-delete"></span> Annuler la validation</a>
            <?php endif ?>
        <?php else: ?>
            <ul class="validation-attendue">
                <li>
                    <?php echo $these->getDoctorant() ?> n'a pas encore validé.
                </li>
            </ul>
            <?php if ($canValidate): ?>
                <a href="<?php echo $validerUrl ?>"
                   class="btn btn-success ajax-modal"
                   data-event="event-validation-depot-these-corrigee"><span class="fas fa-thumbs-up"></span> Valider</a>
            <?php endif ?>
        <?php endif ?>

        <?php
        $msgCollector = $this->messageCollector(BaseAssertion::class);
        $msgCollector->getMessengerHelper()->setContainerClassesToAdd('alert-sm');
        // --> Désactiver car le message est perturbant <--
        //echo $msgCollector->render();
        ?>
    </div>
</div>


<?php echo $this->messenger()
    ->setContainerClassesToAdd('alert-md')
    ->addMessagesFromFlashMessengerWithNamespace($typeValidation->getCode() . '/*') ?>