<?php
/**
 * @see \Soutenance\Controller\EngagementImpartialiteController::presenterNoAuthAction()
 *
 * @var bool $valide (booleen retour après la vérification de la clef fournir pour un acteur)
 *
 * @var These $these
 * @var Proposition $proposition
 * @var Membre $membre
 * @var Validation $validation
 * @var Acteur[] $encadrants
 * @var string $urlSigner
 * @var string $urlRefuser
 */

use Application\Entity\Db\Acteur;
use Application\Entity\Db\These;
use Application\Entity\Db\TypeValidation;
use Application\Entity\Db\Validation;
use Soutenance\Entity\Membre;
use Soutenance\Entity\Proposition;

/**
 * La validation CODE_ENGAGEMENT_IMPARTIALITE fait office de signature électronique de l'engagement d'impartilité. Par
 * conséquent :
 *  - seul le rapporteur connecté peut valider ce formulaire car elle l'engage lui personnellement ;
 *  - seule la maison du doctorat de l'établissement d'encadrement peut invalider cette signature.
 */

$doctorantNom = $these->getDoctorant()->getIndividu();
$this->headTitle("Engagement d'impartialité portant sur la thèse de ".$doctorantNom);
?>

<h1 class="page-header">
    Engagement d'impartialité / Impartiality commitment
</h1>

<p>
    Engagement d'impartialité en rapport à la thèse suivante :
</p>

<?php if (!$valide) : ?>
    <div class="alert alert-danger lead">

        <p>
            La clef fournie n'a pas permis d'établir le lien avec la soutenance.
            Veuillez contacté la direction de la thèse afin de remonter le problème.
        </p>

        <p>
            The provided token did not allowed to establish the link with the thesis.
            Please contact the thesis direction to signal this issue.
        </p>
    </div>
<?php else : ?>
<div>
    <div class="box panel panel-info">
        <div class="panel-heading">
            <h2 class="first"> Information sur la thèse / Information about the PhD thesis </h2>
        </div>
        <div class="panel-body">
            <dl class="dl-horizontal infos">
                <dt> Titre / Title </dt>
                <dd> <?php echo $these->getTitre(); ?> </dd>
                <dt> Doctorant / PhD Student</dt>
                <dd> <?php echo $doctorantNom; ?> </dd>
                <dt> Directeur(s) / Supervisor(s) </dt>
                <dd>
                    <?php foreach ($encadrants as $encadrant): ?>
                        <?php
                        /** @var Acteur $encadrant */
                        echo $encadrant->getIndividu();
                        ?>
                        <br/>
                    <?php endforeach; ?>
                <dt> Discipline </dt>
                <dd> <?php echo $these->getLibelleDiscipline(); ?> </dd>
                <dt> Date de la soutenance </dt>
                <dd> <?php echo $proposition->getDate()->format("d/m/Y"); ?> </dd>
                <dt> Lieu de la soutenance </dt>
                <dd> <?php echo $proposition->getLieu(); ?> </dd>
            </dl>

        </div>
    </div>
</div>

<p>
    En signant cet engagment d'impartialité, je, sous-signé <strong><?php echo $membre->getIndividu(); ?></strong>,
    atteste ne pas avoir de liens d'intérêt, qu'ils soient de nature professionnelle, familiale, personnelle ou patrimoniale
    avec le doctorant ou son directeur de thèse, ne pas avoir pris part aux travaux de la thèse et ne pas avoir de publication
    cosignée avec le doctorant dans les cinq dernières années et ne pas avoir participer au comité de suivi de la thèse de
    <?php echo $these->getDoctorant()->getIndividu(); ?>.
</p>
<p>
    By signing, I certify that I have no personal or family connection with the doctoral student or his/her PhD supervisor
    and that I have not taken part in the work of the thesis and not co-authored  publications with the doctoral student for
    the last five years.
</p>
<div class="row">
    <div class="col-md-4">
    <p>
        <span style="text-align: center">
        <a      <?php /** @see \Soutenance\Controller\EngagementImpartialiteController::signerEngagementImpartialiteAction()  */ ?>
                href="<?php echo $urlSigner;  ?>"
                class="btn btn-success" style="width:80%;">
            <span class="glyphicon glyphicon-thumbs-up"></span>
            Je signe / I agree </a>

            <br/>
            <br/>

        <a      <?php /** @see \Soutenance\Controller\EngagementImpartialiteController::refuserEngagementImpartialiteAction()  */ ?>
                href="<?php echo $urlRefuser;  ?>" class="btn btn-danger" style="width:80%;">
            <span class="glyphicon glyphicon-thumbs-down"></span>
            Je ne signe pas / I disagree </a>
        </span>
    </p>
    </div>
    <div class="col-md-8">
        <!-- affichage -->
        <?php if ($validation): ?>
        <div class="panel
            <?php  if ($validation->getTypeValidation()->getCode() === TypeValidation::CODE_ENGAGEMENT_IMPARTIALITE): ?>
                panel-success
            <?php else : ?>
                panel-danger
            <?php endif; ?>
        ">
            <div class="panel-heading">
                <?php echo $this->validation($validation) ?>
            </div>
        </div>
        <?php else: ?>
            <div class="panel panel-warning">
                <div class="panel-heading">
                    Aucune signature.
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>

<?php if ($validation AND $validation->getTypeValidation()->getCode() === TypeValidation::CODE_ENGAGEMENT_IMPARTIALITE): ?>
<div class="box panel panel-success">
    <div class="panel-heading">
        <h2 class="first"> Et ensuite ? </h2>
    </div>
    <div class="panel-body">

        Vous pouvez maintenant accéder à la partie de remise de votre avis de soutenance et dépôt du pré-rapport de soutenance.
        <nav aria-label="Etape suivante">
            <ul class="roadmap pagination">
            <li>
                <a
                        <?php /** @see \Soutenance\Controller\AvisController::indexAction()  */ ?>
                        class="roadmap-step-link"
                        href="<?php echo $this->url('soutenance/avis-soutenance', ['these' => $these->getId(), 'rapporteur' => $membre->getId()], [], true); ?>">
                    <span class="glyphicon glyphicon-circle-arrow-right"></span>
                        Avis de soutenance
                </a>
            </li>
            </ul>
        </nav>
    </div>
</div>
<?php endif; ?>

<?php endif; ?>


<style>
    dl.infos > dt {
        width:20rem;
        margin-right: 1rem;
    }
</style>