<?php

use Structure\Entity\Db\Etablissement;
use Structure\Provider\Privilege\StructurePrivileges;
use Structure\Provider\Privilege\SubstitutionPrivileges;

/**
 * @var Etablissement[] $etablissementsSygal
 * @var Etablissement[] $etablissementsExternes
 *
 * @see \Application\Controller\EtablissementController::indexAction()
 */

$appName = $this->appInfos()->nom;

$canModifier = $this->isAllowed(StructurePrivileges::getResourceId(StructurePrivileges::STRUCTURE_MODIFICATION_TOUTES_STRUCTURES));
$canAjouter = $this->isAllowed(StructurePrivileges::getResourceId(StructurePrivileges::STRUCTURE_MODIFICATION_TOUTES_STRUCTURES));
$canSubstituer = $this->isAllowed(SubstitutionPrivileges::getResourceId(SubstitutionPrivileges::SUBSTITUTION_CONSULTATION_TOUTES_STRUCTURES))
    OR $this->isAllowed(SubstitutionPrivileges::getResourceId(SubstitutionPrivileges::SUBSTITUTION_CONSULTATION_SA_STRUCTURE));
?>


<?php $this->headTitle($this->translate("Établissements")) ?>

<h1 class="page-header first">
    <?php echo $this->translate("Établissements") ?>
    <span class="badge bg-secondary">
        <?php echo count($etablissementsSygal) + count($etablissementsExternes); ?>
    </span>
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace() ?>

<?php if ($canModifier): ?>

    <a href="<?php echo $this->url('etablissement/ajouter', [], [], true) ?>"
       class="btn btn-primary"
       title="<?php echo $this->translate("Créer un nouvel établissement");?>">
        <span class="icon icon-plus"></span>
        <?php echo $this->translate("Ajouter un nouvel établissement");?>
    </a>
<?php endif ?>

<h2>
    Établissements participant à <?php echo $appName ?>
    <span class="badge bg-secondary">
        <?php echo count($etablissementsSygal); ?>
    </span>
</h2>

<div>
    <table class="table table-sm">
        <thead>
        <tr>
            <th> Libellé </th>
            <th> Source </th>
            <th> Code </th>
            <th> Sigle </th>
            <th> Actions </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($etablissementsSygal as $etablissement): ?>

            <?php
            $historisee = (!$etablissement->estNonHistorise());
            $hasSousStructure = !($etablissement->getStructure()->getStructuresSubstituees()->isEmpty());
            $canModifierCetEtab = $this->isAllowed($etablissement->getStructure(),StructurePrivileges::STRUCTURE_MODIFICATION_SES_STRUCTURES);
            ?>

            <tr>
                <td>
                    <a href="<?php echo $this->url('etablissement/information', ['structure' => $etablissement->getStructure()->getId()], [], true); ?>">
                        <?php echo $etablissement->getLibelle(); ?>
                        <?php if ($etablissement->getStructure()->estFermee()) : ?>
                            &nbsp;<span class="badge bg-danger">Structure fermée</span>
                        <?php endif; ?>
                    </a>
                    <?php if ($etablissement->estMembre()): ?>
                        <span class="badge bg-primary">Membre</span>
                    <?php endif ?>
                    <?php if ($etablissement->estAssocie()): ?>
                        <span class="badge bg-info">Associé</span>
                    <?php endif ?>
                    <?php if ($etablissement->estInscription()): ?>
                        <span class="badge bg-warning">Inscription</span>
                    <?php endif ?>
                </td>
                <td>
                    <?php echo $etablissement->getSource(); ?>
                </td>
                <td>
                    <?php echo $etablissement->getStructure()->getCode(); ?>
                </td>
                <td> <?php echo $etablissement->getSigle(); ?> </td>
                <td>
                    <?php if (($canModifier OR $canModifierCetEtab) && !$historisee) : ?>
                        <a href="<?php echo $this->url('etablissement/supprimer', ["structure" => $etablissement->getStructure()->getId()], [], true); ?>"
                           title="Historiser l'établissement">
                            <span class="icon icon-delete iconly"></span>
                        </a>
                    <?php endif; ?>

                    <?php if ($canSubstituer && !$historisee && $hasSousStructure) : ?>
                        <a href="<?php echo $this->url('substitution-modifier', ['cible' => $etablissement->getStructure()->getId(), [], true]); ?>"
                           title="Historiser l'établissement">
                            <span class="fas fa-link" title="Éditer la substitution"></span>
                        </a>
                    <?php endif; ?>

                    <?php if (($canModifier OR $canModifierCetEtab) && $historisee) : ?>
                        <a href="<?php echo $this->url('etablissement/restaurer', ["structure" => $etablissement->getStructure()->getId()], [], true); ?>"
                           title="Restaurer l'établissement">
                            Restaurer
                        </a>
                    <?php endif; ?>
                </td>
            </tr>

        <?php endforeach; ?>

        </tbody>
    </table>
</div>

<h2>
    Autres établissements
    <span class="badge bg-secondary">
        <?php echo count($etablissementsExternes); ?>
    </span>
</h2>

<div>
    <table class="table table-sm">
        <thead>
        <tr>
            <th> Libellé </th>
            <th> Source </th>
            <th> Code </th>
            <th> Sigle </th>
            <th> Actions </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($etablissementsExternes as $etablissement): ?>

            <?php
            $historisee = (!$etablissement->estNonHistorise());
            $hasSousStructure = !($etablissement->getStructure()->getStructuresSubstituees()->isEmpty());
            $canModifierCetEtab = $this->isAllowed($etablissement->getStructure(),StructurePrivileges::STRUCTURE_MODIFICATION_SES_STRUCTURES);
            ?>

            <tr>
                <td>
                    <a href="<?php echo $this->url('etablissement/information', ['structure' => $etablissement->getStructure()->getId()], [], true); ?>">
                        <?php echo $etablissement->getLibelle(); ?>
                    </a>
                    <?php if ($etablissement->estMembre()): ?>
                        <span class="badge bg-primary">Membre</span>
                    <?php endif ?>
                    <?php if ($etablissement->estAssocie()): ?>
                        <span class="badge bg-info">Associé</span>
                    <?php endif ?>
                </td>
                <td>
                    <?php echo $etablissement->getSource(); ?>
                </td>
                <td>
                    <?php echo $etablissement->getStructure()->getCode(); ?>
                </td>
                <td> <?php echo $etablissement->getSigle(); ?> </td>
                <td>
                    <?php if (($canModifier OR $canModifierCetEtab) && !$historisee) : ?>
                        <a href="<?php echo $this->url('etablissement/supprimer', ["structure" => $etablissement->getStructure()->getId()], [], true); ?>"
                           title="Historiser l'établissement">
                            <span class="icon icon-delete iconly"></span>
                        </a>
                    <?php endif; ?>

                    <?php if (($canModifier OR $canModifierCetEtab) && !$historisee && $hasSousStructure) : ?>
                        <a href="<?php echo $this->url('substitution-modifier', ['cible' => $etablissement->getStructure()->getId(), [], true]); ?>"
                           title="Historiser l'établissement">
                            <span class="fas fa-link" title="Éditer la substitution"></span>
                        </a>
                    <?php endif; ?>

                    <?php if (($canModifier OR $canModifierCetEtab) && $historisee) : ?>
                        <a href="<?php echo $this->url('etablissement/restaurer', ["structure" => $etablissement->getStructure()->getId()], [], true); ?>"
                           title="Restaurer l'établissement">
                            Restaurer
                        </a>
                    <?php endif; ?>
                </td>
            </tr>

        <?php endforeach; ?>

        </tbody>
    </table>
</div>