<?php

use Structure\Entity\Db\Etablissement;
use Structure\Provider\Privilege\StructurePrivileges;

/**
 * @var Etablissement[] $etablissementsMembres
 * @var Etablissement[] $etablissementsCeds
 * @var Etablissement[] $etablissementsAutres
 *
 * @see \Structure\Controller\EtablissementController::indexAction()
 */

$appName = $this->appInfos()->nom;

$canModifier = $this->isAllowed(StructurePrivileges::getResourceId(StructurePrivileges::STRUCTURE_MODIFICATION_TOUTES_STRUCTURES));
$canAjouter = $this->isAllowed(StructurePrivileges::getResourceId(StructurePrivileges::STRUCTURE_MODIFICATION_TOUTES_STRUCTURES));
?>


<?php $this->headTitle($this->translate("Établissements")) ?>

<?php if ($canModifier): ?>
    <div class="dropdown float-end">
        <a class="btn btn-primary dropdown-toggle" href="#"
           role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
            <?php echo $this->translate("Ajouter un nouvel établissement") ?>
        </a>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <li><a class="dropdown-item"
                   href="<?php echo $this->url('etablissement/ajouter', ['type' => Etablissement::TYPE_INSCRIPTION], [], true) ?>">
                    <?php echo $this->translate("Établissement d'inscription") ?></a></li>
            <li><a class="dropdown-item"
                   href="<?php echo $this->url('etablissement/ajouter', ['type' => Etablissement::TYPE_COLLEGE_ED], [], true) ?>">
                    <?php echo $this->translate("Collège des écoles doctorales") ?></a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item"
                   href="<?php echo $this->url('etablissement/ajouter', ['type' => Etablissement::TYPE_AUTRE], [], true) ?>">
                    Autre type d'établissement</a></li>
        </ul>
    </div>
<?php endif ?>

<h1 class="page-header first">
    <?php echo $this->translate("Établissements") ?>
    <span class="badge bg-secondary">
        <?php echo count($etablissementsMembres) + count($etablissementsAutres); ?>
    </span>
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace() ?>

<h2>
    Établissements membres
    <span class="badge bg-secondary">
        <?php echo count($etablissementsMembres); ?>
    </span>
</h2>

<div>
    <table class="table table-sm">
        <thead>
        <tr>
            <th> Libellé </th>
            <th> </th>
            <th> Source </th>
            <th> Source Code </th>
            <th> Code UAI </th>
            <th> Sigle </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($etablissementsMembres as $etablissement): ?>
            <tr>
                <td>
                    <a href="<?php echo $this->url('etablissement/voir', ['etablissement' => $etablissement->getId()], [], true); ?>">
                        <?php echo $etablissement->getStructure()->getLibelle(); ?>
                    </a>
                </td>
                <td>
                    <?php if ($etablissement->getStructure()->estFermee()) : ?>
                        &nbsp;<span class="badge bg-danger">Structure fermée</span>
                    <?php endif; ?>
                    <?php if ($etablissement->estMembre()): ?>
                        <span class="badge bg-primary" title="Établissement membre">Membre</span>
                    <?php endif ?>
                    <?php if ($etablissement->estAssocie()): ?>
                        <span class="badge bg-info" title="Établissement associé">Associé</span>
                    <?php endif ?>
                    <?php if ($etablissement->estInscription()): ?>
                        <span class="badge bg-warning" title="Établissement d'inscription">Inscription</span>
                    <?php endif ?>
                </td>
                <td>
                    <?php echo $etablissement->getSource(); ?>
                    <?php if ($etablissement->estSubstituant()) : ?>
                        <a href="<?php echo $this->url('substitution/substitution/voir', ['type' => \Substitution\Constants::TYPE_etablissement, 'id' => $etablissement->getId()]) ?>"
                           title="Accéder aux détails de cette substitution">
                            <span class="badge bg-light text-info" title="Cet enregistrement substitue d'autres enregistrements, cliquez pour en savoir plus...">Substitution</span></a>
                    <?php endif; ?>
                </td>
                <td>
                    <code><?php echo $etablissement->getSourceCode(); ?></code>
                </td>
                <td>
                    <?php echo $etablissement->getStructure()->getCode(); ?>
                </td>
                <td> <?php echo $etablissement->getStructure()->getSigle(); ?> </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>


<h2>
    Collège des écoles doctorales
</h2>

<div>
    <?php if ($etablissementsCeds): ?>
    <table class="table table-sm">
        <thead>
        <tr>
            <th> Libellé </th>
            <th> Source </th>
            <th> Source Code </th>
            <th> Code </th>
            <th> Sigle </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($etablissementsCeds as $etablissement): ?>
            <tr>
                <td>
                    <a href="<?php echo $this->url('etablissement/voir', ['etablissement' => $etablissement->getId()], [], true); ?>">
                        <?php echo $etablissement->getStructure()->getLibelle(); ?>
                    </a>
                    <?php if ($etablissement->estSubstituant()) : ?>
                        <a href="<?php echo $this->url('substitution/substitution/voir', ['type' => \Substitution\Constants::TYPE_etablissement, 'id' => $etablissement->getId()]) ?>"
                           title="Accéder aux détails de cette substitution">
                            <span class="badge bg-info" title="Cet enregistrement substitue d'autres enregistrements">S</span></a>
                    <?php endif; ?>
                    <?php if ($etablissement->estMembre()): ?>
                        <span class="badge bg-primary">Membre</span>
                    <?php endif ?>
                    <?php if ($etablissement->estAssocie()): ?>
                        <span class="badge bg-info">Associé</span>
                    <?php endif ?>
                </td>
                <td>
                    <?php echo $etablissement->getSource(); ?>
                </td>
                <td>
                    <code><?php echo $etablissement->getSourceCode(); ?></code>
                </td>
                <td>
                    <?php echo $etablissement->getStructure()->getCode(); ?>
                </td>
                <td> <?php echo $etablissement->getStructure()->getSigle(); ?> </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?php else: ?>
    Aucun
    <?php endif; ?>
</div>


<h2>
    Autres établissements
    <span class="badge bg-secondary">
        <?php echo count($etablissementsAutres); ?>
    </span>
</h2>

<div>
    <table class="table table-sm">
        <thead>
        <tr>
            <th> Libellé </th>
            <th> Source </th>
            <th> Code </th>
            <th> Sigle </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($etablissementsAutres as $etablissement): ?>
            <tr>
                <td>
                    <a href="<?php echo $this->url('etablissement/voir', ['etablissement' => $etablissement->getId()], [], true); ?>">
                        <?php echo $etablissement->getStructure()->getLibelle(); ?>
                    </a>
                    <?php if ($etablissement->estSubstituant()) : ?>
                        <a href="<?php echo $this->url('substitution/substitution/voir', ['type' => \Substitution\Constants::TYPE_etablissement, 'id' => $etablissement->getId()]) ?>"
                           title="Accéder aux détails de cette substitution">
                            <span class="badge bg-info" title="Cet enregistrement substitue d'autres enregistrements">S</span></a>
                    <?php endif; ?>
                    <?php if ($etablissement->estMembre()): ?>
                        <span class="badge bg-primary">Membre</span>
                    <?php endif ?>
                    <?php if ($etablissement->estAssocie()): ?>
                        <span class="badge bg-info">Associé</span>
                    <?php endif ?>
                </td>
                <td>
                    <?php echo $etablissement->getSource(); ?>
                </td>
                <td>
                    <?php echo $etablissement->getStructure()->getCode(); ?>
                </td>
                <td> <?php echo $etablissement->getStructure()->getSigle(); ?> </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>