<?php

/**
 * @see \Structure\Controller\EtablissementController::informationAction()
 * @var \Application\View\Renderer\PhpRenderer $this
 * @var Etablissement $etablissement
 * @var array $roleListing (string => int)
 * @var array $individuListing (string => string[])
 * @var string $logoContent
 * @var string $signatureConvocation
 * @var string[] $contenusFichiers
 * @var \Application\Entity\Db\Variable[] $variables
 */

use Individu\Provider\Privilege\IndividuPrivileges;
use Structure\Controller\StructureController;
use Structure\Entity\Db\Etablissement;
use Structure\Entity\Db\TypeStructure;
use Structure\Provider\Privilege\StructurePrivileges;
use UnicaenPrivilege\Provider\Privilege\Privileges;

$this->headTitle("Établissement '{$etablissement->getStructure()->getLibelle()}'");

$canAddRole = true;
$canModifierEtablissement = $this->isAllowed(StructurePrivileges::getResourceId(StructurePrivileges::STRUCTURE_MODIFICATION_TOUTES_STRUCTURES));
$canModifierCetEtab = !$etablissement->getSource()->getImportable() &&
    $this->isAllowed($etablissement->getStructure(),StructurePrivileges::STRUCTURE_MODIFICATION_SES_STRUCTURES);

$historisee = !$etablissement->estNonHistorise();

$tab = $this->queryParams()['tab'] ?? StructureController::TAB_infos;
?>

<h1 class="page-header">
    <?php if ($etablissement->estInscription()): ?>
        Établissement d'inscription &laquo; <?php echo $etablissement ?> &raquo;
    <?php elseif ($etablissement->estCed()): ?>
        Collège des Écoles Doctorales
    <?php else: ?>
        Établissement &laquo; <?php echo $etablissement ?> &raquo;
    <?php endif ?>
</h1>


<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace() ?>


<ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="nav-item">
        <a class="nav-link <?php echo $tab === StructureController::TAB_infos ? 'active' : '' ?>"
           href="<?php echo $this->url('etablissement/voir', ['etablissement' => $etablissement->getId()], ['query' => ['tab' => StructureController::TAB_infos]], true) ?>"
           role="tab"
           aria-controls="informations"
        >
            Informations générales
        </a>
    </li>
    <li role="presentation" class="nav-item">
        <a class="nav-link <?php echo $tab === StructureController::TAB_membres ? 'active' : '' ?>"
           href="<?php echo $this->url('etablissement/voir', ['etablissement' => $etablissement->getId()], ['query' => ['tab' => StructureController::TAB_membres]], true) ?>"
           role="tab"
           aria-controls="membres"
        >
            Rôles et membres
        </a>
    </li>
    <?php if ($etablissement->estInscription()) : ?>
        <li role="presentation" class="nav-item">
            <a class="nav-link <?php echo $tab === StructureController::TAB_docs ? 'active' : '' ?>"
               href="<?php echo $this->url('etablissement/voir', ['etablissement' => $etablissement->getId()], ['query' => ['tab' => StructureController::TAB_docs]], true) ?>"
               role="tab"
               aria-controls="documents"
            >
                Documents
            </a>
        </li>
    <?php endif; ?>
    <li role="presentation" class="nav-item">
        <a class="nav-link <?php echo $tab === StructureController::TAB_variables ? 'active' : '' ?>"
           href="<?php echo $this->url('etablissement/voir', ['etablissement'=> $etablissement->getId()], ['query' => ['tab' => StructureController::TAB_variables]], true); ?>"
           role="tab"
           aria-controls="variables"
        >
            Variables
        </a>
    </li>
</ul>



<div class="tab-content <?php echo $tab === StructureController::TAB_infos ? '' : 'd-none' ?>" id="informations">

    <div class="row">
        <div class="col-md-4">
            <?php echo $this->partial('structure/etablissement/partial/information', ['entity' => $etablissement]) ?>
        </div>
        <div class="col-md-4">
            <h3>
                Étiquettes
            </h3>
            <p>
                <?php if ($etablissement->estAssocie()): ?>
                    <span class="badge bg-info">Associé</span>
                <?php endif ?>
                <?php if ($etablissement->estInscription()): ?>
                    <span class="badge bg-warning">Inscription</span>
                <?php endif ?>
                <?php if ($etablissement->getStructure()->estFermee()) : ?>
                    <span class="badge bg-secondary" style="background-color:darkred">Structure fermée</span>
                <?php else : ?>
                    <span class="badge bg-secondary" style="background-color:darkgreen">Structure ouverte</span>
                <?php endif; ?>
            </p>

            <h3>
                Logo
            </h3>
            <p>
                <img id="logo" alt="Logo de la structure" style="max-width: 200px; max-height: 200px; background-color: white;"
                     src="data:image/*;base64,<?php echo base64_encode($logoContent); ?>"/>
            </p>
        </div>
        <div class="col-md-4">
            <div class="box card">
                <div class="card-header bg-dark text-white">
                    <h2 class="first">Substitution</h2>
                </div>
                <div class="card-body">
                    <?php echo $this->partial('substitution/substitution/_partial/substitution-statut', ['entity' => $etablissement]) ?>
                </div>
            </div>
        </div>
    </div>

    <?php if ($canModifierEtablissement || $canModifierCetEtab): ?>
        <a href="<?php echo $this->url('etablissement/modifier', ['etablissement'=> $etablissement->getId()], [], true); ?>"
           class="btn btn-primary action">
            <span class="icon icon-edit"></span> Modifier cet établissement
        </a>
    <?php endif; ?>
    <?php if (($canModifierEtablissement || $canModifierCetEtab) && !$historisee) : ?>
        <a href="<?php echo $this->url('etablissement/supprimer', ["etablissement" => $etablissement->getId()], [], true); ?>"
           class="btn btn-danger action"
           data-bs-toggle="tooltip"
           data-bs-html="true"
           title="Une confirmation avant la suppression vous sera demandée"
           data-toggle="confirmationx">
            <span class="icon icon-delete"></span> Supprimer cet établissement
        </a>
    <?php endif; ?>
    <?php if (($canModifierEtablissement || $canModifierCetEtab) && $historisee) : ?>
        <a href="<?php echo $this->url('etablissement/restaurer', ["etablissement" => $etablissement->getId()], [], true); ?>"
           class="btn btn-danger action"
           data-bs-toggle="tooltip"
           data-bs-html="true"
           title="Une confirmation avant la restauration vous sera demandée"
           data-toggle="confirmationx">
            <span class="icon icon-restaurer"></span> Restaurer cet établissement
        </a>
    <?php endif; ?>

</div>



<div class="tab-content <?php echo $tab === StructureController::TAB_membres ? '' : 'd-none' ?>" id="membres">

    <h2 class="first">
        Rôles et membres
    </h2>

    <p class="lead">
        Voici les <em>rôles liés à cet établissement</em> et les individus auxquels ont été attribués ces rôles. <br>
        NB : les rôles comme "Doctorant" ou "Directeur de thèse", "Candidat", "Garant" ne sont pas liés à un établissement mais à une
        thèse/HDR donc ne peuvent figurer sur cette page. <br>
        <?php
        $canVisualiserIndividu = $this->isAllowed(Privileges::getResourceId(IndividuPrivileges::INDIVIDU_LISTER));
        if ($canVisualiserIndividu): ?>
            L'attribution d'un rôle à un quelqu'un n'est pas possible ici, vous devez le faire sur la fiche de l'individu
            (rendez-vous sur la <a href="<?php echo $this->url('individu') ?>">page de recherche d'individu</a>).
        <?php endif ?>
    </p>

    <div class="row">
        <?php foreach ($roleListing as $roleId => $count) :?>
        <div class="col-3 mb-4">
            <h3>
                <?php echo $roleId; ?>
                <span class="badge bg-secondary"><?php echo $count; ?></span>
            </h3>
            <?php if ($count): ?>
                <ul>
                <?php foreach($individuListing as $denomination => $roles): ?>
                    <?php foreach($roles as $role): ?>
                        <?php if ($role === $roleId) : ?>
                            <li><?php echo $denomination; ?></li>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                </ul>
            <?php else: ?>
                Personne.
            <?php endif; ?>
        </div>
        <?php endforeach; ?>
    </div>

    <?php if ($canAddRole && empty($roleListing)): ?>
        <a
                href="<?php echo $this->url('structure/generer-roles-defauts',
                    ['id' => $etablissement->getStructure()->getId(), 'type' => TypeStructure::CODE_ETABLISSEMENT], [], true);?>"
                class="btn btn-warning"
        >
            <span class="icon icon-refresh"></span>
            Générer rôles par défaut
        </a>
    <?php endif; ?>

</div>



<?php if ($etablissement->estInscription()): ?>
    <div class="tab-content <?php echo $tab === StructureController::TAB_docs ? '' : 'd-none' ?>" id="documents">

        <?php echo $this->partial('structure/structure/partial/documents', ['structure' => $etablissement->getStructure(), 'contenusFichiers' => $contenusFichiers]); ?>

    </div>
<?php endif; ?>



<div class="tab-content <?php echo $tab === StructureController::TAB_variables ? '' : 'd-none' ?>" id="variables">

    <?php echo $this->partial('structure/variable/index', ['etablissement' => $etablissement, 'variables' => $variables]); ?>

</div>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>