<?php

use Structure\Controller\EtablissementController;
use Structure\Entity\Db\Etablissement;
use Structure\Form\EtablissementForm;
use Application\View\Renderer\PhpRenderer;
use UnicaenIdref\Domain\Index1;

/**
 * @var PhpRenderer        $this
 * @var string             $title
 * @var EtablissementForm  $form
 * @var string|null        $logoContent
 *
 * @method string formControlGroup()
 *
 * @see EtablissementController::modifierAction()
 */

$logoContent = $logoContent ?? null;

/** @var Etablissement $etablissement */
$etablissement = $form->getObject();
$idEtablissement = $etablissement->getStructure()->getId();
$isNew = $etablissement->getId() === null;
$estImportee = $etablissement->getSource()?->getImportable() ?? false;
$fcg = $this->formControlGroup();

$editable = $isNew || !$estImportee;
$form->get('libelle')->setAttribute('readonly', !$editable);
$form->get('sigle')->setAttribute('readonly', !$editable);
$form->get('code')->setAttribute('readonly', !$editable);

$this->headTitle("Modification de l'établissement ".$etablissement->getStructure()->getCode());
?>

<h1 class="page-header">
    <?php if ($isNew): ?>
        Création d'un nouvel établissement
    <?php else: ?>
        Modification de l'établissement &laquo; <?php echo $etablissement ?> &raquo;
    <?php endif ?>
</h1>

<?php echo $this->messenger()->addCurrentMessagesFromFlashMessengerWithNoNamespace(); ?>

<?php if ($estImportee) : ?>
    <p class="alert alert-warning">
        <span class="icon icon-attention"></span>
        <strong>La source (<?php echo $etablissement->getSource()->getLibelle(); ?>) ne permet pas la modification de certains attributs.</strong>
        <br/>
        Par conséquent, vous ne pouvez pas modifier les champs : libellé, sigle et code.
    </p>
<?php endif; ?>

<!-- BLOC DES INFORMATIONS GENERALES ---------------------------------------------------------------------------------->

<?php echo $this->form()->openTag($form->prepare()->setAttribute('class', 'etablissement')) ?>

<div class="row">
    <div class="col-md-6">
        <fieldset>
            <legend><h2>Informations générales</h2></legend>
            <?php echo $fcg($form->get('libelle')->setAttribute('id', 'libelle')) ?>
            <?php echo $fcg($form->get('sigle')) ?>
            <div class="row">
                <div class="col-md-10"><?php echo $fcg($form->get('siteWeb')) ?></div>
            </div>
        </fieldset>
        <fieldset>
            <legend><h2>Coordonnées</h2></legend>
            <?php echo $fcg($form->get('adresse')) ?>
            <div class="row">
                <div class="col-md-4"><?php echo $fcg($form->get('telephone')) ?></div>
                <div class="col-md-4"><?php echo $fcg($form->get('fax')) ?></div>
            </div>
        </fieldset>
        <fieldset>
            <legend><h2>Contact</h2></legend>
            <?php echo $fcg($form->get('email')) ?>
            <?php echo $fcg($form->get('emailAssistance')) ?>
            <?php echo $fcg($form->get('emailBibliotheque')) ?>
            <?php echo $fcg($form->get('emailDoctorat')) ?>
        </fieldset>
        <fieldset>
            <legend><h2>Informations techniques</h2></legend>
            <div class="row">
                <div class="col-md-5">
                    <?php echo $fcg($form->get('id_ref')->setAttribute('id', 'idRef')) ?>
                </div>
                <div class="col-md-2">
                    <?php echo $this->idrefPopupTrigger([
                        ['Index1' => Index1::INDEX_Ppn, 'Index1Value' => ['idRef']],
                        ['Index1' => Index1::INDEX_NomDeCollectivité, 'Index1Value' => ['libelle']],
                    ], 'idRef') ?>
                </div>
            </div>
            <?php echo $fcg($form->get('id_hal')) ?>
            <?php echo $fcg($form->get('code')) ?>
            <?php echo $fcg($form->get('domaine')) ?>
        </fieldset>
    </div>

    <div class="col-md-6">
        <fieldset>
            <legend><h2>Étiquettes associées</h2></legend>
            <?php echo $fcg($form->get('estMembre')) ?>
            <?php echo $fcg($form->get('estAssocie')) ?>
            <?php echo $fcg($form->get('estInscription')) ?>
            <?php echo $fcg($form->get('estFerme')) ?>
            <?php echo $fcg($form->get('estCed')) ?>
        </fieldset>

        <fieldset id="logo-div">
            <legend><h2>Logo</h2></legend>
            <?php
            /** @var \Laminas\Form\Element\File $logoFile */
            $logoFile = $form->get('cheminLogo');
            echo $this->formLabel($logoFile);
            ?>

            <?php
            $content = $logoContent;
            if ($content === null) {
                $form->getObject()->getStructure()->setCheminLogo(null);
            }
            ?>
            <table>
                <tr>
                    <td>
                        <?php if ($logoContent): ?>
                        <img
                                id="logo"
                            style="max-width: 200px; max-height: 200px; border: 1px solid black; background-color: white;"
                            src="data:image/*;base64,<?php echo base64_encode($logoContent); ?>"
                        />
                        <?php else: ?>
                            <strong>Aucun logo défini.</strong>
                        <?php endif; ?>
                    </td>
                    <td style="padding:20px;">
                        <?php
                        echo $this->formFile($logoFile);
                        echo $this->formElementErrors($logoFile);
                        ?>
                        <br/>
                        <?php if($form->getObject()->getId()): ?>
                        <a id="supprimer-logo" class="btn btn-danger" href="<?php echo $this->url('etablissement/supprimer-logo', ["etablissement" => $form->getObject()->getId()], [], true); ?>">
                            <span class="icon icon-delete"></span>
                            Supprimer le logo
                        </a>
                        <?php endif; ?>
                    </td>
                </tr>
            </table>

            <div class="alert alert-warning">
                <small>
                    <span class="icon icon-warning"></span>
                    Le logo de la structure doit être donné dans un des formats suivant&nbsp;:
                    <ul>
                        <li>.bmp</li>
                        <li>.jpg, .jpeg</li>
                        <li>.png</li>
                    </ul>
                </small>
            </div>
        </fieldset>
    </div>

</div>
<?php echo $this->formElement($form->get('submit')) ?>
<?php echo $this->form()->closeTag() ?>

    <!-- pour traduction -->
<?php
$this->translate("Libellé :");
$this->translate("Code :");
$this->translate("Enregistrer");
$this->translate("Supprimer le logo");
$this->translate("Logo de l'établissement :");
?>

<script>
    $(document).ready(function() {

        //remplacement dans la structure cible
        $("input[name='cheminLogo']").on("change", function () {

            var myFile = $("input[name='cheminLogo']").prop('files');
            console.log(myFile[0]);
            fr = new FileReader();
            fr.onload = function () {
                var content = fr.result;
                console.log(content);
                $('#logo').attr("src", content);
            };
            fr.readAsDataURL( myFile[0] );
        });

        $("button#supprimer-logo").on("click",  function() {
           alert("clic");
        });
    });
</script>
