<?php

use Structure\Controller\EtablissementController;
use Structure\Entity\Db\Etablissement;
use Structure\Entity\Db\Structure;
use Structure\Form\EtablissementForm;
use Application\View\Renderer\PhpRenderer;
use UnicaenApp\Form\View\Helper\FormControlGroup;
use UnicaenIdref\Domain\Index1;

/**
 * @var PhpRenderer        $this
 * @var string             $title
 * @var EtablissementForm  $form
 * @var string|null        $logoContent
 *
 * @method FormControlGroup formControlGroup()
 *
 * @see EtablissementController::ajouterAction()
 * @see EtablissementController::modifierAction()
 */

$logoContent = $logoContent ?? null;

/** @var Etablissement $etablissement */
$etablissement = $form->getObject();
$idEtablissement = $etablissement->getStructure()->getId();
$isNew = $etablissement->getId() === null;
$estImportee = $etablissement->getSource()?->getImportable() ?? false;
$fcg = $this->formControlGroup();

$editable = $isNew || !$estImportee;
$form->get('libelle')->setAttribute('readonly', !$editable);
$form->get('sigle')->setAttribute('readonly', !$editable);
$form->get('code')->setAttribute('readonly', !$editable);

$this->headTitle(($isNew ? "Création" : "Modif.") . " établissemnt " . $etablissement->getStructure()->getCode());
?>

<h1 class="page-header">
    <?php if ($isNew): ?>
        <?php if ($etablissement->estInscription()): ?>
            Création d'un nouvel établissement d'inscription
        <?php elseif ($etablissement->estCed()): ?>
            Création du Collège des Écoles Doctorales
        <?php else: ?>
            Création d'un nouvel établissement
        <?php endif ?>
    <?php else: ?>
        <?php if ($etablissement->estInscription()): ?>
            Modification de l'établissement d'inscription &laquo; <?php echo $etablissement ?> &raquo;
        <?php elseif ($etablissement->estCed()): ?>
            Modification du Collège des Écoles Doctorales
        <?php else: ?>
            Modification de l'établissement &laquo; <?php echo $etablissement ?> &raquo;
        <?php endif ?>
    <?php endif ?>
</h1>

<?php echo $this->messenger()->addCurrentMessagesFromFlashMessengerWithNoNamespace(); ?>

<?php if ($estImportee) : ?>
    <p class="alert alert-warning">
        <span class="icon icon-attention"></span>
        <strong>La source (<?php echo $etablissement->getSource()->getLibelle(); ?>) ne permet pas la modification de certains attributs.</strong>
        <br/>
        Par conséquent, vous ne pouvez pas modifier les champs : libellé, sigle et code.
    </p>
<?php endif; ?>

<!-- BLOC DES INFORMATIONS GENERALES ---------------------------------------------------------------------------------->

<?php echo $this->form()->openTag($form->prepare()->setAttribute('class', 'etablissement')) ?>

<div class="row justify-content-around">
    <div class="col-5">
        <fieldset>
            <legend><h2>Informations générales</h2></legend>
            <?php echo $fcg($form->get('libelle')->setAttribute('id', 'libelle')) ?>
            <div class="row row-cols-3">
                <div class="col"><?php echo $fcg($form->get('code')) ?></div>
                <div class="col"><?php echo $fcg($form->get('sigle')) ?></div>
                <div class="col"><?php echo $fcg($form->get('sourceCode')) ?></div>
            </div>
            <div class="row">
                <?php if ($form->has('domaine')) : ?>
                    <?php echo $fcg($form->get('domaine')) ?>
                <?php endif ?>
                <div class="col-md-10"><?php echo $fcg($form->get('siteWeb')) ?></div>
            </div>
        </fieldset>
        <fieldset>
            <legend><h2>Coordonnées</h2></legend>
            <?php echo $fcg($form->get('adresse')) ?>
            <div class="row">
                <div class="col-md-4"><?php echo $fcg($form->get('telephone')) ?></div>
                <div class="col-md-4"><?php echo $fcg($form->get('fax')) ?></div>
            </div>
        </fieldset>
        <fieldset>
            <legend><h2>Contact</h2></legend>
            <?php echo $fcg($form->get('email')) ?>
            <?php if ($form->has('emailAssistance')) : ?>
                <?php echo $fcg($form->get('emailAssistance')) ?>
            <?php endif ?>
            <?php if ($form->has('emailBibliotheque')) : ?>
                <?php echo $fcg($form->get('emailBibliotheque')) ?>
            <?php endif ?>
            <?php if ($form->has('emailDoctorat')) : ?>
                <?php echo $fcg($form->get('emailDoctorat')) ?>
            <?php endif ?>
        </fieldset>
        <fieldset>
            <legend><h2>Autres attributs</h2></legend>
            <div class="row">
                <div class="col-md-5">
                    <?php if ($form->has('id_ref')) : ?>
                        <?php echo $fcg($form->get('id_ref')->setAttribute('id', 'idRef')) ?>
                    <?php endif ?>
                </div>
                <div class="col-md-2">
                    <?php if ($form->has('id_ref')) : ?>
                        <style>
                            .idref-popup-trigger {
                                position: relative;
                                top: 18px;
                                left: -15px;

                            }
                        </style>
                        <?php echo $this->idrefPopupTrigger([
                            ['Index1' => Index1::INDEX_Ppn, 'Index1Value' => ['idRef']],
                            ['Index1' => Index1::INDEX_NomDeCollectivité, 'Index1Value' => ['libelle']],
                        ], 'idRef') ?>
                    <?php endif ?>
                </div>
                <div class="col-md-5">
                    <?php if ($form->has('id_hal')) : ?>
                        <?php echo $fcg($form->get('id_hal')) ?>
                    <?php endif ?>
                </div>
            </div>
        </fieldset>
    </div>

    <div class="col-5">
        <fieldset>
            <legend><h2>Étiquettes associées</h2></legend>
            <?php if ($form->has('estCed')) : ?>
                <?php echo $fcg($form->get('estCed')) ?>
            <?php endif ?>
            <?php if ($form->has('estInscription')) : ?>
                <?php echo $fcg($form->get('estInscription')) ?>
            <?php endif; ?>
            <?php if ($form->has('estMembre')) : ?>
                <?php echo $fcg($form->get('estMembre')) ?>
            <?php endif ?>
            <?php if ($form->has('estAssocie')) : ?>
                <?php echo $fcg($form->get('estAssocie')) ?>
            <?php endif ?>
            <?php if ($form->has('estFerme')) : ?>
                <?php echo $fcg($form->get('estFerme')) ?>
            <?php endif ?>
        </fieldset>

        <fieldset id="logo-div">
            <legend><h2>Logo</h2></legend>
            <?php
            /** @var \Laminas\Form\Element\File $logoFile */
            $logoFile = $form->get('cheminLogo');

            $content = $logoContent;
            if ($content === null) {
                $form->getObject()->getStructure()->setCheminLogo(null);
            }
            ?>
            <div>
                <?php if ($logoContent): ?>
                <img
                        id="logo"
                    style="max-width: 200px; max-height: 200px; border: 1px solid black; background-color: white;"
                    src="data:image/*;base64,<?php echo base64_encode($logoContent); ?>"
                />
                <?php else: ?>
                    Aucun logo défini.
                <?php endif; ?>
            </div>
            <div style="padding:20px;">
                <?php echo $this->formControlGroup($logoFile) ?>
                <div class="alert alert-warning text-md">
                    <span class="icon icon-warning"></span>
                    Le logo de la structure doit être fourni dans l'un des formats suivants :
                    <?php echo implode(', ', Structure::LOGO_ALLOWED_FILE_EXTENSIONS) ?>.
                </div>
                <?php if ($form->getObject()->getId()): ?>
                    <a data-toggle="confirmationx" id="supprimer-logo" class="btn btn-danger"
                       href="<?php echo $this->url('etablissement/supprimer-logo', ["etablissement" => $form->getObject()->getId()], [], true); ?>">
                        <span class="icon icon-delete"></span>
                        Supprimer le logo
                    </a>
                <?php endif; ?>
            </div>
        </fieldset>
    </div>

</div>

<?php echo $this->formHidden($form->get('id')) ?>
<?php echo $this->formHidden($form->get('csrf')) ?>
<?php echo $this->formElement($form->get('submit')) ?>
<?php echo $this->form()->closeTag() ?>

    <!-- pour traduction -->
<?php
$this->translate("Libellé :");
$this->translate("Code :");
$this->translate("Enregistrer");
$this->translate("Supprimer le logo");
$this->translate("Logo de l'établissement :");
?>

<script>
    $(document).ready(function() {

        //remplacement dans la structure cible
        $("input[name='cheminLogo']").on("change", function () {

            var myFile = $("input[name='cheminLogo']").prop('files');
            console.log(myFile[0]);
            fr = new FileReader();
            fr.onload = function () {
                var content = fr.result;
                console.log(content);
                $('#logo').attr("src", content);
            };
            fr.readAsDataURL( myFile[0] );
        });

        $("button#supprimer-logo").on("click",  function() {
           alert("clic");
        });
    });
</script>
