<?php

/**
 * @see \Structure\Controller\EtablissementController::televerserSignatureConvocationAction()
 * @var string $title
 * @var string $nature
 * @var string $action
 */

?>


<form method="post" action="<?php echo $action; ?>">
    <input type="file" id="fichier" name="fichier"/>
    <button type="submit" name="submit" class="btn btn-primary" value="">
        <span class="icon icon-televerser"></span>
        Téléverser
    </button>
</form>
