create table SOUTENANCE_QUALITE
(
    ID NUMBER not null
        primary key,
    LIBELLE VARCHAR2(128) not null,
    RANG VARCHAR2(1) not null,
    HDR VARCHAR2(1) not null,
    EMERITAT VARCHAR2(1) not null
);

create table SOUTENANCE_QUALITE_SUP
(
    ID NUMBER not null,
    QUALITE_ID NUMBER not null
        constraint SQS_QUALITE_FK
            references SOUTENANCE_QUALITE
            on delete cascade,
    LIBELLE VARCHAR2(255) not null,
    HISTO_CREATION DATE not null,
    HISTO_CREATEUR_ID NUMBER not null
        constraint SQS_CREATEUR_FK
            references UTILISATEUR,
    HISTO_MODIFICATION DATE not null,
    HISTO_MODIFICATEUR_ID NUMBER not null
        constraint SQS_MODIFICATEUR_FK
            references UTILISATEUR,
    HISTO_DESTRUCTION DATE,
    HISTO_DESTRUCTEUR_ID NUMBER
        constraint SQS_DESTRUCTEUR_FK
            references UTILISATEUR
);

create unique index SQS_ID_UINDEX on SOUTENANCE_QUALITE_SUP (ID);
alter table SOUTENANCE_QUALITE_SUP add constraint SOUTENANCE_QUALITE_SUP_PK primary key (ID);

INSERT INTO SOUTENANCE_QUALITE (ID, LIBELLE, RANG, HDR, EMERITAT) VALUES (0, 'Qualité inconnue', 'B', 'N', 'N');
INSERT INTO SOUTENANCE_QUALITE (ID, LIBELLE, RANG, HDR, EMERITAT) VALUES (1, 'Professeur des universités', 'A', 'O', 'N');
INSERT INTO SOUTENANCE_QUALITE (ID, LIBELLE, RANG, HDR, EMERITAT) VALUES (2, 'Directeur de recherche', 'A', 'O', 'N');
INSERT INTO SOUTENANCE_QUALITE (ID, LIBELLE, RANG, HDR, EMERITAT) VALUES (3, 'Maître de conférences', 'B', 'N', 'N');
INSERT INTO SOUTENANCE_QUALITE (ID, LIBELLE, RANG, HDR, EMERITAT) VALUES (4, 'Chargé de recherche', 'B', 'N', 'N');
INSERT INTO SOUTENANCE_QUALITE (ID, LIBELLE, RANG, HDR, EMERITAT) VALUES (5, 'Maître de conférences (HDR)', 'B', 'O', 'N');
INSERT INTO SOUTENANCE_QUALITE (ID, LIBELLE, RANG, HDR, EMERITAT) VALUES (6, 'Professeur émerite', 'A', 'O', 'O');

INSERT INTO SOUTENANCE_QUALITE_SUP (ID, QUALITE_ID, LIBELLE, HISTO_CREATION, HISTO_CREATEUR_ID, HISTO_MODIFICATION, HISTO_MODIFICATEUR_ID, HISTO_DESTRUCTION, HISTO_DESTRUCTEUR_ID) VALUES (1, 4, 'CHARGE DE RECHERCHE', TO_DATE('2019-12-17 10:01:15', 'YYYY-MM-DD HH24:MI:SS'), 1, TO_DATE('2019-12-17 10:01:22', 'YYYY-MM-DD HH24:MI:SS'), 1, null, null);
INSERT INTO SOUTENANCE_QUALITE_SUP (ID, QUALITE_ID, LIBELLE, HISTO_CREATION, HISTO_CREATEUR_ID, HISTO_MODIFICATION, HISTO_MODIFICATEUR_ID, HISTO_DESTRUCTION, HISTO_DESTRUCTEUR_ID) VALUES (6, 1, 'PROFESSEUR DES UNIVERSITES', TO_DATE('2019-12-17 11:54:12', 'YYYY-MM-DD HH24:MI:SS'), 1446, TO_DATE('2019-12-17 11:54:12', 'YYYY-MM-DD HH24:MI:SS'), 1446, null, null);
INSERT INTO SOUTENANCE_QUALITE_SUP (ID, QUALITE_ID, LIBELLE, HISTO_CREATION, HISTO_CREATEUR_ID, HISTO_MODIFICATION, HISTO_MODIFICATEUR_ID, HISTO_DESTRUCTION, HISTO_DESTRUCTEUR_ID) VALUES (2, 2, 'DIRECTEUR DE RECHERCHE', TO_DATE('2019-12-17 11:26:10', 'YYYY-MM-DD HH24:MI:SS'), 1446, TO_DATE('2019-12-17 11:26:10', 'YYYY-MM-DD HH24:MI:SS'), 1446, null, null);
INSERT INTO SOUTENANCE_QUALITE_SUP (ID, QUALITE_ID, LIBELLE, HISTO_CREATION, HISTO_CREATEUR_ID, HISTO_MODIFICATION, HISTO_MODIFICATEUR_ID, HISTO_DESTRUCTION, HISTO_DESTRUCTEUR_ID) VALUES (3, 1, 'PROFESSEUR DES UNIVERSITÉS', TO_DATE('2019-12-17 11:27:29', 'YYYY-MM-DD HH24:MI:SS'), 1446, TO_DATE('2019-12-17 11:27:29', 'YYYY-MM-DD HH24:MI:SS'), 1446, null, null);