<?php

/**
 * @var string[] $filtres
 * @var array $listings
 */

?>


<div class="panel panel-default">
    <div class="panel-heading">
        <span class="glyphicon glyphicon-filter"></span>
        Filtre des formations
    </div>
    <div class="panel-body">
        <form id="filter" method="get" action="">

            <div class="row">
                <!-- libelle du module ------------------------------------------------------------------------------------>
                <div class="col-md-4">
                    <label for="libelle">Libellé : </label>
                    <input type="text" name="libelle" id="libelle" <?php if ($filtres['libelle'] !== null AND $filtres['libelle'] !== '') echo " value='".$filtres['libelle']."' "; ?>/>
                </div>
            </div>

            <br/>

            <div class="row">
                <div class="pull-right">
                    <button type="button" id="filter" class="btn btn-primary filter-action">
                        <span class="glyphicon glyphicon-filter" aria-hidden="true"></span> Filtrer
                    </button>
                    <button type="button" id="reset" class="btn btn-primary filter-action">
                        <span class="glyphicon glyphicon-erase" aria-hidden="true"></span> R.A.Z.
                    </button>
                </div>
            </div>

        </form>

    </div>
</div>


<style>
    .filter-action {
        width: 25rem;
        margin: 0 1rem;
    }

    form#filter label {
        width: 10rem;
    }
</style>

<script>
    $('button#reset').click(function (e) {
        e.preventDefault();
        window.location = '?';
    });
    $('button#filter').click(function () {
        $('form#filter').submit();
    });
</script>