<?php

/**
 * @var string[] $filtres
 * @var array $listings
 */

?>

<div class="card bg-default">
    <div class="card-header">
        <span class="icon icon-filter"></span>
        Filtre des formations
    </div>
    <div class="card-body">
        <form id="filter" method="get" action="">

            <div class="row">
                <!-- libelle du module ------------------------------------------------------------------------------------>
                <div class="col-md-4">
                    <label class="form-label" for="libelle">Libellé : </label>
                    <input class="form-control" type="text" name="libelle" id="libelle" <?php if ($filtres['libelle'] !== null AND $filtres['libelle'] !== '') echo " value='".$filtres['libelle']."' "; ?>/>
                </div>

                <div>
                    <button type="button" id="filter" class="btn btn-primary">
                        <span class="icon icon-filter" aria-hidden="true"></span> Filtrer
                    </button>
                    <button type="button" id="reset" class="btn btn-primary">
                        <span class="icon icon-delete" aria-hidden="true"></span> R.A.Z.
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    $('button#reset').click(function (e) {
        e.preventDefault();
        window.location = '?';
    });
    $('button#filter').click(function () {
        $('form#filter').submit();
    });
</script>