<?php

use Application\Search\Filter\TextSearchFilter;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var TextSearchFilter $filter
 * @var array $queryParams
 */

$paramAttributes = $filter->getAttributes();
$title = $paramAttributes['title'] ?: null;
?>

<div class="form-group">
    <label class="form-label visually-hidden" for="search-input"></label>
    <div class="input-group">
        <span class="input-group-text"><span class="icon iconly icon-search"></span></span>
        <input type="search"
               value="<?php echo $filter->getValue(); ?>"
               name="<?php echo $filter->getName(); ?>"
               title="<?php echo $title ?>"
               class="form-control filter"
               id="search-input"
               placeholder="<?php echo $this->translate("Entrez 2 caractères au moins..."); ?>">
    </div>
</div>

<script>
    $(function () {
        $("#search-input").tooltip({html: true, trigger: "hover", placement: "bottom"});
    });
</script>