<?php

use Application\Search\Filter\SearchFilter;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var SearchFilter[] $filters
 */

$queryParams = $this->queryParams();
?>

<div class="card filters">
    <div class="card-header">
        <span class="icon icon-filter"></span> Filtres
    </div>
    <form class="card-body filters" method="GET" action="">
        <div class="container">
            <div class="row">
                <?php foreach ($filters as $filter): ?>
                    <?php if (!$filter->isVisible()) continue; ?>
                    <div class="col col-auto p-1">
                        <label class="form-label" for="<?php echo $filter->getName() ?>">
                            <?php echo $filter->getLabel() ?>
                        </label>
                        <div class="input-group">
                            <?php
                            echo $this->partial('filter-form-item', [
                                'filter' => $filter,
                                'queryParams' => $queryParams,
                            ]);
                            ?>
                        </div>
                    </div>
                <?php endforeach ?>
                <div class="col col-auto">
                    <label for="reset">Vider</label>
                    <div class="input-group">
                        <button type="button"
                                name="reset"
                                class="btn btn-secondary"
                                onclick="resetForm()"
                                title="<?php echo $this->translate("Vider le formulaire");?>" >
                            <span class="icon icon-delete iconly"></span>
                        </button>
                    </div>
                </div>
                <div class="col col-auto">
                    <div class="input-group">
                        <input type="submit" name="search" class="btn btn-primary" value="Rechercher"/>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>



<script>
    var $form;
    var $selectpickers;

    $(function() {
        $form = $("form.filters");
        $form.submit(function() {
            $("body").addClass('wait');
        });

        $selectpickers = $form.find(".selectpicker");
        if ($selectpickers.length) {
            $selectpickers.selectpicker();
        }
    });
    function resetForm() {
        $form
            .find(":input.filter").val('').attr("checked", false).end()
            .find(":input[type=checkbox].filter").attr("checked", false).end()
        if ($selectpickers.length) {
            $selectpickers.selectpicker('deselectAll').selectpicker('render').end();
        }
    }
</script>