<?php

use Application\Search\Filter\SearchFilter;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var SearchFilter[] $filters
 */

$queryParams = $this->queryParams();
?>

<div class="panel panel-default filters">
    <div class="panel-heading">
        <span class="glyphicon glyphicon-filter"></span> Filtres
    </div>
    <form class="panel-body form-inline filters" method="GET" action="">
        <?php foreach ($filters as $filter): ?>
        <div class="form-group">
            <label for="<?php echo $filter->getName() ?>">
                <?php echo $filter->getLabel() ?>
            </label>
            <div class="input-group">
                <?php
                echo $this->partial('filter-form-item', [
                    'filter' => $filter,
                    'queryParams' => $queryParams,
                ]);
                ?>
            </div>
        </div>
        <?php endforeach ?>
        <div class="form-group">
            <label for="reset">Vider</label>
            <div class="input-group">
                <button type="button"
                        name="reset"
                        class="btn btn-default"
                        onclick="resetForm()"
                        title="<?php echo $this->translate("Vider le formulaire");?>" >
                    <span class="glyphicon glyphicon-erase"></span>
                </button>
            </div>
        </div>
        <div class="form-group">
            <div class="input-group">
                <input type="submit" name="search" class="btn btn-primary" value="Rechercher"/>
            </div>
        </div>
    </form>
</div>



<script>
    var $form;
    var $selectpickers;

    $(function() {
        $form = $("form.filters");
        $form.submit(function() {
            $("body").addClass('wait');
        });

        $selectpickers = $form.find(".selectpicker");
        if ($selectpickers.length) {
            $selectpickers.selectpicker();
        }
    });
    function resetForm() {
        $form
            .find(":input.filter").val('').attr("checked", false).end()
            .find(":input[type=checkbox].filter").attr("checked", false).end()
        if ($selectpickers.length) {
            $selectpickers.selectpicker('deselectAll').selectpicker('render').end();
        }
    }
</script>