<?php

use Application\Search\Filter\TextSearchFilter;
use Application\Search\These\TheseTextSearchFilter;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var TextSearchFilter $filter
 * @var array $queryParams
 */

$name = $filter->getName();
$text = $filter->getTextValue();
$criteria = $filter->getCriteriaValue();

$title = htmlspecialchars(
    "<div class=\"these-search-input-help\">" .
    $this->translate("La recherche de texte porte sur les critères sélectionnés dans la liste déroulante ci-contre...") .
    "</div>"
);
?>

<div class="form-group">
    <label class="sr-only" for="search-input">Recherche d'une thèse (code, titre de la thèse ; code, nom, prénom de l'auteur) :</label>
    <div class="input-group">
        <div class="input-group-prepend">
            <span class="input-group-text"><span class="icon iconly icon-search"></span></span>
        </div>
        <input type="search"
               value="<?php echo $text; ?>"
               name="<?php echo $name; ?>"
               class="form-control filter"
               id="search-input"
               placeholder="<?php echo $this->translate("Entrez 2 caractères au moins...");?>"
               data-content="<?php echo $title ?>">
        <div class="input-group-append">
            <div class="input-group-text">
                <select multiple name="<?php echo $name; ?>Criteria[]" id="" class="selectpicker show-menu-arrow"
                        title="Sélectionnez un critère..."
                        data-selected-text-format="count"
                        data-count-selected-text="{0} critères sélectionnés"
                        data-actions-box="true"
                        data-header="Critères sur lesquels portera la recherche textuelle">
                    <?php foreach (TheseTextSearchFilter::CRITERIA as $key => $label): ?>
                        <?php $isActive = in_array($key, $criteria); ?>
                        <option value="<?php echo $key ?>" <?php echo $isActive ? 'selected' : '' ?>><?php echo $label ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
    </div>
</div>

<script>
    $(function() {
        $("#search-input").popover({html: true, trigger: "hover", placement: "bottom"});
    });
</script>