<?php

use Application\Search\Filter\SelectSearchFilter;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer       $this
 * @var SelectSearchFilter $filter
 * @var array             $queryParams
 */

$paramAttributes = $filter->getAttributes();
$paramName = $filter->getName();

$width = $paramAttributes['width'] ?? 'fit';
$liveSearch = (bool) ($paramAttributes['liveSearch'] ?? false);
?>

<select title=""
        class="zform-control filter selectpicker show-menu-arrow"
        name="<?php echo $paramName ?>"
        data-live-search="<?php echo $liveSearch ? 'true' : 'false' ?>"
        data-width="<?php echo $width ?>"
        data-html="true"
>

<?php foreach ($filter->getOptions() as $data): ?>

    <?php
    $value = $data['value'];
    $label = $data['label'];
    $subtext = $data['subtext'] ?? '';
    $class = $data['class'] ?? '';
    $isActive = $value === $filter->getValue() || $filter->isSelectOptionActive($value, $queryParams);
    ?>
    <option <?php echo $isActive ? 'selected' : '' ?>
            value="<?php echo $value ?>"
            class="<?php echo $class ?>"
            data-subtext="<?php echo $subtext ?>">
        <?php echo $label ?>
    </option>

<?php endforeach ?>

</select>