<?php
/**
 * @see \Individu\Controller\IndividuComplController::afficherAction()
 * @var IndividuCompl $complement
 * @var string $title
 */

use Individu\Entity\Db\IndividuCompl;

?>

<h1 class="page-header"><?php echo $title ?></h1>

<div class="row">
    <div class="col-md-6">
        <dl>
            <dt>Individu concerné</dt>
            <dd><?php echo $complement->getIndividu() ?> </dd>
        </dl>
    </div>
    <div class="col-md-6">
        <dl>
            <?php if ($complement->getHistoCreation()) : ?>
                <dt> Création</dt>
                <dd>
                    <?php echo $complement->getHistoCreateur()->getDisplayName(); ?>
                    le
                    <?php echo $complement->getHistoCreation()->format("d/m/Y H:i:s"); ?>
                </dd>
            <?php endif; ?>
            <?php if ($complement->getHistoModification()) : ?>
                <dt> Modification</dt>
                <dd>
                    <?php echo $complement->getHistoModificateur()->getDisplayName(); ?>
                    le
                    <?php echo $complement->getHistoModification()->format("d/m/Y H:i:s"); ?>
                </dd>
            <?php endif; ?>
            <?php if ($complement->getHistoDestruction()) : ?>
                <dt> Historisation</dt>
                <dd>
                    <?php echo $complement->getHistoDestructeur()->getDisplayName(); ?>
                    le
                    <?php echo $complement->getHistoDestruction()->format("d/m/Y H:i:s"); ?>
                </dd>
            <?php endif; ?>
        </dl>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <dl>
            <dt>Adresse électronique professionnelle</dt>
            <dd><?php echo $complement->getEmail() ?: "(Non renseignée)" ?> </dd>
            <dt>Établissement</dt>
            <dd><?php echo $complement->getEtablissement() ?: "(Non renseigné)" ?> </dd>
            <dt>Unité de recherche</dt>
            <dd><?php echo $complement->getUniteRecherche() ?: "(Non renseignée)" ?> </dd>
        </dl>
    </div>
</div>
