<?php

use Individu\Form\IndividuCompl\IndividuComplForm;

/**
 * @see \Individu\Controller\IndividuComplController::ajouterAction()
 * @see \Individu\Controller\IndividuComplController::modifierAction()
 * @var IndividuComplForm $form
 */

?>

<?php echo $this->form()->openTag($form); ?>

<?php echo $this->formControlGroup()->render($form->get('individu')); ?>
<?php echo $this->formControlGroup()->render($form->get('email')); ?>
<?php echo $this->formControlGroup()->render($form->get('etablissement')); ?>
<?php echo $this->formControlGroup()->render($form->get('uniteRecherche')); ?>

<?php echo $this->formControlGroup()->render($form->get('enregistrer')); ?>

<?php echo $this->form()->closeTag(); ?>
