<?php /** @noinspection PhpUnusedAliasInspection */

/**
 * @see \Formation\Controller\PresenceController::renseignerPresencesAction()
 * @var Session $session
 * @var Presence[][] $presences
 * @var bool $titre
 */

use Formation\Entity\Db\Inscription;
use Formation\Entity\Db\Seance;
use Formation\Entity\Db\Session;
use Formation\Entity\Db\Presence;
use Formation\Provider\Privilege\SeancePrivileges;
use Formation\Provider\Privilege\SessionPrivileges;

/** @var Seance[] $seances */
$seances = $session->getSeances()->toArray();
$seances = array_filter($seances, function (Seance $a) { return $a->estNonHistorise();});
usort($seances, function(Seance $a, Seance $b) { return $a->getDebut() > $b->getDebut();});
/** @var Inscription[] $inscriptions */
$inscriptions = $session->getListePrincipale();
usort($inscriptions, function(Inscription $a, Inscription $b) { return $a->getDoctorant()->getIndividu()->getNomComplet() > $b->getDoctorant()->getIndividu()->getNomComplet();});

$canPresenceModifier = $this->isAllowed(SeancePrivileges::getResourceId(SeancePrivileges::SEANCE_PRESENCE));

$titrePage= " Présences pour la formation : " . $session->getFormation()->getLibelle() . " #" . $session->getIndex();
$this->headTitle($titrePage);
?>

<?php if ($titre !== false) : ?>
    <h1 class="page-header">
        <?php echo $titrePage; ?>
    </h1>
<?php endif; ?>

<div class="main">

    <table class="formation-presence">
        <tr>
            <td class="separateur"></td>
            <?php foreach ($seances as $seance) : ?>
                <td class="journee">
                    <?php echo $seance->getDebut()->format('d/m/Y');?> <br/>
                    <?php echo $seance->getDebut()->format('H:i');?> &rightarrow; <?php echo $seance->getFin()->format('H:i');?> </td>
            <?php endforeach; ?>
        </tr>
        <?php foreach ($inscriptions as $inscription) : ?>
        <tr>
            <td class="inscrit">
                    <div style="float:left;">
                            <strong><?php echo $inscription->getDoctorant()->getIndividu()->getNomComplet(); ?></strong>
                    </div>
                    <div style="float:right;" style="padding-right: 1rem;">
                        <?php if ($canPresenceModifier) : ?>
                            <span class="all_toggle icon icon-yes" id="on_<?php echo $inscription->getId(); ?>"           data-bs-toggle="tooltip" data-bs-html="true" title="Passer à présent toutes les journées de <span class='highlight agent'><?php echo $inscription->getDoctorant()->getIndividu()->getNomComplet(); ?></span>"></span>
                            <span class="all_toggle icon icon-no" id="off_<?php echo $inscription->getId(); ?>"    data-bs-toggle="tooltip" data-bs-html="true" title="Passer à absent toutes les journées de <span class='highlight agent'><?php echo $inscription->getDoctorant()->getIndividu()->getNomComplet(); ?></span>"></span>
                        <?php endif; ?>
                    </div>
            </td>
            <?php foreach ($seances as $seance) : ?>
                <td class="reponse <?php if ($canPresenceModifier) echo "toggle"; ?>" id="<?php echo $seance->getId(); ?>_<?php echo $inscription->getId(); ?>">
                    <?php if (isset($presences[$seance->getId()][$inscription->getId()]) && $presences[$seance->getId()][$inscription->getId()]->isPresent()) : ?>
                        <span class="icon icon-yes" style="color:darkgreen;" title="Présent"></span>
                    <?php else : ?>
                        <span class="icon icon-no" style="color:darkred;" title="Non présent"></span>
                    <?php endif; ?>
                </td>
            <?php endforeach; ?>
        </tr>
        <?php endforeach; ?>
    </table>
</div>

<style>
    td.toggle {
        cursor: pointer;
    }
</style>

<script>
    let seances = [
        <?php
            $array = array_map(function(Seance $a) {return $a->getId();}, $seances);
            echo implode(",", $array);
        ?>
    ];
    $(function() {
        $("td.toggle").on("click", function () {
            let id = $(this).attr('id');
            let split = id.split("_");
            let inscrit = split[1];
            let journee = split[0];
            // console.log('inscrit: ' + inscrit);
            // console.log('journee: ' + journee);

            <?php /** @see \Formation\Controller\PresenceController::togglePresenceAction() */ ?>
            let url = "../../presence/toggle-presence/" + journee + "/" + inscrit;
            $.ajax({
                type: "POST",
                url : url,
                beforeSend:
                    function () {
                        document.getElementById(id).innerHTML = "<i class='fas fa-hourglass' style='color:#1b6d85;'></i>";
                    },
                success:
                    function(retour){
                        // console.log(retour);
                        // console.log(id);
                        let texte;
                        if (retour === "1") texte = "<span class='icon icon-yes' style='color:darkgreen;'></span>";
                        else texte = "<span class='icon icon-no' style='color:darkred;'></span>";
                        document.getElementById(id).innerHTML = texte;
                    }
            });
        });

        $("span.all_toggle").on("click", function () {
            let id = $(this).attr('id');
            let split = id.split("_");
            let inscrit = split[1];
            let mode = split[0];
            console.log('mode: ' + mode);
            console.log('inscrit: ' + inscrit);

            <?php /** @see PresenceController::togglePresencesAction() */ ?>
            let url = "../../presence/toggle-presences/" + mode + "/" + inscrit;
            $.ajax({
                type: "POST",
                url : url,
                beforeSend:
                    function () {
                        $.each(seances, function(index, journee) {
                            // console.log(inscrit);
                            // console.log(journee);
                            document.getElementById(journee + "_" + inscrit).innerHTML = "<i class='fas fa-hourglass' style='color:#1b6d85;'></i>";
                        });
                    },
                success:
                    function(){
                        // console.log(retour);
                        let texte = "";
                        $.each(seances, function(index, journee) {
                            // console.log(inscrit);
                            // console.log(journee);
                            if (mode === 'on') texte = "<span class='icon icon-yes' style='color:darkgreen;'></span>";
                            else texte = "<span class='icon icon-no' style='color:darkred;'></span>";
                            document.getElementById(journee + "_" + inscrit).innerHTML = texte;
                        });
                    }
            });
        });
    });
</script>