<?php
/**
 * @var Membre[] $membres
 * @var These $these
 */

use Application\Entity\Db\These;
use Soutenance\Entity\Membre;

?>

<h1 class="">
    Renseignement des PersoP@ss des membres du jury
</h1>

<table class="table table-extra-condensed">
    <thead>
        <tr>
            <th> Dénomination </th>
            <th> Qualité </th>
            <th> PersoP@ss </th>
            <th> Création </th>
            <th> Action </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($membres as $membre): ?>
            <tr>
                <td>
                    <?php echo $membre->getDenomination(); ?>
                </td>
                <td>
                    <?php echo $membre->getQualite()->getLibelle(); ?>
                </td>
                <td>
                    <?php echo $membre->getPersopass(); ?>
                </td>
                <td>
                    <?php echo ($membre->isNouveau())?'<span class="glyphicon glyphicon-ok"></span>':''; ?>
                </td>
                <td>
                   <a
                       href="<?php echo $this->url('soutenance/persopass/modifier', ['these' => $these->getId(), 'membre' => $membre->getId()], [], true); ?>"
                        class="ajax-modal"
                        data-event="modifier-persopass">
                        <span class="glyphicon glyphicon-pencil"></span>
                   </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function() {
        $("body").on("modifier-persopass", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>