<?php

namespace These\Fieldset\Financement;

use Application\Entity\Db\OrigineFinancement;
use Laminas\Filter\ToNull;
use Laminas\Form\Element\Date;
use Laminas\Form\Element\Number;
use Laminas\Form\Element\Select;
use Laminas\Form\Element\Text;
use Laminas\Form\Fieldset;
use Laminas\Form\FormInterface;
use Laminas\InputFilter\InputFilterProviderInterface;
use These\Entity\Db\These;

class FinancementFieldset extends Fieldset implements InputFilterProviderInterface
{
    private array $originesFinancements;

    public function setOrigineFinancementsPossibles(array $originesFinancements): void
    {
        $options = [];
        foreach ($originesFinancements as $origine) {
            /** @var OrigineFinancement $origine */
            if(!in_array($origine->getLibelleLong(), $options)){
                $options[$origine->getId()] = $origine->getLibelleLong();
            }
        }
        $this->originesFinancements = $options;
    }

    // Méthode pour générer les options d'année
    protected function generateYearOptions() : array
    {
        $currentYear = date('Y');
        $options = [];
        for ($year = $currentYear; $year >= $currentYear - 50; $year--) {
            $options[$year] = $year;
        }
        return $options;
    }

    public function prepareElement(FormInterface $form): void
    {
        /** @var These $these */
        $these = $form->getObject();
        $estModifiable = !$these->getSource()->getImportable();

        $this->get('origineFinancement')->setEmptyOption('Sélectionnez une option');
        $this->get('origineFinancement')->setValueOptions($this->originesFinancements);

        $this->get('annee')->setAttribute('disabled', !$estModifiable);
        $this->get('dateDebut')->setAttribute('disabled', !$estModifiable);
        $this->get('dateFin')->setAttribute('disabled', !$estModifiable);
        $this->get('origineFinancement')->setAttribute('disabled', !$estModifiable);
        $this->get('complementFinancement')->setAttribute('disabled', !$estModifiable);
        $this->get('quotiteFinancement')->setAttribute('disabled', !$estModifiable);

        parent::prepareElement($form); // TODO: Change the autogenerated stub
    }

    public function init()
    {
        $this->add(
            (new Select("annee"))
                ->setLabel("Année <span class='icon icon-obligatoire' style='color: darkred;font-size: 0.8em;' data-bs-toggle='tooltip' title='Obligatoire'></span> :")
                ->setLabelOptions(['disable_html_escape' => true, ])
                ->setValueOptions($this->generateYearOptions())
                ->setEmptyOption("Sélectionner une année")
                ->setAttributes([
                    'class' => 'selectpicker show-menu-arrow',
                ])
        );

        $this->add([
            'type' => Date::class,
            'name' => 'dateDebut',
            'options' => [
                'label' => "Date de début du financement : ",
            ],
        ]);

        $this->add([
            'type' => Date::class,
            'name' => 'dateFin',
            'options' => [
                'label' => "Date de fin du financement : ",
            ],
        ]);

        $this->add(
            (new Select("origineFinancement"))
                ->setLabel("Origine de Financement <span class='icon icon-obligatoire' style='color: darkred;font-size: 0.8em;' data-bs-toggle='tooltip' title='Obligatoire'></span> :")
                ->setLabelOptions(['disable_html_escape' => true, ])
                ->setOptions(['emptyOption' => 'Choisissez un élément',])
                ->setDisableInArrayValidator(true)
                ->setAttributes([
                    'class' => 'selectpicker show-menu-arrow',
                    'data-live-search' => 'true',
                    'id' => 'origineFinancement',
                ])
        );

        $this->add([
            'type' => Text::class,
            'name' => 'complementFinancement',
            'options' => [
                'label' => "Complément de financement :",
            ],
        ]);

        $this->add([
            'name' => 'quotiteFinancement',
            'type' => Number::class,
            'options' => [
                'label' => "Quotité de financement :",
            ],
            'attributes' => [
                'min' => 1,
                'max' => 100,
                'step' => 1,
            ],
        ]);
    }

    /**
     * @inheritDoc
     */
    public function getInputFilterSpecification()
    {
        /** @var These $these */
        $these = $this->getObject();
        $estModifiable = !$these->getSource()->getImportable();
        return [
            'annee' => [
                'name' => 'annee',
                'required' => $estModifiable,
            ],
            'dateDebut' => [
                'name' => 'dateDebut',
                'required' => false,
            ],
            'dateFin' => [
                'name' => 'dateFin',
                'required' => false,
            ],
            'origineFinancement' => [
                'name' => 'origineFinancement',
                'required' => $estModifiable,
                'filters' => [
                    ['name' => ToNull::class], /** nécessaire et suffisant pour mettre la relation à null */
                ],
            ],
            'quotiteFinancement' => [
                'name' => 'quotiteFinancement',
                'required' => false,
                'filters' => [
                    ['name' => ToNull::class], /** nécessaire et suffisant pour mettre la relation à null */
                ],
            ],
            'complementFinancement' => [
                'name' => 'complementFinancement',
                'required' => false,
                'filters' => [
                    ['name' => ToNull::class], /** nécessaire et suffisant pour mettre la relation à null */
                ],
            ],
        ];
    }
}