<?php

use HDR\Entity\Db\HDR;
use Soutenance\Entity\Etat;
use Soutenance\Entity\Proposition;
use Soutenance\Provider\Privilege\PropositionPrivileges;
use These\Entity\Db\These;

/**
  * @var Proposition $proposition
  * @var string $typeProposition
 */

$adresse = $proposition->getAdresseActive();
$object = $proposition->getObject();

$canDemanderAdresseExacte = $this->isAllowed(PropositionPrivileges::getResourceId(PropositionPrivileges::PROPOSITION_MODIFIER_GESTION));


?>

<?php if ($adresse !== null) : ?>
    <?php echo $adresse->format(); ?>
<?php else :?>
    <?php if ($proposition->getAdresse() !== null) : ?>
        <div class="alert alert-info">
            <span class="icon icon-info"></span>
            Adresse récupérée de l'ancien système.
        </div>
        <p><?php echo $proposition->getAdresse(); ?></p>
    <?php else : ?>
        <p class="lead">L'adresse exacte n'a pas encore été saisie dans la partie proposition.</p>
    <?php endif; ?>

    <?php
    $etatObject = $object instanceof These ? $object->getEtatThese() : $object->getEtatHDR();
    if($canDemanderAdresseExacte && ($etatObject === These::ETAT_EN_COURS || $etatObject === HDR::ETAT_EN_COURS)) : ?>
        <?php /** @see \Soutenance\Controller\PropositionController::demanderAdresseAction() */ ?>
        <a href="<?php echo $this->url("soutenance_{$typeProposition}/proposition/demander-adresse", ['id' => $object->getId(), 'proposition' => $proposition->getId()], [], true); ?>"
           class="btn btn-info">
            <span class="icon icon-notifier"></span>
            Demander la saisie de l'adresse exacte
        </a>
    <?php endif; ?>
<?php endif; ?>

