<?php

/**
 * @var Proposition $proposition
 * @var These $these
 */

use Soutenance\Service\Horodatage\HorodatageService;
use These\Entity\Db\These;
use Soutenance\Entity\Membre;
use Soutenance\Entity\Proposition;
use Soutenance\Provider\Privilege\PresoutenancePrivileges;

$canAssocierMembreIndividu              = $this->isAllowed($these, PresoutenancePrivileges::PRESOUTENANCE_ASSOCIATION_MEMBRE_INDIVIDU);
$theseImportee = $these->getSource()->getImportable()
?>

<div class="box card">
    <div class="card-header bg-dark text-white">
        <div class="row">
            <div class="col-md-8">
                <?php if($theseImportee): ?>
                    <h2> Association d'acteur SYGAL aux membres de jury </h2>
                <?php else: ?>
                    <h2> Association d'individu SYGAL aux membres de jury </h2>
                <?php endif; ?>
            </div>
            <div class="col-md-4">
                <p>
<!--                    <a-->
<!--                        --><?php ///** @see  \Soutenance\Controller\PresoutenanceController::presoutenanceAction() */ ?>
<!--                        class="btn btn-secondary btn-sm"-->
<!--                       id="refresh-these-button"-->
<!--                       href="--><?php //echo $this->urlThese()->refreshTheseUrl($these, $this->url('soutenance/presoutenance', ['these' => $these->getId()], [], true)); ?><!--"-->
<!--                    ><span class="icon icon-import"></span> <strong>Mettre à jour</strong> la thèse à partir de-->
<!--                        --><?php //echo $these->getSource() ?><!--</a>-->

                </p>
<!--                <span class="small">-->
<!--                    Dernière mise à jour : --><?php //echo $these->getHistoModification()->format(Constants::DATETIME_FORMAT) ?><!--.-->
<!--                </span>-->

            </div>
        </div>
    </div>

    <div class="card-body">

        <p class="lead">
            <?php if($theseImportee) : ?>
                Tous les membres du jury doivent être associés à des acteurs enregistrés dans SyGAL.
            <?php else: ?>
                Tous les membres (déclarés dans la composition du jury de la proposition de soutenance) doivent être associés à des individus enregistrés dans SyGAL.
            <?php endif; ?>
        </p>

        <table class="table table-extra-condensed">
            <thead>
            <tr>
                <th> Dénomination </th>
                <th> Rôle </th>
                <th> Qualité </th>
                <th> Etablissement </th>
                <th> Id <?php echo $this->appInfos()->nom ?> </th>
                <th> Action </th>
            </tr>
            </thead>
            <tbody>
            <?php /** @var Membre $membre  */ ?>
            <?php foreach ($proposition->getMembres() as $membre): ?>
                <tr>
                    <td>    <?php echo $membre->getDenomination(); ?>                                                   </td>
                    <td>    <?php echo $membre->getRole(); ?>                                                           </td>
                    <td>    <?php echo ($membre->getQualite())?$membre->getQualite()->getLibelle():"Non définie"; ?>    </td>
                    <td>    <?php echo $membre->getEtablissement(); ?>                                                  </td>
                    <td>    <?php echo ($membre->getActeur())?$membre->getActeur()->getId() .' '. $membre->getIndividu()->getNomComplet():''; ?>                  </td>
                    <td>
                        <?php if($canAssocierMembreIndividu): ?>
<!--                            --><?php //if ($membre->estRapporteur()) : ?>
                                    <?php if (! $membre->getActeur()): ?>
                                        <?php if ($theseImportee):
                                            /** @see \Soutenance\Controller\PresoutenanceController::associerJuryAction() **/
                                            $lienAssociationJury = $this->url('soutenance/presoutenance/associer-jury', ['these' => $these->getId(), 'membre' => $membre->getId()], [], true); ?>
                                        <?php else:
                                            /** @see \Soutenance\Controller\PresoutenanceController::associerJuryTheseSygalAction() **/
                                            $lienAssociationJury = $this->url('soutenance/presoutenance/associer-jury-these-sygal', ['these' => $these->getId(), 'membre' => $membre->getId()], [], true); ?>
                                        <?php endif; ?>
                                            <a  href="<?php echo $lienAssociationJury ?>"
                                                class="action ajax-modal"
                                                data-event="modification-association-jury"
                                            >
                                            <span class="fas fa-link" title="Associer un individu à un membre de jury"></span>
                                        </a>
                                    <?php else: ?>
                                        <a  <?php /** @see \Soutenance\Controller\PresoutenanceController::deassocierJuryAction() */ ?>
                                            href="<?php echo $this->url('soutenance/presoutenance/deassocier-jury', ['these' => $these->getId(), 'membre' => $membre->getId()], [], true);; ?>"
                                        >
                                            <span class="icon icon-delete iconly" title="Casser l'association d'un individu à un membre de jury"></span>
                                        </a>
                                    <?php endif; ?>
<!--                            --><?php //endif; ?>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>

        <?php echo $this->dernierHorodatage($proposition, HorodatageService::TYPE_MODIFICATION, "Association jury"); ?>

    </div>

</div>