<?php

/**
 * @var Proposition $proposition
 * @var These $these
 */

use These\Entity\Db\These;
use Soutenance\Entity\Membre;
use Soutenance\Entity\Proposition;
use Soutenance\Provider\Privilege\PresoutenancePrivileges;

$canAssocierMembreIndividu              = $this->isAllowed($these, PresoutenancePrivileges::PRESOUTENANCE_ASSOCIATION_MEMBRE_INDIVIDU);
?>

<div class="box card">
    <div class="card-header bg-dark text-white">
        <div class="row">
            <div class="col-md-8">
                <h2> Association d'acteur SYGAL aux membres de jury </h2>
            </div>
            <div class="col-md-4">
                <p>
                    <a
                        <?php /** @see  \Soutenance\Controller\PresoutenanceController::presoutenanceAction() */ ?>
                        class="btn btn-secondary btn-sm"
                       id="refresh-these-button"
                       href="<?php echo $this->urlThese()->refreshTheseUrl($these, $this->url('soutenance/presoutenance', ['these' => $these->getId()], [], true)); ?>"
                    ><span class="icon icon-import"></span> <strong>Mettre à jour</strong> la thèse à partir de
                        <?php echo $these->getSource() ?></a>

                </p>
<!--                <span class="small">-->
<!--                    Dernière mise à jour : --><?php //echo $these->getHistoModification()->format(Constants::DATETIME_FORMAT) ?><!--.-->
<!--                </span>-->

            </div>
        </div>
    </div>

    <div class="card-body">

        <p class="lead">
            Tous les membres du jury doivent être associés à des acteurs enregistrés dans SyGAL.
        </p>

        <table class="table table-extra-condensed">
            <thead>
            <tr>
                <th> Dénomination </th>
                <th> Rôle </th>
                <th> Qualité </th>
                <th> Etablissement </th>
                <th> Id <?php echo $this->appInfos()->nom ?> </th>
                <th> Action </th>
            </tr>
            </thead>
            <tbody>
            <?php /** @var Membre $membre  */ ?>
            <?php foreach ($proposition->getMembres() as $membre): ?>
                <tr>
                    <td>    <?php echo $membre->getDenomination(); ?>                                                   </td>
                    <td>    <?php echo $membre->getRole(); ?>                                                           </td>
                    <td>    <?php echo ($membre->getQualite())?$membre->getQualite()->getLibelle():"Non définie"; ?>    </td>
                    <td>    <?php echo $membre->getEtablissement(); ?>                                                  </td>
                    <td>    <?php echo ($membre->getActeur())?$membre->getActeur()->getId() .' '. $membre->getIndividu()->getNomComplet():''; ?>                  </td>
                    <td>
                        <?php if($canAssocierMembreIndividu): ?>
                            <?php if ($membre->estRapporteur()) : ?>
                                <?php if (! $membre->getActeur()): ?>
                                    <a  <?php /** @see \Soutenance\Controller\PresoutenanceController::associerJuryAction() */ ?>
                                        href="<?php echo $this->url('soutenance/presoutenance/associer-jury', ['these' => $these->getId(), 'membre' => $membre->getId()], [], true); ?>"
                                        class="ajax-modal"
                                        data-event="modification-date-rendu-rapport"
                                    >
                                        <span class="fas fa-link" title="Associer un individu à un membre de jury"></span>
                                    </a>
                                <?php else: ?>
                                    <a  <?php /** @see \Soutenance\Controller\PresoutenanceController::deassocierJuryAction() */ ?>
                                        href="<?php echo $this->url('soutenance/presoutenance/deassocier-jury', ['these' => $these->getId(), 'membre' => $membre->getId()], [], true); ?>"
                                    >
                                        <span class="icon icon-delete iconly" title="Casser l'association d'un individu à un membre de jury"></span>
                                    </a>
                                <?php endif; ?>
                            <?php endif; ?>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>

    </div>

</div>