<?php

/**
 * @var These $these
 * @var Proposition $proposition
 * @var Membre[] $rapporteurs
 * @var Validation[] $engagements
 * @var Avis[] $avis
 *
 * @var Evenement[] $evenementsPrerapport

 */

use Application\Constants;
use Application\Entity\Db\These;
use Application\Entity\Db\Validation;
use Soutenance\Entity\Avis;
use Soutenance\Entity\Evenement;
use Soutenance\Entity\Membre;
use Soutenance\Entity\Proposition;
use Soutenance\Provider\Privilege\AvisSoutenancePrivileges;

$canNotifierAvisSoutenance = $this->isAllowed(AvisSoutenancePrivileges::getResourceId(AvisSoutenancePrivileges::AVIS_NOTIFIER));
$canRevoquerAvisSoutenance = $this->isAllowed(AvisSoutenancePrivileges::getResourceId(AvisSoutenancePrivileges::AVIS_ANNULER));

$tousLesEngagements = count($rapporteurs) === count($engagements) ;
$tousLesAvis = count($rapporteurs) === count($avis) ;
?>


<div class="box card">
    <div class="card-header bg-info">
        <h2> Avis de soutenance</h2>
    </div>
    <div class="card-body">
        <p class="lead">
            Avant de pouvoir déclencher la procédure de soutenance il est nécessaire d'attendre le retour des avis de soutenance des rapporteurs.
        </p>

        <table class="table table-extra-condensed">
            <thead>
            <tr>
                <th> Rapporteur </th>
                <th> Avis </th>
                <th> Rapport </th>
                <th> Date </th>
                <th> Actions </th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($rapporteurs as $rapporteur) : ?>

                <?php
                $acteur = $rapporteur->getActeur();
                $avi = ($acteur !== null)?$avis[$acteur->getIndividu()->getId()]:null;

                ?>

                <tr>
                    <!-- Colonne affichant le nom du rapporteur -->
                    <td>
                        <?php if ($acteur) : ?>
                            <?php echo $acteur->getIndividu(); ?>
                        <?php else : ?>
                            <span class="text-danger">
                                <?php echo $rapporteur->getDenomination(); ?>
                            </span>
                        <?php endif; ?>
                    </td>

                    <!-- Affichage de l'avis de soutenance -->
                    <td>
                        <?php if ($acteur) : ?>
                            <?php if (isset($avis[$acteur->getIndividu()->getId()])): ?>
                                <?php
                                $avi = $avis[$acteur->getIndividu()->getId()];
                                if ($avi->getAvis() === 'Favorable') : ?>
                                    <span class="text-success">
                                            <span class="icon icon-ok"></span>
                                            Favorable
                                        </span>
                                <?php else: ?>
                                    <span class="text-danger" title="<?php echo $avi->getMotif(); ?>">
                                            <span class="icon icon-ko"></span>
                                            Défavorable
                                        </span>
                                <?php endif; ?>
                            <?php else: ?>
                                <span class="text-warning">
                                    <i> Non rendu </i>
                                </span>
                            <?php endif; ?>
                        <?php else: ?>
                            <span class="text-danger">
                                <span class="fas fa-exclamation-triangle"></span>
                                <i> N'est pas un individu <?php echo $this->appInfos()->nom ?></i>
                                <span class="fas fa-exclamation-triangle"></span>
                            </span>
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php if ($acteur) : ?>
                            <?php if ($engagements[$acteur->getIndividu()->getId()] && $avis[$acteur->getIndividu()->getId()]) : ?>
                                <a
                                    <?php /** @see TELECHARGER FICHIER */ ?>
                                    href=" <?php echo $this->urlFichierThese->telechargerFichierThese($these, $avis[$acteur->getIndividu()->getId()]->getFichier()); ?>" >
                                    Rapport de pré-soutenance</a>
                            <?php endif ?>
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php if ($acteur !== null) :?>
                            <?php if ($avi !== null) :?>
                                <?php echo $avi->getValidation()->getHistoCreation()->format(Constants::DATETIME_FORMAT); ?>
                            <?php endif; ?>
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php if ($acteur !== null) : ?>
                            <?php if ($canNotifierAvisSoutenance && isset($engagements[$rapporteur->getIndividu()->getId()]) && !isset($avis[$acteur->getIndividu()->getId()])) : ?>
                                <a  <?php /** @see \Soutenance\Controller\PresoutenanceController::notifierDemandeAvisSoutenanceAction() */ ?>
                                    href="<?php echo $this->url('soutenance/presoutenance/notifier-demande-avis-soutenance', ['these' => $these->getId(), 'membre' => $rapporteur->getId()], [], true); ?>">
                                    <span class="icon icon-notify"      title="Notifier le rapporteur '<?php echo $rapporteur->getEmail(); ?>'"></span>
                                </a>
                            <?php else: ?>
                                <span class="icon icon-notify" title="Notifier le rapporteur" style="color:lightgray;" ></span>
                            <?php endif; ?>

                            <?php if ($canRevoquerAvisSoutenance && $avi !== null) : ?>
                                <a  <?php /** @see \Soutenance\Controller\PresoutenanceController::revoquerAvisSoutenanceAction(); */ ?>
                                    href="<?php echo $this->url('soutenance/presoutenance/revoquer-avis-soutenance', ['these' => $these->getId(), 'avis' => $avi->getId()], [], true); ?>">
                                    <span class="icon icon-delete iconly"
                                          title="Révoquer l'avis de soutenance">
                                    </span>
                                </a>
                            <?php else: ?>
                                <span class="icon icon-delete iconly"
                                      title="Révoquer l'avis de soutenance"
                                      style="color:lightgray;">
                                </span>
                            <?php endif; ?>
                        <?php endif; ?>

                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>

        <div class="row">
            <div class="col-md-4">
                <?php if($canNotifierAvisSoutenance): ?>
                    <a  <?php /** @see \Soutenance\Controller\PresoutenanceController::notifierDemandeAvisSoutenanceAction() */ ?>
                        class="btn btn-info <?php echo ($tousLesEngagements)?'':'disabled'; ?>"
                        href="<?php echo $this->url('soutenance/presoutenance/notifier-demande-avis-soutenance', ['these' => $these->getId()], [], true); ?>"
                    >
                        <span class="icon icon-notify"></span> Envoyer des demandes d'avis de soutenance
                    </a>
                <?php endif; ?>

                <?php if ($evenementsPrerapport !== null AND !empty($evenementsPrerapport)) : ?>
                    Notification de la demande des pré-rapports &nbsp;:&nbsp;
                    <ul>
                        <?php foreach ($evenementsPrerapport as $evenementPrerapport) : ?>
                            <li> Faite le <?php echo $evenementPrerapport->getDate()->format('d/m/Y à H:i:s'); ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </div>

            <div class="col-md-8">
                <?php if ($tousLesAvis) : ?>
                    <div class="card">
                        <div class="card-header bg-success">
                            <span class="icon icon-ok"></span>
                            Tous les rapports et avis ont été fournis.
                        </div>
                    </div>
                <?php else : ?>
                    <div class="card">
                        <div class="card-header bg-warning">
                            <span class="fas fa-exclamation-triangle"></span>
                            Tous les rapports et avis n'ont pas été founis.
                        </div>
                    </div>
                <?php endif; ?>

            </div>
        </div>
    </div>

</div>