<?php

/**
 * @var int $deadline
 * @var \Soutenance\Entity\Proposition $proposition
 * @var \Application\Entity\Db\These $these
 */

use Soutenance\Provider\Privilege\SoutenancePrivileges;

$canEditDateRenduRapport                = $this->isAllowed($these, SoutenancePrivileges::SOUTENANCE_DATE_RETOUR_MODIFICATION);
?>

<div class=" panel panel-info">

    <div class="panel-heading">
        <h2> Date de retour des rapports </h2>
    </div>

    <div class="panel-body">
        <p class="lead">
            Les rapports doivent être reçu <?php echo $deadline; ?> jours avant la date de soutenance.
        </p>

        <div class="pull-left">
            Date de retour :
            <strong><?php echo $proposition->getRenduRapport()->format('d/m/Y'); ?> </strong>
        </div>

        <?php if($canEditDateRenduRapport): ?>
            <div class="pull-right">
                <a
                    href="<?php echo $this->url('soutenance/presoutenance/date-rendu-rapport', ['these' => $these->getId()], [] , true); ?>"
                    class="btn btn-primary action ajax-modal"
                    data-event="modification-date-rendu-rapport"
                >
                    <span class="glyphicon glyphicon-pencil"></span> Modifier
                </a>
            </div>
        <?php endif; ?>

    </div>
</div>