<?php

/**
 * @var int $deadline
 * @var Proposition $proposition
 * @var These $these
 */

use Soutenance\Service\Horodatage\HorodatageService;
use These\Entity\Db\These;
use Soutenance\Entity\Proposition;
use Soutenance\Provider\Privilege\PresoutenancePrivileges;

$canEditDateRenduRapport = $this->isAllowed($these, PresoutenancePrivileges::PRESOUTENANCE_DATE_RETOUR_MODIFICATION);
?>

<div class="box card">

    <div class="card-header bg-dark text-white">
        <h2> Date de retour des rapports </h2>
    </div>

    <div class="card-body">
        <p class="lead">
            Les prérapports doivent être reçus <?php echo $deadline; ?> jours avant la date de soutenance.
        </p>

        <div class="row">
        <div class="col-md-8">
            Date de retour :
            <strong><?php echo $proposition->getRenduRapport()->format('d/m/Y'); ?> </strong>
        </div>

        <?php if($canEditDateRenduRapport): ?>
            <div class="col-md-4">
                <a  <?php /** @see \Soutenance\Controller\PresoutenanceController::dateRenduRapportAction() */ ?>
                    href="<?php echo $this->url('soutenance/presoutenance/date-rendu-rapport', ['these' => $these->getId()], [] , true); ?>"
                    class="btn btn-primary action ajax-modal"
                    data-event="modification-date-rendu-rapport"
                >
                    <span class="icon icon-edit"></span> Modifier
                </a>
            </div>
        <?php endif; ?>
        </div>

        <?php echo $this->horodatagesParType($proposition, HorodatageService::TYPE_MODIFICATION, "Date de rendu"); ?>
    </div>
</div>