<?php

/**
 * @var These $these
 * @var array $documentsLiesSoutenance
 * @var UrlFichierThese $urlFichierThese
 */

use Depot\Controller\Plugin\UrlFichierThese;
use Soutenance\Provider\Privilege\PropositionPrivileges;
use These\Entity\Db\These;

$canGererDocument             = $this->isAllowed($these, PropositionPrivileges::PROPOSITION_MODIFIER_GESTION);

?>

<div class="box card">
    <div class="card-header bg-dark text-white">
        <h2> Documents liés à la soutenance</h2>
    </div>
    <div class="card-body">
        <p class="lead">
        Dépôt des fichiers liés à la soutenance : autorisation de soutenance, rapport de soutenance
        </p>
        <?php foreach ($documentsLiesSoutenance as $document) : ?>
            <h3><?= $document["label"] ?></h3>
            <div class="row">
                <div class="col-md-4">
                <?php if ($document["justificatif"] === null && $canGererDocument) : ?>
                    <?php /** @see \Soutenance\Controller\JustificatifController::ajouterDocumentLieSoutenanceAction() */?>
                    <a href="<?php echo $this->url("soutenance/justificatif/ajouter-document-lie-soutenance", ['these' => $these?->getId()], ["query" => [
                        "nature" => $document["type"],
                        "label" => $document["label"]
                    ]], true) ?>"
                       class="btn btn-primary ajax-modal" data-event="modification">
                        <span class="icon icon-televerser"></span>
                        Téléverser <?= strtolower($document["label"]) ?>
                    </a>
                <?php endif; ?>
                </div>
                <div class="col-md-8">
                    <?php if (empty($document["justificatif"])) : ?>
                        <div class="card-header bg-warning">
                            <span class="icon icon-attention"></span>
                            Aucun(e) <?= strtolower($document["label"]) ?> déposé(e).
                        </div>
                    <?php else : ?>
                        <ul>
                            <li>
                                <?php echo $this->justificatif()->render($document["justificatif"], $urlFichierThese); ?>
                                <?php if ($canGererDocument) : ?>
                                    <a href="<?php echo $this->url('soutenance/justificatif/retirer',
                                        ['justificatif' => $document["justificatif"]->getId(), 'these' => $these->getId()],
                                        ["query" => [
                                                "retour" => $this->url('soutenance/presoutenance', ['these' => $these->getId()], [], true)
                                            ]
                                        ],
                                        true); ?>"
                                       data-toggle="confirmationx"
                                       data-message="Êtes-vous sûr de vouloir supprimer ce document ?">
                                        <span style='color:darkred;' class="icon icon-delete iconly" data-bs-toggle="tooltip" title="Supprimer le document"></span>
                                    </a>
                                <?php endif; ?>
                            </li>
                        </ul>
                    <?php endif; ?>
                </div>
            </div>
            <br/>
        <?php endforeach; ?>
    </div>
</div>


<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>