<?php

/**
 * @var These $these
 * @var Justificatif $autorisation
 * @var Justificatif $rapport
 * @var UrlFichierThese $urlFichierThese
 */

use Depot\Controller\Plugin\UrlFichierThese;
use Soutenance\Entity\Justificatif;
use Soutenance\Provider\Privilege\PropositionPrivileges;
use These\Entity\Db\These;

$canAjouterAutorisation         = $this->isAllowed($these, PropositionPrivileges::PROPOSITION_MODIFIER_GESTION);
$canAjouterRapport              = $this->isAllowed($these, PropositionPrivileges::PROPOSITION_MODIFIER_GESTION);

?>

<div class="box card">
    <div class="card-header bg-dark text-white">
        <h2> Documents liés à la soutenance</h2>
    </div>
    <div class="card-body">

        <p class="lead">
        Dépôt des fichiers liés à la soutenance : autorisation de soutenance, rapport de soutenance
        </p>

        <div class="row">
            <h3>Autorisation de soutenance</h3>
            <div class="col-md-4">
            <?php if ($autorisation === null AND $canAjouterAutorisation) : ?>
                <?php /** @see \Soutenance\Controller\JustificatifController::ajouterAutorisationSoutenanceAction() */ ?>
                <a href="<?php echo $this->url('soutenance/justificatif/ajouter-autorisation-soutenance', ['these' => $these->getId()], [], true); ?>"
                   class="btn btn-primary ajax-modal" data-event="modification">
                    Téléverser l'autorisation de soutenance
                </a>
            <?php endif; ?>
            </div>
            <div class="col-md-8">
                <?php if ($autorisation === null) : ?>
                    <div class="card-header bg-warning">
                        <span class="icon icon-attention"></span>
                        Aucune autorisation de soutenance déposée.
                    </div>
                <?php else : ?>
                    <ul>
                        <li>
                            <?php echo $this->justificatif()->render($autorisation, $urlFichierThese); ?>
                            <?php if ($canAjouterAutorisation) : ?>
                                <a href="<?php echo $this->url('soutenance/justificatif/retirer',
                                    ['justificatif' => $autorisation->getId(), 'these' => $these->getId()],
                                    ["query" => [
                                            "retour" => $this->url('soutenance/presoutenance', ['these' => $these->getId()], [], true)
                                        ]
                                    ],
                                    true); ?>">
                                    <span class="text-danger">
                                        <span class="icon icon-unchecked"></span>
                                        Supprimer
                                    </span>
                                </a>
                            <?php endif; ?>
                        </li>
                    </ul>
                <?php endif; ?>
            </div>
        </div>

        <br/>

        <div class="row">
            <h3>Rapport de soutenance</h3>
            <div class="col-md-4">
                <?php if ($rapport === null AND $canAjouterRapport) : ?>
                    <?php /** @see \Soutenance\Controller\JustificatifController::ajouterRapportSoutenanceAction() */ ?>
                    <a href="<?php echo $this->url('soutenance/justificatif/ajouter-rapport-soutenance', ['these' => $these->getId()], [], true); ?>"
                       class="btn btn-primary ajax-modal" data-event="modification">
                        Téléverser rapport de soutenance
                    </a>
                <?php endif; ?>
            </div>
            <div class="col-md-8">
                <?php if ($rapport === null or empty($rapport)) : ?>
                    <div class="card-header bg-warning">
                        <span class="icon icon-attention"></span>
                        Aucune rapport de soutenance déposé.
                    </div>
                <?php else: ?>
                    <ul>
                        <li>
                            <?php echo $this->justificatif()->render($rapport, $urlFichierThese); ?>
                            <?php if ($canAjouterRapport) : ?>
                                <a href="<?php echo $this->url('soutenance/justificatif/retirer',
                                    ['justificatif' => $rapport->getId(), 'these' => $these->getId()],
                                    ["query" => [
                                        "retour" => $this->url('soutenance/presoutenance', ['these' => $these->getId()], [], true)
                                    ]
                                    ],
                                    true); ?>">
                                    <span class="text-danger">
                                        <span class="icon icon-unchecked"></span>
                                        Supprimer
                                    </span>
                                </a>
                            <?php endif; ?>
                        </li>
                    </ul>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>


<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>