<?php

/**
 * @var Proposition $proposition
 * @var Membre[] $rapporteurs
 * @var ActeurThese[]|ActeurHDR[] $acteursRapporteurs
 * @var ValidationThese[]|ValidationHDR[] $engagements
 * @var string $typeProposition
 *
 * @var bool $tousLesEngagements
 * @var bool $tousLesAvis
 */

use Acteur\Entity\Db\ActeurHDR;
use Acteur\Entity\Db\ActeurThese;
use Application\Constants;
use Soutenance\Entity\Etat;
use These\Entity\Db\These;
use Validation\Entity\Db\ValidationHDR;
use Validation\Entity\Db\ValidationThese;
use Soutenance\Entity\Membre;
use Soutenance\Entity\Proposition;
use Soutenance\Provider\Privilege\EngagementImpartialitePrivileges;
use Soutenance\Service\Horodatage\HorodatageService;

$tousLesRapporteurs = true;
$validatedCount = 0;
foreach ($rapporteurs as $rapporteur) {
    $acteur = $acteursRapporteurs[$rapporteur->getId()] ?? null;
    $engagement = ($acteur) ? ($engagements[$acteur->getIndividu()->getId()])?? null : null;
    if($engagement) $validatedCount++;
    if ($acteur === null) {
        $tousLesRapporteurs = false;
        break;
    }
}

if($proposition->getEtat()->getCode() === Etat::VALIDEE || $proposition->getEtat()->getCode() === Etat::REJETEE){
    $cssClass = "bg-dark";
}else{
    //si aucun engagement d'impartialité n'a encore été effectué
    if ($validatedCount === 0) {
        $cssClass = "bg-danger";
    //Si le circuit de validations est déjà commencé
    } elseif ($validatedCount < count($acteursRapporteurs)) {
        $cssClass = "bg-warning";
    } else {
        $cssClass = "bg-success";
    }
}

$object = $proposition->getObject();
$canNotifierEngagementImpartialite = $this->isAllowed($object, EngagementImpartialitePrivileges::ENGAGEMENT_IMPARTIALITE_NOTIFIER);
$canRevoquerEngagementImpartialite = $this->isAllowed($object, EngagementImpartialitePrivileges::ENGAGEMENT_IMPARTIALITE_ANNULER);
?>

<div class="box card">
    <div class="card-header <?= $cssClass ?>">
        <h2> Engagements d'impartialité</h2>
    </div>
    <div class="card-body">

        <p class="lead">
            <?php if($object instanceof These): ?>
                Afin de devenir officiellement rapporteur de cette thèse, les futurs rapporteurs doivent signer un engagement
                d'impartialité.
            <?php else: ?>
                Afin de devenir officiellement rapporteur de cette HDR, les futurs rapporteurs doivent signer un engagement
                d'impartialité.
            <?php endif; ?>
        </p>

        <?php if(!$rapporteurs): ?>
            <div class="alert alert-warning">
                <span class="icon icon-warning"></span>
                Aucun rapporteur déclaré dans la proposition de soutenance
            </div>
        <?php else: ?>
            <table class="table table-extra-condensed">
                <thead>
                <tr>
                    <th> Rapporteur</th>
                    <th> Signé</th>
                    <th> Actions</th>
                </tr>
                </thead>
                <tbody>
                <?php
                foreach ($rapporteurs as $rapporteur) : ?>

                    <?php
                    $acteur = $acteursRapporteurs[$rapporteur->getId()] ?? null;
                    $emailActeur = $acteur?->getEmail(true);
                    $engagement = ($acteur) ? ($engagements[$acteur->getIndividu()->getId()])??null : null;
                    ?>

                    <tr>
                        <!-- Affichage du nom du rapporteur --------------------------------------------------------------->
                        <td>
                            <?php if ($acteur !== null) : ?>
                                <?php echo $acteur->getIndividu(); ?>
                            <?php else : ?>
                                <span class="text-danger">
                                <?php echo $rapporteur->getDenomination(); ?>
                            </span>
                            <?php endif; ?>
                        </td>

                        <!-- Signature ------------------------------------------------------------------------------------>
                        <td>
                            <?php if ($acteur !== null) : ?>
                                <?php if ($emailActeur !== null) : ?>
                                    <?php if ($engagement !== null): ?>
                                        <?php
                                        echo $engagement->getHistoCreation()->format(Constants::DATETIME_FORMAT);
                                        ?>
                                    <?php else: ?>
                                        <span class="badge bg-warning text-white">
                                            <span class="icon icon-warning"></span>
                                            Non signé
                                        </span>
                                    <?php endif; ?>
                                <?php else : ?>
                                    <span class="badge bg-danger text-white">
                                        <span class="icon icon-warning"></span>
                                        Aucun email trouvé
                                    </span>
                                <?php endif; ?>
                            <?php else: ?>
                                <span class="badge bg-danger text-white">
                                    <span class="icon icon-warning"></span>
                                    N'est pas un individu <?php echo $this->appInfos()->nom ?>
                                </span>
                            <?php endif; ?>
                        </td>

                        <!-- Actions -------------------------------------------------------------------------------------->
                        <td>
                            <?php if ($acteur !== null and $emailActeur !== null) : ?>

                                <?php if ($canNotifierEngagementImpartialite) : ?>
                                    <?php if ($engagement) : ?>
                                        <span class="icon icon-notify" title="Notifier le rapporteur"
                                              data-bs-toggle="tooltip"
                                              style="color:lightgray;">
                                    </span>
                                    <?php else: ?>
                                        <a
                                            <?php /** @see \Soutenance\Controller\EngagementImpartialiteController::notifierEngagementImpartialiteAction() */ ?>
                                                href="<?php echo $this->url("soutenance_{$typeProposition}/engagement-impartialite/notifier", ['id' => $object->getId(), 'proposition' => $proposition->getId(), 'membre' => $rapporteur->getId()], [], true); ?>"
                                        >
                                        <span class="icon icon-notify"
                                              data-bs-toggle="tooltip"
                                              title="Notifier ce rapporteur (<?php echo $emailActeur; ?>)">
                                        </span>
                                        </a>
                                    <?php endif; ?>
                                <?php else: ?>
                                    <span class="icon icon-notify iconly" style="color:lightgray;"
                                          data-bs-toggle="tooltip"
                                          title="Notifier ce rapporteur (<?php echo $emailActeur; ?>)">
                                </span>
                                <?php endif; ?>

                                <?php if ($canRevoquerEngagementImpartialite) : ?>
                                    <?php if ($engagement) : ?>
                                        <a <?php /** @see \Soutenance\Controller\EngagementImpartialiteController::annulerEngagementImpartialiteAction() */ ?>
                                                href="<?php echo $this->url("soutenance_{$typeProposition}/engagement-impartialite/annuler", ['id' => $object->getId(), 'membre' => $rapporteur->getId()], [], true); ?>">
                                        <span class="icon icon-delete iconly"
                                              data-bs-toggle="tooltip"
                                              title="Révoquer l'engagement d'impartialité">
                                        </span>
                                        </a>
                                    <?php else: ?>
                                        <span class="icon icon-delete iconly" style="color:lightgray;"
                                              data-bs-toggle="tooltip"
                                              title="Révoquer l'engagement d'impartialité">
                                    </span>
                                    <?php endif; ?>
                                <?php else: ?>
                                    <span class="icon icon-delete iconly" style="color:lightgray;"
                                          data-bs-toggle="tooltip"
                                          title="Révoquer l'engagement d'impartialité">
                                </span>
                                <?php endif; ?>

                            <?php else : ?>

                                <?php if ($canNotifierEngagementImpartialite) : ?>
                                    <span class="icon icon-notify iconly" style="color:lightgray;"
                                          data-bs-toggle="tooltip"
                                          title="Notifier le rapporteur">
                                </span>
                                <?php else: ?>
                                    <span class="icon icon-notify iconly"
                                          title="Notifier le rapporteur"
                                          data-bs-toggle="tooltip"
                                          style="color:lightgray;">
                                </span>
                                <?php endif; ?>

                                <?php if ($canRevoquerEngagementImpartialite) : ?>
                                    <span class="icon icon-delete iconly" style="color:lightgray;"
                                          data-bs-toggle="tooltip"
                                          title="Révoquer l'engagement d'impartialité">
                                </span>
                                <?php else: ?>
                                    <span class="icon icon-delete iconly"
                                          title="Révoquer l'engagement d'impartialité"
                                          data-bs-toggle="tooltip"
                                          style="color:lightgray;">
                                </span>
                                <?php endif; ?>

                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>

            <div class="row">
                <?php if ($canNotifierEngagementImpartialite && !$tousLesEngagements): ?>
                <div class="col-md-4">
                        <a
                            <?php /** @see \Soutenance\Controller\PresoutenanceController::notifierRapporteursEngagementImpartialiteAction() */ ?>
                                href="<?php echo $this->url("soutenance_{$typeProposition}/presoutenance/notifier-rapporteurs-engagement-impartialite", ['id' => $object->getId(), 'proposition' => $proposition->getId()], [], true); ?>"
                                class="btn btn-info <?php echo ($tousLesRapporteurs) ? '' : 'disabled'; ?>">
                            <span class="icon icon-notify"></span> Envoyer les notifications aux rapporteurs
                        </a>
                    <br/>
                </div>
                <?php endif; ?>
                <!--            <div class="col-md-8">-->
                <!--                --><?php //if (!$tousLesEngagements) : ?>
                <!--                    <div class="card">-->
                <!--                        <div class="card-header bg-warning">-->
                <!--                            <span class="fas fa-exclamation-triangle"></span>-->
                <!--                            Tous les rapporteurs n'ont pas encore signé leur engagement d'impartialité.-->
                <!--                        </div>-->
                <!--                    </div>-->
                <!--                --><?php //endif; ?>
                <!--            </div>-->

                <?php echo $this->horodatagesParType($proposition, HorodatageService::TYPE_NOTIFICATION, "Demande de signature de l'engagement d'impartialité"); ?>
            </div>
        <?php endif; ?>
    </div>
</div>
