<?php
/**
 * @var These $these
 * @var Attestation $attestation
 */

use Depot\Entity\Db\Attestation;
use These\Entity\Db\These;

?>

<style>
    .attestations-item {  }
    .attestations-item .attestations-item-value { margin-bottom: 5px; }
</style>

<h2>Attestations</h2>

<div class="attestations-item">
    <div class="attestations-item-value">
        ☑ &nbsp;&nbsp;L’auteur certifie avoir pris connaissance de la charte de dépôt et de diffusion des thèses
    </div>
</div>
<div class="attestations-item">
    <div class="attestations-item-value">
        ☑ &nbsp;&nbsp;L’auteur certifie que la version déposée sous forme numérique constitue la version de référence de la thèse
    </div>
</div>
<div class="attestations-item">
    <div class="attestations-item-value">
        ☑ &nbsp;&nbsp;L’auteur certifie que l’exemplaire imprimé fourni est conforme à la version numérique déposée
    </div>
</div>