<table width="100%" style="font-size: 110%; vertical-align: top;">
    <tr>
        <td width="30%" style="text-align: left;">
            <?php echo $this->headerSubtitle; ?>
        </td>
        <td width="40%" align="cegnter" style="font-weight: bold; /*font-size: 120%;*/">
            <?php echo $this->headerTitle; ?>
        </td>
        <td width="20" style="text-align: right;">
<!--            <img src="var:logo" height="50px" alt="Logo de Normandie Université" />-->
            <img src="<?php echo $this->logo; ?>" height="50px" alt="Logo de Normandie Université" />
        </td>
    </tr>
</table>

