<?php

use Application\Entity\Db\Role;
use Application\Entity\Db\Validation;
use Application\View\Renderer\PhpRenderer;
use Soutenance\Entity\Membre;
use Soutenance\Entity\Proposition;

/**
 * @var PhpRenderer             $this
 * @var Proposition $proposition
 * @var Validation[] $validations
 * @var Validation $validation
 * @var array $logos
 * @var int $nbCodirecteur
 * @see
 */
?>

<style>
    body {
        font-size: 9pt;
    }

    span.warning {
        font-weight: bold;
        color: darkred;
    }

    img {
        height:2.5cm;
    }

    h1 {
        font-size: x-large;
    }
    h2 {
        font-size: large;
    }
    table {
        width:100%;
    }

    table.recapitulatif {
        /*background-color: #5cb85c;*/
        border:solid 1px black;
    }

    table.recapitulatif td.head {
        font-weight: bold;
        width: 33.3%
    }

    table.composition {
        /*background-color: #7ACAFF;*/
        border-collapse: collapse;
    }

    table.composition th{
        border-bottom:solid 2px black;
    }

    table.composition td{
        border-bottom:solid 1px gray;
    }

    table.composition tbody tr {
        border-bottom: 1px gray solid ;
    }

    table.informations {
        /*background-color: #f8efc0;*/
    }

    table.informations td.head {
        width: 50%
    }

    table.informations td.info {
        text-align: right;
    }

    table.validation {
        /*background-color: #ffadad;*/
        border-collapse: collapse;
    }

    table.validation th{
        border-bottom:solid 2px black;
    }

    table.validation td{
        border-bottom:solid 1px gray;
        margin: 1rem;
    }


</style>
<!-- SECTION DU LOGO DE LA COMUE -------------------------------------------------------------------------------------->

    <div style="width:25%; float:left; position:absolute; top: 20px; left: 20px">
        <img src="<?php echo $logos['COMUE']; ?>" />
    </div>
    <div style="width:25%; float:right; position:absolute; top: 20px; right: 20px ">
        <img src="<?php echo $logos['ETAB']; ?>" />
    </div>

        <h1 style="position:absolute; top: 60px; left: 30%">
            Proposition de soutenance
        </h1>

<br/>
<br/>

<h2> Récapitulatif de la thèse et soutenance </h2>

<table class="recapitulatif">
    <tr>
        <td class="head"> Titre de la thèse : </td>
        <td><?php echo $proposition->getThese()->getTitre(); ?> </td>
    </tr>
    <tr>
        <td class="head"> Doctorant : </td>
        <td> <?php echo $proposition->getThese()->getDoctorant()->getIndividu()->getNomComplet(); ?> </td>
    </tr>
    <tr>
        <td class="head"> Date de la soutenance : </td>
        <td>
            <?php if($proposition->getDate()) : ?>
                le <?php echo $proposition->getDate()->format("d/m/Y"); ?> à <?php echo $proposition->getDate()->format("H:i"); ?> <br/></td>
            <?php else: ?>
                <span class="warning"> Aucune date de renseignée </span>
            <?php endif; ?>
    </tr>
    <tr>
        <td class="head">Lieu de la soutenance :</td>
        <td>
            <?php if($proposition->getLieu()) : ?>
                <?php echo $proposition->getLieu(); ?>
            <?php else : ?>
                <span class="warning"> Aucun lieu de renseigné </span>
            <?php endif; ?>
        </td>
    </tr>
</table>

<h2>
    Proposition de jury
</h2>

<table class="composition">
    <thead>
        <tr>
            <th> Dénomination </th>
            <th> Qualité </th>
            <th> Établissement/Organisme d'affectation </th>
            <th> Visio </th>
        </tr>
    </thead>
    <tbody>
        <?php /** @var Membre $membre */ ?>
        <?php foreach ($proposition->getMembres() as $membre) : ?>
            <tr>
                <td> <?php echo $membre->getDenomination(); ?> </td>
                <td> <?php echo ($membre->getQualite())?$membre->getQualite()->getLibelle():"Non définie"; ?> </td>
                <td> <?php echo $membre->getEtablissement(); ?> </td>
                <td> <?php echo ($membre->isVisio())?"Oui":"Non"; ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php if ($proposition->getMembres()->isEmpty()) : ?>
    <span class="warning"> Le jury ne contient pas de membre </span>
<?php endif; ?>

<h2>
    Informations sur la thèse
</h2>

<table class="informations">
    <tr>
        <td class="head"> Soutenance hors de l'éatblissement d'inscription : </td>
        <td class="info"> <?php echo ($proposition->isExterieur())?"Oui":"Non"; ?> </td>
    </tr>
    <tr>
        <td class="head"> Thèse confidentielle : </td>
        <td class="info"> <?php echo ($proposition->getConfidentialite())?"Fin de confidentialité le ".$proposition->getConfidentialite()->format('d/m/Y'):"Non"; ?> </td>
    </tr>
    <tr>
        <td class="head"> Soutenance en huis clos : </td>
        <td class="info"> <?php echo ($proposition->isHuitClos())?"Oui":"Non"; ?> </td>
    </tr>
<!--    <tr>-->
<!--        <td class="head"> Rédation de la thèse en anglais : </td>-->
<!--        <td class="info"> --><?php //echo ($proposition->isManuscritAnglais())?"Oui":"Non"; ?><!-- </td>-->
<!--    </tr>-->
    <tr>
        <td class="head"> Soutenance de la thèse en anglais : </td>
        <td class="info"> <?php echo ($proposition->isSoutenanceAnglais())?"Oui":"Non"; ?> </td>
    </tr>
    <tr>
        <td class="head"> Demande de label européen : </td>
        <td class="info"> <?php echo ($proposition->isLabelEuropeen())?"Oui":"Non"; ?> </td>
    </tr>
    <tr>
        <td class="head"> Cotutelle : </td>
        <td class="info">
            <?php if ($proposition->getThese()->getLibelleEtabCotutelle() OR $proposition->getThese()->getLibellePaysCotutelle()) : ?>
                <?php if ($proposition->getThese()->getLibellePaysCotutelle()): ?>
                    <?php echo $proposition->getThese()->getLibelleEtabCotutelle(); ?>, <?php echo $proposition->getThese()->getLibellePaysCotutelle(); ?>
                <?php else : ?>
                    <?php echo $proposition->getThese()->getLibelleEtabCotutelle(); ?>
                <?php endif; ?>
            <?php else : ?>
                Non
            <?php endif; ?>


        </td>
    </tr>

</table>

<h2>
    Validations accordées à la proposition de soutenance
</h2>

<table class="validation">
    <thead>
        <tr>
            <th> Rôle </th>
            <th> Dénomination </th>
            <th> Avis </th>
            <th> Date de validation </th>
        </tr>
    </thead>
    <tbody>
        <!-- Doctorant -->
        <?php if (!empty($validations[Role::CODE_DOCTORANT])): ?>
            <?php foreach($validations[Role::CODE_DOCTORANT] as $validation) : ?>
                <tr>
                    <td> Doctorant </td>
                    <td> <?php echo $validation->getIndividu()->getNomComplet(); ?> </td>
                    <td> Favorable </td>
                    <td> <?php echo $validation->getHistoCreation()->format('d/m/Y'); ?> </td>
                </tr>
            <?php endforeach; ?>
        <?php else : ?>
            <tr><td colspan="4"> <span class="warning">Aucune validation donnée par le doctorant </span></td></tr>
        <?php endif; ?>

        <!-- Directeur -->
        <?php if (!empty($validations[Role::CODE_DIRECTEUR_THESE])): ?>
            <?php foreach($validations[Role::CODE_DIRECTEUR_THESE] as $validation) : ?>
                <tr>
                    <td> Directeur de thèse </td>
                    <td> <?php echo $validation->getIndividu()->getNomComplet(); ?> </td>
                    <td> Favorable </td>
                    <td> <?php echo $validation->getHistoCreation()->format('d/m/Y'); ?> </td>
                </tr>
            <?php endforeach; ?>
        <?php else : ?>
            <tr><td colspan="4"> <span class="warning">Aucune validation donnée par le directeur </span></td></tr>
        <?php endif; ?>

        <!-- Co-directeurs -->
        <?php if ($validations[Role::CODE_CODIRECTEUR_THESE]): ?>
            <?php foreach($validations[Role::CODE_CODIRECTEUR_THESE] as $validation) : ?>
                <tr>
                    <td> Co-directeur de thèse </td>
                    <td> <?php echo $validation->getIndividu()->getNomComplet(); ?> </td>
                    <td> Favorable </td>
                    <td> <?php echo $validation->getHistoCreation()->format('d/m/Y'); ?> </td>
                </tr>
            <?php endforeach; ?>
        <?php else :?>
            <?php if($nbCodirecteur && $nbCodirecteur - count($validations[Role::CODE_CODIRECTEUR_THESE]) !== 0): ?>
                <tr>
                    <td colspan="4"> <span class="warning">Validation manquante d'au moins un codirecteur.</span></td>
                </tr>
            <?php endif; ?>
        <?php endif; ?>

        <!-- UR -->
        <?php if ($validations[Role::CODE_UR]): ?>
            <?php foreach($validations[Role::CODE_UR] as $validation) : ?>
                <tr>
                    <td> Directeur de l'unité de recherche </td>
                    <td> <?php echo $validation->getIndividu()->getNomComplet(); ?> </td>
                    <td> Favorable </td>
                    <td> <?php echo $validation->getHistoCreation()->format('d/m/Y'); ?> </td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td colspan="4"> <span class="warning"> Aucune validation de l'unité de recherche</span> </td>
            </tr>
        <?php endif; ?>
        <!-- ED -->
        <?php if ($validations[Role::CODE_ED]): ?>
            <?php foreach($validations[Role::CODE_ED] as $validation) : ?>
                <tr>
                    <td> Directeur de l'école doctorale </td>
                    <td> <?php echo $validation->getIndividu()->getNomComplet(); ?> </td>
                    <td> Favorable </td>
                    <td> <?php echo $validation->getHistoCreation()->format('d/m/Y'); ?> </td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td colspan="4"> <span class="warning"> Aucune validation de l'école doctorale</span> </td>
            </tr>
        <?php endif; ?>
    </tbody>
</table>

<h2> Validation par la présidence </h2>

<table>
    <tr>
        <td style="width:20%;"> &#9744; Favorable </td>
        <td> Motif du refus : </td>
    </tr>
    <tr>
        <td> &#9744; Défavorable</td>
    </tr>
</table>


<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

<span >

    Fait à <u>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</u> , le <u>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</u>
    <br/>
    Signature de <?php echo $libelle; ?>

</span>


