<table width="100%" style="font-size: 110%; vertical-align: top;">
    <tr>
        <td width="30%" style="text-align: left;">
            <img src="//gest.unicaen.fr/images/UNICAEN-logo-NOIR-horizontal.png" height="90px" alt="Logo de l'Université" />
            <?php echo $this->headerSubtitle; ?>
        </td>
        <td width="40%" align="cegnter" style="font-weight: bold; /*font-size: 120%;*/">
            <?php echo $this->headerTitle; ?>
        </td>
        <td width="20" style="text-align: right;">
            <img src="<?php echo $this->basePath('logo_normandie_univ.jpg') ?>" height="50px" alt="Logo de Normandie Université" />
        </td>
    </tr>
</table>

