<?php

use These\Entity\Db\Acteur;
use Application\Entity\Db\Validation;
use These\Provider\Privilege\PresidentJuryPrivileges;

/**
 * @see \These\Controller\PresidentJuryController::indexAction()
 * @var Acteur[] $presidents
 */

$this->headTitle("Gestion des comptes associés aux présidents du jury");


function afficherActeur(Acteur $a) {

    $mailIndividu = $a->getIndividu()->getEmailPro();

    $title  = "<table>";
    $title .= "<tr><th>ActeurId</th><td>".$a->getId() . "</td></tr>";
    $title .= "<tr><th>IndividuId</th><td>".$a->getIndividu()->getId()."</td></tr>";
    if ($a->getIndividu()->getEmailPro()) {
        $title .= "<tr><th>Email</th><td>" . $mailIndividu . "</td></tr>";
    }
    $title .= "</table>";

    $texte  = "<span title='".$title."' data-bs-toggle='tooltip' data-bs-html='true'>";
    $texte .= $a->getIndividu()->getNomComplet();
    $texte .= "</span>";
    return $texte;

}

function afficherUtilisateur(Acteur $a) {
    $utilisateurs = $a->getIndividu()->getUtilisateurs();

    if (empty($utilisateurs)) {
        return "<span style='color:darkred;' class='icon icon-non iconly'></span>";
    }

    $title = "";
    foreach ($utilisateurs as $utilisateur) {
        if ($title !== "") $title .= "<hr/><br/>";
        $title .= $utilisateur->getUsername() . " - " . $utilisateur->getEmail();
    }
    return "<span style='color:darkgreen;' class='icon icon-oui' title='".$title."' data-bs-toggle='tooltip' data-bs-html='true'></span>";
}

function afficherMailIndividu(Acteur $a) {
    if ($a->getIndividu() !== null AND $a->getIndividu()->getEmailPro() !== null) {
        return "<span class='icon icon-oui' style='color:darkgreen;' 
                    title='IndividuId:". $a->getIndividu()->getId(). "<br/>".
                    $a->getIndividu()->getEmailPro() ."'
                    data-bs-toggle='tooltip' data-bs-html='true'></span>";
    }
    return "<span class='icon icon-non iconly' style='color:darkred;' title='Pas d email lié à l individu'></span>";
}

function afficherMailMembre(Acteur $a) {
    if ($a->getMembre() !== null AND $a->getMembre()->getEmail() !== null) {
        return '<span class="icon icon-oui" style = "color:darkgreen;"
                title = "PropositionId: '. $a->getMembre()->getProposition()->getId() . '<br/>' .
                $a->getMembre()->getEmail().'" 
                data-bs-toggle="tooltip" data-bs-html="true"></span>';
    }
    return '<span class="icon icon-non iconly" style="color:darkred;" title="Pas d email lié à un membre de soutenance"></span>';
}

function afficherThese(Acteur $a, $renderer) {
    $these = $a->getThese();
    $titre = htmlentities($these->getTitre(), ENT_QUOTES);

    $titreCourt = (substr(html_entity_decode($titre),0,40)) . " ...";

    $texte  = "<a href='".$renderer->url('these/identite', ['these' => $these->getId()], [], true)."' ";
    $texte .= "title='".htmlentities($titre)."' data-bs-toggle='tooltip' data-bs-html='true' ";
    $texte .= " >" . $titreCourt . "</a>";
    return $texte;
}

function afficherCorrection(Acteur $a) {
    $these = $a->getThese();
    $correction = $these->getCorrectionAutorisee();
    $forcee = $these->getCorrectionAutoriseeForcee();

    $texte  = "<span class='badge' style='background:". (($correction === 'facultative')?"#CB8113":"#B80E18").";'"
                ." title='". (($forcee !== null)?"Forcé":"Non forcée") ."'>";
    if ($forcee !== null) {
        $texte .= "<em>".$correction."</em>";
    } else {
        $texte .= $correction;
    }
    $texte .= "</span>";
    return $texte;
}

function afficherCorrectionEffectuees(Acteur $a) {
    $these = $a->getThese();
    $correction = $these->getValidations('DEPOT_THESE_CORRIGEE')->toArray();

    if (empty($correction)) {
        return "<span class='icon icon-non iconly' style='color:darkred;'></span>";
    }

    return "<span class='icon icon-oui' style='color:darkgreen;'></span>";
}

function afficherValidations(Acteur $a) {
    /** @var Validation[] $validations */
    $validations = $a->getThese()->getValidations('CORRECTION_THESE')->toArray();
    if (empty($validations)) {
        return "Aucune validation";
    }

    $texte  = "";
    $texte .= "<ul>";
    foreach ($validations as $validation) {
        $texte .= "<li>".$validation->getIndividu()->getNomComplet()."</li>";
    }
    $texte .= "</ul>";
    return $texte;
}

$canModifierMailPresident = $this->isAllowed(PresidentJuryPrivileges::getResourceId(PresidentJuryPrivileges::PRESIDENT_MODIFIER_MAIL));
$canNotifierPresident     = $this->isAllowed(PresidentJuryPrivileges::getResourceId(PresidentJuryPrivileges::PRESIDENT_NOTIFIER));

?>

<h1 class="page-header">
    Gestion des comptes associés aux présidents du jury
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace() ?>

     <p>
         Dans le tableau ci-dessous vous retrouvez la liste des président de jury remonté dans <?php echo $this->appInfos()->nom ?> pour les thèses en attente de correction.
     </p>

    <p>
        Pour chaque président, on retourve les indications suivantes :
    </p>
    <ul>
        <li> <strong>Dénomination du président</strong> : le nom usuel + premier prénom du président </li>
        <li> <strong>Utilisateur</strong> : le fait qu'un président a un compte connu dans SYGAL (au survol on a le username et le mail associé) </li>
        <li> <strong>Individu Mail</strong> : le fait qu'un mail est connu pour l'individu associé (au survol on a l'id et le mail associé)</li>
        <li> <strong>Membre Mail</strong> : le fait qu'un mail est connu pour un membre de soutenance associé (au survol on a l'id et le mail associé)</li>
        <li> <strong>Thèse</strong> : un lien vers la thèse concernée</li>
        <li> <strong>Correction</strong> : le type de correction</li>
        <li> <strong>Version corrigée</strong> : le fait que la version corrigée a été déposée (et est archivable)</li>
        <li> <strong>Validation</strong> : le fait qu'une validation de la version corrigée a été faite</li>
    </ul>

    <p>
        Les actions associées sont :
    </p>
    <ul>
        <li> <span class="icon icon-plus"></span> ajouter manuellement un mail pour pouvoir créer un compte ;</li>
        <li> <span class="icon icon-delete"></span> supprimer le mail renseigné manuellement; </li>
        <li> <span class="icon icon-notify"></span> création d'un compte (si nécessaire) puis notification du président.</li>
    </ul>


<div class="main">
    <table id="president-jury" class="table table-sm" >
        <thead>
            <tr>
                <th> Dénomination du président </th>
                <th> Utilisateur </th>
                <th> Individu<br/>Mail</th>
                <th> Membre<br/>Mail</th>
                <th> These </th>
                <th> Correction </th>
                <th> Version<br/>corrigée </th>
                <th> Validation </th>
                <th> Action </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($presidents as $president) : ?>
                <?php
                    $utilisateurs = $president->getIndividu()->getUtilisateurs();
                ?>
                <tr>
                    <td> <?php echo afficherActeur($president); ?> </td>
                    <td> <center><?php echo afficherUtilisateur($president); ?> </center></td>
                    <td> <center><?php echo afficherMailIndividu($president); ?> </center></td>
                    <td> <center><?php echo afficherMailMembre($president) ; ?> </center></td>
                    <td> <?php echo afficherThese($president, $this); ?> </td>
                    <td> <?php echo afficherCorrection($president); ?> </td>
                    <td> <center><?php echo afficherCorrectionEffectuees($president); ?> </center></td>
                    <td> <?php echo afficherValidations($president); ?> </td>
                    <td>
                        <?php $validations = $president->getThese()->getValidations('CORRECTION_THESE')->toArray(); ?>
                        <?php if (empty($validations)) : ?>
                            <?php if ($canModifierMailPresident) : ?>
                                <?php if (empty($utilisateurs)) : ?>

                                    <!--  // Si aucun membre de  soutenance on peut ajouter un membre factisse pour porter l'information ne remontant pas du SI -->
                                    <?php if ($president->getMembre() === null) : ?>
                                        <?php /** @see \These\Controller\PresidentJuryController::ajouterMailAction() */ ?>
                                        <a href="<?php echo $this->url('president-jury/ajouter-mail', ['president' => $president->getId()], [], true); ?>"
                                           class="ajax-modal" data-event="modification"
                                           title="Ajout d'un email pour le président du jury"
                                        >
                                            <span class="icon icon-plus"></span> </a>
                                    <?php else :?>

                                        <!-- // Si membre factisse alors on peut le supprimer pour eventuellement le modifier -->
                                        <?php if ($president->getMembre()->getProposition()->getId() === 0) : ?>
                                            <?php /** @see \These\Controller\PresidentJuryController::supprimerMailAction() */ ?>
                                            <a href="<?php echo $this->url('president-jury/supprimer-mail', ['president' => $president->getId()], [], true); ?>"
                                               title="Suppression de l'email ajouté manuellement pour le président du jury"
                                            >
                                                <span class="icon icon-delete iconly text-danger"></span> </a>
                                        <?php else : ?>
                                            <span class="icon icon-plus" style="color:white;"></span>
                                        <?php endif;?>

                                    <?php endif;?>
                                <?php else:?>
                                    <span class="icon icon-plus" style="color:white;"></span>
                                <?php endif;?>
                            <?php endif; ?>

                            <?php if ($canNotifierPresident) : ?>
                                <?php if (!empty($utilisateurs) OR ($president->getIndividu() AND $president->getIndividu()->getEmailPro()) OR ($president->getMembre() AND $president->getMembre()->getEmail())) : ?>
                                    <?php /** @see \These\Controller\PresidentJuryController::notifierCorrectionAction() */ ?>
                                    <a href="<?php
                                        if (!empty($utilisateurs) AND ($president->getIndividu() === null OR $president->getIndividu()->getEmailPro() === null) AND ($president->getMembre() === null OR $president->getMembre()->getEmail() === null)) {
                                            echo $this->url('president-jury/notifier-correction', ['president' => $president->getId()], ['query' => ['utilisateur' => end($utilisateurs)->getId()]], true);
                                        } else {
                                            echo $this->url('president-jury/notifier-correction', ['president' => $president->getId()], [], true);
                                        }
                                        ?>"
                                       title="Création du compte (si nécessaire) & notification du président du jury"
                                    >
                                        <span class="icon icon-notify"></span>
                                    </a>
                                <?php else : ?>
                                    <span class="icon icon-notify" style="color:white;"></span>
                                <?php endif; ?>
                            <?php endif; ?>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
        <caption>Liste des présidents du jury de thèses avec des corrections <strong>soutenues dans les 4 derniers mois</strong>.</caption>
    </table>
</div>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>