<?php

/**
 * @var Qualite[] $qualites
 */

use Soutenance\Entity\Qualite;
use Soutenance\Entity\QualiteLibelleSupplementaire;
use Soutenance\Provider\Privilege\QualitePrivileges;


$canEdit = $this->isAllowed(QualitePrivileges::getResourceId(QualitePrivileges::SOUTENANCE_QUALITE_MODIFIER));;
$canDelete = $this->isAllowed(QualitePrivileges::getResourceId(QualitePrivileges::SOUTENANCE_QUALITE_MODIFIER));;
?>

<?php $this->headTitle("Qualités des membres de jury"); ?>

<h1 class="page-header">
    Qualités des membres de jury
</h1>


<a
    <?php /** @see \Soutenance\Controller\Qualite\QualiteController::editerAction() */ ?>
   class="ajax-modal btn btn-primary"
   data-event="edition-qualite"
   href="<?php echo $this->url('qualite/editer', [], [], true); ?>">
        <span class="glyphicon glyphicon-plus"></span>
        Ajouter une qualité
</a>

<br/><br/>

<table class="table table-extra-condensed">
    <thead>
        <tr>
            <th> Rang </th>
            <th> Libellé </th>
            <th> HDR </th>
            <th> Émeritat </th>
            <th> Actions </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($qualites as $qualite): ?>
        <tr>
            <td> <?php echo $qualite->getRang(); ?> </td>
            <td>
                    <div class="toggle" id="_<?php echo $qualite->getId(); ?>">
                    <?php
                    $sups = $qualite->getLibellesSupplementaires()->toArray();
                    $sups = array_filter($sups, function(QualiteLibelleSupplementaire $a) { return $a->getHistoDestruction() === null;});
                    usort($sups, function (QualiteLibelleSupplementaire $a, QualiteLibelleSupplementaire $b) { return $a->getLibelle() > $b->getLibelle();});
                    ?>

                    <?php echo $qualite->getLibelle(); ?> (<?php echo count($sups) ?>)
                    </div>

                    <div class="display" id="d_<?php echo $qualite->getId(); ?>" style="display: none;">
                    <?php foreach ($sups as $sup) : ?>
                        <br/>
                        >>> <?php echo $sup->getLibelle(); ?>
                        <?php if ($canEdit) : ?>
                            <a <?php /** @see \Soutenance\Controller\Qualite\QualiteController::retirerLibelleSupplementaireAction() */ ?>
                               href="<?php echo $this->url('qualite/retirer-libelle-supplementaire', ['libelle' => $sup->getId()], [], true); ?>">
                            <span class="glyphicon glyphicon-minus" title="Retirer le libellé supplémentaire"></span></a>
                        <?php endif; ?>
                    <?php endforeach;?>
                    </div>
            </td>
            <td>
                <?php if ($qualite->isHDR()): ?>
                    <span class="glyphicon glyphicon-ok text-success"></span>
                    <?php $hasVisio = true; ?>
                <?php else: ?>
                    <span class="glyphicon glyphicon-remove text-danger"></span>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($qualite->isEmeritat()): ?>
                    <span class="glyphicon glyphicon-ok text-success"></span>
                    <?php $hasVisio = true; ?>
                <?php else: ?>
                    <span class="glyphicon glyphicon-remove text-danger"></span>
                <?php endif; ?>
            </td>
            <td>
                <?php if($canEdit): ?>
                    <a
                        <?php /** @see \Soutenance\Controller\Qualite\QualiteController::editerAction() */ ?>
                        class="ajax-modal"
                       data-event="edition-qualite"
                       href="<?php echo $this->url('qualite/editer', ['qualite' => $qualite->getId()], [], true); ?>">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                <?php endif; ?>
                <?php if($canEdit): ?>
                    <a  <?php /** @see \Soutenance\Controller\Qualite\QualiteController::ajouterLibelleSupplementaireAction() */ ?>
                        class="ajax-modal"
                        data-event="edition-qualite"
                        href="<?php echo $this->url('qualite/ajouter-libelle-supplementaire', ['qualite' => $qualite->getId()], [], true); ?>">
                        <span class="glyphicon glyphicon-plus" title="Ajouter un libellé supplémentaire"></span>
                    </a>
                <?php endif; ?>
                <?php if($canDelete): ?>
                    <a
                        <?php /** @see \Soutenance\Controller\Qualite\QualiteController::effacerAction() */ ?>
                        href="<?php echo $this->url('qualite/effacer', ['qualite' => $qualite->getId()], [], true); ?>">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>

</table>

<script>
    $(function() {
        $("body").on("edition-qualite", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });

    $(function() {
        $("div.toggle").click(function event() {
            let id = $(this).attr('id');
            $("div#d" + id).toggle();
        });
    });
</script>