<?php

/**
 * @var Qualite[] $qualites
 */

use Soutenance\Entity\Qualite;
use Soutenance\Provider\Privilege\QualitePrivileges;


$canEdit = $this->isAllowed(QualitePrivileges::getResourceId(QualitePrivileges::SOUTENANCE_QUALITE_MODIFIER));;
$canDelete = $this->isAllowed(QualitePrivileges::getResourceId(QualitePrivileges::SOUTENANCE_QUALITE_MODIFIER));;
?>

<?php $this->headTitle("Qualités des membres de jury"); ?>

<h1 class="page-header">
    Qualités des membres de jury
</h1>


<a class="ajax-modal btn btn-primary"
   data-event="edition-qualite"
   href="<?php echo $this->url('qualite/editer', [], [], true); ?>">
        <span class="glyphicon glyphicon-plus"></span>
        Ajouter une qualité
</a>

<br/><br/>

<table class="table table-extra-condensed">
    <thead>
        <tr>
            <th> Rang </th>
            <th> Libellé </th>
            <th> HDR </th>
            <th> Actions </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($qualites as $qualite): ?>
        <tr>
            <td> <?php echo $qualite->getRang(); ?> </td>
            <td> <?php echo $qualite->getLibelle(); ?> </td>
            <td>
                <?php if ($qualite->getHdr() === 'O'): ?>
                    <span class="glyphicon glyphicon-ok text-success"></span>
                    <?php $hasVisio = true; ?>
                <?php else: ?>
                    <span class="glyphicon glyphicon-remove text-danger"></span>
                <?php endif; ?>
            </td>
            <td>
                <?php if($canEdit): ?>
                    <a class="ajax-modal"
                       data-event="edition-qualite"
                       href="<?php echo $this->url('qualite/editer', ['qualite' => $qualite->getId()], [], true); ?>">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                <?php endif; ?>
                <?php if($canDelete): ?>
                    <a href="<?php echo $this->url('qualite/effacer', ['qualite' => $qualite->getId()], [], true); ?>">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>

</table>

<script>
    $(function() {
        $("body").on("edition-qualite", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>