<?php

namespace Application;

use Formation\Provider\Privilege\FormationPrivileges;
use Formation\Service\Formation\Search\FormationSearchService;
use Laminas\Paginator\Paginator as LaminasPaginator;

/**
 * @var string $title
 * @var LaminasPaginator $paginator
 * @var string $routeName
 * @var string $returnUrl
 *
 * @see \Formation\Controller\Recherche\FormationRechercheController::indexAction()
 */

$this->headTitle($this->translate($title));

$canAfficherFormation      = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::FORMATION_AFFICHER));
$canAjouterFormation       = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::FORMATION_AJOUTER));
$canHistoriserFormation    = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::FORMATION_HISTORISER));
$canSupprimerFormation     = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::FORMATION_SUPPRIMER));
?>

<h1 class="page-header"><?php echo $title ?></h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace(); ?>


<!-- Formulaire de filtrage -->
<div class="float-start">
    <?php $loadFiltersUrl = $this->url($routeName . '/filters', [], ['query' => $this->queryParams()], true); ?>
    <div id="filters" data-url="<?php echo $loadFiltersUrl ?>" style="min-height: 160px">
        <!-- Contenu chargé en AJAX -->
    </div>
</div>
<div class="clearfix"></div>


<?php if ($canAjouterFormation) : ?>
    <a
        <?php /** @see \Formation\Controller\FormationController::ajouterAction() */ ?>
            href="<?php echo $this->url('formation/formation/ajouter', [], [], true); ?>"
            class="btn btn-primary action ajax-modal" data-event="modification">
        <span class="icon icon-ajouter"></span>
        Ajouter une formation
    </a>
<?php endif; ?>


<div class="index-result">
    <?php if (count($paginator) > 0): ?>

    <p>
        <?php echo $paginator->getTotalItemCount() . ' ' . $this->translate("formation·s trouvée·s.") ?>
    </p>

    <table class="table table-sm table-hover">
        <thead>
        <tr>
            <th>
                <a href="<?php echo $s = $this->sortable(FormationSearchService::NAME_libelle) ?>"
                   title="<?php echo $this->translate("Libellé") ?> ">
                    <?php echo $this->translate("Libellé") ?>
                </a> <?php echo $s->icon() ?>
            </th>
            <th>
                <a href="<?php echo $s = $this->sortable(FormationSearchService::NAME_site) ?>"
                   title="<?php echo $this->translate("Site") ?> ">
                    <?php echo $this->translate("Site") ?>*
                </a> <?php echo $s->icon() ?>
            </th>
            <th>
                <a href="<?php echo $s = $this->sortable(FormationSearchService::NAME_responsable) ?>"
                   title="<?php echo $this->translate("Responsable") ?> ">
                    <?php echo $this->translate("Responsable") ?>*
                </a> <?php echo $s->icon() ?>
            </th>
            <th>
                <a href="<?php echo $s = $this->sortable(FormationSearchService::NAME_modalite) ?>"
                   title="<?php echo $this->translate("Modalité") ?> ">
                    <?php echo $this->translate("Modalité") ?>*
                </a> <?php echo $s->icon() ?>
            </th>
            <th>
                Type<span title="valeur par défaut">*</span>
            </th>
            <th>
                Effectif des listes<span title="valeur par défaut">*</span>
            </th>
            <th>
                #Session
            </th>
            <th style="min-width: 4rem;">
                Action
            </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($paginator as $formation) : ?>
            <tr>
                <td>
                    <span class="  <?php if ($formation->estHistorise()) echo " historise text-danger"; ?> ">
                        <span class="formation-typage">Formation</span>
                        <?php echo $formation->getLibelle(); ?>
                        <?php if ($formation->getDescription() !== null AND trim($formation->getDescription()) !== null) : ?>
                            <span class="icon icon-info"
                                  title="<?php echo $formation->getDescription(); ?>" data-bs-toggle="tooltip" data-bs-html="true"
                            ></span>
                        <?php endif; ?>
                        <br>
                        <span class="formation-typage">Module</span>
                        <?php if ($formation->getModule()) : ?>
                            <?php echo $formation->getModule()->getLibelle(); ?>
                            <?php if ($formation->getModule()->getDescription() !== null AND trim($formation->getModule()->getDescription()) !== null) : ?>
                                <span class="icon icon-info"
                                      title="<?php echo $formation->getModule()->getDescription(); ?>" data-bs-toggle="tooltip" data-bs-html="true"
                                ></span>
                            <?php endif; ?>
                        <?php else : ?>
                            <i>Aucun module de spécifié</i>
                        <?php endif; ?>
                    </span>
                </td>
                <td> <?php echo $this->site($formation); ?> </td>
                <td>
                    <?php if ($formation->getResponsable()) : ?>
                        <?php echo $formation->getResponsable()->getNomComplet(); ?>
                    <?php else : ?>
                        N.C.
                    <?php endif; ?>
                </td>
                <td> <?php echo $this->modalite($formation); ?> </td>
                <td> <?php echo $this->type($formation); ?> </td>
                <td>
                    Liste principale :
                    <?php echo $formation->getTailleListePrincipale()?:"N.C."; ?>
                    <br/>
                    Liste complémentaire :
                    <?php echo $formation->getTailleListeComplementaire()?:"N.C."; ?>
                </td>
                <td>
                    <?php echo count($formation->getSessions()); ?>
                </td>
                <td>
                    <?php if ($canAfficherFormation) : ?>
                        <?php /** @see \Formation\Controller\FormationController::afficherAction() */ ?>
                        <a href="<?php echo $this->url('formation/formation/afficher', ['formation' => $formation->getId()], [], true); ?>"
                           title="afficher la formation #<?php echo $formation->getId(); ?>"
                           data-bs-toggle="tooltip" data-bs-html="true">
                            <span class="icon icon-voir"></span>
                        </a>
                    <?php endif; ?>
                    <?php if ($canHistoriserFormation) : ?>
                        <?php if ($formation->estNonHistorise()) : ?>
                            <?php /** @see \Formation\Controller\FormationController::historiserAction() */ ?>
                            <a href="<?php echo $this->url('formation/formation/historiser', ['formation' => $formation->getId()], [], true); ?>"
                               title="Historiser la formation #<?php echo $formation->getId(); ?>"
                               data-bs-toggle="tooltip" data-bs-html="true">
                                <span class="icon icon-historiser"></span>
                            </a>
                        <?php else : ?>
                            <?php /** @see \Formation\Controller\FormationController::restaurerAction() */ ?>
                            <a href="<?php echo $this->url('formation/formation/restaurer', ['formation' => $formation->getId()], [], true); ?>"
                               title="Restaurer la formation #<?php echo $formation->getId(); ?>"
                               data-bs-toggle="tooltip" data-bs-html="true">
                                <span class="icon icon-restaurer"></span>
                            </a>
                        <?php endif; ?>
                    <?php endif; ?>

                    <?php if ($canSupprimerFormation and $formation->estHistorise()) : ?>
                        <?php /** @see \Formation\Controller\FormationController::supprimerAction() */?>
                        <a href="<?php echo $this->url('formation/formation/supprimer',['formation' => $formation->getId()], [], true); ?>"
                           class="ajax-modal" data-event="modification"
                           title="Suppression de la formation #<?php echo $formation->getId(); ?>" data-bs-toggle="tooltip" data-bs-html="true">
                            <span class="icon icon-detruire text-danger"></span>
                        </a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <script>
        $(function () {
            $('[data-bs-toggle="tooltip"]').tooltip({});
        });
        $(function() {
            $("body").on("modification", function (event) {
                event.div.modal('hide');
                window.location.reload();
            });

        });
    </script>

    <?php echo $this->paginationControl($paginator, 'sliding', 'paginator', ['route' => $routeName . '/recherche/index']) ?>

<?php else: ?>

    <p>Aucune formation trouvée.</p>

<?php endif ?>
</div>

<script>
    $(function() {
        $("#filters").addClass("loading").refresh(null, function() { $(this).removeClass("loading"); });
    });
</script>