<?php

use Doctorant\Entity\Db\Doctorant;
use These\Entity\Db\These;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var These $these
 * @var string $contact
 * @var Doctorant $doctorant
 * @var bool  $emailDoctorantAbsent
 */
?>

<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application <?php echo $this->appInfos()->nom ?>.
</p>
<?php if ($emailDoctorantAbsent): ?>
<p>
    <em>Ce mail aurait dû être envoyé à <?php echo $doctorant ?> (<?php echo $doctorant->getSourceCode() ?>)
    mais aucune adresse électronique n'a été trouvée pour ce doctorant.</em>
</p>
<?php endif ?>
<p>
    Votre dossier est complet.
</p>
<p>
    Vous serez contacté par la gestionnaire de votre école doctorale pour récupérer votre attestation de réussite au diplôme de doctorat à la Maison du doctorat.
    Vous pouvez en faire la demande à l'adresse de votre école doctorale par mail.
</p>

