<?php

use These\Entity\Db\These;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var string $type
 * @var These $these
 */

$appName = $this->appInfos()->nom;
?>

<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application <?php echo $appName ?>.
</p>
<p>
    Vous êtes informé-e que <?php echo $type; ?> associé à la thèse [<?php echo $these->getId() ?> | <?php echo $these->getTitre() ?>] est manquante.<br/>
    Il est nécessaire de compléter cette information dans le système d'information de votre établissement.
</p>
