<?php

use These\Entity\Db\These;
use Fichier\Entity\Db\VersionFichier;
use Application\Filter\IdifyFilter;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var array $manques
 * @var These $these
 */

$appName = $this->appInfos()->nom;
?>

<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application <?php echo $appName ?>.
</p>
<p>
    Des informations associées à la thèse [<?php echo $these->getId() ?> | <?php echo $these->getTitre() ?>] sont manquantes :
    <ul>
        <?php foreach($manques as $manquante):?>
        <li> <?php echo $manquante; ?> </li>
        <?php endforeach; ?>
    </ul>
    Il est nécessaire de compléter cette information dans le système d'information de votre établissement.
</p>
