<?php

use UnicaenImport\Entity\Differentiel\Query;
use UnicaenImport\Provider\Privilege\Privileges;

/* @var $tables array */
/* @var $mviews array */


$this->headTitle()->append("Import de données");

$canMaj = $this->isAllowed(Privileges::getResourceId(Privileges::IMPORT_MAJ));

?>
<h1 class="page-header">Écarts</h1>

<?php echo $this->partial('unicaen-import/import/menu', ['active'=> 'index'] ); ?>

<div class="row differentiel"
     data-url-synchronisation="<?php echo $this->url('import', ['action' => 'synchronisation']) ?>"
     data-url-differentiel="<?php echo $this->url('import', ['action' => 'differentiel']) ?>"
     data-can-maj="<?php echo $canMaj ? 'true' : 'false' ?>">
    <?php

    foreach ($tables as $table) {
        $tableLabel = ucwords(str_replace('_', ' ', strtolower($table)));

        ?>
        <div class="col-md-6">
            <div class="panel panel-default import-panel" id="<?php echo $table ?>">
                <div class="panel-heading"><strong><?php echo $tableLabel ?></strong></div>
                <table class="table table-condensed import-table" id="<?php echo $table ?>">
                    <tr>
                        <td style="width:20%">Nouveau</td>
                        <td style="width:30%" class="action <?php echo Query::ACTION_INSERT ?>"></td>

                        <td style="width:20%">Mise à jour</td>
                        <td style="width:30%" class="action <?php echo Query::ACTION_UPDATE ?>"></td>
                    </tr>
                    <tr>
                        <td style="width:20%">Suppression</td>
                        <td style="width:30%" class="action <?php echo Query::ACTION_DELETE ?>"></td>

                        <td style="width:20%">Restauration</td>
                        <td style="width:30%" class="action <?php echo Query::ACTION_UNDELETE ?>"></td>
                    </tr>
                </table>
                <div class="panel-body">

                </div>
                <div class="panel-footer">
                    <button type="button" class="btn btn-default btn-refresh" data-id="<?php echo $table ?>"><span
                                class="glyphicon glyphicon-refresh"></span> Recharger
                    </button>
                    <?php if ($canMaj): ?>
                        <?php if (in_array($table, $mviews)): ?>
                            <button type="button" class="btn btn-info btn-vuemat" data-id="<?php echo $table ?>"><span
                                        class="glyphicon glyphicon-list"></span> MAJ vue matérialisée
                            </button>
                        <?php endif; ?>
                        <button type="button" class="btn btn-warning btn-actu" data-id="<?php echo $table ?>"><span
                                    class="glyphicon glyphicon-import"></span> Synchroniser
                        </button>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <?php
    }

    ?>
</div>
<style>

    .differentiel .import-panel .panel-body {
        max-height: 12.5em;
        overflow: auto;
    }

    .btn-actu {
        display: none;
    }

    .btn-details {
        margin-top: -5px;
        margin-bottom: -5px;
    }

    .btn-sync-action {
        margin-top: -5px;
        margin-bottom: -5px;
    }

</style>
<script>

    $.widget("unicaenImport.differentiel", {

        reloadTable: function (tableName, action)
        {
            var that = this;
            var url = this.element.data('url-synchronisation');
            var params = {
                action: action
            };
            var selector = '.import-panel table.import-table#' + tableName + ' td.action';
            if (action && action != 'all' && action != 'vue-materialisee') {
                selector += '.' + action;
            }

            this.element.find(selector).html('<div class="loading"></div>');
            this.clearMsgs(tableName);

            $.post(url + '/' + tableName, params, function (data)
            {
                var sel = '.import-panel table.import-table#' + tableName + ' td.action.';
                var actions = ['insert', 'update', 'delete', 'undelete'];
                var total = 0;

                for (var i in actions) {
                    total += data.chiffres[actions[i]];
                    if (action == undefined || action == 'all' || action == 'vue-materialisee' || action == actions[i]) {
                        var chiffre = data.chiffres[actions[i]];
                        if (chiffre > 0) {
                            chiffre += ' <button class="btn btn-xs btn-primary btn-details" title="Voir le détail" data-action="' + actions[i] + '"><span class="glyphicon glyphicon-search"></span></button>';
                            if (that.element.data('can-maj')) {
                                chiffre += ' <button class="btn btn-xs btn-warning btn-sync-action" title="Synchroniser" data-action="' + actions[i] + '"><span class="glyphicon glyphicon-import"></span></button>';
                            }
                        }
                        that.element.find(sel + actions[i]).html(chiffre);
                        that.element.find(sel + actions[i] + ' .btn-details').click(function ()
                        {
                            that.showDetails(tableName, $(this).data('action'));
                        });
                        that.element.find(sel + actions[i] + ' .btn-sync-action').click(function ()
                        {
                            that.reloadTable(tableName, $(this).data('action'));
                        });
                    }
                }

                if (total > 0) {
                    that.element.find('.import-panel#' + tableName + ' .btn-actu').show();
                } else {
                    that.element.find('.import-panel#' + tableName + ' .btn-actu').hide();
                }

                for (var e in data.errors) {
                    that.addMsg(tableName, data.errors[e], 'danger');
                }
                for (var s in data.success) {
                    that.addMsg(tableName, data.success[s], 'success');
                }
            }).fail(function (jqXHR)
            {
                alertFlash(jqXHR.responseText, 'danger', 5000);
                console.log(jqXHR);
            });
        },

        addMsg: function (table, text, type)
        {
            if (text == '') return;

            var div = this.element.find('.import-panel#' + table + ' .panel-body');

            div.show();
            div.append('<div class="alert alert-' + type + ' alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>' + text + '</div>');
        },

        clearMsgs: function (table)
        {
            var div;
            if (table) {
                div = this.element.find('.import-panel#' + table + ' .panel-body');
                div.html('');
                div.hide();
            } else {
                div = this.element.find('.import-panel .panel-body');
                div.html('');
                div.hide();
            }
        },



        showDetails: function (table, action)
        {
            var that = this;
            var url = this.element.data('url-differentiel');
            var params = {
                action: action
            };
            var div = this.element.find('.import-panel#' + table + ' .panel-body');

            div.show();
            div.html('Chargement en cours... <div class="loading"></div>');

            $.post(url + '/' + table, params, function (data)
            {
                div.html(data);
            }).fail(function (jqXHR)
            {
                alertFlash(jqXHR.responseText, 'danger', 5000);
                console.log(jqXHR);
            });
        },



        refreshAll: function ()
        {
            var that = this;

            this.element.find('.import-table').each(function ()
            {
                that.reloadTable($(this).attr('id'));
            });
        },

        _create: function ()
        {
            var that = this;

            this.element.find('.btn-vuemat').click(function ()
            {
                that.reloadTable($(this).data('id'), 'vue-materialisee');
            });

            this.element.find('.btn-refresh').click(function ()
            {
                that.reloadTable($(this).data('id'));
            });

            this.element.find('.btn-actu').click(function ()
            {
                that.reloadTable($(this).data('id'), 'all');
            });

            this.refreshAll();
        },
    });


    $(function ()
    {
        WidgetInitializer.add('differentiel', 'differentiel');
    });

</script>