<?php

use UnicaenImport\Provider\Privilege\Privileges;

/* @var $active string */

$pages = [
    'index' => [
        'url'     => $this->url('import'),
        'label'   => 'Synchronisation',
        'visible' => $this->isAllowed(Privileges::getResourceId(Privileges::IMPORT_ECARTS)),
        'popover' => false,
        'icon'    => 'icon icon-import',
    ],
    'tbl'   => [
        'url'     => $this->url('import', ['action' => 'tableau-bord']),
        'label'   => 'Branchement',
        'visible' => $this->isAllowed(Privileges::getResourceId(Privileges::IMPORT_TBL)),
        'popover' => false,
        'icon'    => 'fas fa-list',
    ],
    'majvp' => [
        'url'     => $this->url('import', ['action' => 'update-views-and-packages']),
        'label'   => 'Mise à jour des vues et procédures d\'import',
        'visible' => $this->isAllowed(Privileges::getResourceId(Privileges::IMPORT_VUES_PROCEDURES)),
        'popover' => false,
        'icon'    => 'fas fa-wrench',
    ],
];

?>
<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-bs-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="visually-hidden">Menu Import</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Import</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <?php foreach ($pages as $page => $params) {
                    if ($params['visible']) {
                        $lip = [];
                        $ap  = [
                            'href' => $params['url'],
                            'data-bs-placement' => 'bottom',
                        ];

                        if ($page == $active) {
                            $lip['class'] = 'active';
                        }

                        if ($params['popover']){
                            $ap['class'] = 'ajax-popover';
                        }
                        echo $this->tag('li', $lip)->html(
                            $this->tag('a', $ap)->html($this->tag('span',['class' => $params['icon']])->text().' '.$params['label'])
                        );
                    }
                } ?>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>