<?php
    /**
     * @var These $these
     * @var Proposition $proposition
     * @var Doctorant $doctorant
     * @var Acteur[] $directeurs
     */

use Application\Entity\Db\Acteur;
use Application\Entity\Db\Doctorant;
use Application\Entity\Db\These;
use Soutenance\Entity\Membre;
use Soutenance\Entity\Proposition;

?>

<style>
    .badge-success {
        background-color: #468847;
    }

    .badge-error {
        background-color: #881f18;
    }

    .action {
        width: 20em;
        margin:1ex;
    }

</style>

<?php $this->headTitle($this->translate("Proposition de soutenance")); ?>
<h1 class="page-header">
    Proposition de soutenance
</h1>

<p class="">
    Afin d'être validée et traitée par l'école doctorale, la proposition de soutenance doit être validée par tous les intervenants immédiats de la thèse (c.-à-d. doctorant, directeur et co-directeur(s)).
</p>

<p class="">
    <span class="glyphicon glyphicon-warning-sign"></span> En cas de modifications de la proposition, toutes validations (ou refus) seront annulées et la proposition devra être à nouveau être validée.
</p>


<?php
    $datelieu = false;
    if ($proposition->getDate() && $proposition->getLieu()) $datelieu = true;
?>

<div class="panel <?php echo ($datelieu)?'panel-success':'panel-danger'; ?>">
    <div class="panel-heading">
        <h4>
            Date/Heure et lieu de la soutenance
        </h4>
    </div>
    <div class="panel-body">
        <div class="pull-left">
            <ul>
                <li>
                    Date de la soutenance :
                    <?php echo ($proposition->getDate())?$proposition->getDate()->format("d/m/Y"):'<strong>non communiquée</strong>'; ?>
                </li>
                <li>
                    Heure de la soutenance :
                    <?php echo ($proposition->getDate())?$proposition->getDate()->format("H:i:s"):'<strong>non communiquée</strong>'; ?>
                </li>
                <li>
                    Lieu de la Soutenance :
                    <?php echo ($proposition->getLieu())?$proposition->getLieu():'<strong>non communiqué</strong>'; ?>
                </li>
            </ul>
        </div>
        <div class="pull-right">
            <!-- TODO remettre la modale -->
            <a
                href="<?php echo $this->url('soutenance/constituer/modifier-date-lieu', ['these' => $these->getId()], [], true); ?>"
                class="btn btn-primary action zajax-modal"
                data-event="edition-datelieu"
            >
                <span class="glyphicon glyphicon-pencil"></span> Éditer lieu et date de la soutenace
            </a>
        </div>
    </div>
</div>

<?php
    $indicateurs = $proposition->computeIndicateur();
?>

<div class="panel <?php echo ($indicateurs["valide"])?'panel-success':'panel-danger'; ?>">
    <div class="panel-heading">
        <h4>
            Indicateurs liés à la validité du jury de thèse
        </h4>
    </div>
    <div class="panel-body">

        <div class="col-md-3">
            <h4>
                Parité de genre
                <?php if ($indicateurs["parité"]["valide"]):?>
                    <span class="badge badge-success"> Valide </span>
                <?php else: ?>
                    <span class="badge badge-error"> Non valide </span>
                <?php endif; ?>
            </h4>

            <div class="progress">
                <div class="progress-bar progress-bar-success" style="width:<?php echo $indicateurs["parité"]["Femme"]*100; ?>%;"> Femme </div>
                <div class="progress-bar progress-bar-danger"  style="width:<?php echo $indicateurs["parité"]["Homme"]*100; ?>%;"> Homme</div>
            </div>

        </div>
        <div class="col-md-3">
            <h4>
                Nombre de rapporteurs
                <?php if ($indicateurs["rapporteur"]["valide"]):?>
                    <span class="badge badge-success"> Valide </span>
                <?php else: ?>
                    <span class="badge badge-error"> Non valide </span>
                <?php endif; ?>
            </h4>

            <div class="progress">
                <div class="progress-bar progress-bar-info" style="width:<?php echo $indicateurs["rapporteur"]["Ratio"]*100; ?>%;">
                    <?php echo $indicateurs["rapporteur"]["Nombre"]; ?>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <h4>
            Nombre <!--de membres--> de rang A
                <?php if ($indicateurs["rang A"]["valide"]):?>
                    <span class="badge badge-success"> Valide </span>
                <?php else: ?>
                    <span class="badge badge-error"> Non valide </span>
                <?php endif; ?>
            </h4>

            <div class="progress">
                <div class="progress">
                    <div class="progress-bar progress-bar-info" style="width:<?php echo $indicateurs["rang A"]["Ratio"]*100; ?>%;">
                        <?php echo $indicateurs["rang A"]["Nombre"]; ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <h4>
            Nombre <!--de membres--> d'extérieurs
                <?php if ($indicateurs["exterieur"]["valide"]):?>
                    <span class="badge badge-success"> Valide </span>
                <?php else: ?>
                    <span class="badge badge-error"> Non valide </span>
                <?php endif; ?>
            </h4>
            <div class="progress">
                <div class="progress-bar progress-bar-info" style="width:<?php echo $indicateurs["exterieur"]["Ratio"]*100; ?>%;">
                    <?php echo $indicateurs["exterieur"]["Nombre"]; ?>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">
        <h4>
            Composition du jury
        </h4>
    </div>
    <div class="panel-body">
        <div class="col-md-9 pull-left">
            <table class="table table-extra-condensed">
                <thead>
                <tr>
                    <th>Dénomination</th>
                    <th>Adresse électronique</th>
                    <th>Genre</th>
                    <th>Qualité</th>
                    <th>Rang</th>
                    <th>Etablissement</th>
                    <th>Rôle</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                    <?php /** @var Membre $membre */ ?>
                    <?php foreach($proposition->getMembres() as $membre): ?>
                        <tr>
                            <td> <?php echo $membre->getDenomination(); ?> </td>
                            <td> <?php echo $membre->getEmail(); ?> </td>
                            <td> <?php echo $membre->getGenre(); ?> </td>
                            <td> <?php echo $membre->getQualite()->getLibelle(); ?> </td>
                            <td> <?php echo $membre->getRang(); ?> </td>
                            <td> <?php echo $membre->getEtablissement(); ?> </td>
                            <td> <?php echo $membre->getRole(); ?> </td>
                            <td>
                                <a href="<?php echo $this->url('soutenance/constituer/modifier-membre', ['these' => $these->getId(), 'membre' => $membre->getId()], [] ,true); ?>">
                                    <span class="glyphicon glyphicon-pencil"></span>
                                </a>
                                <a href="<?php echo $this->url('soutenance/constituer/effacer-membre', ['these' => $these->getId(), 'membre' => $membre->getId()], [] ,true); ?>">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <div class="pull-right">
            <a
                href="<?php echo $this->url('soutenance/constituer/modifier-membre', ['these' => $these->getId()], [], true); ?>"
                class="btn btn-primary action zajax-modal"
                data-event="edition-membre">
                    <span class="glyphicon glyphicon-plus"></span> Ajouter un membre de jury
            </a>
        </div>

    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">
        <h4>
            Validation de la proposition de soutenance
        </h4>
    </div>
    <div class="panel-body">
        <div class="col-md-8">
            <h4>
                Liste des validations
            </h4>

            <ul>
                <li>
                    <?php echo $doctorant->getIndividu()->getNomComplet(false, false, false, true); ?> (Doctorant)
                    <br/>
                    <?php if ($validations[$doctorant->getIndividu()->getId()]) : ?>
                        <span class="badge badge-success"> Validée</span>
                    <?php else: ?>
                        <span class="badge badge-default"> Aucune validation</span>
                    <?php endif; ?>

                </li>
                <?php foreach ($directeurs as $directeur): ?>
                <li>
                    <?php echo $directeur->getIndividu()->getNomComplet(false,false,false, true); ?> (Directeur)
                    <br/>
                    <?php if ($validations[$directeur->getIndividu()->getId()]) : ?>
                        <span class="badge badge-success"> Validée</span>
                    <?php else: ?>
                        <span class="badge badge-default"> Aucune validation</span>
                    <?php endif; ?>
                </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <div class="pull-right">
            <a
                    href="<?php echo $this->url('soutenance/constituer/valider', ['these' => $these->getId()], [], true); ?>"
                    class="btn btn-success action ">
                <span class="glyphicon glyphicon-ok"></span> Valider la proposition de soutenance
            </a> <br/>
<!--            <a href="--><?php //echo $this->url('soutenance/constituer/refuser', ['these' => $these->getId()], [], true); ?><!--" class="btn btn-danger action"><span class="glyphicon glyphicon-remove"></span> Rejeter la proposition de soutenance</a>-->
        </div>
    </div>
</div>




<script>
    $(function() {
        $("body").on("edition-datelieu", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>