<?php
    /**
     *
     */
?>

<style>
    .badge-error {
        background-color: #b94a48;
    }

    .badge-success {
        background-color: #468847;
    }
</style>

<h1 class="page-header">
    Préparation de la soutenance et constution du jury
</h1>

<div class="panel panel-danger">
    <div class="panel-heading">
        <h4>
            Date/Heure et lieu de la soutenance
        </h4>
    </div>
    <div class="panel-body">
<!--        <span class="badge badge-error">Non valide</span>-->
        <ul>
            <li> Date de la soutenance : non communiquée</li>
            <li> Heure de la soutenance : non communiquée </li>
            <li> Lieu de la Soutenance : non communiqué</li>
        </ul>
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">
        <h4>
            Indicateurs liés à la validité du jury de thèse
        </h4>
    </div>
    <div class="panel-body">
<!--        <span class="badge badge-success">Valide</span>-->
        <div class="col-md-4">
            <h3>
                Parité de genre :
<!--                <span class="glyphicon glyphicon-info-sign"></span>-->
            </h3>

            <div class="progress">
                <div class="progress-bar progress-bar-success" style="width:55%;"> Femme </div>
                <div class="progress-bar progress-bar-danger"  style="width:45%;"> Homme</div>
            </div>

        </div>
        <div class="col-md-4">
            <h3>
            Nombre de membres de rang A :
            </h3>

            <div class="progress">
                <div class="progress-bar progress-bar-info" style="width:60%;"> Rang A </div>
            </div>
        </div>
        <div class="col-md-4">
            <h3>
            Nombre de membres extérieurs :
            </h3>
            <div class="progress">
                <div class="progress-bar progress-bar-info" style="width:50%;"> Extérieurs </div>
            </div>
        </div>
    </div>
</div>

<div>
    Liste des membres
</div>


