<?php

/**
 * @var These $these
 * @var Membre $rapporteur
 * @var Proposition $proposition
 */

use Application\Entity\Db\These;
use Soutenance\Entity\Membre;
use Soutenance\Entity\Proposition;

?>

<h1> Demande d'expertise </h1>

<p class="lead">
Je sousigné, <strong><?php echo $rapporteur->getDenomination(); ?></strong>, déclare être rapporteur de la thèse de
<strong><?php echo $these->getDoctorant()->getIndividu()->getNomComplet(false, true, false,true); ?></strong>
intitulée <strong><?php echo $these->getTitre(); ?></strong> et atteste comprendre les responsabilités associées à ce rôle.
</p>

<p class="lead">
Je m'engage à rendre mon rapport de thèse sur la plateforme SyGAL pour la date du <strong><?php echo $proposition->getRenduRapport()->format('d/m/Y'); ?></strong>.
</p>

<a href="" class="btn btn-success"> Signature </a>


