<?php
/**
 * @var These $these
 * @var Proposition $proposition
 * @var Membre $membre
 * @var Validation $validation
 * @var string $urlSigner
 */

use Application\Entity\Db\Acteur;
use Application\Entity\Db\These;
use Application\Entity\Db\Validation;
use Soutenance\Entity\Membre;
use Soutenance\Entity\Proposition;

$canValidate = true;

?>

<h1 class="page-header">
    Engagement d’impartialité
</h1>

<p>
    Engagement d'impartialité en rapport à la thèse suivante :
</p>

<div>
    <div class="panel panel-info">
        <div class="panel-heading">
            Information sur la thèse
        </div>
        <div class="panel-body">
            <dl class="dl-horizontal">
                <dt> Titre </dt>
                <dd> <?php echo $these->getTitre(); ?> </dd>
                <dt> Doctorant </dt>
                <dd> <?php echo $these->getDoctorant()->getIndividu()->getNomComplet(false, true, false, true, true); ?> </dd>
                <dt> Encadrement </dt>
                <dd>
                    <?php foreach ($these->getEncadrements() as $directeur): ?>
                        <?php
                        /** @var Acteur $directeur */
                        echo $directeur->getIndividu()->getNomComplet(false, true, false, true, true);
                        ?>
                        <br/>
                    <?php endforeach; ?>
                <dt> Discipline </dt>
                <dd> <?php echo $these->getLibelleDiscipline(); ?> </dd>
                <dt> Date de la soutenance </dt>
                <dd> <?php echo $proposition->getDate()->format("d/m/Y"); ?> </dd>
                <dt> Lieu de la soutenance </dt>
                <dd> <?php echo $proposition->getLieu(); ?> </dd>
            </dl>

        </div>
    </div>
</div>

<p>
    En signant cet engagment d'impartialité, je, sous-signé <strong><?php echo $membre->getDenomination(); ?></strong>, atteste ne pas avoir de lien personnel ou familial avec le doctorant ou son directeur de thèse et ne pas
    avoir pris part aux travaux de la thèse et ne pas avoir de publication cosignée avec le doctorant dans les cinq
    dernières années.
</p>

<?php if ($validation): ?>
    <?php echo $this->validation($validation) ?>
<?php else: ?>
    <?php if ($canValidate): ?>
        <p>
            <a href="<?php echo $urlSigner ?>"
               class="btn btn-success ajax-modal"
               data-event="event-page-de-couverture-validated-or-not"><span
                    class="glyphicon glyphicon-thumbs-up"></span> Je signe l'engagement d'impartialité</a>
        </p>
    <?php endif ?>
<?php endif ?>