<?php
    /**
     * @var These $these
     * @var Proposition $proposition
     * @var Individu[] $directeurs
     * @var Membre[] $rapporteurs
     * @var Validation[] $validations
     * @var string[] $avis
     */

use Application\Entity\Db\Individu;
use Application\Entity\Db\These;
use Application\Entity\Db\Validation;
use Soutenance\Entity\Membre;
use Soutenance\Entity\Proposition;

$this->headTitle("Gestion de la préparation de la soutenance");

//TODO faire assertion pour les canTrucs
$canProposer   = true;
$canVisualiser = true;
?>

<h1 class="page-header">
    Gestion de la préparation de la soutenance
</h1>

<?php if($these === null) : ?>
    <p class="lead">
        Le module permet de préparer la soutenance de la <strong>proposition du jury</strong> jusqu'au <strong>rendu des rapports de présoutenance</strong>.
    </p>

    <h2> Constituer votre jury de thèse </h2>

    <p>
        SyGAL permet la constitution de votre jury de thèse de façon dématérialisée.
        La composition de votre jury se passe en deux étapes :
        <ol>
            <li> la composition et acceptation par le doctorant et les directeurs et co-directeurs ;</li>
            <li> la validation par l'unité de recherche, l'école doctorale et maison des doctorats associé à la thèse.</li>
        </ol>
    </p>

    <p>
        Votre jury doit respecter les règles suivantes :
        <ul>
            <li> le jury doit être contenir aux moins deux rapporteurs ;</li>
            <li> au moins la motié des membres doivent être de rang A (Professeurs des universités, Directeur de recherche, ...) ; </li>
            <li> au moins la motié des membres doivent être extérieurs à l'université dans laquelle la thèse se déroule. </li>
        </ul>

        <u>N.B. :</u> Le jury doit idéalement respecter la parité homme/femme.
    </p>

    <p>
        Pour passer à la second étape de la composition de votre jury tous les acteurs directs (doctorant, directeurs et
        co-directeurs) doivent valider unanimement la proposition de soutenance (jury, date et lieu de soutenance).
    </p>

    <?php if ($canProposer) : ?>
        <a href="<?php // echo $this->url('soutenance/proposition', ['these' => $these->getId()], [], true); ?>"
           class="btn btn-primary action pull-right">
            <span class="glyphicon glyphicon-pencil"></span>
            Commencer ma proposition
        </a>
    <?php endif; ?>

    <h2> Voir l'avancement des validations de votre soutenance </h2>

    <p>
        Avant de pouvoir soutenir de nombreuses validations sont nécessaires par :
        <ul>
            <li> les acteurs directs de la thèse (doctorant, directeurs et co-directeurs) ; </li>
            <li> les structures associés à la thèses (unité de recherche, école doctorale, ...) ;</li>
            <li> les rapporteurs de la thèse.</li>
        </ul>
    </p>

    <p>
        Afin de suivre ces validations, SyGAL fournit une interface permettant de suivre l'évolution de celle-ci.
        Cette interface permet de connaître la liste de validations reçus, celles en attentes et l'ordre des validations.
    </p>

    <?php if ($canVisualiser) : ?>
        <a href="<?php // echo $this->url('soutenance', ['these' => $these->getId()], [], true); ?>"
           class="btn btn-primary action pull-right">
            <span class="glyphicon glyphicon-eye-open"></span>
            Voir l'avancement
        </a>
    <?php endif; ?>


<?php else : ?>
    <h2> Proposition de soutenance </h2>

    <dl class="dl-horizontal">
        <dt> Lieu et date </dt>
        <dd>
            <?php echo validite($proposition->getDate() !== null AND $proposition->getLieu() !== null); ?>
        </dd>
        <dt> Jury de thèse </dt>
        <dd>
            <?php echo validite($proposition->juryOk()); ?>
        </dd>
    </dl>

    <h3> Validations des acteurs directs </h3>

    <?php
        if ($these) $doctorant = $these->getDoctorant();
    ?>

    <?php echo getBadge($validations[$doctorant->getId()]); ?>
    <?php echo $doctorant->getNomComplet(false, true, false); ?> <br/>

    <?php foreach($directeurs as $directeur) : ?>
        <?php echo getBadge($validations[$directeur->getId()]); ?>
        <?php echo $directeur->getNomComplet(false, true, false); ?> <br/>

    <?php endforeach; ?>

    <h3> Validations des structures associées </h3>

    <?php
        if ($these) $unite = $these->getUniteRecherche()->getStructure();
        if ($these) $ecole = $these->getEcoleDoctorale()->getStructure();
        if ($these) $etab  = $these->getEtablissement()->getStructure();
    ?>

    <?php echo getBadge($validations['unite-recherche']); ?>
    <?php echo $unite->getLibelle(); ?> (<?php echo $unite->getSigle(); ?> ) <br/>

    <?php echo getBadge($validations['ecole-doctorale']); ?>
    <?php echo $ecole->getLibelle(); ?> (<?php echo $ecole->getSigle(); ?> ) <br/>

    <?php echo getBadge($validations['bureau-doctorat']); ?>
    Maison des doctorats (<?php echo $etab->getLibelle(); ?> ) <br/>

    <h3> Validation de la soutenance par les rapporteurs </h3>

    <?php foreach ($rapporteurs as $rapporteur) : ?>

    <div class="col-md-6">
        <strong><?php echo $rapporteur->getDenomination(); ?></strong><br/>
        <?php echo getBadge($validations[$rapporteur->getIndividu()->getId()]); ?>
        Engagment d'impartialité <br/>

        <?php echo getBadgeAvis($avis[$rapporteur->getIndividu()->getId()]); ?>
        Avis de soutenance <br/>
    </div>

    <?php endforeach; ?>

<?php endif; ?>


<?php
    function validite($value) {
        if ($value === true) {
            return '<span class="badge success">Valide</span>';
        }
        if ($value === false) {
            return '<span class="badge danger">Invalide</span>';
        }
    }

    function getBadge($validation) {
        if ($validation) return '<span class="badge success">Valide</span>';
        return '<span class="badge default">Aucune</span>';
    }

    function getBadgeAvis($avis) {
        if ($avis === "Favorable") {
            return '<span class="badge success">Favorable</span>';
        }
        if ($avis === "Défavorable") {
            return '<span class="badge danger">Défavorable</span>';
        }
        return '<span class="badge default">Aucune</span>';
    }
?>
<style>
    .action {
        width: 20em;
    }

    .success {
        width: 10em;
        background-color: darkgreen;
    }

    .danger {
        width: 10em;
        background-color: darkred;
    }

    .default {
        width: 10em;
    }
</style>
