<?php

/**
 * @var Proposition[] $propositions
 */

use Soutenance\Entity\Proposition;

?>


<h1> Module Soutenance </h1>

<table class="table table-extra-condensed">
    <thead>
        <tr>
            <th> Identifiant </th>
            <th> Thèse ID </th>
            <th> Titre </th>
            <th> Actions </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($propositions as $proposition): ?>
            <tr>
                <td> <?php echo $proposition->getId(); ?> </td>
                <td> <?php echo $proposition->getThese()->getId(); ?> </td>
                <td> <?php echo $proposition->getThese()->getTitre(); ?> </td>
                <td>
                    <a href="<?php echo $this->url('soutenance/constituer', ['these' => $proposition->getThese()->getId()], [], true); ?>">
                        <span class="glyphicon glyphicon-eye-open></span>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>