<?php

/**
 * @var Proposition $proposition
 */

use Soutenance\Entity\Membre;
use Soutenance\Entity\Proposition;

$indicateurs = $proposition->computeIndicateur();

?>

<style>
    .badge-success {
        background-color: #468847;
    }

    .badge-error {
        background-color: #881f18;
    }

    .action {
        width: 25em;
        margin:1ex;
    }

</style>

<?php $this->headTitle($this->translate("Validation de la proposition de soutenance par l'unité de recherche")); ?>
<h1 class="page-header">
    Validation de la proposition de soutenance par l'unité de recherche
</h1>

<div class="panel panel-info">
    <div class="panel-heading">
        <h4>
            Date/Heure et lieu de la soutenance
        </h4>
    </div>
    <div class="panel-body">
        <div class="pull-left">
            <ul>
                <li>
                    Date de la soutenance :  <?php echo $proposition->getDate()->format("d/m/Y"); ?>
                </li>
                <li>
                    Heure de la soutenance : <?php echo $proposition->getDate()->format("H:i:s"); ?>
                </li>
                <li>
                    Lieu de la Soutenance : <?php echo $proposition->getLieu(); ?>
                </li>
            </ul>
        </div>
    </div>
</div>



<div class="panel panel-info">
    <div class="panel-heading">
        <h4>
            Indicateurs liés à la validité du jury de thèse
        </h4>
    </div>
    <div class="panel-body">

        <div class="col-md-3">
            <h4>
                Parité de genre
                <?php if ($indicateurs["parité"]["valide"]):?>
                    <span class="badge badge-success"> Valide </span>
                <?php else: ?>
                    <span class="badge badge-error"> Non valide </span>
                <?php endif; ?>
            </h4>

            <div class="progress">
                <div class="progress-bar progress-bar-success" style="width:<?php echo $indicateurs["parité"]["Femme"]*100; ?>%;"> Femme </div>
                <div class="progress-bar progress-bar-danger"  style="width:<?php echo $indicateurs["parité"]["Homme"]*100; ?>%;"> Homme</div>
            </div>

        </div>
        <div class="col-md-3">
            <h4>
                Nombre de rapporteurs
                <?php if ($indicateurs["rapporteur"]["valide"]):?>
                    <span class="badge badge-success"> Valide </span>
                <?php else: ?>
                    <span class="badge badge-error"> Non valide </span>
                <?php endif; ?>
            </h4>

            <div class="progress">
                <div class="progress-bar progress-bar-info" style="width:<?php echo $indicateurs["rapporteur"]["Ratio"]*100; ?>%;">
                    <?php echo $indicateurs["rapporteur"]["Nombre"]; ?>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <h4>
                Nombre <!--de membres--> de rang A
                <?php if ($indicateurs["rang A"]["valide"]):?>
                    <span class="badge badge-success"> Valide </span>
                <?php else: ?>
                    <span class="badge badge-error"> Non valide </span>
                <?php endif; ?>
            </h4>

            <div class="progress">
                <div class="progress">
                    <div class="progress-bar progress-bar-info" style="width:<?php echo $indicateurs["rang A"]["Ratio"]*100; ?>%;">
                        <?php echo $indicateurs["rang A"]["Nombre"]; ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <h4>
                Nombre <!--de membres--> d'extérieurs
                <?php if ($indicateurs["exterieur"]["valide"]):?>
                    <span class="badge badge-success"> Valide </span>
                <?php else: ?>
                    <span class="badge badge-error"> Non valide </span>
                <?php endif; ?>
            </h4>
            <div class="progress">
                <div class="progress-bar progress-bar-info" style="width:<?php echo $indicateurs["exterieur"]["Ratio"]*100; ?>%;">
                    <?php echo $indicateurs["exterieur"]["Nombre"]; ?>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">
        <h4>
            Composition du jury
        </h4>
    </div>
    <div class="panel-body">
        <table class="table table-extra-condensed">
            <thead>
            <tr>
                <th>Dénomination</th>
                <th>Adresse électronique</th>
                <th>Genre</th>
                <th>Qualité</th>
                <th>Rang</th>
                <th>Etablissement</th>
                <th>Rôle</th>
            </tr>
            </thead>
            <tbody>
            <?php /** @var Membre $membre */ ?>
            <?php foreach($proposition->getMembres() as $membre): ?>
                <tr>
                    <td> <?php echo $membre->getDenomination(); ?> </td>
                    <td> <?php echo $membre->getEmail(); ?> </td>
                    <td> <?php echo $membre->getGenre(); ?> </td>
                    <td> <?php echo $membre->getQualite()->getLibelle(); ?> </td>
                    <td> <?php echo $membre->getRang(); ?> </td>
                    <td> <?php echo $membre->getEtablissement(); ?> </td>
                    <td> <?php echo $membre->getRole(); ?> </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">
        <h4>
            Liste des validations
        </h4>
    </div>
    <div class="panel-body">

    </div>
</div>

<div class="row">
    <a href=""
       class="btn btn-success action"
   >
        <span class="glyphicon glyphicon-ok"></span>
       Accepter la proposition de soutenance
    </a>
    <a href="<?php echo $this->url('soutenance/valider-ur/refuser', ['these' => $proposition->getThese()->getId()], [], true); ?>"
       class="btn btn-danger action ajax-modal"
       data-event="refus"
    >
        <span class="glyphicon glyphicon-remove"></span>
        Refuser la proposition de soutenance
    </a>

</div>

<script>
    $(function() {
        $("body").on("refus", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>