<?php

use Application\Entity\Db\EcoleDoctorale;
use Application\View\Renderer\PhpRenderer;
use ComiteSuivi\Entity\Db\ComiteSuivi;

/**
 * @see \ComiteSuivi\Service\Notifier\NotifierService::triggerRefus()
 * @var PhpRenderer $this
 * @var ComiteSuivi $comite
 * @var EcoleDoctorale $ecole
 * @var string $raison
 */
?>

<?php
$url = $this->url('comite-suivi/modifier', ['these' => $comite->getThese()->getId(), 'comite-suivi' => $comite->getId()], ['force_canonical'=>true], true);
?>

<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application SyGAL.
</p>

<p>
    Votre école doctorale (<?php echo $ecole->getSigle(); ?>) vient de refuser votre comité de suivi de thèse de votre
    <?php echo strtolower($this->anneeThese($comite->getAnneeThese())); ?> de thèse.
</p>

<p>
    Voici la justification fournie par votre école doctorale quant au refus :
    <table><tr><td style="border:solid 1px gray;"> <?php echo $raison; ?></td></tr></table>
</p>
