<?php

namespace Application;

use Application\Entity\Db\Variable;
use Structure\Entity\Db\Etablissement;
use Individu\Entity\Db\Individu;
use Application\Entity\Db\Role;
use Application\Entity\Db\Utilisateur;
use Application\View\Renderer\PhpRenderer;
use Laminas\Validator\EmailAddress as EmailAddressValidator;

/**
 * @var PhpRenderer $this
 * @var Etablissement $etablissement
 * @var Variable[] $variables
 * @var Individu|null $individu
 * @var Utilisateur|null $utilisateur
 * @var Role|null $role
 * @var Role[] $roles
 * @see \Application\Controller\IndexController::contactAction()
 */

$v = new EmailAddressValidator();

$mailBody =
    "Bonjour,".PHP_EOL.PHP_EOL .
    "Decrivez précisément votre problème ici, svp...".PHP_EOL.PHP_EOL.PHP_EOL .
    '------------------------------------------------------------'.PHP_EOL .
    trim($this->partial('application/index/partial/debug-infos', [
        'individu' => $individu,
        'utilisateur' => $utilisateur,
        'role' => $role,
        'roles' => $roles,
        'html' => false,
    ]));
?>

<?php $this->headTitle()->append($title = "Contact") ?>

<h1 class="page-header"><?php echo $this->translate($title); ?></h1>

<div class="row">
    <div class="col-md-7">
        <dl>
            <dt>Adresse d'assistance - <?php echo $etablissement ?: "Établissement indéterminé" ?></dt>
            <dd>
                <?php if (!empty($variables)): ?>
                    <ul>
                    <?php foreach ($variables as $variable): ?>
                        <?php
                        $contact = $variable->getValeur();
                        $contactValide = $v->isValid($contact);
                        ?>
                        <li>
                            <?php if ($contactValide): ?>
                                <a href="mailto:<?php echo trim($contact) ?>?body=<?php echo urlencode($mailBody) ?>"
                                   title="<?php echo $this->translate("Envoyer un mail à cette adresse") ?>"><?php echo $contact ?></a>
                            <?php else: ?>
                                <?php echo $contact ?>
                                <span class="icon icon-warning text-danger" title="Adresse non valide !"></span>
                            <?php endif ?>
                        </li>
                    <?php endforeach ?>
                    </ul>
                <?php else: ?>
                    Indéterminée
                <?php endif ?>
            </dd>
        </dl>
    </div>
    <div class="col-md-5">
        <?php echo $this->partial('application/index/partial/debug-infos') ?>
    </div>
</div>