<?php
/**
 * @var PhpRenderer $this
 * @var Role        $role Rôle courant
 * @var bool        $estDoctorant
 */

use Application\Entity\Db\Role;
use Application\View\Renderer\PhpRenderer;

$appName = $this->appInfos()->nom;
$subtitle = $this->appInfos()->desc;
?>

<?php $this->headTitle($this->translate("Accueil")); ?>

<?php
echo $this->messenger()
    ->addMessagesFromFlashMessengerWithNoNamespace()
    ->addMessagesFromFlashMessengerWithNamespace('UnicaenAuth/*'); ?>

<div class="row">

    <div id="sidebar" class="col-xs-12 col-md-2" role="navigation">
<!--        <div class="menu-information-header">-->
<!--            <ul class="nav nav-pills nav-stacked"><li>Informations générales</li></ul>-->
<!--        </div>-->
            <?php
               echo $this->navigation()->menu('Zend\Navigation\Information')
                  ->setUlClass('nav nav-pills nav-stacked menu-information')
                  ->setMinDepth(1)
                  ->setMaxDepth(1)
                  ->render();
            ?>
    </div>

    <div id="content" class="jumbotron col-xs-12 col-md-10">

        <h1 class="page-header"><?php echo $this->appInfos()->nom ?></h1>

        <p class="appname-subtitle">
            <strong><?php echo $subtitle ?></strong>
        </p>

        <?php if (!$this->identity()): ?>
            <?php echo $appName ?> (<?php echo $subtitle ?>) est une application permettant la gestion dématérialisée
            de l’ensemble des étapes du parcours doctoral en Normandie. Il offre également aux différents acteurs du parcours
            doctoral (établissements, écoles doctorales) une visibilité sur les thèses en cours ou passées.
        <?php endif ?>

        <?php if (!$this->identity()): ?>
            <p class="text-danger">
                <strong>
                    <?php echo $this->translate("Vous n'êtes pas connecté-e."); ?>
                </strong>
            </p>
            <p>
                <a class="btn btn-success btn-lg" href="<?php echo $this->url('zfcuser/login') ?>">
                    <?php echo $this->translate('Connectez-vous...') ?>
                </a>
            </p>
        <?php else: ?>
            <?php if (!$estDoctorant): ?>
                <p class="text-success">
                    <strong>
                        <?php echo $this->translate("Vous êtes connecté-e en tant que"); ?>
                        &laquo; <?php echo ($role)?:"utilisateur authentifié"; ?> &raquo;.
                    </strong>
                </p>
                <ul class="roadmap pagination">
                    <li>
                        <a class="roadmap-step-link " href="<?php echo $this->url('these') ?>">
                            <span class="glyphicon glyphicon-circle-arrow-right"></span>
                            <?php echo $this->translate("Accès aux thèses..."); ?>
                        </a>
                    </li>
                </ul>
            <?php endif ?>
            <hr>
        <?php endif ?>

        <?php echo $this->content ?>

    </div>

</div>
