<?php
/**
 * @var PhpRenderer $this
 * @var Role        $role Rôle courant
 * @var bool        $estDoctorant
 */

use Application\Entity\Db\Role;
use Application\View\Renderer\PhpRenderer;

$subtitle = "SYstème de Gestion et d'Accompagnement doctoraL";
?>

<?php $this->headTitle($this->translate("Accueil")); ?>

<?php
$messenger = $this->messenger();
echo $messenger->addMessagesFromFlashMessenger();
echo $messenger->addMessagesFromFlashMessenger('UnicaenAuth/*');
?>

<div class="jumbotron">

    <h1 class="page-header"><?php echo $this->appInfos()->nom ?></h1>

    <p class="appname-subtitle">
        <strong><?php echo $subtitle ?></strong>
    </p>

    <?php if (!$this->identity()): ?>
        <p>
            <?php echo $this->translate("Bienvenue dans l’outil de suivi et de dépôt numérique des thèses de l'université de Caen Normandie.") ?>
        </p>
        <p>
            <?php echo $this->translate("SyGAL offre aux différents acteurs du circuit des thèses de Normandie Université une vision d’ensemble sur les thèses préparées au sein de la COMUE."); ?>
            <?php echo $this->translate("Il permet la gestion du dépôt de la thèse sous forme numérique, pour archivage et affichage dans le portail national :"); ?>
            <a href="http://www.theses.fr/">theses.fr</a>.
        </p>
    <?php endif ?>

    <?php if (!$this->identity()): ?>
        <p class="text-danger">
            <strong>
                <?php echo $this->translate("Vous n'êtes pas connecté-e."); ?>
            </strong>
        </p>
        <p>
            <a class="btn btn-success btn-lg" href="<?php echo $this->url('zfcuser/login') ?>">
                <?php echo $this->translate('Connectez-vous...') ?>
            </a>
        </p>
    <?php else: ?>
        <?php if (!$estDoctorant): ?>
            <p class="text-success">
                <strong>
                    <?php echo $this->translate("Vous êtes connecté-e en tant que"); ?>
                    &laquo; <?php echo $role ?> &raquo;.
                </strong>
            </p>
            <ul class="roadmap pagination">
                <li>
                    <a class="roadmap-step-link " href="<?php echo $this->url('these') ?>">
                        <span class="glyphicon glyphicon-circle-arrow-right"></span>
                        <?php echo $this->translate("Accès aux thèses..."); ?>
                    </a>
                </li>
            </ul>
        <?php endif ?>
        <hr>
    <?php endif ?>

    <?php echo $this->content ?>

</div>
