<?php
/**
 * @var PhpRenderer $this
 * @var array       $messages
 */

use Application\View\Renderer\PhpRenderer;
?>

<?php $this->headTitle("Accueil") ?>

<div class="jumbotron">

    <h1 class="page-header"><?php echo $this->appInfos()->nom ?></h1>

    <p class="appname-subtitle">
        <strong><?php echo $this->appInfos()->desc ?></strong>
    </p>

    <?php echo $this->messenger()->setMessages($messages); ?>

    <?php echo $this->content ?>

</div>