<?php

namespace Admission\Hydrator\Etudiant;

use Admission\Entity\Db\Etudiant;
use Application\Entity\Db\Pays;
use Doctrine\Laminas\Hydrator\DoctrineObject;
use Individu\Entity\Db\Individu;
use Individu\Service\IndividuServiceAwareTrait;

/**
 * @author Unicaen
 */
class EtudiantHydrator extends DoctrineObject
{

    use IndividuServiceAwareTrait;
    public function extract(object $object): array
    {
        /** @var Etudiant $object */
        $data = parent::extract($object);

        if (array_key_exists($key = 'paysNaissanceId', $data) && $data[$key] instanceof Pays) {
            $data['paysNaissance'] = $object->getPaysNaissance()->getLibelle();
        }

        if (array_key_exists($key = 'nationaliteId', $data) && $data[$key] instanceof Pays) {
            $data['nationalite'] = $object->getPaysNaissance()->getLibelle();
        }

        $data['verificationEtudiant'] = $object->getVerificationEtudiant()->first();

        return $data;
    }

    public function hydrate(array $data, object $object): object
    {
        $data["paysNaissance"] = !empty($data["paysNaissanceId"]) ? $data["paysNaissanceId"] : null;
        $data["nationalite"] = !empty($data["nationaliteId"]) ? $data["nationaliteId"] : null;
        $data["adresseCodePostal"] = empty($data["adresseCodePostal"]) ? null : $data["adresseCodePostal"];

        //Si la case niveauEtude n'est pas le diplôme national, on met à null les valeurs des champs reliés
        if(isset($data["niveauEtude"]) && $data["niveauEtude"] != 1){
            $data["intituleDuDiplomeNational"] = null;
            $data["anneeDobtentionDiplomeNational"] = null;
            $data["etablissementDobtentionDiplomeNational"] = null;
        }

        //Si la case niveauEtude n'est pas la case Autre, on met à null les valeurs des champs reliés
        if(isset($data["niveauEtude"]) && $data["niveauEtude"] != 2){
            $data["typeDiplomeAutre"] = null;
            $data["intituleDuDiplomeAutre"] = null;
            $data["anneeDobtentionDiplomeAutre"] = null;
            $data["etablissementDobtentionDiplomeAutre"] = null;
        }

        if (isset($data['verificationEtudiant']) && !is_array($data['verificationEtudiant'])) {
            $data['verificationEtudiant'] = [$data['verificationEtudiant']];
        }

        return parent::hydrate($data, $object); // TODO: Change the autogenerated stub
    }

}