<h1 class="page-header"> Confirmation de votre mail de contact</h1>

<p class="lead">
    Une demande de confirmation de votre mail de contact <strong><?php echo $email; ?> </strong> vous a été envoyée.
    Pour pouvoir poursuivre sur SyGAL, veuillez confirmer cette adresse grâce au lien fourni dans cette demande.
</p>

<p class="lead">
    Pour changer votre mail de contact ou re-effectuer la demande du mail de confirmation,
    veuillez cliquer sur le bouton ci-dessous.
</p>

    <center>
    <a href="
    <?php echo $this->url('doctorant/modifier-persopass',['back' => true], [], true); ?>
    "><input class="btn btn-info" type="button" value="Retour au formulaire de mail de contact"/></a>
    </center>