<?php

use Application\Entity\Db\Doctorant;

/**
 * @var Doctorant $doctorant
 */

$appName = $this->appInfos()->nom;
?>

<h1 class="page-header"> Confirmation de votre adresse électronique de contact</h1>

<p class="lead">
    Une demande de confirmation de votre adresse électronique de contact a été envoyée à <strong><?php echo $email ?> </strong>.
    Pour pouvoir poursuivre sur <?php echo $appName ?>, veuillez confirmer cette adresse grâce au lien figurant dans la demande.
</p>

<p class="lead">
    Pour modifier votre adresse électronique de contact ou recevoir une nouvelle demande de confirmation,
    veuillez cliquer sur le bouton ci-dessous.
</p>

<a href="
<?php echo $this->url('doctorant/modifier-persopass',['back' => true, 'doctorant' => $doctorant->getId()], [], true) ?>
"><input class="btn btn-info" type="button" value="Retour au formulaire de mail de contact"/></a>