<?php

use Application\View\Renderer\PhpRenderer;

/**
 * @see \Application\Service\Notification\NotifierService::triggerMailConfirmation()
 * @var PhpRenderer $this
 * @var string $confirm
 */
?>

<p>
    Bonjour,
</p>
<p>
    Ceci est un mail envoyé automatiquement par l'application <?php echo $this->appInfos()->nom ?>.
</p>
<p>
    Pour finaliser l'enregistrement de votre email de contact veuillez confirmer celui-ci en cliquant sur le liens suivant :
    <a href="<?php echo $confirm; ?>"><?php echo $confirm; ?></a>.
</p>
<p>
    Une fois confirmé, cet email sera utilisé pour recevoir les notifications de <?php echo $this->appInfos()->nom ?>.
</p>
