<?php

use Application\Entity\Db\These;
use Application\View\Renderer\PhpRenderer;
use Zend\Form\Form;

/**
 * @var        $this         PhpRenderer
 * @var These  $these
 * @var Form   $form
 * @var string $title
 * @var bool   $detournement Indique s'il s'agit d'un détournement de requête pour saisie du persopass
 * @var string $emailBdD
 */
?>

<h1 class="page-header"><?php echo $title ?></h1>

<?php echo $this->messenger()->addMessagesFromFlashMessengerWithNoNamespace(); ?>

<div class="container">
    <div class="col-md-8">
        <p class="lead">
            Avant de continer, merci de bien saissir une adresse mail de contact.
            Cette adresse sera utilisée par SyGAL pour vous communiquer les informations importantes associées à votre
            thèse.
            Cette adresse peut aussi être utilisée afin de vous identifier à SyGAL.
        </p>
        <p class="alert alert-info">
            <strong>NB: </strong>
            L'adresse mail de contact de vous saisez ici doit être une adresse durable (autre que vos adresses mails
            fornies
            par votre établissement).
        </p>
    </div>
</div>

<div class="container">
    <div class="col-md-4 col-md-offset-2">
        <?php
        $fcg = $this->formControlGroup();
        echo $this->form()->openTag($form->prepare()->setAttribute('class', 'mail-confirmation'));
        echo $fcg($form->get('id'));
        echo $fcg($form->get('idIndividu'));
        echo $fcg($form->get('individu'));
        echo $fcg($form->get('email'));
        echo $fcg($form->get('enregistrer'));
        echo $this->form()->closeTag();
        ?>
    </div>
</div>
