<?php
/**
 * @var array $operations
 * @var Individu $individu
 * @var string $returnUrl
 * @var AdmissionOperationInterface $operationEnAttente
 * @var Admission $admission
 * @var boolean $showActionButtons
 * @var boolean $isOperationAllowedByRole
 */

use Admission\Entity\Db\Admission;
use Admission\Entity\Db\AdmissionAvis;
use Admission\Entity\Db\AdmissionOperationInterface;
use Admission\Entity\Db\AdmissionValidation;
use Admission\Entity\Db\TypeValidation;
use Individu\Entity\Db\Individu;

$ajaxModalEvent = 'EVENT_AVIS_SAISI';
?>
<div class="row">
    <div class="col-lg-7 col-sm-12">
        <?php
        $count = 1;
        foreach ($operations as $i => $operation):
            echo $this->partial('admission/admission/partial/operation-card', [
                'operation' => $operation,
                'count' => $count,
                'individu' => $individu,
                'operationEnAttente' => $operationEnAttente,
                'returnUrl' => $returnUrl,
                'ajaxModalEvent' => $ajaxModalEvent,
                'libelleOperation' => null,
                'showRangOperation' => true,
                'showActionButtons' => $showActionButtons,
                'isOperationAllowedByRole' => $isOperationAllowedByRole
            ]);
            $count += 1;
        endforeach;
        ?>
    </div>
    <div class="col-lg-5 col-sm-12 validations-cards-container">
        <?php if ($admission->isDossierComplet() && ($admission->getEtat()->getCode() === Admission::ETAT_EN_COURS_VALIDATION)) { ?>
            <div class="card border-success mb-3 dossier-complet-card">
                <div class="card-body text-success">
                    <i class="icon icon-information"></i>
                    <p class="card-title">Le dossier est complet</p>
                </div>
            </div>
        <?php }else if($admission->getEtat()->getCode() === Admission::ETAT_VALIDE){?>
            <div class="card border-success mb-3 dossier-complet-card">
                <div class="card-body text-success">
                    <i class="icon icon-information"></i>
                    <p class="card-title">La direction de l'établissement a émis un avis favorable sur ce dossier</p>
                </div>
            </div>
        <?php }else if($admission->getEtat()->getCode() === Admission::ETAT_REJETE){ ?>
            <div class="card mb-3 dossier-refuse-card">
                <div class="card-body text-danger">
                    <i class="icon icon-unchecked"></i>
                    <p class="card-title">La direction de l'établissement a émis un avis réservé sur ce dossier</p>
                </div>
            </div>
        <?php }

        if ($operationEnAttente) { ?>
            <div class="card mb-3 dossier-incomplet-card">
                <div class="card-body text-warning">
                    <i class="icon icon-information"></i>
                    <?php
                    if(($operationEnAttente instanceof AdmissionAvis &&
                        $operationEnAttente->getAvis()->getAvisType()->getCode() !== AdmissionAvis::AVIS_TYPE__CODE__AVIS_ADMISSION_PRESIDENCE) ||
                        ($operationEnAttente instanceof AdmissionValidation &&
                        $operationEnAttente->getTypeValidation()->getCode() === TypeValidation::CODE_ATTESTATION_HONNEUR)){ ?>
                        <p class="card-title">En attente de l'<?= strtolower($operationEnAttente->getTypeToString()); ?></p>
                    <?php }else{ ?>
                        <p class="card-title">En attente de la <?= strtolower($operationEnAttente->getTypeToString()); ?></p>
                    <?php } ?>
                </div>
            </div>
        <?php }
        //Si la dernière opération a été déclarée comme réservée / incomplete
        else if ($operationEnAttente === false){ ?>
            <div class="card mb-3 dossier-refuse-card">
                <div class="card-body text-danger">
                    <i class="icon icon-unchecked"></i>
                        <p class="card-title">Un avis réservé / incomplet a été déclaré sur le dossier</p>
                </div>
            </div>
        <?php }

        if (isset($admission) && $admission->hasComments()) { ?>
            <div class="card mb-3 dossier-incomplet-card">
                <div class="card-body text-warning">
                    <i class="icon icon-information"></i>
                    <p class="card-title">Des commentaires ont été ajoutés au dossier</p>
                </div>
            </div>
        <?php } ?>
    </div>
</div>

<div class="modal fade" id="avisComplemsModal" tabindex="-1" aria-labelledby="avisComplemsModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="avisComplemsModalLabel">Détails de l'avis</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button>
            </div>
            <div class="modal-body">
                <!-- rempli dynamiquement -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
            </div>
        </div>
    </div>
</div>
<script>
    $(function() {
        const avisComplemsModal = document.getElementById('avisComplemsModal')
        avisComplemsModal.addEventListener('show.bs.modal', function (event) {
            // Button that triggered the modal
            const button = event.relatedTarget;
            const logFullContent = $(button).parent().siblings(".log-full-content").html();
            // Update the modal's content.
            const modalBody = avisComplemsModal.querySelector('.modal-body');
            $(modalBody).html(logFullContent);
        });

        // Gestion de la fermeture de la modale
        let ajaxModalEvent = '<?php echo $ajaxModalEvent ?>';
        $("body").on(ajaxModalEvent, function(event) {
            $("body").addClass("loading");
            event.div.modal('hide'); // ferme la fenêtre modale
            window.location.reload();
        });
    })
</script>