<?php

use Admission\Form\Fieldset\Validation\ValidationFieldset;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer         $this
 * @var ValidationFieldset    $fieldset
 * @var string              $error
 * @var array               $dataForm
 *
 */
$fcg = $this->formControlGroup();?>
<div class="row">

    <?php foreach ($dataForm as $fieldsetData): ?>
        <div class="col-md-6">

            <?php
            /** @var Fieldset $fieldset */
            $fieldset = $fieldsetData['fieldset'];
            ?>

            <fieldset class="<?php echo $fieldset->getName() ?>">
                <legend><?php echo $fieldset->getLabel() ?></legend>

            </fieldset>

        </div>
    <?php endforeach ?>

</div>



