<?php

use Admission\Entity\Db\Admission;
use Admission\Entity\Db\AdmissionOperationInterface;
use Admission\Entity\Db\ConventionFormationDoctorale;
use Admission\Entity\Db\Etudiant;
use Admission\Entity\Db\Inscription;
use Admission\Entity\Db\TypeValidation;
use Admission\Form\Admission\AdmissionForm;
use Admission\Form\Fieldset\Document\DocumentFieldset;
use Admission\Provider\Privilege\AdmissionPrivileges;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer         $this
 * @var DocumentFieldset    $fieldset
 * @var AdmissionForm $form
 * @var Admission $admission
 * @var array[] $operations
 * @var array               $documents
 * @var AdmissionOperationInterface $operationEnAttente
 * @var array $conventionFormationDoctoraleOperations
 * @var ConventionFormationDoctorale $conventionFormationDoctorale
 * @var boolean $isOperationAllowedByRole
 * @var array $commentaires
 * @see \Admission\Controller\AdmissionController::documentAction()
 */
$form->prepare();

$canAccederCommentaires = $this->isAllowed($admission,AdmissionPrivileges::ADMISSION_ACCEDER_COMMENTAIRES);
$canNotifierDossierIncomplet  = $this->isAllowed($admission, AdmissionPrivileges::ADMISSION_NOTIFIER_DOSSIER_INCOMPLET);
$canGenererRecapitulatif  = $this->isAllowed($admission, AdmissionPrivileges::ADMISSION_GENERER_RECAPITULATIF);
$canAccederRecapitulatifSigne  = $this->isAllowed($admission, AdmissionPrivileges::ADMISSION_ACCEDER_RECAPITULATIF_DOSSIER);
$canGererRecapitulatifSigne  = $this->isAllowed(AdmissionPrivileges::getResourceId(AdmissionPrivileges::ADMISSION_GERER_RECAPITULATIF_DOSSIER));
$canVerifierAdmission  = $this->isAllowed($admission, AdmissionPrivileges::ADMISSION_VERIFIER);

$individu = $admission ?$admission->getIndividu()->getId() : null;
/** @var Etudiant $etudiant */
$etudiant = $admission ? $admission->getEtudiant()->first() : null;
/** @var Inscription $inscription */
$inscription = $admission ?$admission->getInscription()->first() : null;
$returnUrl = $this->url('admission/ajouter', ['action' => "document",'individu' => $individu]);
?>

<script>
    let documents = <?php echo json_encode($documents); ?>;
    let individuId = <?php echo $individu; ?>;
</script>

<div class="admission-section-form">
    <div class="admission-section-title-container">
        <h2 class="admission-section-title">Pièces justificatives<label class="admission-section-title-en">&nbsp; /  Supporting documents</label></h2>
    </div>
    <div class="admission-informations-container">
        <i class="fas fa-info-circle"></i>
        <p>
            Chaque pièce justificative ajoutée ci-dessous est automatiquement enregistrée
        </p>
    </div>
    <div class="row subfield">
        <div class="col infos-pieces-justificatives-container">
            <p>Obligatoires<label class="admission-section-doctype-title-en">&nbsp; / Required</label></p>
        </div>
    </div>
    <?php
    echo $this->partial('admission/partial/document/document', [
        'fieldset' => $fieldset->get('diplomeBac'),
        'documents' => $documents,
        'individu' => $individu,
    ]);
    echo $this->partial('admission/partial/document/document', [
        'fieldset' => $fieldset->get('curicculumVitae'),
        'documents' => $documents,
        'individu' => $individu,
    ]);
    echo $this->partial('admission/partial/document/document', [
        'fieldset' => $fieldset->get('financement'),
        'documents' => $documents,
        'individu' => $individu,
    ]);
    echo $this->partial('admission/partial/document/document', [
        'fieldset' => $fieldset->get('projetThese'),
        'documents' => $documents,
        'individu' => $individu,
    ]);
    echo $this->partial('admission/partial/document/document', [
        'fieldset' => $fieldset->get('exemplairesConvention'),
        'documents' => $documents,
        'individu' => $individu,
        'admission' => $admission,
        'returnUrl' => $returnUrl,
        'conventionFormationDoctoraleOperations' => $conventionFormationDoctoraleOperations,
        'conventionFormationDoctorale' => $conventionFormationDoctorale,
        'isOperationAllowedByRole' => $isOperationAllowedByRole
    ]);
    echo $this->partial('admission/partial/document/document', [
        'fieldset' => $fieldset->get('exemplairesCharteDoctorat'),
        'documents' => $documents,
        'individu' => $individu,
        'admission' => $admission,
        'validation_charte_doctorat' => $operations[TypeValidation::CODE_ATTESTATION_HONNEUR_CHARTE_DOCTORALE],
        'isOperationAllowedByRole' => $isOperationAllowedByRole,
        'returnUrl' => $returnUrl,
    ]);
    if ($etudiant->getNiveauEtude() == 2) { ?>
        <div class="row subfield">
            <div class="col infos-pieces-justificatives-container">
                <p>Vous avez un autre diplôme qu'un master français (Dérogation) <label class="admission-section-doctype-title-en">&nbsp; / If other than a French Master's degree (Derogation)</label></p>
            </div>
        </div>
        <div class="row subfield">
            <div class="col-lg-3 col-sm-12 filename-label">
                <label data-after=" / Argument of PhD director for the council of the doctoral school mandatory">Argumentaire du directeur de thèse pour le conseil de l'école doctorale obligatoire</label>
            </div>
            <div class="col-lg-9 col-sm-12">
                <?php echo $this->formControlGroup($fieldset->get('argumentaireDirecteurThese')) ?>
            </div>
        </div>
    <?php }
    if ($etudiant->getNiveauEtude() == 2 && $etudiant->getTypeDiplomeAutre() == 1) { ?>
        <div class="row subfield">
            <div class="col infos-pieces-justificatives-container">
                <p>Vous êtes titulaire d'un titre étranger<label class="admission-section-doctype-title-en">&nbsp; / If the student has a foreign qualification</label></p>
            </div>
        </div>
        <?php
        echo $this->partial('admission/partial/document/document', [
            'fieldset' => $fieldset->get('diplomesRelevesNotesTraduits'),
            'documents' => $documents,
            'individu' => $individu,
        ]);
        echo $this->partial('admission/partial/document/document', [
            'fieldset' => $fieldset->get('acteNaissance'),
            'documents' => $documents,
            'individu' => $individu,
        ]);
        echo $this->partial('admission/partial/document/document', [
            'fieldset' => $fieldset->get('photocopiePasseport'),
            'documents' => $documents,
            'individu' => $individu,
        ]);
    } ?>
    <?php if ($etudiant->getNiveauEtude() == 2 && $etudiant->getTypeDiplomeAutre() == 2){ ?>
        <div class="row subfield">
            <div class="col infos-pieces-justificatives-container">
                <p>Si l'étudiant est titulaire d'un diplôme français ne conférant pas le grade de master</p>
            </div>
        </div>
    <?php
        echo $this->partial('admission/partial/document/document', [
            'fieldset' => $fieldset->get('diplomesTravauxExperiencePro'),
            'documents' => $documents,
            'individu' => $individu,
        ]);
    } ?>
    <?php if ($inscription && ($inscription->getConfidentialite() || $inscription->getCoTutelle() || $inscription->getCoEncadrement())) { ?>
        <div class="row subfield">
            <div class="col infos-pieces-justificatives-container">
                <p>Spécificité(s) demandée(s)<label class="admission-section-doctype-title-en">&nbsp; /  Specificities requested</label></p>
            </div>
        </div>
        <?php if ($inscription->getConfidentialite()) { ?>
            <div class="row subfield">
                <div class="col-lg-3 col-sm-12 filename-label">
                    <?php echo $this->formlabel($fieldset->get('documentsDemandeConfidentialite')) ?>
                </div>
            </div>
        <?php } ?>
        <?php if ($inscription->getCoTutelle()) {
            echo $this->partial('admission/partial/document/document', [
                'fieldset' => $fieldset->get('documentsCotutelle'),
                'documents' => $documents,
                'individu' => $individu,
            ]);
        } ?>
        <?php if ($inscription->getCoEncadrement()) {
            echo $this->partial('admission/partial/document/document', [
                'fieldset' => $fieldset->get('documentsCoencadrement'),
                'documents' => $documents,
                'individu' => $individu,
            ]);
        }
    } ?>
</div>

<?php
if($canAccederCommentaires) {
    echo $this->partial('admission/partial/verification/verification', [
        'admission' => $admission,
        'fcg' => $this->formControlGroup(),
        'fieldset' => $fieldset->get("verificationDocument"),
        'element' => !empty($admission) && !empty($admission->getDocument()->first()) ? $admission->getDocument() : null,
        'elementVerification' => !empty($admission) && !empty($admission->getDocument()->first()) ? $admission->getDocument()->first()->getVerificationDocument() : null,
    ]);
}

//Permet d'enregistrer les commentaires entrés par la/le gestionnaire du dossier
if ($canVerifierAdmission) { ?>
    <div class="admission-enregistrer-verification-container" style="display:none;">
        <input type="submit" name="document[_nav][_submit]"
               class="multipage-nav submit btn btn-success enregistrer-verification-btn" value="Enregistrer les modifications">
        <?php echo $this->formControlGroup($fieldset->get('enregistrerVerification')); ?>
    </div>
<?php } ?>

<div class="row notifier-dossier-incomplet">
    <?php
    if($canNotifierDossierIncomplet && !$admission->isDossierComplet()){
        //Permettre aux gestionnaires de notifier l'étudiant que son dossier est incomplet ?>
        <a class="btn access-notification-dossier-incomplet-btn required" data-operation="NotificationDossierIncomplet">Notifier l'étudiant que son dossier est incomplet</a>
        <div class="modal fade" id="modalShowConfirmationNotificationDossierIncomplet" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="myModalLabel">Confirmation de l'opération</h4>
                    </div>
                    <div class="modal-body">
                        <p>Êtes-vous sûr·e de vouloir notifier l'étudiant que son dossier est incomplet, cela entrainera la dévalidation de l'attestation sur l'honneur de l'étudiant, si celle-ci a été effectuée ?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Annuler</button>
                        <a href="<?php echo $this->url(
                            'admission/notifier-dossier-incomplet',
                            ['admission' => $admission->getId()],
                            ['query' => ['redirect' => $returnUrl]])?>"
                           class="btn btn-success collapsable-action validation-operation-btn"
                           title="Notifier l'étudiant que son dossier est incomplet ?">
                            Valider
                        </a>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
</div>
<div class="admission-section-form">
    <div class="admission-section-title-container">
        <h2 class="admission-section-title">Signatures</h2>
    </div>
    <?php
    unset($operations[TypeValidation::CODE_ATTESTATION_HONNEUR_CHARTE_DOCTORALE]);
    echo $this->partial('admission/admission/partial/circuit-signatures', [
        'operations' => $operations,
        'individu' => $individu,
        'returnUrl' => $returnUrl,
        'operationEnAttente' => $operationEnAttente,
        'admission' => $admission,
        'showActionButtons' => true,
        'isOperationAllowedByRole' => $isOperationAllowedByRole,
        'commentaires' => $commentaires
    ]);

    if ($canGenererRecapitulatif) { ?>
            <a class="btn btn-primary"
               href="<?php echo $this->url('admission/generer-recapitulatif', ['admission' => $admission->getId()], [], true); ?>"
               target="_blank">
                <span class="icon icon-pdf" title="Télécharger le récapitulatif" data-bs-toggle="tooltip" data-bs-html="true"></span>
                Télécharger le récapitulatif du dossier d'admission
            </a>
    <?php }

    //Affichage du bouton seulement si l'on peut gérer un récap signé
    //ou soit que le dossier ne soit pas plus en cours de saisie et que le récap soit déjà uploadé
    if($canAccederRecapitulatifSigne){
        if($canGererRecapitulatifSigne || isset($documents[$fieldset->get('recapitulatifDossierSigne')->getAttribute('id')])){ ?>
            <a class="btn btn-primary access-recap-signe-btn" href="">
                <span class="icon icon-pdf" title="Télécharger le récapitulatif" data-bs-toggle="tooltip" data-bs-html="true"></span>
                <?php if ($canGererRecapitulatifSigne) { ?>
                    Téléverser le récapitulatif signé
                <?php } else { ?>
                    Accéder au récapitulatif signé
                <?php } ?>
            </a>
            <div id="file-recap-signe-container">
                <?php if ($canGererRecapitulatifSigne) {
                    echo $this->partial('admission/partial/document/document', [
                        'fieldset' => $fieldset->get('recapitulatifDossierSigne')->setAttribute('disabled', false),
                        'documents' => $documents,
                        'individu' => $individu,
                    ]);
                } else {
                    echo $this->partial('admission/partial/document/document', [
                        'fieldset' => $fieldset->get('recapitulatifDossierSigne'),
                        'documents' => $documents,
                        'individu' => $individu,
                    ]);
                } ?>
            </div>
        <?php }
    } ?>

</div>