<?php

use Admission\Entity\Db\Admission;
use Admission\Entity\Db\Etat;
use Admission\Entity\Db\TypeValidation;
use Admission\Entity\Db\Verification;
use Admission\Form\Admission\AdmissionForm;
use Admission\Form\Fieldset\Document\DocumentFieldset;
use Admission\Provider\Privilege\AdmissionPrivileges;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer         $this
 * @var DocumentFieldset    $fieldset
 * @var AdmissionForm $form
 * @var Admission $admission
 * @var array[] $operations
 * @var string              $error
 * @var array               $dataForm
 * @var array               $documents
 */
$form->prepare();
$fcg = $this->formControlGroup();

$canVerifierAdmission  = $this->isAllowed($admission, AdmissionPrivileges::ADMISSION_VERIFIER);
$canNotifierGestionnairesAdmission  = $this->isAllowed($admission, AdmissionPrivileges::ADMISSION_NOTIFIER_GESTIONNAIRES);
$canNotifierCommentairesAjoutesAdmission  = $this->isAllowed($admission, AdmissionPrivileges::ADMISSION_NOTIFIER_COMMENTAIRES_AJOUTES);
$canModifierAdmission  =
    $this->isAllowed($admission,AdmissionPrivileges::ADMISSION_MODIFIER_TOUS_DOSSIERS_ADMISSION) ||
    $this->isAllowed($admission,AdmissionPrivileges::ADMISSION_MODIFIER_SON_DOSSIER_ADMISSION);
if(!empty($admission) && !$canModifierAdmission) {
    foreach ($fieldset->getElements() as $element) {
        $element->setAttribute('readonly', true);
    }
}
$individu = $dataForm["etudiant"]["individu"];
?>

<script>
    var readOnly = <?php echo !empty($admission) && !$canModifierAdmission ? '1' : '0'; ?>;
    var documents = <?php echo json_encode($documents); ?>;
    var individuId = <?php echo $individu; ?>;
</script>

<head>
    <link href="https://unpkg.com/filepond@^4/dist/filepond.css" rel="stylesheet"/>
</head>
<script src="https://unpkg.com/filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.js"></script>
<script src="https://unpkg.com/filepond@^4/dist/filepond.js"></script>

<div class="row_sous_partie">
    <div class="title_sous_partie">
        <h2 class="titre_sous_partie">Pièces justificatives</h2>
    </div>
    <div class="row subfield">
        <div class="col informations-pieces_justificatives">
            <p>Obligatoires</p>
        </div>
    </div>
    <?php
        echo $this->partial('admission/partial/document/document', [
        'fieldset' => $fieldset->get('diplomeBac'),
        'documents' => $documents,
        'individu' => $individu,
        ]);
        echo $this->partial('admission/partial/document/document', [
            'fieldset' => $fieldset->get('curicculumVitae'),
            'documents' => $documents,
            'individu' => $individu,
        ]);
        echo $this->partial('admission/partial/document/document', [
            'fieldset' => $fieldset->get('financement'),
            'documents' => $documents,
            'individu' => $individu,
        ]);
        echo $this->partial('admission/partial/document/document', [
            'fieldset' => $fieldset->get('projetThese'),
            'documents' => $documents,
            'individu' => $individu,
        ]);
        echo $this->partial('admission/partial/document/document', [
            'fieldset' => $fieldset->get('exemplairesConvention'),
            'documents' => $documents,
            'individu' => $individu,
        ]);
        echo $this->partial('admission/partial/document/document', [
            'fieldset' => $fieldset->get('exemplairesCharteDoctorat'),
            'documents' => $documents,
            'individu' => $individu,
        ]);
    ?>

    <?php if (isset($dataForm['etudiant']['niveauEtude']) && $dataForm['etudiant']['niveauEtude'] == 2) { ?>
        <div class="row subfield">
            <div class="col informations-pieces_justificatives">
                <p>Vous avez un autre diplôme qu'un master français (Dérogation)</p>
            </div>
        </div>
        <div class="row subfield">
            <div class="col-lg-3 col-sm-12 label-file">
                <?php echo $this->formlabel($fieldset->get('argumentaireDirecteurThese')) ?>
            </div>
            <div class="col-lg-9 col-sm-12">
                <?php echo $this->formtextarea($fieldset->get('argumentaireDirecteurThese')) ?>
            </div>
        </div>
    <?php }
    if (isset($dataForm['etudiant']['niveauEtude']) && $dataForm['etudiant']['niveauEtude'] == 2 && $dataForm['etudiant']['typeDiplomeAutre'] == 1) { ?>
        <div class="row subfield">
            <div class="col informations-pieces_justificatives">
                <p>Vous êtes titulaire d'un titre étranger</p>
            </div>
        </div>
        <?php
        echo $this->partial('admission/partial/document/document', [
            'fieldset' => $fieldset->get('diplomesRelevesNotesTraduits'),
            'documents' => $documents,
            'individu' => $individu,
        ]);
        echo $this->partial('admission/partial/document/document', [
            'fieldset' => $fieldset->get('acteNaissance'),
            'documents' => $documents,
            'individu' => $individu,
        ]);
        echo $this->partial('admission/partial/document/document', [
            'fieldset' => $fieldset->get('photocopiePasseport'),
            'documents' => $documents,
            'individu' => $individu,
        ]);
    } ?>
    <?php if (isset($dataForm['etudiant']['niveauEtude']) && $dataForm['etudiant']['niveauEtude'] == 2 && $dataForm['etudiant']['typeDiplomeAutre'] == 2) {
        echo $this->partial('admission/partial/document/document', [
            'fieldset' => $fieldset->get('diplomesTravauxExperiencePro'),
            'documents' => $documents,
            'individu' => $individu,
        ]);
    } ?>
    <?php
    $confidentialiteChecked = isset($dataForm['inscription']['confidentialite']) && $dataForm['inscription']['confidentialite'] == 1;
    $coTutelleChecked = isset($dataForm['inscription']['coTutelle']) && $dataForm['inscription']['coTutelle'] == 1;
    $coEncadrementChecked = isset($dataForm['inscription']['coEncadrement']) && $dataForm['inscription']['coEncadrement'] == 1;
    $coDirectionChecked = isset($dataForm['inscription']['co-direction']) && $dataForm['inscription']['co-direction'] == 1;
    if ($confidentialiteChecked || $coTutelleChecked || $coEncadrementChecked || $coDirectionChecked) { ?>
        <div class="row subfield">
            <div class="col informations-pieces_justificatives">
                <p>Spécificité(s) demandée(s)</p>
            </div>
        </div>
        <?php if ($confidentialiteChecked) { ?>
            <div class="row subfield">
                <div class="col-lg-3 col-sm-12 label-file">
                    <?php echo $this->formlabel($fieldset->get('documentsDemandeConfidentialite')) ?>
                </div>
            </div>
        <?php } ?>
        <?php if ($coTutelleChecked) {
            echo $this->partial('admission/partial/document/document', [
                'fieldset' => $fieldset->get('documentsCotutelle'),
                'documents' => $documents,
                'individu' => $individu,
            ]);
        } ?>
        <?php if ($coEncadrementChecked) {
            echo $this->partial('admission/partial/document/document', [
                'fieldset' => $fieldset->get('documentsCoencadrement'),
                'documents' => $documents,
                'individu' => $individu,
            ]);
        }
    } ?>
</div>
<?php
if($canModifierAdmission) {
    echo $this->partial('admission/partial/verification/verification', [
        'canVerifierAdmission' => $canVerifierAdmission,
        'fcg' => $fcg,
        'fieldset' => $fieldset->get("verificationDocument"),
        'element' => !empty($admission) && !empty($admission->getDocument()->first()) ? $admission->getDocument() : null,
        'elementVerification' => !empty($admission) && !empty($admission->getDocument()->first()) ? $admission->getDocument()->first()->getVerificationDocument() : null,
    ]);
}
?>
<div class="row notifier_commentaires_ajoutes">
    <?php
    $dossier_complet = false;
    foreach ($operations as $i => $operation):
        $dossier_complet = ($i == TypeValidation::CODE_VALIDATION_GESTIONNAIRE && $operation->getId()) ? true : $dossier_complet;
    endforeach;
    if($canNotifierCommentairesAjoutesAdmission && !$dossier_complet){
        $returnUrl = $this->url('admission/ajouter', ['action' => "document",
                'individu' => $individu]
        ); ?>
        <a href="<?php echo $this->url('admission/notifier-commentaires-ajoutes', [
            'admission' => $admission->getId(),
        ], [
            'query' => ['redirect' => $returnUrl],
        ]) ?>"
           class="btn btn-primary collapsable-action"
           title="Notifier l'étudiant des commentaires ajoutés ?"
           data-toggle="confirmationx"
           data-message="Êtes-vous sûr·e de vouloir notifier l'étudiant des commentaires ajoutés à son dossier ?">Notifier
            l'étudiant des commentaires ajoutés</span></a>
    <?php } ?>
</div>
<div class="row_sous_partie">
    <div class="title_sous_partie">
        <h2 class="titre_sous_partie">Signatures</h2>
    </div>
    <?php
        $returnUrl = $this->url('admission/ajouter', ['action' => "document",
                'individu' => $individu]
        );
        echo $this->partial('admission/admission/partial/validation/circuit_validation', [
            'operations' => $operations,
            'individu' => $individu,
            'returnUrl' => $returnUrl
        ]);
    ?>
</div>
<?php
//Permet à l'étudiant de notifier les gestionnaires de son dossier, seulement si le dossier n'est pas complet
if ($canNotifierGestionnairesAdmission && !$dossier_complet) {
    $returnUrl = $this->url('admission/ajouter', ['action' => "document", 'individu' => $individu]); ?>
    <div class="row notifier_gestionnaires">
        <a href="<?php echo $this->url('admission/notifier-gestionnaire', [
            'admission' => $admission->getId(),
        ], [
            'query' => ['redirect' => $returnUrl],
        ]) ?>"
           class="btn btn-primary collapsable-action"
           title="Notifier vos gestionnaires de la saisie de vos informations, afin qu'ils vérifient votre dossier ?"
           data-toggle="confirmationx"
           data-message="Êtes-vous sûr·e de vouloir notifier vos gestionnaires de la saisie de vos informations, afin qu'ils vérifient votre dossier ?">Notifier
            vos gestionnaires</span></a>
    </div>
<?php } ?>