<?php

use Admission\Entity\Db\Admission;
use Admission\Entity\Db\Etat;
use Admission\Entity\Db\Verification;
use Admission\Form\Admission\AdmissionForm;
use Admission\Form\Fieldset\Etudiant\EtudiantFieldset;
use Admission\Provider\Privilege\AdmissionPrivileges;
use Application\View\Renderer\PhpRenderer;
use Individu\Entity\Db\Individu;

/**
 * @var EtudiantFieldset $fieldset
 * @var PhpRenderer $this
 * @var AdmissionForm $form
 * @var Admission $admission
 * @var Individu $individu
 * @var string $error
 *
 * @see \Admission\Controller\AdmissionController::etudiantAction()
 */

$form->prepare();
$canVerifierAdmission  = $this->isAllowed($admission,AdmissionPrivileges::ADMISSION_VERIFIER);
$canModifierAdmission  =
    $this->isAllowed($admission, AdmissionPrivileges::ADMISSION_MODIFIER_TOUS_DOSSIERS_ADMISSION) ||
    $this->isAllowed($admission, AdmissionPrivileges::ADMISSION_MODIFIER_SON_DOSSIER_ADMISSION);

$fcg = $this->formControlGroup();
if(!empty($admission) && !$canModifierAdmission) {
    foreach ($fieldset->getElements() as $element) {
        $element->setAttribute('readonly', true);
    }
}
?>
<script>
    var readOnly = <?php echo !empty($admission) && !$canModifierAdmission ? 1 : 0 ?>
</script>
<div class="row_sous_partie">
    <div class="title_sous_partie">
        <h2 class="titre_sous_partie">Étudiant</h2>
    </div>
    <div class="row subfield">
        <div class="col-md-6">
            <?php echo $fcg($fieldset->get('ine')) ?>
        </div>
        <div class="col-md-6">
            <?php echo $fcg($fieldset->get('numeroEtudiant')) ?>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-3 col-sm-12">
            <div class="checkbox_admission">
                <?php echo $fcg($fieldset->get('civilite')->setValue($individu->getCivilite())) ?>
            </div>
        </div>
        <div class="col-lg-3">
            <?php echo $fcg($fieldset->get('individu')->setValue($individu->getId())) ?>
            <?php echo $fcg($fieldset->get('nomFamille')->setValue($individu->getNomPatronymique())) ?>
        </div>
        <div class="col-lg-3">
            <?php echo $fcg($fieldset->get('nomUsuel')->setValue($individu->getNomUsuel())) ?>
        </div>
        <div class="col-lg-3 col-sm-12">
            <?php echo $fcg($fieldset->get('prenom')->setValue($individu->getPrenom())) ?>
            <?php echo $fcg($fieldset->get('prenom2')->setValue($individu->getPrenom2())) ?>
            <?php echo $fcg($fieldset->get('prenom3')->setValue($individu->getPrenom3())) ?>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-md-3">
            <?php echo $fcg($fieldset->get('dateNaissance')->setValue($individu->getDateNaissance())) ?>
        </div>
        <div class="col-md-3">
            <?php echo $fcg($fieldset->get('villeNaissance')) ?>
        </div>
        <div class="col-md-3">
            <?php echo $fcg($fieldset->get('paysNaissanceId')->setValue(!empty($individu->getPaysNationalite()) ? $individu->getPaysNationalite()->getId() : null)) ?>
            <?php echo $fcg($fieldset->get('paysNaissance')->setValue(!empty($individu->getPaysNationalite()) ? $individu->getPaysNationalite()->getLibelle() : null)) ?>
        </div>
        <div class="col-md-3">
            <?php echo $fcg($fieldset->get('nationaliteId')->setValue(!empty($individu->getPaysNationalite()) ? $individu->getPaysNationalite()->getId() : null)) ?>
            <?php echo $fcg($fieldset->get('nationalite')->setValue(!empty($individu->getPaysNationalite()) ? $individu->getPaysNationalite()->getLibelleNationalite() : null)) ?>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-md-3">
            <?php echo $fcg($fieldset->get('adresseLigne3Bvoie')) ?>
        </div>
        <div class="col-md-1">
            <?php echo $fcg($fieldset->get('adresseCodePostal')) ?>
        </div>
        <div class="col-lg-3 col-sm-12">
            <?php echo $fcg($fieldset->get('adresseCodeCommune')) ?>
        </div>
        <div class="col-lg-2 col-sm-12">
            <?php echo $fcg($fieldset->get('numeroTelephone1')) ?>
        </div>
        <div class="col-lg-3 col-sm-12">
            <?php echo $fcg($fieldset->get('courriel')->setValue($individu->getEmailContact())) ?>
        </div>
    </div>
    <div class="row subfield">
        <div class="col">
            <div class="checkbox_admission">
                <?php echo $fcg($fieldset->get('situationHandicap')) ?>
                <p class="informations">Si oui, vous pouvez bénéficier d'un accompagnement au cours de votre cursus :
                    N'hésitez pas à
                    contacter le Service Universitaire de Médecine Préventive (SUMPPS) <a href="mailto:sumpps@unicaen.fr">sumpps@unicaen.fr</a> ainsi que le
                    relais
                    handicap santé (<a href="mailto:deve.accueil.handicap@unicaen.fr">deve.accueil.handicap@unicaen.fr</a>)</p>
            </div>
        </div>
    </div>
</div>
<div class="row_sous_partie">
    <div class="title_sous_partie">
        <h2 class="titre_sous_partie">Niveau d'étude permettant l'accès en doctorat</h2>
    </div>
    <div class="row subfield">
        <div class="checkbox_admission">
            <?php echo $fcg($fieldset->get('niveauEtude')) ?>
        </div>
        <div id="additional_fields_diplome">
            <div class="row subfield">
                <div class="col-lg-4 col-sm-12">
                    <?php echo $fcg($fieldset->get('intituleDuDiplomeNational')) ?>
                </div>
                <div class="col-lg-4 col-sm-12">
                    <?php echo $fcg($fieldset->get("anneeDobtentionDiplomeNational")) ?>
                </div>
                <div class="col-lg-4 col-sm-12">
                    <?php echo $fcg($fieldset->get("etablissementDobtentionDiplomeNational")) ?>
                </div>
            </div>
        </div>
        <div id="additional_fields_autre">
            <div class="row subfield">
                <div class="col">
                    <div class="checkbox_admission checkbox_diplome">
                        <?php echo $fcg($fieldset->get('typeDiplomeAutre')) ?>
                    </div>
                </div>
                <p class="informations">Si une Validation des Acquis de l'Expérience (V.A.E) est souhaitée, vous devez
                    au préalable contacter le
                    service spécifique : <a href="mailto:vae@unicaen.fr">vae@unicaen.fr</a></p>
            </div>
            <div class="row subfield">
                <div class="col-sm-12">
                    <?php echo $fcg($fieldset->get('intituleDuDiplomeAutre')) ?>
                </div>
            </div>
            <div class="row subfield">
                <div class="col-lg-6 col-sm-12">
                    <?php echo $fcg($fieldset->get("anneeDobtentionDiplomeAutre")) ?>
                </div>
                <div class="col-lg-6 col-sm-12">
                    <?php echo $fcg($fieldset->get("etablissementDobtentionDiplomeAutre")) ?>
                </div>
            </div>
        </div>
    </div>

</div>

<?php
if($canModifierAdmission){
    echo $this->partial('admission/partial/verification/verification', [
        'canVerifierAdmission' => $canVerifierAdmission,
        'fcg' => $fcg,
        'fieldset' => $fieldset->get("verificationEtudiant"),
        'element' => !empty($admission) ? $admission->getEtudiant() : null,
        'elementVerification' => !empty($admission) ? $admission->getEtudiant()->first()->getVerificationEtudiant() : null
    ]);
}
?>