<?php

use Admission\Form\Fieldset\Etudiant\EtudiantFieldset;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer         $this
 * @var EtudiantFieldset    $fieldset
 * @var string              $error
 *
 * @see \Admission\Controller\AdmissionController::etudiantAction()
 */
$fcg = $this->formControlGroup();
?>
<div class="modal hide fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">SyGAL - Admission</h5>
            </div>
            <div class="modal-body">
                <p>
                    Les informations que vous entrez dans ce formulaire sont automatiquement sauvegardées dès lors que vous passez à l'étape suivante, ou revenez à l'étape précédente.
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Fermer</button>
            </div>
        </div>
    </div>
</div>
<div class="row_sous_partie">
    <div class="title_sous_partie">
        <h2 class="titre_sous_partie">Étudiant</h2>
    </div>
    <div class="row subfield">
        <div class="col-md-6">
            <?php echo $fcg($fieldset->get('ine')) ?>
        </div>
        <div class="col-md-6">
            <?php echo $fcg($fieldset->get('numeroEtudiant')) ?>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-3 col-sm-12">
            <div class="checkbox_admission">
                <?php echo $fcg($fieldset->get('civilite')) ?>
            </div>
        </div>
        <div class="col-lg-3">
            <?php echo $fcg($fieldset->get('nomFamille')) ?>
        </div>
        <div class="col-lg-3">
            <?php echo $fcg($fieldset->get('nomUsuel')) ?>
        </div>
        <div class="col-lg-3 col-sm-12">
            <?php echo $fcg($fieldset->get('prenom')) ?>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-md-3">
            <?php echo $fcg($fieldset->get('dateNaissance')) ?>
        </div>
        <div class="col-md-3">
            <?php echo $fcg($fieldset->get('villeNaissance')) ?>
        </div>
        <div class="col-md-3">
            <?php echo $fcg($fieldset->get('paysNaissance')) ?>
        </div>
        <div class="col-md-3">
            <?php echo $fcg($fieldset->get('nationalite')) ?>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-md-3">
            <?php echo $fcg($fieldset->get('adresseLigne3Bvoie')) ?>
        </div>
        <div class="col-md-1">
            <?php echo $fcg($fieldset->get('adresseCodePostal')) ?>
        </div>
        <div class="col-lg-3 col-sm-12">
            <?php echo $fcg($fieldset->get('adresseCodeCommune')) ?>
        </div>
        <div class="col-lg-2 col-sm-12">
            <?php echo $fcg($fieldset->get('numeroTelephone1')) ?>
        </div>
        <div class="col-lg-3 col-sm-12">
            <?php echo $fcg($fieldset->get('email')) ?>
        </div>
    </div>
    <div class="row subfield">
        <div class="col">
            <div class="checkbox_admission">
                <?php echo $fcg($fieldset->get('situationHandicap')) ?>
                <p class="informations">Si oui, vous pouvez bénéficier d'un accompagnement au cours de votre cursus :
                    N'hésitez pas à
                    contacter le Service Universitaire de Médecine Préventive (SUMPPS) sumpps@unicaen.fr ainsi que le
                    relais
                    handicap santé (<a href="mailto:deve.accueil.handicap@unicaen.fr">deve.accueil.handicap@unicaen.fr</a>)</p>
            </div>
        </div>
    </div>
    <div class="row boutons_gestionnaires">
        <div class="col">
            <a title="Modifier ces éléments" href="<?= $this->url('admission', ['action' => 'addInformationsEtudiantAction']) ?>" class="btn btn-warning bouton_gestionnaire">Modifier</a>
            <a title="Cette partie du formulaire est incomplète" href="<?= $this->url('admission', ['action' => 'addInformationsEtudiantAction']) ?>" class="btn btn-danger bouton_gestionnaire">Incomplet</a>
            <a title="Cette partie du formulaire est complète" href="<?= $this->url('admission', ['action' => 'addInformationsEtudiantAction']) ?>" class="btn btn-success bouton_gestionnaire">Complet</a>
        </div>
    </div>
</div>
<div class="row_sous_partie">
    <div class="title_sous_partie">
        <h2 class="titre_sous_partie">Niveau d'étude permettant l'accès en doctorat</h2>
    </div>
    <div class="row subfield">
        <div class="checkbox_admission">
            <?php echo $fcg($fieldset->get('niveauEtude')) ?>
        </div>
        <div id="additional_fields_diplome">
            <div class="row subfield">
                <div class="col-lg-4 col-sm-12">
                    <?php echo $fcg($fieldset->get('intituleDuDiplome')) ?>
                </div>
                <div class="col-lg-4 col-sm-12">
                    <?php echo $fcg($fieldset->get("anneeDobtentionDiplome")) ?>
                </div>
                <div class="col-lg-4 col-sm-12">
                    <?php echo $fcg($fieldset->get("etablissementDobtentionDiplome")) ?>
                </div>
            </div>
        </div>
        <div id="additional_fields_autre">
            <div class="row subfield">
                <div class="col">
                    <div class="checkbox_admission checkbox_diplome">
                        <?php echo $fcg($fieldset->get('typeDiplomeAutre')) ?>
                    </div>
                </div>
                <p class="informations">Si une Validation des Acquis de l'Expérience (V.A.E) est souhaitée, vous devez
                    au préalable contacter le
                    service spécifique : <a href="mailto:vae@unicaen.fr">vae@unicaen.fr</a></p>
            </div>
            <div class="row subfield">
                <div class="col-sm-12">
                    <?php echo $fcg($fieldset->get('intituleDuDiplome')) ?>
                </div>
            </div>
            <div class="row subfield">
                <div class="col-lg-6 col-sm-12">
                    <?php echo $fcg($fieldset->get("anneeDobtentionDiplome")) ?>
                </div>
                <div class="col-lg-6 col-sm-12">
                    <?php echo $fcg($fieldset->get("etablissementDobtentionDiplome")) ?>
                </div>
            </div>
        </div>
    </div>
    <div class="row boutons_gestionnaires">
        <div class="col">
            <a title="Modifier ces éléments" href="<?= $this->url('admission', ['action' => 'addInformationsEtudiantAction']) ?>" class="btn btn-warning bouton_gestionnaire">Modifier</a>
            <a title="Cette partie du formulaire est incomplète" href="<?= $this->url('admission', ['action' => 'addInformationsEtudiantAction']) ?>" class="btn btn-danger bouton_gestionnaire">Incomplet</a>
            <a title="Cette partie du formulaire est complète" href="<?= $this->url('admission', ['action' => 'addInformationsEtudiantAction']) ?>" class="btn btn-success bouton_gestionnaire">Complet</a>
        </div>
    </div>
</div>

<?php ///** @see \Admission\Controller\AdmissionController::envoyerMailAction() */ ?>
<!--<a href="--><?php //echo $this->url('admission/envoyer-mail', [], [], true); ?><!--"-->
<!--   class="btn btn-primary">-->
<!--    <span class="icon icon-notifier"></span>-->
<!--    Envoyer un mail-->
<!--</a>-->
