<?php

use Admission\Entity\Db\Admission;
use Admission\Entity\Db\Etat;
use Admission\Entity\Db\Verification;
use Admission\Form\Admission\AdmissionForm;
use Admission\Form\Fieldset\Financement\FinancementFieldset;
use Admission\Provider\Privilege\AdmissionPrivileges;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer         $this
 * @var FinancementFieldset    $fieldset
 * @var AdmissionForm $form
 * @var Admission $admission
 * @var string              $error
 *
 */
$form->prepare();
$fcg = $this->formControlGroup();
$canVerifierAdmission  = $this->isAllowed($admission, AdmissionPrivileges::ADMISSION_VERIFIER);
$canModifierAdmission  =
    $this->isAllowed($admission,AdmissionPrivileges::ADMISSION_MODIFIER_TOUS_DOSSIERS_ADMISSION) ||
    $this->isAllowed($admission, AdmissionPrivileges::ADMISSION_MODIFIER_SON_DOSSIER_ADMISSION);
if(!empty($admission) && !$canModifierAdmission) {
    foreach ($fieldset->getElements() as $element) {
        $element->setAttribute('readonly', true);
    }
}
?>
<script>
    var readOnly = <?php echo !empty($admission) && !$canModifierAdmission ? 1 : 0 ?>
</script>
<div class="row_sous_partie">
    <div class="title_sous_partie">
        <h2 class="titre_sous_partie">Financement</h2>
    </div>
    <div class="row subfield">
        <div class="col-lg-2 col-sm-12">
            <div class="checkbox_admission">
                <?php echo $this->formControlGroup($fieldset->get('contratDoctoral')) ?>
            </div>
        </div>
        <div class="col-lg-10 col-sm-12">
            <div id="additional_fields_contrat_doctoral">
                <div class="row">
                    <div class="col-lg-12 col-sm-12">
                        <?php echo $this->formControlGroup($fieldset->get('employeurContrat')) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-12 col-sm-12">
            <p class="informations">Merci de préciser le nom, l'acronyme, adresse, coordonnées de la structure publique ou privée signataire du contrat</p>
            <?php echo $this->formControlGroup($fieldset->get('detailContratDoctoral')) ?>
        </div>
    </div>
</div>
<?php
if($canModifierAdmission) {
    echo $this->partial('admission/partial/verification/verification', [
        'canVerifierAdmission' => $canVerifierAdmission,
        'fcg' => $fcg,
        'fieldset' => $fieldset->get("verificationFinancement"),
        'element' => !empty($admission->getFinancement()->first()) ? $admission->getFinancement() : null,
        'elementVerification' => !empty($admission->getFinancement()->first()) ? $admission->getFinancement()->first()->getVerificationFinancement() : null
    ]);
}
?>