<?php
/**
* @var PhpRenderer $this
* @var Admission $admission
* @var Individu $individu
*
* @see \Admission\Controller\AdmissionController::etudiantAction()
*/

use Admission\Entity\Db\Admission;
use Admission\Provider\Privilege\AdmissionPrivileges;
use Application\View\Renderer\PhpRenderer;
use Individu\Entity\Db\Individu;

$canConfigurerModule = $this->isAllowed(AdmissionPrivileges::getResourceId(AdmissionPrivileges::ADMISSION_CONFIGURER_MODULE));

?>
<div class="header-admission">
    <?php
        $individu = isset($individu) ? " de ".$individu->getNomComplet() : null;
        $individu = isset($admission) ? " de ".$admission->getIndividu()->getNomComplet() : $individu;
        $this->headTitle($this->translate($title = "Admission".$individu))
    ?>

    <h1 class="page-header"><?php echo $this->translate($title); ?> </h1>
    <?php if(!isset($individu) && $canConfigurerModule):
        /** @see \Admission\Controller\AdmissionController::configurerModuleAdmissionAction() */?>
        <a href="<?php echo $this->url('admission/configurer-module-admission', [], [], true); ?>" class="float-end btn btn-primary">
            <span class="icon icon-gerer"></span> Gérer le module Admission
        </a>
    <?php endif; ?>


    <p class="introduction">Ce module permet dans un premier temps de candidater à un parcours doctoral.
        <br>Vous devrez remplir un formulaire en ligne et déposer les documents demandés.<br>
        Les données que vous saisissez dans ce formulaire sont automatiquement sauvegardées dès que vous avancez vers l'étape suivante, ou que vous revenez à l'étape précédente.
    </p>


</div>
