<?php
/**
* @var PhpRenderer $this
* @var Admission $admission
* @var Individu $individu
*
* @see \Admission\Controller\AdmissionController::etudiantAction()
*/

use Admission\Entity\Db\Admission;
use Application\View\Renderer\PhpRenderer;
use Individu\Entity\Db\Individu;

?>
<div class="header-admission">
    <?php
        $individu = isset($individu) ? " de ".$individu->getNomComplet() : null;
        $individu = isset($admission) ? " de ".$admission->getIndividu()->getNomComplet(false, false, false, true) : $individu;
        $this->headTitle($this->translate($title = "Admission".$individu))
    ?>

    <h1 class="page-header"><?php echo $this->translate($title); ?> </h1>

    <p class="introduction">Ce module permet dans un premier temps de candidater à un parcours doctoral.
        <br>Vous devrez remplir un formulaire en ligne et déposer les documents demandés.<br>
        Les données que vous saisissez dans ce formulaire sont automatiquement sauvegardées dès que vous avancez vers l'étape suivante, ou que vous revenez à l'étape précédente.
    </p>
</div>
