<?php

use Admission\Entity\Db\Admission;
use Admission\Entity\Db\Inscription;
use Admission\Entity\Db\Verification;
use Admission\Form\Admission\AdmissionForm;
use Admission\Form\Fieldset\Inscription\InscriptionFieldset;
use Admission\Provider\Privilege\AdmissionPrivileges;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer         $this
 * @var InscriptionFieldset    $fieldset
 * @var AdmissionForm $form
 * @var Admission $admission
 * @var string              $error
 *
 */
$form->prepare();
$fcg = $this->formControlGroup();
$canVerifierAdmission  = $this->isAllowed(AdmissionPrivileges::getResourceId(AdmissionPrivileges::ADMISSION_VERIFIER));
?>
<div class="row_sous_partie">
    <div class="title_sous_partie">
        <h2 class="titre_sous_partie">Inscription demandée</h2>
    </div>
    <div class="row subfield">
        <div class="col">
                <?php echo $this->formControlGroup($fieldset->get('disciplineDoctorat')) ?>
        </div>
        <div class="col-lg-6 col-sm-12">
            <?php echo $this->formControlGroup($fieldset->get('specialiteDoctorat')) ?>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-6 col-sm-12">
            <?php echo $this->formControlGroup($fieldset->get('composanteDoctorat')) ?>
        </div>
        <div class="col-lg-6 col-sm-12">
            <?php echo $this->formControlGroup($fieldset->get('ecoleDoctorale')) ?>
        </div>
    </div>
    <div class="row subfield">
        <div class="col">
            <?php echo $this->formControlGroup($fieldset->get('uniteRecherche')) ?>
        </div>
    </div>
    <div class="row subfield">
        <?php echo $this->formControlGroup($fieldset->get('directeur')) ?>
        <div class="col-lg-4 col-sm-12">
            <?php echo $this->formControlGroup($fieldset->get('nomDirecteurThese')) ?>
        </div>
        <div class="col-lg-4 col-sm-12">
            <?php echo $this->formControlGroup($fieldset->get('prenomDirecteurThese')) ?>
        </div>
        <div class="col-lg-4 col-sm-12">
            <?php echo $this->formControlGroup($fieldset->get('emailDirecteurThese')) ?>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-12 titre_these">
            <label class="form-label" for="inscription[titreThese]">Titre provisoire de la thèse</label>
            <span class="icon icon-information" data-toggle="tooltip" title="Le titre saisi dans ce champ est provisoire et pourra être modifié ultérieurement durant votre parcours doctoral"></span>
        </div>
        <div class="col">
            <?php echo $this->formControlGroup($fieldset->get('titreThese')) ?>
        </div>
    </div>
</div>
<div class="row_sous_partie">
    <div class="title_sous_partie">
        <div class="row">
            <div class="col-lg-4 col-sm-12">
                <h2 class="titre_sous_partie">Spécificités envisagées</h2>
            </div>
            <div class="col">
                <p class="informations-title-sous-partie">Demande de spécificité(s) à émettre obligatoirement via le(s) formulaire(s) téléchargeable(s) sur le site internet UNICAEN</p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="row subfield">
            <div class="col-lg-2 col-sm-12">
                <div class="checkbox_admission">
                    <?php echo $this->formControlGroup($fieldset->get('confidentialite')) ?>
                </div>
            </div>
            <div class="col-lg-10 col-sm-12">
                <div id="additionalFieldsConfidentialite">
                    <div class="row">
                        <div class="col-lg-6 col-sm-12">
                            <?php echo $this->formControlGroup($fieldset->get('dateConfidentialite')) ?>
                        </div>
                        <div class="col-lg-6 col-sm-12 informations-confidentialite-souhaitee">
                            <p class="informations">A demander et motiver dans la convention de formation doctorale</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row subfield">
            <div class="col-lg-2 col-sm-12">
                <div class="checkbox_admission">
                    <?php echo $this->formControlGroup($fieldset->get('coTutelle')) ?>
                </div>
            </div>
            <div class="col-lg-10 col-sm-12">
                <div id="additionalFieldsCotutelle">
                    <div class="row">
                        <div class="col-lg-6 col-sm-12">
                            <?php echo $this->formControlGroup($fieldset->get('paysCoTutelle')) ?>
                        </div>
                        <div class="col-lg-6 col-sm-12">
                            <p class="informations">Attention, il est OBLIGATOIRE d'en faire la demande officielle via le formulaire spécifique. Retrouvez toutes les informations en ligne : <a href="https://unicaen.fr/recherche/etudes-doctorales/faire-une-these/partir à l'étranger/faire-sa-these-en-cotutelle-internationale/">https://unicaen.fr/recherche/etudes-doctorales/faire-une-these/partir à l'étranger/faire-sa-these-en-cotutelle-internationale/</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row subfield">
            <div class="col-lg-2 col-sm-12">
                <div class="checkbox_admission">
                    <?php echo $this->formControlGroup($fieldset->get('coDirection')) ?>
                </div>
            </div>
            <div class="col-lg-10 col-sm-12">
                <div id="additionalFieldsCodirection">
                    <div class="row">
                        <?php echo $this->formControlGroup($fieldset->get('coDirecteur')) ?>
                        <div class="col-lg-4 col-sm-12">
                            <?php echo $this->formControlGroup($fieldset->get('nomCodirecteurThese')) ?>
                        </div>
                        <div class="col-lg-4 col-sm-12">
                            <?php echo $this->formControlGroup($fieldset->get('prenomCodirecteurThese')) ?>
                        </div>
                        <div class="col-lg-4 col-sm-12">
                            <?php echo $this->formControlGroup($fieldset->get('emailCodirecteurThese')) ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row subfield">
            <div class="col-lg-2 col-sm-12">
                <div class="checkbox_admission">
                    <?php echo $this->formControlGroup($fieldset->get('coEncadrement')) ?>
                </div>
            </div>
            <div class="col-lg-10 col-sm-12">
                <p class="informations">Extrait de la décision du Conseil Académique de Normandie du 13 septembre 2016 : "Le co-encadrement de thèse s'adresse exclusivement aux personnes non H.D.R. de la ComUE Normandie université souhaitant acquérir une expérience en encadrement en vue de l'obtention de l'H.D.R. Retrouvez toutes les informations et le formulaire en ligne : <a href="https://unicaen.fr/recherche/etudes-doctorales/faire-une-these/sinscrire-en-doctorat/suivi-et-modification-du-doctorat/demande-de-reconnaissance-de-co-encadrement-de-these/">https://unicaen.fr/recherche/etudes-doctorales/faire-une-these/sinscrire-en-doctorat/suivi-et-modification-du-doctorat/demande-de-reconnaissance-de-co-encadrement-de-these/</a></p>
            </div>
        </div>
    </div>
</div>
<div class="row_sous_partie">
    <div class="title_sous_partie">
        <h2 class="titre_sous_partie">Commentaires</h2>
    </div>
    <?php if ($canVerifierAdmission) { ?>
        <div class="row observations_gestionnaire">
            <div class="col">
                <?php echo $fcg($fieldset->get("verificationInscription")->get('estComplet')) ?>
            </div>
            <div class="commentaires_gestionnaire">
                <?php echo $fcg($fieldset->get("verificationInscription")->get('commentaire')) ?>
            </div>
        </div>
    <?php }else{ ?>
        <div class="commentaires_gestionnaire">
            <div class="partie_etudiant">
                <?php
                /** @var Verification $verification */
                $verification = !empty($admission->getInscription()->first()) ? $admission->getInscription()->first()->getVerificationInscription()->first() : null;
                $nom = !empty($verification) ? $verification->getIndividu()->getNomUsuel() : null;
                $prenom = !empty($verification) ? $verification->getIndividu()->getPrenom() : null;
                $commentaire = !empty($verification) ? $verification->getCommentaire() : null ;
                $date_verification = !empty($verification) ? $verification->getHistoModification()->format('d/m/Y H:i') : null;
                echo !empty($commentaire) ? "<p class='gestionnaire'>".$nom." ".$prenom." (".$date_verification.")</p><p> :  ".$commentaire." </p>" : "<p class='pas_de_commentaire'>Pas de commentaire renseigné par vos gestionnaires</p>";
                ?>
            </div>
        </div>
    <?php  } ?>
</div>