<?php

use Admission\Entity\Db\Admission;
use Admission\Form\Admission\AdmissionForm;
use Admission\Form\Fieldset\Inscription\InscriptionFieldset;
use Admission\Provider\Privilege\AdmissionPrivileges;
use Application\Entity\Db\Role;
use Application\View\Renderer\PhpRenderer;
use Laminas\Form\Element\Select;
use UnicaenApp\Form\Element\SearchAndSelect;
use UnicaenRenderer\Entity\Db\Rendu;
use UnicaenRenderer\Provider\Privilege\DocumenttemplatePrivileges;

/**
 * @var PhpRenderer         $this
 * @var InscriptionFieldset    $fieldset
 * @var AdmissionForm $form
 * @var Admission $admission
 * @var string              $error
 * @var Rendu              $texteCotutelle
 * @var Rendu              $texteCoencadrement
 * @var Role $role
 *
 */
$form->prepare();
$canAccederCommentaires = $this->isAllowed($admission,AdmissionPrivileges::ADMISSION_ACCEDER_COMMENTAIRES);
$canModifier = $this->isAllowed(DocumenttemplatePrivileges::getResourceId(DocumenttemplatePrivileges::DOCUMENTTEMPLATE_MODIFIER));

?>
<div class="admission-section-form">
    <div class="admission-section-title-container">
        <h2 class="admission-section-title">Inscription demandée<label class="admission-section-title-en">&nbsp; /  Application for registration</label></h2>
        </h2>
    </div>
    <div class="row subfield">
        <div class="col">
                <?php echo $this->formControlGroup($fieldset->get('disciplineDoctorat')) ?>
        </div>
        <div class="col-lg-6 col-sm-12">
            <?php echo $this->formControlGroup($fieldset->get('specialiteDoctorat')) ?>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-6 col-sm-12">
            <?php echo $this->formControlGroup($fieldset->get('composanteDoctoratLibelle')) ?>
        </div>
        <div class="col-lg-6 col-sm-12">
            <?php echo $this->formControlGroup($fieldset->get('ecoleDoctorale')) ?>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-4 col-sm-12">
            <?php echo $this->formControlGroup($fieldset->get('uniteRecherche')) ?>
        </div>
        <div class="col-lg-5 col-sm-12">
            <?php echo $this->formControlGroup($fieldset->get('etablissementLaboratoireRecherche')) ?>
        </div>
        <div class="col-lg-3 col-sm-12">
            <?php echo $this->formControlGroup($fieldset->get('etablissementInscription')) ?>
        </div>
    </div>
    <div class="row subfield">
        <?php echo $this->formControlGroup($fieldset->get('directeur')) ?>
        <div class="col-lg-6 col-sm-12">
            <?php
            $inscriptionExist = $admission && $admission->getInscription()->first();
            if(!$inscriptionExist ||
                empty($admission->getInscription()->first()->getDirecteur())){ ?>
                <label class="form-label" for="inscription[nomDirecteurThese]">Nom du directeur de thèse</label><label class="label_en">&nbsp; / Lastname of thesis supervisor</label>
                <span class="icon icon-warning admission-info-bulle" data-toggle="tooltip" style="display:none;">
                    <span class="tooltip-text">Le dossier n'a pas pu être associé au directeur de thèse désigné, puisque <b>l'individu n'est pas connu de l'application.</b> <br> Veillez à bien sélectionner un individu dans la liste proposée <br><br> Rapprochez-vous de votre gestionnaire, si vous ne trouvez pas l'individu recherché</span>
                </span>
            <?php }else{ ?>
                    <label class="form-label" for="inscription[nomDirecteurThese]">Nom du directeur de thèse</label><label class="label_en">&nbsp; / Lastname of thesis supervisor</label>
                        <?php if($inscriptionExist &&
                              $admission->getInscription()->first()->getDirecteur()){ ?>
                    <span class="icon icon-success admission-info-bulle" data-toggle="tooltip">
                        <span class="tooltip-text">Le dossier a bien été associé au directeur de thèse désigné</span>
                    </span>
                <?php } ?>
            <?php } ?>
            <?php echo $this->formControlGroup($fieldset->get('nomDirecteurThese')) ?>
        </div>
        <div class="col-lg-6 col-sm-12">
            <?php echo $this->formControlGroup($fieldset->get('prenomDirecteurThese')) ?>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-6 col-sm-12">
            <?php echo $this->formControlGroup($fieldset->get('emailDirecteurThese')) ?>
        </div>
        <div class="col-lg-6 col-sm-12">
            <?php echo $this->formControlGroup($fieldset->get('fonctionDirecteurThese')) ?>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-12 these-titre-container">
            <label class="form-label" for="inscription[titreThese]">Titre provisoire de la thèse</label><label class="label_en">&nbsp; / Provisional title of thesis</label>
            <span class="icon icon-information admission-info-bulle" data-toggle="tooltip">
                <span class="tooltip-text">Le titre saisi dans ce champ est provisoire et pourra être modifié ultérieurement durant votre parcours doctoral</span>
            </span>
        </div>
        <div class="col">
            <?php echo $this->formControlGroup($fieldset->get('titreThese')) ?>
        </div>
    </div>
</div>
<div class="admission-section-form">
    <div class="admission-section-title-container">
        <div class="row">
            <div class="col-lg-5 col-sm-12">
                <h2 class="admission-section-title specifites-section-title">Spécificités envisagées<label class="admission-section-title-en">&nbsp; / Specificity(ies) planned</label></h2>
            </div>
            <div class="col">
                <p class="admission-informations-title-section">Demande de spécificité(s) à émettre obligatoirement via le(s) formulaire(s) téléchargeable(s) sur le site internet de votre établissement d'inscription</p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="row subfield">
            <div class="col-lg-3 col-sm-12">
                <div class="admission-form-checkboxes">
                    <?php echo $this->formControlGroup($fieldset->get('confidentialite')) ?>
                </div>
            </div>
            <div class="col-lg-9 col-sm-12">
                <div id="additionalFieldsConfidentialite">
                    <div class="row">
                        <div class="col-lg-6 col-sm-12">
                            <?php echo $this->formControlGroup($fieldset->get('dateConfidentialite')) ?>
                        </div>
                        <div class="col-lg-6 col-sm-12 informations-confidentialite-souhaitee">
                            <p class="admission-field-information">A demander et motiver dans la convention de formation doctorale (présente à la dernière étape de ce formulaire)</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row subfield">
            <div class="col-lg-3 col-sm-12">
                <div class="admission-form-checkboxes">
                    <div class="col-lg-12 these-titre-container">
                        <label class="form-label" for="inscription[coTutelle]">Cotutelle envisagée</label><label class="label_en">&nbsp; / Planned cotutelle</label>
                        <span class="icon icon-information admission-info-bulle" data-toggle="tooltip">
                            <span class="tooltip-text">
                                La cotutelle de thèse est un dispositif qui favorise la coopération scientifique entre des équipes de recherche française et étrangère.
                                <br>
                                <br>
                                Thesis cotutelle is a system that encourages scientific cooperation between French and foreign research teams.
                            </span>
                        </span>
                    </div>
                    <?php echo $this->formControlGroup($fieldset->get('coTutelle')) ?>
                </div>
            </div>
            <div class="col-lg-9 col-sm-12">
                <div id="additionalFieldsCotutelle">
                    <div class="row">
                        <div class="col-lg-6 col-sm-12">
                            <?php echo $this->formControlGroup($fieldset->get('paysCoTutelle')) ?>
                        </div>
                        <div class="col-lg-6 col-sm-12">
                            <?php
                            $texteCotutelleCorps = preg_replace('/<\/?p>/', '', $texteCotutelle->getCorps());
                            if($role->getCode() === Role::CODE_GEST_ED): ?>
                                <p class="admission-field-information information-modifiable" data-bs-toggle="tooltip" title="Ce champ est personnalisable en fonction de l'établissement d'inscription. Pour le modifier, vous devez être Administrateur technique" style="cursor:default;">
                                    <?= $texteCotutelleCorps ?>
                                    <span class="icon icon-modifier edit-icon"></span>
                                </p>
                            <?php elseif($role->getCode() === Role::CODE_ADMIN_TECH):
                                /** @see TemplateController::modifierAction */
                                $lien = $canModifier ? $this->url('contenu/template/modifier', ['template' => $texteCotutelle->getTemplate()->getId()], [], true) : "#"; ?>
                                <a href="<?php echo $lien; ?>" class="ajax-modal" data-event="modification-template">
                                    <p class="admission-field-information information-modifiable" data-bs-toggle="tooltip" title="Modifier ce champ">
                                        <?= $texteCotutelleCorps ?>
                                        <span class="icon icon-modifier edit-icon"></span>
                                    </p>
                                </a>
                            <?php else: ?>
                                <p class="admission-field-information"><?= $texteCotutelleCorps ?></p>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row subfield">
            <div class="col-lg-3 col-sm-12">
                <div class="admission-form-checkboxes">
                    <?php echo $this->formControlGroup($fieldset->get('coDirection')) ?>
                </div>
            </div>
            <div class="col-lg-9 col-sm-12">
                <div id="additionalFieldsCodirection">
                    <div class="row">
                        <?php echo $this->formControlGroup($fieldset->get('coDirecteur')) ?>
                        <div class="col-lg-6 col-sm-12">
                            <?php if(!$inscriptionExist ||
                                    empty($admission->getInscription()->first()->getCoDirecteur())){ ?>
                                    <label class="form-label" for="inscription[nomCoDirecteurThese]">Nom du co-directeur de thèse</label><label class="label_en">&nbsp; / Lastname of thesis co-supervisor</label>
                                    <span class="icon icon-warning admission-info-bulle" data-toggle="tooltip" style="display:none;">
                                        <span class="tooltip-text">Le dossier n'a pas pu être associé au co-directeur de thèse désigné, puisque <b>l'individu n'est pas connu de l'application.</b> <br> Veillez à bien sélectionner un individu dans la liste proposée <br><br> Rapprochez-vous de votre gestionnaire, si vous ne trouvez pas l'individu recherché</span>
                                    </span>
                            <?php }else{ ?>
                                <label class="form-label" for="inscription[nomCoDirecteurThese]">Nom du co-directeur de thèse</label><label class="label_en">&nbsp; / Lastname of thesis co-supervisor</label>
                                <?php if($inscriptionExist &&
                                        $admission->getInscription()->first()->getCoDirecteur()){ ?>
                                        <span class="icon icon-success admission-info-bulle" data-toggle="tooltip">
                                            <span class="tooltip-text">Le dossier a bien été associé au co-directeur de thèse désigné</span>
                                        </span>
                                <?php } ?>
                            <?php } ?>
                            <?php echo $this->formControlGroup($fieldset->get('nomCodirecteurThese')) ?>
                        </div>
                        <div class="col-lg-6 col-sm-12">
                            <?php echo $this->formControlGroup($fieldset->get('prenomCodirecteurThese')) ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-4 col-sm-12">
                            <?php echo $this->formControlGroup($fieldset->get('emailCodirecteurThese')) ?>
                        </div>
                        <div class="col-lg-4 col-sm-12">
                            <?php echo $this->formControlGroup($fieldset->get('uniteRechercheCoDirecteur')) ?>
                        </div>
                        <div class="col-lg-4 col-sm-12">
                            <?php echo $this->formControlGroup($fieldset->get('etablissementRattachementCoDirecteur')) ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <?php echo $this->formControlGroup($fieldset->get('fonctionCoDirecteurThese')) ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row subfield">
            <div class="col-lg-3 col-sm-12">
                <div class="admission-form-checkboxes">
                    <?php echo $this->formControlGroup($fieldset->get('coEncadrement')) ?>
                </div>
            </div>
            <div class="col-lg-9 col-sm-12">
                <?php
                $texteCoencadrementCorps = preg_replace('/<\/?p>/', '', $texteCoencadrement->getCorps());
                if($role->getCode() === Role::CODE_GEST_ED): ?>
                    <p class="admission-field-information information-modifiable" data-bs-toggle="tooltip" title="Ce champ est personnalisable en fonction de l'établissement d'inscription. Pour le modifier, vous devez être Administrateur technique" style="cursor:default;">
                        <?= $texteCoencadrementCorps ?>
                        <span class="icon icon-modifier edit-icon"></span>
                    </p>
                <?php elseif($role->getCode() === Role::CODE_ADMIN_TECH):
                    /** @see TemplateController::modifierAction */
                    $lien = $canModifier ? $this->url('contenu/template/modifier', ['template' => $texteCoencadrement->getTemplate()->getId()], [], true) : "#"; ?>
                    <a href="<?php echo $lien; ?>" class="ajax-modal" data-event="modification-template">
                        <p class="admission-field-information information-modifiable" data-bs-toggle="tooltip" title="Modifier ce champ">
                            <?= $texteCoencadrementCorps ?>
                            <span class="icon icon-modifier edit-icon"></span>
                        </p>
                    </a>
                <?php else: ?>
                    <p class="admission-field-information"><?= $texteCoencadrementCorps ?></p>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<?php
if($canAccederCommentaires) {
    echo $this->partial('admission/partial/verification/verification', [
        'admission' => $admission,
        'fcg' => $this->formControlGroup(),
        'fieldset' => $fieldset->get("verificationInscription"),
        'element' => !empty($admission) && !empty($admission->getInscription()) ? $admission->getInscription() : null,
        'elementVerification' => !empty($admission) && !empty($admission->getInscription()->first()) ? $admission->getInscription()->first()->getVerificationInscription() : null
    ]);
}
?>
<script>
    $(function() {
        var body = $("body");
        body.on("modification-template", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
