<?php

use Admission\Fieldset\Justificatifs\ValidationFieldset;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer         $this
 * @var ValidationFieldset    $fieldset
 * @var string              $error
 *
 */
$fcg = $this->formControlGroup();
var_dump($data_form);
?>
<div class="row_sous_partie">
    <div class="title_sous_partie">
        <h2 class="titre_sous_partie">Pièces justificatives</h2>
    </div>
    <div class="row subfield">
        <div class="col informations-pieces_justificatives">
            <p>Obligatoires</p>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-3 col-sm-12">
            <?php echo $this->formlabel($fieldset->get("pieces_justificatives")->get('diplome_bac')) ?>
        </div>
        <div class="col-lg-9 col-sm-12">
            <div class="row detail_file">
                <div class="col-lg-1 upload_file">
                    <i class="icon icon-upload"></i>
                    <?php echo $this->formfile($fieldset->get("pieces_justificatives")->get('diplome_bac')) ?>
                </div>
                <div class="col-lg-2 date_televersement">
                    <p>Téléversé le 25/09/2023</p>
                </div>
                <div class="col-lg-1 action_file">
                    <span class="icon icon-voir iconly" title="Voir le fichier"></span>
                    <span class="icon icon-delete iconly text-danger" title="Supprimer le fichier"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-3 col-sm-12">
            <?php echo $this->formlabel($fieldset->get("pieces_justificatives")->get('curicculum_vitae')) ?>
        </div>
        <div class="col-lg-9 col-sm-12">
            <div class="row detail_file">
                <div class="col-lg-1 upload_file">
                    <i class="icon icon-upload"></i>
                    <?php echo $this->formfile($fieldset->get("pieces_justificatives")->get('curicculum_vitae')) ?>
                </div>
                <div class="col-lg-2 date_televersement">
                </div>
                <div class="col-lg-1 action_file">
                    <span class="icon icon-voir iconly" title="Voir le fichier"></span>
                    <span class="icon icon-delete iconly text-danger" title="Supprimer le fichier"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-3 col-sm-12">
            <?php echo $this->formlabel($fieldset->get("pieces_justificatives")->get('financement')) ?>
        </div>
        <div class="col-lg-9 col-sm-12">
            <div class="row detail_file">
                <div class="col-lg-1 upload_file">
                    <i class="icon icon-upload"></i>
                    <?php echo $this->formfile($fieldset->get("pieces_justificatives")->get('financement')) ?>
                </div>
                <div class="col-lg-2 date_televersement">
                    <p>Téléversé le 25/09/2023</p>
                </div>
                <div class="col-lg-1 action_file">
                    <span class="icon icon-voir iconly" title="Voir le fichier"></span>
                    <span class="icon icon-delete iconly text-danger" title="Supprimer le fichier"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-3 col-sm-12">
            <?php echo $this->formlabel($fieldset->get("pieces_justificatives")->get('projet_these')) ?>
        </div>
        <div class="col-lg-9 col-sm-12">
            <div class="row detail_file">
                <div class="col-lg-1 upload_file">
                    <i class="icon icon-upload"></i>
                    <?php echo $this->formfile($fieldset->get("pieces_justificatives")->get('projet_these')) ?>
                </div>
                <div class="col-lg-2 date_televersement">
                </div>
                <div class="col-lg-1 action_file">
                    <span class="icon icon-voir iconly" title="Voir le fichier"></span>
                    <span class="icon icon-delete iconly text-danger" title="Supprimer le fichier"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-3 col-sm-12">
            <?php echo $this->formlabel($fieldset->get("pieces_justificatives")->get('exemplaires_convention')) ?>
        </div>
        <div class="col-lg-9 col-sm-12">
            <div class="row detail_file">
                <div class="col-lg-1 upload_file">
                    <i class="icon icon-upload"></i>
                    <?php echo $this->formfile($fieldset->get("pieces_justificatives")->get('exemplaires_convention')) ?>
                </div>
                <div class="col-lg-2 date_televersement">
                    <p>Téléversé le 24/09/2023</p>
                </div>
                <div class="col-lg-1 action_file">
                    <span class="icon icon-voir iconly" title="Voir le fichier"></span>
                    <span class="icon icon-delete iconly text-danger" title="Supprimer le fichier"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-3 col-sm-12">
            <?php echo $this->formlabel($fieldset->get("pieces_justificatives")->get('exemplaires_charte_doctorat')) ?>
        </div>
        <div class="col-lg-9 col-sm-12">
            <div class="row detail_file">
                <div class="col-lg-1 upload_file">
                    <i class="icon icon-upload"></i>
                    <?php echo $this->formfile($fieldset->get("pieces_justificatives")->get('exemplaires_charte_doctorat')) ?>
                </div>
                <div class="col-lg-2 date_televersement">
                    <p>Téléversé le 25/09/2023</p>
                </div>
                <div class="col-lg-1 action_file">
                    <span class="icon icon-voir iconly" title="Voir le fichier"></span>
                    <span class="icon icon-delete iconly text-danger" title="Supprimer le fichier"></span>
                </div>
            </div>
        </div>
    </div>

    <div class="row subfield">
        <div class="col informations-pieces_justificatives">
            <p>Si autre diplôme qu'un master français (Dérogation)</p>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-3 col-sm-12">
            <?php echo $this->formlabel($fieldset->get("pieces_justificatives")->get('argumentaire_directeur_these')) ?>
        </div>
        <div class="col-lg-9 col-sm-12">
            <?php echo $this->formtextarea($fieldset->get("pieces_justificatives")->get('argumentaire_directeur_these')) ?>
        </div>
    </div>

    <div class="row subfield">
        <div class="col informations-pieces_justificatives">
            <p>Si l'étudiant est titulaire d'un titre étranger</p>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-3 col-sm-12">
            <?php echo $this->formlabel($fieldset->get("pieces_justificatives")->get('diplomes_releves_notes_traduits')) ?>
        </div>
        <div class="col-lg-9 col-sm-12">
            <div class="row detail_file">
                <div class="col-lg-1 upload_file">
                    <i class="icon icon-upload"></i>
                    <?php echo $this->formfile($fieldset->get("pieces_justificatives")->get('diplomes_releves_notes_traduits')) ?>
                </div>
                <div class="col-lg-2 date_televersement">
                    <p>Téléversé le 23/09/2023</p>
                </div>
                <div class="col-lg-1 action_file">
                    <span class="icon icon-voir iconly" title="Voir le fichier"></span>
                    <span class="icon icon-delete iconly text-danger" title="Supprimer le fichier"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-3 col-sm-12">
            <?php echo $this->formlabel($fieldset->get("pieces_justificatives")->get('acte_naissance')) ?>
        </div>
        <div class="col-lg-9 col-sm-12">
            <div class="row detail_file">
                <div class="col-lg-1 upload_file">
                    <i class="icon icon-upload"></i>
                    <?php echo $this->formfile($fieldset->get("pieces_justificatives")->get('acte_naissance')) ?>
                </div>
                <div class="col-lg-2 date_televersement">
                    <p>Téléversé le 24/09/2023</p>
                </div>
                <div class="col-lg-1 action_file">
                    <span class="icon icon-voir iconly" title="Voir le fichier"></span>
                    <span class="icon icon-delete iconly text-danger" title="Supprimer le fichier"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-3 col-sm-12">
            <?php echo $this->formlabel($fieldset->get("pieces_justificatives")->get('photocopie_passeport')) ?>
        </div>
        <div class="col-lg-9 col-sm-12">
            <div class="row detail_file">
                <div class="col-lg-1 upload_file">
                    <i class="icon icon-upload"></i>
                    <?php echo $this->formfile($fieldset->get("pieces_justificatives")->get('photocopie_passeport')) ?>
                </div>
                <div class="col-lg-2 date_televersement">
                </div>
                <div class="col-lg-1 action_file">
                    <span class="icon icon-voir iconly" title="Voir le fichier"></span>
                    <span class="icon icon-delete iconly text-danger" title="Supprimer le fichier"></span>
                </div>
            </div>
        </div>
    </div>

    <div class="row subfield">
        <div class="col informations-pieces_justificatives">
            <p>Si l'étudiant est titulaire d'un diplôme français ne conférant pas le grade de master</p>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-3 col-sm-12">
            <?php echo $this->formlabel($fieldset->get("pieces_justificatives")->get('diplomes_travaux_experience_pro')) ?>
        </div>
        <div class="col-lg-9 col-sm-12">
            <div class="row detail_file">
                <div class="col-lg-1 upload_file">
                    <i class="icon icon-upload"></i>
                    <?php echo $this->formfile($fieldset->get("pieces_justificatives")->get('diplomes_travaux_experience_pro')) ?>
                </div>
                <div class="col-lg-2 date_televersement">
                    <p>Téléversé le 25/09/2023</p>
                </div>
                <div class="col-lg-1 action_file">
                    <span class="icon icon-voir iconly" title="Voir le fichier"></span>
                    <span class="icon icon-delete iconly text-danger" title="Supprimer le fichier"></span>
                </div>
            </div>
        </div>
    </div>

    <div class="row subfield">
        <div class="col informations-pieces_justificatives">
            <p>Si spécificité(s) demandé(s)</p>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-3 col-sm-12">
            <?php echo $this->formlabel($fieldset->get("pieces_justificatives")->get('documents_demande_confidentialite')) ?>
        </div>
        <div class="col-lg-9 col-sm-12">
            <div class="row detail_file">
                <div class="col-lg-1 upload_file">
                    <i class="icon icon-upload"></i>
                    <?php echo $this->formfile($fieldset->get("pieces_justificatives")->get('documents_demande_confidentialite')) ?>
                </div>
                <div class="col-lg-2 date_televersement">
                    <p>Téléversé le 25/09/2023</p>
                </div>
                <div class="col-lg-1 action_file">
                    <span class="icon icon-voir iconly" title="Voir le fichier"></span>
                    <span class="icon icon-delete iconly text-danger" title="Supprimer le fichier"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-3 col-sm-12">
            <?php echo $this->formlabel($fieldset->get("pieces_justificatives")->get('documents_cotutelle')) ?>
        </div>
        <div class="col-lg-9 col-sm-12">
            <div class="row detail_file">
                <div class="col-lg-1 upload_file">
                    <i class="icon icon-upload"></i>
                    <?php echo $this->formfile($fieldset->get("pieces_justificatives")->get('documents_cotutelle')) ?>
                </div>
                <div class="col-lg-2 date_televersement">
                </div>
                <div class="col-lg-1 action_file">
                    <span class="icon icon-voir iconly" title="Voir le fichier"></span>
                    <span class="icon icon-delete iconly text-danger" title="Supprimer le fichier"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-3 col-sm-12">
            <?php echo $this->formlabel($fieldset->get("pieces_justificatives")->get('documents_coencadrement')) ?>
        </div>
        <div class="col-lg-9 col-sm-12">
            <div class="row detail_file">
                <div class="col-lg-1 upload_file">
                    <i class="icon icon-upload"></i>
                    <?php echo $this->formfile($fieldset->get("pieces_justificatives")->get('documents_coencadrement')) ?>
                </div>
                <div class="col-lg-2 date_televersement">
                    <p>Téléversé le 25/09/2023</p>
                </div>
                <div class="col-lg-1 action_file">
                    <span class="icon icon-voir iconly" title="Voir le fichier"></span>
                    <span class="icon icon-delete iconly text-danger" title="Supprimer le fichier"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="row boutons_gestionnaires">
        <div class="col">
            <a title="Modifier ces éléments" href="<?= $this->url('admission', ['action' => 'addInformationsEtudiantAction']) ?>" class="btn btn-warning bouton_gestionnaire">Modifier</a>
            <a title="Cette partie du formulaire est incomplète" href="<?= $this->url('admission', ['action' => 'addInformationsEtudiantAction']) ?>" class="btn btn-danger bouton_gestionnaire">Incomplet</a>
            <a title="Cette partie du formulaire est complète" href="<?= $this->url('admission', ['action' => 'addInformationsEtudiantAction']) ?>" class="btn btn-success bouton_gestionnaire">Complet</a>
        </div>
    </div>
</div>

<div class="row_sous_partie">
    <div class="title_sous_partie">
        <h2 class="titre_sous_partie">Signatures</h2>
    </div>
    <div class="row">
        <div class="col-lg-6 col-sm-12">
            <div class="row subfield">
                <div class="col etape_signature">
                    <div class="circle"><p>1</p></div>
                    <?php echo $this->formlabel($fieldset->get("circuit_signature")->get('validation_gestionnaires')) ?>
                </div>
            </div>
            <div class="row subfield">
                <div class="col etape_signature">
                    <div class="circle"><p>2</p></div>
                    <?php echo $this->formlabel($fieldset->get("circuit_signature")->get('validation_directeurthese')) ?>
                </div>
            </div>
            <div class="row subfield">
                <div class="col etape_signature">
                    <div class="circle"><p>3</p></div>
                    <?php echo $this->formlabel($fieldset->get("circuit_signature")->get('validation_codirecteur')) ?>
                </div>
            </div>
            <div class="row subfield">
                <div class="col etape_signature">
                    <div class="circle"><p>4</p></div>
                    <?php echo $this->formlabel($fieldset->get("circuit_signature")->get('validation_uniterecherche')) ?>
                </div>
            </div>
            <div class="row subfield">
                <div class="col etape_signature">
                    <div class="circle"><p>5</p></div>
                    <?php echo $this->formlabel($fieldset->get("circuit_signature")->get('validation_ecoledoctorale')) ?>
                </div>
            </div>
            <div class="row subfield">
                <div class="col etape_signature">
                    <div class="circle"><p>6</p></div>
                    <?php echo $this->formlabel($fieldset->get("circuit_signature")->get('signature_president')) ?>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-sm-12 cards_validation">
            <div class="card border-success mb-3 dossier_complet">
                <div class="card-body text-success">
                    <i class="icon icon-information"></i>
                    <p class="card-title">Votre dossier est complet</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row boutons_gestionnaires">
        <div class="col">
            <a title="Cette partie du formulaire est incomplète" href="<?= $this->url('admission', ['action' => 'addInformationsEtudiantAction']) ?>" class="btn btn-danger bouton_gestionnaire">Incomplet</a>
            <a title="Cette partie du formulaire est complète" href="<?= $this->url('admission', ['action' => 'addInformationsEtudiantAction']) ?>" class="btn btn-success bouton_gestionnaire">Complet</a>
        </div>
    </div>
</div>