<?php

use Admission\Form\Fieldset\Validation\ValidationFieldset;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer         $this
 * @var ValidationFieldset    $fieldset
 * @var string              $error
 * @var array               $dataForm
 *
 */
$fcg = $this->formControlGroup();
?>
<div class="row_sous_partie">
    <div class="title_sous_partie">
        <h2 class="titre_sous_partie">Pièces justificatives</h2>
    </div>
    <div class="row subfield">
        <div class="col informations-pieces_justificatives">
            <p>Obligatoires</p>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-3 col-sm-12">
            <?php echo $this->formlabel($fieldset->get('diplomeBac')) ?>
        </div>
        <div class="col-lg-9 col-sm-12">
            <div class="row detail_file">
                <div class="col-lg-1 upload_file">
                    <i class="icon icon-upload"></i>
                    <?php echo $this->formfile($fieldset->get('diplomeBac')) ?>
                </div>
                <div class="col-lg-2 date_televersement">
                    <p>Téléversé le 25/09/2023</p>
                </div>
                <div class="col-lg-1 action_file">
                    <span class="icon icon-voir iconly" title="Voir le fichier"></span>
                    <span class="icon icon-delete iconly text-danger" title="Supprimer le fichier"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-3 col-sm-12">
            <?php echo $this->formlabel($fieldset->get('curicculumVitae')) ?>
        </div>
        <div class="col-lg-9 col-sm-12">
            <div class="row detail_file">
                <div class="col-lg-1 upload_file">
                    <i class="icon icon-upload"></i>
                    <?php echo $this->formfile($fieldset->get('curicculumVitae')) ?>
                </div>
                <div class="col-lg-2 date_televersement">
                </div>
                <div class="col-lg-1 action_file">
                    <span class="icon icon-voir iconly" title="Voir le fichier"></span>
                    <span class="icon icon-delete iconly text-danger" title="Supprimer le fichier"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-3 col-sm-12">
            <?php echo $this->formlabel($fieldset->get('financement')) ?>
        </div>
        <div class="col-lg-9 col-sm-12">
            <div class="row detail_file">
                <div class="col-lg-1 upload_file">
                    <i class="icon icon-upload"></i>
                    <?php echo $this->formfile($fieldset->get('financement')) ?>
                </div>
                <div class="col-lg-2 date_televersement">
                    <p>Téléversé le 25/09/2023</p>
                </div>
                <div class="col-lg-1 action_file">
                    <span class="icon icon-voir iconly" title="Voir le fichier"></span>
                    <span class="icon icon-delete iconly text-danger" title="Supprimer le fichier"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-3 col-sm-12">
            <?php echo $this->formlabel($fieldset->get('projetThese')) ?>
        </div>
        <div class="col-lg-9 col-sm-12">
            <div class="row detail_file">
                <div class="col-lg-1 upload_file">
                    <i class="icon icon-upload"></i>
                    <?php echo $this->formfile($fieldset->get('projetThese')) ?>
                </div>
                <div class="col-lg-2 date_televersement">
                </div>
                <div class="col-lg-1 action_file">
                    <span class="icon icon-voir iconly" title="Voir le fichier"></span>
                    <span class="icon icon-delete iconly text-danger" title="Supprimer le fichier"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-3 col-sm-12">
            <?php echo $this->formlabel($fieldset->get('exemplairesConvention')) ?>
        </div>
        <div class="col-lg-9 col-sm-12">
            <div class="row detail_file">
                <div class="col-lg-1 upload_file">
                    <i class="icon icon-upload"></i>
                    <?php echo $this->formfile($fieldset->get('exemplairesConvention')) ?>
                </div>
                <div class="col-lg-2 date_televersement">
                    <p>Téléversé le 24/09/2023</p>
                </div>
                <div class="col-lg-1 action_file">
                    <span class="icon icon-voir iconly" title="Voir le fichier"></span>
                    <span class="icon icon-delete iconly text-danger" title="Supprimer le fichier"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="row subfield">
        <div class="col-lg-3 col-sm-12">
            <?php echo $this->formlabel($fieldset->get('exemplairesCharteDoctorat')) ?>
        </div>
        <div class="col-lg-9 col-sm-12">
            <div class="row detail_file">
                <div class="col-lg-1 upload_file">
                    <i class="icon icon-upload"></i>
                    <?php echo $this->formfile($fieldset->get('exemplairesCharteDoctorat')) ?>
                </div>
                <div class="col-lg-2 date_televersement">
                    <p>Téléversé le 25/09/2023</p>
                </div>
                <div class="col-lg-1 action_file">
                    <span class="icon icon-voir iconly" title="Voir le fichier"></span>
                    <span class="icon icon-delete iconly text-danger" title="Supprimer le fichier"></span>
                </div>
            </div>
        </div>
    </div>
    <?php if (isset($dataForm['etudiant']['diplomeEtudiant']['niveauEtude']) && $dataForm['etudiant']['diplomeEtudiant']['niveauEtude'] == 2) { ?>
        <div class="row subfield">
            <div class="col informations-piecesJustificatives">
                <p>Vous avez un autre diplôme qu'un master français (Dérogation)</p>
            </div>
        </div>
        <div class="row subfield">
            <div class="col-lg-3 col-sm-12">
                <?php echo $this->formlabel($fieldset->get('argumentaireDirecteurThese')) ?>
            </div>
            <div class="col-lg-9 col-sm-12">
                <?php echo $this->formtextarea($fieldset->get('argumentaireDirecteurThese')) ?>
            </div>
        </div>
    <?php } ?>
    <?php if (isset($dataForm['etudiant']['diplomeEtudiant']['niveauEtude']) && $dataForm['etudiant']['diplomeEtudiant']['niveauEtude'] == 2 && $dataForm['etudiant']['diplomeEtudiant']['typeDiplomeAutre'] == 1) { ?>
        <div class="row subfield">
            <div class="col informations-piecesJustificatives">
                <p>Vous êtes titulaire d'un titre étranger</p>
            </div>
        </div>
        <div class="row subfield">
            <div class="col-lg-3 col-sm-12">
                <?php echo $this->formlabel($fieldset->get('diplomesRelevesNotesTraduits')) ?>
            </div>
            <div class="col-lg-9 col-sm-12">
                <div class="row detail_file">
                    <div class="col-lg-1 upload_file">
                        <i class="icon icon-upload"></i>
                        <?php echo $this->formfile($fieldset->get('diplomesRelevesNotesTraduits')) ?>
                    </div>
                    <div class="col-lg-2 date_televersement">
                        <p>Téléversé le 23/09/2023</p>
                    </div>
                    <div class="col-lg-1 action_file">
                        <span class="icon icon-voir iconly" title="Voir le fichier"></span>
                        <span class="icon icon-delete iconly text-danger" title="Supprimer le fichier"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="row subfield">
            <div class="col-lg-3 col-sm-12">
                <?php echo $this->formlabel($fieldset->get('acteNaissance')) ?>
            </div>
            <div class="col-lg-9 col-sm-12">
                <div class="row detail_file">
                    <div class="col-lg-1 upload_file">
                        <i class="icon icon-upload"></i>
                        <?php echo $this->formfile($fieldset->get('acteNaissance')) ?>
                    </div>
                    <div class="col-lg-2 date_televersement">
                        <p>Téléversé le 24/09/2023</p>
                    </div>
                    <div class="col-lg-1 action_file">
                        <span class="icon icon-voir iconly" title="Voir le fichier"></span>
                        <span class="icon icon-delete iconly text-danger" title="Supprimer le fichier"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="row subfield">
            <div class="col-lg-3 col-sm-12">
                <?php echo $this->formlabel($fieldset->get('photocopiePasseport')) ?>
            </div>
            <div class="col-lg-9 col-sm-12">
                <div class="row detail_file">
                    <div class="col-lg-1 upload_file">
                        <i class="icon icon-upload"></i>
                        <?php echo $this->formfile($fieldset->get('photocopiePasseport')) ?>
                    </div>
                    <div class="col-lg-2 date_televersement">
                    </div>
                    <div class="col-lg-1 action_file">
                        <span class="icon icon-voir iconly" title="Voir le fichier"></span>
                        <span class="icon icon-delete iconly text-danger" title="Supprimer le fichier"></span>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
    <?php if (isset($dataForm['etudiant']['diplomeEtudiant']['niveauEtude']) && $dataForm['etudiant']['diplomeEtudiant']['niveauEtude'] == 2 && $dataForm['etudiant']['diplomeEtudiant']['typeDiplomeAutre'] == 2) { ?>
        <div class="row subfield">
            <div class="col informations-piecesJustificatives">
                <p>Vous êtes titulaire d'un diplôme français ne conférant pas le grade de master</p>
            </div>
        </div>
        <div class="row subfield">
            <div class="col-lg-3 col-sm-12">
                <?php echo $this->formlabel($fieldset->get('diplomesTravauxExperiencePro')) ?>
            </div>
            <div class="col-lg-9 col-sm-12">
                <div class="row detail_file">
                    <div class="col-lg-1 upload_file">
                        <i class="icon icon-upload"></i>
                        <?php echo $this->formfile($fieldset->get('diplomesTravauxExperiencePro')) ?>
                    </div>
                    <div class="col-lg-2 date_televersement">
                        <p>Téléversé le 25/09/2023</p>
                    </div>
                    <div class="col-lg-1 action_file">
                        <span class="icon icon-voir iconly" title="Voir le fichier"></span>
                        <span class="icon icon-delete iconly text-danger" title="Supprimer le fichier"></span>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
    <?php if (isset($dataForm['inscription']['specifitesEnvisagees']['confidentialite']) || isset($dataForm['inscription']['specifitesEnvisagees']['coTutelle']) || isset($dataForm['inscription']['specifitesEnvisagees']['coEncadrement']) || isset($dataForm['inscription']['specifitesEnvisagees']['co-direction'])) { ?>
        <div class="row subfield">
            <div class="col informations-piecesJustificatives">
                <p>Spécificité(s) demandée(s)</p>
            </div>
        </div>
        <?php if (isset($dataForm['inscription']['specifitesEnvisagees']['confidentialite']) && $dataForm['inscription']['specifitesEnvisagees']['confidentialite'] == 1) { ?>
            <div class="row subfield">
                <div class="col-lg-3 col-sm-12">
                    <?php echo $this->formlabel($fieldset->get('documentsDemandeConfidentialite')) ?>
                </div>
            </div>
        <?php } ?>
        <?php if (isset($dataForm['inscription']['specifitesEnvisagees']['coTutelle']) && $dataForm['inscription']['specifitesEnvisagees']['coTutelle'] == 1) { ?>
            <div class="row subfield">
                <div class="col-lg-3 col-sm-12">
                    <?php echo $this->formlabel($fieldset->get('documentsCotutelle')) ?>
                </div>
                <div class="col-lg-9 col-sm-12">
                    <div class="row detail_file">
                        <div class="col-lg-1 upload_file">
                            <i class="icon icon-upload"></i>
                            <?php echo $this->formfile($fieldset->get('documentsCotutelle')) ?>
                        </div>
                        <div class="col-lg-2 date_televersement">
                        </div>
                        <div class="col-lg-1 action_file">
                            <span class="icon icon-voir iconly" title="Voir le fichier"></span>
                            <span class="icon icon-delete iconly text-danger" title="Supprimer le fichier"></span>
                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>
        <?php if (isset($dataForm['inscription']['specifitesEnvisagees']['coEncadrement']) && $dataForm['inscription']['specifitesEnvisagees']['coEncadrement'] == 1) { ?>
            <div class="row subfield">
                <div class="col-lg-3 col-sm-12">
                    <?php echo $this->formlabel($fieldset->get('documentsCoencadrement')) ?>
                </div>
                <div class="col-lg-9 col-sm-12">
                    <div class="row detail_file">
                        <div class="col-lg-1 upload_file">
                            <i class="icon icon-upload"></i>
                            <?php echo $this->formfile($fieldset->get('documentsCoencadrement')) ?>
                        </div>
                        <div class="col-lg-2 date_televersement">
                            <p>Téléversé le 25/09/2023</p>
                        </div>
                        <div class="col-lg-1 action_file">
                            <span class="icon icon-voir iconly" title="Voir le fichier"></span>
                            <span class="icon icon-delete iconly text-danger" title="Supprimer le fichier"></span>
                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>
    <?php } ?>
    <div class="row boutons_gestionnaires">
        <div class="col">
            <a title="Modifier ces éléments" href="<?= $this->url('admission', ['action' => 'addInformationsEtudiantAction']) ?>" class="btn btn-warning bouton_gestionnaire">Modifier</a>
            <a title="Cette partie du formulaire est incomplète" href="<?= $this->url('admission', ['action' => 'addInformationsEtudiantAction']) ?>" class="btn btn-danger bouton_gestionnaire">Incomplet</a>
            <a title="Cette partie du formulaire est complète" href="<?= $this->url('admission', ['action' => 'addInformationsEtudiantAction']) ?>" class="btn btn-success bouton_gestionnaire">Complet</a>
        </div>
    </div>
</div>

<div class="row_sous_partie">
    <div class="title_sous_partie">
        <h2 class="titre_sous_partie">Signatures</h2>
    </div>
    <div class="attestation_honneur">
        <div class="row subfield texte_validation_attestation_honneur">
            <p>A la validation, mon dossier sera soumis au visa du directeur de thèse, du co-directeur (le cas échéant), du directeur de l'unité de recherche, du directeur de l'école doctorale et du Président de l'université</p>
        </div>
        <div class="row subfield validation_attestation">
            <div class="col-lg-4">
                <?php echo $fcg($fieldset->get('attestationHonneurInformations')) ?>
            </div>
            <div class="col-lg-4 bouton_validation">
                <?php echo $fcg($fieldset->get('saveAttestationHonneur')) ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 col-sm-12">
            <div class="row subfield">
                <div class="col etape_signature">
                    <span class="icon icon-checked circle_success"></span>
                    <?php echo $this->formlabel($fieldset->get('validationGestionnaires')) ?>
                </div>
            </div>
            <div class="row subfield">
                <div class="col etape_signature">
                    <span class="icon icon-unchecked circle_incomplete"></span>
                    <?php echo $this->formlabel($fieldset->get('validationDirecteurthese')) ?>
                </div>
            </div>
            <div class="row subfield">
                <div class="col etape_signature">
                    <div class="circle"><p>3</p></div>
                    <?php echo $this->formlabel($fieldset->get('validationCodirecteur')) ?>
                </div>
            </div>
            <div class="row subfield">
                <div class="col etape_signature">
                    <div class="circle"><p>4</p></div>
                    <?php echo $this->formlabel($fieldset->get('validationUniterecherche')) ?>
                </div>
            </div>
            <div class="row subfield">
                <div class="col etape_signature">
                    <div class="circle"><p>5</p></div>
                    <?php echo $this->formlabel($fieldset->get('validationEcoledoctorale')) ?>
                </div>
            </div>
            <div class="row subfield">
                <div class="col etape_signature">
                    <div class="circle"><p>6</p></div>
                    <?php echo $this->formlabel($fieldset->get('signaturePresident')) ?>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-sm-12 cardsValidation">
            <div class="card border-success mb-3 dossier_complet">
                <div class="card-body text-success">
                    <i class="icon icon-information"></i>
                    <p class="card-title">Votre dossier est complet</p>
                </div>
            </div>
            <div class="card mb-3 dossier_incomplet">
                <div class="card-body text-warning">
                    <i class="icon icon-information"></i>
                    <p class="card-title">En attente de la validation du directeur de thèse</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row boutons_gestionnaires">
        <div class="col">
            <a title="Cette partie du formulaire est incomplète" href="<?= $this->url('admission', ['action' => 'addInformationsEtudiantAction']) ?>" class="btn btn-danger bouton_gestionnaire">Incomplet</a>
            <a title="Cette partie du formulaire est complète" href="<?= $this->url('admission', ['action' => 'addInformationsEtudiantAction']) ?>" class="btn btn-success bouton_gestionnaire">Complet</a>
        </div>
    </div>
</div>