<?php
/**
 * @var These              $these
 * @var DiffusionTheseForm $form
 * @var boolean            $masquerFichiers
 * @var array              $theseFichiersExpurgesItems
 * @var array              $annexesFichiersExpurgesItems
 */

use Application\Entity\Db\Diffusion;
use Application\Entity\Db\These;
use Application\Form\DiffusionTheseForm;
use Application\Service\Message\DiffusionMessages;

$diffusion = $these->getDiffusion();
?>

<?php if ($diffusion->getConfidentielle()): ?>
<div class="row">
    <div class="col-xs-6">
        <div class="alert alert-md alert-danger">
            <?php echo sprintf("La thèse est confidentielle jusqu'au %s.", $diffusion->getDateFinConfidentialiteToString()) ?>
        </div>
    </div>
</div>
<?php endif ?>

<ul class="autorisation-diffusion">
    <li><?php echo $this->message()->render('DROITS_AUTEUR_OK_PHRASE', [], $diffusion) ?></li>

    <?php if (empty($masquerFichiers) && ! $these->getDiffusion()->getDroitAuteurOk()): ?>
        <li>Version expurgée pour la diffusion :
        <?php echo $this->partial('application/fichier-these/lister-fichiers', ['items' => $theseFichiersExpurgesItems]) ?></li>
        <li>Autres formats de fichiers expurgés, le cas échéant :
        <?php echo $this->partial('application/fichier-these/lister-fichiers', ['items' => $annexesFichiersExpurgesItems]) ?></li>
    <?php endif ?>

    <li><?php echo $form->get('certifCharteDiff')->getLabel() . "." ?>

    <li>
        <?php echo $this->message()->render(DiffusionMessages::AUTORIS_MISE_EN_LIGNE_PHRASE, [], $diffusion) ?>
        <div class="autorisation-laius text-info">
            <?php echo $this->message()->render(DiffusionMessages::AUTORIS_MISE_EN_LIGNE_LAIUS, [], $diffusion) ?>
        </div>
    </li>

    <?php if ($idOrcid = $diffusion->getOrcid()): ?>
        <li>Identifiant ORCID : <code class="text-muted"><?php echo $idOrcid ?></code></li>
    <?php endif ?>
</ul>