<?php

use Application\Entity\Db\These;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var string      $text
 */

/**
 * @param string $paramName
 * @param string $paramValue
 * @param array $queryParams
 * @return string
 */
$urlFiltrer = function ($paramName, $paramValue, $queryParams) {
    $queryParams[$paramName] = $paramValue;
    return $this->url('these/rechercher', [], ['query' => $queryParams], true);
};
?>

<?php echo $this->filterPanel([
    $this->translate("État") => [
        'paramName' => 'etatThese',
        'paramConfig' => [
            ['value' => '',                             'label' => $this->translate("Tous") ],
            ['value' => $v = These::ETAT_EN_COURS,      'label' => $this->translate(These::$etatsLibelles[$v]) ],
            ['value' => $v = These::ETAT_ABANDONNEE,    'label' => $this->translate(These::$etatsLibelles[$v]) ],
            ['value' => $v = These::ETAT_SOUTENUE,      'label' => $this->translate(These::$etatsLibelles[$v]) ],
            ['value' => $v = These::ETAT_TRANSFEREE,    'label' => $this->translate(These::$etatsLibelles[$v]) ],
        ],
        'filterUrl' => $urlFiltrer,
    ],
//    "Résultat" => [
//        'paramName' => 'resultat',
//        'paramConfig' => [
//            ['value' => '', 'label' => "Tous"],
//            ['value' => $v = (string) These::RESULTAT_ADMIS, 'label' => These::$resultatsLibellesCourts[$v]],
//            ['value' => $v = (string) These::RESULTAT_AJOURNE, 'label' => These::$resultatsLibellesCourts[$v]],
//            ['value' => $v = These::ETAT_SOUTENUE, 'label' => These::$etatsLibelles[$v]],
//        ],
//        'filterUrl' => $urlFiltrer,
//    ],
]) ?>


