<?php

use Application\Entity\Db\These;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var string      $text
 */

/**
 * @param string $paramName
 * @param string $paramValue
 * @param array $queryParams
 * @return string
 */
$urlFiltrer = function ($paramName, $paramValue, $queryParams) {
    $queryParams[$paramName] = $paramValue;
    return $this->url('these/rechercher', [], ['query' => $queryParams], true);
};

echo $this->filterPanel([
    $this->translate("État") => [
        'paramName' => 'etatThese',
        'paramConfig' => [
            ['value' => '',                             'label' => $this->translate("Tous") ],
            ['value' => $v = These::ETAT_EN_COURS,      'label' => $this->translate(These::$etatsLibelles[$v]) ],
            ['value' => $v = These::ETAT_ABANDONNEE,    'label' => $this->translate(These::$etatsLibelles[$v]) ],
            ['value' => $v = These::ETAT_SOUTENUE,      'label' => $this->translate(These::$etatsLibelles[$v]) ],
            ['value' => $v = These::ETAT_TRANSFEREE,    'label' => $this->translate(These::$etatsLibelles[$v]) ],
        ],
        'filterUrl' => $urlFiltrer,
    ],

    $this->translate("Établissement") => [
        'paramName' => 'etablissement',
        'paramConfig' => [
            ['value' => '',                             'label' => $this->translate("Tous") ],
            ['value' => $v = 'INSA',                    'label' => $this->translate("INSA Rouen") ],
            ['value' => $v = 'UCN',                     'label' => $this->translate("UniCaen") ],
            ['value' => $v = 'ULHN',                    'label' => $this->translate("Univ-LeHavre") ],
            ['value' => $v = 'URN',                     'label' => $this->translate("Univ-Rouen") ],
        ],
        'filterUrl' => $urlFiltrer,
    ],
]) ?>


