<?php
/**
 * @var These $these
 */

use Application\Entity\Db\These;
?>

<div class="panel panel-info these-panel">
    <?php if ($this->header): ?>
    <div class="panel-heading">
        <?php echo $this->header ?>
    </div>
    <?php endif ?>
    <div class="panel-body">
        <h3><?php echo $these->getTitre() ?></h3>
        <ul class="roadmap pagination">
            <li>
                <?php $url = $this->url('these/identite', ['these' => $these->getId()]) ?>
                <a class="roadmap-step-link " href="<?php echo $url ?>"><span class="glyphicon glyphicon-circle-arrow-right"></span>Détails...</a>
            </li>
        </ul>
    </div>
</div>
