<?php
/**
 * @var These $these
 * @var bool $useTitreThese
 */

use Application\Entity\Db\These;
use Application\Filter\TitreFormatter;
use UnicaenApp\Util;

$class = $these->estConfidentielle() ? 'text-danger' : '';

$titreFormatter = new TitreFormatter();
$titre = $titreFormatter->doFormat($these);
?>

<?php if (isset($useTitreThese) && $useTitreThese): ?>
    <span class="<?php echo $class ?>"
          title="<?php echo $titre ?>">
        <?php echo trim($titre) ? Util::truncatedString($titre, 40) : "(Aucun titre)" ?></span>
<?php else: ?>
    <span class="<?php echo $class ?>"><?php echo $these->getDoctorant()->getNomComplet() ?></span>
<?php endif ?>

<?php if ($these->estConfidentielle()): ?>
    <?php $content = sprintf('<span class="text-danger">Confidentielle jusqu\'au %s</span>', $these->getDateFinConfidentialiteToString()) ?>
    <span class="text-danger"
       data-toggle="popover"
       data-content="<?php echo htmlspecialchars($content) ?>"
       data-trigger="hover"
       data-html="true"
       data-placement="bottom"><span class="label label-danger">CONFIDENTIELLE</span></span>
<?php endif ?>

<a title="Thèse"
   data-toggle="popover"
   data-content="<?php echo htmlspecialchars($this->partial('application/these/partial/fiche')) ?>"
   data-trigger="click"
   data-placement="bottom"
   data-container="body"
   data-html="true"
   tabindex="0"
   role="button"><span class="glyphicon glyphicon-list-alt"></span>
</a>