<?php
/**
 * @var These $these
 * @var bool $useTitreThese
 * @var int $length
 * @var boolean $description
 */

if (! isset($length)) $length = 40;

use Application\Entity\Db\These;
use UnicaenApp\Util;

$class = $these->estConfidentielle() ? 'text-danger' : '';
?>

<?php if (isset($useTitreThese) && $useTitreThese): ?>
    <span class="<?php echo $class ?>"
          title="<?php echo $titre = $these->getTitre() ?>"><?php echo trim($titre) ? Util::truncatedString($titre, $length) : "(Aucun titre)" ?></span>
<?php else: ?>
    <span class="<?php echo $class ?>"><?php echo $these->getDoctorant()->getNomComplet() ?></span>
<?php endif ?>

<?php if ($these->estConfidentielle()): ?>
    <?php $content = sprintf('<span class="text-danger">Confidentielle jusqu\'au %s</span>', $these->getDateFinConfidentialiteToString()) ?>
    <span class="text-danger"
       data-toggle="popover"
       data-content="<?php echo htmlspecialchars($content) ?>"
       data-trigger="hover"
       data-html="true"
       data-placement="bottom"><span class="badge bg-danger">CONFIDENTIELLE</span></span>
<?php endif ?>

<?php if ($description !== false) : ?>
    <a title="Thèse"
       data-toggle="popover"
       data-content="<?php echo htmlspecialchars($this->partial('application/these/partial/fiche')) ?>"
       data-trigger="click"
       data-placement="bottom"
       data-html="true"
       role="button"><span class="fas fa-list-alt"></span>
    </a>
<?php endif; ?>