<?php

use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 *
 * @see \Admission\Controller\AdmissionController::etudiantAction()
 */
?>

<?php $this->headTitle($this->translate($title = "Admission")) ?>

<h1 class="page-header"><?php echo $this->translate($title); ?> </h1>

<p class="introduction">Cette application permet dans un premier temps de candidater à un parcours doctoral à
    l'université de Caen Normandie. <br>Vous devrez remplir un formulaire en ligne et déposer les documents demandés.<br>
    Les informations que vous entrez dans ce formulaire sont automatiquement sauvegardées dès lors que vous passez à l'étape suivante, ou revenez à l'étape précédente.
</p>

<?php
$multipageFormFieldset = $this->multipageFormFieldset();
$multipageFormFieldset->setPartial('admission/partial/etudiantInfos');
echo $multipageFormFieldset;
?>
