<?php

use Admission\Entity\Db\Admission;
use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var Admission $admission
 *
 * @see \Admission\Controller\AdmissionController::inscriptionAction()
 */
?>

<?php echo $this->partial('admission/admission/partial/header', ['admission' => $admission]); ?>

<?= $this->messenger()->addCurrentMessagesFromFlashMessengerWithNoNamespace() ?>

<?php
$multipageFormFieldset = $this->multipageFormFieldset();
$multipageFormFieldset->setPartial('admission/partial/inscriptionInfos'); ?>
<div class="admission">
    <?php echo $multipageFormFieldset; ?>
</div>
