<?php

use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 *
 * @see \Admission\Controller\AdmissionController::financementAction()
 */
?>

<?php $this->headTitle($this->translate($title = "Admission")) ?>

<h1 class="page-header"><?php echo $this->translate($title); ?> </h1>

<p class="introduction">Cette application permet dans un premier temps de candidater à un parcours doctoral à
    l'université de Caen Normandie. <br>Vous devrez remplir un formulaire en ligne et déposer les documents demandés.
</p>

<?php
$multipageFormFieldset = $this->multipageFormFieldset();
$multipageFormFieldset->setPartial('admission/partial/financementInfos');
echo $multipageFormFieldset;
?>
