<?php

use Application\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 *
 * @see \Admission\Controller\AdmissionController::etudiantAction()
 */
?>

<?php echo $this->partial('admission/admission/partial/header', []); ?>

<?= $this->messenger()->addCurrentMessagesFromFlashMessengerWithNoNamespace() ?>

<?php
$multipageFormFieldset = $this->multipageFormFieldset();
$multipageFormFieldset->setPartial('admission/partial/etudiantInfos'); ?>
<div class="admission">
    <?php echo $multipageFormFieldset; ?>
</div>

