<?php

use Admission\Entity\Db\Admission;
use Admission\Entity\Db\AdmissionOperationInterface;
use Admission\Entity\Db\TypeValidation;
use Individu\Entity\Db\Individu;

/**
 *  @var array $operations
 * * @var Individu $individu
 * * @var string $returnUrl
 * * @var AdmissionOperationInterface $operationEnAttente
 * * @var Admission $admission
 * * @var boolean $showActionButtons
 * * @var boolean $isOperationAllowedByRole
 */
echo $this->partial('admission/admission/partial/circuit-signatures', [
    'operations' => $operations,
    'individu' => $admission->getIndividu(),
    'returnUrl' => "",
    'operationEnAttente' => $operationEnAttente,
    'admission' => $admission,
    'showActionButtons' => $showActionButtons,
    'isOperationAllowedByRole' => $isOperationAllowedByRole
]);