<?php

use Admission\Entity\Db\Admission;
use Admission\Entity\Db\AdmissionOperationInterface;
use Admission\Provider\Privilege\AdmissionPrivileges;
use Application\View\Renderer\PhpRenderer;
use Individu\Entity\Db\Individu;
use UnicaenApp\Form\Element\SearchAndSelect;

/**
 * @var PhpRenderer $this
 * @var Admission[] $admissions
 * @var Admission $admission
 * @var array $operations
 * @var Individu $individu
 * @var SearchAndSelect $inputIndividu
 * @var AdmissionOperationInterface $operationEnAttente
 *
 * @see \Admission\Controller\AdmissionController::indexAction()
 */
$canRechercherDossiersAdmission  = $this->isAllowed(AdmissionPrivileges::getResourceId(AdmissionPrivileges::ADMISSION_RECHERCHER_DOSSIERS_ADMISSION));
$canListerDossiersAdmission  = $this->isAllowed(AdmissionPrivileges::getResourceId(AdmissionPrivileges::ADMISSION_LISTER_MES_DOSSIERS_ADMISSION));
?>

<?php $this->headTitle($this->translate($title = "Admission")) ?>

<h1 class="page-header"><?php echo $this->translate($title); ?> </h1>

<p class="introduction">Cette application permet dans un premier temps de candidater à un parcours doctoral.
    <br>Vous devrez remplir un formulaire en ligne et déposer les documents demandés.<br>
</p>
<?= $this->messenger()->addCurrentMessagesFromFlashMessengerWithNoNamespace() ?>

<?php if($canRechercherDossiersAdmission) { ?>
    <div class="form_admission">
        <form action="<?php echo $this->url('admission', [], [], true); ?>" method="post">
            <div class="row individu_recherche_index">
                <div class="col-lg-4 col-sm-12 label_index">
                    <label for="individuId">Entrez l'individu recherché :</label>
                </div>
                <div class="col-lg-4 col-sm-12 input_index">
                    <?php echo $this->formControlGroup($inputIndividu); ?>
                </div>
                <div class="col-lg-3 col-sm-12 bouton_acces_dossier_index">
                    <button type="submit" class="btn btn-primary">Accéder à son dossier d'admission</button>
                </div>
            </div>
        </form>
    </div>
<?php }else if(!empty($operations)){ ?>
    <h2>Statut de votre dossier d'admission</h2>
    <?php
    $returnUrl = $this->url('admission', ['individu' => $individu]);
        echo $this->partial('admission/admission/partial/circuit-signatures', [
            'operations' => $operations,
            'individu' => $individu->getId(),
            'returnUrl' => $returnUrl,
            'admission' => $admission,
            'operationEnAttente' => $operationEnAttente,
            'showActionButtons' => true
        ]);
    } ?>

<?php if($canListerDossiersAdmission) { ?>
    <h2>Dossiers d'admissions en cours</h2>
    <table class="table table-sm">
        <thead>
        <tr>
            <th>Nom de l'étudiant</th>
            <th>Statut</th>
            <th>Titre provisoire de la thèse</th>
            <th>École Doctorale</th>
            <th>Unité de recherche</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <?php
        $countFilteredAdmissions=0;
        foreach ($admissions as $admission):
            $can = $this->isAllowed($admission, AdmissionPrivileges::ADMISSION_AFFICHER_SON_DOSSIER_ADMISSION_DANS_LISTE);
            if($can){
                $countFilteredAdmissions++; ?>
                <tr>
                    <td><?php echo $admission->getIndividu()->getNomUsuel()." ".$admission->getIndividu()->getPrenom(); ?></td>
                    <td><?php echo $admission->getEtat()->getLibelle() ?>
                        <a href="<?php echo $this->url('admission/generer-statut-dossier', ['action' => 'generer-statut-dossier','admission' => $admission->getId()], [], true) ?>"
                           title="Appuyer pour avoir plus de détails"
                           data-bs-toggle="tooltip" data-bs-html="true" class="info_statut_dossier action ajax-modal">
                            <span class="icon icon-information"></span>
                        </a>
                    </td>
                    <td><?php echo $admission->getInscription()->first() ? $admission->getInscription()->first()->getTitreThese() : ""; ?></td>
                    <td><?php if($admission->getInscription()->first() && $admission->getInscription()->first()->getEcoleDoctorale()){
                            echo $admission->getInscription()->first()->getEcoleDoctorale();
                        }else{
                            echo "<p class='structure_non_declaree'>Aucune ED déclarée</p>";
                        }?>
                    </td>
                    <td>
                        <?php if($admission->getInscription()->first() && $admission->getInscription()->first()->getUniteRecherche()){
                            echo $admission->getInscription()->first()->getUniteRecherche();
                        }else{
                            echo "<p class='structure_non_declaree'>Aucune UR déclarée</p>";
                        }?>
                    <td>
                        <a href="<?php echo $this->url('admission/ajouter', ['action' => 'etudiant','individu' => $admission->getIndividu()->getId()], [], true) ?>"
                           title="Accéder au dossier d'admission #<?php echo $admission->getId(); ?>"
                           data-bs-toggle="tooltip" data-bs-html="true">
                            <span class="icon icon-voir"></span>
                        </a>
                        <a href="<?php echo $this->url('admission/ajouter',['action' => 'supprimer', 'individu' => $admission->getIndividu()->getId()], [], true); ?>"
                           data-toggle="confirmationx" data-event="modification"
                           title="Suppression du dossier d'admission #<?php echo $admission->getId(); ?>" data-bs-toggle="tooltip" data-bs-html="true">
                            <span class="icon icon-historiser text-danger"></span>
                        </a>
                    </td>
                </tr>
            <?php } ?>
        <?php endforeach; ?>
        </tbody>
    </table>
    <p><?php echo $countFilteredAdmissions." dossier(s) d'admission(s) trouvé(s)";?></p>
<?php }else{ ?>
    <div class="row bouton_acces_dossier">
        <a href="<?php echo $this->url('admission/ajouter', ['action' => 'etudiant','individu' => $individu->getId()], [], true) ?>" class="btn btn-primary acces_dossier">Accéder à votre dossier d'admission</a>
    </div>
<?php } ?>