<?php
/**
 * @var PropositionHDR $proposition
 * @var string $FORMULAIRE_DEMANDE_ANGLAIS
 * @var string $FORMULAIRE_DEMANDE_CONFIDENTIALITE
 * @var bool $canModifier
 * @var string $typeProposition
 */

use Soutenance\Entity\PropositionHDR;
use Soutenance\Service\Horodatage\HorodatageService;


$hdr = $proposition->getHDR();
?>

<div id="BOXDIV_INFORMATIONS">
    <div class="box card">
        <div class="card-header bg-dark text-white">
            <h2>
                Informations sur l'HDR et la soutenance
            </h2>
        </div>
        <div class="row card-body">
            <!-- THESE EN ANGLAIS ----------------------------------------------------------------------------------------->
            <div class="col-md-8">
                <dl>
                    <dt>HDR en anglais</dt>
                    <?php if ($proposition->isSoutenanceAnglais()) : ?>
                        <dd>
                            Soutenance en anglais
                        </dd>
                    <?php else : ?>
                        <dd> Non</dd>
                    <?php endif; ?>
                </dl>
            </div>

            <div class="col-md-4">
                <?php if ($canModifier) : ?>
                    <a <?php /** @see \Soutenance\Controller\PropositionController::anglaisAction(); */ ?>
                            href="<?php echo $this->url("soutenance_{$typeProposition}/proposition/anglais", ['id' => $hdr->getId()], [], true); ?>"
                            class="btn btn-primary action ajax-modal"
                            data-event="edition-informations"
                    >
                        <span class="icon icon-plus"></span>
                        Renseigner HDR en anglais
                    </a>
                <?php endif; ?>

                <!--            --><?php //if($proposition->isManuscritAnglais() || $proposition->isSoutenanceAnglais()): ?>
                <!--                <div class="alert alert-warning">-->
                <!--                    <span class="icon icon-warning"> </span>-->
                <!--                    Afin de réaliser la demande de rédaction ou de soutenance en anglais vous devez motiver votre demande via la demande suivante :-->
                <!--                    <a href="-->
                <?php //echo $FORMULAIRE_DEMANDE_ANGLAIS; ?><!--">demande de redaction ou de soutenance en anglais</a>.-->
                <!--                </div>-->
                <!--            --><?php //endif; ?>
            </div>

            <div class="col-md-8">
                <dl>
                    <dt> Confidentialité de l'HDR</dt>
                    <?php if ($hdr->getDateFinConfidentialite() !== null): ?>
                        HDR confidentielle jusqu'au <?php echo $hdr->getDateFinConfidentialite()->format('d/m/Y'); ?>
                        <?php if ($proposition->isHuitClos()): ?>
                            <dd> Soutenance en huis clos</dd>
                        <?php endif; ?>
                    <?php else: ?>
                        <?php if ($proposition->getConfidentialite()): ?>
                            <dd> Date de fin de confidentialité
                                : <?php echo $proposition->getConfidentialite()->format("d/m/Y"); ?> </dd>
                            <?php if ($proposition->isHuitClos()): ?>
                                <dd> Soutenance en huis clos</dd>
                            <?php endif; ?>
                        <?php else : ?>
                            <dd> HDR non confidentielle</dd>
                        <?php endif; ?>
                    <?php endif; ?>
                </dl>
            </div>

            <div class="col-md-4">
                <?php if ($canModifier) : ?>
                    <a <?php /** @see \Soutenance\Controller\PropositionController::confidentialiteAction(); */ ?>
                            href="<?php echo $this->url("soutenance_{$typeProposition}/proposition/confidentialite", ['id' => $hdr->getId()], [], true); ?>"
                            class="btn btn-primary action ajax-modal"
                            data-event="edition-informations"
                    >
                        <span class="icon icon-plus"></span>
                        Renseigner un huis clos et/ou une confidentialité
                    </a>
                <?php endif; ?>

                <?php if ($proposition->getConfidentialite()): ?>
                    <div class="alert alert-warning">
                        <span class="fas fa-exclamation-triangle"> </span>
                        Afin de réaliser une demande de confidentialité, un accord doit au préalable être rempli :
                        <a href="<?php echo $FORMULAIRE_DEMANDE_CONFIDENTIALITE; ?>">demande d'accord de confidentialité</a>.
                    </div>
                <?php endif; ?>
            </div>
        <?php echo $this->horodatagesParType($proposition, HorodatageService::TYPE_MODIFICATION, "Informations complémentaires"); ?>
    </div>
</div>