<?php

use Application\Entity\Db\Acteur;
use Application\Entity\Db\Individu;
use Application\Entity\Db\These;
use Soutenance\Entity\Membre;
use UnicaenApp\Form\Element\SearchAndSelect;

/**
 * @var These $these
 * @var Membre $membre
 * @var Acteur $acteur
 * @var string $title
 */

$membreNom = $membre->getDenomination();

$this->headTitle($title);
?>
<h1 class="page-header">
    <?php echo $title; ?>
</h1>

<div class="panel panel-info">
    <div class="panel-heading">
        Informations fournies lors de la consitution du jury de thèse
    </div>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>Dénomination</dt>           <dd> <?php echo $membre->getDenomination(); ?> </dd>
            <dt>Qualité</dt>                <dd> <?php echo $membre->getQualite()->getLibelle(); ?> </dd>
            <dt>Établissement</dt>          <dd> <?php echo $membre->getEtablissement(); ?> </dd>
            <dt>Adresse électronique</dt>   <dd> <?php echo $membre->getEmail(); ?></dd>
        </dl>
    </div>
</div>

<h2> Recherche dans les acteurs SyGAL</h2>


<form method='post' class="form-inline " style="margin-bottom:10px;"
      action="<?php echo $this->url('soutenance/presoutenance/associer-membre-individu', ['these' => $these->getId(), 'membre' => $membre->getId()], [], true);?>"
>
    <?php
    $sas = new SearchAndSelect('individu');
    $sas->setAttribute('placeholder','Recherchez un utilisateur');
    $sas->setAttribute('class', 'individu-finder');
    $sas->setAutocompleteSource($this->url('soutenance/presoutenance/associer-membre-individu/rechercher-acteur', ['these' => $these->getId(), 'membre' => $membre->getId()], [], true));
    echo $this->formControlGroup($sas, 'formSearchAndSelect');
    ?>
    <input type="submit" class="" value="Sélection l'utilisateur"/>
</form>

<?php if($acteur): ?>
    <div class="panel panel-info">
        <div class="panel-heading">
            Informations sur l'acteur SyGAL sélectionné
        </div>
        <div class="panel-body">
            <dl class="dl-horizontal">
                <dt>Dénomination</dt>           <dd> <?php echo $acteur->getIndividu()->getNomComplet(false, false, false,true,false); ?> </dd>
                <dt>Qualité</dt>                <dd> <?php echo $acteur->getQualite(); ?> </dd>
                <dt>Établissement</dt>          <dd> <?php echo $acteur->getEtablissement(); ?> </dd>
                <dt>Adresse électronique</dt>   <dd> <?php echo $acteur->getIndividu()->getEmail(); ?></dd>
            </dl>
        </div>
    </div>

<p>
En cliquant sur ce bouton le membre renseigné lors de la composition du jury sera associé à l'acteur SyGAL sélectionné.
</p>

<a href="<?php echo $this->url('soutenance/presoutenance/associer-membre-individu/enregistrer', ['these' => $these->getId(), 'membre' => $membre->getId(), 'acteur' => $acteur->getId()], [], true);?>"
   class="btn btn-primary pull-right"
>
    <span class="glyphicon glyphicon-link"></span>
    Associer cet acteur au membre de jury
</a>
<?php endif; ?>
