<?php

use Acteur\Entity\Db\ActeurThese;
use HDR\Entity\Db\HDR;
use These\Entity\Db\These;
use Soutenance\Entity\Membre;

/**
 * @see \Soutenance\Controller\PresoutenanceController::associerJuryAction()
 * @var ActeurThese[] $acteurs
 * @var Membre $membre
 * @var These|HDR $entity
 * @var string $typeProposition
 */

?>

<p class="lead">
    Associer <?php echo $membre->getDenomination() ?> à un acteur enregistré dans SyGAL
</p>
<form method="post" action="<?php echo $this->url("soutenance_{$typeProposition}/presoutenance/associer-jury", ['id' => $entity->getId(), 'membre' => $membre->getId()], [], true); ?>">
    <select name="acteur" class="form-control">
        <option value="">Sélectionner un membre du jury ... </option>
        <?php foreach($acteurs as $acteur) : ?>
            <option value="<?php echo $acteur->getId(); ?>">
                <span class="badge bg-secondary"> <?php echo $acteur->getRole()->getLibelle(); ?> </span>
                <?php echo $acteur->getIndividu()->getNomComplet(); ?>
                <?php echo $acteur->getLibelleQualite(); ?>
                <?php echo ($acteur->getEtablissement())?$acteur->getEtablissement()->getStructure()->getLibelle():"Établissement inconnu"; ?>
            </option>
        <?php endforeach; ?>
    </select>
    <button type="submit" name="submit" class="btn btn-primary" value=""><span class="fas fa-link"></span>Associer</button>
</form>