<?php

/**
 * @var \Application\Entity\Db\These $these
 * @var \Application\Entity\Db\Validation $validationBDD
 */

$this->headTitle('Préparation de la soutenance de '.$these->getDoctorant()->getIndividu());
?>

<h1 class="page-header">
    Préparation de la soutenance
    <small><?php echo $this->partial('application/these/partial/titre') ?></small>
</h1>

<?php if ($validationBDD) : ?>
    <!-- DATE DE RENDU DE RAPPORT ----------------------------------------------------------------------------------------->
    <?php echo $this->partial('soutenance/presoutenance/partial/date-de-retour'); ?>

    <!-- MEMBRES DU JURY ET PERSOPASS ------------------------------------------------------------------------------------->
    <?php echo $this->partial('soutenance/presoutenance/partial/association-jury'); ?>

    <!-- ENGAGEMENT IMPARTIALITE------------------------------------------------------------------------------------------->
    <?php echo $this->partial('soutenance/presoutenance/partial/engagement-impartialite'); ?>

    <!-- AVIS SOUTENANCE -------------------------------------------------------------------------------------------------->
    <?php echo $this->partial('soutenance/presoutenance/partial/avis-soutenance'); ?>
<?php else : ?>
    <p class="lead">
        Vous ne pouvez commencer les démarches de présouteances qu'une fois toutes les validations obtenues.
    </p>
<?php endif; ?>

<script>
    $(function() {
        $("body").on("modification-date-rendu-rapport", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>