<?php

/**
 * @see \Formation\Service\Exporter\Convocation\AttestationExporter;
 * @var Inscription $inscription
 * @var string[] $logos
 * @var float $presences
 * @var string $signature
 */

use Application\Entity\Db\Individu;
use Formation\Entity\Db\Inscription;
use Formation\Entity\Db\Seance;

$session = $inscription->getSession();
$doctorant = $inscription->getDoctorant();

$libelle = $session->getFormation()->getLibelle();
$denomination = $doctorant->getIndividu()->getNomComplet(false, false,false,true);
$responsable = null;
if ($individu = $session->getResponsable()) {
    $nom = $individu->getNomComplet(false, false,false,true);
    $responsable = $nom;
}

$duree = $session->getDuree();
$debut = $session->getDateDebut()->format("d/m/Y");
$fin = $session->getDateFin()->format("d/m/Y");
$periode = "Période non précisé";
if ($debut !== null AND $fin !== null) {
    if ($debut === $fin) $periode = $debut;
    else $periode = $debut. " au " .$fin;
}

?>

<?php if  (isset($logos['comue']))  : ?>
    <div style="width:25%; float:left; position:absolute; top: 20px; left: 20px">
        <?php if ($logos['comue'] !== null): ?>
            <img src="<?php echo $logos['comue']; ?>" alt="Logo de la COMUE" />
        <?php else : ?>
            <span style='background-color:red;'>
                    Logo du site manquant
            </span>
        <?php endif; ?>
    </div>
    <div style="width:25%; float:right; position:absolute; top: 20px; right: 20px">
        <?php if ($logos['site'] !== null): ?>
            <img src="<?php echo $logos['site']; ?>" alt="Logo du site de formation" />
        <?php else : ?>
            <span style='background-color:red;'>
                Logo du site manquant
            </span>
        <?php endif; ?>
    </div>
<?php else : ?>
<div style="width:25%; float:left; position:absolute; top: 20px; left: 20px">
    <?php if ($logos['site'] !== null): ?>
        <img src="<?php echo $logos['site']; ?>" alt="Logo du site de formation" />
    <?php else : ?>
        <span style='background-color:red;'>
            Logo du site manquant
        </span>
    <?php endif; ?>
</div>
<?php endif; ?>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<h1>Attestation de formation
    <br/>
    <?php echo $libelle; ?>
</h1>

<p>
Bonjour ,
</p>
<p>
    Je,
    <?php
    if ($individu === null) $individu = new Individu();
    switch($individu->getCivilite()) {
        case "M." :
            echo "soussigné,";
            break;
        case "Mme" :
            echo "soussignée,";
            break;
        default :
            echo "soussigné&middot;e,";
            break;
    }
    ?>
    certifie que <strong><?php echo $denomination; ?></strong> a participé à la formation <span class="formation"><?php echo $libelle; ?></span>
    qui s'est déroulee sur la période du <?php echo $periode; ?> (Durée :  <?php echo $duree; ?> heures).
</p>
<p>
    <?php echo $denomination; ?> a suivi <?php echo $presences; ?> heure<?php if ($presences>1) echo "s";?> de formation.</p>

<p style="text-align: right;">
    <?php
        switch($individu->getCivilite()) {
            case "M." :
                echo "Le";
                break;
            case "Mme" :
                echo "La";
                break;
            default :
                echo "Le&middot;a";
                break;
        }
    ?>
    responsable du module <br/>
    <?php echo $responsable; ?>

    <img id="logo" style="background-color: white; max-width: 50%;"
         src="data:image/*;base64,<?php echo base64_encode($signature); ?>"/>
</p>



<p>
</p>

<style>
    span.formation {
        font-weight: bold;
    }
</style>


