<?php
/**
 * @var PhpRenderer $this
 * @var $fieldset
 * @var $fieldsetCharteDoctoratSignee
 * @var array $documents
 * @var AdmissionValidation $validation_charte_doctorat
 * @var string $returnUrl
 * @var boolean $showActionButtons
 * @var ConventionFormationDoctorale $conventionFormationDoctorale
 * @var Admission $admission
 * @var array $conventionFormationDoctoraleOperations
 * @var boolean $isOperationAllowedByRole
 * @var Role $role
 */

use Admission\Entity\Db\Admission;
use Admission\Entity\Db\AdmissionValidation;
use Admission\Entity\Db\ConventionFormationDoctorale;
use Admission\Entity\Db\Etat;
use Admission\Entity\Db\Inscription;
use Admission\Provider\Privilege\AdmissionPrivileges;
use Application\Entity\Db\Role;
use Application\View\Renderer\PhpRenderer;
use Fichier\Entity\Db\NatureFichier;
use Individu\Entity\Db\Individu;

$canTelechargerDocument =
    $this->isAllowed(AdmissionPrivileges::getResourceId(AdmissionPrivileges::ADMISSION_TELECHARGER_TOUT_DOCUMENT)) ||
    $this->isAllowed(AdmissionPrivileges::getResourceId(AdmissionPrivileges::ADMISSION_TELECHARGER_SON_DOCUMENT));

$canAccederConventionFormationDoctorale = $this->isAllowed(AdmissionPrivileges::getResourceId(AdmissionPrivileges::ADMISSION_CONVENTION_FORMATION_MODIFIER));
$canGenererConventionFormationDoctorale = isset($conventionFormationDoctorale) && $this->isAllowed($conventionFormationDoctorale, AdmissionPrivileges::ADMISSION_CONVENTION_FORMATION_GENERER);

/** @var Inscription $inscription */
$inscription = isset($admission) && $admission->getInscription()->first() ? $admission->getInscription()->first() : null;
/** @var Individu $individu */
$individu = $admission?->getIndividu()->getId();

$natureFichier = $fieldset->getAttribute('id');
$enCours = isset($admission) && $admission->getEtat()->getCode() === Etat::CODE_EN_COURS_SAISIE;
?>

<div class="row subfield">
    <div class="col-lg-3 col-sm-12 filename-label">
        <?php
            echo $this->formlabel($fieldset);
            if($natureFichier === NatureFichier::CODE_ADMISSION_CONVENTION && $enCours && $role->getRoleId() === Role::ROLE_ID_ADMISSION_CANDIDAT): ?>
                <span class="icon icon-information admission-info-bulle" data-toggle="tooltip">
                    <span class="tooltip-text">Merci de remplir ce formulaire en collaboration avec votre direction de thèse.</span>
                </span>
            <?php endif; ?>
    </div>
    <div class="col-lg-9 col-sm-12">
        <div class="row detail-file-container">
            <?php if($natureFichier === NatureFichier::CODE_ADMISSION_CHARTE_DOCTORAT): ?>
                <div class="col-lg-12 upload-file">
                   <?php if($inscription && $inscription->getEtablissementInscription() === null): ?>
                       <a class="btn aucune-charte-doctorale-associee-btn" data-toggle="tooltip" title="Veuillez renseigner un établissement d'inscription (à l'étape 2 du formulaire)">
                           <span class="icon icon-warning"></span>
                           Aucune charte doctorale associée au dossier
                       </a>
                   <?php elseif($validation_charte_doctorat->getId() === null): ?>
                       <a class="btn access-charte-doctorat-btn required">Lire et valider la charte du doctorat</a>
                   <?php else: ?>
                       <a class="btn btn-primary access-charte-doctorat-btn">Lire la charte du doctorat</a>
                   <?php endif;
                   echo $this->partial('admission/admission/partial/document/modal/charte', [
                       'documents' => $documents,
                       'validation_charte_doctorat' => $validation_charte_doctorat,
                       'admission' => $admission,
                       'fieldsetCharteDoctoratSignee' => $fieldsetCharteDoctoratSignee,
                       'canTelechargerDocument' => $canTelechargerDocument,
                       'fieldset' => $fieldset,
                       'returnUrl' => $returnUrl,
                       'isOperationAllowedByRole' => $isOperationAllowedByRole,
                       'role' => $role
                   ]); ?>
                </div>
            <?php elseif ($natureFichier === NatureFichier::CODE_ADMISSION_CONVENTION): ?>
                <div class="col-lg-12 upload-file">
                    <?php if ($canAccederConventionFormationDoctorale && $enCours):
                        $nameRoute = $conventionFormationDoctorale ? 'admission/modifier-convention-formation' : 'admission/ajouter-convention-formation';
                        $classButton = $canGenererConventionFormationDoctorale ? "" : "required"; ?>
                        <a href="<?php echo $this->url($nameRoute, ['admission' => $admission->getId()], [], true) ?>"
                           class="btn btn-primary access-conv-form-doct-btn <?=$classButton?>"
                           title="Accéder à la convention de formation doctorale">Remplir la convention de formation doctorale</a>
                    <?php endif;

                    if ($canGenererConventionFormationDoctorale): ?>
                        <a class="btn btn-primary access-conv-form-doct-btn">Lire la convention de formation doctorale</a>
                        <?php echo $this->partial('admission/admission/partial/document/modal/convention', [
                            'documents' => $documents,
                            'conventionFormationDoctoraleOperations' => $conventionFormationDoctoraleOperations,
                            'admission' => $admission,
                            'canTelechargerDocument' => $canTelechargerDocument,
                            'natureFichier' => $natureFichier,
                            'conventionFormationDoctorale' => $conventionFormationDoctorale,
                            'fieldset' => $fieldset,
                            'returnUrl' => $returnUrl,
                            'isOperationAllowedByRole' => $isOperationAllowedByRole,
                            'role' => $role
                        ]); ?>
                    <?php endif ?>
                </div>
            <?php else: ?>
                <div class="col-lg-5 upload-file">
                    <?php echo $this->formfile($fieldset) ?>
                </div>
                <?php if(array_key_exists($natureFichier, $documents)): ?>
                    <div class="col-lg-3 date-televersement-container">
                        <p>Téléversé le
                            <?php
                            echo $documents[$natureFichier]['televersement'];
                            ?>
                        </p>
                    </div>
                    <?php if($canTelechargerDocument): ?>
                        <div class="col-lg-1 action-file-container">
                            <a href="<?php echo $this->url('admission/telecharger-document',['individu'=>$individu,'codeNatureFichier' => $natureFichier], [],true) ?>"
                               class="icon icon-download iconly"
                               title="Télécharger ?"></a>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </div>
</div>